### ISSUE TITLE
Transitive world?

### ISSUE THREAD

**Issue by Hansonaplane** [NuGet/docs.microsoft.com-nuget#1001]
What exactly is meant by "transitive world" in the sentence "Traditional NuGet packages support a set of features that are not carried over to the transitive world."?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 91757e7f-eaee-8494-942f-4364e19cc3d0
* Version Independent ID: 8e31aa7f-fb80-56cf-7261-5cb9440218b8
* Content: [project.json impact on NuGet package authors](https://docs.microsoft.com/en-us/nuget/archive/project-json-impact)
* Content Source: [docs/archive/project-json-impact.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/master/docs/archive/project-json-impact.md)
* Product: **nuget**
* GitHub Login: @karann-msft
* Microsoft Alias: **karann**

**Comment by karann-msft** [comment]
Quoting [Dependency resolution with PackageReference](https://docs.microsoft.com/en-us/nuget/consume-packages/dependency-resolution#dependency-resolution-with-packagereference)
> When installing packages into projects using the PackageReference format, NuGet adds references to a flat package graph in the appropriate file and resolves conflicts ahead of time. This process is referred to as transitive restore.

If a project uses the PackageReference format to reference NuGet packages, it is said to be in the "transitive world"
