### ISSUE TITLE
Info for .Net Core apps?

### ISSUE THREAD

**Issue by ColbyRingeisen** [NuGet/docs.microsoft.com-nuget#1002]
There's a note on the 'Creating a package' page that says "This topic applies to project types other than .NET Core projects using Visual Studio 2017 and NuGet 4.0+."  That note then says to reference two other pages for information on .NET Core projects.  However, neither of those pages have anything specific to .NET Core projects either.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f35f4267-e5e3-ddcf-d3e4-479fb233ce9f
* Version Independent ID: 6d49d66f-f777-7e44-3a45-723e3ad09a59
* Content: [How to create a NuGet package](https://docs.microsoft.com/en-us/nuget/create-packages/creating-a-package)
* Content Source: [docs/create-packages/Creating-a-Package.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/master/docs/create-packages/Creating-a-Package.md)
* Product: **nuget**
* GitHub Login: @karann-msft
* Microsoft Alias: **karann**

**Comment by karann-msft** [comment]
A .NET Standard library or a .NET Core library are both SDK-style projects and the steps to create a NuGet package are similar. The only difference is you'd start with File > New > Project, expand the Visual C# > .NET Core node, select the "Class Library (.NET Core)" template.

Let us know if you run into any issues.

**Comment by ColbyRingeisen** [comment]
NOT the point of my post at all. There's a "Note" on https://github.com/NuGet/docs.microsoft.com-nuget/blob/master/docs/create-packages/Creating-a-Package.md that points out the specified documentation doesn't apply to .Net Core projects then refers the reader to other documentation which also doesn't cover the topic. Fix the docs.
