### ISSUE TITLE
There is a "NuGetFallbackFolder" does not show up in the `-list`

### ISSUE THREAD

**Issue by StingyJack** [NuGet/docs.microsoft.com-nuget#1003]
Is that a folder for something other than these global packages and caches?  It really sounds like it should be one. 

Locally its at %programfiles%\dotnet\sdk\NuGetFallbackFolder and is chewing up 1.3 GB of space with packages that look unnecessary or are already present in the global caches named here. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 71b49477-cafa-d7d4-76fe-83aff43a3f47
* Version Independent ID: 68d7a416-1397-8cf3-bead-e3cd328aca48
* Content: [How to manage the global packages, cache, temp folders in NuGet](https://docs.microsoft.com/en-us/nuget/consume-packages/managing-the-global-packages-and-cache-folders)
* Content Source: [docs/consume-packages/managing-the-global-packages-and-cache-folders.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/master/docs/consume-packages/managing-the-global-packages-and-cache-folders.md)
* Product: **nuget**
* GitHub Login: @karann-msft
* Microsoft Alias: **karann**

**Comment by anangaur** [comment]
The folder typically contains the expanded packages needed for creating new projects from the VS templates. These packages (+versions) ideally shouldn't be there in the global packages folder.

**Comment by nkolev92** [comment]
It should be thought of as part of the VS/SDK installation, rather than a dependency that NuGet brings.

**Comment by StingyJack** [comment]
Its not one of [these](https://github.com/NuGet/Home/wiki/%5BSpec%5D-Fallback-package-folders) then?

**Comment by nkolev92** [comment]
@StingyJack 
It is one of those. 

But that's a feature that NuGet itself enables, that other NuGet consumers cna use to optimize their offline and CI scenarios. 

NuGet itself does not create fallback folders.

**Comment by StingyJack** [comment]
They should have called that folder the "Project System Dependent Nuget Packages" and not "NugetFallbackFolder". I do no .netcore (no reason to do so other than forced obsolescence) or .netstandard even (tried it, TFS 2015 build hates it), but through some chain of dependencies the VS installer needed to put it there, useless, taking up space. I'll set the compression bit and be done with it. Thanks for the info @nkolev92
