### ISSUE TITLE
Document the changes in https://github.com/NuGet/NuGet.Client/pull/2297

### ISSUE THREAD

**Issue by nkolev92** [NuGet/docs.microsoft.com-nuget#1007]
We need to document the new authentication types flag. 

More info https://github.com/NuGet/NuGet.Client/pull/2297

This needs done before 4.9 or whenever that PR ships. 

//cc @rrelyea @NuGet/nuget-client @jmyersmsft

**Comment by rrelyea** [comment]
replaced by #1283
