### ISSUE TITLE
Documentation appears to need updates

### ISSUE THREAD

**Issue by LisandroSu** [NuGet/docs.microsoft.com-nuget#1011]
@taori commented on [Sat Aug 11 2018](https://github.com/NuGet/docs.microsoft.com-nuget.de-de/issues/3)

There is no indication about "symbolUrl" - However it is available for package configuration now. I've seen how it is shown during Connect/Build 2018. There should be some samples on how it works / how to get it working as intendend.

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: 06a19d7d-253d-f17f-6421-624c9867473d
* Version Independent ID: cc37eb17-f715-080c-7bfc-9eae868d50ba
* Content: [NuSpec-Dateireferenz für NuGet](https://docs.microsoft.com/de-de/nuget/reference/nuspec)
* Content Source: [docs/reference/nuspec.md](https://github.com/NuGet/docs.microsoft.com-nuget.de-de/blob/live/docs/reference/nuspec.md)
* GitHub Login: @karann-msft
* Microsoft Alias: **karann**

**Comment by LisandroSu** [comment]
Hi team,

Please check on this request for more information.

Thanks!

**Comment by karann-msft** [comment]
That work is still underway. You can read the spec here - https://github.com/NuGet/Home/wiki/Symbols-Package-Upload-Workflow

And a related blogpost here - https://blog.nuget.org/20180501/Welcoming-SymbolSource-to-Dot-Net-Foundation.html

**Comment by taori** [comment]
@karann-msft To be more specific. My concern was the lack of documentation regarding the <symbolUrl> tag in a csproj-file. Your links do not mention this tag.
