### ISSUE TITLE
The left sidebar on the docs page was truncated

### ISSUE THREAD

**Issue by mishra14** [NuGet/docs.microsoft.com-nuget#1015]
The left sidebar on the docs page was truncated on my browser - 

![image](https://user-images.githubusercontent.com/10507120/44177008-f7f46280-a0a0-11e8-8009-b6240e4f4da4.png)

**Comment by mishra14** [comment]
cc: @anangaur

**Comment by karann-msft** [comment]
@mishra14 closing this as it can't be repro'ed. Do provide more info or maybe a screen capture to better explain the issue.
