### ISSUE TITLE
Nuget keep asking for proxy credentials when running install package command line

### ISSUE THREAD

**Issue by jhenyffer** [NuGet/docs.microsoft.com-nuget#1018]
Hello, is there a way to run nuget.exe install command with the credentials setted in the command? 
What I need is to install the packages without having to provide the credentials manually.

I have already tryied to set the credentials in Nuget.config, it worksed for some time, but all of a sudden it stoped working.

The thing is that I am using proxy, I have done the proxy configuration on NuGet.config, but nuget keeps asking for the credentials.

Can you plese advise me? I have spent a lot of time on this already...

Thanks!

**Comment by karann-msft** [comment]
Issue moved to [NuGet/Home #7225](https://github.com/NuGet/Home/issues/7225) via [**ZenHub**](https://www.zenhub.com/)
