### ISSUE TITLE
How we can create PWA site using CSOM code with use of new Microsoft.ProjectServer.Client.dll [16.1.7414.1200]?

### ISSUE THREAD

**Issue by Shraddhasv** [NuGet/docs.microsoft.com-nuget#1021]
We have product which is using Microsoft.ProjectServer.Client.dll to create project sites with PWA template.
Last week I have updated nuget package 'SharePointPnPCoreOnline'. I want to use new Modern templates[Team site/communication site].
Because of this update Microsoft.ProjectServer.Client.dll version changed from 15.0.4420.1017 to 16.1.7414.1200
Now I am not able to create Project site. This is major thing for us.
Can anyone help me, how we can create PWA site using CSOM code with use of new Microsoft.ProjectServer.Client.dll.
Thanks in advance.
Following last line throwing exception : "The stub for the type with id "{154360b4-899f-4237-b0ed-3e35f014c748}" was not found. The specified server may not support the APIs used in this operation."

var prjContext = new ProjectContext(urlName);
prjContext.Credentials = clientContext.Credentials;
var projTypeName = "Enterprise-Project";
var epts = prjContext.EnterpriseProjectTypes;
prjContext.Load(epts, ept => ept.Include(pt => pt.Name, pt => pt.Id).Where(pt => pt.Name == projTypeName));
prjContext.ExecuteQuery();

**Comment by karann-msft** [comment]
@Shraddhasv - we can't support individual packages in this forum. Please contact the package owners using this link https://www.nuget.org/packages/SharePointPnPCoreOnline/3.0.1808/ContactOwners
