### ISSUE TITLE
Misleading information about "readme.txt" for .NET Core Library

### ISSUE THREAD

**Issue by mbedded** [NuGet/docs.microsoft.com-nuget#1027]
I created a .NET Standard project and enabled "create nuget package". When i add a "readme.txt" into the root file of this project and publish the package, my target project receives a "readme.txt" file in the root of the project.
Unfortunately the readme is not opened by visual studio..

Is this a bug by NuGet or has VS2017 15.8.1 some internal changes? I want to open a readme when the developer updates or installs my package.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f35f4267-e5e3-ddcf-d3e4-479fb233ce9f
* Version Independent ID: 6d49d66f-f777-7e44-3a45-723e3ad09a59
* Content: [How to create a NuGet package](https://docs.microsoft.com/en-us/nuget/create-packages/creating-a-package)
* Content Source: [docs/create-packages/Creating-a-Package.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/master/docs/create-packages/Creating-a-Package.md)
* Product: **nuget**
* GitHub Login: @karann-msft
* Microsoft Alias: **karann**

**Comment by karann-msft** [comment]
You have to put the readme.txt at the root of the "package", not the project. Putting a file at the project root does not result in that file being packed in the nuget package.

Here's what you can do:
Open the csproj file and add the following to it:

` <ItemGroup>
    <Content Include="readme.txt">
      <Pack>true</Pack>
      <PackagePath>\</PackagePath>
    </Content>
  </ItemGroup>`

Next time you build, the readme.txt will be packaged and placed at the package root.

**Comment by mbedded** [comment]
Hello Karan, thanks for the information :) With this update it is possible to include the file into the package which is automatically displayed by VisualStudio.

I was stumbling because of the following passage:
https://docs.microsoft.com/en-us/nuget/create-packages/creating-a-package#from-a-convention-based-working-directory

> (root) | Location for readme.txt | Visual Studio displays a readme.txt file in the package root when the package is installed.
> -- | -- | --
> 

Here it says i have only to add this file and thats it. Have i done something wrong? Because in my Solution i have ProjectA and ProjectB which are packed as individual NuGet-Packages.
So it was in the (root) of ProjectA (which created his own ProjectA.nupkg).

Is this a missing convention in Net Core yet? Based on your csproj-snipped it works like a charm. From my point of view this ticket may be closed. Maybe the documentation should be extended for Net Core libraries, shouldn't it?

**Comment by karann-msft** [comment]
@mbedded - I am glad that worked for you. I have created a PR to update the relevant docs. Thanks for the feedback!
