### ISSUE TITLE
Push your packages to http://[your server]/nuget instead of /api/v2/package

### ISSUE THREAD

**Issue by OndrejValenta** [NuGet/docs.microsoft.com-nuget#1038]
You will always get 404, I was fighting with this for several hours.

So for example: nuget.exe push "KeenMate.FluentlySharePoint.0.5.nupkg" [api key] -Source http[s]://[your server]/nuget

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2fb1dbf3-8883-dad4-c9ab-e518b6278c2b
* Version Independent ID: 7dbbe467-03e8-abf5-1652-4082b0fd3a42
* Content: [Using NuGet.Server to Host NuGet Feeds](https://docs.microsoft.com/en-us/nuget/hosting-packages/nuget-server)
* Content Source: [docs/hosting-packages/NuGet-Server.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/master/docs/hosting-packages/NuGet-Server.md)
* Product: **nuget**
* GitHub Login: @karann-msft
* Microsoft Alias: **karann**

**Comment by AlexejLiebenthal** [comment]
@94151
Step 7 has a deprecated image.
In step 3 the user installs NuGet.Server -Version 3.1.2
In the image in step 3 shows instead an instance with NuGet.Server -Version 2.11.3 is running
In 3.1.2 Source is http[s]://[your server]/nuget instead of http[s]://[your server]/api/v2/package

**Comment by karann-msft** [comment]
Docs day - test the example and update.

**Comment by joelverhagen** [comment]
Hello everyone, I have updated the document so it matches the latest package version. Also, I added this blurb:

> Starting with NuGet.Server 3.0.0, the URL for pushing packages was change to `http://<domain>/nuget`. Prior to the 3.0.0 release, the push URL was `http://<domain>/api/v2/package`.
>
> With NuGet 3.2.1 and newer, this legacy URL `/api/v2/package` is enabled in addition to `/nuget`` by default via `enableLegacyPushRoute: true` option in your startup config (NuGetODataConfig.cs by default). Note that this feature does not work when multiple feeds are hosted in the same project.
