### ISSUE TITLE
Great document. How do I make nuget to add packages to application folder?

### ISSUE THREAD

**Issue by kudlatiger** [NuGet/docs.microsoft.com-nuget#1042]
In some cases, I do not want visual studio to refer the global nuget folder. In such cases How do I make nuget to add packages to application folder?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 71b49477-cafa-d7d4-76fe-83aff43a3f47
* Version Independent ID: 68d7a416-1397-8cf3-bead-e3cd328aca48
* Content: [How to manage the global packages, cache, temp folders in NuGet](https://docs.microsoft.com/en-us/nuget/consume-packages/managing-the-global-packages-and-cache-folders)
* Content Source: [docs/consume-packages/managing-the-global-packages-and-cache-folders.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/master/docs/consume-packages/managing-the-global-packages-and-cache-folders.md)
* Product: **nuget**
* GitHub Login: @karann-msft
* Microsoft Alias: **karann**

**Comment by rrelyea** [comment]
When using Packages.Config, it uses the Solution package folder technique.
When using PackageReference, NuGet uses a global package folder.

As mentioned above, it is possible to override the  location of the global package folder via:
"Override using the NUGET_PACKAGES environment variable, the globalPackagesFolder or repositoryPath configuration settings (when using PackageReference and packages.config, respectively), or the RestorePackagesPath MSBuild property (MSBuild only). The environment variable takes precedence over the configuration setting."
