### ISSUE TITLE
Need documentation on legacy API key expiration

### ISSUE THREAD

**Issue by joelverhagen** [NuGet/docs.microsoft.com-nuget#1050]
Today, this is only in a blog post:
https://blog.nuget.org/20170202/introducing-scoped-api-keys.html#faqs

Ideally we document other API key information as well.

When these docs are done, update https://aka.ms/nugetlegacyapikeys.

**Comment by Mikejo5000** [comment]
Doc on API keys is here:
https://docs.microsoft.com/en-us/nuget/nuget-org/scoped-api-keys
