### ISSUE TITLE
Wrong path for contentFiles

### ISSUE THREAD

**Issue by andrekoehler** [NuGet/docs.microsoft.com-nuget#1051]
The documentation for the &lt;contentFiles&gt;&lt;files include&gt; attribute states "The path is relative to the .nuspec file". This is wrong. The example section shows it correctly as being relative to the contentFiles folder: https://docs.microsoft.com/en-us/nuget/reference/nuspec#example-contentfiles-section

I tried including the contentFiles folder in the include path but that results in the files being found but the build action is overridden as "compile with C# compiler".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 06a19d7d-253d-f17f-6421-624c9867473d
* Version Independent ID: cc37eb17-f715-080c-7bfc-9eae868d50ba
* Content: [.nuspec File Reference for NuGet](https://docs.microsoft.com/en-us/nuget/reference/nuspec#using-the-contentfiles-element-for-content-files)
* Content Source: [docs/reference/nuspec.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/master/docs/reference/nuspec.md)
* Product: **nuget**
* GitHub Login: @karann-msft
* Microsoft Alias: **karann**

**Comment by Mikejo5000** [comment]
Updating doc
