### ISSUE TITLE
What is the “after imports” target?

### ISSUE THREAD

**Issue by binki** [NuGet/docs.microsoft.com-nuget#1052]
Please explain what the “after imports” target is or link to its documentation. Searching that doesn’t seem to yield anything.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e7a0653a-ec3b-3b60-ae77-a51fedf1966e
* Version Independent ID: 90a503d7-6d0f-7b9e-4c2c-45f9a9705ac7
* Content: [NuGet Error NU1105](https://docs.microsoft.com/en-us/nuget/reference/errors-and-warnings/nu1105)
* Content Source: [docs/reference/errors-and-warnings/NU1105.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/master/docs/reference/errors-and-warnings/NU1105.md)
* Product: **nuget**
* GitHub Login: @zhili1208
* Microsoft Alias: **lzhi**

**Comment by Mikejo5000** [comment]
Looks like there is no explicit "after imports" target. This doc appears relevant though:
https://docs.microsoft.com/en-us/visualstudio/msbuild/customize-your-build?view=vs-2019

**Comment by binki** [comment]
.

**Comment by mot256** [comment]
reopen?

**Comment by binki** [comment]
@mot256 It may be less obvious on docs.microsoft.com, but this issue was reopened due to it still being a relevant issue.
