### ISSUE TITLE
Link to the MSCredProvider plugin is broken.

### ISSUE THREAD

**Issue by nizmow** [NuGet/docs.microsoft.com-nuget#1053]
"A sample implementation can be found in MSCredProvider plugin."

The hyperlink in that sentence leads to a 404.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dad5f10a-14c8-d875-47d1-323cacbd221f
* Version Independent ID: d71e35dd-93ea-9ab4-9b0a-4b1f8fa13f22
* Content: [NuGet cross platform authentication plugin](https://docs.microsoft.com/en-us/nuget/reference/extensibility/nuget-cross-platform-authentication-plugin)
* Content Source: [docs/reference/extensibility/NuGet-Cross-Platform-Authentication-Plugin.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/master/docs/reference/extensibility/NuGet-Cross-Platform-Authentication-Plugin.md)
* Product: **nuget**
* GitHub Login: @nkolev92
* Microsoft Alias: **nikolev**

**Comment by nkolev92** [comment]
@nizmow 

Thanks for the heads up. 

I will fix that soon.

**Comment by nkolev92** [comment]
Fixed in https://github.com/NuGet/docs.microsoft.com-nuget/commit/adcbb7170b3716c6ce90422608baa8146c40440c
