### ISSUE TITLE
Example error not right

### ISSUE THREAD

**Issue by lukepuplett** [NuGet/docs.microsoft.com-nuget#1062]
The sample error above doesn't match what I see. Here's mine.

Detected package downgrade: Microsoft.NETCore.App from 2.1.4 to 2.1.0. Reference the package directly from the project to select a different version. 
 Biz.Cart.Microservice.Tests.HttpAutomation -&gt; Biz.Cart -&gt; Microsoft.NETCore.App (&gt;= 2.1.4) 
 Biz.Cart.Microservice.Tests.HttpAutomation -&gt; Microsoft.NETCore.App (&gt;= 2.1.0)

The "root" of the dependency chain is the project with the problem, but your example shows PackageA and PackageC. I suspect you've just contrived that error and it doesn't match reality.

There's no version after each dependency in the chain, only the final one and its expressed as a constraint in parentheses.

Sounds like nit-picking but in all honesty its these kinds of arcane errors that block millions of developers from being productive every single day. I've been programming since .NET 1.0 and its the weird errors and ambiguous documentation that kills me.

My Biz.Cart web app project has a package reference to Microsoft.AspNetCore.App (2.1.3), and in the SDK node it has Microsoft.NETCore.App (2.1.4).

I've been staring at this and trying to figure out what the problem is for 3 hours now.

I cannot understand it since my HttpAutomation xUnit test project doesn't even have a package reference to Microsoft.NETCore.App and the SDK node is missing completely for some reason! It also does not have a reference to Microsoft.AspNetCore.App of any version.

Both projects target framework netcoreapp2.1. My test project references my web app project.

"Add a direct reference to the project for the higher version of the package that you want to use."

Do you mean "To the project exhibiting the restore error, add a package reference to the higher version of the package." ?

Seriously, this kind of error is very confusing to think about so a diagram and really dumbed-down explainer would be great, thanks.

Moreover, Microsoft.NETCore.App is that even a package or an SDK? Or maybe its a package, a metapackage, but shows under the SDK node and not under the NuGet node for some design reason.

In which case why when I add a new xUnit project does it have Microsoft.NETCore.App (2.1) and not (2.1.4) like the web app project in the same solution? That seems the be problem.

The problem is that new projects added to the solution set a different SDK version for some reason.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0960d68b-f164-4e7e-5cdb-ad70e6f9de89
* Version Independent ID: 82b4d896-1d52-ce2e-c2ff-f76f4308ac56
* Content: [NuGet Warning NU1605](https://docs.microsoft.com/en-us/nuget/reference/errors-and-warnings/nu1605?f1url=https%3A%2F%2Fmsdn.microsoft.com%2Fquery%2Fdev15.query%3FappId%3DDev15IDEF1%26l%3DEN-US%26k%3Dk(NU1605)%26rd%3Dtrue)
* Content Source: [docs/reference/errors-and-warnings/NU1605.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/master/docs/reference/errors-and-warnings/NU1605.md)
* Product: **nuget**
* GitHub Login: @zhili1208
* Microsoft Alias: **lzhi**

**Comment by lukepuplett** [comment]
It appears to be https://github.com/dotnet/core/issues/1754 

I think adding `<TargetLatestRuntimePatch>true</TargetLatestRuntimePatch>` to the test project with the restore error works.

I think the documentation for this error needs to say something about SDKs or runtime choices. I don't know what exactly because I don't really understand it, but I was troubleshooting my NuGet package references when it was to do with the runtime version choice by NuGet.

Thanks.

**Comment by nirzaf** [comment]
This error is really frustrating and still could not fix it

**Comment by karann-msft** [comment]
Fixed in https://github.com/NuGet/docs.microsoft.com-nuget/pull/1370
