### ISSUE TITLE
Transformations on Json config files

### ISSUE THREAD

**Issue by lisberPontes** [NuGet/docs.microsoft.com-nuget#1063]
Hi,
With recent projects in .NET Core that uses .json as source for config settings, how can we provide 'transformations' within our nuget packages so that they add/update/remove content into current app.config (json format) files ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 40bb9dee-46d6-4064-83e8-ba2e22ac6afe
* Version Independent ID: aac0bbd8-645b-ccf8-bec9-e0d970c8b089
* Content: [Source and config file transformations for NuGet packages](https://docs.microsoft.com/en-us/nuget/create-packages/source-and-config-file-transformations)
* Content Source: [docs/create-packages/Source-and-Config-File-Transformations.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/master/docs/create-packages/Source-and-Config-File-Transformations.md)
* Product: **nuget**
* GitHub Login: @karann-msft
* Microsoft Alias: **karann**

**Comment by rrelyea** [comment]
This question is better placed to the asp.net core or .net core team.
Can you please file it into their repo?

**Comment by aberbegall** [comment]
@lisberPontes, I believe I'm aiming to achieve the same thing. I want generate a Nuget with a default key\values in appsettings.json file that must either replace or add key\values into the target project appsettings.json where is being added that nuget package. But I'm only able to replace the whole file content. 
Did you find a way to achieve it?
