### ISSUE TITLE
Avoid "consume" in cases where the action does not spend the input

### ISSUE THREAD

**Issue by dizzi90** [NuGet/docs.microsoft.com-nuget#1064]
https://www.gnu.org/philosophy/words-to-avoid.en.html#Consume
The word consume is misused throughout the nuget documentation to describe non-destructive use. This is misleading and may cause confusion.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6f32fcb5-8641-9062-83bd-2c8c09aab872
* Version Independent ID: 12404cbd-0105-957e-2875-bb91904fc359
* Content: [Overview and workflow of using NuGet packages](https://docs.microsoft.com/en-us/nuget/consume-packages/overview-and-workflow)
* Content Source: [docs/consume-packages/Overview-and-Workflow.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/master/docs/consume-packages/Overview-and-Workflow.md)
* Product: **nuget**
* GitHub Login: @karann-msft
* Microsoft Alias: **karann**

**Comment by NReilingh** [comment]
As someone not familiar with NuGet particularly, but with package managers in general, the concept of "consuming a package" seems perfectly clear, and perfectly in line with common usage within the context of package management.

I don't think FSF language policing<sup>1</sup> is a good strategy for maintaining docs that are useful and clear to the average user.

<sup>1. From [the page you linked](https://www.gnu.org/philosophy/words-to-avoid.en.html): "Some [of these words] presuppose a viewpoint that we disagree with, and we hope you disagree with it too."</sup>

**Comment by dizzi90** [comment]
> Language policing
😁 No such intention at least not from me.
I think it is imprecise to describe using a package as "eating" that package. It is a poor analogy.
If I eat an apple, I no longer have that apple and nor do you. We are here talking about downloading and using a unit of information. Information is not "spent" or destroyed when used.

**Comment by NReilingh** [comment]
"Consume", like many words in many languages, has more than one meaning. Even "ingest" does not exclusively mean to spend or destroy something by taking it in — it means "to absorb information". "Consume", similarly, is used here with the meaning of "consumer", or "a person who uses something". [Citation: Oxford English Dictionary]

The reason it is more fitting of a word than, say, "copy", or "use", is that it better illustrates the relationship between the person writing the package and the person using it, which is an important mechanic of all package repositories like NPM or the NuGet Gallery. As a package consumer, you use packages that are provided by a package publisher, so the publisher/consumer dynamic is what is being illustrated here.

Anyway, far more relevant here than the FSF's ideo-philosophical "Words to Avoid" document is the [Microsoft Writing Style Guide](https://docs.microsoft.com/en-us/style-guide/welcome/), which dictates the writing style used in all documentation. "Consume" appears exactly twice in the style guide, on [this page](https://docs.microsoft.com/en-us/style-guide/a-z-word-list-term-collections/term-collections/cloud-computing-terms), and in neither case is being used to refer to food or the spending of an input.

https://github.com/MicrosoftDocs/microsoft-style-guide/blob/cd4fa9cc0b451ac4cd73580ce7a38ffea7f0f461/styleguide/a-z-word-list-term-collections/term-collections/cloud-computing-terms.md#L37

**Comment by dizzi90** [comment]
Yes, language is versatile and changes as usage changes.
The association with using up, spending, eating will be invoked.

The publisher-subscriber relationship may well be a better image to invoke, but that would limit the word usage to instances where you stay up to date, which may not be appropriate in all cases.

Perhaps an analogy to book publishing would be best. There you may well have updated versions, but they do not necessarily render older versions obsolete, similarly to software packages.

So instead of "x software consumes y package" you get "x software reads y package" or another formulation for which I am not sufficiently creative to think up on the fly. Read may well be to vague to convey the meaning, but it doesn't occur to me exactly what is lost.

**Comment by dizzi90** [comment]
A note on the FSF document, although it is a little orthogonal to the point I am making.

I am not suggesting that Ms or anyone needs to read their output uncritically. I included the document because it is the document that got me thinking about this word and a few others with a bit more care. I have described RMS as useful in the way a lighthouse is useful. I want to know where he is, but if I am where he is, I might be in trouble.

There are some ideas contained in the discussion that are interesting perspectives to take into account when publishing documentation or other prescriptive texts. The contrast between seeing software as a fungible object versus a published work does seem like a valid distinction to make. And I think developers are more like authors than they are like producers of consumable goods that are used up.

**Comment by zivkan** [comment]
Thanks for the suggestion. I can imagine for non-native English speakers it may be confusing, as looking up the word in a dictionary gives destructive examples as you have mentioned and translating it to their native language is unlikely to help. However, I believe that many native speakers would have heard of examples such as "consume music", or "media consumption", and would probably understand/guess the meaning even if this is the first time they heard consume or consumption being used in reference to  information.

After reading the page you linked, I agree in principal that it would be better to use a verb like "use". However, I believe there is more valuable work to do on the docs. For this reason, I don't imagine this will be changed unless/until we can fix all other docs requests. Particularly since all the pages under the `consume-packages/` directory would need redirects, there would be a reasonable amount of effort in changing everything and testing.

**Comment by zivkan** [comment]
For what it's worth, I just checked the French, Spanish and Italian translations of one instance of consume, and in all three translations, the translators changed the word to their equivalents of "to use" or "utilize". So, the translators appear to understand 😃

**Comment by karann-msft** [comment]
Thanks for the feedback and discussion everyone. We'll stick with "consume".
