### ISSUE TITLE
airtime

### ISSUE THREAD

**Issue by joseph018** [NuGet/docs.microsoft.com-nuget#1069]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d0b2ec4d-76e7-1c04-098c-99ea98676866
* Version Independent ID: 3cb2eaa8-3101-dc2e-b298-5c0d12a830be
* Content: [Service Index, NuGet API](https://docs.microsoft.com/en-us/nuget/api/service-index)
* Content Source: [docs/api/service-index.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/master/docs/api/service-index.md)
* Product: **nuget**
* GitHub Login: @joelverhagen
* Microsoft Alias: **jver**

**Comment by rrelyea** [comment]
this issue has no feedback. closing.
