### ISSUE TITLE
"Implicitly referenced by an SDK" information is not adequate

### ISSUE THREAD

**Issue by Serjster** [NuGet/docs.microsoft.com-nuget#1071]
The information provided for "Implicitly referenced by an SDK" error is not adequate, for example the solution provided talks about the installed SDK, which for me is 2.1.4, but nuget is not letting me update to that version, instead forcing me to stay at 2.1 with the above "Implicitly referenced by an SDK" error showing!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 108d587b-429e-3459-5698-3b40e44f4c3e
* Version Independent ID: 76ad6a3f-4dde-0883-1df9-0f173f0ca7e7
* Content: [NuGet Package Manager UI Reference](https://docs.microsoft.com/en-us/nuget/tools/package-manager-ui#updating-a-package)
* Content Source: [docs/tools/Package-Manager-UI.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/master/docs/tools/Package-Manager-UI.md)
* Product: **nuget**
* GitHub Login: @karann-msft
* Microsoft Alias: **karann**

**Comment by rrelyea** [comment]
@Serjster - please file an issue with the team that owns that SDK. As part of that issue, complain that you feel the need to see the version change to 2.1.4, but you cannot.

One of the things that they could do to help address that issue, is explain things better in the nuget core documentation.

But this isn't a nuget decision....it is that SDK.  (if .net core SDK, please address in the https://github.com/dotnet/sdk repo. if asp.net core, please address here: https://github.com/aspnet/Home)

Thanks, Rob
