### ISSUE TITLE
V3 protocol documentation does not define client behavior for unsupported data

### ISSUE THREAD

**Issue by agr** [NuGet/docs.microsoft.com-nuget#1073]
Right now, V3 protocol documentation does not define an expected client behavior when new properties are introduced in the responses to various queries. While most reasonable implementations would ignore any new properties they do not understand, it would better to explicitly call out that protocol might be extended in the future, and suggest the expected client behavior so it does not break when used with newer server implementations.

**Comment by agr** [comment]
The following change added a paragraph regarding the future-proofing the client: https://github.com/NuGet/docs.microsoft.com-nuget/commit/01f849c1f744eb0e8ba5b88c76288f99b6590c17

Do we need anything else?

**Comment by Mikejo5000** [comment]
Appears to be fixed in #1075
