### ISSUE TITLE
typo

### ISSUE THREAD

**Issue by t-robalt** [NuGet/docs.microsoft.com-nuget#1078]
In the second paragraph: "This project references NuGet package(s) that are missing on this computer"
This error occurs ____ you attempt. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 906d0438-0338-0167-3a38-d213ee187ddb
* Version Independent ID: b558fa0c-f549-1e6a-c2db-fd2e6a2351be
* Content: [Troubleshooting NuGet Package Restore in Visual Studio](https://docs.microsoft.com/en-us/nuget/Consume-Packages/Package-restore-troubleshooting#this-project-references-nuget-packages-that-are-missing-on-this-computer)
* Content Source: [docs/consume-packages/Package-restore-troubleshooting.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/master/docs/consume-packages/Package-restore-troubleshooting.md)
* Product: **nuget**
* GitHub Login: @karann-msft
* Microsoft Alias: **karann**

**Comment by Meikay** [comment]
Can I take this on?

**Comment by karann-msft** [comment]
this has been fixed.
