### ISSUE TITLE
Request: allow queueing of updates and execute in batch

### ISSUE THREAD

**Issue by markchagers** [NuGet/docs.microsoft.com-nuget#1081]
It would be immensely helpful if we could specify a number of packages to update/consolidate and have the packages installed in batch. Currently you have to wait for each package to finish updating before you can specify the next one to update. This is most obvious when consolidating packages in a large solution with many projects.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 108d587b-429e-3459-5698-3b40e44f4c3e
* Version Independent ID: 76ad6a3f-4dde-0883-1df9-0f173f0ca7e7
* Content: [NuGet Package Manager UI Reference](https://docs.microsoft.com/en-us/nuget/tools/package-manager-ui)
* Content Source: [docs/tools/Package-Manager-UI.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/master/docs/tools/Package-Manager-UI.md)
* Product: **nuget**
* GitHub Login: @karann-msft
* Microsoft Alias: **karann**

**Comment by Mikejo5000** [comment]
In VS, in the NuGet Package Manager, that is a limitation, I believe. You can use the Package Manager Console in VS to update and install all packages in a project at once. Restore Packages also supports this in different ways.
