### ISSUE TITLE
I would like to see sample code that would deal with these operations

### ISSUE THREAD

**Issue by asvyat** [NuGet/docs.microsoft.com-nuget#1082]
I would like to see sample C# code that would deal with these operations.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6f5691c1-f008-bbbf-a086-d9e665b5c332
* Version Independent ID: f255cc99-1041-ca5c-d2e5-5981e450a236
* Content: [Push and Delete, NuGet API](https://docs.microsoft.com/en-us/nuget/api/package-publish-resource)
* Content Source: [docs/api/package-publish-resource.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/master/docs/api/package-publish-resource.md)
* Product: **nuget**
* GitHub Login: @joelverhagen
* Microsoft Alias: **jver**

**Comment by joelverhagen** [comment]
Hey @asvyat, what kind of sample code are you looking for? Do you mean a small, concise example with minimal dependencies?

One option would be to look at the official NuGet client code. For example, this is where `nuget.exe push` crafts the HTTP request sent to the server.

https://github.com/NuGet/NuGet.Client/blob/2c7fe4724f81fe6ed3a5c7e1c2abef43c70ef12d/src/NuGet.Core/NuGet.Protocol/Resources/PackageUpdateResource.cs#L361

You'll notice that they use `MultipartFormDataContent` and add the package file stream as the first (and only) entry.
