### ISSUE TITLE
How to uninstall global packages?

### ISSUE THREAD

**Issue by DeveloperLookBook** [NuGet/docs.microsoft.com-nuget#1087]
Pleas ass info about "how to uninstall global packages"?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1462545b-8a98-31aa-1a9b-fc63a6372c29
* Version Independent ID: c40cee3d-3995-f589-5786-42d30d10183b
* Content: [NuGet Uninstall-Package PowerShell Reference](https://docs.microsoft.com/en-us/nuget/tools/ps-ref-uninstall-package)
* Content Source: [docs/tools/ps-ref-uninstall-package.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/master/docs/tools/ps-ref-uninstall-package.md)
* Product: **nuget**
* GitHub Login: @karann-msft
* Microsoft Alias: **karann**

**Comment by karann-msft** [comment]
https://docs.microsoft.com/en-us/dotnet/core/tools/global-tools-how-to-create#remove-the-tool

**Comment by karann-msft** [comment]
https://docs.microsoft.com/en-us/nuget/consume-packages/managing-the-global-packages-and-cache-folders#clearing-local-folders
