### ISSUE TITLE
Extensions whitelist

### ISSUE THREAD

**Issue by nvmkpk** [NuGet/docs.microsoft.com-nuget#1089]
Nothing mentioned about extensions whitelist and 'AllowedOutputExtensionsInPackageBuildOutputFolder' for 'TargetsForTfmSpecificBuildOutput'?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 099102e8-c320-ef50-6821-57519684dc98
* Version Independent ID: 1523dac4-419d-613d-2497-4062f9efd358
* Content: [NuGet pack and restore as MSBuild targets](https://docs.microsoft.com/en-us/nuget/reference/msbuild-targets)
* Content Source: [docs/reference/msbuild-targets.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/master/docs/reference/msbuild-targets.md)
* Product: **nuget**
* GitHub Login: @karann-msft
* Microsoft Alias: **karann**

**Comment by karann-msft** [comment]
@nvmkpk - where did you see these props?

**Comment by nvmkpk** [comment]
In some targets or props file. I don't remember, it has been a while.

**Comment by JonDouglas** [comment]
There's a few items here about some of these properties:

https://docs.microsoft.com/en-us/dotnet/standard/library-guidance/nuget

https://docs.microsoft.com/en-us/nuget/reference/msbuild-targets#targetsfortfmspecificbuildoutput

Anything else we can add?

**Comment by JonDouglas** [comment]
I'm closing this issue as we haven't got more information about what can be improved here. Please file a new issue if this comes up again with any further details to help.
