### ISSUE TITLE
Misleading information in dependencies-element

### ISSUE THREAD

**Issue by quasarea** [NuGet/docs.microsoft.com-nuget#1093]
The dependencies-element attributes table states that both id and version are required while example in dependency groups section below shows example without version:

    <group targetFramework="net40">
        <dependency id="jQuery" />
        <dependency id="WebActivator" />
    </group>

## Document Details
⚠ Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.

ID: 06a19d7d-253d-f17f-6421-624c9867473d
Version Independent ID: cc37eb17-f715-080c-7bfc-9eae868d50ba
Content: .nuspec File Reference for NuGet
Content Source: docs/reference/nuspec.md

**Comment by Mikejo5000** [comment]
Updating doc
