### ISSUE TITLE
Nuget pack ConfigFile

### ISSUE THREAD

**Issue by peval27** [NuGet/docs.microsoft.com-nuget#1110]
Hi,

if I run "nuget pack /?" there's an option -ConfigFile. This option is not documented here. I'm using Nuget 4.7.1.5393

Thanks,
Paolo

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2e18eb26-7a73-5e48-abd0-3d53476c6f91
* Version Independent ID: 5469de95-4b00-2fbd-f3c0-1cde036f3c7f
* Content: [NuGet CLI pack command](https://docs.microsoft.com/en-gb/nuget/tools/cli-ref-pack)
* Content Source: [docs/tools/cli-ref-pack.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/master/docs/tools/cli-ref-pack.md)
* Product: **nuget**
* GitHub Login: @karann-msft
* Microsoft Alias: **karann**

**Comment by Naveenkhasyap** [comment]
This has been fixed in PR [1115](https://github.com/NuGet/docs.microsoft.com-nuget/pull/1115)

**Comment by Mikejo5000** [comment]
Appears to be fixed
