### ISSUE TITLE
Incorrect example: -s

### ISSUE THREAD

**Issue by iskiselev** [NuGet/docs.microsoft.com-nuget#1118]
When I've tried to use server with -s parameter, as specified on last Examples lane, it had failed with:  Ambiguous option 's'. Possible values: Source SymbolSource SymbolApiKey.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fea0203e-9793-5e92-ee94-0bf972ff91cc
* Version Independent ID: 6d98cff6-9ef7-8c84-941b-4db0db65908c
* Content: [NuGet CLI push command](https://docs.microsoft.com/en-us/nuget/tools/cli-ref-push)
* Content Source: [docs/tools/cli-ref-push.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/master/docs/tools/cli-ref-push.md)
* Product: **nuget**
* GitHub Login: @karann-msft
* Microsoft Alias: **karann**

**Comment by zhaparoff** [comment]
Faced the same issue when using TFS Build Task 'NuGet Publish' with the latest NuGet executable.
Have to publish with old NuGet binary instead.

**Comment by karann-msft** [comment]
Fixed in https://github.com/NuGet/docs.microsoft.com-nuget/pull/1420
