### ISSUE TITLE
Verbosity, available options

### ISSUE THREAD

**Issue by johannes-schmitt** [NuGet/docs.microsoft.com-nuget#1121]
It would be good to mention, what are the possible values for "Verbosity" (normal, quiet, detailed).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 30f597bb-080f-188b-b1ba-a02efbe1e9ca
* Version Independent ID: 88e19d47-f4e1-0496-305c-af14f0d54afb
* Content: [NuGet Command-Line Interface (CLI) Reference](https://docs.microsoft.com/en-us/nuget/tools/nuget-exe-cli-reference)
* Content Source: [docs/tools/nuget-exe-CLI-Reference.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/master/docs/tools/nuget-exe-CLI-Reference.md)
* Product: **nuget**
* GitHub Login: @karann-msft
* Microsoft Alias: **karann**

**Comment by davidalpert** [comment]
@johannes-schmitt I notice that on this Install documentation the Verbosity is listed:

|*Option*|*Description*|
|-|-|
|`Verbosity` | Specifies the amount of detail displayed in the output: _normal_, _quiet_, _detailed_.|

https://docs.microsoft.com/en-us/nuget/tools/cli-ref-install#options

**Comment by karann-msft** [comment]
@johannes-schmitt, this doc is more like an index for all the CLI commands. The individual CLI command do talk about all the options including verbosity like @davidalpert points outs (thanks @davidalpert). Happy to re-open the issue if you feel that does not address your feedback. Thanks for using NuGet!
