### ISSUE TITLE
How to access package's content?

### ISSUE THREAD

**Issue by yhvicey** [NuGet/docs.microsoft.com-nuget#1122]
For example, I have a Azure Blob Emulator installed as a NuGet package, it provides an executable and I want to launch it at our build server for unit testing, is there any way to have some properties to access contents under packages' root folder/sub folder?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ff707668-94d6-25a5-9139-b18cc1b6b446
* Version Independent ID: 494847b9-4894-0beb-7ffa-39a2359999fa
* Content: [NuGet PackageReference format (package references in project files)](https://docs.microsoft.com/en-us/nuget/consume-packages/package-references-in-project-files)
* Content Source: [docs/consume-packages/Package-References-in-Project-Files.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/master/docs/consume-packages/Package-References-in-Project-Files.md)
* Product: **nuget**
* GitHub Login: @karann-msft
* Microsoft Alias: **karann**

**Comment by jonatan1024** [comment]
On Windows the packages are stored here: `c:\Users\<username>\.nuget\packages\`

The path to the specific package is sored in a specific variable, as it can be seen in this file: `obj/<projectname>.csproj.nuget.g.props`

For example I needed to get a NuGet executable from NuGet.CommandLine package, so I added this section into my csproj:

```
  <ItemGroup>
    <None Include="$(PkgNuGet_CommandLine)\tools\NuGet.exe">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>
```

Similar results could be achieved with custom target and copy command.

**Comment by yhvicey** [comment]
Cool! Thanks for your information! Maybe this should be updated to doc.
