### ISSUE TITLE
Update title

### ISSUE THREAD

**Issue by rido-min** [NuGet/docs.microsoft.com-nuget#1124]
Why VS 2015 in the title? IMHO VS 2017 is mature enough to use it as the default version

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9af4b521-192a-5454-8fa5-eeab811ac0ad
* Version Independent ID: 2cfe381e-4510-0bd8-1242-d78733b6bae7
* Content: [Create .NET Standard and .NET Framework NuGet Packages with Visual Studio 2015](https://docs.microsoft.com/en-us/nuget/guides/create-net-standard-packages-vs2015)
* Content Source: [docs/guides/Create-NET-Standard-Packages-VS2015.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/master/docs/guides/Create-NET-Standard-Packages-VS2015.md)
* Product: **nuget**
* GitHub Login: @karann-msft
* Microsoft Alias: **karann**

**Comment by zivkan** [comment]
I think the title is correct, as this page has content that is specific to VS2015. The first paragraph says that VS2017 is preferred with a link to docs relevant to VS 2017.

**Comment by rido-min** [comment]
@zivkan  should we update the full page then?  

/cc @karann-msft @anangaur
