### ISSUE TITLE
Incorrect Parameters

### ISSUE THREAD

**Issue by AspenForester** [NuGet/docs.microsoft.com-nuget#1127]
Get-Package (from Module PackageManagement 1.2.2) does not have a parameter called "Updates"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9477f383-5e28-7739-6562-fb3234b6b0ec
* Version Independent ID: f9af74cb-e3a8-d5e0-75d1-7c7199e76d36
* Content: [NuGet Get-Package PowerShell Reference](https://docs.microsoft.com/en-us/nuget/tools/ps-ref-get-package)
* Content Source: [docs/tools/ps-ref-get-package.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/master/docs/tools/ps-ref-get-package.md)
* Product: **nuget**
* GitHub Login: @karann-msft
* Microsoft Alias: **karann**

**Comment by mrward** [comment]
I think the documentation here is correct. It refers to the NuGet Package Console in Visual Studio not the generic PowerShell Get-Package command which is different. NuGet's Get-Package has an Updates parameter.

The top of this page has:

This topic describes the command within the NuGet Package Manager Console in Visual Studio on Windows. For the generic PowerShell Get-Package command, see the PowerShell PackageManagement reference.

**Comment by AspenForester** [comment]
Thanks for the clarification!
