### ISSUE TITLE
Stylistic error in the caption of the first workflow image

### ISSUE THREAD

**Issue by hugodahl** [NuGet/docs.microsoft.com-nuget#1129]
The caption of the workflow image for the various methods to consume NuGet packages currently reads as such: 

    * Visual Studio and dotnet.ex` only. The nuget install command does not modify project files or packages.config; entries must be managed manually.

Note that there is a single backtick (\`) after "dotnet.ex", as well as the text command is referred to as "dotnet.ex" rather than `dotnet.exe`.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6f32fcb5-8641-9062-83bd-2c8c09aab872
* Version Independent ID: 12404cbd-0105-957e-2875-bb91904fc359
* Content: [Overview and workflow of using NuGet packages](https://docs.microsoft.com/en-us/nuget/consume-packages/overview-and-workflow)
* Content Source: [docs/consume-packages/Overview-and-Workflow.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/master/docs/consume-packages/Overview-and-Workflow.md)
* Product: **nuget**
* GitHub Login: @karann-msft
* Microsoft Alias: **karann**

**Comment by karann-msft** [comment]
@hugodahl thanks for catching that and fixing it!
