### ISSUE TITLE
Debug and release builds in a package

### ISSUE THREAD

**Issue by jozefizso** [NuGet/docs.microsoft.com-nuget#1134]
How can we create a package which contains both Debug and Release builds of a library to provide better debugging experience?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2e18eb26-7a73-5e48-abd0-3d53476c6f91
* Version Independent ID: 5469de95-4b00-2fbd-f3c0-1cde036f3c7f
* Content: [NuGet CLI pack command](https://docs.microsoft.com/en-us/nuget/tools/cli-ref-pack)
* Content Source: [docs/tools/cli-ref-pack.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/master/docs/tools/cli-ref-pack.md)
* Product: **nuget**
* GitHub Login: @karann-msft
* Microsoft Alias: **karann**

**Comment by Mikejo5000** [comment]
I don't believe that is supported. However, you can create a symbol package for better debugging.
https://docs.microsoft.com/en-us/nuget/create-packages/symbol-packages-snupkg
