### ISSUE TITLE
Regarding including dependencies in the section about creating a .nuspec file from a Visual Studio project

### ISSUE THREAD

**Issue by carlos-quintero** [NuGet/docs.microsoft.com-nuget#1135]
Regarding the section about creating a .nuspec file from a Visual Studio project, specifically this phrase:

"Creating a .nuspec from a .csproj or .vbproj file is convenient because other packages that have been installed into those project are automatically referenced as dependencies." 

At the time of this comment (Nov 4, 2018), if you have a .NET Framework myproject.csproj that references a NuGet package, and using nuget.exe 4.7.1.5393, then:

1) If myproject.csproj uses PackageReference:

1.1) nuget.exe spec myproject.csproj generates a .nuspec file that does NOT include dependencies.

1.2) nuget.exe pack myproject.csproj generates a .nupkg file that includes inside a .nuspec file that does NOT include dependencies.

2) If myproject.csproj uses packages.config file:

2.1) nuget.exe spec myproject.csproj generates a .nuspec file that does NOT include dependencies.

2.2) nuget.exe pack myproject.csproj generates a .nupkg file that includes inside a .nuspec file that DOES include dependencies. 

Only case 2.2 works as expected and documented.

Needless to say, this NuGet/dependencies stuff is a nightmare and time-consuming. At the very least, the documentation is wrong. And nuget.exe could do a better job in cases 1.1, 1.2 and 2.1.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f35f4267-e5e3-ddcf-d3e4-479fb233ce9f
* Version Independent ID: 6d49d66f-f777-7e44-3a45-723e3ad09a59
* Content: [How to create a NuGet package](https://docs.microsoft.com/en-us/nuget/create-packages/creating-a-package#from-a-visual-studio-project)
* Content Source: [docs/create-packages/Creating-a-Package.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/master/docs/create-packages/Creating-a-Package.md)
* Product: **nuget**
* GitHub Login: @karann-msft
* Microsoft Alias: **karann**

**Comment by Mikejo5000** [comment]
This doc is limited now to nuget.exe with packages.config, so some issues described here go away.
However, the issue with nuget.exe spec not generating a .nuspec with dependencies looks like a doc bug.

**Comment by Mikejo5000** [comment]
Updating doc
