### ISSUE TITLE
Visual Studio for Mac does have some NuGet export capability

### ISSUE THREAD

**Issue by conceptdev** [NuGet/docs.microsoft.com-nuget#1148]
The [create a NuGet from an existing library](https://docs.microsoft.com/xamarin/cross-platform/app-fundamentals/nuget-multiplatform-libraries/existing-library) doc explains how to add the required metadata and build a NuGet package from a .NET Standard or PCL project in Visual Studio for Mac. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 18071970-cf13-78af-ac1d-9adefefdb693
* Version Independent ID: 3bf15a5c-8b3e-0e69-0bf6-03b44654970c
* Content: [Create and publish a .NET Standard package using Visual Studio on Windows](https://docs.microsoft.com/en-us/nuget/quickstart/create-and-publish-a-package-using-visual-studio)
* Content Source: [docs/quickstart/create-and-publish-a-package-using-visual-studio.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/master/docs/quickstart/create-and-publish-a-package-using-visual-studio.md)
* Product: **nuget**
* GitHub Login: @karann-msft
* Microsoft Alias: **karann**

**Comment by karann-msft** [comment]
Yes! It does! Please re-open this issue if you have feedback about this doc which talks about creating a package using Visual Studio on Windows.

**Comment by conceptdev** [comment]
Sorry, I should have been clearer. This document contains a warning (the second paragraph) which says "Visual Studio for Mac does not include the capabilities described here", which isn't totally accurate:

![note](https://user-images.githubusercontent.com/199373/53768055-905f0280-3e8c-11e9-9637-1d97d6019801.png)

A better message would be "If you are using Visual Studio for Mac, refer to this information on [creating a NuGet package](https://docs.microsoft.com/xamarin/cross-platform/app-fundamentals/nuget-multiplatform-libraries/existing-library), or use the [dotnet CLI tools](https://docs.microsoft.com/en-us/nuget/quickstart/create-and-publish-a-package-using-the-dotnet-cli)"?

Just a thought to help customers on the Mac.

**Comment by Mikejo5000** [comment]
Updating doc...
