### ISSUE TITLE
The symbols packages link points to an older topic

### ISSUE THREAD

**Issue by StingyJack** [NuGet/docs.microsoft.com-nuget#1158]
That is all

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bca41d96-58d7-6586-5b66-39265853acc2
* Version Independent ID: a6d86de4-d74c-9274-b900-4922f833b6a7
* Content: [Overview and workflow of creating NuGet packages](https://docs.microsoft.com/en-us/nuget/create-packages/overview-and-workflow)
* Content Source: [docs/create-packages/Overview-and-Workflow.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/master/docs/create-packages/Overview-and-Workflow.md)
* Product: **nuget**
* GitHub Login: @karann-msft
* Microsoft Alias: **karann**

**Comment by karann-msft** [comment]
Fixed
