### ISSUE TITLE
Update for Arm64?

### ISSUE THREAD

**Issue by edwardskrod** [NuGet/docs.microsoft.com-nuget#1160]
Some of the images are no longer relevant given ARM64 (such as the step relating to BatchBuild).   Should we update them?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5842072b-8382-e7bb-7fd7-9e91cb4b4704
* Version Independent ID: c3e784d1-2aa7-9313-fcb6-bbbdb6ddb987
* Content: [Create NuGet Packages for the Universal Windows Platform](https://docs.microsoft.com/en-us/nuget/guides/create-uwp-packages#feedback)
* Content Source: [docs/guides/Create-UWP-Packages.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/master/docs/guides/Create-UWP-Packages.md)
* Product: **nuget**
* GitHub Login: @karann-msft
* Microsoft Alias: **karann**

**Comment by karann-msft** [comment]
@edwardskrod that's great feedback. Can you help us with a PR with these changes?

**Comment by rrelyea** [comment]
@edwardskrod - your team has more expertise than ours on this. Can you submit PRs?
