### ISSUE TITLE
Update for .nuspec changes

### ISSUE THREAD

**Issue by edwardskrod** [NuGet/docs.microsoft.com-nuget#1161]
Step 3 of Create and update the .nuspec file is not correct.  There are tokens in the &lt;id&gt;, &lt;version&gt;, &lt;title&gt;, etc. 

&lt;?xml version="1.0"?&gt;
&lt;package &gt;
  &lt;metadata&gt;
    &lt;id&gt;$id$&lt;/id&gt;
    &lt;version&gt;$version$&lt;/version&gt;
    &lt;title&gt;$title$&lt;/title&gt;
    &lt;authors&gt;$author$&lt;/authors&gt;
    &lt;owners&gt;$author$&lt;/owners&gt;
    &lt;licenseUrl&gt;http://LICENSE_URL_HERE_OR_DELETE_THIS_LINE&lt;/licenseUrl&gt;
    &lt;projectUrl&gt;http://PROJECT_URL_HERE_OR_DELETE_THIS_LINE&lt;/projectUrl&gt;
    &lt;iconUrl&gt;http://ICON_URL_HERE_OR_DELETE_THIS_LINE&lt;/iconUrl&gt;
    &lt;requireLicenseAcceptance&gt;false&lt;/requireLicenseAcceptance&gt;
    &lt;description&gt;$description$&lt;/description&gt;
    &lt;releaseNotes&gt;Summary of changes made in this release of the package.&lt;/releaseNotes&gt;
    &lt;copyright&gt;Copyright 2018&lt;/copyright&gt;
    &lt;tags&gt;Tag1 Tag2&lt;/tags&gt;
  &lt;/metadata&gt;
&lt;/package&gt;

Update the document to reflect these changes?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5842072b-8382-e7bb-7fd7-9e91cb4b4704
* Version Independent ID: c3e784d1-2aa7-9313-fcb6-bbbdb6ddb987
* Content: [Create NuGet Packages for the Universal Windows Platform](https://docs.microsoft.com/en-us/nuget/guides/create-uwp-packages#feedback)
* Content Source: [docs/guides/Create-UWP-Packages.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/master/docs/guides/Create-UWP-Packages.md)
* Product: **nuget**
* GitHub Login: @karann-msft
* Microsoft Alias: **karann**

**Comment by rrelyea** [comment]
@edwardskrod - your team has more expertise than ours on this. Can you submit PRs?
