### ISSUE TITLE
Support for nuspec language tag?

### ISSUE THREAD

**Issue by dima-y** [NuGet/docs.microsoft.com-nuget#1165]
What about the nuspec language tag (e.g. &lt;language&gt;en-US&lt;/language&gt; as shown in one of the examples here https://docs.microsoft.com/en-us/nuget/reference/nuspec )?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 099102e8-c320-ef50-6821-57519684dc98
* Version Independent ID: 1523dac4-419d-613d-2497-4062f9efd358
* Content: [NuGet pack and restore as MSBuild targets](https://docs.microsoft.com/en-us/nuget/reference/msbuild-targets)
* Content Source: [docs/reference/msbuild-targets.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/master/docs/reference/msbuild-targets.md)
* Product: **nuget**
* GitHub Login: @karann-msft
* Microsoft Alias: **karann**

**Comment by dima-y** [comment]
The <language> tag exists in the XML schema and specifies the package's locale ID as described here:
https://docs.microsoft.com/en-us/nuget/reference/nuspec
I want to be able to generate a package using a .csproj that includes that tag, similarly to how <id> is generated from msbuild's PackageId , <ProjectUrl> from PackageProjectUrl etc. 
Does that make sense?

**Comment by dima-y** [comment]
sorry, my answer was mangled, should read
similarly to how 'id' is generated from msbuild's PackageId , 'ProjectUrl' from PackageProjectUrl etc.

**Comment by zivkan** [comment]
Yes, it's clear now, thanks. From [what I can see](https://github.com/NuGet/NuGet.Client/blob/e2a9cd92a7e07d0fe451fb3c67e138342816ef22/src/NuGet.Core/NuGet.Build.Tasks.Pack/NuGet.Build.Tasks.Pack.targets#L199), there's currently no way to do this. I created a issue to add this functionality NuGet/Home#7520

**Comment by zivkan** [comment]
I'm closing this since we have an issue to track it.
