### ISSUE TITLE
env variable use on Mac

### ISSUE THREAD

**Issue by psrivastava** [NuGet/docs.microsoft.com-nuget#1176]
For me $VAR_NAME did not work. I had to change it to $(VAR_NAME) for it to be evaluated.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 370d9d91-9f35-79aa-3ace-7b77436e988f
* Version Independent ID: 3da4591a-3d3d-c07a-6672-97964de13b14
* Content: [Configuring the behavior of NuGet](https://docs.microsoft.com/en-us/nuget/consume-packages/configuring-nuget-behavior)
* Content Source: [docs/consume-packages/configuring-nuget-behavior.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/master/docs/consume-packages/configuring-nuget-behavior.md)
* Product: **nuget**
* GitHub Login: @karann-msft
* Microsoft Alias: **karann**

**Comment by zivkan** [comment]
What shell are you using? As far as I can tell, the default shell is Bash, and using "$(VAR_NAME)" on the command line will try to execute a program named `VAR_NAME` and use the program's output to replace the variable of the command you typed, and then execute that command.

**Comment by rrelyea** [comment]
@psrivastava - can you give context on which part of this page we need to improve. and exactly how?
Also - can you answer @zivkan's question about which shell you are using?

**Comment by Mikejo5000** [comment]
Closing - need more info to address this
