### ISSUE TITLE
我生成解决方案方案的时候报这个错，我也试过按照官方文档还原NuGet包但没效果

### ISSUE THREAD

**Issue by Jameszyq** [NuGet/docs.microsoft.com-nuget#1180]
严重性	代码	说明	项目	文件	行	禁止显示状态
错误		这台计算机上缺少此项目引用的 NuGet 程序包。使用“NuGet 程序包还原”可下载这些程序包。有关更多信息，请参见 http://go.microsoft.com/fwlink/?LinkID=322105。缺少的文件是 ..\packages\Microsoft.Net.Compilers.2.1.0\build\Microsoft.Net.Compilers.props。	AideshengShopping	D:\AiDeShengShopping\AideshengShopping.csproj	380

**Comment by zivkan** [comment]
I'd like to help, but I'm closing this for a few reasons:

1. This is the English docs repo and we don't have translators in our team.
2. Docs repos are not intended for product support. We'll reroute questions where we can, but it's intended to track issues with the docs, not the product.
3. The issue appears to be a copy/paste of an error message, and the error message includes a link to docs that help resolve the problem. There's no question or commentary about the error, or explanation why the  instructions in the docs linked by the error message does not work.

At this time, all I can suggest is try following the docs that the error message gives a link to. If that doesn't help, something like [stackoverflow](https://stackoverflow.com) may be able to help, although I have no idea if there's a Chinese version. Finally, you can try searching for or opening an issue in [NuGet/Home](https://github.com/NuGet/Home/issues), but we'll need it in English and we need to know.
