### ISSUE TITLE
Misspelling

### ISSUE THREAD

**Issue by behrouz-s** [NuGet/docs.microsoft.com-nuget#1193]
The "using Newtonsoft.json;" had been misspelled, it should be "using Newtonsoft.Json;"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ef71b45e-0bb6-6e61-3b42-8e8f150db9fb
* Version Independent ID: 129fb470-7186-059a-fbe8-29b1caf96bf9
* Content: [Introductory Guide to Using NuGet Packages from within Visual Studio](https://docs.microsoft.com/en-us/nuget/quickstart/install-and-use-a-package-in-visual-studio)
* Content Source: [docs/quickstart/install-and-use-a-package-in-visual-studio.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/master/docs/quickstart/install-and-use-a-package-in-visual-studio.md)
* Product: **nuget**
* GitHub Login: @karann-msft
* Microsoft Alias: **karann**

**Comment by zivkan** [comment]
thank you for your feedback.

**Comment by behrouz-s** [comment]
You're welcome :)
Please change "using Newtonsoft.json;" in part 3, please.

**Comment by zivkan** [comment]
oops. Thanks for pointing out the other, more important, instance. It'll go live then next time fixes are merged.
