### ISSUE TITLE
lockfile-related flags for are not documented on 'dotnet restore' page

### ISSUE THREAD

**Issue by bergbria** [NuGet/docs.microsoft.com-nuget#1199]
The ['dotnet restore' command line documentation](https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-restore?tabs=netcore2x) does not include references to any of the [flags related to lock files](https://github.com/NuGet/Home/wiki/Enable-repeatable-package-restore-using-lock-file#restore-command-line-options) such as `--use-lock-file` and `--locked-mode`

**Comment by Mikejo5000** [comment]
Needs to be moved to dotnet repo
