### ISSUE TITLE
NuGet missing on this computer

### ISSUE THREAD

**Issue by perryraskin** [NuGet/docs.microsoft.com-nuget#1200]
I'm trying to import my .sln file from a Visual Studio project (from a Windows computer) into Rider on my Mac. I'm getting the following error.

```
[null] This project references NuGet package(s) that are missing on this computer. 
Enable NuGet Package Restore to download them.  For more information, see
http://go.microsoft.com/fwlink/?LinkID=322105. 
The missing file is .../.nuget/NuGet.targets.
```

I already copied the .nuget folder from the Windows computer (where the project is working properly). Anything I'm missing here? Usually doing this fixes the issue when I've moved to another Windows computer in the past.

**Comment by zivkan** [comment]
Issue moved to [NuGet/Home #7568](https://github.com/NuGet/Home/issues/7568) via [**ZenHub**](https://www.zenhub.com/)
