### ISSUE TITLE
Xamarin.MAC PC to PR migration shows up a warning

### ISSUE THREAD

**Issue by rafsanulhasan** [NuGet/docs.microsoft.com-nuget#1202]
While I tries to Migrate my projects (Xamarin.Android, Xamarin.iOS, UWP, watchOS, tvOS, .NET core, GTK, WPF) from PC to PR,  it works all fine with Xam.Plugins.Settings NuGet package by James. But a warning shows in a Xamarin.MAC project that:

** "content" assets are not available when the package is installed after the migration**

* NB Though I've created the MACOS project using a MACBOOK, this warning shows up only in windows using VS 2017 build 15.9.3, I've not tried it on MAC after migration. 

Does VS for MAC support PR instead of PC in a Xamarin.MAC project?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 75e25f56-15c8-79d7-5e55-d145b7c1159c
* Version Independent ID: 06388a58-df68-9438-92d7-17359196f5c8
* Content: [Migrating from package.config to PackageReference formats](https://docs.microsoft.com/en-us/nuget/reference/migrate-packages-config-to-package-reference#how-to-roll-back-to-packagesconfig)
* Content Source: [docs/reference/migrate-packages-config-to-package-reference.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/master/docs/reference/migrate-packages-config-to-package-reference.md)
* Product: **nuget**
* GitHub Login: @karann-msft
* Microsoft Alias: **karann**

**Comment by Mikejo5000** [comment]
Migration tool is only available in VS on Windows. PackageRef is supported wherever you have a csproj.
