### ISSUE TITLE
NuGet in VSMac

### ISSUE THREAD

**Issue by esreeves** [NuGet/docs.microsoft.com-nuget#1203]
This document is really useful, but is really lacking for documentation for Visual Studio for the Mac. I need to clear the cache for my nugets, but the button for clearing the nuget cache is missing in Visual Studio for the Mac. Which folder(s) do I manually clear to create the same effect. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 71b49477-cafa-d7d4-76fe-83aff43a3f47
* Version Independent ID: 68d7a416-1397-8cf3-bead-e3cd328aca48
* Content: [How to manage the global packages, cache, temp folders in NuGet](https://docs.microsoft.com/en-us/nuget/consume-packages/managing-the-global-packages-and-cache-folders)
* Content Source: [docs/consume-packages/managing-the-global-packages-and-cache-folders.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/master/docs/consume-packages/managing-the-global-packages-and-cache-folders.md)
* Product: **nuget**
* GitHub Login: @karann-msft
* Microsoft Alias: **karann**

**Comment by mrward** [comment]
The only official Microsoft document that I am aware of for VSMac and NuGet is about how to use VS Mac to install a NuGet package - https://docs.microsoft.com/en-us/visualstudio/mac/nuget-walkthrough

So probably a good idea to enhance the document on the NuGet site.

The NuGet extension for VS Mac/MonoDevelop used to have the clear cache button but I was asked to remove it.

**Comment by karann-msft** [comment]
This has been resolved in the latest updates to this page.
