### ISSUE TITLE
Add dependencies for multiple frameworks in NuSpec file 

### ISSUE THREAD

**Issue by p0onage** [NuGet/docs.microsoft.com-nuget#1206]
I've created a Nuget package from a project targetting .Net Standard 2.0 but when coming to install this project from the Nuget feed it is not visible within a .Net framework 4.7 solution. The reason for the is having .Net Standard 2.0 as a dependency. 

I fixed this in the end by using 
`  <TargetFrameworks>netstandard2.0;net47</TargetFrameworks>`
but it would have been ideal if the NuSpec file has an override dependency area where I could remove this dependency and state any other dependencies. We have a Dependencies field in the metadata of the nuspec file but it doesn't work as expected

**Comment by zivkan** [comment]
Issue moved to [NuGet/Home #7597](https://github.com/NuGet/Home/issues/7597) via [**ZenHub**](https://www.zenhub.com/)
