### ISSUE TITLE
License element is documented but not released yet

### ISSUE THREAD

**Issue by maxim-zhao** [NuGet/docs.microsoft.com-nuget#1209]
Current NuGet (4.7.1), with or without an XSD URI (e.g. http://schemas.microsoft.com/packaging/2013/05/nuspec.xsd) rejects packages with the "license" metadata element. This is currently documented at https://github.com/NuGet/Home/wiki/Packaging-License-within-the-nupkg as "Reviewed", but the docs show it as available (without any minimum version).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 06a19d7d-253d-f17f-6421-624c9867473d
* Version Independent ID: cc37eb17-f715-080c-7bfc-9eae868d50ba
* Content: [.nuspec File Reference for NuGet](https://docs.microsoft.com/en-us/nuget/reference/nuspec)
* Content Source: [docs/reference/nuspec.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/master/docs/reference/nuspec.md)
* Product: **nuget**
* GitHub Login: @karann-msft
* Microsoft Alias: **karann**

**Comment by karann-msft** [comment]
This feature has not been released and NuGet.org does accept the license metadata. Thanks!
