### ISSUE TITLE
Semantic versioning and "normalization"

### ISSUE THREAD

**Issue by StingyJack** [NuGet/docs.microsoft.com-nuget#1211]
&gt; "NuGet supports Semantic Versioning 2.0.0."

This is not a true statement. NuGet forces you to adopt their flavor of semantic versioning even for private packages hosted in a private repository. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 55c7db33-f188-0247-4c5e-035b25b11392
* Version Independent ID: 33cd8166-51d5-3ce3-8d6f-8f0df0310724
* Content: [NuGet Package Version Reference](https://docs.microsoft.com/en-us/nuget/reference/package-versioning)
* Content Source: [docs/reference/Package-Versioning.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/master/docs/reference/Package-Versioning.md)
* Product: **nuget**
* GitHub Login: @karann-msft
* Microsoft Alias: **karann**

**Comment by karann-msft** [comment]
Please file product feedback issues on the Home repo.

**Comment by StingyJack** [comment]
I did so for the unwanted version normalization. This issue is open so the documentation will be corrected. 

Nuget does not _support_ SemVer among other versioning schemes, Nuget _coerces_ package authors into adhering to **its** flavor of SemVer. Existing versioning schemes may be broken in order to meet this. That this did not merit a Major version increment for nuget.exe when its a breaking change only serves to reinforce the point that Nuget itself does not even adhere to SemVer. 

@karann-msft - I may continue to forgive your earlier knee-jerk protective reaction to a reasoned and truthful criticism, but that forgiveness does not extend into perpetuity. Should you choose to deface, vandalize, alter, or restrict access to **my** content a second time an official complaint about your professional conduct will be filed with E&C/BusCon.  If you would prefer I go to your supervisor first instead, please cc them on this thread.
