### ISSUE TITLE
Is there a way to block a package from being included?

### ISSUE THREAD

**Issue by StingyJack** [NuGet/docs.microsoft.com-nuget#1212]
I dont want some packages to ever be installed. I dont see a way in here to exclude it without adding it and setting an allowed version of almost nothing, and that would probably not work. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 63f06d78-4229-5af1-fd2f-a3c4f1601e82
* Version Independent ID: bfaddd49-ed46-768e-8c92-1af18d523ad9
* Content: [NuGet packages.config File Reference](https://docs.microsoft.com/en-us/nuget/reference/packages-config)
* Content Source: [docs/reference/packages-config.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/master/docs/reference/packages-config.md)
* Product: **nuget**
* GitHub Login: @karann-msft
* Microsoft Alias: **karann**

**Comment by karann-msft** [comment]
There isn't a way to do that today. Feel free to file a feature request issue in the Home repo.
