### ISSUE TITLE
Error on build due to missing NuGet packages: "..\packages\Microsoft.Bcl.Build.1.0.21\build\Microsoft.Bcl.Build.targets"

### ISSUE THREAD

**Issue by wfuller** [NuGet/docs.microsoft.com-nuget#1215]
I am getting this error "Error on build due to missing NuGet packages: "..\packages\Microsoft.Bcl.Build.1.0.21\build\Microsoft.Bcl.Build.targets" when I try and build this solution in VS 2013.

Despite the error, I can see the 3 BCL files in my packages.config file:
    <package id="Microsoft.Bcl" version="1.1.3" targetFramework="net45" />
    <package id="Microsoft.Bcl" version="1.1.10" targetFramework="net45" />
    <package id="Microsoft.Bcl.Build" version="1.0.21" targetFramework="net45" />

My package manager settings are set to "Allow NuGet to download missing packages", and to "Automatically check for missing packages during build in Visual Studio".

All of the troubleshooting info I've found suggests this should be all I need. The BCL files are specified in the packages.config file, and so VS should get them from NuGet if they aren't already present. 

But it still isn't working.

I should mention that this is an old web app build on a different computer some time ago by someone else, which I now need to modify. There is an old build that worked and can still run. I just can't get it to build now, on my computer.

**Comment by zivkan** [comment]
Issue moved to [NuGet/Home #7618](https://github.com/NuGet/Home/issues/7618) via [**ZenHub**](https://www.zenhub.com/)
