### ISSUE TITLE
Package Restore not Working

### ISSUE THREAD

**Issue by Rainamay** [NuGet/docs.microsoft.com-nuget#1216]
The error is:

This project references NuGet package(s) that are
 missing on this computer. Use NuGet Package Restore to download them.  For more information, see http://go.microsoft.com/fwlink/?LinkID=322105. The missing file is ..\packages\Microsoft.CodeDom.Providers.DotNetCompilerPlatform.2.0.0\buil
d\net46\Microsoft.CodeDom.Providers.DotNetCompilerPlatform.props.

I already have the settings as they should be:
![settings](https://user-images.githubusercontent.com/24514861/49689094-25e73200-faea-11e8-808e-0731d50dd0ab.PNG)

This happens often.  I also get an error all the time with IIS Express that a bin\roslyn.exe file is missing.

Thank you

**Comment by zivkan** [comment]
Issue moved to [NuGet/Home #7619](https://github.com/NuGet/Home/issues/7619) via [**ZenHub**](https://www.zenhub.com/)
