### ISSUE TITLE
-symbols on pack

### ISSUE THREAD

**Issue by OzBob** [NuGet/docs.microsoft.com-nuget#1221]
how can I add the attribute '-symbols' to the pack command. before I would have this in the post-build event: nuget.exe pack aaa.nuspec -includereferencedprojects -symbols

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 18071970-cf13-78af-ac1d-9adefefdb693
* Version Independent ID: 3bf15a5c-8b3e-0e69-0bf6-03b44654970c
* Content: [Create and publish a .NET Standard package using Visual Studio on Windows](https://docs.microsoft.com/en-us/nuget/quickstart/create-and-publish-a-package-using-visual-studio#run-the-pack-command)
* Content Source: [docs/quickstart/create-and-publish-a-package-using-visual-studio.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/master/docs/quickstart/create-and-publish-a-package-using-visual-studio.md)
* Product: **nuget**
* GitHub Login: @karann-msft
* Microsoft Alias: **karann**

**Comment by karann-msft** [comment]
That a look at this doc - https://docs.microsoft.com/en-us/nuget/create-packages/symbol-packages-snupkg
Let us know if it helped.
