### ISSUE TITLE
the CLI does not support uninstall 

### ISSUE THREAD

**Issue by lywyn** [NuGet/docs.microsoft.com-nuget#1223]
The matrix has tick for install/uninstall for the windows CLI but the docs for the cli do not have an uninstall option.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3460a9b2-3b49-1cda-add2-14d26e217716
* Version Independent ID: 95b91106-faff-c7f6-3699-94d643b5cf73
* Content: [Installing NuGet client tools](https://docs.microsoft.com/en-us/nuget/install-nuget-client-tools#feature-availability)
* Content Source: [docs/install-nuget-client-tools.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/master/docs/install-nuget-client-tools.md)
* Product: **nuget**
* GitHub Login: @karann-msft
* Microsoft Alias: **karann**

**Comment by nnmer** [comment]
Based on https://github.com/NuGet/docs.microsoft.com-nuget/blame/master/docs/tools/cli-ref-install.md#L23
the uninstall option perhaps was not implemented, as you can just delete the folder from packages folder manually

**Comment by Mikejo5000** [comment]
The procedure for uninstall for nuget.exe CLI is documented in here:
https://docs.microsoft.com/en-us/nuget/consume-packages/reinstalling-and-updating-packages
