### ISSUE TITLE
Token replacement $authors$ to be $author$

### ISSUE THREAD

**Issue by satish5b8** [NuGet/docs.microsoft.com-nuget#1226]
Token replacement $authors$ to be $author$

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 06a19d7d-253d-f17f-6421-624c9867473d
* Version Independent ID: cc37eb17-f715-080c-7bfc-9eae868d50ba
* Content: [.nuspec File Reference for NuGet](https://docs.microsoft.com/en-us/nuget/reference/nuspec)
* Content Source: [docs/reference/nuspec.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/master/docs/reference/nuspec.md)
* Product: **nuget**
* GitHub Login: @karann-msft
* Microsoft Alias: **karann**

**Comment by karann-msft** [comment]
Thanks to @StingyJack, this has been fixed - https://github.com/NuGet/docs.microsoft.com-nuget/pull/1325
The changes will be live shortly.
