### ISSUE TITLE
What about .Net Standard

### ISSUE THREAD

**Issue by loicmorvan-ansys** [NuGet/docs.microsoft.com-nuget#1227]
Can you add netstandard in this document? You talk a little about PCL, but not at all about .Net Standard!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f1482e18-5f1f-3a8a-3321-66af52879ec5
* Version Independent ID: d70bd2f5-c04b-9207-62a0-4ecb6e8e5ca6
* Content: [Multi-targeting for NuGet Packages](https://docs.microsoft.com/en-us/nuget/create-packages/supporting-multiple-target-frameworks)
* Content Source: [docs/create-packages/Supporting-Multiple-Target-Frameworks.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/master/docs/create-packages/Supporting-Multiple-Target-Frameworks.md)
* Product: **nuget**
* GitHub Login: @karann-msft
* Microsoft Alias: **karann**

**Comment by AsharSiddiqui** [comment]
All the supported target frameworks are listed in following link;
https://docs.microsoft.com/en-us/nuget/reference/target-frameworks

**Comment by Mikejo5000** [comment]
Here's a new topic on multitargeting using the project file:
https://docs.microsoft.com/en-us/nuget/create-packages/multiple-target-frameworks-project-file
