### ISSUE TITLE
Need a better message and example

### ISSUE THREAD

**Issue by raffaeler** [NuGet/docs.microsoft.com-nuget#1228]
This warning is issued also when the csproj contains the tag &lt;PackageLicenseUrl/&gt; which is not 'licenseUrl'.
In this case the documentation should provide a clear example of the replacement needed in the csproj.
The provided link is about a discussion and does not provide any help.
At the provided link there is another link pointing to the nuget specification which, again, talks about nuget and not the csproj.
At the end, I will stay with the current deprecated tag, waiting for some better explanation.
Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d2331cad-1911-3ab2-8060-d92334132437
* Version Independent ID: 6b09a340-76da-0315-7cf7-90f6395bb652
* Content: [NuGet Error NU5125](https://docs.microsoft.com/en-us/nuget/reference/errors-and-warnings/nu5125)
* Content Source: [docs/reference/errors-and-warnings/NU5125.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/master/docs/reference/errors-and-warnings/NU5125.md)
* Product: **nuget**
* GitHub Login: @nkolev92

**Comment by nkolev92** [comment]
@raffaeler 
Please refer to https://docs.microsoft.com/en-us/nuget/reference/msbuild-targets#packing-a-license-expression-or-a-license-file. 

//cc @karann-msft @anangaur

**Comment by raffaeler** [comment]
Thank you @nkolev92 
On GitHub the License file is usually stored in the repo root.
Since the project is in a subfolder, which one is correct?
```
<PackageLicenseFile>../LICENSE</PackageLicenseFile>
or
<PackageLicenseFile>..\LICENSE</PackageLicenseFile>
```

**Comment by zivkan** [comment]
The docs nkolev92 linked to say this, emphasis mine

> When packing a license file, you need to use PackageLicenseFile property to specify the package path, **relative to the root of the package**. In addition, you need to make sure that the file is included in the package

The `..` in your path tries to look outside of the package, so is not valid (a security risk recently named zip slip). You will however, need the `..` in the `None` MSBuild item's include path.

**Comment by raffaeler** [comment]
@zivkan Can you please provide an example? 
I added the following in the csproj:
```
<PropertyGroup>
    <PackageLicenseFile>LICENSE</PackageLicenseFile>
</PropertyGroup>
...
  <ItemGroup>
    <None Add="..\LICENSE" />
  </ItemGroup>
``` 
But when I pack the project, I get the following error:
```
error NU5030: The license file 'LICENSE' does not exist in the package
```

**Comment by anangaur** [comment]
https://docs.microsoft.com/en-us/nuget/reference/msbuild-targets#packing-a-license-expression-or-a-license-file

**Comment by raffaeler** [comment]
@anangaur no way
```
<PropertyGroup>
    <PackageLicenseFile>LICENSE</PackageLicenseFile>
</PropertyGroup>
  <ItemGroup>
    <None Include="..\LICENSE" Pack="true" PackagePath="$(PackageLicenseFile)"/>
  </ItemGroup>
``` 
Still getting an error:
```
 error NU5030: The license file 'LICENSE' does not exist in the package
``` 
and also:
```
An attempt was made to move the file pointer before the beginning of the file 
```

**Comment by nkolev92** [comment]
@raffaeler 

Try using
`PackagePath=""` or `PackagePath="."`
It's a function of how paths are handled in pack in general.

**Comment by raffaeler** [comment]
It finally worked. The documentation definitely need to be updated as the solution was absolutely not straightforward.

If anyone should find this post, here is how I solved my problem.

The LICENSE file is located in the **parent** folder of the project file as it always works on GitHub.
```
Repo Root
 |
 | ----- LICENSE
 | ----- Project Folder
            |
            | ---- nupkg Folder
```

The project csproj contains these license-related tags:
```
  <PropertyGroup>
    <PackageLicenseFile>LICENSE</PackageLicenseFile>
  </PropertyGroup>

  <ItemGroup>
    <None Include="..\LICENSE" Pack="true" PackagePath=""/>
  </ItemGroup>
```

Inside the project folder, the subfolder called nupkg will contains the result of the package creation. In order to exclude this folder, the csproj must contains these tags:
```
  <ItemGroup>
    <Compile Remove="nupkg\**" />
    <EmbeddedResource Remove="nupkg\**" />
    <None Remove="nupkg\**" />
  </ItemGroup>
```

Commands to create the package and install temporary the global tool:
```
dotnet pack -c Release
dotnet tool install --global --add-source ./nupkg ProjectName
```

Command to uninstall the global tool:
```
dotnet tool uninstall -g ProjectName
```
