### ISSUE TITLE
4.9.2 release notes missing?

### ISSUE THREAD

**Issue by devlead** [NuGet/docs.microsoft.com-nuget#1230]
Read the latest NuGet announcement https://github.com/NuGet/Announcements/issues/32 and it says 4.9.2 has shipped December 11th.

Reading through this page I only see 4.9.0 and 4.9.1 mentioned.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 300985dd-9626-6e0a-d055-73dbbc3633a0
* Version Independent ID: 814d9eaa-25dc-58f2-e0be-a390f3d360b7
* Content: [NuGet 4.9 RTM Release Notes](https://docs.microsoft.com/en-us/nuget/release-notes/nuget-4.9-rtm)
* Content Source: [docs/release-notes/NuGet-4.9-RTM.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/master/docs/release-notes/NuGet-4.9-RTM.md)
* Product: **nuget**
* GitHub Login: @karann-msft
* Microsoft Alias: **karann**

**Comment by anangaur** [comment]
@devlead Release notes for [4.9.2](https://docs.microsoft.com/en-us/nuget/release-notes/nuget-4.9-rtm#summary-whats-new-in-492) is now available. Thanks for your patience.

**Comment by devlead** [comment]
@anangaur Excellent! 🎉 Happy holidays 🎁
