### ISSUE TITLE
This MSBuild doesn't work

### ISSUE THREAD

**Issue by DoCode** [NuGet/docs.microsoft.com-nuget#1231]
The MSBuild scenario doesn't work when I reference the file relative:
```xml
<PropertyGroup>
    <PackageLicenseFile>LICENSE</PackageLicenseFile>
</PropertyGroup>

<ItemGroup>
    <None Include="../../LICENSE" Pack="true" PackagePath="$(PackageLicenseFile)" />
</ItemGroup>
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6c43c07f-a3e6-6da8-1c85-d0dc06fade2f
* Version Independent ID: 5cc5f0b0-8ab5-f05c-89ad-92172362fcf3
* Content: [NuGet Error NU5030](https://docs.microsoft.com/en-us/nuget/reference/errors-and-warnings/nu5030)
* Content Source: [docs/reference/errors-and-warnings/NU5030.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/master/docs/reference/errors-and-warnings/NU5030.md)
* Product: **nuget**
* GitHub Login: @nkolev92

**Comment by Mikejo5000** [comment]
Looks like it needs a file URL.

**Comment by jjxtra** [comment]
Broken in vs 2019. Cannot use file path or file url. License file error always that license file is not found.

**Comment by jjxtra** [comment]
Fixed, must use just file name in PackageLicenseFile.
