### ISSUE TITLE
.NET Runtime Requirements missing

### ISSUE THREAD

**Issue by bladeoflight16** [NuGet/docs.microsoft.com-nuget#1239]
The NuGet.exe CLI appears to require some minimum .NET Framework version higher than 4.5.2. I get the following error from any command:

```
Unhandled Exception: System.TypeLoadException: Could not load type 'System.AppContext' from assembly 'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'.
   at NuGet.CommandLine.Program.Main(String[] args)
```

But the documentation doesn't clarify what the minimum version is.

Ideally, there would be documentation for each available version of the tool so I can figure out which ones I might be able to run without upgrading.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3460a9b2-3b49-1cda-add2-14d26e217716
* Version Independent ID: 95b91106-faff-c7f6-3699-94d643b5cf73
* Content: [Installing NuGet client tools](https://docs.microsoft.com/en-us/nuget/install-nuget-client-tools)
* Content Source: [docs/install-nuget-client-tools.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/master/docs/install-nuget-client-tools.md)
* Product: **nuget**
* GitHub Login: @karann-msft
* Microsoft Alias: **karann**

**Comment by ktabarez** [comment]
@bladeoflight16  I ran into this issue on a brand new Windows Server while trying to execute a cake script as part of my CI process. [According to the .NET API, System.AppContext ships with .NET Framework 4.7.2](https://docs.microsoft.com/en-us/dotnet/api/system.appcontext?view=netframework-4.7.2). After I installed .NET Framework 4.7.2 via Choco and then rebooted, nuget.exe ran as expected.

**Comment by kentcb** [comment]
Getting this on Linux simply by:

```
> sudo apt-get install nuget
> nuget update -self
> nuget

Unhandled Exception:
System.TypeLoadException: Could not load type 'System.AppContext' from assembly 'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'.
[ERROR] FATAL UNHANDLED EXCEPTION: System.TypeLoadException: Could not load type 'System.AppContext' from assembly 'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'.
```

**Comment by bsommardahl** [comment]
I just got this on Linux Mint 18.3 with Dotnet Core SDK 2.2

**Comment by bsommardahl** [comment]
Updating to the latest version of Mono fixed it for me. I was on 4.x.x. Now I have 5.x.x and everything works fine. https://www.mono-project.com/download/stable/#download-lin

**Comment by karann-msft** [comment]
@rrelyea - thoughts?

**Comment by rrelyea** [comment]
Created https://github.com/NuGet/docs.microsoft.com-nuget/pull/1449 to document .net framework version required.
Unsure of the answer for mono, etc...

**Comment by karann-msft** [comment]
merged Rob's changes - https://github.com/NuGet/docs.microsoft.com-nuget/commit/887a44e17384e1c3477c98d9eb09d74135e949ae

**Comment by Mikejo5000** [comment]
@karann-msft Karan, looks like this was fixed in the PR?

**Comment by Mikejo5000** [comment]
Appears to be fixed
