### ISSUE TITLE
How i can provide codestyle with .editorconfig to my projects using nuget package?

### ISSUE THREAD

**Issue by inyutin-maxim** [NuGet/docs.microsoft.com-nuget#1241]
I am want provide codestyle with .editorconfig file to my projects using nuget package. How i can do it?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f35f4267-e5e3-ddcf-d3e4-479fb233ce9f
* Version Independent ID: 6d49d66f-f777-7e44-3a45-723e3ad09a59
* Content: [How to create a NuGet package](https://docs.microsoft.com/en-us/nuget/create-packages/creating-a-package#from-a-convention-based-working-directory)
* Content Source: [docs/create-packages/Creating-a-Package.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/master/docs/create-packages/Creating-a-Package.md)
* Product: **nuget**
* GitHub Login: @karann-msft
* Microsoft Alias: **karann**

**Comment by Paul-Dempsey** [comment]
That would seem to be something more appropriate for a project template (delivered in a .vsix) than for a nuget package.

**Comment by MelGrubb** [comment]
Styling decisions evolve over time, and a project template would be a one-time snapshot. Delivering an editorconfig via NuGet means that as more and more settings are supported by Visual Studio, we can add them to the editorconfig file, and as long as our various different projects remember to update to the latest version of that particular package on a regular basis, we can ensure that all of our projects are adhering to the current standards.

Also, I've found myself on one branch of our project when I find that something doesn't look right. I research editorconfig support, find the appropriate rule/setting, and add it to the editorconfig file. That's great, but it only exists on my branch. I switch to some other feature branch, and that setting is gone. I can cherry pick the change to the config file individually, but simply updating the NuGet package would be a lot easier, apart from the maintenance of the package itself, of course.

**Comment by binki** [comment]
This is a problem that maybe needs to be solved. But it is the same problem as synchronizing your `.gitignore` across projects. Also, nuget is probably not the right solution for this—if anything is, npmjs likely is. And this would need to be specified/recommended by [`.editorconfig` itself](https://editorconfig.org/#feedback) rather than nuget. See my comment at [this issue](https://github.com/dotnet/roslyn/issues/19028#issuecomment-1147586947).
