### ISSUE TITLE
Can't get Solution to Build

### ISSUE THREAD

**Issue by regal60740** [NuGet/docs.microsoft.com-nuget#1243]
ASP.NET 4.6.1 - VS2017, will not build. I am using NLog.Web Version 4.7.0. I've tried all the suggestions for Nuget, but nothing works.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 906d0438-0338-0167-3a38-d213ee187ddb
* Version Independent ID: b558fa0c-f549-1e6a-c2db-fd2e6a2351be
* Content: [Troubleshooting NuGet Package Restore in Visual Studio](https://docs.microsoft.com/en-us/nuget/Consume-Packages/Package-restore-troubleshooting)
* Content Source: [docs/consume-packages/Package-restore-troubleshooting.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/master/docs/consume-packages/Package-restore-troubleshooting.md)
* Product: **nuget**
* GitHub Login: @karann-msft
* Microsoft Alias: **karann**

**Comment by karann-msft** [comment]
@regal60740 please file an issue on https://github.com/nuget/home/issues with steps to repro.
