### ISSUE TITLE
Typo, missing word?

### ISSUE THREAD

**Issue by joeboon** [NuGet/docs.microsoft.com-nuget#1244]
Seems to be a missing word “because you're with the Console you're already in the context of Visual Studio”

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6f32fcb5-8641-9062-83bd-2c8c09aab872
* Version Independent ID: 12404cbd-0105-957e-2875-bb91904fc359
* Content: [Overview and workflow of using NuGet packages](https://docs.microsoft.com/en-us/nuget/consume-packages/overview-and-workflow)
* Content Source: [docs/consume-packages/Overview-and-Workflow.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/master/docs/consume-packages/Overview-and-Workflow.md)
* Product: **nuget**
* GitHub Login: @karann-msft
* Microsoft Alias: **karann**

**Comment by karann-msft** [comment]
@joeboon thanks for catching that. I have fixed it and should be live next time we merge to live.
We also accept PRs for our docs and we've made it super easy to do that. Just click the "edit" button on top of the page you want to submit a PR for, and you'll be brought to the markdown file for that page. 
![image](https://user-images.githubusercontent.com/16904420/51269965-9cdcd980-1978-11e9-9d88-b8356a8e12d2.png)
