### ISSUE TITLE
Relisting command

### ISSUE THREAD

**Issue by Kannan1015** [NuGet/docs.microsoft.com-nuget#1246]
Getting unknown command POST when relisting the unlisted package from nuget.exe. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6f5691c1-f008-bbbf-a086-d9e665b5c332
* Version Independent ID: f255cc99-1041-ca5c-d2e5-5981e450a236
* Content: [Push and Delete, NuGet API](https://docs.microsoft.com/en-us/nuget/api/package-publish-resource#relist-a-package)
* Content Source: [docs/api/package-publish-resource.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/master/docs/api/package-publish-resource.md)
* Product: **nuget**
* GitHub Login: @joelverhagen
* Microsoft Alias: **jver**

**Comment by loic-sharma** [comment]
What is your package source? What version of nuget.exe are you on?

**Comment by Kannan1015** [comment]
Please find the details.

Version: 4.9.2.5706
Package Name: All packages which I have an owner.
