### ISSUE TITLE
Doubts

### ISSUE THREAD

**Issue by lindomarfarineli** [NuGet/docs.microsoft.com-nuget#1248]
And what is the target structure that the package supports?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 377ae860-386f-149f-c5e0-410d3aa89dbc
* Version Independent ID: 2b145147-fd3f-d1aa-2694-071a31542d9a
* Content: [NuGet Errors and Warnings Reference](https://docs.microsoft.com/en-us/nuget/reference/errors-and-warnings/nu1701?f1url=https%3A%2F%2Fmsdn.microsoft.com%2Fquery%2Fdev15.query%3FappId%3DDev15IDEF1%26l%3DEN-US%26k%3Dk(NU1701)%26rd%3Dtrue)
* Content Source: [docs/reference/errors-and-warnings/NU1701.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/master/docs/reference/errors-and-warnings/NU1701.md)
* Product: **nuget**
* GitHub Login: @zhili1208
* Microsoft Alias: **lzhi**

**Comment by Mikejo5000** [comment]
If I understand the question, it's about how to correctly specify the target framework in the project file. Some docs may help with that:
https://docs.microsoft.com/en-us/nuget/create-packages/multiple-target-frameworks-project-file
https://docs.microsoft.com/en-us/nuget/create-packages/supporting-multiple-target-frameworks

**Comment by Mikejo5000** [comment]
You can change the project file directly or through the properties. I don't think we need to update the docs though.

**Comment by lindomarfarineli** [comment]
Thank you!


Enviado do Outlook<http://aka.ms/weboutlook>

________________________________
De: Mike Jones <notifications@github.com>
Enviado: quinta-feira, 8 de agosto de 2019 17:03
Para: NuGet/docs.microsoft.com-nuget <docs.microsoft.com-nuget@noreply.github.com>
Cc: lindomarfarineli <lindomarfarineli@hotmail.com>; Author <author@noreply.github.com>
Assunto: Re: [NuGet/docs.microsoft.com-nuget] Doubts (#1248)


If I understand the question, it's about how to correctly specify the target framework in the project file. Some docs may help with that:
https://docs.microsoft.com/en-us/nuget/create-packages/multiple-target-frameworks-project-file
https://docs.microsoft.com/en-us/nuget/create-packages/supporting-multiple-target-frameworks
