### ISSUE TITLE
Other poential conditions

### ISSUE THREAD

**Issue by jensVivende** [NuGet/docs.microsoft.com-nuget#1251]
This section is very promising, but does not work. Nuget command is not working on latest VS. There are not packages folder (please specify where it is). The nuget locals all -clear does not work

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 906d0438-0338-0167-3a38-d213ee187ddb
* Version Independent ID: b558fa0c-f549-1e6a-c2db-fd2e6a2351be
* Content: [Troubleshooting NuGet Package Restore in Visual Studio](https://docs.microsoft.com/en-gb/nuget/Consume-Packages/Package-restore-troubleshooting)
* Content Source: [docs/consume-packages/Package-restore-troubleshooting.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/master/docs/consume-packages/Package-restore-troubleshooting.md)
* Product: **nuget**
* GitHub Login: @karann-msft
* Microsoft Alias: **karann**

**Comment by jawn** [comment]
Same here, can the same be achieved using the NuGet Package Manager in powershell?

I understand NuGet is not included in VS 2017: https://www.nuget.org/downloads

**Comment by Mikejo5000** [comment]
@jensVivende Which NuGet command did not work? Updating doc, adding links to full restore procedure and also links to packages.config for more information (sounds like you are using a project with packages.config).
