### ISSUE TITLE
difference in "packages" restore path - vs 2017 vs dotnet.exe restore (2.1) cli

### ISSUE THREAD

**Issue by verbaloid** [NuGet/docs.microsoft.com-nuget#1252]
Why vs 2017 restores under "packages\Newtonsoft.Json.12.0.1\Newtonsoft.Json.12.0.1.nupkg" but
dotnet.exe restore (2.1) cli restores under "packages\newtonsoft.json\12.0.1\newtonsoft.json.12.0.1.nupkg"?
What is the reason behind difference in path (. in place of \)?

**Comment by verbaloid** [comment]
workarounded in .csproj by this 
        <HintPath Condition="Exists('..\..\packages\Newtonsoft.Json\12.0.1\lib\net35')">..\..\packages\Newtonsoft.Json\12.0.1\lib\net35\Newtonsoft.Json.dll</HintPath>
        <HintPath Condition="Exists('..\..\packages\Newtonsoft.Json.12.0.1\lib\net35')">..\..\packages\Newtonsoft.Json.12.0.1\lib\net35\Newtonsoft.Json.dll</HintPath>

**Comment by verbaloid** [comment]
"<HintPath Condition="Exists('..\..\packages\Newtonsoft.Json\12.0.1\lib\net35')">..\..\packages\Newtonsoft.Json\12.0.1\lib\net35\Newtonsoft.Json.dll</HintPath>"

**Comment by verbaloid** [comment]
> <HintPath

 Condition="Exists('..\..\packages\Newtonsoft.Json\12.0.1\lib\net35')">..\..\packages\Newtonsoft.Json\12.0.1\lib\net35\Newtonsoft.Json.dll</HintPath>

>

**Comment by Mikejo5000** [comment]
For dotnet.exe (SDK-style projects or non-SDK migrated to PackageReference), there shouldn't be any packages in the \packages folder.
Packages should be in the global-packages folder
https://docs.microsoft.com/en-us/nuget/reference/migrate-packages-config-to-package-reference
