### ISSUE TITLE
Repeatable build related errors and warnings dont have docs, NU1004, NU1005

### ISSUE THREAD

**Issue by nkolev92** [NuGet/docs.microsoft.com-nuget#1257]
For exampe NU1004 https://docs.microsoft.com/en-us/nuget/reference/errors-and-warnings/nu1004

//cc @jainaashish @anangaur

**Comment by anangaur** [comment]
Assigning this to Rob for now to plan and get this assigned to somebody in Engineering.

**Comment by nkolev92** [comment]
//cc @rrelyea This is the issue we discussed in stand-up.

**Comment by karann-msft** [comment]
@nkolev92, @anangaur, @rrelyea - ping!
