### ISSUE TITLE
 NU1701: Package 'PagedList 1.17.0' was restored using v4.6.1 instead of  '.NETCoreApp,Version=v2.1'.

### ISSUE THREAD

**Issue by rajashekargoka** [NuGet/docs.microsoft.com-nuget#1258]
warning NU1701: Package 'PagedList 1.17.0' was restored using '.NETFramework,Version=v4.6.1' instead of the project target framework '.NETCoreApp,Version=v2.1'. This package may not be fully compatible with your project.

**Comment by karann-msft** [comment]
@rajashekargoka this repo is intended for docs, and related issues.
For product feedback and filing bugs, please file an issue in our Home repo - https://github.com/NuGet/Home/issues
