### ISSUE TITLE
NuGet Package Sources priority ordering is ineffectual and should be removed

### ISSUE THREAD

**Issue by MaxG117** [NuGet/docs.microsoft.com-nuget#1259]
The up and down arrows in the **Tools > Options > NuGet Package Manager > Package Sources** dialog are ineffectual, and the documentation stating:

> Use the up and down arrow buttons to change the priority order of the package sources. Visual Studio searches these sources in the priority order when restoring packages for a project.

does not make sense. According to https://github.com/NuGet/Home/issues/3676#issuecomment-254570021, the package sources are unordered by design and they are searched by order of the quickest response.

Please remove the arrows from the GUI and update the documentation accordingly.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 108d587b-429e-3459-5698-3b40e44f4c3e
* Version Independent ID: 76ad6a3f-4dde-0883-1df9-0f173f0ca7e7
* Content: [NuGet Package Manager UI Reference](https://docs.microsoft.com/en-us/nuget/tools/package-manager-ui)
* Content Source: [docs/tools/Package-Manager-UI.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/master/docs/tools/Package-Manager-UI.md)
* Product: **nuget**
* GitHub Login: @karann-msft
* Microsoft Alias: **karann**

**Comment by AceHack** [comment]
Hey, I rely on order.  I'd rather see things the other way around and have nuget respect order.

**Comment by karann-msft** [comment]
Thanks for the feedback. The docs have been updated to call out the fact the ordering does not impact priority.

**Comment by AceHack** [comment]
So what about allowing for order to make a difference?

**Comment by karann-msft** [comment]
@AceHack - that would be a feature ask. Feel free to file on the home repo - https://github.com/nuget/home/issues

**Comment by AceHack** [comment]
I did https://github.com/NuGet/Home/issues/7938

**Comment by karann-msft** [comment]
Thanks @AceHack - let continue product related coversation on that issue.
