### ISSUE TITLE
How to encrypt password used in packageSourceCredentials

### ISSUE THREAD

**Issue by mathewkuruvila** [NuGet/docs.microsoft.com-nuget#1260]
How exactly can i encrypt the password used in packageSourceCredentials. I couldn't find anywhere mentioning about it.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0ea1390e-db36-6759-3095-ebab9d546fdb
* Version Independent ID: ca88d8c6-0515-a267-aac3-a508c54157ab
* Content: [nuget.config File Reference](https://docs.microsoft.com/en-us/nuget/reference/nuget-config-file)
* Content Source: [docs/reference/nuget-config-file.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/master/docs/reference/nuget-config-file.md)
* Product: **nuget**
* GitHub Login: @karann-msft
* Microsoft Alias: **karann**

**Comment by JamesMBristow2** [comment]
Use the nuget.exe sources command, detailed at https://docs.microsoft.com/en-us/nuget/tools/cli-ref-sources. Make sure to include -UserName, -Password. Use -ConfigFile if you are targeting a configuration other than your user-level config (%AppData%\NuGet\NuGet.Config (Windows) or ~/.nuget/NuGet/NuGet.Config (Mac/Linux) ).
