### ISSUE TITLE
What is the format of the Source parameter's list?

### ISSUE THREAD

**Issue by RobertBernstein-MSFT** [NuGet/docs.microsoft.com-nuget#1262]
Is it space-separated?  Comma-separated?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a31f9836-625a-7ffe-bb24-605bd6fc56c8
* Version Independent ID: 441fbba9-5f9b-289e-a0ca-3f887f5d800c
* Content: [NuGet CLI list command](https://docs.microsoft.com/en-us/nuget/tools/cli-ref-list)
* Content Source: [docs/tools/cli-ref-list.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/master/docs/tools/cli-ref-list.md)
* Product: **nuget**
* GitHub Login: @karann-msft
* Microsoft Alias: **karann**

**Comment by davidalpert** [comment]
furthermore is it possible to indicate in a source parameter whether to use api v2 or v3 syntax for that source?

this documentation could use more detail as to how to use the various options for each of these CLI commands.

**Comment by loic-sharma** [comment]
Thanks for creating this issue! We clarified how to add multiple packages sources: https://github.com/NuGet/docs.microsoft.com-nuget/pull/2241

Please let us know if you have any additional feedback or questions!

**Comment by davidalpert** [comment]
that is helpful and more clear. thank you.
