### ISSUE TITLE
NuGet doesn't appear to work in VS 2017 Community Edition

### ISSUE THREAD

**Issue by tshinkle** [NuGet/docs.microsoft.com-nuget#1267]
I'm trying to do the most basic tutorial in VS 2017 and all I get is the following:
NuGet package restore failed. Please see Error List window for detailed warnings and errors.

Here is the first error of 34:
Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0246	The type or namespace name 'System' could not be found (are you missing a using directive or an assembly reference?)	VotingWeb	C:\Users\tim\source\repos\Voting\VotingWeb\VotingWeb.cs	1	Active

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 906d0438-0338-0167-3a38-d213ee187ddb
* Version Independent ID: b558fa0c-f549-1e6a-c2db-fd2e6a2351be
* Content: [Troubleshooting NuGet Package Restore in Visual Studio](https://docs.microsoft.com/en-us/nuget/consume-packages/package-restore-troubleshooting)
* Content Source: [docs/consume-packages/Package-restore-troubleshooting.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/master/docs/consume-packages/Package-restore-troubleshooting.md)
* Product: **nuget**
* GitHub Login: @karann-msft
* Microsoft Alias: **karann**

**Comment by karann-msft** [comment]
@tshinkle I am moving this issue to the Home repo which the place for exactly this sort of issue.
Can you share the steps to repro the issue and point to the tutorial that you are trying to follow.
Thanks!

**Comment by karann-msft** [comment]
Issue moved to [NuGet/Home #7710](https://github.com/NuGet/Home/issues/7710) via [**ZenHub**](https://www.zenhub.com/)
