### ISSUE TITLE
Hardlinks

### ISSUE THREAD

**Issue by imanushin** [NuGet/docs.microsoft.com-nuget#1268]
How can I ask MS Build to create hardlinks/symlinks for restoring, instead of files copy?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ff707668-94d6-25a5-9139-b18cc1b6b446
* Version Independent ID: 494847b9-4894-0beb-7ffa-39a2359999fa
* Content: [NuGet PackageReference format (package references in project files)](https://docs.microsoft.com/en-us/nuget/consume-packages/package-references-in-project-files)
* Content Source: [docs/consume-packages/Package-References-in-Project-Files.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/master/docs/consume-packages/Package-References-in-Project-Files.md)
* Product: **nuget**
* GitHub Login: @karann-msft
* Microsoft Alias: **karann**

**Comment by Nirmal4G** [comment]
There are `CreateHardLink*` properties for doing that, I recently saw those properties somewhere mention, may be StackOverflow. Let me check and get back to you.

**Comment by Nirmal4G** [comment]
Here's the relevant PR that adds the `SymbolicLinks` feature: Microsoft/msbuild#742

**Comment by Nirmal4G** [comment]
Here's the one I was talking about: [`CreateHardLinks*IfPossible`](https://stackoverflow.com/a/29708236)

**Comment by imanushin** [comment]
Hi @Nirmal4G, this is exact what I wanted. Thank you !!

**Comment by Nirmal4G** [comment]
You're welcome. They defnitely increase performance on larger builds. I'm using it mostly on large solutions containg `>10` projects.

**Comment by Nirmal4G** [comment]
@mairaw 

I don't mind creating a PR. But I have no clue as where to add this. Can you point me to the right file/section?
