### ISSUE TITLE
How to target specific framework?

### ISSUE THREAD

**Issue by JosKrause** [NuGet/docs.microsoft.com-nuget#1275]
How would I ensure that only a specific framework version of a package is installed? e.g. .NET Core App 2.0 dependencies only, so it doesn't traverse the entire dependency tree.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2b3c1240-cc9b-af42-0cdb-a455bad923b5
* Version Independent ID: 7bd8ee0a-5a87-55f2-74d4-40adaa72ea75
* Content: [NuGet Install-Package PowerShell Reference](https://docs.microsoft.com/en-us/nuget/tools/ps-ref-install-package)
* Content Source: [docs/tools/ps-ref-install-package.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/master/docs/tools/ps-ref-install-package.md)
* Product: **nuget**
* GitHub Login: @karann-msft
* Microsoft Alias: **karann**

**Comment by karann-msft** [comment]
the NuGet client makes that determination based on the target framework of your project, and the assets available in the package you are trying to install. Take a package like newtonsoft.json for example, when you install it in a project targeting  .NET Framework 4.5, the assets under lib/net45 are referenced by the project.

**Comment by JosKrause** [comment]
Hi @karann-msft,

Thanks for your reply, but when trying to work with NuGet packages from within **Powershell** (which is what the page is about, Powershell) you don't have a `csproj` or `sln` file to target. Without specifying that you want the package dependency for a specific framework it will download nearly 800MB of packages because it just grabs *ALL* of them.

This makes it next to impossible to grab a package for your script.

**Comment by Mikejo5000** [comment]
There is a clarifying note at the top of the page that the page is specific to PowerShell within the Package Manager Console (VS). So, you will have a csproj and sln.
