### ISSUE TITLE
Example of "Add a direct reference to the project for the higher version of the package that you want to use."

### ISSUE THREAD

**Issue by agilmore30** [NuGet/docs.microsoft.com-nuget#1277]
In your description of this issue (and others where the solution is the same), Please provide an example of "Add a direct reference to the project for the higher version of the package that you want to use." It's not clear how to do this for people new to C# .NET Core development. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0960d68b-f164-4e7e-5cdb-ad70e6f9de89
* Version Independent ID: 82b4d896-1d52-ce2e-c2ff-f76f4308ac56
* Content: [NuGet Warning NU1605](https://docs.microsoft.com/en-us/nuget/reference/errors-and-warnings/nu1605?f1url=https%3A%2F%2Fmsdn.microsoft.com%2Fquery%2Fdev15.query%3FappId%3DDev15IDEF1%26l%3DEN-US%26k%3Dk(NU1605)%26rd%3Dtrue)
* Content Source: [docs/reference/errors-and-warnings/NU1605.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/master/docs/reference/errors-and-warnings/NU1605.md)
* Product: **nuget**
* GitHub Login: @zhili1208
* Microsoft Alias: **lzhi**

**Comment by pfgindy** [comment]
Um, yeah. You guys are not making it easy.

**Comment by BlueMarmalade** [comment]
an alternative could be to create a new project within your app, like a .net standard library, and in it's csproj explicitly write the nuget packages and version you use.  of course, this means whatever function that uses it needs to be in this project, but I find it easier to maintain a large app by separating code that use uncommon nuget libraries from the main app.

**Comment by karann-msft** [comment]
@agilmore30 - you mean clarify that adding a direct reference means installing a nuget package?

**Comment by devnaviworld** [comment]
"Add a direct reference to the project for the higher version of the package that you want to use.".
Please explain how this is done. It's not helpful, it's just another thing you need to google.

**Comment by ozhydkov** [comment]
update base nuget package to latest version, then update child package to needed version. For example, in case of same error if you want to update Xamarin.Forms.Maps package update first Xamarin.Forms to latest version and then do what you need previously to do.
