### ISSUE TITLE
Pack sources inside snupkg

### ISSUE THREAD

**Issue by loicmorvan-ansys** [NuGet/docs.microsoft.com-nuget#1278]
It is not said how to include source files within the snupkg or even if it's possible.
Can you say a little more about that?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 22767e96-d56f-aa81-f1ca-17e256ed617e
* Version Independent ID: d7cdc676-2705-3cb1-bcd6-d1637460d5c7
* Content: [How to publish NuGet symbol packages using the new symbol package format '.snupkg'](https://docs.microsoft.com/en-us/nuget/create-packages/symbol-packages-snupkg)
* Content Source: [docs/create-packages/Symbol-Packages-snupkg.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/master/docs/create-packages/Symbol-Packages-snupkg.md)
* Product: **nuget**
* GitHub Login: @cristinamanum
* Microsoft Alias: **cristinamanu**

**Comment by cristinamanum** [comment]
If source files are manually included in the snupkg the snupkg will fail to be published.
The file extensions allowed inside of a snupkg are documented [here](https://docs.microsoft.com/en-us/nuget/create-packages/symbol-packages-snupkg#nugetorg-symbol-package-constraints)

**Comment by loicmorvan-ansys** [comment]
Thanks for your answer. Indeed the information was there, my bad!
But still, is there a way to upload (and use!) source code files to a nuget server so that we can use them when debugging?

**Comment by cristinamanum** [comment]
There is no need to upload the source files you need only the pdbs. If the pdbs are available (from a symbol server for example) and they are built with SourceLink support or by embeding sources to the pdb the debugger will find the right sources. 
I added below some information that could be a good start.

SourceLink:
https://blog.nuget.org/20180827/Introducing-Source-Code-Link-for-NuGet-packages.html
https://github.com/dotnet/sourcelink#using-source-link-in-net-projects

EmbededSources
https://github.com/dotnet/roslyn/issues/12625
Also you can add <EmbedAllSources>true</EmbedAllSources> in your csproj. 

I hope that this helps.

**Comment by loicmorvan-ansys** [comment]
It helps very much, thanks!

**Comment by chilakamarthi** [comment]
I Included both EmbedAllSources and DebugType in csproj like below.

    <EmbedAllSources>true</EmbedAllSources> 
    <DebugType>portable</DebugType>

Still at the time I debug, though PDB file is downloaded from nuget symbol server, it asks me path for cs files. My understanding is cs files are supposed to be embedded and it should find it automatically,

Any help?

**Comment by karann-msft** [comment]
@chilakamarthi feel free to open an issue on our home repo for product feedback.
