### ISSUE TITLE
Improve documentation - bait and switch pattern, other

### ISSUE THREAD

**Issue by rrelyea** [NuGet/docs.microsoft.com-nuget#1282]
Good feedback in: https://github.com/NuGet/Home/issues/3157 for things to improve about docs.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f1482e18-5f1f-3a8a-3321-66af52879ec5
* Version Independent ID: d70bd2f5-c04b-9207-62a0-4ecb6e8e5ca6
* Content: [Multi-targeting for NuGet Packages](https://docs.microsoft.com/en-us/nuget/create-packages/supporting-multiple-target-frameworks)
* Content Source: [docs/create-packages/Supporting-Multiple-Target-Frameworks.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/master/docs/create-packages/Supporting-Multiple-Target-Frameworks.md)
* Product: **nuget**
* GitHub Login: @karann-msft
* Microsoft Alias: **karann**

**Comment by vatsan-madhavan** [comment]
@rrelyea could this be reactivated and acted upon?

**Comment by JonDouglas** [comment]
I believe this is mostly documented by multi-targeting?

https://docs.microsoft.com/en-us/nuget/create-packages/supporting-multiple-target-frameworks

@vatsan-madhavan is there anything specific for bait & switch that hasn't already been documented?

**Comment by JonDouglas** [comment]
Closing this issue as we haven't had much activity in over a year.
