### ISSUE TITLE
Add docs for 4.9 config option to filter auth types for credentials

### ISSUE THREAD

**Issue by rrelyea** [NuGet/docs.microsoft.com-nuget#1283]
We need to document the new authentication types flag.
More info https://github.com/NuGet/NuGet.Client/pull/2297
This needs done before 4.9 or whenever that PR ships. (we're late)
//cc @rrelyea @NuGet/nuget-client @jmyersmsft

(this new issue replaces #1007 - in an attempt to have it listed in the page that needs fixing)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0ea1390e-db36-6759-3095-ebab9d546fdb
* Version Independent ID: ca88d8c6-0515-a267-aac3-a508c54157ab
* Content: [nuget.config File Reference](https://docs.microsoft.com/en-us/nuget/reference/nuget-config-file#packagesourcecredentials)
* Content Source: [docs/reference/nuget-config-file.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/master/docs/reference/nuget-config-file.md)
* Product: **nuget**
* GitHub Login: @karann-msft
* Microsoft Alias: **karann**

**Comment by karann-msft** [comment]
Not eligible for docs day.
