### ISSUE TITLE
<LICENSE> metadata fields implicitly requires license filename to have an extension

### ISSUE THREAD

**Issue by WilliamXieMSFT** [NuGet/docs.microsoft.com-nuget#1291]
Using dotnet\sdk\2.2.101-rtm-009628 NuGet pack targets, I am getting
`error NU5030 The license file 'LICENSE' does not exist in the package.`

.nuspec file:
```
<metadata>
  <license>LICENSE</license>
</metadata>
```

This error goes away if I add a '.txt' extension to the LICENSE file and update the field.
.nuspec file:
```
<metadata>
  <license>LICENSE.txt</license>
</metadata>
```

**Comment by karann-msft** [comment]
Issue moved to [NuGet/Home #7783](https://github.com/NuGet/Home/issues/7783) via [**ZenHub**](https://www.zenhub.com/)
