### ISSUE TITLE
Further document RestoreSources

### ISSUE THREAD

**Issue by sdolenc** [NuGet/docs.microsoft.com-nuget#1296]
The current documentation for adding "packageSources" wasn't helpful for our .net core 2.1 project.

It looks like the way to go is by adding the following key to the csproj
&lt;RestoreSources&gt; $(RestoreSources);https://newUrl/ &lt;/RestoreSources&gt;

Would it be possible to update this documentation directly or link to an existing page explaining this solution?

FWIW here are a couple of existing projects on github that have already adopted the RestoreSources csproj solution
- https://github.com/PankajPatro/dotnetcoreblazorexp/blob/master/Blazor-dev/src/Microsoft.AspNetCore.Blazor.Templates/content/BlazorContent.CSharp/BlazorContent.CSharp.csproj
- https://github.com/logikuma1024/Konomi/blob/master/Konomi/Konomi.Server/Konomi.Server.csproj
- https://github.com/kristapsstrals/restaurant-kata/blob/master/Restaurant/Restaurant.csproj
- https://github.com/bjorndaniel/cloudbattleships/blob/master/Battleships.BlazorUI/Battleships.BlazorUI/Battleships.BlazorUI.csproj
- https://github.com/mkfilipiuk/2048/blob/master/game2048.Client/game2048.Client.csproj

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0ea1390e-db36-6759-3095-ebab9d546fdb
* Version Independent ID: ca88d8c6-0515-a267-aac3-a508c54157ab
* Content: [nuget.config File Reference](https://docs.microsoft.com/en-us/nuget/reference/nuget-config-file#packagesources)
* Content Source: [docs/reference/nuget-config-file.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/master/docs/reference/nuget-config-file.md)
* Product: **nuget**
* GitHub Login: @karann-msft
* Microsoft Alias: **karann**

**Comment by karann-msft** [comment]
Not eligible for docs-day.

**Comment by JonDouglas** [comment]
@nkolev92 Is there any source code or further explanation of `RestoreSources`?

`Semicolon-delimited list of package sources.`

Best I can find is a few related items:

https://docs.microsoft.com/en-us/nuget/reference/msbuild-targets#restore-properties
https://github.com/NuGet/Home/issues/6045

Is this just a property to define a source in a .csproj rather than nuget.config?

**Comment by nkolev92** [comment]
> Is this just a property to define a source in a .csproj rather than nuget.config?

Yes, pretty much. 

This takes precedence over NuGet.Config. 

It's also how `dotnet restore --source` works.
