### ISSUE TITLE
Nuget 4.7 works, but later ones do not (Service Fabric projects)

### ISSUE THREAD

**Issue by galmok** [NuGet/docs.microsoft.com-nuget#1300]
We are using nuget to restore the packages of our projects, but when we upgraded nuget from version 4.7.1 to 4.8.1 or to 4.9.1, this restore must be run twice to do the work that 4.7.1 does. The newer nugets issue this warning (originating from the Service Fabric project, *.sfproj file):

D:\temp\telemetryperiodservice\TelemetryPeriodServiceSF\TelemetryPeriodServiceSF.sfproj(47,5): error : Unable to find the '..\packages\Microsoft.VisualStudio.Azure.Fabric.MSBuild.1.6.7\build\Microsoft.VisualStudio.Azure.Fabric.Application.props' file. Please restore the 'Microsoft.VisualStudio.Azure.Fabric.MSBuild' Nuget package.

The first package restored is actually the package it complains about.

Using nuget 4.7.1, it seems the mentioned package is already restored which makes all the nuget restore put packages into the projects and not just into the packages folder.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 300985dd-9626-6e0a-d055-73dbbc3633a0
* Version Independent ID: 814d9eaa-25dc-58f2-e0be-a390f3d360b7
* Content: [NuGet 4.9 RTM Release Notes](https://docs.microsoft.com/en-us/nuget/release-notes/nuget-4.9-rtm)
* Content Source: [docs/release-notes/NuGet-4.9-RTM.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/master/docs/release-notes/NuGet-4.9-RTM.md)
* Product: **nuget**
* GitHub Login: @karann-msft
* Microsoft Alias: **karann**

**Comment by karann-msft** [comment]
Issue moved to [NuGet/Home #7784](https://github.com/NuGet/Home/issues/7784) via [**ZenHub**](https://www.zenhub.com/)
