### ISSUE TITLE
.nuspec manifest not created by visual studioe

### ISSUE THREAD

**Issue by tkumark** [NuGet/docs.microsoft.com-nuget#1302]
I followed the above instructions but did not see any .nuspec manifest file created automatically. do we need to create it by our selfe for .net standard or will Visual studio create it. The below line was mentioned in point 2.
"All of the properties here go into the .nuspec manifest that Visual Studio creates for the project."
you have given the example for .nuspec manifest for .Net Framework Package. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 18071970-cf13-78af-ac1d-9adefefdb693
* Version Independent ID: 3bf15a5c-8b3e-0e69-0bf6-03b44654970c
* Content: [Create and publish a .NET Standard package using Visual Studio on Windows](https://docs.microsoft.com/en-us/nuget/quickstart/create-and-publish-a-package-using-visual-studio)
* Content Source: [docs/quickstart/create-and-publish-a-package-using-visual-studio.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/master/docs/quickstart/create-and-publish-a-package-using-visual-studio.md)
* Product: **nuget**
* GitHub Login: @karann-msft
* Microsoft Alias: **karann**

**Comment by karann-msft** [comment]
@tkumark the nuspec file does get generated and is packed as part of the package. The package by default goes into the `bin/<soluton_configuration>/` folder. For example, if you are building in debug, it will go into `bin/debug/`

**Comment by LazZiya** [comment]
The **nuspec** file is generated under `obj/<solution_configuration>/`, and the **nupkg** file is generated under `bin/<solution_configuration>/`

**Comment by lHubertl** [comment]
I also walked through this article and *.nupkg was not generated so I found that I need to tick a checkbox "Generate NuGet Package on Build". "Pack" did not work for me
