### ISSUE TITLE
Signing package

### ISSUE THREAD

**Issue by honzajscz** [NuGet/docs.microsoft.com-nuget#1307]
How could be a package signed using MSBuild like with the "nuget sign" command? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 099102e8-c320-ef50-6821-57519684dc98
* Version Independent ID: 1523dac4-419d-613d-2497-4062f9efd358
* Content: [NuGet pack and restore as MSBuild targets](https://docs.microsoft.com/en-us/nuget/reference/msbuild-targets)
* Content Source: [docs/reference/msbuild-targets.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/master/docs/reference/msbuild-targets.md)
* Product: **nuget**
* GitHub Login: @karann-msft
* Microsoft Alias: **karann**

**Comment by karann-msft** [comment]
@rido-min, thoughts?

**Comment by rido-min** [comment]
What's the goal of signing with MSBuild directly?  
You can always integrate `nuget.exe sign` with MSBuild `<Exec />`.

**Comment by honzajscz** [comment]
We converted all our .NET Framework old style projects to the new SDK style but still using the Full Framework not .NET Core. MSBuild is our work horse for building, strong signing, digital signing and packaging our dlls. Everything from A to Y. However, the package signing step - the Z - is missing in it. 

I could, as you suggest, use **nuget.exe**, what we will eventually end up doing anyway but it is yet another dependency and it is not MSBuild "native". Actually, it is all about convenience.

**Comment by karann-msft** [comment]
@honzajscz, as it turns out signing a package, is not supported with msbuild directly yet. Feel free to file an ask on Home repo - https://duanenewman.net/blog/post/a-better-way-to-override-references-with-packagereference/
