### ISSUE TITLE
Document how dependency for specific framework works

### ISSUE THREAD

**Issue by quasarea** [NuGet/docs.microsoft.com-nuget#1311]
In example I do:

    msbuild /p:Platform=AnyCPU /p:PlatformTarget=AnyCPU /p:Configuration=Release /p:TargetFrameworkVersion=v4.6.1 /restore  /t:Build myproject.csproj 

and it fails due to:

    error NU1101: Unable to find package System.Runtime.CompilerServices.Unsafe. 
    No packages exist with this id in source(s): CompanyVSTS

 **System.Threading.Tasks.Extensions** that I depend on, depends on **System.Runtime.CompilerServices.Unsafe** only in **.NETFramework4.5** while I explicitly set target framework to **v4.6.1** 

I cannot understand what is happening here, migrated from console call of nuget restore to restore target as console is no framework specific (I guess it pulls native dependencies, but maybe I'm wrong) but it seems it is not solving my issue at all.

* Version Independent ID: b7d27caf-5476-2315-f4dc-e413b1be0726

**Comment by karann-msft** [comment]
Sorry, but we don't have the bandwidth to respond to support requests at this time. Please take a look at  https://stackoverflow.com/questions/tagged/nuget
