### ISSUE TITLE
Clearly call out that floating versions are not valid nuspec  versions

### ISSUE THREAD

**Issue by nkolev92** [NuGet/docs.microsoft.com-nuget#1318]
In the dependency section in the nuspec, only version ranges are allowed. 

The floating versions were added years later than the original version range design. 

There's been various customers confused as to how this works because the documentation is not clear enough.

**Comment by Mikejo5000** [comment]
Updating doc. Looks like package versioning doc already mentions this, so just updating the .nuspec reference.
