### ISSUE TITLE
Description does not appear to work

### ISSUE THREAD

**Issue by mattwhitfield** [NuGet/docs.microsoft.com-nuget#1320]
Setting a property called 'PackageDescription' does work - setting a property called 'Description' does not

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 099102e8-c320-ef50-6821-57519684dc98
* Version Independent ID: 1523dac4-419d-613d-2497-4062f9efd358
* Content: [NuGet pack and restore as MSBuild targets](https://docs.microsoft.com/en-us/nuget/reference/msbuild-targets)
* Content Source: [docs/reference/msbuild-targets.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/master/docs/reference/msbuild-targets.md)
* Product: **nuget**
* GitHub Login: @karann-msft
* Microsoft Alias: **karann**

**Comment by karann-msft** [comment]
@mattwhitfield - can you provide the repro steps?
I just tried setting "Description" in the project file and it worked just fine.

**Comment by mattwhitfield** [comment]
The steps I had were just setting properties in the project file - but with GenerateAssemblyInfo set to false. I've actually remixed what we're doing pretty heavily now so I'm not in a position to repro it. Maybe it was just one of those things - so if you can't repro it then it's probably just worth closing...

**Comment by karann-msft** [comment]
@mattwhitfield, closing the issue for now. But if you are able to repro it at a later time, please feel free to reopen the issue. Thanks!
