### ISSUE TITLE
The examples need to cover the usage of each element described on this page or in the schema

### ISSUE THREAD

**Issue by StingyJack** [NuGet/docs.microsoft.com-nuget#1324]
The current examples are missing a bunch of elements.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 06a19d7d-253d-f17f-6421-624c9867473d
* Version Independent ID: cc37eb17-f715-080c-7bfc-9eae868d50ba
* Content: [.nuspec File Reference for NuGet](https://docs.microsoft.com/en-us/nuget/reference/nuspec)
* Content Source: [docs/reference/nuspec.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/master/docs/reference/nuspec.md)
* Product: **nuget**
* GitHub Login: @karann-msft
* Microsoft Alias: **karann**

**Comment by Miles-Davies-HORIBA** [comment]
I would like to use the releaseNotes field but have no real idea how to handle multi-line notes. Is this <xml> <html> text? Does it handle CDATA?

**Comment by StingyJack** [comment]
@Miles-Davies-HORIBA - if you can find an existing nuget package that displays with multiline release notes, you can unzip it and check what the nuspec uses for line breaks

**Comment by StingyJack** [comment]
DependencyGroups is conspicuously absent;

**Comment by StingyJack** [comment]
Why would it ever be OK to close an unfulfilled documentation request?   Just backlog it.
