### ISSUE TITLE
Document "tags" for compound words

### ISSUE THREAD

**Issue by SidShetye** [NuGet/docs.microsoft.com-nuget#1327]
What is the best way to express a compound word like "entity framework" in the `tags` section? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 06a19d7d-253d-f17f-6421-624c9867473d
* Version Independent ID: cc37eb17-f715-080c-7bfc-9eae868d50ba
* Content: [.nuspec File Reference for NuGet](https://docs.microsoft.com/en-us/nuget/reference/nuspec)
* Content Source: [docs/reference/nuspec.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/master/docs/reference/nuspec.md)
* Product: **nuget**
* GitHub Login: @karann-msft
* Microsoft Alias: **karann**

**Comment by Mikejo5000** [comment]
@SidShetye Is this question about whether spaces are OK, and/or capitalization? I'd recommend finding the official terminology and using that.
@karann-msft @nkolev92 in case I'm missing something here.

**Comment by loic-sharma** [comment]
Hello, NuGet.org does not support compound words in a single tag. We recommend you create multiple tags like `entity` and `framework`. As a work around, you can add use a tag like `entity_framework`, `entity-framework`, or `EntityFramework`.

**Comment by SidShetye** [comment]
@Mikejo5000: This is more about what is best for discoverability. In other words, if authors want a positive hit for a "entity framework" user query, all things considered, what should be the input at the `.nuspec` (or equivalently, `.csproj`) file stage?

@loic-sharma : Are there plans to lift that limitation in the near future? If not, of the various suggestions you presented, what's the authoritative **best** recommendation given the current nuget.org indexing and search delivery results? Customers could speculate and experiment but I'm hoping this ticket helps document based on the actual workings.

**Comment by nkolev92** [comment]
> Are there plans to lift that limitation in the near future?
I think this goes beyond nuget.org.
The NuGet pack experiences define the tags as a space delimited list. 

While not saying never, a change like that would have a long tail.

**Comment by loic-sharma** [comment]
> @Mikejo5000: This is more about what is best for discoverability. In other words, if authors want a positive hit for a "entity framework" user query, all things considered, what should be the input at the `.nuspec` (or equivalently, `.csproj`) file stage?

You should make your csproj's tags something like `entity;framework`. This value will get split into `entity` and `framework`, which will match `entity framework` search queries.

**Comment by SidShetye** [comment]
Ok. Perhaps we can limit this to the best recommended given today’s limitations?
