### ISSUE TITLE
Description for "title" element is false; it is not used with Visual Studio's Package Manager

### ISSUE THREAD

**Issue by duckfist** [NuGet/docs.microsoft.com-nuget#1329]
In the article, under "Optional Metadata Elements", the current description of the "&lt;title&gt;" element is as follows:
"A human-friendly title of the package, typically used in UI displays as on nuget.org and the Package Manager in Visual Studio. If not specified, the package ID is used."

However, the contents of &lt;title&gt; are not used for the UI display in Visual Studio's Package Manager (although it would be incredibly helpful if it did). Instead, only the ID element is used for display in the Package Manager.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 06a19d7d-253d-f17f-6421-624c9867473d
* Version Independent ID: cc37eb17-f715-080c-7bfc-9eae868d50ba
* Content: [.nuspec File Reference for NuGet](https://docs.microsoft.com/en-us/nuget/reference/nuspec)
* Content Source: [docs/reference/nuspec.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/master/docs/reference/nuspec.md)
* Product: **nuget**
* GitHub Login: @karann-msft
* Microsoft Alias: **karann**

**Comment by Mikejo5000** [comment]
Looks like this was fixed in #1329
