### ISSUE TITLE
Quickstart for New NuGet users

### ISSUE THREAD

**Issue by DSivtsov** [NuGet/docs.microsoft.com-nuget#1337]
I'm a new NuGet user.
I was gone to this project by link from GitHub related to problem with use System.Net (class HttpWebRequest) with current standard compiler (set of libraries) of VS 2017.
When I came to this page, I couldn't understand how i can use demanded to me package from NuGet, because on this page isn't clearly described how it will work with standard environment of VS 2017 (now it's clear for me, but for first time wasn't).

Could I recommend, to add additional information in the begin article between “Prerequisites” & “Create a project“ additional subsection (may be named as "Summary") where was wroten similar as:
To use any package from GitHub demanded:
1.	Create a VS Project
2.	Import demanded package from NuGet server (standard source – nuget.org), as result it’s a copy files from package to the current project directory and to add reference in the current project (packages.config).
3.	Add corresponding statement (“using …”, for c#) to your code.

After that use standard VS instruments to build & run your project.
Below it described on example of  the popular Newtonsoft.Json package (You can install it for test, but it isn't demanded to all our projects using some GitHub packages).

With Best Regards.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ef71b45e-0bb6-6e61-3b42-8e8f150db9fb
* Version Independent ID: 129fb470-7186-059a-fbe8-29b1caf96bf9
* Content: [Introductory Guide to Using NuGet Packages from within Visual Studio](https://docs.microsoft.com/en-gb/nuget/quickstart/install-and-use-a-package-in-visual-studio#)
* Content Source: [docs/quickstart/install-and-use-a-package-in-visual-studio.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/master/docs/quickstart/install-and-use-a-package-in-visual-studio.md)
* Product: **nuget**
* GitHub Login: @karann-msft
* Microsoft Alias: **karann**

**Comment by karann-msft** [comment]
Thansk for the feedback!
