### ISSUE TITLE
dotnet cli does not seem to support updating packages

### ISSUE THREAD

**Issue by ashmind** [NuGet/docs.microsoft.com-nuget#1338]
The table has "Update packages" ticked for `dotnet cli`, but I can't find that in the CLI docs.
There is `dotnet add package`, but that always adds the package, even if it wasn't used before.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3460a9b2-3b49-1cda-add2-14d26e217716
* Version Independent ID: 95b91106-faff-c7f6-3699-94d643b5cf73
* Content: [Installing NuGet client tools](https://docs.microsoft.com/en-us/nuget/install-nuget-client-tools#feature-availability)
* Content Source: [docs/install-nuget-client-tools.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/master/docs/install-nuget-client-tools.md)
* Product: **nuget**
* GitHub Login: @karann-msft
* Microsoft Alias: **karann**

**Comment by Mikejo5000** [comment]
The add command can update a package. See docs in this new topic:
https://docs.microsoft.com/en-us/nuget/consume-packages/install-use-packages-dotnet-cli#update-a-package
