### ISSUE TITLE
Update required: Create a nuget.org account step

### ISSUE THREAD

**Issue by ClydeDz** [NuGet/docs.microsoft.com-nuget#1339]
Create a nuget.org account step in the prerequisites section needs to reflect the current sign in with Microsoft account process.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 18071970-cf13-78af-ac1d-9adefefdb693
* Version Independent ID: 3bf15a5c-8b3e-0e69-0bf6-03b44654970c
* Content: [Create and publish a .NET Standard package using Visual Studio on Windows](https://docs.microsoft.com/en-us/nuget/quickstart/create-and-publish-a-package-using-visual-studio#feedback)
* Content Source: [docs/quickstart/create-and-publish-a-package-using-visual-studio.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/master/docs/quickstart/create-and-publish-a-package-using-visual-studio.md)
* Product: **nuget**
* GitHub Login: @karann-msft
* Microsoft Alias: **karann**

**Comment by karann-msft** [comment]
Are you referring to this line? 
> "Register for a free account on nuget.org if you don't have one already. Creating a new account sends a confirmation email. You must confirm the account before you can upload a package."

**Comment by ClydeDz** [comment]
Yes. I've created a PR #1340 with a potential update but I'm happy to reword it if necessary.

**Comment by karann-msft** [comment]
This has been fixed! Thanks, @ClydeDz !
