### ISSUE TITLE
Nuget packages restore is not working

### ISSUE THREAD

**Issue by slishnevsky** [NuGet/docs.microsoft.com-nuget#1341]
In Visual Studio 2017 Enterprise (Build 15.9.8)
In VS Settings I have all options for Package Restore turned ON.
When I load a project, it should automatically restore all nuget packages.
Automatic nuget package restore is not working.

**Comment by karann-msft** [comment]
Please file an isue on the home repo for product feedback - https://github.com/NuGet/Home/issues/new
