### ISSUE TITLE
ASP.NET Web Application (.net framework) package reference

### ISSUE THREAD

**Issue by stefanelll123** [NuGet/docs.microsoft.com-nuget#1342]
I tried to migrate package.config to Package reference on a ASP.NET Web Application (.net framework), and I had the following error: "Operation failed. Project is not eligible for migration. Either the project is not packages.config based or doesn't support PackageReference yet.

**What I did:** I set in Nuget package manager the default package manager format to be PackageReference, I deleted the package.config and all the references and nugets from the project and I install them again. Now the references are install with PackageReference.

**First of all, the PackageReference is supported by ASP.NET Web Application (.net framework)?**

**Do you see any issues on this approach and do you think I can have some problems with the tfs build?**

**Comment by wagnerteixeira** [comment]
I'm having the same problem, I can not migrate a web application to PackageReference. I did a test creating a new web application in Visual Studio 2017 and I also did not get it.

The ProjectTypeIds are <ProjectTypeGuids> {349c5851-65df-11da-9384-00065b846f21}; {fae04ec0-301f-11d3-bf4b-00c04f79efbc} </ ProjectTypeGuids>

Is PackageReference compatible with Web Application?

**Comment by Mikejo5000** [comment]
Support is limited for ASP.NET Web apps:
https://docs.microsoft.com/en-us/nuget/consume-packages/package-references-in-project-files#project-type-support

which links to this GitHub feature tracking issue:
https://github.com/NuGet/Home/issues/5877

**Comment by hpavon** [comment]
> Support is limited for ASP.NET Web apps:
> https://docs.microsoft.com/en-us/nuget/consume-packages/package-references-in-project-files#project-type-support
> 
> which links to this GitHub feature tracking issue:
> [NuGet/Home#5877](https://github.com/NuGet/Home/issues/5877)

Half a year later, is there any plans to fix it? My boss would really appreciate that I finish fooling around with the System.Net.Http version mismatch that I'm facing these days.

**Comment by 0liver** [comment]
There are - unfortunately - unsurpassable problems when switching from PC (packages.config) to PR (PackageReference). Here's a solid summary of those: https://github.com/NuGet/Home/issues/5877#issuecomment-518310126.

For anyone who knows they don't use any packages that contain install/uninstall scripts and which don't adjust the web.config in your project, you can manually fiddle your way through the update using the instructions from here: https://stackoverflow.com/a/65284840/177710

ATTENTION: This **will** break your app or build process or something/somewhere/sometime if you reference packages that rely on custom activity after installation.
