### ISSUE TITLE
This topic doesn't appear to be connected to the Table of Contents for MSBuild

### ISSUE THREAD

**Issue by Paul-Dempsey** [NuGet/docs.microsoft.com-nuget#1349]
This makes the information much harder to find (and makes me wonder how much other vital information has been hidden in disconnected topics).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 099102e8-c320-ef50-6821-57519684dc98
* Version Independent ID: 1523dac4-419d-613d-2497-4062f9efd358
* Content: [NuGet pack and restore as MSBuild targets](https://docs.microsoft.com/en-us/nuget/reference/msbuild-targets#feedback)
* Content Source: [docs/reference/msbuild-targets.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/master/docs/reference/msbuild-targets.md)
* Product: **nuget**
* GitHub Login: @karann-msft
* Microsoft Alias: **karann**

**Comment by Paul-Dempsey** [comment]
Sorry, wrong section -- I though I was under MSBuild, now I'm in nuget, but still -- the topic isn't connected to the TOC

**Comment by karann-msft** [comment]
umm...what do you mean by "not connected to the TOC" because I can see the topic in the TOC.

![image](https://user-images.githubusercontent.com/16904420/54469421-ff720c00-4754-11e9-9d32-fa58f3d9762b.png)

**Comment by Paul-Dempsey** [comment]
Turns out I was just confused by the mismatch between the TOC and the topic title. There's no good reason these can't be the same: "MSBuild pack and restore targets".

**Comment by karann-msft** [comment]
"MSBuild Targets" in context of NuGet conveys sufficient context in my opinion. You were coming from a different docset and that docset should do a better job at setting expectations that you are being taken to a different docset. Also, putting the entire title makes it too long for the TOC.
