### ISSUE TITLE
Missing info on using the new MSBuild pack target, or .Net Core check box

### ISSUE THREAD

**Issue by Paul-Dempsey** [NuGet/docs.microsoft.com-nuget#1350]
The entire section on Create Packages manages to entirely omit creating packages without a nuspe, by checking a box in a .NET Core project properties, or by using the new MSBuild targets which is buried in the reference at https://docs.microsoft.com/en-us/nuget/reference/msbuild-targets

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f35f4267-e5e3-ddcf-d3e4-479fb233ce9f
* Version Independent ID: 6d49d66f-f777-7e44-3a45-723e3ad09a59
* Content: [How to create a NuGet package](https://docs.microsoft.com/en-us/nuget/create-packages/creating-a-package)
* Content Source: [docs/create-packages/Creating-a-Package.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/master/docs/create-packages/Creating-a-Package.md)
* Product: **nuget**
* GitHub Login: @karann-msft
* Microsoft Alias: **karann**

**Comment by karann-msft** [comment]
We have quickstarts at the very top of the TOC https://docs.microsoft.com/en-us/nuget/quickstart/create-and-publish-a-package-using-visual-studio
Did you happen to see those?

**Comment by Paul-Dempsey** [comment]
I expect something more than only some random quickstart to cover the relevant material. None of the quickstart titles specifically mention .net core. I expect comprehensive overviews that give me the concepts and pointers to deeper information.

**Comment by Mikejo5000** [comment]
There's a new topic on creating a package with dotnet CLI. There is also some info on MSBuild pack, which might need to be expanded into a separate, short topic.
https://docs.microsoft.com/en-us/nuget/create-packages/creating-a-package-dotnet-cli
