### ISSUE TITLE
Document GeneratePathProperty

### ISSUE THREAD

**Issue by nkolev92** [NuGet/docs.microsoft.com-nuget#1355]
Per @anangaur's request. 

https://github.com/NuGet/Home/issues/7843#issuecomment-474626825

This issue covers the documentation for the full feature.

**Comment by anangaur** [comment]
Note: We should explain how to use this property for multiple scenarios including the scenario to pick specific assets group during build that's not automatically picked. Similar to: http://duanenewman.net/blog/post/forcing-a-specific-target-platform-with-packagereference

**Comment by karann-msft** [comment]
dupe of https://github.com/NuGet/docs.microsoft.com-nuget/issues/1802
