### ISSUE TITLE
Cannot add code to project

### ISSUE THREAD

**Issue by RLCongithub** [NuGet/docs.microsoft.com-nuget#1356]
I am trying to use a piece of code from nuget using Visual Studio Express 2013. I can invoke the "Manage Nuget Packages" and the nupkg of interest shows under the "updates ->all item, but I cannot see how to add the code to the project. What am I missing?

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bd0c2ac7-8837-d4fd-955b-6a5b261592f3
* Version Independent ID: 4c62f271-70ea-8537-f670-b59bb702c4c0
* Content: [What is NuGet and what does it do?](https://docs.microsoft.com/en-us/nuget/what-is-nuget#feedback)
* Content Source: [docs/what-is-nuget.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/master/docs/what-is-nuget.md)
* Product: **nuget**
* GitHub Login: @karann-msft
* Microsoft Alias: **karann**

**Comment by karann-msft** [comment]
@RLCongithub - you can referene the types and methods exposed by the nuget pacakge you reference. The source/implementation of the package won't appear in your project as you shouldn't have to worry about that.
Take a look at this quickstart. Although its for VS 2017, it shouldn't be terrible different in VS 2013 - https://docs.microsoft.com/en-us/nuget/quickstart/install-and-use-a-package-in-visual-studio

**Comment by RLCongithub** [comment]
Doesn't work.  nuget.org appears but Newtonsoft.Json is not in dropdown list and cannot be found in search. Dead end.
Please respond.
Ron Chandlerhobbitdome@aol.com


-----Original Message-----

**Comment by RLCongithub** [comment]
You have not helped.


-----Original Message-----

**Comment by karann-msft** [comment]
@RLCongithub - this repo is for docs. File an issue on the Home repo.
