### ISSUE TITLE
ProjectReference is undocumented

### ISSUE THREAD

**Issue by rossng** [NuGet/docs.microsoft.com-nuget#1357]
I can't find any documentation of how `ProjectReference` works in the docs. Given that it's a) pretty critical and b) has non-intuitive behaviour, I think it would be very useful to add.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ff707668-94d6-25a5-9139-b18cc1b6b446
* Version Independent ID: 494847b9-4894-0beb-7ffa-39a2359999fa
* Content: [NuGet PackageReference format (package references in project files)](https://docs.microsoft.com/en-us/nuget/consume-packages/package-references-in-project-files)
* Content Source: [docs/consume-packages/Package-References-in-Project-Files.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/master/docs/consume-packages/Package-References-in-Project-Files.md)
* Product: **nuget**
* GitHub Login: @karann-msft
* Microsoft Alias: **karann**

**Comment by karann-msft** [comment]
@rossng - that would be a question for msbuild - https://github.com/Microsoft/msbuild/blob/master/documentation/ProjectReference-Protocol.md
