### ISSUE TITLE
restore - document other msbuild properties

### ISSUE THREAD

**Issue by rrelyea** [NuGet/docs.microsoft.com-nuget#1358]
https://github.com/NuGet/Home/wiki/%5BSpec%5D-NuGet-settings-in-MSBuild

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ff707668-94d6-25a5-9139-b18cc1b6b446
* Version Independent ID: 494847b9-4894-0beb-7ffa-39a2359999fa
* Content: [NuGet PackageReference format (package references in project files)](https://docs.microsoft.com/en-us/nuget/consume-packages/package-references-in-project-files)
* Content Source: [docs/consume-packages/Package-References-in-Project-Files.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/master/docs/consume-packages/Package-References-in-Project-Files.md)
* Product: **nuget**
* GitHub Login: @karann-msft
* Microsoft Alias: **karann**

**Comment by nkolev92** [comment]
I'll fix this one next week.

**Comment by rrelyea** [comment]
Once we have added this, @loic-sharma had a good suggestion...add a link from the known issue in 4.9 and 5.0 release notes to the docs for RestoreAdditionalProjectSources

**Comment by nkolev92** [comment]
https://github.com/NuGet/docs.microsoft.com-nuget/pull/1395
