### ISSUE TITLE
Warning or Error?

### ISSUE THREAD

**Issue by mrlacey** [NuGet/docs.microsoft.com-nuget#1365]
This shows up in VS as a Warning but as it prevents the solution from building it should be an 'Error'.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0960d68b-f164-4e7e-5cdb-ad70e6f9de89
* Version Independent ID: 82b4d896-1d52-ce2e-c2ff-f76f4308ac56
* Content: [NuGet Warning NU1605](https://docs.microsoft.com/en-us/nuget/reference/errors-and-warnings/nu1605?f1url=https%3A%2F%2Fmsdn.microsoft.com%2Fquery%2Fdev15.query%3FappId%3DDev15IDEF1%26l%3Den-US%26k%3Dk(NU1605)%26rd%3Dtrue)
* Content Source: [docs/reference/errors-and-warnings/NU1605.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/master/docs/reference/errors-and-warnings/NU1605.md)
* Product: **nuget**
* GitHub Login: @zhili1208
* Microsoft Alias: **lzhi**

**Comment by karann-msft** [comment]
@mrlacey thanks for the feedback. For prouct feedback use the "Product feedback" button

![image](https://user-images.githubusercontent.com/16904420/55251422-c4201480-520d-11e9-80ea-60399724a49c.png)
