### ISSUE TITLE
Create Security Best Practice / Guidance doc

### ISSUE THREAD

**Issue by rrelyea** [NuGet/docs.microsoft.com-nuget#1366]
As an offshoot task from ADO bug# 784553, we should improve our public guidance on using NuGet Securely.

I'd imagine it would cover things like this (focused on package consumers):

IDEAL: use latest nuget client (nuget.exe, VS release, dotnet sdk)
OR AT LEAST: use a release that is in current support.

use https: for any networked feeds.
use tls 1.2 on any corporate feeds
use client trust policies
use lock files to ensure that the package you use never changes, even if somebody changes content.
for internal packages, use prefix that is reserved on nuget.org by your organization.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6f32fcb5-8641-9062-83bd-2c8c09aab872
* Version Independent ID: 12404cbd-0105-957e-2875-bb91904fc359
* Content: [Overview and workflow of using NuGet packages](https://docs.microsoft.com/en-us/nuget/consume-packages/overview-and-workflow)
* Content Source: [docs/consume-packages/Overview-and-Workflow.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/master/docs/consume-packages/Overview-and-Workflow.md)
* Product: **nuget**
* GitHub Login: @karann-msft
* Microsoft Alias: **karann**

**Comment by JonDouglas** [comment]
#2227 Related & collecting issues to help define the conceptual doc.

**Comment by anangaur** [comment]
1 of the 2 can be closed IMO.

**Comment by JonDouglas** [comment]
Completed via https://github.com/NuGet/docs.microsoft.com-nuget/pull/2309

If we should add more guidance around HTTPS & TLS, please open up an issue or PR against the doc :)
