### ISSUE TITLE
Documentation examples don't show certificate path

### ISSUE THREAD

**Issue by timheuer** [NuGet/docs.microsoft.com-nuget#1381]
The `sign` argument requires a parameter to specify some aspect of the certificate to be used for signing.  The examples provided don't provide any examples and would fail if used.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 425e8072-43a4-bce5-5044-e90190188fe9
* Version Independent ID: 0ff711b0-675b-b032-800b-bb9cb14507f5
* Content: [NuGet CLI sign command](https://docs.microsoft.com/en-us/nuget/tools/cli-ref-sign#feedback)
* Content Source: [docs/tools/cli-ref-sign.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/master/docs/tools/cli-ref-sign.md)
* Product: **nuget**
* GitHub Login: @dtivel
* Microsoft Alias: **dtivel**

**Comment by timheuer** [comment]
@Mikejo5000 can we keep this open until fixed?

**Comment by heng-liu** [comment]
I tried the following command in manual testing:
`nuget sign .\beforeSigning\package1.1.0.0.nupkg -CertificatePath C:\demo0622\FC25325B225D6B15128A8220EF4091F06D55D8F5.pfx`

**Comment by JonDouglas** [comment]
Resolved via https://github.com/NuGet/docs.microsoft.com-nuget/pull/2129

If anything else needs added, let us know!
