### ISSUE TITLE
Supercedes Is Misspelled

### ISSUE THREAD

**Issue by ColbyTaitAfrica** [NuGet/docs.microsoft.com-nuget#1388]
Supercedes Is misspelled in the note regarding multi-targeting

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bd0c2ac7-8837-d4fd-955b-6a5b261592f3
* Version Independent ID: 4c62f271-70ea-8537-f670-b59bb702c4c0
* Content: [What is NuGet and what does it do?](https://docs.microsoft.com/en-us/nuget/what-is-nuget#feedback)
* Content Source: [docs/what-is-nuget.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/master/docs/what-is-nuget.md)
* Product: **nuget**
* GitHub Login: @karann-msft
* Microsoft Alias: **karann**

**Comment by karann-msft** [comment]
Thanks for catching that. I'll have that fixed.
We also accept and encourage contributions. It is super easy - click the edit button at top of the page and submit a PR
![image](https://user-images.githubusercontent.com/16904420/55758068-92c3f780-5a0a-11e9-8f1e-ba2c8d5be0e3.png)

**Comment by ColbyTaitAfrica** [comment]
Well duh!  LOL.  Thanks.  I was in a hurry and misspelled words jump out at me so I didn’t take the time to notice the edit feature.

Thanks for closing this out.

Colby

**Comment by karann-msft** [comment]
There's always next time! Thanks again! :)
