### ISSUE TITLE
Why the CLI after all these years?

### ISSUE THREAD

**Issue by Korporal** [NuGet/docs.microsoft.com-nuget#1389]
It's incredible that Microsoft have still not added GUI publishing support for nuget packages into Visual Studio. I half expected to see something appear in Visual Studio 2019 but alas no. I can use the GUI to edit package details, I can use the GUI to run "pack" but then I must open a command window (which will no doubt require me to enter a bunch of CD commands to get to the right folder, then perhaps edit my "path" setting to ensure I can find nuget.exe) and enter some cryptic command and hope I don't mistype anything.

Why have Microsoft STILL no added this support?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 18071970-cf13-78af-ac1d-9adefefdb693
* Version Independent ID: 3bf15a5c-8b3e-0e69-0bf6-03b44654970c
* Content: [Create and publish a .NET Standard package using Visual Studio on Windows](https://docs.microsoft.com/en-us/nuget/quickstart/create-and-publish-a-package-using-visual-studio)
* Content Source: [docs/quickstart/create-and-publish-a-package-using-visual-studio.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/master/docs/quickstart/create-and-publish-a-package-using-visual-studio.md)
* Product: **nuget**
* GitHub Login: @karann-msft
* Microsoft Alias: **karann**

**Comment by karann-msft** [comment]
Issue moved to [NuGet/Home #7975](https://github.com/NuGet/Home/issues/7975) via [**ZenHub**](https://www.zenhub.com/)
