### ISSUE TITLE
myProject

### ISSUE THREAD

**Issue by BernaEryigit** [NuGet/docs.microsoft.com-nuget#1392]
deny

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 729fede5-f7cb-2543-ff1a-d743bf909f0c
* Version Independent ID: 42f1258c-974f-5321-8817-395921e95581
* Content: [How to Publish a NuGet Package](https://docs.microsoft.com/en-us/nuget/create-packages/publish-a-package#feedback)
* Content Source: [docs/create-packages/Publish-a-package.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/master/docs/create-packages/Publish-a-package.md)
* Product: **nuget**
* GitHub Login: @karann-msft
* Microsoft Alias: **karann**

**Comment by karann-msft** [comment]
closed as spam.
