### ISSUE TITLE
Misleading information on specifying versions for prerelease packages

### ISSUE THREAD

**Issue by mahalex** [NuGet/docs.microsoft.com-nuget#1396]
The page suggests two ways of creating prerelease packages: editing a .nuspec file, or specifying `AssemblyInformationalVersionAttribute`. In my view, this doesn't work, and the phrase "NuGet picks up this value instead of the one specified in the AssemblyVersion attribute, which does not support semantic versioning" is misleading. The correct way to provide a package version to NuGet (specifying a `PackageVersion` property) is described on a totally different page: https://docs.microsoft.com/en-us/dotnet/standard/library-guidance/nuget

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 19c82e43-a3ec-102d-38c4-9ca1a09e98b7
* Version Independent ID: 9b037f92-00d4-de61-4295-ddfe3027dbe1
* Content: [Pre-release versions in NuGet packages](https://docs.microsoft.com/en-us/nuget/create-packages/prerelease-packages#feedback)
* Content Source: [docs/create-packages/Prerelease-Packages.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/master/docs/create-packages/Prerelease-Packages.md)
* Product: **nuget**
* GitHub Login: @karann-msft
* Microsoft Alias: **karann**

**Comment by karann-msft** [comment]
Thanks @mahalex! The PR from @loic-sharma should address that concern and it is now live.
