### ISSUE TITLE
Why CLI

### ISSUE THREAD

**Issue by Korporal** [NuGet/docs.microsoft.com-nuget#1399]
It's frankly ridiculous that Visual Studio provides zero support for the last publish step. Even after a decade of asking for this Microsoft has simply refused to do this. It is absurd.

**Comment by karann-msft** [comment]
@Korporal - while we appreciate the feedback, creating multiple duplicate issues seldom help. 
Closing as duplicate of https://github.com/NuGet/docs.microsoft.com-nuget/issues/1389 which you created.
