### ISSUE TITLE
When to use NuGet Client Sdk over NuGet API

### ISSUE THREAD

**Issue by stg609** [NuGet/docs.microsoft.com-nuget#1400]
"Not to be confused with the NuGet Web API" is not enough for me to understand the differences between each other, and when to use one over another?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cb17b741-1635-af19-e74b-d9921b0bd1ab
* Version Independent ID: 740217ba-335d-6401-64a1-d2f5d8e74f82
* Content: [NuGet Client SDK](https://docs.microsoft.com/en-us/nuget/reference/nuget-client-sdk)
* Content Source: [docs/reference/NuGet-Client-SDK.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/master/docs/reference/NuGet-Client-SDK.md)
* Product: **nuget**
* GitHub Login: @karann-msft
* Microsoft Alias: **karann**

**Comment by karann-msft** [comment]
The NuGet "Web" APIs are a set of HTTP endpoints exposed by a nuget server such as NuGet.org.
The NuGet "Client" SDK is the set of libraries that expose nuget client (nuget.exe) functionality.

For example - when installing a package using nuget.exe, it calls the NuGet.org v3 endpoint to get the package, and then installs it into the target project.

What is your scenario?

**Comment by loic-sharma** [comment]
@stg609, does this change make it a little clearer? Please let us know if you have any suggestions! https://github.com/NuGet/docs.microsoft.com-nuget/pull/1409

**Comment by karann-msft** [comment]
@stg609 please reopen the issue if you feel the updates don't resolve your concern.

**Comment by stg609** [comment]
Sorry for the late feedback. I was busy on doing other projects these days.

Our scenerio is to fetch package from local nuget gallery, and unzip the package. So, does it mean I should use NuGet "Web" API directly? Currently, I was doing the same thing using NuGet Client SDK.

BTW, to make use of the NuGet client SDK, does it require the client machine to have the nuget.exe? Thanks.

@loic-sharma

**Comment by loic-sharma** [comment]
No worries! The NuGet client SDK should be a good fit for your scenario, you shouldn't need to move to the NuGet "Web" API. 

You do need to install nuget.exe on your machine to use the NuGet client SDK.

**Comment by stg609** [comment]
Thanks very much!
