### ISSUE TITLE
NuGet wont accept license tag

### ISSUE THREAD

**Issue by quantumtunneling** [NuGet/docs.microsoft.com-nuget#1403]
The example license tag here will not be accepted by NuGet.org for upload. If I try to specify:

&lt;license type="expression"&gt;MIT&lt;/license&gt;

It says that I need to use the full URL. When I use the full URL, it says to URL encode it. When I URL encode it, it says there are invalid characters. INCREDIBLY frustrating. Your example license should be accepted. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 06a19d7d-253d-f17f-6421-624c9867473d
* Version Independent ID: cc37eb17-f715-080c-7bfc-9eae868d50ba
* Content: [.nuspec File Reference for NuGet](https://docs.microsoft.com/en-us/nuget/reference/nuspec#feedback)
* Content Source: [docs/reference/nuspec.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/master/docs/reference/nuspec.md)
* Product: **nuget**
* GitHub Login: @karann-msft
* Microsoft Alias: **karann**

**Comment by karann-msft** [comment]
@quantumtunneling - can you specify how you are creating the package? 
Some background - the new "license" tag is not understood by old clients. To maintain backward compat, `nuget pack` or `dotnet pack` will also insert a licenseUrl and it's value is determined by what you put in the "license". Now to prevent abuse, nuget.org will validate if you went and modified it. If you did, such packages would be rejected.

**Comment by Mikejo5000** [comment]
Need more info to identify issues.
