### ISSUE TITLE
WHERE?

### ISSUE THREAD

**Issue by serhioV** [NuGet/docs.microsoft.com-nuget#1410]
Where should we run all the mentioned commands? in the command line, VS Developer prompt, package management console? where?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a3b20c46-c5f1-3a2a-738d-8aa8e69cf10c
* Version Independent ID: 7055e752-859b-6106-6802-70010d0305d9
* Content: [NuGet Package Restore](https://docs.microsoft.com/en-us/nuget/consume-packages/package-restore#feedback)
* Content Source: [docs/consume-packages/Package-Restore.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/master/docs/consume-packages/Package-Restore.md)
* Product: **nuget**
* GitHub Login: @karann-msft
* Microsoft Alias: **karann**

**Comment by karann-msft** [comment]
which command are you referring to specifically?
Towards the top, the page talks about the different ways a restore maybe triggered. Each of those bullets is almost a different tool and has links to more details specific to that tool. For example, the dotnet CLI links to [dotnet restore](https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-restore?tabs=netcore2x)

**Comment by Mikejo5000** [comment]
Fixed in #1512
