### ISSUE TITLE
\buildCrossTargeting or \buildMultiTargeting

### ISSUE THREAD

**Issue by Igorbek** [NuGet/docs.microsoft.com-nuget#1412]
It seems the folder `\buildCrossTargeting` was renamed to `\buildMultiTargeting`, but docs still refer to older name.
See https://github.com/NuGet/Home/issues/4098
Should it be changed?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f35f4267-e5e3-ddcf-d3e4-479fb233ce9f
* Version Independent ID: 6d49d66f-f777-7e44-3a45-723e3ad09a59
* Content: [How to create a NuGet package](https://docs.microsoft.com/en-us/nuget/create-packages/creating-a-package#including-msbuild-props-and-targets-in-a-package)
* Content Source: [docs/create-packages/Creating-a-Package.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/master/docs/create-packages/Creating-a-Package.md)
* Product: **nuget**
* GitHub Login: @karann-msft
* Microsoft Alias: **karann**

**Comment by karann-msft** [comment]
@Igorbek thanks for catching that AND fixing it!
