### ISSUE TITLE
Sample given in this page will result into error.

### ISSUE THREAD

**Issue by egbertn** [NuGet/docs.microsoft.com-nuget#1417]
It seems that XDT transforms have changed so current sample will give the following error
 No element in the source document matches '/configuration/system.webServer/modules'

To solve this, a new xdt attribute must be added.

&lt;system.webServer xdt:Transform="InsertIfMissing"&gt;
        &lt;modules xdt:Transform="InsertIfMissing"&gt;
            &lt;add name="ContosoUtilities" type="Contoso.Utilities" xdt:Transform="InsertIfMissing"/&gt;
            &lt;add name="MyNuModule" type="Sample.MyNuModule"  xdt:Transform="InsertIfMissing"/&gt;
        &lt;/modules&gt;
    &lt;/system.webServer&gt;
xdt:Transform="InsertIfMissing"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 40bb9dee-46d6-4064-83e8-ba2e22ac6afe
* Version Independent ID: aac0bbd8-645b-ccf8-bec9-e0d970c8b089
* Content: [Source and config file transformations for NuGet packages](https://docs.microsoft.com/en-us/nuget/create-packages/source-and-config-file-transformations)
* Content Source: [docs/create-packages/Source-and-Config-File-Transformations.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/master/docs/create-packages/Source-and-Config-File-Transformations.md)
* Product: **nuget**
* GitHub Login: @karann-msft
* Microsoft Alias: **karann**

**Comment by donnie-msft** [comment]
Think this one is similar/related https://github.com/NuGet/docs.microsoft.com-nuget/issues/1907
