### ISSUE TITLE
what is the RestoreProjectStyle  option to force packages.config?

### ISSUE THREAD

**Issue by StingyJack** [NuGet/docs.microsoft.com-nuget#1418]
I have a project that will *not* stop trying to use package ref. I've... 

- cleaned the solution (only has the one project) 
- closed VS
- deleted the bin, obj, and .vs folders 
- deleted any .user files
- removed any trace of &lt;PackageReference&gt; from the csproj
- added a packages.config file, formatted as correctly as I can see (where's the xsd???)
- opened VS
- made sure that Tools--&gt;Options--&gt; Nuget PM has packages.config as the default selection

... then opened the solution and tried to add the Microsoft.TeamFoundationServer.Client package to the project, and every time its adding it as Package Reference. Visual Studio needs to honor the default format setting, I've logged a separate bug for that already. Here, I'm asking that the missing documentation element is filled in, so I can try to use it to force the use of packages.config.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ff707668-94d6-25a5-9139-b18cc1b6b446
* Version Independent ID: 494847b9-4894-0beb-7ffa-39a2359999fa
* Content: [NuGet PackageReference format (package references in project files)](https://docs.microsoft.com/en-us/nuget/consume-packages/package-references-in-project-files)
* Content Source: [docs/consume-packages/Package-References-in-Project-Files.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/master/docs/consume-packages/Package-References-in-Project-Files.md)
* Product: **nuget**
* GitHub Login: @karann-msft
* Microsoft Alias: **karann**

**Comment by AndyLysenko** [comment]
> I have a project that will _not_ stop trying to use package ref. I've...
> 
> * cleaned the solution (only has the one project)
> * closed VS
> * deleted the bin, obj, and .vs folders
> * deleted any .user files
> * removed any trace of <PackageReference> from the csproj
> * added a packages.config file, formatted as correctly as I can see (where's the xsd???)
> * opened VS
> * made sure that Tools-->Options--> Nuget PM has packages.config as the default selection
> 
> ... then opened the solution and tried to add the Microsoft.TeamFoundationServer.Client package to the project, and every time its adding it as Package Reference. Visual Studio needs to honor the default format setting, I've logged a separate bug for that already. Here, I'm asking that the missing documentation element is filled in, so I can try to use it to force the use of packages.config.
> 
> #### Document Details
> ⚠ _Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking._
> 
> * ID: ff707668-94d6-25a5-9139-b18cc1b6b446
> * Version Independent ID: 494847b9-4894-0beb-7ffa-39a2359999fa
> * Content: [NuGet PackageReference format (package references in project files)](https://docs.microsoft.com/en-us/nuget/consume-packages/package-references-in-project-files)
> * Content Source: [docs/consume-packages/Package-References-in-Project-Files.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/master/docs/consume-packages/Package-References-in-Project-Files.md)
> * Product: **nuget**
> * GitHub Login: @karann-msft
> * Microsoft Alias: **karann**

Found any solution or workaround?

**Comment by StingyJack** [comment]
I rewrote the proj file to use the declarative format that did not have a problem and did need to be fixed, replacing that awful new SDK format that makes extra work for any kind of proj file automation and brings back the "whoops" file gets compiled cos its in a folder bad old days of Asp.net web site projects.

**Comment by Mikejo5000** [comment]
SDK format can only use PackageReference, I believe. Sounds like you fixed the issue by using the other project format.

**Comment by StingyJack** [comment]
@mikejo5000 - pretty sure I have a few of the maintenance-and-automation-unfriendly SDK style projects using the more-featured-and-useful package.config style nuget.

My bias for better software aside, I'm looking for the allowable values for the element named in the title. Do you know what they are?

**Comment by Mikejo5000** [comment]
@nkolev92 Are there any other supported values for RestoreProjectStyle besides PackageReference?

**Comment by dochoffiday** [comment]
@Mikejo5000 I believe you can do `<RestoreProjectStyle>Packages.config</RestoreProjectStyle>`
