### ISSUE TITLE
using prerelease with and without sdk style projects

### ISSUE THREAD

**Issue by zivkan** [NuGet/docs.microsoft.com-nuget#1423]
@karann-msft merged PR #1421 before I looked at it, but I have a comment which I think needs to be considered.

The new suggestion to use `PackageVersion` in the csproj, I believe only works with the MSBuild pack targets (including SDK style projects), but I think won't work with traditional projects using `nuget.exe pack`.

I'm concerned that if the docs don't explicitly point this out, some customers will be confused.

**Comment by loic-sharma** [comment]
Does `nuget.exe pack` work as expected if you add a package reference to `NuGet.Build.Tasks.Pack`?

**Comment by Mikejo5000** [comment]
Looks like this was fixed in #1424
