### ISSUE TITLE
Missing Override

### ISSUE THREAD

**Issue by schellem** [NuGet/docs.microsoft.com-nuget#1427]
NuGet.config file can override the NuGet settings

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 71b49477-cafa-d7d4-76fe-83aff43a3f47
* Version Independent ID: 68d7a416-1397-8cf3-bead-e3cd328aca48
* Content: [How to manage the global packages, cache, temp folders in NuGet](https://docs.microsoft.com/en-us/nuget/Consume-Packages/managing-the-global-packages-and-cache-folders)
* Content Source: [docs/consume-packages/managing-the-global-packages-and-cache-folders.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/master/docs/consume-packages/managing-the-global-packages-and-cache-folders.md)
* Product: **nuget**
* GitHub Login: @karann-msft
* Microsoft Alias: **karann**

**Comment by karann-msft** [comment]
@schellem we do talk about that on this page for configuring nuget behavior - https://docs.microsoft.com/en-us/nuget/consume-packages/configuring-nuget-behavior

**Comment by schellem** [comment]
Why leave that one out of the list of the other overrides mentioned in the article I made this comment on.

**Comment by karann-msft** [comment]
@schellem - I don't follow. What exactly is missing from what page?

**Comment by schellem** [comment]
I got here from the Feedback options on a Microsoft help page.

**Comment by karann-msft** [comment]
@schellem - unfortunately that's not actionable. Please feel free to reopen the issue if you have more info.

**Comment by schellem** [comment]
The title and link to the deficient article is at the head of this thread, it is missing information, if that is not actionable I don't know what to tell you.

**Comment by karann-msft** [comment]
@schellem if you cannot articulate the deficiency, I am not sure what to fix!

**Comment by schellem** [comment]
An article that leaves out pretty key information is flawed. I wasted significant time due to the article lacking information.

**Comment by karann-msft** [comment]
@schellem what is that "pretty key information"? I'll repeat, can you articulate what information is missing?

**Comment by schellem** [comment]
It's stated in my original post, NuGet.config can override settings and this is not mentioned in the article alongside the other files that also do overrides.
