### ISSUE TITLE
NU3004 erroneously raised by some NuGet clients

### ISSUE THREAD

**Issue by dtivel** [NuGet/docs.microsoft.com-nuget#1428]
There are some NuGet client versions which can raise NU3004 erroneously.  These bugs were fixed in later versions.

If you encounter NU3004, and you have separately verified that the error is false (via [`NuGet.exe verify -signatures`](https://docs.microsoft.com/en-us/nuget/tools/cli-ref-verify#nuget-verify--signatures), and:
*  …you're using dotnet CLI, try updating to a newer SDK.  The issue should be fixed in the latest 2.2.1xx SDK release.
*  ...you're using NuGet.exe 5.0.0 on Mono, try using NuGet 4.9.4 for the time being.  The issue should be fixed with NuGet 5.0.2.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 314a276e-4a6c-1fed-ed29-dda792e45a7c
* Version Independent ID: 8e6ab25e-35a1-7b8a-645d-13398431c1df
* Content: [NuGet Error NU3004](https://docs.microsoft.com/en-us/nuget/reference/errors-and-warnings/nu3004#feedback)
* Content Source: [docs/reference/errors-and-warnings/NU3004.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/master/docs/reference/errors-and-warnings/NU3004.md)
* Product: **nuget**
* GitHub Login: @mishra14
* Microsoft Alias: **karann**

**Comment by danieljgmaclean** [comment]
Thanks. I instead dropped the NuGet version down to 4.3.1 and it also fixed the problem. I was using NuGet 5 on Mono.

**Comment by loic-sharma** [comment]
@danieljgmaclean Why did you settle on 4.3.1? I believe you should be able to use nuget [5.0.2](https://dist.nuget.org/win-x86-commandline/v5.0.2/nuget.exe) or [4.6.4](https://dist.nuget.org/win-x86-commandline/v4.6.4/nuget.exe).
