### ISSUE TITLE
Implement Nuget Package which contains UI pages

### ISSUE THREAD

**Issue by PrabhujiMudragalla** [NuGet/docs.microsoft.com-nuget#1430]
Hi Team, 

I am planning to create a UI Package which can be used across all my projects, it should support the following type of applications:
1. MVC Web Applications
2. MVC Web API 
3. Web Forms
4. WPF Applications 
5. .NET Core Web API 
6. .NET Core MVC 
Can you please suggest what type of application should I prefer to achieve the above frameworks?

**Comment by karann-msft** [comment]
Issue moved to [NuGet/Home #8145](https://github.com/NuGet/Home/issues/8145) via [**ZenHub**](https://www.zenhub.com/)
