### ISSUE TITLE
ensuring or ensure?

### ISSUE THREAD

**Issue by mkalkere** [NuGet/docs.microsoft.com-nuget#1431]
In the below paragraph I think it should be _ensure_ not _ensuring_

**NuGet defaults file**
The NuGetDefaults.Config file exists to specify package sources from which packages are installed and updated, and to control the default target for publishing packages with nuget push. Because administrators can conveniently (using Group Policy, for example) deploy consistent NuGetDefaults.Config files to developer and build machines, they can *_ensuring_* that everyone in the organization is using the correct package sources rather than nuget.org.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 370d9d91-9f35-79aa-3ace-7b77436e988f
* Version Independent ID: 3da4591a-3d3d-c07a-6672-97964de13b14
* Content: [Configuring the behavior of NuGet](https://docs.microsoft.com/en-us/nuget/consume-packages/configuring-nuget-behavior#feedback)
* Content Source: [docs/consume-packages/configuring-nuget-behavior.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/master/docs/consume-packages/configuring-nuget-behavior.md)
* Product: **nuget**
* GitHub Login: @karann-msft
* Microsoft Alias: **karann**

**Comment by karann-msft** [comment]
@mkalkere thanks for catching that! You can now submit a PR to update docs! Just click on the "edit" button on the top right of the page.
![image](https://user-images.githubusercontent.com/16904420/57588956-7f0c2500-74d1-11e9-8951-2e80e55dc6cd.png)
