### ISSUE TITLE
`NuGet.Config` file locations

### ISSUE THREAD

**Issue by matthew-a-thomas** [NuGet/docs.microsoft.com-nuget#1433]
This page says
> settings in one or more `NuGet.Config` (XML) files that can exist at **project-**, user-, and computer-wide levels

But the `NuGet.Config` file is recognized at _solution_ level, not _project_ level.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 370d9d91-9f35-79aa-3ace-7b77436e988f
* Version Independent ID: 3da4591a-3d3d-c07a-6672-97964de13b14
* Content: [Configuring the behavior of NuGet](https://docs.microsoft.com/en-us/nuget/consume-packages/configuring-nuget-behavior)
* Content Source: [docs/consume-packages/configuring-nuget-behavior.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/master/docs/consume-packages/configuring-nuget-behavior.md)
* Product: **nuget**
* GitHub Login: @karann-msft
* Microsoft Alias: **karann**

**Comment by MisinformedDNA** [comment]
Yea, I ran into this as well. See also https://developercommunity.visualstudio.com/content/problem/24733/visual-studio-nuget-package-manager-ignores-nugetc.html
