### ISSUE TITLE
Is there any option to provide password interactively?

### ISSUE THREAD

**Issue by raspy** [NuGet/docs.microsoft.com-nuget#1434]
When setting password from command line it is visible on the command line and stored in history. Is there any possibility for nuget to ask for password interactively with echo disabled?

**Comment by karann-msft** [comment]
@raspy how did you land on this repo? This is the docs repo and meant for docs related issues.

**Comment by raspy** [comment]
It was referenced in https://docs.microsoft.com/en-us/nuget/tools/cli-ref-sources. If this is not the right place to ask issues for the topic, could you please point me to the right direction?

**Comment by karann-msft** [comment]
> Use the [Home repo](https://github.com/nuget/home/issues) for product issues.
