### ISSUE TITLE
Mac OSX Local Feed Example

### ISSUE THREAD

**Issue by bradlis7** [NuGet/docs.microsoft.com-nuget#1435]
How do you add a network feed on Mac OSX and linux? The `\\myserver\packages` is not a supported path on other OSes than windows.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fd704fe8-fd6e-ba7f-6021-15f280657f4d
* Version Independent ID: dc047102-284f-ad70-99ee-dac5be511392
* Content: [NuGet CLI sources command](https://docs.microsoft.com/en-us/nuget/tools/cli-ref-sources)
* Content Source: [docs/tools/cli-ref-sources.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/master/docs/tools/cli-ref-sources.md)
* Product: **nuget**
* GitHub Login: @karann-msft
* Microsoft Alias: **karann**

**Comment by nkalfov** [comment]
On linux, you may mount the network location and then you would have to provide a normal path. Probably the solution is similar in OS X.

**Comment by bradlis7** [comment]
I ended up using the NuGet hosting TFS add-on, so it's now an https URL instead.
