### ISSUE TITLE
Unclear how to install packages already added

### ISSUE THREAD

**Issue by alexanderankin** [NuGet/docs.microsoft.com-nuget#1436]
This is the equivalent task of "yarn install"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ccd3dbd2-1958-5812-dff4-502b540408d9
* Version Independent ID: cd159720-ee00-b949-a813-20df0058a1be
* Content: [NuGet Package Manager Console Guide](https://docs.microsoft.com/en-us/nuget/tools/package-manager-console#feedback)
* Content Source: [docs/tools/Package-Manager-Console.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/master/docs/tools/Package-Manager-Console.md)
* Product: **nuget**
* GitHub Login: @karann-msft
* Microsoft Alias: **karann**

**Comment by karann-msft** [comment]
the equivalent of `yarn install` is nuget restore - https://docs.microsoft.com/en-us/nuget/consume-packages/package-restore

When using a dotnet or Visual Studio, building the project will also perform nuget restore.

**Comment by alexanderankin** [comment]
thanks
