### ISSUE TITLE
No se encuentra el paquete AutoMapper.Extensions.Microsoft.DependencyInjection.

### ISSUE THREAD

**Issue by Robinl2018** [NuGet/docs.microsoft.com-nuget#1445]
Hi, i'm trying to create a web api with Visual Studio Code, but when i try to add the package AutoMapper.Extensions.Microsoft.DependencyInjection i get this error:

error: No se encuentra el paquete AutoMapper.Extensions.Microsoft.DependencyInjection. No existe ningún paquete con este id. en los orígenes: Microsoft Visual Studio Offline Packages
error: El paquete "AutoMapper.Extensions.Microsoft.DependencyInjection" no es compatible con los marcos de trabajo de "all" del proyecto "C:\Robin\Fuentes\ASPNetApi\aspnetapi.csproj".

![image](https://user-images.githubusercontent.com/39069169/57892484-ad0ca480-7804-11e9-821b-efcac8b5d60a.png)

This is my aspnetapi.csproj

![image](https://user-images.githubusercontent.com/39069169/57892357-3ff90f00-7804-11e9-95ee-fc52d8050d59.png)

The command that i am using is this:
dotnet add package AutoMapper.Extensions.Microsoft.DependencyInjection -v 6.1.0

I´ve tried with all versión of the package, and with all of them i get the same error.

Thanks a lot

**Comment by karann-msft** [comment]
since it is not in English, I am not able to comprehend the error message. That said, I was able to install `AutoMapper.Extensions.Microsoft.DependencyInjection` to an aspnet core project targeting netcoreapp2.2.

```
<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>netcoreapp2.2</TargetFramework>
    <AspNetCoreHostingModel>InProcess</AspNetCoreHostingModel>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper.Extensions.Microsoft.DependencyInjection" Version="6.1.0" />
    <PackageReference Include="Microsoft.AspNetCore.App" />
    <PackageReference Include="Microsoft.AspNetCore.Razor.Design" Version="2.2.0" PrivateAssets="All" />
  </ItemGroup>

</Project>
```

```
C:\Users\karann\source\repos\aspnetcore>dotnet new web

Welcome to .NET Core!
---------------------
Learn more about .NET Core: https://aka.ms/dotnet-docs
Use 'dotnet --help' to see available commands or visit: https://aka.ms/dotnet-cli-docs

Telemetry
---------
The .NET Core tools collect usage data in order to help us improve your experience. The data is anonymous and doesn't include command-line arguments. The data is collected by Microsoft and shared with the community. You can opt-out of telemetry by setting the DOTNET_CLI_TELEMETRY_OPTOUT environment variable to '1' or 'true' using your favorite shell.

Read more about .NET Core CLI Tools telemetry: https://aka.ms/dotnet-cli-telemetry

ASP.NET Core
------------
Successfully installed the ASP.NET Core HTTPS Development Certificate.
To trust the certificate run 'dotnet dev-certs https --trust' (Windows and macOS only). For establishing trust on other platforms refer to the platform specific documentation.
For more information on configuring HTTPS see https://go.microsoft.com/fwlink/?linkid=848054.
Getting ready...
The template "ASP.NET Core Empty" was created successfully.

C:\Users\karann\source\repos\aspnetcore>dotnet add package AutoMapper.Extensions.Microsoft.DependencyInjection
Writing C:\Users\karann\AppData\Local\Temp\tmp2545.tmp
info : Adding PackageReference for package 'AutoMapper.Extensions.Microsoft.DependencyInjection' into project 'C:\Users\karann\source\repos\aspnetcore\aspnetcore.csproj'.
info : Restoring packages for C:\Users\karann\source\repos\aspnetcore\aspnetcore.csproj...
info :   GET https://api.nuget.org/v3-flatcontainer/automapper.extensions.microsoft.dependencyinjection/index.json
info :   OK https://api.nuget.org/v3-flatcontainer/automapper.extensions.microsoft.dependencyinjection/index.json 340ms
info :   GET https://api.nuget.org/v3-flatcontainer/automapper.extensions.microsoft.dependencyinjection/6.1.0/automapper.extensions.microsoft.dependencyinjection.6.1.0.nupkg
info :   OK https://api.nuget.org/v3-flatcontainer/automapper.extensions.microsoft.dependencyinjection/6.1.0/automapper.extensions.microsoft.dependencyinjection.6.1.0.nupkg 8ms
info :   GET https://api.nuget.org/v3-flatcontainer/automapper/index.json
info :   OK https://api.nuget.org/v3-flatcontainer/automapper/index.json 234ms
info :   GET https://api.nuget.org/v3-flatcontainer/automapper/8.1.0/automapper.8.1.0.nupkg
info :   OK https://api.nuget.org/v3-flatcontainer/automapper/8.1.0/automapper.8.1.0.nupkg 10ms
info : Installing AutoMapper 8.1.0.
info : Installing AutoMapper.Extensions.Microsoft.DependencyInjection 6.1.0.
info : Package 'AutoMapper.Extensions.Microsoft.DependencyInjection' is compatible with all the specified frameworks in project 'C:\Users\karann\source\repos\aspnetcore\aspnetcore.csproj'.
info : PackageReference for package 'AutoMapper.Extensions.Microsoft.DependencyInjection' version '6.1.0' added to file 'C:\Users\karann\source\repos\aspnetcore\aspnetcore.csproj'.
info : Committing restore...
info : Writing assets file to disk. Path: C:\Users\karann\source\repos\aspnetcore\obj\project.assets.json
log  : Restore completed in 2.98 sec for C:\Users\karann\source\repos\aspnetcore\aspnetcore.csproj.

```
C:\Users\karann\source\repos\aspnetcore>dotnet add package AutoMapper.Extensions.Microsoft.DependencyInjection
  Writing C:\Users\karann\AppData\Local\Temp\tmp2545.tmp
info : Adding PackageReference for package 'AutoMapper.Extensions.Microsoft.DependencyInjection' into project 'C:\Users\karann\source\repos\aspnetcore\aspnetcore.csproj'.
info : Restoring packages for C:\Users\karann\source\repos\aspnetcore\aspnetcore.csproj...
info :   GET https://api.nuget.org/v3-flatcontainer/automapper.extensions.microsoft.dependencyinjection/index.json
info :   OK https://api.nuget.org/v3-flatcontainer/automapper.extensions.microsoft.dependencyinjection/index.json 340ms
info :   GET https://api.nuget.org/v3-flatcontainer/automapper.extensions.microsoft.dependencyinjection/6.1.0/automapper.extensions.microsoft.dependencyinjection.6.1.0.nupkg
info :   OK https://api.nuget.org/v3-flatcontainer/automapper.extensions.microsoft.dependencyinjection/6.1.0/automapper.extensions.microsoft.dependencyinjection.6.1.0.nupkg 8ms
info :   GET https://api.nuget.org/v3-flatcontainer/automapper/index.json
info :   OK https://api.nuget.org/v3-flatcontainer/automapper/index.json 234ms
info :   GET https://api.nuget.org/v3-flatcontainer/automapper/8.1.0/automapper.8.1.0.nupkg
info :   OK https://api.nuget.org/v3-flatcontainer/automapper/8.1.0/automapper.8.1.0.nupkg 10ms
info : Installing AutoMapper 8.1.0.
info : Installing AutoMapper.Extensions.Microsoft.DependencyInjection 6.1.0.
info : Package 'AutoMapper.Extensions.Microsoft.DependencyInjection' is compatible with all the specified frameworks in project 'C:\Users\karann\source\repos\aspnetcore\aspnetcore.csproj'.
info : PackageReference for package 'AutoMapper.Extensions.Microsoft.DependencyInjection' version '6.1.0' added to file 'C:\Users\karann\source\repos\aspnetcore\aspnetcore.csproj'.
info : Committing restore...
info : Writing assets file to disk. Path: C:\Users\karann\source\repos\aspnetcore\obj\project.assets.

**Comment by Robinl2018** [comment]
Hi, i still have the error when i try to install the package:

The AutoMapper.Extensions.Microsoft.DependencyInjection package can not be found. There is no package with this id. in the beginning: Microsoft Visual Studio Offline Packages

The "AutoMapper.Extensions.Microsoft.DependencyInjection" package is not compatible with the "all" frameworks of the "C: \ Robin \ Sources \ ASPNetApi \ aspnetapi.csproj" project.

**Comment by Robinl2018** [comment]
> since it is not in English, I am not able to comprehend the error message. That said, I was able to install `AutoMapper.Extensions.Microsoft.DependencyInjection` to an aspnet core project targeting netcoreapp2.2.
> 
> ```
> <Project Sdk="Microsoft.NET.Sdk.Web">
> 
>   <PropertyGroup>
>     <TargetFramework>netcoreapp2.2</TargetFramework>
>     <AspNetCoreHostingModel>InProcess</AspNetCoreHostingModel>
>   </PropertyGroup>
> 
>   <ItemGroup>
>     <PackageReference Include="AutoMapper.Extensions.Microsoft.DependencyInjection" Version="6.1.0" />
>     <PackageReference Include="Microsoft.AspNetCore.App" />
>     <PackageReference Include="Microsoft.AspNetCore.Razor.Design" Version="2.2.0" PrivateAssets="All" />
>   </ItemGroup>
> 
> </Project>
> ```
> 
> ```
> C:\Users\karann\source\repos\aspnetcore>dotnet new web
> 
> Welcome to .NET Core!
> ---------------------
> Learn more about .NET Core: https://aka.ms/dotnet-docs
> Use 'dotnet --help' to see available commands or visit: https://aka.ms/dotnet-cli-docs
> 
> Telemetry
> ---------
> The .NET Core tools collect usage data in order to help us improve your experience. The data is anonymous and doesn't include command-line arguments. The data is collected by Microsoft and shared with the community. You can opt-out of telemetry by setting the DOTNET_CLI_TELEMETRY_OPTOUT environment variable to '1' or 'true' using your favorite shell.
> 
> Read more about .NET Core CLI Tools telemetry: https://aka.ms/dotnet-cli-telemetry
> 
> ASP.NET Core
> ------------
> Successfully installed the ASP.NET Core HTTPS Development Certificate.
> To trust the certificate run 'dotnet dev-certs https --trust' (Windows and macOS only). For establishing trust on other platforms refer to the platform specific documentation.
> For more information on configuring HTTPS see https://go.microsoft.com/fwlink/?linkid=848054.
> Getting ready...
> The template "ASP.NET Core Empty" was created successfully.
> 
> C:\Users\karann\source\repos\aspnetcore>dotnet add package AutoMapper.Extensions.Microsoft.DependencyInjection
> Writing C:\Users\karann\AppData\Local\Temp\tmp2545.tmp
> info : Adding PackageReference for package 'AutoMapper.Extensions.Microsoft.DependencyInjection' into project 'C:\Users\karann\source\repos\aspnetcore\aspnetcore.csproj'.
> info : Restoring packages for C:\Users\karann\source\repos\aspnetcore\aspnetcore.csproj...
> info :   GET https://api.nuget.org/v3-flatcontainer/automapper.extensions.microsoft.dependencyinjection/index.json
> info :   OK https://api.nuget.org/v3-flatcontainer/automapper.extensions.microsoft.dependencyinjection/index.json 340ms
> info :   GET https://api.nuget.org/v3-flatcontainer/automapper.extensions.microsoft.dependencyinjection/6.1.0/automapper.extensions.microsoft.dependencyinjection.6.1.0.nupkg
> info :   OK https://api.nuget.org/v3-flatcontainer/automapper.extensions.microsoft.dependencyinjection/6.1.0/automapper.extensions.microsoft.dependencyinjection.6.1.0.nupkg 8ms
> info :   GET https://api.nuget.org/v3-flatcontainer/automapper/index.json
> info :   OK https://api.nuget.org/v3-flatcontainer/automapper/index.json 234ms
> info :   GET https://api.nuget.org/v3-flatcontainer/automapper/8.1.0/automapper.8.1.0.nupkg
> info :   OK https://api.nuget.org/v3-flatcontainer/automapper/8.1.0/automapper.8.1.0.nupkg 10ms
> info : Installing AutoMapper 8.1.0.
> info : Installing AutoMapper.Extensions.Microsoft.DependencyInjection 6.1.0.
> info : Package 'AutoMapper.Extensions.Microsoft.DependencyInjection' is compatible with all the specified frameworks in project 'C:\Users\karann\source\repos\aspnetcore\aspnetcore.csproj'.
> info : PackageReference for package 'AutoMapper.Extensions.Microsoft.DependencyInjection' version '6.1.0' added to file 'C:\Users\karann\source\repos\aspnetcore\aspnetcore.csproj'.
> info : Committing restore...
> info : Writing assets file to disk. Path: C:\Users\karann\source\repos\aspnetcore\obj\project.assets.json
> log  : Restore completed in 2.98 sec for C:\Users\karann\source\repos\aspnetcore\aspnetcore.csproj.
> ```
> 
> C:\Users\karann\source\repos\aspnetcore>dotnet add package AutoMapper.Extensions.Microsoft.DependencyInjection
> Writing C:\Users\karann\AppData\Local\Temp\tmp2545.tmp
> info : Adding PackageReference for package 'AutoMapper.Extensions.Microsoft.DependencyInjection' into project 'C:\Users\karann\source\repos\aspnetcore\aspnetcore.csproj'.
> info : Restoring packages for C:\Users\karann\source\repos\aspnetcore\aspnetcore.csproj...
> info : GET https://api.nuget.org/v3-flatcontainer/automapper.extensions.microsoft.dependencyinjection/index.json
> info : OK https://api.nuget.org/v3-flatcontainer/automapper.extensions.microsoft.dependencyinjection/index.json 340ms
> info : GET https://api.nuget.org/v3-flatcontainer/automapper.extensions.microsoft.dependencyinjection/6.1.0/automapper.extensions.microsoft.dependencyinjection.6.1.0.nupkg
> info : OK https://api.nuget.org/v3-flatcontainer/automapper.extensions.microsoft.dependencyinjection/6.1.0/automapper.extensions.microsoft.dependencyinjection.6.1.0.nupkg 8ms
> info : GET https://api.nuget.org/v3-flatcontainer/automapper/index.json
> info : OK https://api.nuget.org/v3-flatcontainer/automapper/index.json 234ms
> info : GET https://api.nuget.org/v3-flatcontainer/automapper/8.1.0/automapper.8.1.0.nupkg
> info : OK https://api.nuget.org/v3-flatcontainer/automapper/8.1.0/automapper.8.1.0.nupkg 10ms
> info : Installing AutoMapper 8.1.0.
> info : Installing AutoMapper.Extensions.Microsoft.DependencyInjection 6.1.0.
> info : Package 'AutoMapper.Extensions.Microsoft.DependencyInjection' is compatible with all the specified frameworks in project 'C:\Users\karann\source\repos\aspnetcore\aspnetcore.csproj'.
> info : PackageReference for package 'AutoMapper.Extensions.Microsoft.DependencyInjection' version '6.1.0' added to file 'C:\Users\karann\source\repos\aspnetcore\aspnetcore.csproj'.
> info : Committing restore...
> info : Writing assets file to disk. Path: C:\Users\karann\source\repos\aspnetcore\obj\project.assets.

Hi, i still have the error when i try to install the package. This is the error in english:

The AutoMapper.Extensions.Microsoft.DependencyInjection package can not be found. There is no package with this id. in the beginning: Microsoft Visual Studio Offline Packages

The "AutoMapper.Extensions.Microsoft.DependencyInjection" package is not compatible with the "all" frameworks of the "C: \ Robin \ Sources \ ASPNetApi \ aspnetapi.csproj" project.

**Comment by karann-msft** [comment]
can you [download nuget.exe](https://dist.nuget.org/win-x86-commandline/latest/nuget.exe), place it in the same folder as the csproj, run `nuget sources`, and paste the output below. It should look like this 
```
C:\Users\karann>nuget sources
Registered Sources:

  1.  nuget.org [Enabled]
      https://api.nuget.org/v3/index.json
  2.  local [Enabled]
      C:\nuget\local
  3.  Package source [Disabled]
      C:\Users\karann\Documents\GitHub\NuGetSamples\ExtensionSDKasNuGetPackage\ManagedPackage
  4.  nuget.org v2 [Disabled]
      https://www.nuget.org/api/v2
  5.  MyGet Dotnet [Disabled]
      https://dotnet.myget.org/F/nuget-build/api/v3/index.json
  6.  Package source 1 [Disabled]
      \\mikefan-dev1\public2
  7.  dev.nugettest.org [Disabled]
      https://apidev.nugettest.org/v3-index/index.json
  8.  Microsoft Visual Studio Offline Packages [Enabled]
      C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\
  9.  signedPackage [Disabled]
      C:\Users\karann\source\repos\ClientPolicyTest\SignedPackage\bin\Debug
  10. MathWizardHelper [Enabled]
      C:\Users\karann\source\repos\MathWizardHelper\MathWizardHelper\bin\Release
  11. MathWizardFeed [Disabled]
      https://pkgs.dev.azure.com/karann9/_packaging/MathWizardFeed/nuget/v3/index.json
```

**Comment by Robinl2018** [comment]
Hi,

I add the source nuget.org  https://api.nuget.org/v3/index.json and everything is fine.

Thanks a lot
