### ISSUE TITLE
nuspec file reference incorrectly lists minClientVersion as an element rather than attribute

### ISSUE THREAD

**Issue by duckfist** [NuGet/docs.microsoft.com-nuget#1450]
On the page that describes the [**.nuspec File Reference**](https://docs.microsoft.com/en-us/nuget/reference/nuspec), the description of "_minClientVersion_" is listed under the section titled "_Optional metadata elements_". However, _minClientVersion_ is an XML **attribute** of the "_metadata_" XML element, and not an XML element in an of itself. 

For a newbie reading the article as-is, one might try adding tags named _\<minClientVersion\>_, only to have the _nuget pack_ command return errors, before eventually realizing that it's not actually a valid tag. I'd suggest making another subheading somewhere that describes what the _metadata_ element is, and underneath it describe possible attributes, such as _minClientVersion_.

Note that this is a duplicate of #607, which has been closed, yet it has not actually been solved.

Thank you!!

**Comment by Mikejo5000** [comment]
@nkolev92 Nikolche, does this seem like a good change to docs.

**Comment by nkolev92** [comment]
Yup, the OP is correct. 

The minClientVersion belongs on the metadata element:

Example

```xml
<?xml version="1.0" encoding="utf-8"?>
<package xmlns="http://schemas.microsoft.com/packaging/2013/01/nuspec.xsd">
    <metadata minClientVersion="100.0.0.1">
        <id>dasdas</id>
        <version>2.0.0</version>
        <title />
        <authors>dsadas</authors>
        <owners />
        <requireLicenseAcceptance>false</requireLicenseAcceptance>
        <description>My package description.</description>
    </metadata>
    <files>
        <file src="content\one.txt" target="content\one.txt" />
    </files>
</package>
```

**Comment by Mikejo5000** [comment]
@nkolev92 Thanks, updating doc
