### ISSUE TITLE
Wrong location path of NuGet.Config for linux

### ISSUE THREAD

**Issue by CeciAc** [NuGet/docs.microsoft.com-nuget#1451]
Hi team, 
I'm moving this from here: https://github.com/NuGet/docs.microsoft.com-nuget.fr-fr/issues/15

@arthis commented 7 hours ago

> In the above :
> ConfigFile The NuGet configuration file to apply. If not specified, %AppData%\NuGet\NuGet.Config (Windows) or ~/.nuget/NuGet/NuGet.Config (Mac/Linux) is used.
> 
> For linux, it is not the correct location , it should be ~/.config/NuGet/NuGet.Config
> 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d63170c3-1894-8ead-b557-9937dae88172
* Version Independent ID: 67968c11-0aa0-f835-357d-8690911eb011
* Content: [NuGet CLI restore command](https://docs.microsoft.com/en-us/nuget/tools/cli-ref-restore#feedback)
* Content Source: [docs/tools/cli-ref-restore.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/master/docs/tools/cli-ref-restore.md)
* Product: **nuget**
* GitHub Login: @karann-msft
* Microsoft Alias: **karann**

**Comment by Mikejo5000** [comment]
@nkolev92 @karann-msft If true, this fix likely applies in several places. Should all Linux paths be updated from "/.nuget/" to "/.config/"?

**Comment by nkolev92** [comment]
I don't think that's correct. 

All default folders are .nuget in the User Profile.

**Comment by Mikejo5000** [comment]
Need more info to keep this open.
