### ISSUE TITLE
How do I publish a package which has no assembly (Microsoft.Build.NoTargets SDK)

### ISSUE THREAD

**Issue by binki** [NuGet/docs.microsoft.com-nuget#1452]
Hi,

I am getting this error.

However, I want to run `dotnet pack` for my project which doesn’t have an assembly. I just want a pure build-targets-only package. Here is my layout:

`px.csproj`:
```xml
<Project Sdk="Microsoft.Build.NoTargets/1.0.26">
  <PropertyGroup>
    <TargetFramework>netstandard1.1</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <Content Include="build/px.targets" />
  </ItemGroup>
</Project>
```

`build/px.targets`:
```xml
<?xml version="1.0"?>
<Project Sdk="Microsoft.Build.NoTargets/1.0.26">
  <Target BeforeTargets="Build" Name="pxSayHi">
    <Warning Text="Hello from px!" />
  </Target>
</Project>
```

Trying to pack, I get this error:

```
C:\Users\binki\AppData\Local\Temp\px>dotnet pack
Microsoft (R) Build Engine version 16.1.76+g14b0a930a7 for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.

  Restore completed in 32.47 ms for C:\Users\binki\AppData\Local\Temp\px\px.csproj.
  px ->
C:\Program Files\dotnet\sdk\2.2.300\Sdks\NuGet.Build.Tasks.Pack\build\NuGet.Build.Tasks.Pack.targets(199,5): error NU5026: The file 'C:\Users\binki\AppData\Local\Temp\px\bin\Debug\netstandard1.1\px.dll' to be packed was not found on disk. [C:\Users\binki\AppData\Local\Temp\px\px.csproj]
```

Because this documentation page describes this error, I would expect it to have a pointer to documentation which explains how to create a NuGet package which does not contain an assembly as one possible solution to the error. Instead, the documentation only addresses the scenario where one is trying to build an assembly-containing nuget package.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7fb15c8f-7da1-a19c-0642-85dbf61ba8bf
* Version Independent ID: e9f608fc-a014-0061-0def-b2b04dca26fa
* Content: [NuGet Error NU5026](https://docs.microsoft.com/en-us/NuGet/reference/errors-and-warnings/nu5026)
* Content Source: [docs/reference/errors-and-warnings/NU5026.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/master/docs/reference/errors-and-warnings/NU5026.md)
* Product: **nuget**
* GitHub Login: @mishra14
* Microsoft Alias: **karann**

**Comment by binki** [comment]
Note that the solution that I needed which I think the documentation should mention is adding `<IncludeBuildOutput>false</IncludeBuildOutput>` in a `<PropertyGroup/>` as mentioned in the second option at https://stackoverflow.com/a/42867924.

**Comment by karann-msft** [comment]
Issue moved to [NuGet/Home #8165](https://github.com/NuGet/Home/issues/8165) via [**ZenHub**](https://www.zenhub.com/)

**Comment by binki** [comment]
@karann-msft Hi, thanks for looking into my issue.

I think the docs could be improved further.

When someone sees and googles “NU5026” and arrives at the documentation page, it would be useful to explain the scenarios that may result in the error:

1. The user is trying to pack the project without permitting it to build.
2. The user is trying to pack a project which does not output an assembly without informing NuGet that the project does not output an assembly.

Currently, the docs only describe the first scenario. They also only give a direct solution for the first scenario:

> Please build the project before running `dotnet pack` operation or do not use `--no-build` option to allow dotnet pack to build the project before packaging.

However, the docs do not describe the second scenario. They are written in a way that will convince the user that NuGet’s requirement that a package include an assembly cannot be disabled. Perhaps some blurb more fully describing the scenario of the package legitimately not having an output assembly could be more fully described in this error documentation page. For example:

> You may have written a project which does not output assemblies. If you intend to ship an assembly-free NuGet package, disable `dotnet pack`’s requirement that there be an output assembly. You can do this by setting the [`IncludeBuildOutput`](https://docs.microsoft.com/en-us/NuGet/reference/msbuild-targets#output-assemblies) property to `false` in your project file.

Thanks for considering this!

**Comment by Mikejo5000** [comment]
Adding note

**Comment by wasabii** [comment]
I have to resuscitate this. How do you get both IncludeBuildOutput=false as well as TargetsForTfmSpecificBuildOutput to work at the same time?
