### ISSUE TITLE
case no longer work in visual studio 2019 sdk

### ISSUE THREAD

**Issue by LittleLittleCloud** [NuGet/docs.microsoft.com-nuget#1453]
as follow

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 24e1c35e-18f4-1357-65a0-e5f228c72476
* Version Independent ID: 72a6e51a-3cb1-60bd-0ce5-9827a724a028
* Content: [NuGet API in Visual Studio](https://docs.microsoft.com/en-us/nuget/visual-studio-extensibility/nuget-api-in-visual-studio#feedback)
* Content Source: [docs/visual-studio-extensibility/nuget-api-in-visual-studio.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/master/docs/visual-studio-extensibility/nuget-api-in-visual-studio.md)
* Product: **nuget**
* GitHub Login: @karann-msft
* Microsoft Alias: **karann**

**Comment by karann-msft** [comment]
@LittleLittleCloud can you provide more info? What exactly on that page didn't work?

**Comment by Mikejo5000** [comment]
Related to #1477 ?

**Comment by Mikejo5000** [comment]
Needs more info
