### ISSUE TITLE
Programmatically analyze the dependencies

### ISSUE THREAD

**Issue by fleed** [NuGet/docs.microsoft.com-nuget#1459]
Is there a library to analyze the csproj structure and programmatically detect the package references?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ff707668-94d6-25a5-9139-b18cc1b6b446
* Version Independent ID: 494847b9-4894-0beb-7ffa-39a2359999fa
* Content: [NuGet PackageReference format (package references in project files)](https://docs.microsoft.com/en-us/nuget/consume-packages/package-references-in-project-files#feedback)
* Content Source: [docs/consume-packages/Package-References-in-Project-Files.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/master/docs/consume-packages/Package-References-in-Project-Files.md)
* Product: **nuget**
* GitHub Login: @karann-msft
* Microsoft Alias: **karann**

**Comment by karann-msft** [comment]
Issue moved to [NuGet/Home #8706](https://github.com/NuGet/Home/issues/8706) via [**ZenHub**](https://www.zenhub.com/)
