### ISSUE TITLE
Can I publish netstandard library as dll?

### ISSUE THREAD

**Issue by baruchiro** [NuGet/docs.microsoft.com-nuget#1461]
I want to publish a `dll` from one solution to use this `dll` in another solution.

Yes, I know the right way is to use `nuget`.

If I **publish** my project, it published as `nupkg` file. How can I publish the dll itself without `nupkg` structure?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 18071970-cf13-78af-ac1d-9adefefdb693
* Version Independent ID: 3bf15a5c-8b3e-0e69-0bf6-03b44654970c
* Content: [Create and publish a .NET Standard package using Visual Studio on Windows](https://docs.microsoft.com/en-us/nuget/quickstart/create-and-publish-a-package-using-visual-studio)
* Content Source: [docs/quickstart/create-and-publish-a-package-using-visual-studio.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/master/docs/quickstart/create-and-publish-a-package-using-visual-studio.md)
* Product: **nuget**
* GitHub Login: @karann-msft
* Microsoft Alias: **karann**

**Comment by karann-msft** [comment]
@baruchiro - you can add a reference to the nuget package from the project in the other solution.
What do you mean by "publish my project"? What are you trying to achieve and what blocker are you hitting? Why do you think publishing a dll without a the nupkg structure is going to solve that problem?

**Comment by saisirisha1835** [comment]
@karann-msft , I have the same issue,I am working on a .net project.I want to publish a dll from one solution to nexus and reference this dll in another solution using Jenkins scripted pipeline.What is the better way to do it?Please advise.

**Comment by saisirisha1835** [comment]
@karann-msft,I have the output 7 dll’s into a nuget package and published it to nexus using jenkins pipeline script,but when I change something in the code and push the dll’s again the old nuget package in nexus is being overwritten,how to add versioning to nuget packages .Please suggest.

**Comment by karann-msft** [comment]
every package has a "version" metadata. You need to rev that version with every release.  See this https://docs.microsoft.com/en-us/nuget/reference/nuspec#version

As for referencing a package, take a look at this package consumption overview - https://docs.microsoft.com/en-us/nuget/consume-packages/overview-and-workflow

That should cover everything you need.

**Comment by saisirisha1835** [comment]
Thank you.I will work on it.
