### ISSUE TITLE
Explicit References 

### ISSUE THREAD

**Issue by Good-man** [NuGet/docs.microsoft.com-nuget#1463]
The following documentation isn't completely accurate:
"The &lt;references&gt; element explicitly specifies the assemblies that the target project should reference when using the package. When this element is present, NuGet add references to only the listed assemblies; it does not add references for any other assemblies in the package's lib folder."

According to this, if no references are listed, it should not add any references.  However, with empty &lt;references&gt;, nuget still adds a reference to the DLL in the lib folder. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 06a19d7d-253d-f17f-6421-624c9867473d
* Version Independent ID: cc37eb17-f715-080c-7bfc-9eae868d50ba
* Content: [.nuspec File Reference for NuGet](https://docs.microsoft.com/en-us/nuget/reference/nuspec#feedback)
* Content Source: [docs/reference/nuspec.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/master/docs/reference/nuspec.md)
* Product: **nuget**
* GitHub Login: @karann-msft
* Microsoft Alias: **karann**

**Comment by Mikejo5000** [comment]
Looks like the incorrect text has been removed.
