### ISSUE TITLE
cascade examples

### ISSUE THREAD

**Issue by davidalpert** [NuGet/docs.microsoft.com-nuget#1464]
after reading this page several times I find I am still struggling to understand how to properly arrange and the various config files to configure nuget sources on macos with credentials.

I keep getting asked for credentials after I believe that I have already set them.

Explicit examples of full file paths to all the possible configs in the sequence they are read would be helpful.

I would offer to contribute such an example but after hours and hours of fighting with this I still cannot figure it out. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 370d9d91-9f35-79aa-3ace-7b77436e988f
* Version Independent ID: 3da4591a-3d3d-c07a-6672-97964de13b14
* Content: [Configuring the behavior of NuGet](https://docs.microsoft.com/en-us/nuget/consume-packages/configuring-nuget-behavior)
* Content Source: [docs/consume-packages/configuring-nuget-behavior.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/master/docs/consume-packages/configuring-nuget-behavior.md)
* Product: **nuget**
* GitHub Login: @karann-msft
* Microsoft Alias: **karann**

**Comment by McDalen** [comment]
someone?

Debugging... InputParameters -- Sources : 'Microsoft.Xrm.Sdk.EntityCollection' 00.0000,-000.0000 Targets : 
'Microsoft.Xrm.Sdk.EntityCollection' 00.09979,-000.64032 OutputParameters -- ExceptionMessage :
 '' Result : 'Microsoft.Xrm.Sdk.EntityCollection' Microsoft.Xrm.Sdk.EntityCollection 0,787 SharedVariables --
