### ISSUE TITLE
Nuspec schema image should be updated

### ISSUE THREAD

**Issue by code2mars** [NuGet/docs.microsoft.com-nuget#1469]
Lincense Url description says it has been deprecated but the schema screen shot still shows the licenseUrl tag. Also the new license tag is missing. I think the image needs to be updated to reflect new schema.

**Comment by karann-msft** [comment]
what page are you referring to?

**Comment by code2mars** [comment]
Below is the link to the page that i am referring to: 
https://docs.microsoft.com/en-us/nuget/reference/nuspec

![image](https://user-images.githubusercontent.com/43263527/61271265-755fb000-a7e7-11e9-93ed-f7605dfecdde.png)
