### ISSUE TITLE
Attractive software

### ISSUE THREAD

**Issue by mkstarr** [NuGet/docs.microsoft.com-nuget#1471]
Good basic features and demonstration of use. Plenty of supporting documentation to last for some time.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a3d9a003-8855-e57a-2f57-5a8e2ad831f2
* Version Independent ID: 68bacd53-48dc-bae3-4a51-207a7b9ce95f
* Content: [NuGet CLI add command](https://docs.microsoft.com/en-us/nuget/tools/cli-ref-add)
* Content Source: [docs/tools/cli-ref-add.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/master/docs/tools/cli-ref-add.md)
* Product: **nuget**
* GitHub Login: @karann-msft
* Microsoft Alias: **karann**

**Comment by karann-msft** [comment]
Thank you!
