### ISSUE TITLE
nuget update with mono

### ISSUE THREAD

**Issue by nelfer** [NuGet/docs.microsoft.com-nuget#1472]
Hi,
I noticed the note about `nuget update` doesn't work under `mono` . Is there any updates on this? or any work around? I have a linux machine where I was doing a script to mass update projects (over 100) and saw that it didn't work.

The projects are .Net 4.7 by the way.

Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9ffc1aea-bed4-f33a-69e8-b0a339443d94
* Version Independent ID: ed0d51ba-df92-4e87-211b-2e0f6bc5da0c
* Content: [NuGet CLI update command](https://docs.microsoft.com/en-us/nuget/tools/cli-ref-update)
* Content Source: [docs/tools/cli-ref-update.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/master/docs/tools/cli-ref-update.md)
* Product: **nuget**
* GitHub Login: @karann-msft
* Microsoft Alias: **karann**

**Comment by karann-msft** [comment]
Issue moved to [NuGet/Home #8705](https://github.com/NuGet/Home/issues/8705) via [**ZenHub**](https://www.zenhub.com/)
