### ISSUE TITLE
More information needed

### ISSUE THREAD

**Issue by JoelMacKenzie** [NuGet/docs.microsoft.com-nuget#1473]
How do I "install/reference" 'PackageA' directly?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 448640a2-cc95-ee40-f4c1-abed6eaf00db
* Version Independent ID: d3dde0f2-9aac-f6d9-3887-37efef551e01
* Content: [NuGet Error NU1107](https://docs.microsoft.com/en-us/nuget/reference/errors-and-warnings/nu1107?f1url=https%3A%2F%2Fmsdn.microsoft.com%2Fquery%2Fdev15.query%3FappId%3DDev15IDEF1%26l%3DEN-US%26k%3Dk(NU1107)%26rd%3Dtrue%26f%3D255%26MSPPError%3D-2147217396#feedback)
* Content Source: [docs/reference/errors-and-warnings/NU1107.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/master/docs/reference/errors-and-warnings/NU1107.md)
* Product: **nuget**
* GitHub Login: @zhili1208
* Microsoft Alias: **lzhi**

**Comment by hokibuf** [comment]
Hi Joel. 
1. Right-click on your project in Solution Explorer and select Manage NuGet Packages for Solution...
2. Select Installed and click on each package to see the installed version and latest version
3. Select Updates --> running the updates should correct the issue for you

That's what worked for me.
Good luck,
Al

**Comment by Mikejo5000** [comment]
Adding links
