### ISSUE TITLE
"repositorypath" and not "repositoryPath"

### ISSUE THREAD

**Issue by assafisr** [NuGet/docs.microsoft.com-nuget#1477]
Hi,
After a lot of struggling with NuGet.config inheritance of settings, specifically with the configuration key `repositoryPath` mentioned in [this article](https://docs.microsoft.com/en-us/nuget/consume-packages/configuring-nuget-behavior), I've came to realize the correct syntax of this key is `repositorypath` with lower-case _P_ and not `repositoryPath`.

Since NuGet.config keys are case-sensitive I believe this should be fixed in all relevant documentation articles.

**Comment by Mikejo5000** [comment]
@nkolev92 I've seen a few of these properties mentioned. Is case incorrect?

**Comment by nkolev92** [comment]
I don't think they are case sensitive, but we recently did work in this space, so maybe there's a bug?

I'll investigate later today and come back with a clarification.

**Comment by nkolev92** [comment]
So I verified quickly. 

The nuget config command is case sensitive. It only updates keys with the exact case. 

On the consumption side, the casing is ignored.

Both "repositorypath" and "repositoryPath" work. If both are present, NuGet picks one. 

I verified this with 4.7 and 5.2

**Comment by nkolev92** [comment]
Related: https://github.com/NuGet/Home/issues/8266

**Comment by nkolev92** [comment]
Actually the issue suggests, I'm wrong about the config command side, at least prior to 4.9. 
The special keys are supposed to be case insensitive :) 

I think we need to resolve NuGet/Home#8266 first before making any doc changes.

**Comment by karann-msft** [comment]
This looks like a product bug and docs cannot be used to fix it.

We should fix NuGet/Home#8266
