### ISSUE TITLE
How to install and modify projects or reference files

### ISSUE THREAD

**Issue by HebaruSan** [NuGet/docs.microsoft.com-nuget#1479]
"Installs a package into the current project but does not modify projects or reference files."

I want to installs a package into the current project AND ALSO modify projects or reference files. Can I do that with this tool? No other command's description mentions anything like that.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 30f597bb-080f-188b-b1ba-a02efbe1e9ca
* Version Independent ID: 88e19d47-f4e1-0496-305c-af14f0d54afb
* Content: [NuGet Command-Line Interface (CLI) Reference](https://docs.microsoft.com/en-us/nuget/tools/nuget-exe-cli-reference#feedback)
* Content Source: [docs/tools/nuget-exe-CLI-Reference.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/master/docs/tools/nuget-exe-CLI-Reference.md)
* Product: **nuget**
* GitHub Login: @karann-msft
* Microsoft Alias: **karann**

**Comment by Mikejo5000** [comment]
I don't believe there is a way to do this using this tool alone. See the topic here:
https://docs.microsoft.com/en-us/nuget/consume-packages/install-use-packages-nuget-cli#install-a-package
