### ISSUE TITLE
NuGet logo on the home page at docs.microsoft.com points to the wrong URL and has a glitch

### ISSUE THREAD

**Issue by unniravindranathan** [NuGet/docs.microsoft.com-nuget#148]
Per conversation with Karan, opening to track. We do need to add a button to docs.microsoft.com so users can navigate to docs.microsoft.com/nuget from the home page for Docs.

**Comment by karann-msft** [comment]
updating the title to reflect the issue. attaching gif.
![nuget button glitch](https://cloud.githubusercontent.com/assets/16904420/21796449/b8b53800-d6bd-11e6-8bf0-9c91f1b6df37.gif)

**Comment by karann-msft** [comment]
Fixed
