### ISSUE TITLE
Can repository element commit attribute be a tag or is it sha only?

### ISSUE THREAD

**Issue by devlead** [NuGet/docs.microsoft.com-nuget#1481]
Reading through the [documentation](https://docs.microsoft.com/en-us/nuget/reference/nuspec#repository) and [schema](https://github.com/NuGet/NuGet.Client/blob/686dd6b060639a0fb401eceb4c3a4029c1482023/src/NuGet.Core/NuGet.Packaging/compiler/resources/nuspec.xsd#L83) around repository -> commit it's not totally clear if the commit attribute can be any git ref or sha only?

Schema just specified `xs:string`.

![image](https://user-images.githubusercontent.com/1647294/59848152-bf7a8080-9364-11e9-8b96-c51f64224f7c.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 06a19d7d-253d-f17f-6421-624c9867473d
* Version Independent ID: cc37eb17-f715-080c-7bfc-9eae868d50ba
* Content: [.nuspec File Reference for NuGet](https://docs.microsoft.com/en-us/nuget/reference/nuspec#repository)
* Content Source: [docs/reference/nuspec.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/master/docs/reference/nuspec.md)
* Product: **nuget**
* GitHub Login: @karann-msft
* Microsoft Alias: **karann**

**Comment by karann-msft** [comment]
it is meant to be the commit hash 
![image](https://user-images.githubusercontent.com/16904420/61476909-eb2c5e80-a942-11e9-8472-a9abef60cd2a.png)

**Comment by devlead** [comment]
@karann-msft ok thanks! 👍  Then I'll send an PR to clarify that and reference this issue.
