### ISSUE TITLE
More Clarification on Certificate Formats

### ISSUE THREAD

**Issue by ghost** [NuGet/docs.microsoft.com-nuget#1483]
I had some trouble getting `nuget sign` to work with the `-CertificatePath` option. This article says to export a "DER encoded binary X.509 (.CER)" file, but when I passed the exported `.cer` file to `nuget sign`, I got a `Key does not exist` error. Turns out I had to pass it a `.p12` file instead. This all felt like voodoo to me as I don't really know what the difference was between those two files. Some of this may be outside the scope of this article, and I am certainly new to code signing, but I think there should be more info on what certificate file format `nuget sign` requires, what file extension the file must have (if any), and maybe something about the difference between these formats.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5e2a0cf1-bbb7-18f7-bfed-f717da4c1812
* Version Independent ID: 0e4df241-34c7-d943-5811-9ed0d40291f1
* Content: [Signing NuGet Packages](https://docs.microsoft.com/en-us/nuget/create-packages/sign-a-package#feedback)
* Content Source: [docs/create-packages/Sign-a-Package.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/master/docs/create-packages/Sign-a-Package.md)
* Product: **nuget**
* GitHub Login: @rido-min
* Microsoft Alias: **rmpablos**

**Comment by ridomin** [comment]
The `sign` operation requires access to the private key, often found in a PFX file. The `.cer` file in DER format is required to register the certificate on NuGet.org, not for signing.

**Comment by DanVicarel** [comment]
So is it fair to say that:
- A file can contain just a private key, either in binary DER format or plaintext PEM format (which just contains the Base64-encoded DER data)
- A file can contain just a certificate, either in binary DER format or plantext PEM format. Binary certificate files typically have the `.cer` extension, while PEM certificate files typically have the `.crt` extension
- A file can contain both the certificate _and_ the private key, and is then pretty much always in a binary PKCS #12 format, with a `.p12` or `.pfx` extension. And _this_ is the kind of file that must be passed to the `-CertificatePath` option of `nuget sign`?

**Comment by emorell96** [comment]
Can you use EV Code Signing certificates? Specially the ones in a hardware token? Thanks.

**Comment by Willy-Kimura** [comment]
> Can you use EV Code Signing certificate? Specially the ones in a hardware token? Thanks.

@emorell96 Tried this severally from my end and can confirm it doesn't work with hardware-based EV Code Signing tokens. 
I've recently [reported this issue](https://github.com/NuGet/Home/issues/11930) it being of importance. Still waiting for feedback...
