### ISSUE TITLE
fallbackPackageFolders set via nuget.config

### ISSUE THREAD

**Issue by rrelyea** [NuGet/docs.microsoft.com-nuget#1487]
FallbackPackageFolders need to be added to this documentation.

FallbackPackageFolders are useful because they provide a way to preinstall packages such that no work needs to be done if the package is found there. Fallback package folders have the exact same folder/file structure as the global package folder: nupkg is there, and also all files are extracted.

Lookup logic:
- look in global package folder to see if the package/version has already been downloaded.
- look in fallback folders for a package/version match.
if either of those lookups was successful, then no download is necessary.
If a match wasn't found yet, then we check file sources, then http sources -- and download the packages.

```
<configuration>
  <fallbackPackageFolders>
    <add key="XYZ Offline Packages" value="C:\somePath\someFolder\"/>
  </fallbackPackageFolders>
</configuration>
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0ea1390e-db36-6759-3095-ebab9d546fdb
* Version Independent ID: ca88d8c6-0515-a267-aac3-a508c54157ab
* Content: [nuget.config File Reference](https://docs.microsoft.com/en-us/nuget/reference/nuget-config-file)
* Content Source: [docs/reference/nuget-config-file.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/master/docs/reference/nuget-config-file.md)
* Product: **nuget**
* GitHub Login: @karann-msft
* Microsoft Alias: **karann**

**Comment by Mikejo5000** [comment]
Updating doc with this content.
