### ISSUE TITLE
Error in restoring assembly references 

### ISSUE THREAD

**Issue by rs00556897** [NuGet/docs.microsoft.com-nuget#1493]
After cloning the projects from GitHub, all the project references are not working in my project. I have checked the Packages folders. it seems the dlls are available in the "packages" folder. And even try to install nugget. But it says that the required nugget packages are already available. How can I restore all my project Reference items? Kindly help

**Comment by Mikejo5000** [comment]
Did you try following procedures here?
https://docs.microsoft.com/en-us/nuget/consume-packages/package-restore
