### ISSUE TITLE
CLI not working on Windows, docs give no hint to require config

### ISSUE THREAD

**Issue by peterlukerow** [NuGet/docs.microsoft.com-nuget#1497]
Using a 2017 developer prompt or a standard command prompt both running as admin if I go to my solution folder and run:  "nuget restore" I just get the typical "'nuget' is not a recogniszed as an internal or external command, operable program or batch file" kind of message.

Similarly from the package manager console in VS2017 if I try to run the command I get a similar error message but more powershell-y.

What is needed to run this fr

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d63170c3-1894-8ead-b557-9937dae88172
* Version Independent ID: 67968c11-0aa0-f835-357d-8690911eb011
* Content: [NuGet CLI restore command](https://docs.microsoft.com/en-us/nuget/tools/cli-ref-restore#feedback)
* Content Source: [docs/tools/cli-ref-restore.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/master/docs/tools/cli-ref-restore.md)
* Product: **nuget**
* GitHub Login: @karann-msft
* Microsoft Alias: **karann**

**Comment by Mikejo5000** [comment]
@peterlukerow Did you install nuge.exe CLI? It must be installed separately. Also, you need to be in the directory containing the project.
https://docs.microsoft.com/en-us/nuget/consume-packages/package-restore#restore-using-the-nugetexe-cli

**Comment by peterlukerow** [comment]
You need to install something separately? How does VS let you search for and add nuGet packages then. This is some seriously messed up timewasting by MS. You would surely expect it to be installed with VS. This is one of the rare cases where the internet fails you. No where I found that tells you to run the nuget restore commands mentions anything about having to install any additional nuget CLI stuff.

**Comment by peterlukerow** [comment]
ok, download latest nuget.exe and added the path to my environment variables - completely annoying step. Given that nuget.exe has all the capabilities that VS on Windows has plus several more (see feature availability section - https://docs.microsoft.com/en-us/nuget/install-nuget-client-tools) it seems like MS should change VS to use nuGet.exe under the covers and deliver updated versions of it with point releases of VS, thus saving us all time and effort.
