### ISSUE TITLE
There are two places that refer to SymbolPackageFormat as a link but both are broken links

### ISSUE THREAD

**Issue by rbwhitaker** [NuGet/docs.microsoft.com-nuget#1503]
Two places in the document refer to: https://docs.microsoft.com/en-us/dotnet/core/tools/csproj.md#symbolpackageformat, which  gives me a 404 page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 22767e96-d56f-aa81-f1ca-17e256ed617e
* Version Independent ID: d7cdc676-2705-3cb1-bcd6-d1637460d5c7
* Content: [How to publish NuGet symbol packages using the new symbol package format '.snupkg'](https://docs.microsoft.com/en-us/nuget/create-packages/symbol-packages-snupkg)
* Content Source: [docs/create-packages/Symbol-Packages-snupkg.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/master/docs/create-packages/Symbol-Packages-snupkg.md)
* Product: **nuget**
* GitHub Login: @cristinamanum
* Microsoft Alias: **cristinamanu**

**Comment by loic-sharma** [comment]
Thanks for reporting! This should be fixed by: https://github.com/NuGet/docs.microsoft.com-nuget/pull/1500

**Comment by IanKemp** [comment]
@rbwhitaker or @loic-sharma you can probably close this now as it's fixed.

**Comment by loic-sharma** [comment]
Thanks for the reminder :)
