### ISSUE TITLE
The NuGet Command Line sections needs a subsection: How do I check the version

### ISSUE THREAD

**Issue by PetRose** [NuGet/docs.microsoft.com-nuget#1505]
Similar to whats written for the Visual Studio, you need a section 'How do I check the exact version of the NuGet tools that are installed?' for the Command Line.
Here, one could refer to this PS Command, as a useful command:
Get-PackageProvider -ListAvailable

---
#### Dokumentoplysninger

⚠ *Undlad at redigere denne sektion. Det er påkrævet til docs.microsoft.com ➟ GitHub-problemlinkning.*

* ID: a6a76206-726c-b428-483a-01facc5776b6
* Version Independent ID: d5834bd3-72e1-8760-1789-e8130bad8d2e
* Content: [NuGet Frequently-Asked Questions](https://docs.microsoft.com/da-dk/nuget/faqs/nuget-faq)
* Content Source: [docs/faqs/NuGet-FAQ.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/master/docs/faqs/NuGet-FAQ.md)
* Product: **nuget**
* GitHub Login: @shishirx34
* Microsoft Alias: **shishirh**

**Comment by Mikejo5000** [comment]
Updating docs in a couple places.
