### ISSUE TITLE
Clarify 'action upon package install' for build folder

### ISSUE THREAD

**Issue by rossng** [NuGet/docs.microsoft.com-nuget#1507]
The article contains this table

| Folder | Description | Action upon package install |
| --- | --- | --- |
| build | MSBuild `.targets` and `.props` files | Automatically inserted into the project file or `project.lock.json` (NuGet 3.x+). |

It's not clear to me what it means to have a targets/props file 'inserted into project.lock.json'. 

The words 'build props project.lock.json' are pretty much un-Googleable so I have no way of finding out.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f35f4267-e5e3-ddcf-d3e4-479fb233ce9f
* Version Independent ID: 6d49d66f-f777-7e44-3a45-723e3ad09a59
* Content: [How to create a NuGet package](https://docs.microsoft.com/en-us/nuget/create-packages/creating-a-package)
* Content Source: [docs/create-packages/Creating-a-Package.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/master/docs/create-packages/Creating-a-Package.md)
* Product: **nuget**
* GitHub Login: @karann-msft
* Microsoft Alias: **karann**

**Comment by Mikejo5000** [comment]
It's a deprecated feature, and is now removed from the docs.
