### ISSUE TITLE
Describe effect of developmentDependency setting when using PackageReference

### ISSUE THREAD

**Issue by rossng** [NuGet/docs.microsoft.com-nuget#1509]
When the package specifies `&lt;developmentDependency&gt;true&lt;/developmentDependency&gt;`, the `PackageReference` is created with custom `IncludeAssets` and `PrivateAssets` settings - at least in Visual Studio. I don't know if this is the ideal place to document it, but it should be somewhere. 

Also consider documenting the behaviour of this setting on the page about creating NuGet packages: https://docs.microsoft.com/en-us/nuget/create-packages/creating-a-package

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ff707668-94d6-25a5-9139-b18cc1b6b446
* Version Independent ID: 494847b9-4894-0beb-7ffa-39a2359999fa
* Content: [NuGet PackageReference format (package references in project files)](https://docs.microsoft.com/en-us/nuget/consume-packages/package-references-in-project-files)
* Content Source: [docs/consume-packages/Package-References-in-Project-Files.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/master/docs/consume-packages/Package-References-in-Project-Files.md)
* Product: **nuget**
* GitHub Login: @karann-msft
* Microsoft Alias: **karann**

**Comment by Mikejo5000** [comment]
Adding note with link to feature:
https://github.com/NuGet/Home/wiki/DevelopmentDependency-support-for-PackageReference
