### ISSUE TITLE
This doc should specify what correct format is for naming framework-specific folder.

### ISSUE THREAD

**Issue by shalomshachne** [NuGet/docs.microsoft.com-nuget#1510]
This needs to show what the naming convention is for framework version.  A example showing the directory tree would be much more helpful.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 72f129e2-7aaf-c191-1c5c-191b49dce8cd
* Version Independent ID: e24ae21e-ca22-cd8b-f72f-ac125925a597
* Content: [NuGet Warning NU5100](https://docs.microsoft.com/en-us/nuget/reference/errors-and-warnings/nu5100#feedback)
* Content Source: [docs/reference/errors-and-warnings/NU5100.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/master/docs/reference/errors-and-warnings/NU5100.md)
* Product: **nuget**
* GitHub Login: @mishra14
* Microsoft Alias: **karann**

**Comment by Mikejo5000** [comment]
Adding a link here rather than adding additional information to this topic.
