### ISSUE TITLE
The `SymbolPackageFormat` parameter is not documented

### ISSUE THREAD

**Issue by jozefizso** [NuGet/docs.microsoft.com-nuget#1514]
The parameter `-SymbolPackageFormat` used in the sample code is not documented.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2e18eb26-7a73-5e48-abd0-3d53476c6f91
* Version Independent ID: 5469de95-4b00-2fbd-f3c0-1cde036f3c7f
* Content: [NuGet CLI pack command](https://docs.microsoft.com/en-us/nuget/tools/cli-ref-pack)
* Content Source: [docs/tools/cli-ref-pack.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/master/docs/tools/cli-ref-pack.md)
* Product: **nuget**
* GitHub Login: @karann-msft
* Microsoft Alias: **karann**

**Comment by loic-sharma** [comment]
Sorry about that! I went ahead and added some documentation [here](https://github.com/NuGet/docs.microsoft.com-nuget/pull/1515), please let me know what you think.

**Comment by karann-msft** [comment]
@jozefizso thanks for catching that, @loic-sharma - thanks for fixing that.
The fix has now been merged.
