### ISSUE TITLE
Where are ProjectReference, Reference, FrameworkReference docs?

### ISSUE THREAD

**Issue by Nirmal4G** [NuGet/docs.microsoft.com-nuget#1526]
Whenever I search for ProjectReference / Reference / FrameworkReference, the Docs always lead me here.

Where can I find the ProjectReference / Reference / FrameworkReference docs?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ff707668-94d6-25a5-9139-b18cc1b6b446
* Version Independent ID: 494847b9-4894-0beb-7ffa-39a2359999fa
* Content: [NuGet PackageReference format (package references in project files)](https://docs.microsoft.com/en-us/nuget/consume-packages/package-references-in-project-files#controlling-dependency-assets)
* Content Source: [docs/consume-packages/Package-References-in-Project-Files.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/master/docs/consume-packages/Package-References-in-Project-Files.md)
* Product: **nuget**
* GitHub Login: @karann-msft
* Microsoft Alias: **karann**

**Comment by karann-msft** [comment]
what specifically about ProjectReference + NuGet are you looking for? 

Are you looking for this - https://docs.microsoft.com/en-us/visualstudio/msbuild/common-msbuild-project-items?view=vs-2019#projectreference ?

**Comment by Nirmal4G** [comment]
Yes, but those are for the old project system. What are the changes in Sdk-style `ProjectReference`, what are the new attributes, etc...?

These are not mentioned anywhere. Were they?

**Comment by Nirmal4G** [comment]
I found it for [`ProjectReference`](https://docs.microsoft.com/en-us/nuget/reference/msbuild-targets#project-to-project-references). It was mentioned [here](https://github.com/dotnet/sdk/issues/952#issuecomment-285107437).

But can't find it for the others.

**Comment by karann-msft** [comment]
@Nirmal4G - this is not going to be a part of NuGet content. As you have discovered, this will be a part of dotnet docs. If you can't find what you are looking, file an issue on the dotnet docs repo.

**Comment by Nirmal4G** [comment]
Moved to dotnet/docs#13521

Happy @karann-msft? 😁
