### ISSUE TITLE
Automatic package restore

### ISSUE THREAD

**Issue by damienestewart** [NuGet/docs.microsoft.com-nuget#1534]
Hi team,

Is there a way to know the exact command being used by VS to restore nuget packages before a build when we enable automatic package restore?

Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a3b20c46-c5f1-3a2a-738d-8aa8e69cf10c
* Version Independent ID: 7055e752-859b-6106-6802-70010d0305d9
* Content: [NuGet Package Restore](https://docs.microsoft.com/en-us/nuget/consume-packages/package-restore#feedback)
* Content Source: [docs/consume-packages/Package-Restore.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/master/docs/consume-packages/Package-Restore.md)
* Product: **nuget**
* GitHub Login: @karann-msft
* Microsoft Alias: **karann**

**Comment by Mikejo5000** [comment]
@nkolev92 Nikolche, not sure if this is documented. Is this just running "dotnet restore" or "nuget restore"?

**Comment by nkolev92** [comment]
It's not really documented. 

In reality it's a different implementation :)
Majority of the logic across dotnet restore/nuget restore/ VS restore is shared.

Automatic restore does the same thing that clicking "Restore NuGet Packages for solution" on the solution node does. 
I think that's the closest explanation.

**Comment by Mikejo5000** [comment]
OK, I don't think we need a doc change here as far as I can tell.
