### ISSUE TITLE
More details on signatures and timestamps

### ISSUE THREAD

**Issue by AlexanderMalyshev** [NuGet/docs.microsoft.com-nuget#1539]
Please provide commands of how to check what timestamps package has. How to solve the issue or workaround it.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 616fd14c-3bdc-b9ce-9d9f-4209ee408199
* Version Independent ID: 10b7ef44-d45a-d10b-c01e-6b3d2cc45e5e
* Content: [NuGet Warning NU3000](https://docs.microsoft.com/en-us/nuget/reference/errors-and-warnings/nu3000)
* Content Source: [docs/reference/errors-and-warnings/NU3000.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/master/docs/reference/errors-and-warnings/NU3000.md)
* Product: **nuget**
* GitHub Login: @mishra14
* Microsoft Alias: **karann**

**Comment by karann-msft** [comment]
@dtivel can you please help with this one?
