### ISSUE TITLE
Typo in NuGet docs home page

### ISSUE THREAD

**Issue by diverdan92** [NuGet/docs.microsoft.com-nuget#154]
It should say NuGet gives you access to thousands of package**s** from other developers on... (currently, the "s" is missing)
![image](https://cloud.githubusercontent.com/assets/6608201/21814736/1c033f6e-d70f-11e6-8fed-85957601e021.png)

**Comment by kraigb** [comment]
Fixed in https://github.com/NuGet/docs.microsoft.com-nuget/pull/156/. Please verify and close the issue.

**Comment by karann-msft** [comment]
Fixed.
