### ISSUE TITLE
Contributor URL broken

### ISSUE THREAD

**Issue by dtivel** [NuGet/docs.microsoft.com-nuget#1541]
At the top of this page, click on any contributor icon and it will dead end with a 404 like this:

https://github.com/NuGet/docs.microsoft.com-nuget/blob/master/docs/tools/nuget-exe-CLI-Reference.md

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 30f597bb-080f-188b-b1ba-a02efbe1e9ca
* Version Independent ID: 88e19d47-f4e1-0496-305c-af14f0d54afb
* Content: [NuGet Command-Line Interface (CLI) Reference](https://docs.microsoft.com/en-us/nuget/tools/nuget-exe-cli-reference)
* Content Source: [docs/tools/nuget-exe-CLI-Reference.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/master/docs/tools/nuget-exe-CLI-Reference.md)
* Product: **nuget**
* GitHub Login: @karann-msft
* Microsoft Alias: **karann**

**Comment by karann-msft** [comment]
@Mikejo5000 can you help with this?

**Comment by Mikejo5000** [comment]
@karann-msft I believe a push live will fix this. These are topics that have been moved. The links all work on the master branch on staging. Should I go ahead and do that, or do you want to?

**Comment by Mikejo5000** [comment]
Looks like Contributor and Edit links from the live site always link back to the master branch, so when we move files around, we should always sync to live as soon as possible (after merging into master).

**Comment by Mikejo5000** [comment]
Fixed. Here's the new live link for the page:
https://docs.microsoft.com/en-us/nuget/reference/nuget-exe-cli-reference

**Comment by dtivel** [comment]
Looks great.  Thanks, @Mikejo5000.
