### ISSUE TITLE
Confusing Lock File Wording

### ISSUE THREAD

**Issue by Silvenga** [NuGet/docs.microsoft.com-nuget#1542]
> The lock file is temporary and should not be added to source control.

Would it be safe to assume that with modern tooling this is talking about the `project.lock.json` file? Since we now have `packages.lock.json` in NuGet 4.9, this part may be a little confusing.

I can open a pr if I can get a confirmation on this.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 68d87097-68a1-cdd2-edfc-93fd2366fd0a
* Version Independent ID: b7d27caf-5476-2315-f4dc-e413b1be0726
* Content: [NuGet Package Dependency Resolution](https://docs.microsoft.com/en-us/nuget/consume-packages/dependency-resolution#feedback)
* Content Source: [docs/consume-packages/Dependency-Resolution.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/master/docs/consume-packages/Dependency-Resolution.md)
* Product: **nuget**
* GitHub Login: @karann-msft
* Microsoft Alias: **karann**

**Comment by karann-msft** [comment]
@Silvenga - that's right. We would appreciate the PR. Thank you for flagging that!

**Comment by karann-msft** [comment]
fixed in https://github.com/NuGet/docs.microsoft.com-nuget/pull/1568
