### ISSUE TITLE
dependency groups

### ISSUE THREAD

**Issue by zivkan** [NuGet/docs.microsoft.com-nuget#1544]
This page should also document how to create a different dependency group for each TFM. The info already exists in the nuspec reference, but should also be here since it's so important and related to multitargeting packages.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f1482e18-5f1f-3a8a-3321-66af52879ec5
* Version Independent ID: d70bd2f5-c04b-9207-62a0-4ecb6e8e5ca6
* Content: [Multi-targeting for NuGet Packages](https://docs.microsoft.com/en-gb/nuget/create-packages/supporting-multiple-target-frameworks#feedback)
* Content Source: [docs/create-packages/Supporting-Multiple-Target-Frameworks.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/master/docs/create-packages/Supporting-Multiple-Target-Frameworks.md)
* Product: **nuget**
* GitHub Login: @karann-msft
* Microsoft Alias: **karann**

**Comment by Mikejo5000** [comment]
@zivkan To avoid duplicating content, it might be best to either put this content inside of an INCLUDE or create a new section and just link to the sub-section in the .nuspec doc. Should this new section in multi-targeting doc be called "Grouping assemblies by TFM"?

**Comment by zivkan** [comment]
Technically most of the information on this page is duplicated elsewhere, but here it's focused on a specific scenario rather than listing all the features. Avoiding duplication is good, but simply linking to other docs, I worry that it will increase the barrier for customers to understand quickly how to achieve what they want.

Anyway, if adding a new section on this page, I think "Declaring dependencies" is a good name. In the context of a package, when someone says assemblies, I think of the files in the `lib/` or `ref/`, or `runtimes/<rid>/lib/` folders.
