### ISSUE TITLE
How do I ignore satellite assembly when publishing?

### ISSUE THREAD

**Issue by Nirmal4G** [NuGet/docs.microsoft.com-nuget#1549]
I want to reduce the my size of my published project. For local testing, I don't need all the language specific resources, just the neutral version is more than enough. I also test them manually by removing and adding language specific resources when the project is running!

So, How do I ignore the language folders from NuGet `PackageReference`?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ff707668-94d6-25a5-9139-b18cc1b6b446
* Version Independent ID: 494847b9-4894-0beb-7ffa-39a2359999fa
* Content: [NuGet PackageReference format (package references in project files)](https://docs.microsoft.com/en-us/nuget/consume-packages/package-references-in-project-files)
* Content Source: [docs/consume-packages/Package-References-in-Project-Files.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/master/docs/consume-packages/Package-References-in-Project-Files.md)
* Product: **nuget**
* GitHub Login: @karann-msft
* Microsoft Alias: **karann**

**Comment by karann-msft** [comment]
@Nirmal4G this is more of a product question. Can you file an issue on the Home repo - https://github.com/NuGet/Home/issues/new
For future reference, use the send feedback for product button to file such issues.

**Comment by Nirmal4G** [comment]
In any case, there should be docs section explaining those scenarios.

**Comment by Nirmal4G** [comment]
Issue moved to [NuGet/Home #8359](https://github.com/NuGet/Home/issues/8359) via [**ZenHub**](https://www.zenhub.com/)
