### ISSUE TITLE
API Link under "Explore NuGet" points to "NuGet.exe Credential Providers"

### ISSUE THREAD

**Issue by diverdan92** [NuGet/docs.microsoft.com-nuget#155]
Not sure if this is by design, but I would expect it to point to the "NuGet API V3" instead. 
![image](https://cloud.githubusercontent.com/assets/6608201/21814849/8769c746-d70f-11e6-8fc9-ed64702b15e4.png)

**Comment by kraigb** [comment]
Fixed in #156/ (points to the API page instead). Please verify and close the issue.

**Comment by karann-msft** [comment]
Fixed. Thanks @kraigb
