### ISSUE TITLE
Error	NU1202

### ISSUE THREAD

**Issue by cfgvii** [NuGet/docs.microsoft.com-nuget#1553]
How can I rectify this problem - the information above are not sufficient for me; i.e. how do I change: Change the project's target framework to one that the package supports.
Which Package should I use?
Full error :
Package Microsoft.AspNetCore.Blazor.Cli 0.8.0-preview-19104-04 is not compatible with netcoreapp2.2 (.NETCoreApp,Version=v2.2). Package Microsoft.AspNetCore.Blazor.Cli 0.8.0-preview-19104-04 supports: netcoreapp3.0 (.NETCoreApp,Version=v3.0)	BlazorSpreadsheet

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b2c2eb22-045b-1c00-512a-a9eb1be4d784
* Version Independent ID: 87d10a7f-725b-18ef-d5ae-12b2f1c568b3
* Content: [NuGet Error NU1202](https://docs.microsoft.com/en-us/nuget/reference/errors-and-warnings/nu1202?f1url=https%3A%2F%2Fmsdn.microsoft.com%2Fquery%2Fdev15.query%3FappId%3DDev15IDEF1%26l%3Den-US%26k%3Dk(NU1202)%26rd%3Dtrue)
* Content Source: [docs/reference/errors-and-warnings/NU1202.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/master/docs/reference/errors-and-warnings/NU1202.md)
* Product: **nuget**
* GitHub Login: @zhili1208
* Microsoft Alias: **lzhi**

**Comment by karann-msft** [comment]
@cfgvii - like the error calls out, you need to change the target framework of your project to `netcoreapp3.0`. You can do this in Visual Studio by editing the project properties or by editing the csproj directly.

```
  <PropertyGroup>
    <TargetFramework>netcoreapp3.0</TargetFramework>
    ...
  </PropertyGroup>
```

**Comment by cfgvii** [comment]
Hi Karan Nandwani,
Thanks for getting back to me.

I tried your suggestion but no luck - still getting NU1202; actually I did
use different target framework before I posted my comment but got nowhere.

The project I have trouble with is taken from:
https://github.com/Lupusa87/BlazorSpreadsheet. Strait-out-of-the-box
without any local tempering. I would be very grateful if you could offer
some more ideas how to go about.

Below are the two .csproj. The original TargetFramework was set to
netstandard2.0
which I have commented out.

Thankyou for your time,

Fred


========================= BlazorSpreadsheet.csproj ================

<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    
    <TargetFramework>netcoreapp3.0</TargetFramework>
    <RunCommand>dotnet</RunCommand>
    <RunArguments>blazor serve</RunArguments>
    <LangVersion>7.3</LangVersion>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Blazor"
Version="0.8.0-preview-19104-04" />
    <PackageReference Include="Microsoft.AspNetCore.Blazor.Build"
Version="0.8.0-preview-19104-04" PrivateAssets="all" />
    <DotNetCliToolReference Include="Microsoft.AspNetCore.Blazor.Cli"
Version="0.8.0-preview-19104-04" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference
Include="..\BlazorSpreadsheetComponent\BlazorSpreadsheetComponent.csproj" />
  </ItemGroup>

</Project>


========================== BlazorSpreadsheetComponent.csproj ==========

<Project Sdk="Microsoft.NET.Sdk.Razor">

  <PropertyGroup>
    
    <TargetFramework>netcoreapp3.0</TargetFramework>
    <OutputType>Library</OutputType>
    <IsPackable>true</IsPackable>
    <LangVersion>7.3</LangVersion>
  </PropertyGroup>

  <ItemGroup>
    
    <EmbeddedResource Include="content\**\*.js"
LogicalName="blazor:js:%(RecursiveDir)%(Filename)%(Extension)" />
    <EmbeddedResource Include="content\**\*.css"
LogicalName="blazor:css:%(RecursiveDir)%(Filename)%(Extension)" />
    <EmbeddedResource Include="content\**" Exclude="**\*.js;**\*.css"
LogicalName="blazor:file:%(RecursiveDir)%(Filename)%(Extension)" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Components.Browser"
Version="3.0.0-preview-19075-0444" />
    <PackageReference Include="Microsoft.AspNetCore.Components.Build"
Version="3.0.0-preview-19075-0444" PrivateAssets="all" />
  </ItemGroup>

</Project>
