### ISSUE TITLE
Guidance for packing WinRT native components is incorrect .NET Core 3.0

### ISSUE THREAD

**Issue by ocalvo** [NuGet/docs.microsoft.com-nuget#1563]
.NET Core 3.0 is able to reference native winrt components, but the final targets file is not compatible with .NET and the components cannot be referenced.

**Comment by ocalvo** [comment]
[This is section that needs update](https://docs.microsoft.com/en-us/nuget/guides/create-uwp-packages#adding-targets)

**Comment by ocalvo** [comment]
Adding .targets
Next, C++ and JavaScript projects that might consume your NuGet package need a .targets file to identify the necessary assembly and winmd files. (C# and Visual Basic projects do this automatically.) Create this file by copying the text below into ImageEnhancer.targets and save it in the same folder as the .nuspec file. Note: This .targets file needs to be the same name as the package ID (e.g. the <Id> element in the .nupspec file):

```
<?xml version="1.0" encoding="utf-8"?>
<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
    <PropertyGroup>
        <ImageEnhancer-Platform Condition="'$(Platform)' == 'Win32'">x86</ImageEnhancer-Platform>
        <ImageEnhancer-Platform Condition="'$(Platform)' != 'Win32'">$(Platform)</ImageEnhancer-Platform>
    </PropertyGroup>
    <ItemGroup>
        <Reference Include="$(MSBuildThisFileDirectory)..\..\lib\uap10.0\ImageEnhancer.winmd">
            <Implementation>ImageEnhancer.dll</Implementation>
             <Private>true</Private>
        </Reference>
    <ReferenceCopyLocalPaths Include="$(MSBuildThisFileDirectory)..\..\runtimes\win10-$(ImageEnhancer-Platform)\native\ImageEnhancer.dll" />
    </ItemGroup>
</Project>
```

Then refer to ImageEnhancer.targets in your .nuspec file:

```
<?xml version="1.0"?>
<package >
    <metadata>
        ...
    </metadata>
    <files>
        ...

        <!-- .targets -->
        <file src="ImageEnhancer.targets" target="build"/>

    </files>
</package>
```

**Comment by karann-msft** [comment]
@ocalvo - can you help us with a PR to this doc - https://github.com/NuGet/docs.microsoft.com-nuget/blob/master/docs/guides/Create-UWP-Packages.md

**Comment by karann-msft** [comment]
@ocalvo - it is not clear to what needs to change. Can you let me know if this issue is still valid and provide a brain dump that'll help me make the necessary docs update.

**Comment by karann-msft** [comment]
We are rolling up all native and C++ related issues into #238.
