### ISSUE TITLE
Create release notes for 5.1.0

### ISSUE THREAD

**Issue by pascalberger** [NuGet/docs.microsoft.com-nuget#1567]
There are neither release notes for 5.1.0 (currently the recommended version) nor 5.2.0 available [here](https://docs.microsoft.com/en-us/nuget/release-notes/nuget-5.0-rtm)

**Comment by karann-msft** [comment]
it already exists - https://docs.microsoft.com/en-us/nuget/release-notes/nuget-5.1-rtm

the TOC needs updates. Which will happen soon as well?=.
