### ISSUE TITLE
.Net Standard v2.0 is not recognised as being the same as .Net Framework v4.6.1

### ISSUE THREAD

**Issue by overfilledwaistcoat** [NuGet/docs.microsoft.com-nuget#1580]
VS 2019 community edition, I get this error on a class library that is set up to use .Net Standard v2.0  My understanding (which may well be wrong) is that .Net Standard 2.0 is a wrapper around (among other things) the .Net Framework library v4.6.1.  So in this case is the error message misleading?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 377ae860-386f-149f-c5e0-410d3aa89dbc
* Version Independent ID: 2b145147-fd3f-d1aa-2694-071a31542d9a
* Content: [NuGet Errors and Warnings Reference](https://docs.microsoft.com/en-us/nuget/reference/errors-and-warnings/nu1701?f1url=https%3A%2F%2Fmsdn.microsoft.com%2Fquery%2Fdev16.query%3FappId%3DDev16IDEF1%26l%3DEN-US%26k%3Dk(NU1701)%26rd%3Dtrue#feedback)
* Content Source: [docs/reference/errors-and-warnings/NU1701.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/master/docs/reference/errors-and-warnings/NU1701.md)
* Product: **nuget**
* GitHub Login: @zhili1208
* Microsoft Alias: **lzhi**

**Comment by nkolev92** [comment]
Hey @overfilledwaistcoat, 

The specific code that you linked is a warning only. It might have gotten elevated to an error if you have TreatWarningsAsErrors (it's possible that your project template has it). 

netstandard2.0 is a subset of what net461, you can read more about it here. 
https://docs.microsoft.com/en-us/dotnet/standard/net-standard
