### ISSUE TITLE
This project references NuGet package(s) that are missing on this computer

### ISSUE THREAD

**Issue by ayalwe** [NuGet/docs.microsoft.com-nuget#1581]
I clone a project from azure git and I can't run its 
I get many errors "are you missing a using .. or an assembly reference"
and this error with the NuGet.
I did all that you say in the troubleshooting to restore the NuGet packages
but still, my project doesn't build successfully.

**Comment by karann-msft** [comment]
@alexvy86 please file an issue on the Home repo for all product-related bugs - https://github.com/nuget/home/issues

**Comment by alexvy86** [comment]
@karann-msft I assume you meant that message for @ayalwe ?

**Comment by ginow** [comment]
Is this issue fixed?, because I'm still getting a similar issue.
![image](https://user-images.githubusercontent.com/15030674/71335064-d80f6180-2566-11ea-8f6f-3223ae69698f.png)
