### ISSUE TITLE
NuGet Fails to Add Reference

### ISSUE THREAD

**Issue by jmawebtech** [NuGet/docs.microsoft.com-nuget#1586]
Hi,

I have a class library called Amazon.Core. The class library has some references, outlined in the .nuspec file I described.

When I upload the package and add it, Amazon.Core fails to reference. Do I need to change my nuspec file?

<?xml version="1.0"?>
<package>
  <metadata>
    <id>Amazon.Core</id>
    <version>1.0.0.3</version>
    <title>Amazon Integration</title>
    <authors>JMA Web Technologies</authors>
    <owners>JMA Web Technologies</owners>
    <iconUrl>http://www.jmawebtechnologies.com/wp-content/uploads/2019/01/amazon@2x.png</iconUrl>
    <requireLicenseAcceptance>false</requireLicenseAcceptance>
    <description>Syncs orders from Amazon.</description>
    <releaseNotes>First release.</releaseNotes>
    <copyright>Copyright JMA Web Technologies 2019</copyright>
    <tags>Amazon</tags>
    <references>
      <reference file="MarketplaceWebService.dll"></reference>
      <reference file="MWSClientCsRuntime-1.0.dll"></reference>
      <reference file="MWSFinances_2015-05-01_v2019-02-25.dll"></reference>
      <reference file="MWSOrders_2013-09-01_v2018-10-31.dll"></reference>
      <reference file="MWSSellers_2011-07-01_v2015-06-18.dll"></reference>
    </references>
  </metadata>
  <files>
    <file target="lib" src="bin\Debug\Amazon.Core.dll"/>
    <file target="lib" src="bin\Debug\MarketplaceWebService.dll"/>
    <file target="lib" src="bin\Debug\MWSClientCsRuntime-1.0.dll"/>
    <file target="lib" src="bin\Debug\MWSFinances_2015-05-01_v2019-02-25.dll"/>
    <file target="lib" src="bin\Debug\MWSOrders_2013-09-01_v2018-10-31.dll"/>
    <file target="lib" src="bin\Debug\MWSSellers_2011-07-01_v2015-06-18.dll"/>
  </files>
</package>

**Comment by karann-msft** [comment]
@jmawebtech - where are you uploading this package to? what is the error you get?

**Comment by jmawebtech** [comment]
I resolved it. In the nuspec file, I had to add this code:

  <files>
    <file target="lib\net461" src="bin\Debug\MarketplaceWebService.dll"/>
    <file target="lib\net461" src="bin\Debug\MWSClientCsRuntime-1.0.dll"/>
    <file target="lib\net461" src="bin\Debug\MWSFinances_2015-05-01_v2019-02-25.dll"/>
    <file target="lib\net461" src="bin\Debug\MWSOrders_2013-09-01_v2018-10-31.dll"/>
    <file target="lib\net461" src="bin\Debug\MWSSellers_2011-07-01_v2015-06-18.dll"/>
  </files>
