### ISSUE TITLE
Discoverability of the references for the nuget targets

### ISSUE THREAD

**Issue by nkolev92** [NuGet/docs.microsoft.com-nuget#1595]
After the recent changes the msbuild targets are not on the front page. 

The discoverability is also lower, getting to in advanced tasks is not obvious. 

The name is also confusing, as it's "Specify MSBuild pack and restore targets" 

So a few questions I guess. 

- Why did we remove this from references?
It's a link I very frequently share with both internal and external customers. 

- I don't necessarily think msbuild pack/restore targets are advanced tasks. They are core scenarios for .NET Core folks. 

//cc @karann-msft @Mikejo5000 

This is just my gut instinct, would be happy to discuss further.

**Comment by Mikejo5000** [comment]
I had some input that this article was more about creating a package using MSBuild, and that it could go in the "create packages" section. However, after working on some of the new topics and getting some feedback, it became clear that this wasn't really a good introduction for the subject of creating a package using MSBuild.

There's a new article on MSBuild for creating packages, equivalent to the article on dotnet CLI:
https://docs.microsoft.com/en-us/nuget/create-packages/creating-a-package-msbuild (let me know if there's anything missing that needs to be there).

It makes sense to me to move the article in question back to reference. It's better to identify a user task when possible, so I used "Specify..." in the TOC link, though not in the H1. But, for a reference doc, identifying the user task is less important.

**Comment by nkolev92** [comment]
I think that makes sense. Moving it back to reference would help.

I like the create package with msbuild, I have a few suggestions to improve first section of that page, but I'll create a new issue for that.

**Comment by Mikejo5000** [comment]
Sounds good, thanks! I'll move the article back to reference.
