### ISSUE TITLE
Create a Nuget Package using MSBuild improvements

### ISSUE THREAD

**Issue by nkolev92** [NuGet/docs.microsoft.com-nuget#1596]
The page overall looks great, but I think we can improve the first few paragraphs that explain how to enable the scenario in question. 

> To use MSBuild, included with Visual Studio or installed separately, you must also install the dotnet CLI, see Install NuGet client tools. Starting in Visual Studio 2017, the dotnet CLI is included with .NET Core workloads.

MSBuild comes in with every workload that contains NuGet. MSBuild is pretty much everywhere. 
MSBuild can be used without the dotnet CLI.

My suggestion would be something like: 
> MSBuild comes preinstalled with every Visual Studio workload that contains NuGet. Additionally you can also use MSBuild through the dotnet CLI with https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-msbuild

The links would be made better and according to the guidelines of course :) 

> To build with MSBuild, you need to add the NuGet.Build.Tasks.Pack package to the project dependencies. For detailed information about MSBuild pack targets, see NuGet pack and restore as MSBuild targets.

The pack targets are available with SDK based projects by default. 
You only need to install the package with non-SDK based projects, so suggestion is something along the lines of: 

> SDK-style projects have the pack functionality available by default. For non SDK-style PackageReference projects, you need to add the NuGet.Build.Tasks.Pack package to the project dependencies. For detailed information about MSBuild pack targets, see NuGet pack and restore as MSBuild targets.

//cc @Mikejo5000 @karann-msft

**Comment by Mikejo5000** [comment]
Thanks! Updating doc
