### ISSUE TITLE
'error NU5000 - Nuspec file does not exist in package' should either identify the package or reinstall it

### ISSUE THREAD

**Issue by kartheekp-ms** [NuGet/docs.microsoft.com-nuget#1613]
Add new error code NU5037 to the docs. This issue is related to NuGet/Home/issues/8291

**Comment by karann-msft** [comment]
@kartheekp-ms - can you open a PR with the required changes. You can create a new file for NU5037 here - https://github.com/NuGet/docs.microsoft.com-nuget/tree/master/docs/reference/errors-and-warnings
