### ISSUE TITLE
TFM compatibility

### ISSUE THREAD

**Issue by ryantrem** [NuGet/docs.microsoft.com-nuget#1618]
This page doesn't seem to give much information on TFM compatibility. For example, if I have a net461 app, it can use a netstandard2.0 library, PCL Profile2/3/4/etc. It gets more complicated when something like a net461 app consumes a project/package that, for example, supports both netstandard1.4 and PCL Profile4. Both are "compatible" with net461, so which one will it choose? It would be super helpful if this documentation provided the complete list of compatible TFMs (along with precedence) for each other TFM.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0a0f5267-208d-8af2-ef18-dae7407eefad
* Version Independent ID: 19b00f91-5d31-0d4d-388b-30b1bd4e7c0f
* Content: [Target Frameworks Reference for NuGet](https://docs.microsoft.com/en-us/nuget/reference/target-frameworks)
* Content Source: [docs/reference/target-frameworks.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/master/docs/reference/target-frameworks.md)
* Product: **nuget**
* GitHub Login: @karann-msft
* Microsoft Alias: **karann**

**Comment by bcrosnier** [comment]
I also needed this earlier (in our case, we need to pick a compatible framework for a given target and set of NuGet packages).

To my knowledge, this mapping is done in [DefaultFrameworkMappings](https://github.com/NuGet/NuGet.Client/blob/dev/src/NuGet.Core/NuGet.Frameworks/DefaultFrameworkMappings.cs), but a dump of the actual [CompatibilityTable](https://github.com/NuGet/NuGet.Client/blob/dev/src/NuGet.Core/NuGet.Frameworks/CompatibilityTable.cs) in readable form would be appreciated, especially if it can incorporate precedence.

**Comment by JonDouglas** [comment]
@ryantrem & @bcrosnier 

I know this might be a little parallel to this issue reported, but does the .NET docs do a better job of explaining what you're referring to in terms of a compatibility matrix? 

https://docs.microsoft.com/en-us/dotnet/standard/frameworks or https://docs.microsoft.com/en-us/dotnet/standard/net-standard

Is it that the clarification on the resolution / preferred behavior is what you're after? Or is it knowing what is the modern supported story for things such as PCL -> NetStandard -> Net5?

Generally speaking, the newest released API surface should be the "happy path" for resolution given the surface is compatible and covered.
