### ISSUE TITLE
nuget pack IS NOT the same as dotnet pack or msbuild -t:pack

### ISSUE THREAD

**Issue by IanKemp** [NuGet/docs.microsoft.com-nuget#1651]
Because it doesn't support `PackageReference` elements as dependencies, see: https://github.com/NuGet/Home/issues/4491

This command should be marked as legacy and discouraged from being used unless or until the NuGet team decide to actually fix the linked issue.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d85bd49a-f83d-7588-5c70-edad5270c0f0
* Version Independent ID: 11cc9edc-4803-c768-5cdd-25c9b41ec8d3
* Content: [NuGet CLI pack command](https://docs.microsoft.com/en-us/nuget/reference/cli-reference/cli-ref-pack)
* Content Source: [docs/reference/cli-reference/cli-ref-pack.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/master/docs/reference/cli-reference/cli-ref-pack.md)
* Product: **nuget**
* GitHub Login: @karann-msft
* Microsoft Alias: **karann**

**Comment by paul-charousset** [comment]
Thank you so much for your comment. Just lost half a day to this, and now works perfectly after I switched to dotnet pack instead of nuget pack.

**Comment by IanKemp** [comment]
> Thank you so much for your comment. Just lost half a day to this, and now works perfectly after I switched to dotnet pack instead of nuget pack.

That's about the amount of time I spent figuring this out. :/ Glad it could help you.
