### ISSUE TITLE
Add note that dotnet/MSBuild symbol output can be controlled via the command-line

### ISSUE THREAD

**Issue by IanKemp** [NuGet/docs.microsoft.com-nuget#1653]
It's not necessary to edit the `csproj` file to specify the symbol format, it can be specified on the command-line:

`dotnet pack -p:IncludeSymbols=true -p:SymbolPackageFormat=snupkg`

or

`msbuild /t:pack /p:IncludeSymbols=true /p:SymbolPackageFormat=snupkg`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 22767e96-d56f-aa81-f1ca-17e256ed617e
* Version Independent ID: d7cdc676-2705-3cb1-bcd6-d1637460d5c7
* Content: [How to publish NuGet symbol packages using the new symbol package format '.snupkg'](https://docs.microsoft.com/en-us/nuget/create-packages/symbol-packages-snupkg)
* Content Source: [docs/create-packages/Symbol-Packages-snupkg.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/master/docs/create-packages/Symbol-Packages-snupkg.md)
* Product: **nuget**
* GitHub Login: @cristinamanu
* Microsoft Alias: **cristinamanu**

**Comment by karann-msft** [comment]
Fixed in https://github.com/NuGet/docs.microsoft.com-nuget/pull/1654
