### ISSUE TITLE
.NET Core 3.0.100-preview9-014004 gives warning and links to this page

### ISSUE THREAD

**Issue by devlead** [NuGet/docs.microsoft.com-nuget#1660]
Latest .NET Core 3 preview ( 3.0.100-preview9-014004 ) gives below warning on dotnet pack, links to this page but seems to be no details yet about the new upcoming elements.
```diff 
- error NU5048: The 'PackageIconUrl'/'iconUrl' element is deprecated. Consider using the 'PackageIcon'/'icon' element instead. Learn more at https://aka.ms/deprecateIconUrl
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 06a19d7d-253d-f17f-6421-624c9867473d
* Version Independent ID: cc37eb17-f715-080c-7bfc-9eae868d50ba
* Content: [.nuspec File Reference for NuGet](https://docs.microsoft.com/en-us/nuget/reference/nuspec#feedback)
* Content Source: [docs/reference/nuspec.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/master/docs/reference/nuspec.md)
* Product: **nuget**
* GitHub Login: @karann-msft
* Microsoft Alias: **karann**

**Comment by loic-sharma** [comment]
It looks like the documentation is still in progress with pull request https://github.com/NuGet/docs.microsoft.com-nuget/pull/1661. Here is the latest preview: https://github.com/NuGet/docs.microsoft.com-nuget/blob/1d0a27127fb7814c9da9c767e3fcb3bacf397327/docs/reference/errors-and-warnings/NU5048.md

Feel free to leave comments on the pull request if you have any feedback!

**Comment by devlead** [comment]
Ok, maybe https://aka.ms/deprecateIconUrl should go to that PR or nuget wiki then for now. A bit confusing otherwise.

**Comment by devlead** [comment]
Ah PR seems merged now,  so guess it'll be out on web soon.

**Comment by devlead** [comment]
And it's out would probably be good to document minimum required nuget version.
