### ISSUE TITLE
Link to an explanation of adding nuget PATH variables.

### ISSUE THREAD

**Issue by cdvillard** [NuGet/docs.microsoft.com-nuget#1674]
The Windows installation section doesn't take into consideration whether the user understands PATH variables, so even simply a link to an explanation would be helpful.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6d00296b-ac62-3d6c-beea-b2042b63dc5b
* Version Independent ID: 587da972-dfde-88bc-9dc0-7c32dae3454b
* Content: [NuGet Command-Line Interface (CLI) Reference](https://docs.microsoft.com/en-us/nuget/reference/nuget-exe-cli-reference#feedback)
* Content Source: [docs/reference/nuget-exe-CLI-Reference.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/master/docs/reference/nuget-exe-CLI-Reference.md)
* Product: **nuget**
* GitHub Login: @karann-msft
* Microsoft Alias: **karann**

**Comment by Quico20** [comment]
I honestly don't understand the step 3. could you explain more about the meaning of path???

**Comment by cdvillard** [comment]
@Quico20, what they're referring to by PATH, is an environment variable. In essence, it's a literal variable used to store the file paths to executable commands in the system. For example, when you run a command in the command line like `npm'`or `git`, what you're actually doing is running the program located at, say, `C://Program Files/nodejs/npm` and passing it a few commands.

**Comment by jerroldneal** [comment]
Use this existing directory that should be in your path already:

c:\Users\{your user name}\.dotnet\tools\

Example:

move c:\Users\{your user name}\downloads\nuget.exe c:\Users\{your user name\.dotnet\tools\

or 

move %USERPROFILE%\downloads\nuget.exe %USERPROFILE%\.dotnet\tools\

To confirm it is in your path:

which nuget.exe

nuget ?

**Comment by jerroldneal** [comment]
If you downloaded to your default download directory:
1) press windowskey-r
2) cmd.exe
3) move %USERPROFILE%\downloads\nuget.exe %USERPROFILE%\.dotnet\tools\
4) nuget ?

**Comment by jerroldneal** [comment]
If you downloaded to your default download directory:

press windowskey-r
cmd.exe
move %USERPROFILE%\downloads\nuget.exe %USERPROFILE%\.dotnet\tools\
nuget ?

**Comment by amoraitis** [comment]
> If you downloaded to your default download directory:
> 
> press windowskey-r
> cmd.exe
> move %USERPROFILE%\downloads\nuget.exe %USERPROFILE%.dotnet\tools
> nuget ?

The destination path should be `%USERPROFILE%\.dotnet\tools`. You were missing a backslash...

**Comment by karann-msft** [comment]
The idea here is to link to authoritative docs on how to set up path variables and not document it as part of the docs itself. If anyone has recommendations on the official docs on the path variable, please comment on this issue. For now, I am closing this issue.
