### ISSUE TITLE
Path too long when consuming package with a .pp in it

### ISSUE THREAD

**Issue by julienshepherd** [NuGet/docs.microsoft.com-nuget#1676]
I have a .netstandard2.0 package containing a .pp file. When I consume this package in another UWP package (min target 1803, target 1903), I get a path too long error. This happens as well when using a CI pipeline in the restore build definition task. The error comes out in both Release and Debug modes.

It would be useful to better explain how the .pp logic works so we can avoid these issues. It would help to answer questions like: what happens when you install a package with a .pp file in it? Why there is this long path with something resembling a guid or thumbprint in it? Even if I use tokens so the infrastructure will copy the .pp file like $rootnamespace$, the same error happens.

![PackageStructure](https://user-images.githubusercontent.com/20776298/64689300-c06c0b80-d496-11e9-9f51-e5035eddb408.PNG)

![PathTooLong blurred](https://user-images.githubusercontent.com/20776298/64689312-c2ce6580-d496-11e9-9f4c-ad2f40ee0e1c.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 40bb9dee-46d6-4064-83e8-ba2e22ac6afe
* Version Independent ID: aac0bbd8-645b-ccf8-bec9-e0d970c8b089
* Content: [Source and config file transformations for NuGet packages](https://docs.microsoft.com/en-us/nuget/create-packages/source-and-config-file-transformations#feedback)
* Content Source: [docs/create-packages/Source-and-Config-File-Transformations.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/master/docs/create-packages/Source-and-Config-File-Transformations.md)
* Product: **nuget**
* GitHub Login: @karann-msft
* Microsoft Alias: **karann**

**Comment by karann-msft** [comment]
Issue moved to [NuGet/Home #8588](https://github.com/NuGet/Home/issues/8588) via [**ZenHub**](https://www.zenhub.com/)

**Comment by karann-msft** [comment]
@julienshepherd - I have moved your issue to the Home repo which is meant for product feedback.

Please use the "product feedback" button to file issues about the product. 

![image](https://user-images.githubusercontent.com/16904420/64880442-0ea31b00-d60d-11e9-910a-8492010506a9.png)
