### ISSUE TITLE
Typo in remark about .nuget folder

### ISSUE THREAD

**Issue by ralphhendriks** [NuGet/docs.microsoft.com-nuget#1678]
> NuGet 3.3 and earlier used a .nuget folder for solution-wide settings. This file is not used in NuGet 3.4+.

Should probably read:

> NuGet 3.3 and earlier used a .nuget folder for solution-wide settings. This **folder** is not used in NuGet 3.4+.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 370d9d91-9f35-79aa-3ace-7b77436e988f
* Version Independent ID: 3da4591a-3d3d-c07a-6672-97964de13b14
* Content: [Common NuGet configurations](https://docs.microsoft.com/en-us/nuget/consume-packages/configuring-nuget-behavior)
* Content Source: [docs/consume-packages/configuring-nuget-behavior.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/master/docs/consume-packages/configuring-nuget-behavior.md)
* Product: **nuget**
* GitHub Login: @karann-msft
* Microsoft Alias: **karann**

**Comment by karann-msft** [comment]
thanks for catching that! we have made it super easy to contribute to our docs - just click on the edit button on the top right of the page and submit a PR! 

![image](https://user-images.githubusercontent.com/16904420/64880183-68571580-d60c-11e9-98e9-5c20ac2d90dd.png)
