### ISSUE TITLE
No good examples of packaging app.config related to a dll

### ISSUE THREAD

**Issue by gilescope** [NuGet/docs.microsoft.com-nuget#1681]
Microsoft has pushed app.config files travelling with their associated dlls for _many_ _many_ years.
It would be great to see an example of how app.config should be added to a nuget package.

The docs on contentFiles talk of any/any/ dirs but that seems to be include dirs not target dirs? 

https://github.com/NuGet/docs.microsoft.com-nuget/blob/master/docs/reference/nuspec.md

Given how important app.config files are (/were?) I'm probably not alone in wanting to package them.

**Comment by gilescope** [comment]
Maybe its not documented as the solution is unknown? 
This issue seems unresolved: https://github.com/dotnet/sdk/issues/3249

**Comment by gilescope** [comment]
There is Install.ps1 (see https://stackoverflow.com/questions/49885009/nuget-package-does-not-restore-all-dlls-and-dependencies ) but people are moving away from using Install.ps1 to fix their problems. I would think there's a solution using contentFiles potentially...

**Comment by rrelyea** [comment]
This sample should show how to do XDT transform via msbuild targets -- which would be compatible with PackageReference projects:
https://github.com/NuGet/Samples/tree/master/XDTransformExample

**Comment by karann-msft** [comment]
@gilescope - I hope the sample Rob pointe you to was helpful. Feel free to reopen the issue if that is not the case.
