### ISSUE TITLE
Cross platform availability

### ISSUE THREAD

**Issue by riscie** [NuGet/docs.microsoft.com-nuget#1682]
If I understand correctly, the process described here aplies to not only .NET but .NET Core. This article does not describe how to sign packages on linux/unix. Is it possible to sign packages with the `dotnet` command on linux? (`dotnet nuget sign` is not available) If it is, please add it to the article. If it is not, there should also be a section about the information that it is not possible.

Thanks for all your work.

**Edit:**
In the meantime I stumbled upon: https://docs.microsoft.com/en-us/nuget/install-nuget-client-tools which answers my questions. Maybe we still could get a link or a small info-section regarding other platforms than windows to the article.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5e2a0cf1-bbb7-18f7-bfed-f717da4c1812
* Version Independent ID: 0e4df241-34c7-d943-5811-9ed0d40291f1
* Content: [Signing NuGet Packages](https://docs.microsoft.com/en-us/nuget/create-packages/sign-a-package#feedback)
* Content Source: [docs/create-packages/Sign-a-Package.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/master/docs/create-packages/Sign-a-Package.md)
* Product: **nuget**
* GitHub Login: @rido-min
* Microsoft Alias: **rmpablos**

**Comment by karann-msft** [comment]
we are working on it. Follow this issue to track progress - Support package verification / signing for dotnet core & mono (xplat) [#7939](https://github.com/NuGet/Home/issues/7939)
