### ISSUE TITLE
.NET Core Global Tool support

### ISSUE THREAD

**Issue by kbilsted** [NuGet/docs.microsoft.com-nuget#1690]
When targeting multiple frameworks, nuget no longer displays ` This package contains a .NET Core Global Tool you can call from the shell/command line.` and you cannot install your tool through the command line.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 71d8ea9f-7126-5908-64c1-68cbd135bd91
* Version Independent ID: a6f41006-95fc-bd79-6885-812d01f7872d
* Content: [Multi-targeting for NuGet Packages in your project file](https://docs.microsoft.com/en-us/nuget/create-packages/multiple-target-frameworks-project-file#feedback)
* Content Source: [docs/create-packages/multiple-target-frameworks-project-file.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/master/docs/create-packages/multiple-target-frameworks-project-file.md)
* Product: **nuget**
* GitHub Login: @karann-msft
* Microsoft Alias: **karann**

**Comment by karann-msft** [comment]
Issue moved to [NuGet/Home #8631](https://github.com/NuGet/Home/issues/8631) via [**ZenHub**](https://www.zenhub.com/)
