### ISSUE TITLE
"Source Link guidance" link is broken

### ISSUE THREAD

**Issue by canton7** [NuGet/docs.microsoft.com-nuget#1694]
"Source Link guidance" links to https://docs.microsoft.com/en-us/dotnet/standard/library-guidance/sourcelink.md, which 404's.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 22767e96-d56f-aa81-f1ca-17e256ed617e
* Version Independent ID: d7cdc676-2705-3cb1-bcd6-d1637460d5c7
* Content: [How to publish NuGet symbol packages using the new symbol package format '.snupkg'](https://docs.microsoft.com/en-us/nuget/create-packages/symbol-packages-snupkg#feedback)
* Content Source: [docs/create-packages/Symbol-Packages-snupkg.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/master/docs/create-packages/Symbol-Packages-snupkg.md)
* Product: **nuget**
* GitHub Login: @cristinamanu
* Microsoft Alias: **cristinamanu**

**Comment by loic-sharma** [comment]
Hello, thank you for reporting this! This should be fixed by https://github.com/NuGet/docs.microsoft.com-nuget/pull/1685

For now, you can find the proper page by removing the `.md` from the URL.

**Comment by karann-msft** [comment]
That PR has not been merged.
