### ISSUE TITLE
Option to choose PackageReference or packages.config

### ISSUE THREAD

**Issue by zivkan** [NuGet/docs.microsoft.com-nuget#1695]
This page should show the general NuGet options dialog, particularly the ability to select PackageReference or packages.config as default, and the option to prompt on first package install to choose format.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9cbbd8f5-8155-0057-b0cc-0b96ee35aad4
* Version Independent ID: 8b085f6d-05f3-e213-6b2a-3f7274581111
* Content: [Install and manage NuGet packages in Visual Studio](https://docs.microsoft.com/en-gb/nuget/consume-packages/install-use-packages-visual-studio)
* Content Source: [docs/consume-packages/install-use-packages-visual-studio.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/master/docs/consume-packages/install-use-packages-visual-studio.md)
* Product: **nuget**
* GitHub Login: @karann-msft
* Microsoft Alias: **karann**

**Comment by karann-msft** [comment]
@zivkan - can you please help with a PR :)

**Comment by karann-msft** [comment]
The doc should also have a screenshot of VS.
