### ISSUE TITLE
Are the xamarin targets appropriate?

### ISSUE THREAD

**Issue by SittenSpynne** [NuGet/docs.microsoft.com-nuget#1708]
Tools like Nugetizer 3000 use target framework values like "xamarinios10" and "monodroid90". Which is correct?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0a0f5267-208d-8af2-ef18-dae7407eefad
* Version Independent ID: 19b00f91-5d31-0d4d-388b-30b1bd4e7c0f
* Content: [Target Frameworks Reference for NuGet](https://docs.microsoft.com/en-us/nuget/reference/target-frameworks)
* Content Source: [docs/reference/target-frameworks.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/master/docs/reference/target-frameworks.md)
* Product: **nuget**
* GitHub Login: @karann-msft
* Microsoft Alias: **karann**

**Comment by karann-msft** [comment]
"xamarinios" is a valid TFM. The suffix "10" is treated like a version similar to the "48" in "net48". I am not sure if "monodroid" is a valid TFM. I did find "monoandroid"

**Comment by karann-msft** [comment]
@SittenSpynne - I assume that answered your question. Please reopen if you have further questions on this topic.
