### ISSUE TITLE
nuget.exe pack should be invoked with the same properties/params as build

### ISSUE THREAD

**Issue by nkolev92** [NuGet/docs.microsoft.com-nuget#1709]
Motivation from the thread in the nuget/home repo. 

https://github.com/NuGet/Home/issues/7131#issuecomment-535497315

Basically if nuget pack and build are run with different properties, NuGet might end up looking in the wrong directory.

**Comment by karann-msft** [comment]
@nkolev92 - can u help with a PR here :)
