### ISSUE TITLE
Examples are lacking.

### ISSUE THREAD

**Issue by twopieman** [NuGet/docs.microsoft.com-nuget#1710]
Can we please add more examples ? for example how do we specify sources? if I have a repo uri how do i search that specific repo ? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7387ab78-ea68-638b-37fa-e3e0b567bd34
* Version Independent ID: 2050c175-26f2-bd31-174d-84661f7ab845
* Content: [NuGet CLI list command](https://docs.microsoft.com/en-us/nuget/reference/cli-reference/cli-ref-list#feedback)
* Content Source: [docs/reference/cli-reference/cli-ref-list.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/master/docs/reference/cli-reference/cli-ref-list.md)
* Product: **nuget**
* GitHub Login: @karann-msft
* Microsoft Alias: **karann**

**Comment by Mortens4444** [comment]
With the default setting NuGet will use %AppData%\NuGet\NuGet.Config. In that file, you can find <packageSources> element. These package source keys can be provided to this command: nuget list -Source "My Artifactory Server"

**Comment by dkymlicka** [comment]
@twopieman, try:
nuget.exe list couchbase -AllVersions -Source "https://your-nuget-feed-url-goes-here"
