### ISSUE TITLE
PackageReference requires all sources to be available

### ISSUE THREAD

**Issue by nkolev92** [NuGet/docs.microsoft.com-nuget#1716]
See https://github.com/NuGet/Home/issues/5035 and lots of related issues. 

I could not find a specific doc documenting this right now.

**Comment by karann-msft** [comment]
@nkolev92 - what exactly should we document here? 'nuget does not work offline' ?

**Comment by nkolev92** [comment]
NuGet requires all sources to be available in order to have a deterministic resolution.

**Comment by karann-msft** [comment]
@nkolev92 - can you please help with a PR :)

**Comment by nkolev92** [comment]
Can you help deciding where? 

https://github.com/NuGet/docs.microsoft.com-nuget/blob/master/docs/consume-packages/Package-References-in-Project-Files.md maybe?

**Comment by nkolev92** [comment]
PR out https://github.com/NuGet/docs.microsoft.com-nuget/pull/1764
