### ISSUE TITLE
The targets docs need to call out the msbuild switches for repeatable build

### ISSUE THREAD

**Issue by nkolev92** [NuGet/docs.microsoft.com-nuget#1717]
Specifically https://docs.microsoft.com/en-us/nuget/reference/msbuild-targets and https://docs.microsoft.com/en-us/nuget/consume-packages/package-references-in-project-files need to mention RestoreForceReevaluate and related. https://github.com/NuGet/Home/wiki/Enable-repeatable-package-restore-using-lock-file#restore-command-line-options

**Comment by karann-msft** [comment]
@nkolev92 - can u help us with a PR ;)

**Comment by karann-msft** [comment]
Fixed in https://github.com/NuGet/docs.microsoft.com-nuget/pull/1738
