### ISSUE TITLE
SymbolPackageFormat

### ISSUE THREAD

**Issue by weitzhandler** [NuGet/docs.microsoft.com-nuget#1722]
Hi,
What's the difference between what's explain in this page and what's explained [here](https://devblogs.microsoft.com/nuget/improved-package-debugging-experience-with-the-nuget-org-symbol-server)?

I find it difficult to understand whether the `snupkg` symbol package format is the newer one.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 98435fc3-0e6f-91e8-b2ba-5329fffd193b
* Version Independent ID: ea0fe9fc-d171-8ddf-426d-a7ec3a232445
* Content: [How to create NuGet symbol packages](https://docs.microsoft.com/en-us/nuget/create-packages/symbol-packages)
* Content Source: [docs/create-packages/Symbol-Packages.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/master/docs/create-packages/Symbol-Packages.md)
* Product: **nuget**
* GitHub Login: @karann-msft
* Microsoft Alias: **karann**

**Comment by loic-sharma** [comment]
Hello! To answer your question, you should use the `.snupkg` format if you can. There's a little note on the documentation that you linked:

> The new recommended format for symbol packages is .snupkg. See [Creating symbol packages (.snupkg)](https://docs.microsoft.com/en-us/nuget/create-packages/symbol-packages-snupkg).
> .symbols.nupkg is still supported but only for compatibility reasons.

It seems that this note is commonly missed. Is it possible to make it more eye catching? @karann-msft @Mikejo5000 Any suggestions?

In any case, I've opened a change to make it harder to accidentally find the legacy symbol documentation: https://github.com/NuGet/docs.microsoft.com-nuget/pull/1724.

**Comment by weitzhandler** [comment]
My bad. I guess I went right to the topic and missed it.
I guess this issue can be closed. Sorry and thanks.

**Comment by loic-sharma** [comment]
No worries! You're not the first person to make that mistake, it seems that our docs should be clearer

**Comment by quasarea** [comment]
Is this still a case with sourcelink and lack of support for snupkg in azure devops?

**Comment by loic-sharma** [comment]
Hello, Azure Artifacts does not support .snupkg symbol packages yet. They recommend pushing symbols using the `PublishSymbols@2` task. See: https://developercommunity.visualstudio.com/comments/1247260/view.html
