### ISSUE TITLE
Documentation does not mention feature availability

### ISSUE THREAD

**Issue by SamuelDebruyn** [NuGet/docs.microsoft.com-nuget#1728]
This feature is not available on macOS but the documentation doesn't mention that.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6a154e5f-436d-6297-ec05-4d134a2404f9
* Version Independent ID: 1c782e82-db9a-bf77-05ef-cd49374aee36
* Content: [Migrating from package.config to PackageReference formats](https://docs.microsoft.com/en-us/nuget/consume-packages/migrate-packages-config-to-package-reference#feedback)
* Content Source: [docs/consume-packages/migrate-packages-config-to-package-reference.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/master/docs/consume-packages/migrate-packages-config-to-package-reference.md)
* Product: **nuget**
* GitHub Login: @karann-msft
* Microsoft Alias: **karann**

**Comment by nkolev92** [comment]
@SamuelDebruyn 

The first sentence of the page says: 

```
Visual Studio 2017 Version 15.7 and later supports migrating a project from the packages.config management format to the PackageReference format.
```

It's referring to Visual Studio, Visual Studio for Mac is called out specifically when applicable.

**Comment by karann-msft** [comment]
@SamuelDebruyn please feel free to reopen if you feel this is not resolved.
