### ISSUE TITLE
Document the force switches for msbuild and nuget.exe restore

### ISSUE THREAD

**Issue by nkolev92** [NuGet/docs.microsoft.com-nuget#1729]
See https://github.com/NuGet/Home/issues/7198#issuecomment-539666208

**Comment by karann-msft** [comment]
@nkolev92 - can u help us out with a PR :)

**Comment by nkolev92** [comment]
There's a PR already, but I guess you saw that by now :D

**Comment by karann-msft** [comment]
fixed in https://github.com/NuGet/docs.microsoft.com-nuget/pull/1730
