### ISSUE TITLE
Customer Comment on API/NuGet.exe Credential Providers

### ISSUE THREAD

**Issue by kraigb** [NuGet/docs.microsoft.com-nuget#173]
See https://docs.microsoft.com/en-us/nuget/api/nuget-exe-credential-providers#comments-container. Comment claims the content isn't accurate. Needs to be checked and updated.

**Comment by xavierdecoster** [comment]
Perhaps a section on _How to debug your credential provider?_ would be useful?

The comment looks like a support request to me, which should be channeled through the nuget.org support request form instead. The debugging section could provide some self-diagnostics checks (e.g. assert nuget.exe version is v3.3 or higher, adding debug messages to stdout, ...) and mention that support requests should go through the form at https://www.nuget.org/policies/Contact.

**Comment by alpaix** [comment]
There's no good diagnostics for discovering and running custom credential providers.
Filed new issue NuGet/Home#4598 to add relevant logging.

In addition to that I'd suggest following steps for the new _How to debug.._ section:
- Run nuget.exe with `-verbosity detailed` and inspect output.
- Attach debugger on startup with this code snippet;
```cs
    while (!Debugger.IsAttached)
    {
        System.Threading.Thread.Sleep(100);
    }
    Debugger.Break();
```

**Comment by kraigb** [comment]
Addressed with https://github.com/NuGet/docs.microsoft.com-nuget/pull/608
