### ISSUE TITLE
Restore not pulling from source declared in global NuGet.config when the same exists in solution-based nuget.config

### ISSUE THREAD

**Issue by mdzeko** [NuGet/docs.microsoft.com-nuget#1731]
I have the same package source (URL) defined in both global `%%apdata%%\NuGet\NuGet.config`, and in local solution-based `nuget.config`. Sources are listed under different names. 

This is neccessary because the source requires authentication, so for our build server to be able to do restore, it needs local nuget.config source without credentials which are then injected in the build pipeline.
Developers, howerever, cannot use this local source and need to set their own global source with their auth credentials in order to restore. At least in theory. But this doesn't work. Packages restore results with "**NU1100** - **Unable to resolve...**".

Note: all sources (global and local) are listed in VisualStudio under "package source:" and browsing works as expected using authenticated source name.

### Steps to reproduce

1. Add package source to solution based nuget.config that requires authentication, but without auth parameters.
2. Add the same package source in global `%%apdata%%\NuGet\NuGet.config` with correct auth parameters (under different name)
3. Do a "Clear All NuGet Cache(s)" in NPM settings
4. Run "Restore NuGet packages" on the solution

### Expected beahvior
NPM is able to restore packages using globally defined source with correct auth

### Actual behavior
NPM is not able to restore packages and ends up with "NU1100 - Unable to resolve..."

**Comment by karann-msft** [comment]
Issue moved to [NuGet/Home #8700](https://github.com/NuGet/Home/issues/8700) via [**ZenHub**](https://www.zenhub.com/)
