### ISSUE TITLE
Example of adding a lower bound needed

### ISSUE THREAD

**Issue by nathanjwtx** [NuGet/docs.microsoft.com-nuget#1745]
[Enter feedback here]
An example of how to do this, particularly on dotnet core 3.0, would be very useful.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 520cf107-0d2e-f014-1420-a704ab761424
* Version Independent ID: 7f25b7e4-59d1-e79b-469b-950e3281c859
* Content: [NuGet Warning NU1604](https://docs.microsoft.com/en-us/nuget/reference/errors-and-warnings/nu1604)
* Content Source: [docs/reference/errors-and-warnings/NU1604.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/master/docs/reference/errors-and-warnings/NU1604.md)
* Product: **nuget**
* GitHub Login: @zhili1208
* Microsoft Alias: **lzhi**

**Comment by karann-msft** [comment]
@rrelyea - can you please help with this.
