### ISSUE TITLE
We have an example nuspec.XSD in document which doesn't exist in our code  

### ISSUE THREAD

**Issue by heng-liu** [NuGet/docs.microsoft.com-nuget#1749]
In our [document](https://docs.microsoft.com/en-us/nuget/reference/nuspec#repository), we have "http://schemas.microsoft.com/packaging/2016/06/nuspec.xsd" as the example nuspec.xsd file.

But it's not in our SchemaVersion list https://github.com/NuGet/NuGet.Client/blob/dev/src/NuGet.Core/NuGet.Packaging/PackageCreation/Authoring/ManifestSchemaUtility.cs#L23-L50

It might mislead others to use that nuspec.xsd, which will cause an error msg as following when running nuget pack command. 
`The schema version of 'Package' is incompatible with version 5.3.0.4 of NuGet. Please upgrade NuGet to the latest version from http://go.microsoft.com/fwlink/?LinkId=213942.`

**Comment by karann-msft** [comment]
@heng-liu - can you help us with a PR for this :)

**Comment by heng-liu** [comment]
Sure~
