### ISSUE TITLE
PackageIcon doesn't work in VS yet

### ISSUE THREAD

**Issue by ygoe** [NuGet/docs.microsoft.com-nuget#1755]
I built my package with VS 2017 15.9.17 ('dotnet build') today and saw the PackageIconUrl deprecation warning. So I changed my .csproj file to use PackageIcon instead and placed the PNG image file in the project root directory. It is included in the .nupkg file and the .nuspec file in it contains that link with the file name (no path). Looks good. But Visual Studio won't show that icon anymore. Using a local directory as package source. So the docs should probably also tell me that I can only use this with an unspecified newer version of Visual Studio. Reverting my commit now and staying with PackageIconUrl.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 099102e8-c320-ef50-6821-57519684dc98
* Version Independent ID: 1523dac4-419d-613d-2497-4062f9efd358
* Content: [NuGet pack and restore as MSBuild targets](https://docs.microsoft.com/en-us/nuget/reference/msbuild-targets#packageiconurl)
* Content Source: [docs/reference/msbuild-targets.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/master/docs/reference/msbuild-targets.md)
* Product: **nuget**
* GitHub Login: @karann-msft
* Microsoft Alias: **karann**

**Comment by karann-msft** [comment]
@ygoe - VS doesn't yet support showing self-contained icons from offline or folder based feeds. We are working on releasing this in Visual Studio 16.5. If you publish packages to nuget.org, the self-contained icon scenario is fully supported since nuget.org extracts, hosts, and serves these icons when browsing packages on nuget.org.

**Comment by Mike-EEE** [comment]
So odd and frustrating that you are providing warnings for (and documenting!) "features" that are not even fully supported yet.

LICENSE is another great example:

https://github.com/NuGet/Home/issues/7509#issuecomment-446296042

**Comment by rrelyea** [comment]
Yes, @Mike-EEE, evolving the package format, changing the clients and changing the protocol and the server is tricky work to plan, execute and coordinate.
We're learning each time we do it, and appreciate your constructive feedback.

As we plan each new instance of these coordinated features, the teams involved are taking these lessons to heart. Sorry for your frustration, as we get better at this.

**Comment by jasonycw** [comment]
@karann-msft VS 16.5.0 is out and seems `PackageIcon` is not supported yet?

**Comment by karann-msft** [comment]
@jasinycw It is fully supported in 16.5. Have you tried it out and found something not working as expected?
