### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by traderhut** [NuGet/docs.microsoft.com-nuget#1757]
I have a project that works in Visual Studio (builds fine), but the packages won't restore using dotnet restore solution.sln  Apparently, this has been a known bug since 2017 (using VS 2017), so WTF why isn't this a RED HOT problem with all hands on deck to fix it!  This means that you can NOT do continuous integration, or even use a build server *at all* I have ZERO idea how to restore the packages, just doesn't work.  (this is with the &lt;/PackageReference&gt; in the .csproj file.. Would *really* like to fetch it for me so it builds *without* errors... Even if it builds in VS, you *still* can't get it to build from the command line...

So calling BS on this documentation...

**Comment by karann-msft** [comment]
@traderhut - can you provide a link to the "known bug" you talk about?

**Comment by grimreaper38uk** [comment]
Same issue with VS2019.  I've got access denied trying to restore packages, and NO documentation ANYWHERE on how to configure the damn path.
Lots of BS.

**Comment by karann-msft** [comment]
@grimreaper38uk - what path are you talking about? It is very difficult to provide help without knowing more about your scenario, error code, etc. Feel free to open an issue on NuGet/Home repo - https://github.com/nuget/home/issues if you feel there is a bug in the product or experience.
