### ISSUE TITLE
Need more direction on solving this error

### ISSUE THREAD

**Issue by hfloyd** [NuGet/docs.microsoft.com-nuget#1768]
I got this error for the first time attempting to build a project in VS2019. (I have successfully built it without errors in VS2017.)
The supposedly missing file path shown in the error is my solution directory, not a specific file.
When clicking on the error, it takes me to these lines:

  &lt;PackTask PackItem="$(PackProjectInputFile)"
              PackageFiles="@(_PackageFiles)"
              PackageFilesToExclude="@(_PackageFilesToExclude)"
...

The only change I had made to the Package Properties was updating from a PackageLicenseUrl to a file (path: "..\..\LICENSE.md" in the UI 'Package" tab on the Project Properties) (as per: https://github.com/NuGet/Home/wiki/Packaging-License-within-the-nupkg) I noticed that in the .csproj file, the XML says:
&lt;PackageLicenseFile&gt;LICENSE.md&lt;/PackageLicenseFile&gt;

Which makes me think that perhaps the packager is looking for LICENSE.md in the solution directory, rather than two directories above that. However, reverting those license changes doesn't stop the same error from appearing. 

It would be helpful if there were some more direction about what list of files is being used by the packager.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 377b80da-ae89-7e89-1674-a18e0c49e263
* Version Independent ID: 12eee46f-c507-64dd-3f3f-2ad59829e5e6
* Content: [NuGet Error NU5019](https://docs.microsoft.com/en-us/nuget/reference/errors-and-warnings/nu5019?f1url=https%3A%2F%2Fmsdn.microsoft.com%2Fquery%2Fdev16.query%3FappId%3DDev16IDEF1%26l%3DEN-US%26k%3Dk(NU5019)%26rd%3Dtrue)
* Content Source: [docs/reference/errors-and-warnings/NU5019.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/master/docs/reference/errors-and-warnings/NU5019.md)
* Product: **nuget**
* GitHub Login: @mishra14
* Microsoft Alias: **karann**

**Comment by hfloyd** [comment]
I figured something else out - closer to the bottom of my csproj file, there was a new section that seems to have been added when I changed to a license file - 

 <ItemGroup>
    <None Include="..\..\">
      <Pack>True</Pack>
      <PackagePath></PackagePath>
    </None>
  </ItemGroup>

In addition to one added for the actual file:

 <ItemGroup>
    <None Include="..\..\LICENSE.md">
      <Pack>True</Pack>
      <PackagePath></PackagePath>
    </None>
  </ItemGroup>

When I deleted that first one, and updated the package properties to use the license file again, the build worked.

So, I suppose one issue is that VS2019 adds an unnecessary reference to the solution directory, but in terms of this documentation, I'd suggest adding information that one should look at the "<ItemGroup>"s near the bottom of their .csproj file to resolve the error.

**Comment by hfloyd** [comment]
It seems the comment form on the documentation page threw out the XML snippets I added.

Here they are (hopefully preserved by Markdown...)

XML causing error:

```
 <ItemGroup>
    <None Include="..\..\">
      <Pack>True</Pack>
      <PackagePath></PackagePath>
    </None>
  </ItemGroup>
```

XML referencing license file:

```
 <ItemGroup>
    <None Include="..\..\LICENSE.md">
      <Pack>True</Pack>
      <PackagePath></PackagePath>
    </None>
  </ItemGroup>
```

**Comment by karann-msft** [comment]
@hfloyd, this error can happen for any missing file and is not unique to license or icon files. Also, the lines causing the issue aren't always going to be at the bottom of the nuspec.

Next, take a look at the [docs on how to include a license](https://docs.microsoft.com/en-us/nuget/reference/msbuild-targets#packing-a-license-expression-or-a-license-file). I believe you got into this state after you hand-edited the csproj. 

I am assuming you are trying to move away from PackageLicenseUrl and use the new self-contained license using PackageLicenseExpression or PackageLicenseFile. If you use the project properties UI to select a license file, use the file selector and VS will take care of the rest. If you hand-edit the csproj, follow the docs. I believe

**Comment by hfloyd** [comment]
Hi @karann-msft 

Yes, I recognize the error could occur for any missing file. It just wasn't as clear what file was affected, which is why I originally posted. Some mention could be made in the docs to check the files listed in the *.csproj file - since that is a place to look.

Actually, I used the VS UI to change the license info (using the "browse..." button to pick the file), and it looked correct in the Packager UI - however, VS2019 added an unnecessary reference to the solution directory, in addition to the actual license.md file path, to the .csproj. I was only able to correct that by directly editing the .csproj file and deleting the erroneous solution directory reference.

_Removing this from .csproj manually resolved the error:_
```
<ItemGroup>
    <None Include="..\..\">
      <Pack>True</Pack>
      <PackagePath></PackagePath>
    </None>
  </ItemGroup>
```

I realize that this second part is actually more a bug of the VS packager UI - and not of NuGet Docs.
