### ISSUE TITLE
align content in "msbuild-targets" for pack with the pack spec

### ISSUE THREAD

**Issue by rohit21agrawal** [NuGet/docs.microsoft.com-nuget#177]
the content in  https://docs.microsoft.com/en-us/nuget/schema/msbuild-targets is outdated , and needs to be aligned with the updated version of spec : https://github.com/NuGet/Home/wiki/Adding-nuget-pack-as-a-msbuild-target

**Comment by kraigb** [comment]
Rohit, can you review the changes to this topic in my branch before I do a PR? https://github.com/NuGet/docs.microsoft.com-nuget/blob/kraigb/docs/Schema/msbuild-targets.md

Note that I also updated the restore target section according to https://github.com/NuGet/Home/wiki/%5BSpec%5D-MSBuild-restore-target, and also checked https://github.com/NuGet/Home/wiki/PackageTargetFallback-(new-design-for-Imports).

**Comment by rohit21agrawal** [comment]
@kraigb have made some comments on suggested changes.

**Comment by rohit21agrawal** [comment]
@emgarten might want to read through the restore documentation

**Comment by kraigb** [comment]
In the meantime, I'll do the PR to update the pack section, and can update restore as needed with a new PR.

**Comment by kraigb** [comment]
Content should be aligned now. If you see anything, just edit the file and do a PR.
