### ISSUE TITLE
Documentation is unclear WRT native NuGet packages

### ISSUE THREAD

**Issue by TheRealZonaP** [NuGet/docs.microsoft.com-nuget#1773]
I find the use of ".NET" throughout this whole guide very confusing as it implies that NuGet is only for deployment of managed code.  It is not clear how to create and consume packages for native SDKs.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bd0c2ac7-8837-d4fd-955b-6a5b261592f3
* Version Independent ID: 4c62f271-70ea-8537-f670-b59bb702c4c0
* Content: [What is NuGet and what does it do?](https://docs.microsoft.com/en-us/nuget/what-is-nuget)
* Content Source: [docs/what-is-nuget.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/master/docs/what-is-nuget.md)
* Product: **nuget**
* GitHub Login: @karann-msft
* Microsoft Alias: **karann**

**Comment by karann-msft** [comment]
@TheRealZonaP - NuGet does not have a first class experience for creating native packages. Please take a look at this doc for more details - https://docs.microsoft.com/en-us/nuget/guides/native-packages

**Comment by karann-msft** [comment]
dupe of https://github.com/NuGet/docs.microsoft.com-nuget/issues/1774
