### ISSUE TITLE
.NET Framework defualt to PackageReference

### ISSUE THREAD

**Issue by ChrisMaddock** [NuGet/docs.microsoft.com-nuget#1775]
This page states that:

> .NET Framework projects support PackageReference, but currently default to packages.config. 

That default doesn't appear to be true in VS 15.9.17.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ff707668-94d6-25a5-9139-b18cc1b6b446
* Version Independent ID: 494847b9-4894-0beb-7ffa-39a2359999fa
* Content: [NuGet PackageReference format (package references in project files)](https://docs.microsoft.com/en-us/nuget/consume-packages/package-references-in-project-files)
* Content Source: [docs/consume-packages/Package-References-in-Project-Files.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/master/docs/consume-packages/Package-References-in-Project-Files.md)
* Product: **nuget**
* GitHub Login: @karann-msft
* Microsoft Alias: **karann**

**Comment by karann-msft** [comment]
@ChrisMaddock - can you elaborate? Are you saying it defaults to something else in 15.9.17?

**Comment by ChrisMaddock** [comment]
Yes, sorry. The doc says the default for .NET framework projects is packages.config. 

In my version of VS (15.9.7) this appears to be incorrect. It defaults instead to PackageReference. I don’t know when that might have changed, sorry.

**Comment by karann-msft** [comment]
The doc is indeed accurate. 

Check your setting to see if you have selected the default to be PackageReference.

You can do that by going to Tools>Options>NuGet Package Manager>General

![image](https://user-images.githubusercontent.com/16904420/69101409-65194500-0a14-11ea-9b4d-58c4f595d9e3.png)

My hunch is your default format is "PackageReference" and you have "Allow format selection...." unchecked.

**Comment by karann-msft** [comment]
@ChrisMaddock - I hope that helped. Please create an issue on the [Home ](https://github.com/NuGet/Home/issues)repo if you have product feedback.

**Comment by ChrisMaddock** [comment]
Hey @karann-msft - sorry it's taken me a while to get back to this. You were spot on - no doc change needed. Thanks! 😄
