### ISSUE TITLE
PDF edition of this page refers to a local file

### ISSUE THREAD

**Issue by spchamp** [NuGet/docs.microsoft.com-nuget#1776]
Hello,

I was reading through the PDF edition of the NuGet documentation, today, when I noticed the following reference:

> For information on dependency resolution, see {Dependency resolution with PackageReference}

In the PDF edition of this page, the bracketed section (a link in the PDF) refers to a local filename `file:///T:/iyhd/concepts/Dependency-Resolution.html#dependency-resolution-with-packagereference` rather than any other section in the same PDF. Perhaps the reference may represent something of an artifact from the PDF publishing process? As such, I thought it might bear mention for purpose of linting.

The local file reference, as such, occurs on PDF p. 121 of 750,  in a recent edition of the PDF imprint of the NuGet documentation

Of course, in the web based edition of the .NET NuGet documentation - as at the web page published from the source document, here - the reference would refer to the content as available at https://docs.microsoft.com/en-us/nuget/concepts/dependency-resolution 

tbt I'm not sure what syntax a PDF file may use, for internal hyperlinks. 

Personally, I think it's some useful documentation. I believe that the referred page may be particularly helpful in understanding how NuGet fits in beside the SDK resolvers in MSBuild.

[ Plug ]
I look forward to reading more about this API and its applications - working with Mono 6 and the MonoDevelop IDE tbt, respectively with Mono 6 under pkgsrc in Linux and FreeBSD environments, and with MonoDevelop in its distribution for Debian 10. Of course, NuGet may find a  relevance for distribution management with Mono and in shared Mono/.NET environments, under OS distributions' respective package management systems and in BSD-like port systems furthermore, as well as in singular projects, and on other platforms - so much to read about.
[/ Plug]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 92399c34-8136-b3bf-4754-5f0781a99bad
* Version Independent ID: 459b7ff8-6d5d-2dcb-fd78-9f52f56ae9b0
* Content: [Create a NuGet package using the dotnet CLI](https://docs.microsoft.com/en-us/nuget/create-packages/creating-a-package-dotnet-cli)
* Content Source: [docs/create-packages/creating-a-package-dotnet-cli.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/master/docs/create-packages/creating-a-package-dotnet-cli.md)
* Product: **nuget**
* GitHub Login: @karann-msft
* Microsoft Alias: **karann**

**Comment by spchamp** [comment]
The bracketed section, denoted above - in perhaps a more HTML-friendly syntax: 

> For information on dependency resolution, {see Dependency resolution with PackageReference}

This local file reference, as such, occurs on PDF p. 121 of 750,  in a recent edition of the PDF imprint of the NuGet documentation

**Comment by karann-msft** [comment]
@Mikejo5000 - how should we route this issue? It seems like a bug with the docs platform.

**Comment by Mikejo5000** [comment]
There are some known issues with certain links in the PDFs, but this seems like a fairly standard link, so I'm not sure about it. @ghogen Do you have any thoughts about this?

**Comment by Mikejo5000** [comment]
@karann-msft Gordon is talking to the folks who own PDF generation. Sounds like a bug.

**Comment by karann-msft** [comment]
Thanks @Mikejo5000. Linking to the internal ticket tracking this bug - https://ceapex.visualstudio.com/Engineering/_workitems/edit/141381

**Comment by Mikejo5000** [comment]
OK, I think we should close this since it's external.

**Comment by karann-msft** [comment]
@spchamp - thanks for reporting this. It seems to be an issue with the docs platform and not specific to NuGet docs. I am closing this issue as an external. I will reply to this issue once the bug has been fixed.
