### ISSUE TITLE
Definition of Leading

### ISSUE THREAD

**Issue by MatthewSteeples** [NuGet/docs.microsoft.com-nuget#1777]
The docs state "It will lead you to the package and its deprecation information...". It indicates that there is a package that's deprecated, but does not lead you to it. If you have a large number of packages like we do then you're required to do a lot of scrolling to find the yellow icon next to the version number

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a01e821e-fdaa-ddeb-584c-e3d1af0ce964
* Version Independent ID: f919df6a-2e9e-d289-4628-f43d3330a9fe
* Content: [Deprecating packages on nuget.org](https://docs.microsoft.com/en-us/nuget/nuget-org/deprecate-packages)
* Content Source: [docs/nuget-org/Deprecate-packages.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/master/docs/nuget-org/Deprecate-packages.md)
* Product: **nuget**
* GitHub Login: @anangaur
* Microsoft Alias: **anangaur**

**Comment by karann-msft** [comment]
@MatthewSteeples - the doc is trying to convey that the yellow exclamation mark is essentially leading you to the packages that have a problem. Your feedback seems to be less about the documentation and more about the feature. Is that accurate?

**Comment by MatthewSteeples** [comment]
I'm not sure. To me it would be "leading" if it scrolled to the right item, or maybe filtered. As it stands, we have about 130 NuGet packages and the one that was deprecated was about half way down.

I know it sounds picky, but I'd suggest a word like "highlight" instead of leading.

**Comment by MatthewSteeples** [comment]
To be clear, the way I read this I thought it was talking about the yellow triangle next to "Installed", not the yellow triangle next to the package name

**Comment by MatthewSteeples** [comment]
Thanks
