### ISSUE TITLE
Document how to run NuGet concurrently

### ISSUE THREAD

**Issue by nkolev92** [NuGet/docs.microsoft.com-nuget#1779]
Motivation from https://github.com/NuGet/Home/issues/7380

Specifically, nuget operations will run concurrently as long as they are sharing the same temp folder. 

Any overlaps among projects can still cause issues though.

**Comment by karann-msft** [comment]
@nkolev92 - can you please help us with a PR.

**Comment by mostynb** [comment]
> Any overlaps among projects can still cause issues though.

I wonder if you could explain this part a bit- what kind of overlaps cause trouble?
