### ISSUE TITLE
PackageOutputPath is required

### ISSUE THREAD

**Issue by kirschem** [NuGet/docs.microsoft.com-nuget#1789]
I'm using a non SDK-Project, targetting .NET 4.5.2 with VS2019. With the properties in `<PropertyGroup>` listed in this article, I'm getting an error, stating that the variable PackageOutputPath is required.
After Adding
`<PackageOutputPath>bin\Package</PackageOutputPath>`
inside the `<PropertyGroup>` it works. The article should be updated.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 31da7408-981b-cc54-1791-ca39dbdbc091
* Version Independent ID: 2060c9e8-7f2e-5da1-ee19-d196f38339fe
* Content: [Create a NuGet package using MSBuild](https://docs.microsoft.com/en-us/nuget/create-packages/creating-a-package-msbuild)
* Content Source: [docs/create-packages/creating-a-package-msbuild.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/master/docs/create-packages/creating-a-package-msbuild.md)
* Product: **nuget**
* GitHub Login: @karann-msft
* Microsoft Alias: **karann**

**Comment by karann-msft** [comment]
@kirschem - thanks for catching that! It would be awesome if you could help us with a PR. Just click on the edit button on this page 
![image](https://user-images.githubusercontent.com/16904420/69457662-6e5f2600-0d22-11ea-803a-4bf2314d869f.png)

**Comment by kirschem** [comment]
I don't know yet if specifying `PackageOutputPath` is only needed when used in conjunction with `<GeneratePackageOnBuild>true</GeneratePackageOnBuild>` (which is what I did). Gotta test when there is time.

**Comment by karann-msft** [comment]
@nkolev92 - can you please help with this.

**Comment by kodigo35** [comment]
You must add the PackageOutputPath in your csproj

`<PropertyGroup` Condition=" '$(Configuration)|$(Platform)' == 'Debug|AnyCPU' ">
        <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
	`<PackageOutputPath>bin\debug\</PackageOutputPath>

**Comment by nkolev92** [comment]
It's only required non SDK based projects as the customer states.

We should maybe consider a product change and add a default in the old csproj as well.

**Comment by nkolev92** [comment]
Related: 

https://github.com/NuGet/Home/issues/9231

I think the product should add a default.
