### ISSUE TITLE
Documentation of nuget restore does not list options for lock files

### ISSUE THREAD

**Issue by KalleOlaviNiemitalo** [NuGet/docs.microsoft.com-nuget#1791]
These options are shown by `nuget restore -help` of NuGet 5.3.1 but they are not listed on the page:

* `-UseLockFile`
* `-LockedMode`
* `-LockFilePath`
* `-ForceEvaluate`

Please add these options to the page.  Perhaps also say which version of NuGet is the first one that supports them; I guess that would be 4.9.0.

In addition, it would be useful to list these options in &lt;https://docs.microsoft.com/en-us/nuget/consume-packages/package-references-in-project-files#lock-file-extensibility&gt; as well. Currently, that topic lists options for `dotnet restore` and properties for MSBuild, but not options for `nuget restore`.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 78b5e2ae-0676-040b-1870-14e885fbe228
* Version Independent ID: af4e9bfc-b2bc-96f5-d1f0-009353fb061f
* Content: [NuGet CLI restore command](https://docs.microsoft.com/en-us/nuget/reference/cli-reference/cli-ref-restore?source=docs#feedback)
* Content Source: [docs/reference/cli-reference/cli-ref-restore.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/master/docs/reference/cli-reference/cli-ref-restore.md)
* Product: **nuget**
* GitHub Login: @karann-msft
* Microsoft Alias: **karann**

**Comment by karann-msft** [comment]
@anangaur - who can help with this?

**Comment by anangaur** [comment]
You have the right person assigned to it :)

**Comment by anangaur** [comment]
@zivkan can you review the PR, especially which version of nuget.exe its available from?
https://github.com/NuGet/docs.microsoft.com-nuget/pull/1891

**Comment by karann-msft** [comment]
DocsDay - use this PR as the starting point - https://github.com/NuGet/docs.microsoft.com-nuget/pull/1891
