### ISSUE TITLE
Invalid xsd reference

### ISSUE THREAD

**Issue by CeciAc** [NuGet/docs.microsoft.com-nuget#1792]
@Q-Tec90 commented on [Tue Nov 26 2019](https://github.com/NuGet/docs.microsoft.com-nuget.de-de/issues/17)

Hello,

the xsd reference in the example is invalid. 
Could you please fix that.

---

@srvbpigh commented on [Tue Nov 26 2019](https://github.com/NuGet/docs.microsoft.com-nuget.de-de/issues/17#issuecomment-558635008)

Hello, @Q-Tec90
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.

Kind regards,
Microsoft DOCS International Team

**Comment by karann-msft** [comment]
@CeciAc - what doc was this comment on?

**Comment by karann-msft** [comment]
Closing since there has been no response.
