### ISSUE TITLE
Presence of <trustedSigners/> implies signatureValidationMode=require?

### ISSUE THREAD

**Issue by mahilleb-msft** [NuGet/docs.microsoft.com-nuget#1794]
Can you confirm / document if true whether the presence of &lt;trustedSigners/&gt; in NuGet.config implicitly sets signatureValidationMode to require?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ed8354aa-ccf0-ff9a-dbc1-f78f9a4de84f
* Version Independent ID: a0fa663b-fee8-e831-133d-ad99cdacd7d7
* Content: [Manage package trust boundaries](https://docs.microsoft.com/en-us/nuget/consume-packages/installing-signed-packages)
* Content Source: [docs/consume-packages/installing-signed-packages.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/master/docs/consume-packages/installing-signed-packages.md)
* Product: **nuget**
* GitHub Login: @karann-msft
* Microsoft Alias: **karann**

**Comment by karann-msft** [comment]
@mahilleb-msft - presence of <trustedSigners/> in NuGet.config does NOT implicitly set signatureValidationMode to require. I don't think we lead the reader to believe that it is.

**Comment by mahilleb-msft** [comment]
@karann-msft thanks for your answer. I'll revisit my tests related to this.
