### ISSUE TITLE
Misleading text about explicit assembly references

### ISSUE THREAD

**Issue by tomkuijsten** [NuGet/docs.microsoft.com-nuget#180]
I read the [Explicit assembly references](https://docs.microsoft.com/en-us/nuget/schema/nuspec#explicit-assembly-references) documentation and I found this last paragraph a bit misleading:

`
Similarly, explicit references can be used for unit test frameworks, such as XUnit, which needs its tools assemblies located next to the runtime assemblies, but does not need them included as project references.
`

If I read this, I expect the tools assemblies located next to the runtime assemblies. However, if I look at the output folder (the only place I would search for the runtime assemblies), these explicit assembly references are not there. I understand that this is by design, the text is just not that clear about it.

**Comment by karann-msft** [comment]
We encourage and ❤️ PRs. Please open a PR and recommend changes that would make the text more clear in your opinion.

**Comment by tomkuijsten** [comment]
I understand that you love PRs, but that can't be the only way to solve an issue right? I'm, as everyone else, a busy man. I do help by pointing out problems in code and documentation through GitHub, create repro scenario's and share them with you. When I don't have the time to fix your errors, it won't be solved?

Don't get me wrong, I love the way that you open sourced a lot, but I expected a fix for this issue... or at least the reason why it won't be fixed.

**Comment by karann-msft** [comment]
@tomkuijsten I wouldn't categorize matters of opinion as errors :-)
I was hoping for a PR from you so that I can see from your perspective what phrasing would make this more clear for you. 

You need to read that para in the context of the one just before it:

> Explicit reference are typically used for design-time only assemblies. When using Code Contracts, for example, contract assemblies need to be next to the runtime assemblies that they augment so that Visual Studio can find them, but the contract assemblies need not be referenced by the project or copied into the project's bin folder.+
> 
> Similarly, explicit references can be used for unit test frameworks, such as XUnit, which needs its tools assemblies located next to the runtime assemblies, but does not need them included as project references.

So above, we do call out that similar to code contracts, reference assemblies will not be copied to the project's bin folder. VS expects them to be located next to the runtime assemblies IF they were not explicitly referenced.

**Comment by tomkuijsten** [comment]
Thanks for re-opening and I do agree with your point of view. I don't think it needs to be updated. Was this line:

```or copied into the project's bin folder```

always there, or did you add that recently?

**Comment by kraigb** [comment]
That line was always there, though I edited it a little when we migrated the docs from docs.nuget.org to docs.microsoft.com. Maybe that's why you noticed it. In any case, I'm closing this issue given that no changes are needed.
