### ISSUE TITLE
Missing information about GeneratePathProperty

### ISSUE THREAD

**Issue by ltrzesniewski** [NuGet/docs.microsoft.com-nuget#1802]
The `GeneratePathProperty` metadata item is not documented, see https://github.com/NuGet/NuGet.Client/pull/2271

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ff707668-94d6-25a5-9139-b18cc1b6b446
* Version Independent ID: 494847b9-4894-0beb-7ffa-39a2359999fa
* Content: [NuGet PackageReference format (package references in project files)](https://docs.microsoft.com/en-us/nuget/consume-packages/package-references-in-project-files#feedback)
* Content Source: [docs/consume-packages/Package-References-in-Project-Files.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/master/docs/consume-packages/Package-References-in-Project-Files.md)
* Product: **nuget**
* GitHub Login: @karann-msft
* Microsoft Alias: **karann**

**Comment by karann-msft** [comment]
@rrelyea, @aortiz-msft - can you please help with this :)

**Comment by anangaur** [comment]
It should be documented here: https://docs.microsoft.com/en-us/nuget/reference/msbuild-targets#restore-properties

**Comment by ltrzesniewski** [comment]
@anangaur it's a `PackageReference` metadata item, not a restore property, so I believe it fits better on the page I suggested.

Maybe add a mention to both pages?
