### ISSUE TITLE
Revisit contentFiles dependencies element explanation. 

### ISSUE THREAD

**Issue by nkolev92** [NuGet/docs.microsoft.com-nuget#1806]
See: https://github.com/NuGet/Home/issues/8858

Specifically "content/ ContentFiles are also implicitly excluded in the final package which can't be over-written." is not fully correct.

**Comment by nkolev92** [comment]
Confirmed in https://github.com/NuGet/Home/issues/8858#issuecomment-563468545 that it's not completely correct. 
I think Project -> Package ->Package works, but Project ->Project -> Package doesn't.

**Comment by karann-msft** [comment]
@nkolev92 - please help with a PR.
