### ISSUE TITLE
How to INCLUDE the package files in TFS

### ISSUE THREAD

**Issue by MarkLTX** [NuGet/docs.microsoft.com-nuget#1808]
What if I actually WANT to include the package files in my TFS folders?  I realize I can just add the packages folder to TFS, but will it automatically include new and updated packages?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d965aea9-a6cc-06da-a347-6e8c89458c98
* Version Independent ID: 6775f211-f4b6-6d0c-6f2e-6664b3e9721e
* Content: [NuGet Packages and Source Control](https://docs.microsoft.com/en-us/nuget/consume-packages/packages-and-source-control#feedback)
* Content Source: [docs/consume-packages/Packages-and-Source-Control.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/master/docs/consume-packages/Packages-and-Source-Control.md)
* Product: **nuget**
* GitHub Login: @karann-msft
* Microsoft Alias: **karann**

**Comment by karann-msft** [comment]
just like any source control, any changes you make locally and checkin will be included in your TFS repo. If you restore the latest packages locally and then perform a checkin, then yes it will be included.

**Comment by karann-msft** [comment]
Closing the issue as resolved.
