### ISSUE TITLE
Visual Studio Packages out of Control

### ISSUE THREAD

**Issue by Johnvan** [NuGet/docs.microsoft.com-nuget#1813]
Severity	Code	Description	Project	File	Line	Suppression State
Warning	NU1605	Detected package downgrade: Xamarin.Android.Support.Design from 28.0.0.3 to 28.0.0.1. Reference the package directly from the project to select a different version. 
 Notes.Android -> Xamarin.Forms 4.4.0.991265 -> Xamarin.Android.Support.Design (>= 28.0.0.3) 
 Notes.Android -> Xamarin.Android.Support.Design (>= 28.0.0.1)	Notes.Android	C:\Projects\Notes - 14_12_19\Notes\Notes.Android\Notes.Android.csproj	1	

The above code is repeated 5 times after I updated (as suggested on opening Visual Studio 19) but there are no instructions (from this current page as follows, that do anything to fix it);

Solution
To the project exhibiting the restore error, add a package reference to the higher version of the package.

In the example above, you would add a package reference to Package B version 4.0.0:

  'PackageA' 3.5.0 -> 'PackageB' 3.5.0

  'PackageC' 4.0.0 -> 'PackageD' 4.0.0 -> 'PackageB' 4.0.0

  'PackageB' 4.0.0
 This place is soooo confusing, and I feel have lost the plot for Version control.

John van der Linden
(john.linden@outlook.com)

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0960d68b-f164-4e7e-5cdb-ad70e6f9de89
* Version Independent ID: 82b4d896-1d52-ce2e-c2ff-f76f4308ac56
* Content: [NuGet Warning NU1605](https://docs.microsoft.com/en-au/nuget/reference/errors-and-warnings/nu1605?f1url=https%3A%2F%2Fmsdn.microsoft.com%2Fquery%2Fdev15.query%3FappId%3DDev15IDEF1%26l%3Den-AU%26k%3Dk(NU1605)%26rd%3Dtrue#feedback)
* Content Source: [docs/reference/errors-and-warnings/NU1605.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/master/docs/reference/errors-and-warnings/NU1605.md)
* Product: **nuget**
* GitHub Login: @zhili1208
* Microsoft Alias: **lzhi**

**Comment by karann-msft** [comment]
Not eligible for docs day.

**Comment by toddalbers** [comment]
I am getting the same error message x 3.  One for each of 3 projects in same solution.  I tried the "Solution\Workaround" provided for this issue on this site under [NU1605](https://docs.microsoft.com/en-us/nuget/reference/errors-and-warnings/nu1605).  But, it doesn't resolve the issue for me.  Versioning is a very simple concept that quickly gets very complex.  I feel that I have lost the plot on this also.  Is there possibly some documentation or write-ups that someone can point us to so we can understand this error message better and how understand to resolve it?  Thanks all.  - Todd Albers

**Comment by toddalbers** [comment]
I was able to resolve the issue... to a point.  I don't know that this is the best approach.  It might cause problems.  So, I don't recommend for production critical solutions\projects (at least without a lot of testing) and I recommend doing on a copy\test version first.  But, mine is experimental.  And this seems to have worked.  

I had downloaded from github a solution with multiple projects in it.  I wanted the actual code.  There is one main project which is a class library which is referenced by all the other projects.  The other projects are different examples of how to use the class library.  One of them is Blazor Server project.  Another is Blazor WebAssembly project.  And there are others.  You set each one as start up project to try it.  

I opened the project (.csproj) file for the class library project and also the project (.csproj) files for all the other projects that reference it.  I saw under <PropertyGroup> that the <TargetFramework> in them did not match.  I was going to make them match but wasn't sure which to use as they had different ones.  And that makes sense especially between Blazor Server and Blazor WebAssebly. Blazor Server is released in production version but Blazor WebAssembly is still in preview.  They aren't going target the same framework version right now.

I created a separate new Blazor Server solution and project.  I looked at what value it put in there for <PropertyGroup><TargetFramework>.  I changed the value of <PropertyGroup><TargetFramework> in all of the projects in the downloaded solution to match what showed in the new blank solution\project I created.  Basically, I know that Framework is installed and works if VS 2019 is creating the projects with it.  (Note that I created a blank Blazor SERVER , not webassembly, project here).

It successfully compiles the entire solution now.  And when I set the Blazor Server project as the startup project in the solution, and run it, it works.  However, when I set the start up project to Blazor WebAssembly and run it, it errors out.  Blazor webassembly is still in preview and needs one of the preview target frameworks.  So, that makes sense.  I bet I can copy the downloaded web assembly project, and the target class framework, out over to a new project that I create with VS 2019 (preview) and set the <TargetFramework> settings to match, it would work.  Well, maybe.

As a side note, I don't recommend putting Blazor Server demos in the same solution as Blazor webassembly demos until Blazor webassembly production version is released at least.  And even then I don't know that both Blazor server and Blazor webassembly will be running off the same targetframework right away.

But, this worked for me.  I hope it helps someone.  Change settings at your own risk.  Make sure you have backups first.

**Comment by Johnvan** [comment]
I created a new project and made sure all the packages were up to date before copy pasting the code from the old project. I now also, before starting a new project, I check the package versions and update if necessary. Then do the programming. Once programmed do not update the packages.

**Comment by JonDouglas** [comment]
@Johnvan When I worked on the Xamarin team, we added this helpful error message to tell you exactly what library you needed to install to resolve the issue:

https://github.com/xamarin/AndroidSupportComponents/blob/master/source/buildtasks/support-annotations/VerifyVersionsTask.cs

Is there something we can improve the NuGet docs with today based on your original post & recent update?

@toddalbers 

Based on your feedback in your two reported issues here & https://github.com/NuGet/docs.microsoft.com-nuget/issues/2021 it sounds like what you're after is a more empowering error message for NU1605? I.e. one that tells you more specifically what you're missing version wise & also where you should add it in terms of what project/.csproj? This is similar to what we did in the VerifyVersionsTask I linked to above. I'm not sure how much we'll be able to do on the NuGet side, but we'll definitely want to encourage similar verification tasks to teams that have these issues with higher versions needing to be explicitly referenced.

**Comment by Johnvan** [comment]
Dear Jon Douglas<mailto:notifications@github.com>,
I feel you don’t know what the problem is and how it could be fixed by a bit more documentation of Packages and what and how to use them.

You supplied the link:

https://github.com/xamarin/AndroidSupportComponents/blob/master/source/buildtasks/support-annotations/VerifyVersionsTask.cs
which means nothing to me, but you seem to think that fixes everything.

I created a new project and made sure all the packages were up to date before copy pasting the code from the old project.
I now, before starting a new project, check the package versions and update if necessary.
Then do the programming. Once programmed do not update the packages.

The Packages, if not backward compatible, should be re-named to something else as the original Package is now obsolete.

Just a suggestion.

Kind regards,

John van der Linden
Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by JonDouglas** [comment]
@Johnvan 

> I feel you don’t know what the problem is and how it could be fixed by a bit more documentation of Packages and what and how to use them.

I appreciate the comment. This happens when you have two different versions of the same package. You can easily reproduce this by creating a File -> New Xamarin.Forms project and downgrading or upgrading the Xamarin.Forms version in one of the projects such as the .NET Standard or Android project.

You would see something like this:

```
NU1605: Detected package downgrade: Xamarin.Forms from 4.3.0.947036 to 4.3.0.908675. Reference the package directly from the project to select a different version. 
 App76.Android -> App76 -> Xamarin.Forms (>= 4.3.0.947036) 
 App76.Android -> Xamarin.Forms (>= 4.3.0.908675)
```

In your scenario, you can always post your `.csproj`/`<PackageReferences>` or similar on this thread for us to understand what your project is referencing to understand this warning better & document it further for the use-case. This is a very common scenario with Xamarin given the support libraries & AndroidX libraries are typically only compatible to the same version across the board or else it can lead to runtime crashes if they are mixed with third-party dependencies that require older versions to be used.

This warning is very closely related to [NU1107](https://docs.microsoft.com/en-us/nuget/reference/errors-and-warnings/nu1107). We can choose to document these codes better, empower the error messages such as previous work that was done here: https://github.com/NuGet/NuGet.Client/pull/2336, or a combination of both. I believe we first need to understand your scenario before we can document it better.
