### ISSUE TITLE
How do we pack Universal Windows Class Libraries?

### ISSUE THREAD

**Issue by SuperJMN** [NuGet/docs.microsoft.com-nuget#1814]
I would like to create a NuGet package for my Universal Windows Class Library (UAP10). I don't know if there's a way (for dummies).

I haven't found any good docs describing it. Only this one, but it doesn't mention UWP.
https://github.com/NuGet/docs.microsoft.com-nuget/blob/master/docs/guides/Create-UI-Controls.md

Thanks in advance!

**Comment by karann-msft** [comment]
@SuperJMN check this out - https://docs.microsoft.com/en-us/nuget/guides/create-uwp-packages
