### ISSUE TITLE
how to include referenced projects?

### ISSUE THREAD

**Issue by adamosoftware** [NuGet/docs.microsoft.com-nuget#1819]
How do we use the -IncludeReferencedProjects flag when building packages in this way?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 18071970-cf13-78af-ac1d-9adefefdb693
* Version Independent ID: 3bf15a5c-8b3e-0e69-0bf6-03b44654970c
* Content: [Create and publish a .NET Standard NuGet package - Visual Studio on Windows](https://docs.microsoft.com/en-us/nuget/quickstart/create-and-publish-a-package-using-visual-studio?tabs=netcore-cli)
* Content Source: [docs/quickstart/create-and-publish-a-package-using-visual-studio.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/master/docs/quickstart/create-and-publish-a-package-using-visual-studio.md)
* Product: **nuget**
* GitHub Login: @karann-msft
* Microsoft Alias: **karann**

**Comment by rrelyea** [comment]
Using `dotnet pack` or `msbuild /t:pack` doesn't have support for this today. 

See this highly voted issue [#3891](https://github.com/NuGet/Home/issues/3891) 
(there are a few workarounds detailed in that issue)
