### ISSUE TITLE
Clarify the authentication docs

### ISSUE THREAD

**Issue by nkolev92** [NuGet/docs.microsoft.com-nuget#1823]
https://docs.microsoft.com/en-us/nuget/reference/extensibility/nuget-credential-providers-for-visual-studio#creating-a-nuget-credential-provider-for-visual-studio

The docs don't really mention the default network credentials which are used for ntlm/negotiate/kerberos authentication. 

Note related: https://github.com/dotnet/corefx/issues/30203 and internal e-mail titled "Kerberos on repo Nuget (Artifactory) from Windows Session" 

//cc @NuGet/nuget-client @kartheekp-ms

**Comment by karann-msft** [comment]
@kartheekp-ms - I am leaning on you to help with a PR on this :)
