### ISSUE TITLE
Incomplete documentatoin

### ISSUE THREAD

**Issue by triynko** [NuGet/docs.microsoft.com-nuget#1824]
Every NuGet package I've ever seen has 4 parts to the version number. This only defines 3 of them, even though it hints at the possibility of a fourth when it says "A zero in the fourth part of the version number will be omitted". This does not document the range of allowed version numbers. Often, they're one to 3 digits. I've seen them as large as 5 digits, but this tells me nothing about the actual allowed range.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7c462602-7e8f-2634-4006-3fadaa68ef45
* Version Independent ID: 7a6ec89f-55c5-2d49-6677-fcc87b0e40ac
* Content: [NuGet Package Version Reference](https://docs.microsoft.com/en-us/nuget/concepts/package-versioning)
* Content Source: [docs/concepts/Package-Versioning.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/master/docs/concepts/Package-Versioning.md)
* Product: **nuget**
* GitHub Login: @karann-msft
* Microsoft Alias: **karann**

**Comment by karann-msft** [comment]
@triynko > This does not document the range of allowed version numbers. 
By allowed version numbers, I believe you mean what can be the range of values for each of the 3 parts. 

We use [semantic versioning](https://semver.org/spec/v2.0.0.html) which states
> A normal version number MUST take the form X.Y.Z where X, Y, and Z are non-negative integers, and MUST NOT contain leading zeroes. X is the major version, Y is the minor version, and Z is the patch version. Each element MUST increase numerically. For instance: 1.9.0 -> 1.10.0 -> 1.11.0

I hope that answers your question.

**Comment by triynko** [comment]
No. It still doesn't specify the range of allowed values. "Non-negative integer" is an infinite range. In the real world, the range seems to be "unsigned 16 bit integer, ranging from 0 to 65535". Are the version numbers allowed to exceed the max value of a 16 bit integer? (i.e. greater than 65535?)

On Jan 6, 2020 12:38 PM, Karan Nandwani <notifications@github.com> wrote:

@triynko<https://github.com/triynko> > This does not document the range of allowed version numbers.
By allowed version numbers, I believe you mean what can be the range of values for each of the 3 parts.

We use semantic versioning<https://semver.org/spec/v2.0.0.html> which states

A normal version number MUST take the form X.Y.Z where X, Y, and Z are non-negative integers, and MUST NOT contain leading zeroes. X is the major version, Y is the minor version, and Z is the patch version. Each element MUST increase numerically. For instance: 1.9.0 -> 1.10.0 -> 1.11.0

I hope that answers your question.

**Comment by karann-msft** [comment]
@triynko - each of the parts is "int" which means theoretically they can have a range of 0 to 4294967295.

**Comment by karann-msft** [comment]
We believe the information currently in the docs is sufficient for all practical purposes.
