### ISSUE TITLE
Note about excluded props

### ISSUE THREAD

**Issue by sungam3r** [NuGet/docs.microsoft.com-nuget#1829]
Regarding this note in docs:

> 5. authors and owners field will be excluded from the snupkg's nuspec.

Also `icon` and `requireLicenseAcceptance` props are excluded.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 22767e96-d56f-aa81-f1ca-17e256ed617e
* Version Independent ID: d7cdc676-2705-3cb1-bcd6-d1637460d5c7
* Content: [How to publish NuGet symbol packages using the new symbol package format '.snupkg'](https://docs.microsoft.com/en-us/nuget/create-packages/symbol-packages-snupkg)
* Content Source: [docs/create-packages/Symbol-Packages-snupkg.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/master/docs/create-packages/Symbol-Packages-snupkg.md)
* Product: **nuget**
* Technology: ****
* GitHub Login: @cristinamanu
* Microsoft Alias: **cristinamanu**

**Comment by karann-msft** [comment]
Fixed in #1838
