### ISSUE TITLE
Typo: We recommend an image resoulution

### ISSUE THREAD

**Issue by Crono1981** [NuGet/docs.microsoft.com-nuget#1834]
Should be "resolution". ;)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 06a19d7d-253d-f17f-6421-624c9867473d
* Version Independent ID: cc37eb17-f715-080c-7bfc-9eae868d50ba
* Content: [.nuspec File Reference for NuGet](https://docs.microsoft.com/en-us/nuget/reference/nuspec#icon)
* Content Source: [docs/reference/nuspec.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/master/docs/reference/nuspec.md)
* Product: **nuget**
* GitHub Login: @karann-msft
* Microsoft Alias: **karann**

**Comment by karann-msft** [comment]
Thanks for catching that @Crono1981! We also accept and appreciate PRs to help improve our docs. Just click on the edit button on any page you want to submit a PR for....

![image](https://user-images.githubusercontent.com/16904420/72182171-c835b100-339f-11ea-8163-5622b85c15f8.png)

**Comment by Crono1981** [comment]
@karann-msft Huh! Never even noticed that button before. Thanks, will do. :)
