### ISSUE TITLE
Missing option for install  -DependencyVersion parameter

### ISSUE THREAD

**Issue by JamesQMurphy** [NuGet/docs.microsoft.com-nuget#1849]
The `-DependencyVersion` parameter has a fifth option that is not listed:  `ignore`
This suppresses nuget.exe from downloading dependencies.
Can it please be added?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 18671d93-6504-2771-9bd2-699a51a1a4d7
* Version Independent ID: 46c8e886-eea8-c9f9-be41-fcdd3a1c180c
* Content: [NuGet CLI install command](https://docs.microsoft.com/en-us/nuget/reference/cli-reference/cli-ref-install)
* Content Source: [docs/reference/cli-reference/cli-ref-install.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/master/docs/reference/cli-reference/cli-ref-install.md)
* Product: **nuget**
* GitHub Login: @karann-msft
* Microsoft Alias: **karann**

**Comment by karann-msft** [comment]
@JamesQMurphy - thanks for point this out.
PS: we are happy to accept PRs :) 
Just click on the edit button on the top right of the page to get started...
![image](https://user-images.githubusercontent.com/16904420/72937280-acc29280-3d1d-11ea-9559-a99fc0009174.png)

**Comment by JamesQMurphy** [comment]
Thanks... looks like @kim-lindhard-dfds beat me to it.  Next time I will submit a PR! 😃

**Comment by karann-msft** [comment]
Fixed in #1851
