### ISSUE TITLE
How do I set Owners with an msbuild project?

### ISSUE THREAD

**Issue by shueybubbles** [NuGet/docs.microsoft.com-nuget#1858]
This page just says Owners isn't supported outside of a nuspec, so where is the doc/example on how to set Owners? Nuget.org appears to provide hyperlinks to an Owner id, but not for an Author id.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 099102e8-c320-ef50-6821-57519684dc98
* Version Independent ID: 1523dac4-419d-613d-2497-4062f9efd358
* Content: [NuGet pack and restore as MSBuild targets](https://docs.microsoft.com/en-us/nuget/reference/msbuild-targets)
* Content Source: [docs/reference/msbuild-targets.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/master/docs/reference/msbuild-targets.md)
* Product: **nuget**
* GitHub Login: @karann-msft
* Microsoft Alias: **karann**

**Comment by karann-msft** [comment]
The short answer is - you don't.
The owner is the one who published the package to nuget.org. For example - my nuget.org profile name is "karann-msft". When I publish a package, the owner is set to "karann-msft".
See this -> https://www.nuget.org/packages/KRN.AppLogger/
Please feel free to reopen the issue if that didn't answer your question.
