### ISSUE TITLE
.Nuget Solution Folder Confusion

### ISSUE THREAD

**Issue by gravidThoughts** [NuGet/docs.microsoft.com-nuget#1859]
[Documentation states](https://docs.microsoft.com/en-us/nuget/consume-packages/configuring-nuget-behavior):

> NuGet 3.3 and earlier used a .nuget folder for solution-wide settings. This folder is not used in NuGet 3.4+.

So what exactly does this mean? I upgrade VS and move from Nuget 3.3 to 3.4. 

Are all nuget.config files contained in .nuget folders suddenly ignored by the nuget cli?
If I move the nuget.config from the .nuget solution folder into the same folder as the solution file, this will start to be used as the solution scoped configuration?
Solution scoped settings do not exist with 3.4+?

The documentation further states that:

> In a solution folder, settings apply to all projects in subfolders. Note that if a config file is placed in a project folder, it has no effect on that project.

Does this mean if I have a project in a solution file that is not nested in the folder with the solution file itself, the nuget configuation does not apply to that project?

Please clarify.
Thanks,
Matthew

**Comment by karann-msft** [comment]
@gravidThoughts - what is your scenario? What kind of project do you have? What version of Visual Studio and NuGet are you using? What is it that you are intending to achieve?

**Comment by gravidThoughts** [comment]
@karann-msft  Let's start with the first scenario I described above. Upgrading Visual Studio resulting upgrading of VS nuget from 3.3 or earlier  to 3.4+. If the solution depended on `.nuget` solution folder, does it all of a sudden break? Per your documentation: 

> NuGet 3.3 and earlier used a .nuget folder for solution-wide settings. This folder is not used in NuGet 3.4+.

**Comment by karann-msft** [comment]
@gravidThoughts - no it does not.

**Comment by karann-msft** [comment]
@gravidThoughts - after you've had a chance to try out the side by side install and if you run into issues, file an issue on the [Home repo](https://github.com/NuGet/Home/issues).
