### ISSUE TITLE
Conflicting NuGet image size information

### ISSUE THREAD

**Issue by jc1001** [NuGet/docs.microsoft.com-nuget#1863]
On page:
https://docs.microsoft.com/en-us/nuget/reference/msbuild-targets#packing-an-icon-image-file
there is a sentence at the end of the first paragraph that reads:
"We recommend an image resolution of 64x64."

On page:
https://docs.microsoft.com/en-us/nuget/reference/nuspec#icon
there is a sentence at the end of the first paragraph that reads:
"We recommend an image resolution of 128x128."

According to this page:
https://github.com/NuGet/Home/wiki/Packaging-Icon-within-the-nupkg#other-considerations
it seems that the recommended size is 128x128

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 099102e8-c320-ef50-6821-57519684dc98
* Version Independent ID: 1523dac4-419d-613d-2497-4062f9efd358
* Content: [NuGet pack and restore as MSBuild targets](https://docs.microsoft.com/en-us/nuget/reference/msbuild-targets#packageicon)
* Content Source: [docs/reference/msbuild-targets.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/master/docs/reference/msbuild-targets.md)
* Product: **nuget**
* GitHub Login: @karann-msft
* Microsoft Alias: **karann**

**Comment by karann-msft** [comment]
@jc1001 - thanks for catching that. We also accept PRs, Just click on the "edit" button on the top right of the page to get started :)
![image](https://user-images.githubusercontent.com/16904420/73872527-b6abc180-4804-11ea-91a9-b7f78e1123f2.png)
