### ISSUE TITLE
how do you do a first time push of a nupkg?

### ISSUE THREAD

**Issue by ticianaciminari** [NuGet/docs.microsoft.com-nuget#1867]
@taori commented on [Wed Jan 29 2020](https://github.com/NuGet/docs.microsoft.com-nuget.de-de/issues/18)

this information would be useful at this place, since it does not work. if i recall correctly nuget add is used instead then, but `nuget add` has no api key parameter. possibly a missing thing in the CLI

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: c75248c2-cd5d-cbb2-6c33-0103586491e1
* Version Independent ID: a318c7de-b335-5df1-b7ec-1c448abcf7f4
* Content: [Befehl ](https://docs.microsoft.com/de-de/nuget/reference/cli-reference/cli-ref-push)
* Content Source: [docs/reference/cli-reference/cli-ref-push.md](https://github.com/NuGet/docs.microsoft.com-nuget.de-de/blob/live/docs/reference/cli-reference/cli-ref-push.md)
* Product: **nuget**
* GitHub Login: @karann-msft
* Microsoft Alias: **karann**

---

@srvbpigh commented on [Wed Jan 29 2020](https://github.com/NuGet/docs.microsoft.com-nuget.de-de/issues/18#issuecomment-579939993)

Hello, @taori
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.

Kind regards,
Microsoft DOCS International Team

---

@taori commented on [Wed Jan 29 2020](https://github.com/NuGet/docs.microsoft.com-nuget.de-de/issues/18#issuecomment-579975705)

Ok. Pushing against the v3 api apparently does no longer require nuget add calls but accepts a push as initial command. Also i had an error which was unrelated to nuget itself but to secret variables in azure devops which prompted me with an error, because my key variable was not expanded

**Comment by ticianaciminari** [comment]
Hi Team, could you please check user's question?

Kind regards,

Microsoft DOCS Global Experience Team

**Comment by karann-msft** [comment]
@taori - take a look at this doc - https://docs.microsoft.com/en-us/nuget/nuget-org/publish-a-package
Feel free to reopen the issue if it does no resolve your concern.
