### ISSUE TITLE
Signing on Linux? 

### ISSUE THREAD

**Issue by DanVev** [NuGet/docs.microsoft.com-nuget#1868]
Hi, is it still impossible to sign NuGet packages on non-Window platforms (e.g. Linux)? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a85b6901-248a-5423-4b73-2e45cd1d750a
* Version Independent ID: bb29b2b7-46d0-e683-57e4-14317f29fd6f
* Content: [NuGet CLI sign command](https://docs.microsoft.com/en-us/nuget/reference/cli-reference/cli-ref-sign#feedback)
* Content Source: [docs/reference/cli-reference/cli-ref-sign.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/master/docs/reference/cli-reference/cli-ref-sign.md)
* Product: **nuget**
* GitHub Login: @dtivel
* Microsoft Alias: **dtivel**

**Comment by dtivel** [comment]
Yes; however, [efforts are underway](https://github.com/NuGet/Home/issues/7939) to enable this.
