### ISSUE TITLE
customize expiration of http-cache

### ISSUE THREAD

**Issue by qub1n** [NuGet/docs.microsoft.com-nuget#1869]
It is possible of customizing expiration of http-cache?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 71b49477-cafa-d7d4-76fe-83aff43a3f47
* Version Independent ID: 68d7a416-1397-8cf3-bead-e3cd328aca48
* Content: [How to manage the global packages, cache, temp folders in NuGet](https://docs.microsoft.com/en-us/nuget/consume-packages/managing-the-global-packages-and-cache-folders)
* Content Source: [docs/consume-packages/managing-the-global-packages-and-cache-folders.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/master/docs/consume-packages/managing-the-global-packages-and-cache-folders.md)
* Product: **nuget**
* GitHub Login: @karann-msft
* Microsoft Alias: **karann**

**Comment by karann-msft** [comment]
@qub1n - this repo is not meant for asking product related questions. I would start with StackOverflow - https://stackoverflow.com/questions/tagged/nuget. If you would like to report a product bug, please do so on the Home repo - https://github.com/NuGet/Home
