### ISSUE TITLE
packageRestore section of nuget.config is optional

### ISSUE THREAD

**Issue by AnthonySteele** [NuGet/docs.microsoft.com-nuget#1873]
In https://docs.microsoft.com/en-us/nuget/reference/nuget-config-file

The `packageRestore` section of `nuget.config` is optional, but the docs don't make this clear, or say what the defaults are.

Similarly most other sections besides `packageSources`.

People use the example file given, and produce overcomplex files, most of which isn't needed. We are currently using a simple file that looks like this:

```
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <packageSources>
    <clear />
    <add key="nuget.org" value="https://api.nuget.org/v3/index.json" />
    <add key="Acme" value="https://pkgs.acme.com/nuget/v3/index.json" />      
  </packageSources>
</configuration>
```

Which should be a better starting point.

**Comment by karann-msft** [comment]
@AnthonySteele - it is not optional. It works because some config file in the hierarchy, most likely the default ones created by a VS install, is supplying this value. NuGet reads and all config files right up to the root to determine the effective nuget.config.

**Comment by AnthonySteele** [comment]
Good point. Though people do tend to assume that the "Example config file" is the kind of thing that they should check into each rope.
