### ISSUE TITLE
Missing SkipGetTargetFrameworkProperties and PublishProfile attributes

### ISSUE THREAD

**Issue by gewarren** [NuGet/docs.microsoft.com-nuget#1890]
(From Oren Novotny)

Missing the SkipGetTargetFrameworkProperties attribute, which affects restore compatibility checks.

Also missing the PublishProfile attribute, which can be used to specify a pubxml file in the case of wapproj project types.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ff707668-94d6-25a5-9139-b18cc1b6b446
* Version Independent ID: 494847b9-4894-0beb-7ffa-39a2359999fa
* Content: [NuGet PackageReference format (package references in project files)](https://docs.microsoft.com/en-us/nuget/consume-packages/package-references-in-project-files#locking-dependencies)
* Content Source: [docs/consume-packages/Package-References-in-Project-Files.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/master/docs/consume-packages/Package-References-in-Project-Files.md)
* Product: **nuget**
* GitHub Login: @karann-msft
* Microsoft Alias: **karann**

**Comment by karann-msft** [comment]
@gewarren - I need more context here. I don't know what these properties are. @nkolev92 do they look familiar?

**Comment by nkolev92** [comment]
SkipGetTargetFrameworkProperties  is used to skip project references, but we use ReferenceOutputAssembly in our code so not sure whether it works cleanly (I think it does, but haven't played around with this in a while). 

Not familiar with PublishProfile

**Comment by karann-msft** [comment]
@onovotney?

**Comment by onovotny** [comment]
They're both in the wapproj tooling by default as attributes of the ProjectReference.

**Comment by nkolev92** [comment]
wapproj doesn't really import the NuGet.targets right now does it? 

Any usage of PublishProfile beyond wapproj?

**Comment by gewarren** [comment]
Please keep open.
