### ISSUE TITLE
need more detail on how nuget constructs paths to the package

### ISSUE THREAD

**Issue by stevenbrix** [NuGet/docs.microsoft.com-nuget#1894]
It seems that under some circumstances, Nuget puts the package in a `\packages\<package_name>\<package_version>` folder and sometimes it's in `\packages\<package_name>.<package_version>\` folder. For those that can't use `PackageReference` (C++) it would be helpful to understand when and why this is, because we have to construct the paths manually, instead of allowing MSBuild to do so for us

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 370d9d91-9f35-79aa-3ace-7b77436e988f
* Version Independent ID: 3da4591a-3d3d-c07a-6672-97964de13b14
* Content: [Common NuGet configurations](https://docs.microsoft.com/en-us/nuget/consume-packages/configuring-nuget-behavior#feedback)
* Content Source: [docs/consume-packages/configuring-nuget-behavior.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/master/docs/consume-packages/configuring-nuget-behavior.md)
* Product: **nuget**
* GitHub Login: @karann-msft
* Microsoft Alias: **karann**

**Comment by karann-msft** [comment]
@stevenbrix - that is an implementation detail and not something we plan to document. Please feel free to reach out nugetdisc alias.

**Comment by stevenbrix** [comment]
@karann-msft why? we've had build breaks in our lab because of this. we also have duplicate versions of packages on disk, one in the `<package_name>\<package_version>` and the other in the `<package_name>.<package_version>` folder. it would be nice to know why this is so we can avoid it
