### ISSUE TITLE
widen its version constraints

### ISSUE THREAD

**Issue by ravick4u** [NuGet/docs.microsoft.com-nuget#1899]
Could you please elaborate on how I can "change the project's reference to the package to widen its version constraints."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5d8ccae0-8ebb-e0bd-07a5-e64a7044e7f5
* Version Independent ID: f71c678f-ef86-3eea-6db5-f7b45db4a6aa
* Content: [NuGet Warning NU1608](https://docs.microsoft.com/en-us/nuget/reference/errors-and-warnings/nu1608?f1url=https%3A%2F%2Fmsdn.microsoft.com%2Fquery%2Fdev16.query%3FappId%3DDev16IDEF1%26l%3DEN-US%26k%3Dk(NU1608)%26rd%3Dtrue)
* Content Source: [docs/reference/errors-and-warnings/NU1608.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/master/docs/reference/errors-and-warnings/NU1608.md)
* Product: **nuget**
* GitHub Login: @zhili1208
* Microsoft Alias: **lzhi**

**Comment by karann-msft** [comment]
@ravick4u - what type of project do you have? Does it use packages.config or packageReference?

**Comment by ravick4u** [comment]
I don't have packages.config file in my solution so I believe its packageReference

**Comment by karann-msft** [comment]
You can use floating versions - https://docs.microsoft.com/en-us/nuget/consume-packages/package-references-in-project-files#floating-versions

**Comment by ravick4u** [comment]
Not sure when you say floating version. Could you please let me know how this can be updated in the project?

**Comment by karann-msft** [comment]
I have linked to the docs in my previous comment which has examples. If you have more questions please start with StackOverflow - https://stackoverflow.com/questions/tagged/nuget
