### ISSUE TITLE
XDT not supported for PackageReference projects

### ISSUE THREAD

**Issue by AndrewKoransky** [NuGet/docs.microsoft.com-nuget#1907]
According to https://docs.microsoft.com/en-us/nuget/consume-packages/migrate-packages-config-to-package-reference, XDT transforms are not supported for PackageReference projects. Shouldn't this be mentioned here??

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 40bb9dee-46d6-4064-83e8-ba2e22ac6afe
* Version Independent ID: aac0bbd8-645b-ccf8-bec9-e0d970c8b089
* Content: [Source and config file transformations for NuGet packages](https://docs.microsoft.com/en-us/nuget/create-packages/source-and-config-file-transformations)
* Content Source: [docs/create-packages/Source-and-Config-File-Transformations.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/master/docs/create-packages/Source-and-Config-File-Transformations.md)
* Product: **nuget**
* GitHub Login: @karann-msft
* Microsoft Alias: **karann**

**Comment by karann-msft** [comment]
@AndrewKoransky, if you scroll down the page a little you should see this - https://docs.microsoft.com/en-us/nuget/consume-packages/migrate-packages-config-to-package-reference#xdt-transforms-are-not-applied-when-the-package-is-installed-after-the-upgrade

**Comment by zivkan** [comment]
Whoever updates the docs should not only make it more clear that XDT currently documented in `packages.config` only (the very first paragraph of the docs already say this), but also should document how it could be done with `PackageReference`. See this thread: https://github.com/NuGet/Home/issues/5954

also this sample: https://github.com/NuGet/Samples/pull/15/files
