### ISSUE TITLE
Use consistent casing for the NuGet.config references

### ISSUE THREAD

**Issue by nkolev92** [NuGet/docs.microsoft.com-nuget#1933]
Proposed one is NuGet.config...thoughts @zivkan @karann-msft

**Comment by rrelyea** [comment]
Might be interested to understand (and decide to be consistent) with what case we create those files in different scenarios too. `dotnet new nugetconfig` in 5.0.0-preview2 daily build creates 'nuget.config' file. Not sure what VS does.

**Comment by zivkan** [comment]
50 days slow reply. Anyway, I'd suggest considering all lowercase.

When NuGet creates the user-profile config, it always uses `NuGet/NuGet.Config` casing, on both Windows and Linux (I don't have a Mac to test, but I'd expect it to be the same).

However, .NET, thanks to .NET Core, is becoming more and more popular on Linux and Mac. Most UNIXy tools use all lowercase (on any Linux machine, even Windows Subsystem for Linux, do `ls /etc` and see how many other tools use config files or directories with mixed case), which is probably why `dotnet new nugetconfig` creates all lowercase `nuget.config`. So, if we also use all lowercase, it will feel more natural to anyone used to using Linux, and probably Mac. I don't think that Windows developers (at least .NET developers on Windows) use the command line much, so I don't think most will notice.

I'd even go as far as saying we should consider changing NuGet to creates an all lower-case user-profile `nuget.config` when one doesn't already exist, but we'd need to test that it still find the config on case sensitive filesystems. Unfortunately I don't think it's feasible to change the default directory name from `NuGet` to `nuget` though (although `NuGet` is the most natural casing on Windows)

**Comment by JonDouglas** [comment]
Should we keep this issue open? Not sure we should refactor this right now and rather just keep in mind that linux is case sensitive.
