### ISSUE TITLE
unlist nuget package

### ISSUE THREAD

**Issue by MohammadMQ** [NuGet/docs.microsoft.com-nuget#1939]
Maybe this page could inform the reader about how to unlist a specific version of a nuget package. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f1e7b39d-59f3-f390-26ec-404ccb8e97be
* Version Independent ID: eba35a17-7cc0-2a6b-2421-24a7fba46d28
* Content: [Deleting NuGet Packages from nuget.org](https://docs.microsoft.com/en-us/nuget/nuget-org/policies/deleting-packages)
* Content Source: [docs/nuget-org/policies/deleting-packages.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/master/docs/nuget-org/policies/deleting-packages.md)
* Product: **nuget**
* GitHub Login: @karann-msft
* Microsoft Alias: **karann**

**Comment by karann-msft** [comment]
@MohammadMQ - the doc calls out 
> nuget.org does supports unlisting a package, which can be done in the package management page on the web site.

Looking at your package - [MKValidator.Mohammad_Mukammil](https://www.nuget.org/packages/MKValidator.Mohammad_Mukammil/1.0.2), I can see that you have unlisted packages in the past which leads me to believe this document was sufficient and/or the website is intuitive enough to perform this action.

![image](https://user-images.githubusercontent.com/16904420/76131957-5d7eab80-5fc5-11ea-944c-8650170f09b4.png)

**Comment by MohammadMQ** [comment]
Hi Karann
Thanks for your reply. 
The MKValidator.Mohammad_Mukammil account at nuget is not mine. I have no control over it. I just used it as an example. 
However I found out myself how to unlist a nuget package. This document is not at all sufficient in informing the user as how to unlist a nuget package. The whole process of unlisted a nuget package requires many steps that aren't mentioned here.

**Comment by karann-msft** [comment]
@MohammadMQ - thanks for the feedback. We also accept pull requests from the community to improve our docs. Start by selecting the "Edit" button on the top left of the page you wish to contribute to.
![image](https://user-images.githubusercontent.com/16904420/76253377-d66d4580-6207-11ea-9859-3016d1c73099.png)

**Comment by joelverhagen** [comment]
This document now contains steps as of https://github.com/NuGet/docs.microsoft.com-nuget/pull/1945. Thanks for doing this, @MohammadMQ.
