### ISSUE TITLE
source not understandable

### ISSUE THREAD

**Issue by MohammadMQ** [NuGet/docs.microsoft.com-nuget#1940]
I'm not able to understand the url of the source (http://package.contoso.com/source). 
If I want to delete a specific nuget version of a repo at nuget, e.g. https://www.nuget.org/packages/MKValidator.Mohammad_Mukammil/1.0.3 
how would I write the above delete command?

---
#### Dokumentoplysninger

⚠ *Undlad at redigere denne sektion. Det er påkrævet til docs.microsoft.com ➟ GitHub-problemlinkning.*

* ID: eb358f2f-a905-a02c-b1d1-9bc994cdca5f
* Version Independent ID: ec61a9fd-0c90-1f65-0593-e743d1a245ad
* Content: [NuGet CLI delete command](https://docs.microsoft.com/da-dk/nuget/reference/cli-reference/cli-ref-delete)
* Content Source: [docs/reference/cli-reference/cli-ref-delete.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/master/docs/reference/cli-reference/cli-ref-delete.md)
* Product: **nuget**
* GitHub Login: @karann-msft
* Microsoft Alias: **karann**

**Comment by karann-msft** [comment]
@MohammadMQ - that doc page says
> for nuget.org, the delete command unlists the package.

Packages on nuget.org cannot be deleted as a matter of policy - https://docs.microsoft.com/en-us/nuget/nuget-org/policies/deleting-packages
