### ISSUE TITLE
Add .NET CLI to local feeds documentation

### ISSUE THREAD

**Issue by vivainio** [NuGet/docs.microsoft.com-nuget#1942]
See page: https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-nuget-push

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 72d49ada-7a7b-e976-88a0-72ad0707dbd8
* Version Independent ID: dcc2b12a-4da9-8e7b-f973-e49347030651
* Content: [Setting up Local NuGet Feeds](https://docs.microsoft.com/en-us/nuget/hosting-packages/local-feeds)
* Content Source: [docs/hosting-packages/Local-Feeds.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/master/docs/hosting-packages/Local-Feeds.md)
* Product: **nuget**
* GitHub Login: @karann-msft
* Microsoft Alias: **karann**

**Comment by yangrongwei** [comment]
On my experiment, "dotnet nuget push" is using a single folder layout. ( dotnet --version == Version:   3.1.101)
