### ISSUE TITLE
NU1603

### ISSUE THREAD

**Issue by m-ringler** [NuGet/docs.microsoft.com-nuget#1950]
This page should document under which circumstances a [NU1603](https://docs.microsoft.com/en-us/nuget/reference/errors-and-warnings/nu1603) warning is issued, and ways to avoid it.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8e8a945e-ee7e-cefa-282a-41da09a951b9
* Version Independent ID: c380b1cb-6e17-7777-995f-7c8b48f581de
* Content: [NuGet Package Dependency Resolution](https://docs.microsoft.com/en-us/nuget/concepts/dependency-resolution)
* Content Source: [docs/concepts/Dependency-Resolution.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/master/docs/concepts/Dependency-Resolution.md)
* Product: **nuget**
* GitHub Login: @karann-msft
* Microsoft Alias: **karann**

**Comment by karann-msft** [comment]
@m-ringler - thanks for the feedback. We will definitely consider this we reorganize the content of our docs.
