### ISSUE TITLE
Need clarification for computer configuration for Linux

### ISSUE THREAD

**Issue by euyuil** [NuGet/docs.microsoft.com-nuget#1954]
For the `NuGet.Config` path on Linux, the document says it should be located at `/usr/local/share` if the environment doesn't specify it. It's a directory so I'm assuming the full file path should be `/usr/local/share/NuGet.Config`. But after I created such file (added a package source), and used `dotnet restore` to restore my project, the package source was not referenced to.

I'm wondering if it's because the full path is wrong, or the document doesn't apply to `dotnet restore`.

Thank you!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 370d9d91-9f35-79aa-3ace-7b77436e988f
* Version Independent ID: 3da4591a-3d3d-c07a-6672-97964de13b14
* Content: [Common NuGet configurations](https://docs.microsoft.com/en-us/nuget/consume-packages/configuring-nuget-behavior)
* Content Source: [docs/consume-packages/configuring-nuget-behavior.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/master/docs/consume-packages/configuring-nuget-behavior.md)
* Product: **nuget**
* GitHub Login: @karann-msft
* Microsoft Alias: **karann**

**Comment by timothy-mcroy** [comment]
Hi. I had the same issue. The problem is that the documentation for nuget.exe has NuGet.Config , but dotnet restore needs nuget.config . Linux is case-sensitive.

**Comment by hangjit-domain** [comment]
I moved the `NuGet.Config` file to `~/.nuget/NuGet` in Ubuntu 20.x WSL and seems to have been picked up by `dotnet run`

**Comment by hrai** [comment]
I moved the `NuGet.Config` file to `~/.nuget/NuGet` in Ubuntu 20.x WSL and seems to have been picked up by `dotnet run`

**Comment by euyuil** [comment]
@hrai Thanks for the solution. But I need to apply the config file on machine level for all the users.

**Comment by heng-liu** [comment]
The code of machine wide config file on Linux and Mac are from **SpecialFolder.CommonApplicationData** + "NuGet" + ".config".
And the  **SpecialFolder.CommonApplicationData** is resolved here for .NET Core code path on non-Windows platform:
https://github.com/NuGet/NuGet.Client/blob/dev/src/NuGet.Core/NuGet.Common/PathUtil/NuGetEnvironment.cs#L113-L126
However, the document doesn't respect the code...

**Comment by JonDouglas** [comment]
@heng-liu quick ping on the above. That way we can close out this issue with a quick PR. :)
