### ISSUE TITLE
AssetTargetFallback doesn't work for transitive dependencies - workaround

### ISSUE THREAD

**Issue by rrelyea** [NuGet/docs.microsoft.com-nuget#1955]
If you get a NU1701 warning for package A...and package A pulls in package B and package C as dependencies, B and C will not be properly pulled in for use into your project.
Fixes: 
- contact package A author to update the package to work more naturally for the TFM of your project (add netstandard2.0 and/or netcoreapp3.1 tfm support)
- workaround the outdated package and this problem by directly referencing A, B, and C.

FYI - @nkolev92

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 377ae860-386f-149f-c5e0-410d3aa89dbc
* Version Independent ID: 2b145147-fd3f-d1aa-2694-071a31542d9a
* Content: [NuGet Errors and Warnings Reference](https://docs.microsoft.com/en-us/nuget/reference/errors-and-warnings/nu1701)
* Content Source: [docs/reference/errors-and-warnings/NU1701.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/master/docs/reference/errors-and-warnings/NU1701.md)
* Product: **nuget**
* GitHub Login: @zhili1208
* Microsoft Alias: **lzhi**

**Comment by nkolev92** [comment]
This works nowadays. https://learn.microsoft.com/en-us/nuget/release-notes/nuget-6.2#summary-whats-new-in-62
