### ISSUE TITLE
Conflicting information for env vars

### ISSUE THREAD

**Issue by mtttcgcg** [NuGet/docs.microsoft.com-nuget#1959]
The article content states:
"Note that you have to use Windows-style environment variables (starts and ends with %) even on Mac/Linux"

Yet the example config file has a comment which states:
"In this example, %PACKAGEHOME% is an environment variable. On Mac/Linux, use $PACKAGE_HOME/External as the value."

Which is correct?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0ea1390e-db36-6759-3095-ebab9d546fdb
* Version Independent ID: ca88d8c6-0515-a267-aac3-a508c54157ab
* Content: [nuget.config File Reference](https://docs.microsoft.com/en-us/nuget/reference/nuget-config-file#feedback)
* Content Source: [docs/reference/nuget-config-file.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/master/docs/reference/nuget-config-file.md)
* Product: **nuget**
* GitHub Login: @karann-msft
* Microsoft Alias: **karann**

**Comment by dominoFire** [comment]
### NuGet.Config environment variable support on Mac

| Syntax | nuget.exe (Via Mono) | dotnet.exe |
|---|---|---|
| `%MY_VAR%` | Yes | Yes |
| `$MY_VAR` | No | No |
