### ISSUE TITLE
PackageIcon not doesn't work in VS 16.5.0 yet 

### ISSUE THREAD

**Issue by jasonycw** [NuGet/docs.microsoft.com-nuget#1960]
We are using a self host NuGet server and was using `PackageIconUrl` before. After we reading this doc and saw https://github.com/NuGet/docs.microsoft.com-nuget/issues/1755 and https://github.com/NuGet/Home/issues/8189 are closed, we decided to move to `PackageIcon`. But then NuGet PM UI revert back to showing the default icon.

Even following the example here https://github.com/NuGet/Samples/blob/master/PackageIconExample/PackageIconExample.csproj does not show the icon properly. We need to then add back `PackageIconUrl`

It will be better if the **tips** specify exactly which VS version will start supporting `PackageIcon` properly and it is not supported now instead of vaguely mention 
> Visual Studio will support `PackageIcon` for packages coming from a folder-based source in a future release.

So that dev will not remove `PackageIconUrl` right now.

And as mentioned before (https://github.com/NuGet/docs.microsoft.com-nuget/issues/1755#issuecomment-552174544), until `PackageIcon` is shipped properly and can be used in VS NuGet PM UI, I don't think `PackageIconUrl` should be marked as **deprecated** yet.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 099102e8-c320-ef50-6821-57519684dc98
* Version Independent ID: 1523dac4-419d-613d-2497-4062f9efd358
* Content: [NuGet pack and restore as MSBuild targets](https://docs.microsoft.com/en-us/nuget/reference/msbuild-targets#packing-an-icon-image-file)
* Content Source: [docs/reference/msbuild-targets.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/master/docs/reference/msbuild-targets.md)
* Product: **nuget**
* GitHub Login: @karann-msft
* Microsoft Alias: **karann**

**Comment by karann-msft** [comment]
Does your self host server have the ability to understand the new packageIcon metadata, host package icon and serve it?

**Comment by jasonycw** [comment]
https://github.com/emgarten/Sleet/blob/master/ReleaseNotes.md

Seems like they've updated it recently, we will update that and have a look, thanks

**Comment by jasonycw** [comment]
Seems like Sleet's S3 NuGet server not support `PackageIcon` yet
https://github.com/emgarten/Sleet/issues/107

**Comment by JobaDiniz** [comment]
Using **private** `github nuget packages` the self-contained icons do not appear in VS, but if I download the `.nupgk` and opened in the *package explorer* it shows the icon there.
