### ISSUE TITLE
How to solve it

### ISSUE THREAD

**Issue by akramHossain49119** [NuGet/docs.microsoft.com-nuget#1961]
(
Package 'PackageId' 4.0.11 is not compatible with 'TargetFramework'. Package 'PackageId' 4.0.11 supports:
  - 'TargetFrameworkA'
  - 'TargetFrameworkB'
  - 'TargetFrameworkC'

[Enter feedback here]
)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b2c2eb22-045b-1c00-512a-a9eb1be4d784
* Version Independent ID: 87d10a7f-725b-18ef-d5ae-12b2f1c568b3
* Content: [NuGet Error NU1202](https://docs.microsoft.com/en-us/nuget/reference/errors-and-warnings/nu1202?f1url=https%3A%2F%2Fmsdn.microsoft.com%2Fquery%2Fdev15.query%3FappId%3DDev15IDEF1%26l%3Den-US%26k%3Dk(NU1202)%26rd%3Dtrue)
* Content Source: [docs/reference/errors-and-warnings/NU1202.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/master/docs/reference/errors-and-warnings/NU1202.md)
* Product: **nuget**
* GitHub Login: @zhili1208
* Microsoft Alias: **lzhi**

**Comment by akramHossain49119** [comment]
How to solve it?

**Comment by karann-msft** [comment]
> How to solve it?

Change the project's target framework to one that the package supports.

**Comment by norgie** [comment]
Can anyone please tell me what's the correct approach? This is my project file
`  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
    <TargetFramework>netcoreapp3.1</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.CSharp" Version="4.7.0" />
  </ItemGroup>
`
and this is parts of the nuspec file
`    <dependencies>
      <group targetFramework=".NETStandard2.1">
        <dependency id="Microsoft.CSharp" version="4.7.0" />
      </group>
      <group targetFramework=".NetCore,Version=3.1">
        <dependency id="Microsoft.CSharp" version="4.7.0" />
      </group>
    </dependencies>
    <packageTypes>
      <packageType name="Dependency" />
    </packageTypes>  
  </metadata>
  <files>
    <file src="bin\$configuration$\**\*.*" exclude="**\*.pdb" target=".\lib"/>
  </files>
`
After building this assembly, when I try to install it in a .net core 3.1 project I get the dreaded:
Error	NU1202	Package JDM.Common.Json 0.2.2 is not compatible with netcoreapp3.1 (.NETCoreApp,Version=v3.1). Package JDM.Common.Json 0.2.2 does not support any target frameworks. ... `

It is driving me crazy.

**Comment by karann-msft** [comment]
@norgie - please file an issue on the Home repo - https://github.com/nuget/home/issues
