### ISSUE TITLE
Search terms not described

### ISSUE THREAD

**Issue by BruceHaley** [NuGet/docs.microsoft.com-nuget#1964]
Would be nice to have a link to a description of the search terms syntax. Saying "Search terms are applied...just as they are when using them on nuget.org" is not sufficient, as the syntax is not described there, either. I want to know, for instance, how to get only exact matches to a package name. Searching for "Moq", Moq is buried in a list of 253 hits.
Thank you.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7387ab78-ea68-638b-37fa-e3e0b567bd34
* Version Independent ID: 2050c175-26f2-bd31-174d-84661f7ab845
* Content: [NuGet CLI list command](https://docs.microsoft.com/en-us/nuget/reference/cli-reference/cli-ref-list#feedback)
* Content Source: [docs/reference/cli-reference/cli-ref-list.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/master/docs/reference/cli-reference/cli-ref-list.md)
* Product: **nuget**
* GitHub Login: @karann-msft
* Microsoft Alias: **karann**

**Comment by william-gross** [comment]
@BruceHaley I had the same issue and found search syntax at https://docs.microsoft.com/en-us/nuget/consume-packages/finding-and-choosing-packages#search-syntax

**Comment by BruceHaley** [comment]
I created [PR #2042](https://github.com/NuGet/docs.microsoft.com-nuget/pull/2042) adding @william-gross 's suggested link to the document. If approved, this would fix the problem.

**Comment by JonDouglas** [comment]
Should be fixed via https://github.com/NuGet/docs.microsoft.com-nuget/pull/2042 Thanks for the PR!
