### ISSUE TITLE
NuGet Warning NU5048 - Icon URL is deprecated

### ISSUE THREAD

**Issue by c0g1t8** [NuGet/docs.microsoft.com-nuget#1966]
The `iconUrl` nuspec property is deprecated and should not be recommended by our documentation:

* [x] Update `nuget spec` to not include an `iconUrl`. Tracked by: https://github.com/NuGet/Home/issues/10400
* [ ] Once https://github.com/NuGet/Home/issues/10400 is done, update the nuspec generated by the `nuget spec` command in the [Generate the initial manifest section](https://docs.microsoft.com/en-us/nuget/quickstart/create-and-publish-a-package-using-visual-studio-net-framework#generate-the-initial-manifest).
* [x] Update the [Edit manifest section](https://docs.microsoft.com/en-us/nuget/quickstart/create-and-publish-a-package-using-visual-studio-net-framework#edit-the-manifest) to not mention `iconUrl`.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e8beb111-7b49-2fbe-eeb5-e485b6515ef2
* Version Independent ID: 22535840-0a27-797e-ebc8-5dbe447156d2
* Content: [Create and publish a .NET Framework NuGet package using Visual Studio on Windows](https://docs.microsoft.com/en-us/nuget/quickstart/create-and-publish-a-package-using-visual-studio-net-framework)
* Content Source: [docs/quickstart/create-and-publish-a-package-using-visual-studio-net-framework.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/master/docs/quickstart/create-and-publish-a-package-using-visual-studio-net-framework.md)
* Product: **nuget**
* GitHub Login: @karann-msft
* Microsoft Alias: **karann**

**Comment by c0g1t8** [comment]
Related to #1965.

**Comment by karann-msft** [comment]
@c0g1t8 - what text specifically?

**Comment by c0g1t8** [comment]
I forgot to add the fact that I found this warning with **VS2019 16.5.0**.   You can find the text in question by searching for **iconURL**.

Below are two links with more details.
- https://docs.microsoft.com/en-us/nuget/reference/errors-and-warnings/nu5048
- https://github.com/NuGet/Home/issues/8569

I realize that this may have to wait till the documentation is updated for VS2019 but I thought it was worthwhile to call out.  :)

**Comment by CrispyDrone** [comment]
This is behaving as an error, __not__ a warning for me.

`dotnet pack` "crashes" and doesn't produce a nupkg file. Encountered the error while creating a package for my fork of this library: https://github.com/NuKeeperDotNet/NuKeeper

**Comment by zivkan** [comment]
@CrispyDrone your project is asking tooling to treat all warnings as errors: https://github.com/NuKeeperDotNet/NuKeeper/blob/ed8d5bad0f3e5a4c77838f6e6d9c51a3d11f3bb7/Directory.Build.props#L4

**Comment by CrispyDrone** [comment]
@zivkan Woops. Sorry for the confusion. Thank you for your keen eye!

**Comment by loic-sharma** [comment]
Hello, thank you for reporting this! The `nuget spec` command generates a .nuspec with an `iconUrl` (see https://github.com/NuGet/Home/issues/10400). I don't think we can update this documentation until this is fixed.
