### ISSUE TITLE
No explanation or documentation on how to extract .nupkg

### ISSUE THREAD

**Issue by yulayula16** [NuGet/docs.microsoft.com-nuget#1970]
As title states, No documentation what-so-ever on how to extract `.nupkg` archive files.

You try install something from a `*.nupkg` package file like so

```
nuget install MyPackage.nupkg -Source %cd% -OutputDirectory packages
```

but it'll just then return `Unable to find package 'MyPackage.nupkg` Nowhere in any of the documentation does it specify or say how to extract and install from a package file, because all it's trying to do is look online to download a `*.json` or `*.config` file that doesn't exist.

**Comment by rrelyea** [comment]
>nuget.exe install -help
usage: NuGet install packageId|pathToPackagesConfig [options]

so, it looks like neither of those options call for a pointer to the package itself.
go ahead and create a feed/source - using `nuget sources add -n myPackages -s c:\myPackages` or `dotnet nuget add source c:\myPackages -n myPackages`

**Comment by karann-msft** [comment]
@yulayula16 - please reopen the issue if the suggestion above doesn't work for you.
