### ISSUE TITLE
When will the additional project types (C++, & ASP.NET) be supported?

### ISSUE THREAD

**Issue by mdell-seradex** [NuGet/docs.microsoft.com-nuget#1973]
How do we find information on this and other issues or temporary limitations (i.e. not currently supported)?

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6a154e5f-436d-6297-ec05-4d134a2404f9
* Version Independent ID: 1c782e82-db9a-bf77-05ef-cd49374aee36
* Content: [Migrating from package.config to PackageReference formats](https://docs.microsoft.com/en-ca/nuget/consume-packages/migrate-packages-config-to-package-reference)
* Content Source: [docs/consume-packages/migrate-packages-config-to-package-reference.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/master/docs/consume-packages/migrate-packages-config-to-package-reference.md)
* Product: **nuget**
* GitHub Login: @karann-msft
* Microsoft Alias: **karann**

**Comment by karann-msft** [comment]
@mdell-seradex - certainly not by commenting on docs. file an issue on the Home repo - https://github.com/nuget/home/issues
