### ISSUE TITLE
Visual Studio 2019 is not mentioned as compatible with SemVer 2.0.0

### ISSUE THREAD

**Issue by Joe-Sewell-PreEmptive** [NuGet/docs.microsoft.com-nuget#1976]
Visual Studio 2017 version 15.3+ and Visual Studio 2015 with NuGet VSIX v3.6.0 are listed as compatible, but there is no mention of Visual Studio 2019.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7c462602-7e8f-2634-4006-3fadaa68ef45
* Version Independent ID: 7a6ec89f-55c5-2d49-6677-fcc87b0e40ac
* Content: [NuGet Package Version Reference](https://docs.microsoft.com/en-us/nuget/concepts/package-versioning#semantic-versioning-200)
* Content Source: [docs/concepts/Package-Versioning.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/master/docs/concepts/Package-Versioning.md)
* Product: **nuget**
* GitHub Login: @karann-msft
* Microsoft Alias: **karann**

**Comment by karann-msft** [comment]
@Joe-Sewell-PreEmptive - the "+" implies that all releases after VS 2017 15.3 support SemVer. The purpose of the "+" is to not have to call out every release explicitly.

**Comment by Joe-Sewell-PreEmptive** [comment]
Ah, I see. I had just glanced at the list and seen 2015 listed separately, so I assumed each major release would have been mentioned. Upon re-reading, I don't think any changes are necessary.
