### ISSUE TITLE
Example PowerShell commands no longer valid with PS 7

### ISSUE THREAD

**Issue by tmarkovski** [NuGet/docs.microsoft.com-nuget#1977]
Example PowerShell commands are no longer valid with PS 7

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: da26ad2b-38d5-acfb-d022-21ba06edad62
* Version Independent ID: 8a0410df-73e6-e92e-59f1-48d6402cdda2
* Content: [NuGet Find-Package PowerShell Reference](https://docs.microsoft.com/en-us/nuget/reference/ps-reference/ps-ref-find-package#feedback)
* Content Source: [docs/reference/ps-reference/ps-ref-find-package.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/master/docs/reference/ps-reference/ps-ref-find-package.md)
* Product: **nuget**
* GitHub Login: @karann-msft
* Microsoft Alias: **karann**

**Comment by karann-msft** [comment]
@tmarkovski - can you elaborate? Or better, help us with a PR :) (just click on the edit button at the top right of the page to get started)
![image](https://user-images.githubusercontent.com/16904420/78103895-e1e50400-73a2-11ea-9e16-a1b34bc5bcdc.png)

**Comment by zivkan** [comment]
The top of the docs says:

> Version 3.0+; this topic describes the command within the Package Manager Console in Visual Studio on Windows. For the generic PowerShell Find-Package command, see the PowerShell PackageManagement reference.

[Here is a link to PowerShell's Find-Package docs for PowerShell 7](https://docs.microsoft.com/en-us/powershell/module/packagemanagement/find-package?view=powershell-7)
