### ISSUE TITLE
packages.config reference is missing

### ISSUE THREAD

**Issue by NReilingh** [NuGet/docs.microsoft.com-nuget#198]
In order to use nuget outside the context of visual studio, you can use the CLI and manual modification of packages.config. However, there is no documentation for the schema of packages.config.

The [Project.json Reference](https://docs.microsoft.com/en-us/nuget/schema/project-json) indicates that project.json is meant to replace packages.config in NuGet 3.x for certain types of projects. But unless I am confused, my reading of this indicates that for other projects (or those of an unclassifiable nature), one must still use packages.config.

As an example of my use case, I am working on a database project in SQL Server Management Studio, and would like to use NuGet to pull down some build and development tools from the NuGet Gallery and a private feed. My project doesn't have a runtime or any frameworks; it produces SQL scripts that will be run on a database.

**Comment by kraigb** [comment]
@NReilingh This is now on https://docs.microsoft.com/en-us/nuget/schema/packages-config. Please review and close this issue if it's been addressed to your satisfaction. Thanks!

**Comment by NReilingh** [comment]
Woohoo! Thank you!
