### ISSUE TITLE
consuming disk space

### ISSUE THREAD

**Issue by Urgen-Dorjee** [NuGet/docs.microsoft.com-nuget#1981]
I have hybrid Hard Drive therefore C drive has very less space. I don't like VS2019 to save my nuget packages in folder(%userprofile%\.nuget\packages) rather i would like to configure it to a different internal drive, what is the way to do this?  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 71b49477-cafa-d7d4-76fe-83aff43a3f47
* Version Independent ID: 68d7a416-1397-8cf3-bead-e3cd328aca48
* Content: [How to manage the global packages, cache, temp folders in NuGet](https://docs.microsoft.com/en-us/nuget/consume-packages/managing-the-global-packages-and-cache-folders)
* Content Source: [docs/consume-packages/managing-the-global-packages-and-cache-folders.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/master/docs/consume-packages/managing-the-global-packages-and-cache-folders.md)
* Product: **nuget**
* GitHub Login: @karann-msft
* Microsoft Alias: **karann**

**Comment by zivkan** [comment]
@Urgen-Dorjee The documentation says this:

> Override using the NUGET_PACKAGES environment variable, the globalPackagesFolder or repositoryPath configuration settings (when using PackageReference and packages.config, respectively), or the RestorePackagesPath MSBuild property (MSBuild only). The environment variable takes precedence over the configuration setting.

So, if you set the `globalPackagesFolder` setting in your user-profile `nuget.config`, it should be used by all your projects that don't have their own `nuget.config` that override the setting.

Or you can set the `NUGET_PACKAGES` environment variable, which the docs say "takes precedence over the configuration setting".

**Comment by Urgen-Dorjee** [comment]
@zivkan Thanks for your reply, I would be more than happy to see if there is any example where i get more insight as I already explored what you have stated in the thread, I would not have been posted this issue had I known; how to configure or see the example through the docs. I could not get hold of it through the docs therefore i have posted this issue here. 

    Anyway thanks for your time and patience.
