### ISSUE TITLE
Delete sources seems not to be working

### ISSUE THREAD

**Issue by JPGRodrigues** [NuGet/docs.microsoft.com-nuget#1983]
Issuing a "nuget sources delete -Name MyName -Sources https://mydomainurl" is returning no error.
If a "nuget sources list" is issue after, source MyName still exists.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 300f4f85-f1df-d3c3-3792-c6af032db21f
* Version Independent ID: 388142d8-ce04-c2df-5e50-b150980e3a26
* Content: [NuGet CLI sources command](https://docs.microsoft.com/en-us/nuget/reference/cli-reference/cli-ref-sources#options)
* Content Source: [docs/reference/cli-reference/cli-ref-sources.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/master/docs/reference/cli-reference/cli-ref-sources.md)
* Product: **nuget**
* GitHub Login: @karann-msft
* Microsoft Alias: **karann**

**Comment by JPGRodrigues** [comment]
Got the error: to delete a source the command is "nuget sources remove -Name MyName -Sources https://mydomainurl".
But original error is not displaying any error message

**Comment by JonDouglas** [comment]
@JPGRodrigues The parameter `-Sources` is just `-Source`.

Additionally, the command is called `Remove`, not delete.

![image](https://user-images.githubusercontent.com/1288848/90181015-66925680-dd75-11ea-8422-8bfd9cede308.png)

Going to close this issue for now as it works as expected.
