### ISSUE TITLE
What does the command exactly do?

### ISSUE THREAD

**Issue by MikeChristensen** [NuGet/docs.microsoft.com-nuget#1984]
Is this command supposed to actually modified app.config and web.config files, or just spit out what redirects are needed to the console?  I tried running it in a solution with 40 projects, but it didn't actually modify anything..

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6e008921-f86c-1bb8-8078-58da69b8110d
* Version Independent ID: 5e7ce9e8-cef9-2a43-1c57-9ceca886bd34
* Content: [NuGet Add-BindingRedirect PowerShell Reference](https://docs.microsoft.com/en-us/nuget/reference/ps-reference/ps-ref-add-bindingredirect)
* Content Source: [docs/reference/ps-reference/ps-ref-add-bindingredirect.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/master/docs/reference/ps-reference/ps-ref-add-bindingredirect.md)
* Product: **nuget**
* GitHub Login: @karann-msft
* Microsoft Alias: **karann**

**Comment by JonDouglas** [comment]
@MikeChristensen The command is supposed to add a respective `<bindingRedirect>` to a respective config file. I believe this is done on the project level and not on the solution level. Thus you probably won't see anything as it requires a `-ProjectName` to be defined.
