### ISSUE TITLE
nuget.exe CLI works for SDK style project that target .NET standard 2.0

### ISSUE THREAD

**Issue by varunmankal** [NuGet/docs.microsoft.com-nuget#1988]
[Enter feedback here]
The docs says that dotnet CLI need to used to publish SDK style projects and nuget.exe CLI to publish non-SDK style projects to nuget.org . However, I was able to push SDK style project to nuget.org from nuget.exe CLI. Does it mean nuget.exe CLI supports SDK style projects as well ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c8a37c64-6dc3-56d9-f5cc-f0aedf7dea40
* Version Independent ID: f5e964c2-d858-43a2-0bda-15770a6aeb20
* Content: [Manage NuGet packages using the nuget.exe CLI](https://docs.microsoft.com/en-us/nuget/consume-packages/install-use-packages-nuget-cli#feedback)
* Content Source: [docs/consume-packages/install-use-packages-nuget-cli.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/master/docs/consume-packages/install-use-packages-nuget-cli.md)
* Product: **nuget**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by rrelyea** [comment]
in order to create a package for a project
- nuget.exe works on old projects.
- dotnet.exe pack works on sdk style projects.

once you have a nuget package (nupkg file), either `nuget.exe push` or `dotnet nuget push` work similarly.

so creating nuget packages require different tools depending on your project.
pushing (or publishing) the package can use either tool.

if you can tell us which page and give us a quote of the confusing text, we can improve the language.

**Comment by varunmankal** [comment]
Got it. Thanks for the quick response.

I would suggest to add an explicit statement that says either `nuget.exe push` or `dotnet nuget push` can be used to publish a package in this page: https://docs.microsoft.com/en-us/nuget/nuget-org/publish-a-package. 

In the same page, consider the section `Command line` where it says as follows:
`To push packages to nuget.org you must use nuget.exe v4.1.0 or above, which implements the required NuGet protocols. You also need an API key, which is created on nuget.org.`

I think this statement says that only nuget.exe can be used to push packages to nuget.org . However, dotnet CLI can also be used.

please correct me if i miss anything.
