### ISSUE TITLE
repositoryPath is not overridden by NUGET_PACKAGES environment variable

### ISSUE THREAD

**Issue by mrward** [NuGet/docs.microsoft.com-nuget#1989]
The information for repositoryPath looks wrong to me. It says `This setting is overridden by the NUGET_PACKAGES environment variable, which takes precedence.`

Looking at the NuGet source code and testing this locally this seems to be incorrect. NUGET_PACKAGES is only used for the global packages folder and not the folder used when restoring packages into the solution for a project that uses packages.config file.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0ea1390e-db36-6759-3095-ebab9d546fdb
* Version Independent ID: ca88d8c6-0515-a267-aac3-a508c54157ab
* Content: [nuget.config File Reference](https://docs.microsoft.com/en-us/nuget/reference/nuget-config-file#config-section)
* Content Source: [docs/reference/nuget-config-file.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/master/docs/reference/nuget-config-file.md)
* Product: **nuget**
* GitHub Login: @karann-msft
* Microsoft Alias: **karann**

**Comment by prasadu-microsoft** [comment]
This issue is still present and should be fixed (if not in functionality then at least in the doc).
