### ISSUE TITLE
Update Package Restore docs to align with new MSBuild based restore

### ISSUE THREAD

**Issue by ridomin** [NuGet/docs.microsoft.com-nuget#199]
The main page for [Package Restore](https://github.com/NuGet/docs.microsoft.com-nuget/blob/master/docs/Consume-Packages/Package-Restore.md#migrating-to-automatic-restore) should be updated to reflect new 4.x MSBuild integration. 

Describe when to  use `MSBuild /t:Restore` versus `Nuget.exe restore`.
Instructions to  acquire the recommended `NuGet.exe`  version for VS2017 projects.

**Comment by kraigb** [comment]
Done. Please review and close this issue.
