### ISSUE TITLE
MIssing information about PackageReference Update Attribute

### ISSUE THREAD

**Issue by sparkie108** [NuGet/docs.microsoft.com-nuget#1992]
I've seen cases where the Update attribute needs to be used instead of Include: 
&lt;PackageReference Update="xxx" Version="1.0"/&gt;
But it seems to be undocumented

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ff707668-94d6-25a5-9139-b18cc1b6b446
* Version Independent ID: 494847b9-4894-0beb-7ffa-39a2359999fa
* Content: [NuGet PackageReference format (package references in project files)](https://docs.microsoft.com/en-us/nuget/consume-packages/package-references-in-project-files#feedback)
* Content Source: [docs/consume-packages/Package-References-in-Project-Files.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/master/docs/consume-packages/Package-References-in-Project-Files.md)
* Product: **nuget**
* GitHub Login: @karann-msft
* Microsoft Alias: **karann**

**Comment by michal-ciechan** [comment]
Does anyone have any input on when Update needs to be used?

**Comment by zivkan** [comment]
This is an MSBuild feature: https://docs.microsoft.com/visualstudio/msbuild/item-element-msbuild?view=vs-2019#attributes-and-elements

It's used when the MSBuild evaluation already has an item with the same value, and you need to change "metadata" (xml attributes) of the item.  Basically, at the top of your csproj you `Inlucde` a package, and at the bottom of the file you want to `Update` it.

It's not commonly used as you can just set the right metadata when the item is defined (Included) in the first place. When your project imports lots of MSBuild props and targets files (either directly or through something like Directory.Build.props), then maybe you have a complex scenario where you'd want to update an existing package reference, but if your scenario is that complex, I hope you understand MSBuild well enough to deal with the complexity it brings.
