### ISSUE TITLE
NuGet Config needs examples of getting a value

### ISSUE THREAD

**Issue by donnie-msft** [NuGet/docs.microsoft.com-nuget#1994]
Reading this document, it says config values can be retrieved (Get value), but fails to show the syntax structure or an example of this. 
An example is, nuget config HTTP_PROXY, which I don't see how I could know that from this doc page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e92758db-8866-42b0-156d-7a7adedbbabb
* Version Independent ID: d49de222-1342-9e17-516b-5572c72a8181
* Content: [NuGet CLI config command](https://docs.microsoft.com/en-us/nuget/reference/cli-reference/cli-ref-config#feedback)
* Content Source: [docs/reference/cli-reference/cli-ref-config.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/master/docs/reference/cli-reference/cli-ref-config.md)
* Product: **nuget**
* GitHub Login: @karann-msft
* Microsoft Alias: **karann**

**Comment by JonDouglas** [comment]
@donnie-msft So what you're hoping for here is an example such as:

![image](https://user-images.githubusercontent.com/1288848/90179178-aefc4500-dd72-11ea-91ad-57614f68cc19.png)

Which shows using the respective "Get" value?

**Comment by donnie-msft** [comment]
That's one example. But you can also do  `-set anything=something` and then say
`nuget config anything` which will output `something`

**Comment by JonDouglas** [comment]
@donnie-msft Maybe we show both example types then or just one?

**Comment by donnie-msft** [comment]
I suggest adding some description under Usage that explains `nuget config anything` results in `something`. 

Then, yes, adding an example below would also be nice. Can show the resulting output with a // comment (I think that's how we do this in docs).
