### ISSUE TITLE
contentFiles unclear

### ISSUE THREAD

**Issue by gfkeogh** [NuGet/docs.microsoft.com-nuget#1995]
The section on contentFiles has strange grammar and the relationship between the &lt;contentFiles&gt; and &lt;files&gt; elements is unclear. The whole section really needs to be rewritten, and it should include a set of smaller realistic examples with combinations of the different elements. It should also be made clear in which project types or platforms the contentFiles feature does or does not work.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 06a19d7d-253d-f17f-6421-624c9867473d
* Version Independent ID: cc37eb17-f715-080c-7bfc-9eae868d50ba
* Content: [.nuspec File Reference for NuGet](https://docs.microsoft.com/en-us/nuget/reference/nuspec#feedback)
* Content Source: [docs/reference/nuspec.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/master/docs/reference/nuspec.md)
* Product: **nuget**
* GitHub Login: @karann-msft
* Microsoft Alias: **karann**

**Comment by datvm** [comment]
Yes I still cannot understand how it works at all. For example:

```
    <contentFiles>
      <files include="Assets\**\*.css" buildAction="AndroidAsset" />
    </contentFiles>
```

Does not pack anything at all for me.

**Comment by Martijn14** [comment]
Agree there is no clear example following the info the a. All the files I add as content file are copyet to the bin folder but not to the package in the package you even see that they are marked as  FileListAbsolute  in obj\Debug\netcoreapp3.1\projctXXX.proj.FileListAbsolute and not copied into the package.
