### ISSUE TITLE
Replace PackageTargetFallback section with the new AssetTargetFallback

### ISSUE THREAD

**Issue by kzu** [NuGet/docs.microsoft.com-nuget#1996]
Since that's apparently *deprecated* (see https://docs.microsoft.com/en-us/nuget/reference/errors-and-warnings/nu1003#solution). Related: https://github.com/dotnet/docs/issues/2816

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 099102e8-c320-ef50-6821-57519684dc98
* Version Independent ID: 1523dac4-419d-613d-2497-4062f9efd358
* Content: [NuGet pack and restore as MSBuild targets](https://docs.microsoft.com/en-us/nuget/reference/msbuild-targets#packagetargetfallback)
* Content Source: [docs/reference/msbuild-targets.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/master/docs/reference/msbuild-targets.md)
* Product: **nuget**
* GitHub Login: @karann-msft
* Microsoft Alias: **karann**

**Comment by nkolev92** [comment]
Dup of https://github.com/NuGet/docs.microsoft.com-nuget/issues/511
