### ISSUE TITLE
Docs page do not show the 'Tip' and 'Note' sections properly

### ISSUE THREAD

**Issue by anangaur** [NuGet/docs.microsoft.com-nuget#200]
Go to https://github.com/NuGet/docs.microsoft.com-nuget/blob/master/docs/Consume-Packages/Package-Restore.md

Look at the **Note** and **Tip** sections

**Comment by anangaur** [comment]
![image](https://cloud.githubusercontent.com/assets/14800916/23475679/1d2c3ec4-fe6d-11e6-9192-db137228a493.png)

**Comment by anangaur** [comment]
![image](https://cloud.githubusercontent.com/assets/14800916/23475695/2b3eb47e-fe6d-11e6-85e1-5f2eaccf5951.png)

**Comment by anangaur** [comment]
my bad :) I was looking at GitHub

**Comment by karann-msft** [comment]
:-)
