### ISSUE TITLE
Terms that should not be localized

### ISSUE THREAD

**Issue by JasonCard** [NuGet/docs.microsoft.com-nuget#2006]
This article contains attributes and property names that should not be localized and some of those are being over-localized by Machine Translation. It would be great if those terms can be blocked from localization by using either in-line code, or [no-loc custom syntax](https://review.docs.microsoft.com/en-us/help/contribute/markdown-reference?branch=master#non-localized-strings).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 099102e8-c320-ef50-6821-57519684dc98
* Version Independent ID: 1523dac4-419d-613d-2497-4062f9efd358
* Content: [NuGet pack and restore as MSBuild targets](https://docs.microsoft.com/en-us/nuget/reference/msbuild-targets#feedback)
* Content Source: [docs/reference/msbuild-targets.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/master/docs/reference/msbuild-targets.md)
* Product: **nuget**
* GitHub Login: @karann-msft
* Microsoft Alias: **karann**

**Comment by dominoFire** [comment]
nuspec reference table needs special strings to avoid translations on entry names
