### ISSUE TITLE
Inconsisten title and text

### ISSUE THREAD

**Issue by mladedav** [NuGet/docs.microsoft.com-nuget#2008]
Title says NU5500, Issue text talks about NU5000. Also note that NU5000 also exists with the same text.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b83566b7-9c89-933e-afb5-c8702bf7d3aa
* Version Independent ID: d9ccbbb8-a334-4780-cbbb-aa177ccc7cea
* Content: [NuGet Warning NU5500](https://docs.microsoft.com/en-us/nuget/reference/errors-and-warnings/nu5500#feedback)
* Content Source: [docs/reference/errors-and-warnings/NU5500.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/master/docs/reference/errors-and-warnings/NU5500.md)
* Product: **nuget**
* GitHub Login: @mishra14
* Microsoft Alias: **karann**

**Comment by JonDouglas** [comment]
@mladedav One is an error & one is a warning. These are catch-alls for nuget pack failures which we will work to expand in the future. I'll go ahead and update the text for NU5500 just to be consistent. Thanks for the report!

https://github.com/NuGet/docs.microsoft.com-nuget/pull/2130
