### ISSUE TITLE
Which variables can be used -- any variable, or only `TargetFramework`?

### ISSUE THREAD

**Issue by zspitz** [NuGet/docs.microsoft.com-nuget#2018]
[This](https://docs.microsoft.com/en-us/nuget/consume-packages/package-references-in-project-files#adding-a-packagereference-condition) is rather unclear:

&gt; You can use a condition to control whether a package is included, where conditions can use any MSBuild variable or a variable defined in the targets or props file. However, at presently, only the `TargetFramework` variable is supported.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ff707668-94d6-25a5-9139-b18cc1b6b446
* Version Independent ID: 494847b9-4894-0beb-7ffa-39a2359999fa
* Content: [NuGet PackageReference format (package references in project files)](https://docs.microsoft.com/en-us/nuget/consume-packages/package-references-in-project-files)
* Content Source: [docs/consume-packages/Package-References-in-Project-Files.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/master/docs/consume-packages/Package-References-in-Project-Files.md)
* Product: **nuget**
* GitHub Login: @karann-msft
* Microsoft Alias: **karann**

**Comment by mrlife** [comment]
I have the same question. Could "MSBuild variable" be linked to where those are listed out?

I found the one I was looking for (Env) but don't see it anywhere in the docs. Here is the comment where I found it: https://github.com/NuGet/Home/issues/8741#issuecomment-547220844
