### ISSUE TITLE
experience to migrate PC -> PR is bad if you have both PR + Packages.config -- PR might come from csproj, props/target, or directory.build.props.

### ISSUE THREAD

**Issue by georg-jung** [NuGet/docs.microsoft.com-nuget#2020]
Regarding https://github.com/NuGet/docs.microsoft.com-nuget/blob/master/docs/consume-packages/migrate-packages-config-to-package-reference.md there are currently three limitations listed. I tried migrating a project from packages.config that had a `Directory.Build.props` in a folder above (i.e. due to `nbgv install`). The migration assistant does not work in this case too. Temporarily removing the `Directory.Build.props` and migrating afterwards does work. Maybe this limitation deserves to be listed too as this can take some time to find but is really easy to get if it's listed. Additionally, the message I'm recieving (so, the MsgBox in Visual Studio) stating that it does not work links to the document above. What do you think?

**Comment by rrelyea** [comment]
Thanks for raising the issue...
Are you saying that you had some packagereferences defined in directory.build.props?
so you tried to migrate a csproj/packages.config based project, which also had a PackageReference?

**Comment by georg-jung** [comment]
I have a `Directory.Build.props` file, that adds i.e. nbgv, like this one: https://github.com/AArnott/Library.Template/blob/3c0c7dae0fe407097af6455adbfb4d6e8b8ba600/Directory.Build.props
In a folder underneath that root repo folder I had a csproj that was using packages.conf. So I was already using PackageRef on solution level but not on project level. In this scenario the automatic migration does fail. Temporarily renaming/moving the .props file (thus "disabling"/removing the solution level references) gets the migration working.

So:

> Are you saying that you had some packagereferences defined in directory.build.props?

Yes

> so you tried to migrate a csproj/packages.config based project, which also had a PackageReference?

Yes and no. It had a PackageReference inherited from the solution but not a direct one.

**Comment by rrelyea** [comment]
my guess is that you shouldn't follow @AArnott's pattern there, if you still have packages.config projects. NuGet uses logic to see if a project is packages.config or PackgeReference. If it finds any packagereferences when it evaluates the project (it cannot tell the difference between csproj or that props file) -- then it treats it as a packagereference project.

what that props file, is effectively turn every project in the solution into a packagereference based project. Does restore even work for the packages.config reference projects???

**Comment by georg-jung** [comment]
I understand that his template is made for more up to date projects. My file just looks similar but isn't publicly available, that's why I linked it.

VS does handle this scenario without problems, commandline doesn't (i.e. the NuGetCommand task in azure pipelines; that's why I stumbled upon this). That's why I wanted to migrate my csproj with packages.config in the first place. But, from a visual studio end-users point of view it could work like this (I hope that's not a special case of my local install):

* Use PackageReference in props
* Use packages.config in at least one csproj
* As long as you compile locally, everything works fine
* For some reason you want to migrate and use the context menu option
* You get an error, directing you to the docs linked above
* Those docs name three possibilities specifically, why you could get this error
* The real reason is a fourth possibility, that's not listed there. Because I thought this could be confusing, I opened this issue. I'm not saying the project set-up I started with was great from an architecture point of view, but I guess other people might run into this too...

**Comment by rrelyea** [comment]
Perhaps we should determine if the project has both packages.config and packagereference...and give a good error...including the possibility of the PR being added in the project, or a props/target that it includes, or a directory.build.props

**Comment by tmilnthorp** [comment]
I recently added the following ```!Exists('packages.config')``` condition to my Directory.Build to to exclude it. I submitted a defect, and NBGC has [included this into their code](https://github.com/dotnet/Nerdbank.GitVersioning/issues/533).
```xml
  <ItemGroup Condition="!Exists('packages.config')">
    <PackageReference Include="Nerdbank.GitVersioning">
      <Version>3.3.37</Version>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
  </ItemGroup>
```
Originally it was breaking the command-line ```nuget.exe restore```, which is now fixed. However migration is still broken. Interestingly, so is ```Update-Package```. ```nuget.exe update``` does work.

I'm guessing the migration wizard uses something along the lines of ```Update-Package``` to check if it's possible or not?

**Comment by tmilnthorp** [comment]
FYI I've created an issue here [also](https://developercommunity2.visualstudio.com/t/NuGet-actions-are-broken-for-a-csproj-t/1257632?port=1025&fsid=051c09d2-e25f-419a-bd83-4b6a9cba9930&entry=myactivity).
