### ISSUE TITLE
Please see my comments on #1813

### ISSUE THREAD

**Issue by toddalbers** [NuGet/docs.microsoft.com-nuget#2021]
Please see my comments on [#1813] (https://github.com/NuGet/docs.microsoft.com-nuget/issues/1813) for a different possible workaround.

Some additional feedback.  The solution listed above here on NU1605 does not say "where" to add the package reference and in what situations.  What file?  What section in the file?  Is that for Blazor Server?  Blazor WebAssembly?  What if you have both Blazor Server and Blazor WebAssembly in the same solution referencing the same output class project? (Like I found myself with in #1813)?  The solution above doesn't seem to work for me when I try it in all the places I think you mean.  But, maybe if I split out the projects so the solution isn't mixing apples (Server) with oranges (WebAssembly), it might.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0960d68b-f164-4e7e-5cdb-ad70e6f9de89
* Version Independent ID: 82b4d896-1d52-ce2e-c2ff-f76f4308ac56
* Content: [NuGet Warning NU1605](https://docs.microsoft.com/en-us/nuget/reference/errors-and-warnings/nu1605)
* Content Source: [docs/reference/errors-and-warnings/NU1605.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/master/docs/reference/errors-and-warnings/NU1605.md)
* Product: **nuget**
* GitHub Login: @zhili1208
* Microsoft Alias: **lzhi**

**Comment by JonDouglas** [comment]
Closing for response in #1813
