### ISSUE TITLE
Update Feature availability table

### ISSUE THREAD

**Issue by MartinZid** [NuGet/docs.microsoft.com-nuget#2025]
Is feature availability correct in regards to https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-nuget-add-source?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3460a9b2-3b49-1cda-add2-14d26e217716
* Version Independent ID: 95b91106-faff-c7f6-3699-94d643b5cf73
* Content: [Installing NuGet client tools](https://docs.microsoft.com/en-us/nuget/install-nuget-client-tools#feedback)
* Content Source: [docs/install-nuget-client-tools.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/master/docs/install-nuget-client-tools.md)
* Product: **nuget**
* GitHub Login: @karann-msft
* Microsoft Alias: **karann**

**Comment by JonDouglas** [comment]
Although you can manage sources, you cannot get/set your NuGet configuration with the `dotnet` CLI today.

i.e. https://docs.microsoft.com/en-us/nuget/reference/cli-reference/cli-ref-config

So as it stands today, it it technically unsupported to `Manage NuGet Configuration` given you can only do a handful of operations and not all.

When we support all NuGet.exe commands in the `dotnet` CLI, we will ensure this table is updated with each supported command. Thanks for filing an issue!
