### ISSUE TITLE
Fixed NU5048 warning using icon element and now I can't publish symbol package (snupkg)

### ISSUE THREAD

**Issue by petrsnd** [NuGet/docs.microsoft.com-nuget#2027]
I noticed in my builds that I was getting NU5048 telling me that my package icon was using the older iconUrl element rather than the icon element in my nuspec file.  I followed the instructions for replacing iconUrl with icon in my nuspec, which included:

- added a files element containing a file element that add my icon file to the package
- referenced the icon file from the metadata using the icon element
- converted my icon from ico to png (discovered this the hard way when nuget.org refused my ico file, should also be documented)

The problem now is that when I generate my nuget package and the accompanying symbols package, i.e. `nuget pack -Symbols -SymbolPackageFormat snupkg`, the symbol package can no longer be pushed to nuget.org.  This is because the symbols package (snupkg) now contains a file that is not a `.pdb`.

I get the following error:
```
Error publishing package. NuGet server returned 400: Invalid file found in the uploaded package. Symbols packages should only contain '.pdb' files.
```

I'm not sure this is the right place to file this issue, but maybe this is a doc error and there is a better way to do what I want to do.

Additional Info:
The broken package is a net462 library built on top of another package which is a netstandard2.0 SDK.  The source for the nuspec is located here: https://github.com/OneIdentity/SafeguardDotNet/blob/master/SafeguardDotNet.GuiLogin/SafeguardDotNet.GuiLogin.nuspec

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 06a19d7d-253d-f17f-6421-624c9867473d
* Version Independent ID: cc37eb17-f715-080c-7bfc-9eae868d50ba
* Content: [.nuspec File Reference for NuGet](https://docs.microsoft.com/en-us/nuget/reference/nuspec)
* Content Source: [docs/reference/nuspec.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/master/docs/reference/nuspec.md)
* Product: **nuget**
* GitHub Login: @karann-msft
* Microsoft Alias: **karann**

**Comment by ewingjm** [comment]
Hi, @petrsnd. I did a Google search for that same error message and this was the only result that it returned. I'm sure we're not the only ones that have had this same issue. 

For me, it was not only the icon but also several content files and build targets. Did you find a resolution? I ended up creating this PowerShell script which I call after doing `nuget pack`.

```powershell
[CmdletBinding()]
param (
    [Parameter(Mandatory = $true)]
    [String]
    $SymbolPackageDirectory
)

Add-Type -Assembly System.IO.Compression.FileSystem

Get-ChildItem "$SymbolPackageDirectory/*" -Include *.snupkg | ForEach-Object {
    Write-Host "Removing invalid files from $($_.Name)"
    $oldName = [IO.Path]::GetFileName($_.Name)
    $newName = [IO.Path]::GetFileName([IO.Path]::ChangeExtension($_.Name, "zip"))
    $zipFile = Rename-Item -Path $_.FullName -NewName $newName -PassThru
    $zip = [System.IO.Compression.ZipFile]::Open($zipFile.FullName, [IO.Compression.ZipArchiveMode]::Update)
    
    $allowedExtensions = @('.pdb', '.nuspec', '.xml', '.psmdcp', '.rels', '.p7s')
    ($zip.Entries | Where-Object { $allowedExtensions -notcontains [IO.Path]::GetExtension($_.Name) }) | ForEach-Object { 
        Write-Host "Removing $($_.Name)"
        $_.Delete() 
    }
    
    $zip.Dispose()
    
    Rename-Item -Path $zipFile.FullName -NewName $oldName
}
```

I took the allowed extensions from https://docs.microsoft.com/en-us/nuget/create-packages/symbol-packages-snupkg#nugetorg-symbol-package-constraints.
