### ISSUE TITLE
Error en Visual Studio

### ISSUE THREAD

**Issue by Zeref038** [NuGet/docs.microsoft.com-nuget#2030]
xamarin error domain=nsurlerrordomain code=-1001 "se ha agotado el tiempo de espera." userinfo={nsunderlyingerror=0x7f9ee065a250 {error domain=kcferrordomaincfnetwork code=-1001 "(null)" userinfo={_kcfstreamerrorcodekey=-2102, _kcfstreamerrordomainkey=4}}, nserrorfailingurlstringkey=https://api.nuget.org/v3-flatcontainer/xamarin.android.support.annotations/index.json, nserrorfailingurlkey=https://api.nuget.org/v3-flatcontainer/xamarin.android.support.annotations/index.json, _kcfstreamerrordomainkey=4, _kcfstreamerrorcodekey=-2102, nslocalizeddescription=se ha agotado el tiempo de espera.} get https://api.nuget.org/v3-flatcontainer/xamarin.android.support.annotations/index.json en mac

**Comment by JonDouglas** [comment]
We're sorry, we don't have enough information to assist in your issue. If you are still encountering this problem, please look through our wiki on how to [submit a bug or suggestion](https://github.com/NuGet/Home/wiki/Submitting-Bugs-and-Suggestions).
