### ISSUE TITLE
Document configure max http request in NuGet

### ISSUE THREAD

**Issue by nkolev92** [NuGet/docs.microsoft.com-nuget#2033]
See spec https://github.com/NuGet/Home/wiki/Config-Max-Http-Request-In-NuGet

See https://github.com/NuGet/Home/issues/4538

RelateD:https://github.com/NuGet/docs.microsoft.com-nuget/issues/776

Example:

```xml
<config>
    <add key="maxHttpRequestsPerSource" value="16" />
</config>
```

**Comment by fotto1** [comment]
Thanks for the hotfix @nkolev92 , I will try this. Anyway will a proper handling of 429 ever implemented?

I working for a large organization and will not the only one with this problem. Also other companies will face same issue when they using nuget package manager which follow HTTP Protocol Version 3
