### ISSUE TITLE
Call out limit of description field and call out embedded README when it is available

### ISSUE THREAD

**Issue by michael-hawker** [NuGet/docs.microsoft.com-nuget#2035]
There's a character limit on the description field (I think it's 4000, but I don't remember, thus why I was coming here). This should be documented, as VS doesn't tell you about it, so you only hit once you go to upload to NuGet.org.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 06a19d7d-253d-f17f-6421-624c9867473d
* Version Independent ID: cc37eb17-f715-080c-7bfc-9eae868d50ba
* Content: [.nuspec File Reference for NuGet](https://docs.microsoft.com/en-us/nuget/reference/nuspec#feedback)
* Content Source: [docs/reference/nuspec.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/master/docs/reference/nuspec.md)
* Product: **nuget**
* GitHub Login: @karann-msft
* Microsoft Alias: **karann**

**Comment by anangaur** [comment]
Irrespective of a seemingly bigger limit, we should recommend this to be a short description, especially with README feature (when it goes live)

**Comment by joelverhagen** [comment]
Okay, I'll leave this issue open and we can add the embedded readme note when it is fully available.

**Comment by michael-hawker** [comment]
@anangaur VS should have an analyzer or something to warn you when you hit this limit still though, as otherwise it only fails when uploading which is undiscoverable and nerve-wracking if you're pushing a bunch of packages up in a CI for a release.

**Comment by anangaur** [comment]
/cc: @JonDouglas as these may sense to make into the warnings at the time of pack, as part of package scoring story.

**Comment by michael-hawker** [comment]
This is still something that should have a better warning/analyzer around to prevent folks from getting confused or run into rejection on upload as part of another process.
