### ISSUE TITLE
Package metadata element names are case-insensitive

### ISSUE THREAD

**Issue by nkolev92** [NuGet/docs.microsoft.com-nuget#2039]
@joelverhagen commented on [Tue, 19 Nov 2019 06:09:53 GMT](https://github.com/NuGet/Home/issues/8838)
Consider the case of the hand-edited .nuspec file (because no one ever does that, right?) where someone mistypes the metadata name and provides and incorrect case. **Should this be supported officially?**

Example. The [BlogML.Core 1,0.0](https://www.nuget.org/packages/BlogML.Core/1.0.0) package on nuget.org has `<ProjectUrl>` in the .nuspec instead of `<projectUrl>` which is the official element name.

![image](https://user-images.githubusercontent.com/94054/69120813-6ae04c00-0a4f-11ea-92a2-e6eaef7ff40d.png)

XML is case sensitive right? Well, yes, but the majority of cases in the official NuGet experiences accept this funky metadata element without blinking an eye:

## 1st Party

- ✔️ nuget.org: [link](https://www.nuget.org/packages/BlogML.Core/1.0.0)
- ✔️ V2 non-hijacked: [link](https://www.nuget.org/api/v2/Packages()?$filter=Id%20eq%20%27BlogML.Core%27%20and%20NormalizedVersion%20eq%20%271.0.0%27%20and%201%20eq%201&$select=ProjectUrl)
- ✔️ V2 hijacked: [link](https://www.nuget.org/api/v2/Packages(Id='BlogML.Core',Version='1.0.0'))
  - This is the thing ready by VS package manager UI on the V2 feed URL
- ❌ Package metadata resource, a.k.a. registration: [link](https://api.nuget.org/v3/registration4/blogml.core/index.json)
  - This is the thing read by VS package manager UI on the V3 feed URL
  - Note this will likely change with my Catalog2Registration rebuild due to [Newtonsoft.Json#815](https://github.com/JamesNK/Newtonsoft.Json/issues/815)
- ✔️ Search: [link](https://azuresearch-usnc.nuget.org/query?q=packageid:BlogML.Core)
- ✔️ Package manager UI on local feed
  - ![image](https://user-images.githubusercontent.com/94054/69120227-e7722b00-0a4d-11ea-8db8-938026ee48a4.png)

## 3rd Party

- ❌ NuGet Package Explorer UI
- ❌ NuGet Package Explorer > Edit > Edit Metadata Source (???)

## This is a good idea right?

My vote is **_NO_**, **no**, **No**, **nO**! We should not support this officially.

In fact I think we should explicitly state it is not supported and any implementation that treats metadata names as case-insensitive strings is doing so at it's own peril. For example, what's the defined behavior when there are two metadata fields with the same name but different case (e.g. `<id>` and `<ID>`). Life's too short!

Fortunately, nuget.org rejects packages with multiple ID and version casings defined so I think we're out of scary land -- just living in crazy land. NBD.

## Okay, who's guilty of this cardinal sin?

No shame, we all hack around with .nupkgs. But the ones I've found on nuget.org are:

- StaticProxy.Fody 1.0.146-GenericMethods has "Summary" not "summary".
  - https://api.nuget.org/v3/catalog0/data/2019.10.02.07.14.49/staticproxy.fody.1.0.146-genericmethods.json
- Boolli 1.0.0 has "licenseurl" not "licenseUrl".
  - https://api.nuget.org/v3/catalog0/data/2019.01.02.03.56.37/boolli.1.0.0.json
- BlogML.Core 1.0.0 has "ProjectUrl" not "projectUrl".
  - https://api.nuget.org/v3/catalog0/data/2019.01.02.13.49.28/blogml.core.1.0.0.json
- Confuser.MSBuild 2.0.0-alpha-0191 has "iconURL" not "iconUrl".
  - https://api.nuget.org/v3/catalog0/data/2019.04.18.10.29.30/confuser.msbuild.2.0.0-alpha-0191.json
- SmartSeeder 0.0.1, 1.0.0-rc1-beta, 1.0.0-rc1-preview have "Language" not "language".
  - https://api.nuget.org/v3/catalog0/data/2018.12.19.07.07.41/smartseeder.0.0.1.json
  - https://api.nuget.org/v3/catalog0/data/2018.12.19.07.07.41/smartseeder.1.0.0-rc1-beta.json
  - https://api.nuget.org/v3/catalog0/data/2018.12.19.07.07.31/smartseeder.1.0.0-rc1-preview.json

🍻

**Comment by nkolev92** [comment]
@xavierdecoster commented on [Tue, 19 Nov 2019 08:53:23 GMT](https://github.com/NuGet/Home/issues/8838#issuecomment-555399344)
> My vote is NO, no, No, nO! We should not support this officially.

🥇

**Comment by nkolev92** [comment]
@nkolev92 commented on [Mon, 18 May 2020 20:27:11 GMT](https://github.com/NuGet/Home/issues/8838#issuecomment-630417570)
@joelverhagen 

Do you have a list of all the packages with bad metadata?

**Comment by nkolev92** [comment]
@joelverhagen commented on [Mon, 18 May 2020 20:30:06 GMT](https://github.com/NuGet/Home/issues/8838#issuecomment-630419033)
See the end of the issue. There is a list of package IDs, versions, and specific metadata properties that are bad.

**Comment by nkolev92** [comment]
@nkolev92 commented on [Mon, 18 May 2020 21:09:12 GMT](https://github.com/NuGet/Home/issues/8838#issuecomment-630436411)
@joelverhagen 

I should've asked a better question. 

Are those packages samples or all packages?

**Comment by nkolev92** [comment]
@joelverhagen commented on [Mon, 18 May 2020 21:09:52 GMT](https://github.com/NuGet/Home/issues/8838#issuecomment-630436716)
All, at the time of filing the issue.

**Comment by nkolev92** [comment]
@nkolev92 commented on [Mon, 18 May 2020 21:16:49 GMT](https://github.com/NuGet/Home/issues/8838#issuecomment-630439790)
I think it makes sense to say that package metadata is case sensitive.

**Comment by anangaur** [comment]
I think we will be making life of package authors tougher by stating package metadata fields are case-sensitive. I do not find any requirement to make them case-sensitive. Package ID is an Id, be it id or ID 😉 

/cc: @JonDouglas

**Comment by nkolev92** [comment]
We discussed this in triage so cc'ing @zkat @aortiz-msft 

> I think we will be making life of package authors tougher by stating package metadata fields are case-sensitive

Our tooling is already case-sensitive. 
We're not changing anything. We're just clarifying that in the docs to avoid confusion for any protocol implementer. 

For example, the below nuspec, won't pack today, with:

```
The element 'metadata' in namespace 'http://schemas.microsoft.com/packaging/2010/07/nuspec.xsd' has invalid child element 'Version' in namespace 'http://schemas.microsoft.com/packaging/2010/07/nuspec.xsd'. List of possible elements expected: 'version, contentFiles, copyright, frameworkReferences, developmentDependency, owners, iconUrl, language, license, frameworkAssemblies, licenseUrl, projectUrl, packageTypes, references, title, repository, authors, summary, requireLicenseAcceptance, tags, dependencies, description, serviceable, releaseNotes, icon' in namespace 'http://schemas.microsoft.com/packaging/2010/07/nuspec.xsd'. This validation error occurred in a 'Version' element.
```

There are no functional changes, so I don't believe we're making the experience worse.  

```xml
<?xml version="1.0" encoding="utf-8"?>
<package >
  <metadata>
    <id>Package</id>
    <Version>1.0.0</Version>
    <authors>Roki2</authors>
    <requireLicenseAcceptance>false</requireLicenseAcceptance>
    <license type="expression">MIT</license>
    <projectUrl>http://project_url_here_or_delete_this_line/</projectUrl>
    <iconUrl>http://icon_url_here_or_delete_this_line/</iconUrl>
    <description>Package description</description>
    <releaseNotes>Summary of changes made in this release of the package.</releaseNotes>
    <copyright>$copyright$</copyright>
    <tags>Tag1 Tag2</tags>
    <dependencies>
      <group targetFramework=".NETStandard2.1">
        <dependency id="SampleDependency" version="1.0.0" />
      </group>
    </dependencies>
  </metadata>
</package>
```

**Comment by JonDouglas** [comment]
We just need to be clear that if a user sees a failure/warning because of case-sensitivity in their XML, that they know how to fix it. I think the note added in https://github.com/NuGet/docs.microsoft.com-nuget/pull/2127 resolves this issue by adding the clarification.

XML in general is case sensitive, `<Version>` is different than `<version>`. Sure we could make this a better experience, but then we go against generalizations of XML such as using lowerCamelCase for element/attribute/enumerated names. Although the providers will generally accept the input the same i.e. `<Version>` will be treated the same as `<version>`, we should honor that this is XML as much as we can even though people have not used proper casing or conventions in the past.

I'm closing this for now given we have a note describing this. If we should reconsider supporting case-insensitive elements/attributes/etc, we should open up a new issue.
