### ISSUE TITLE
update docs for `nuget.exe update [-dependencyVersion Lowest | Highest | HighestMinor | HighestPatch | Ignore]`

### ISSUE THREAD

**Issue by rrelyea** [NuGet/docs.microsoft.com-nuget#2041]
Add docs to cover community contribution adding dependencyVersion parameter - from https://github.com/nuget/home/issues/7694

appears to already be available in `nuget.exe install` and documented: https://docs.microsoft.com/nuget/reference/cli-reference/cli-ref-install

/cc @zivkan @thomassmeets

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 78907d44-6785-f997-9b5c-ca57e85512b4
* Version Independent ID: 868bd2cc-1c52-f168-f2aa-4541f256e23a
* Content: [NuGet CLI update command](https://docs.microsoft.com/en-us/nuget/reference/cli-reference/cli-ref-update?source=docs)
* Content Source: [docs/reference/cli-reference/cli-ref-update.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/master/docs/reference/cli-reference/cli-ref-update.md)
* Product: **nuget**
* GitHub Login: @karann-msft
* Microsoft Alias: **karann**

**Comment by JonDouglas** [comment]
There's additionally https://docs.microsoft.com/en-us/nuget/reference/ps-reference/ps-ref-update-package which seems to have most of this documented as well but just needs added over to nuget update:

https://docs.microsoft.com/en-us/nuget/reference/cli-reference/cli-ref-update
