### ISSUE TITLE
Prevent updates to package versions from affecting a specific project

### ISSUE THREAD

**Issue by logiclrd** [NuGet/docs.microsoft.com-nuget#2048]
When using `<PackageReference>`, is there an equivalent to the `allowedVersions` attribute on `<package>` references in packages.config files? I have a solution where just one project has to be kept on an older version of a dependency because the only reason it exists is to do testing against that older version specifically. Is there a way to update the solution to reference a new version but _automatically_ hold that one project back?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ff707668-94d6-25a5-9139-b18cc1b6b446
* Version Independent ID: 494847b9-4894-0beb-7ffa-39a2359999fa
* Content: [NuGet PackageReference format (package references in project files)](https://docs.microsoft.com/en-us/nuget/consume-packages/package-references-in-project-files)
* Content Source: [docs/consume-packages/Package-References-in-Project-Files.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/master/docs/consume-packages/Package-References-in-Project-Files.md)
* Product: **nuget**
* GitHub Login: @karann-msft
* Microsoft Alias: **karann**

**Comment by logiclrd** [comment]
:-(

**Comment by zivkan** [comment]
no, it's not possible currently. Please 👍  this issue: https://github.com/NuGet/Home/issues/6566
