### ISSUE TITLE
Severity	Code	Description	Project	File	Line	Suppression State Warning	NU1701	Package 'EO.WebBrowser 20.1.45' was restored using '.NETFramework,Version=v4.6.1, .NETFramework,Version=v4.6.2, .NETFramework,Version=v4.7, .NETFramework,Version=v4.7.1, .NETFramework,Version=v4.7.2, .NETFramework,Version=v4.8' instead of the project target framework '.NETCoreApp,Version=v3.1'. This package may not be fully compatible with your project.	JsonProduct	C:\Users\i\source\repos\JsonProduct\JsonProduct\JsonProduct.csproj	1	

### ISSUE THREAD

**Issue by TaraEng** [NuGet/docs.microsoft.com-nuget#2053]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 377ae860-386f-149f-c5e0-410d3aa89dbc
* Version Independent ID: 2b145147-fd3f-d1aa-2694-071a31542d9a
* Content: [NuGet Warning NU1701](https://docs.microsoft.com/en-us/nuget/reference/errors-and-warnings/nu1701?f1url=https%3A%2F%2Fmsdn.microsoft.com%2Fquery%2Fdev16.query%3FappId%3DDev16IDEF1%26l%3DEN-US%26k%3Dk(NU1701)%26rd%3Dtrue%26f%3D255%26MSPPError%3D-2147217396)
* Content Source: [docs/reference/errors-and-warnings/NU1701.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/master/docs/reference/errors-and-warnings/NU1701.md)
* Product: **nuget**
* GitHub Login: @zhili1208
* Microsoft Alias: **lzhi**

**Comment by zivkan** [comment]
Closing as there's not question or feedback. Please provide details if you have a question.
