### ISSUE TITLE
dotnet nuget command

### ISSUE THREAD

**Issue by redwolf2** [NuGet/docs.microsoft.com-nuget#2055]
Using `.NET Core SDK (3.1.300)`, the command `dotnet nuget locals all --clear` only worked for me

This did not work:

- `dotnet locals all --clear`
- `nuget locals all --clear`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 906d0438-0338-0167-3a38-d213ee187ddb
* Version Independent ID: b558fa0c-f549-1e6a-c2db-fd2e6a2351be
* Content: [Troubleshooting NuGet Package Restore in Visual Studio](https://docs.microsoft.com/en-us/nuget/consume-packages/package-restore-troubleshooting)
* Content Source: [docs/consume-packages/Package-restore-troubleshooting.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/master/docs/consume-packages/Package-restore-troubleshooting.md)
* Product: **nuget**
* GitHub Login: @karann-msft
* Microsoft Alias: **karann**

**Comment by zivkan** [comment]
@redwolf2 thanks for reporting this. I created a PR to fix the `dotnet nuget ...` example.

`nuget.exe` uses PowerShell style single `-` for arguments, so perhaps that was the cause why it didn't work for you. Checking the docs, it already uses a single `-` for `-clear`.
