### ISSUE TITLE
Microsoft automatically change the browserbackground to black and text are blue, can't read. 

### ISSUE THREAD

**Issue by larachen** [NuGet/docs.microsoft.com-nuget#2064]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3269728c-1df2-90c2-5b4d-202d7fd7d219
* Version Independent ID: 43b9d30b-1757-10bd-8480-f82e0f07d5d6
* Content: [Install and use a NuGet package in Visual Studio for Mac](https://docs.microsoft.com/en-us/nuget/quickstart/install-and-use-a-package-in-visual-studio-mac)
* Content Source: [docs/quickstart/install-and-use-a-package-in-visual-studio-mac.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/master/docs/quickstart/install-and-use-a-package-in-visual-studio-mac.md)
* Product: **nuget**
* GitHub Login: @jmatthiesen
* Microsoft Alias: **jomatthi**

**Comment by zivkan** [comment]
There is a "theme" buttom at the bottom of the page where you can change the colour theme of the page. To provide feedback on the docs site, use the "Site feedback" link at the bottom of the page, which will take you here: https://aka.ms/sitefeedback

Closing this as it's not a NuGet docs issue.
