### ISSUE TITLE
No information for VS2012

### ISSUE THREAD

**Issue by Nighed** [NuGet/docs.microsoft.com-nuget#2074]
There is no information on where to download/see version information for Nuget on VS2012 - it's not referenced in the provided link (https://dist.nuget.org/index.html) 

(was looking for official documentation on the latest version of nuget that is available for VS2012)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3460a9b2-3b49-1cda-add2-14d26e217716
* Version Independent ID: 95b91106-faff-c7f6-3699-94d643b5cf73
* Content: [Installing NuGet client tools](https://docs.microsoft.com/en-us/nuget/install-nuget-client-tools)
* Content Source: [docs/install-nuget-client-tools.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/master/docs/install-nuget-client-tools.md)
* Product: **nuget**
* GitHub Login: @karann-msft
* Microsoft Alias: **karann**

**Comment by JonDouglas** [comment]
Unfortunately, VS 2012 is over 8 years old & the last service update was in 2015. NuGet is not covered by Visual Studio servicing:

https://docs.microsoft.com/en-us/visualstudio/releases/2019/servicing#components-not-covered-by-visual-studio-servicing

Your best bet is to obtain the oldest version available on that site around the 2015 timeframe i.e. v2.8.6

You can also check out https://github.com/NuGet/NuGet2 which may have some details for older versions.

It's recommended that for the time being, you update to the latest version of Visual Studio that is supported by NuGet.
