### ISSUE TITLE
Document NuGet tooling auth on docker 

### ISSUE THREAD

**Issue by nkolev92** [NuGet/docs.microsoft.com-nuget#2077]
See : https://github.com/dotnet/dotnet-docker/blob/master/documentation/scenarios/nuget-credentials.md

See: https://github.com/dotnet/dotnet-docker/pull/2032

**Comment by zivkan** [comment]
I was asked to document this a while ago, but there's always something more important to work on. I'll get to it eventually.

Currently, the recommendation will be to use .NET's built-in container support: https://devblogs.microsoft.com/dotnet/announcing-builtin-container-support-for-the-dotnet-sdk/

For people who are determined to restore within a docker container, dotnet's docker team have docs: https://github.com/dotnet/dotnet-docker/blob/main/documentation/scenarios/nuget-credentials.md
