### ISSUE TITLE
Merging packages

### ISSUE THREAD

**Issue by frankabbruzzese** [NuGet/docs.microsoft.com-nuget#2079]
Is there a way to merge a package with one or more of its dependencies with the CLI interface or programmatically? If not is there some SDK functionality one can use for this task?
I searched in the [documentation index](https://docs.microsoft.com/en-us/nuget/) but I have found nothing.

**Comment by anangaur** [comment]
Can you expand a bit on your scenario? Are you looking for the following?

> Feature : Allow project reference DLLs to be added to the parent nupkg for pack target like IncludeReferencedProjects in nuget.exe [#3891](https://github.com/NuGet/Home/issues/3891)?

**Comment by nkolev92** [comment]
Hey @frankabbruzzese 

There's currently no built in functionality to satisfy your scenario. 

We can consider moving this to the Home repo as a feature ask. 
WYT @anangaur @JonDouglas 

I think there's something to be said about multiple assemblies in a package as part of the package quality index work, but I couldn't find the equivalent issue to link.
