### ISSUE TITLE
nuget build?

### ISSUE THREAD

**Issue by Leon99** [NuGet/docs.microsoft.com-nuget#2081]
> In general, Properties should be the same that were used during the corresponding `nuget build`, in order to avoid potentially strange behavior.

What does that mean? What is `nuget build`?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d85bd49a-f83d-7588-5c70-edad5270c0f0
* Version Independent ID: 11cc9edc-4803-c768-5cdd-25c9b41ec8d3
* Content: [NuGet CLI pack command](https://docs.microsoft.com/en-us/nuget/reference/cli-reference/cli-ref-pack)
* Content Source: [docs/reference/cli-reference/cli-ref-pack.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/master/docs/reference/cli-reference/cli-ref-pack.md)
* Product: **nuget**
* GitHub Login: @karann-msft
* Microsoft Alias: **karann**

**Comment by zivkan** [comment]
The word nuget shouldn't have been included, and it shouldn't have been in a code block to imply that it was a command line argument.

Basically it means that pack should use the same properties as your command line build for your project. Eg, if you use `msbuild /p:MyProperty=MyValue`, then ideally you should use `nuget pack -Properties MyProperty=MyValue`.

I'll create a PR to update the page.
