### ISSUE TITLE
Stop deleting issues

### ISSUE THREAD

**Issue by JakeSays** [NuGet/docs.microsoft.com-nuget#2082]
There are references to document issues out in the wild, and it's really frustrating to click on one and get nothing. Makes it hard to understand code with commends like:
`// See https://github.com/NuGet/docs.microsoft.com-nuget/issues/543#issue-270039223`
that document why code was written as it was.

So.. please stop deleting issues. It is a highly unusual thing to do.

**Comment by anangaur** [comment]
Thanks for reaching out on this topic. While not sure why this issue was deleted, acknowledge this is highly unusual. We will be more careful in future (ideally should not be deleting issues).
