### ISSUE TITLE
Wrong information about floating notation *

### ISSUE THREAD

**Issue by ilya-spv** [NuGet/docs.microsoft.com-nuget#2088]
The documentation is quite vague about how floating notation works. Additionally it seems that the information provided is partially wrong.

My understanding after some testing is that e.g. `2.*` with existing version 2.0.0 and 2.0.1 means "exactly 2.0.1", that is: 2.0.0 is not allowed. I have tried to install version 2.0.0 explicitly and it did not work with `2.*` constraint.

I don't really know if it is meant to be like that as depending on the top available dependency would mean that consuming projects would always have to update as as soon a new version of dependency pops up, the old one is not allowed anymore (unless this * notation is used only during build time, which still means every new version of our package will force user to update to the latest available dependency as well).

It would be nice if more information about how * works would be provided on this page. Additionally it seems there is an error in here:

```xml
<!-- Accepts any 6.x.y version. -->
<PackageReference Include="ExamplePackage" Version="6.*" />
<PackageReference Include="ExamplePackage" Version="[6,7)" />
```
From what I can see it does not work like that. 6.* is not the same as [6,7) and it does not accept any 6.x.y version, but only highest available

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7c462602-7e8f-2634-4006-3fadaa68ef45
* Version Independent ID: 7a6ec89f-55c5-2d49-6677-fcc87b0e40ac
* Content: [NuGet Package Version Reference](https://docs.microsoft.com/en-us/nuget/concepts/package-versioning)
* Content Source: [docs/concepts/Package-Versioning.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/master/docs/concepts/Package-Versioning.md)
* Product: **nuget**
* GitHub Login: @karann-msft
* Microsoft Alias: **karann**

**Comment by JonDouglas** [comment]
We should definitely document the differences between floating & interval notation. For example:

Floating notation = Satisfies highest available.
Interval notation = Satisfies first available.

@ilya-spv Do you by chance have some other suggestions here? You mentioned documenting non-floating notation such as `2.` for better documentation around minimal versions.

**Comment by ilya-spv** [comment]
I don't have any other specific suggestions apart from documenting that "." will allow only the highest version, i.e. it will not allow any other version at all. This is actually rather strange for a "*" notation. At least my first impression would be that * means wildcard in a way allowing anything, but to achieve that one I had to actually resort to [6,7). 

Additionally  was an error in the docs assuming * "should" work as it does now. While it is probably meant to work as the documentation says and it's merely a bug?

**Comment by nkolev92** [comment]
Fixed in https://github.com/NuGet/docs.microsoft.com-nuget/pull/2132
