### ISSUE TITLE
Error CS0246: The type or namespace name 'NLog' could not be found

### ISSUE THREAD

**Issue by marishvinoj** [NuGet/docs.microsoft.com-nuget#2090]
In my local machine I am not getting any error but after commit data into github facing below issue.
1. Error CS0246: The type or namespace name 'NLog' could not be found (are you missing a using directive or an assembly reference?) 
2. Error CS0246: The type or namespace name 'NLog' could not be found (are you missing a using directive or an assembly reference?) 
3. Error CS0122: 'LogLevel' is inaccessible due to its protection level 
4. Error CS0246: The type or namespace name 'ILogger' could not be found (are you missing a using directive or an assembly reference?) 
5. src\PAMSurveyServiceUnitTests\PAMSurveyServiceUnitTests.csproj(123,5):   Error : This project references NuGet package(s) that are missing on this   computer. Use NuGet Package Restore to download them. For more information,   see http://go.microsoft.com/fwlink/?LinkID=322105.   The missing file is   ..\packages\MSTest.TestAdapter.2.1.1\build\net45\MSTest.TestAdapter.props.
--
Process 'msbuild.exe' exited with code   '1'.

**Comment by zivkan** [comment]
@marishvinoj The errors you reported are C# compiler errors (error code starts with `CS`), not NuGet errors (error codes starting with `NU`). Also, you haven't provided information for us to reproduce the errors. Finally, this is the docs repo, to report issues with https://docs.microsoft.com/nuget, not for product help. If you're asking for help with NuGet, not our documentation, please search for an issue at https://github.com/NuGet/Home/issues and create a new one if you can't find a suitable one, and please provide sufficient details for us to reproduce the error.
