### ISSUE TITLE
Add NuGet.Packaging examples

### ISSUE THREAD

**Issue by the-ress** [NuGet/docs.microsoft.com-nuget#2094]
This page could use some NuGet.Packaging examples.

For example:
```csharp
using (var reader = new PackageArchiveReader("Newtonsoft.Json.nupkg"))
{
    Console.WriteLine($"Version: {reader.GetIdentity().Version}");
}
 ```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cb17b741-1635-af19-e74b-d9921b0bd1ab
* Version Independent ID: 740217ba-335d-6401-64a1-d2f5d8e74f82
* Content: [NuGet Client SDK](https://docs.microsoft.com/en-us/nuget/reference/nuget-client-sdk#feedback)
* Content Source: [docs/reference/NuGet-Client-SDK.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/master/docs/reference/NuGet-Client-SDK.md)
* Product: **nuget**
* GitHub Login: @karann-msft
* Microsoft Alias: **karann**

**Comment by JonDouglas** [comment]
Closing with https://github.com/NuGet/docs.microsoft.com-nuget/pull/2126
