### ISSUE TITLE
 can we inherit nuspec file from another nuspec file

### ISSUE THREAD

**Issue by preetipadalia** [NuGet/docs.microsoft.com-nuget#2095]
I have a requirement to create different type of NuGet with Same project. I know we can create different nuspec file for this purpose. I just wanted to know if it is possible to create a parent nuspec file with common content and use it in child nuspec file. 
Also the dependencies should be available in csproj file itself.

I wanted to do this so that nuspec file mangement would be easy.

Thanks

**Comment by anangaur** [comment]
This would be a new requirement. Can you file an issue on [NuGet/Home](https://github.com/NuGet/Home/issues) with your scenario and sample, if possible?

With .NET Core, you can also use the project file to define package metadata and not deal with .nuspecs at all. See example: https://docs.microsoft.com/en-us/nuget/create-packages/creating-a-package-dotnet-cli
