### ISSUE TITLE
Need detail information for cf20 and sl20 folders

### ISSUE THREAD

**Issue by Leogh** [NuGet/docs.microsoft.com-nuget#2096]
Hi,
I'm trying to write code to add reference to the csproj file and want to know dlls in which folder to take.
In package Google.ProtocolBuffers.2.4.1.521, there are folders cf20 and cf35. They should be for Compact Framework but not in the format lib\{framework name}-{profile}. Also there are folders like sl20, sl30 and sl40 which are not mentioned on the page.
Is there informations about all the folder name format? 

Best Regards,
Leonard

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f1482e18-5f1f-3a8a-3321-66af52879ec5
* Version Independent ID: d70bd2f5-c04b-9207-62a0-4ecb6e8e5ca6
* Content: [Multi-targeting for NuGet Packages](https://docs.microsoft.com/en-us/nuget/create-packages/supporting-multiple-target-frameworks#feedback)
* Content Source: [docs/create-packages/Supporting-Multiple-Target-Frameworks.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/master/docs/create-packages/Supporting-Multiple-Target-Frameworks.md)
* Product: **nuget**
* GitHub Login: @karann-msft
* Microsoft Alias: **karann**

**Comment by zivkan** [comment]
Our [docs on target frameworks](https://docs.microsoft.com/nuget/reference/target-frameworks) show that `sl` was used by Silverlight.  There are no `cf` entries. 

In fact, download the package and opening in NuGet Package Explorer shows the folders listed as "unknown framework". I'm confident that this tool has used NuGet's own SDK packages correctly, so I believe the package with the `lib\cf20`  is not authored correctly and these `cf*` folders will never be used in asset selection.
