### ISSUE TITLE
why? help me

### ISSUE THREAD

**Issue by abassalmdani** [NuGet/docs.microsoft.com-nuget#2098]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b2c2eb22-045b-1c00-512a-a9eb1be4d784
* Version Independent ID: 87d10a7f-725b-18ef-d5ae-12b2f1c568b3
* Content: [NuGet Error NU1202](https://docs.microsoft.com/en-us/nuget/reference/errors-and-warnings/nu1202?f1url=https%3A%2F%2Fmsdn.microsoft.com%2Fquery%2Fdev15.query%3FappId%3DDev15IDEF1%26l%3Den-US%26k%3Dk(NU1202)%26rd%3Dtrue)
* Content Source: [docs/reference/errors-and-warnings/NU1202.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/master/docs/reference/errors-and-warnings/NU1202.md)
* Product: **nuget**
* GitHub Login: @zhili1208
* Microsoft Alias: **lzhi**

**Comment by zivkan** [comment]
Can you elaborate? I don't know how to help if I don't know what issue you're experiencing.

**Comment by Mikejo5000** [comment]
Will re-open if we get more info.
