### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by oliverkenny** [NuGet/docs.microsoft.com-nuget#2106]
"necessarily files all end up in their correct places in the project" should read "necessary files all end up in their correct places in the project"
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 92399c34-8136-b3bf-4754-5f0781a99bad
* Version Independent ID: 459b7ff8-6d5d-2dcb-fd78-9f52f56ae9b0
* Content: [Create a NuGet package using the dotnet CLI](https://docs.microsoft.com/en-us/nuget/create-packages/creating-a-package-dotnet-cli)
* Content Source: [docs/create-packages/creating-a-package-dotnet-cli.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/master/docs/create-packages/creating-a-package-dotnet-cli.md)
* Product: **nuget**
* GitHub Login: @karann-msft
* Microsoft Alias: **karann**

**Comment by zivkan** [comment]
@moingshaikh created a PR to fix the typo, which has been merged. It's not yet live, but will be the next time our staged changes are published to live.
