### ISSUE TITLE
language

### ISSUE THREAD

**Issue by JerryWoods44** [NuGet/docs.microsoft.com-nuget#2108]
is there a VB version, rather than the C# that comes up to copy/Paste?
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ef71b45e-0bb6-6e61-3b42-8e8f150db9fb
* Version Independent ID: 129fb470-7186-059a-fbe8-29b1caf96bf9
* Content: [Install and use a NuGet package in Visual Studio](https://docs.microsoft.com/en-us/nuget/quickstart/install-and-use-a-package-in-visual-studio)
* Content Source: [docs/quickstart/install-and-use-a-package-in-visual-studio.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/master/docs/quickstart/install-and-use-a-package-in-visual-studio.md)
* Product: **nuget**
* GitHub Login: @karann-msft
* Microsoft Alias: **karann**

**Comment by JonDouglas** [comment]
There is not & no plans to support one in the relative near-term.

https://devblogs.microsoft.com/vbteam/visual-basic-support-planned-for-net-5-0/
