### ISSUE TITLE
Remove FAQ about Solution Level Packages

### ISSUE THREAD

**Issue by ChrisMaddock** [NuGet/docs.microsoft.com-nuget#2117]
From Googling around - my understanding is that Solution level NuGet packages were deprecated from NuGet 3.0 ([ref](https://github.com/NuGet/Home/issues/522#issuecomment-98845250)).

This FAQ page has a question that talks about them as current functionality. Could it be added to the list for an update?

Thanks! 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: daea660a-705f-200a-afb4-0446db9333d4
* Version Independent ID: ea13ca94-77d0-905b-de4a-8cffad72304f
* Content: [NuGet Frequently-Asked Questions](https://docs.microsoft.com/en-us/nuget/resources/nuget-faq)
* Content Source: [docs/resources/NuGet-FAQ.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/master/docs/resources/NuGet-FAQ.md)
* Product: **nuget**
* GitHub Login: @shishirx34
* Microsoft Alias: **shishirh**

**Comment by JonDouglas** [comment]
Fixed via https://github.com/NuGet/docs.microsoft.com-nuget/pull/2124

Thanks @anangaur & @ChrisMaddock !
