### ISSUE TITLE
Update the default location for the machine-wide NuGet.Config

### ISSUE THREAD

**Issue by alpaix** [NuGet/docs.microsoft.com-nuget#212]
As it was recently [announced](http://blog.nuget.org/20170308/Announcing-NuGet-4.0-RTM.html) in v4.0.0+ default location for the machine-wide NuGet.config has changed from `%ProgramData%\NuGet\Config` to `%ProgramFiles(x86)%\NuGet\Config`. 

This breaking change should be reflected in the docs page *Configuring NuGet Behavior*.

**Comment by kraigb** [comment]
@alpaix Forgot to mention that I fixed this recently. Please review and close the issue if you're satisfied.

**Comment by alpaix** [comment]
Looks good to me. Thank you!
