### ISSUE TITLE
Page contains incorrect information

### ISSUE THREAD

**Issue by FrankAtHexagon** [NuGet/docs.microsoft.com-nuget#2121]
The page contains this text:
> NuGet cannot directly add references to a C++ project.

This is not correct. Native NuGet packages _can_ directly be added as references to C++ projects. Try using the [googletest](https://www.nuget.org/packages/googletest/) package for instance.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c7064d86-7de7-1a58-393b-39a5281a9617
* Version Independent ID: 8efa557b-8b1e-6320-4640-5226b8983832
* Content: [Creating Native NuGet Packages](https://docs.microsoft.com/en-us/nuget/guides/native-packages)
* Content Source: [docs/guides/Native-Packages.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/master/docs/guides/Native-Packages.md)
* Product: **nuget**
* GitHub Login: @karann-msft
* Microsoft Alias: **karann**

**Comment by JonDouglas** [comment]
This documentation is not very accurate nor well understood. Do you have suggestions as to how we can improve this scenario's documentation?

**Comment by FrankAtHexagon** [comment]
I think it would be great if this page was similar to the other pages for NuGet workflows, like for [MSBuild](https://docs.microsoft.com/en-us/nuget/create-packages/creating-a-package-msbuild).

For instance: have a brief, high-level overview of native NuGet packages at the top, then a section for creating a native package, then a section for adding a reference to a native package.

I worked for a while creating a native NuGet package and found it challenging but doable. I know many folks use vcpkg but many others prefer NuGet. Properly updating this section would save many folks time scouring the web reading blogs.
