### ISSUE TITLE
List of TargetFrameworks? 

### ISSUE THREAD

**Issue by DeanFaizal** [NuGet/docs.microsoft.com-nuget#2136]
Is there an official list of targets for xamarin ios and monodroid? 

The ones from the document: "MonoAndroid" and "Xamarin.iOS10", but other target names that work are "monoandroid81" and "xamarinios10". Can I get some clarification on this? Also, have a note for including .pdb files if there aren't .xml files. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d228e1b2-34af-a8cb-0a54-e2fcb6cd34df
* Version Independent ID: 31e9b41e-b74f-3614-7c3d-cd17a04e1211
* Content: [Create NuGet Packages for Xamarin (for iOS, Android, and Windows) with Visual Studio 2017 or 2019](https://docs.microsoft.com/en-us/nuget/guides/create-packages-for-xamarin)
* Content Source: [docs/guides/create-packages-for-xamarin.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/master/docs/guides/create-packages-for-xamarin.md)
* Product: **nuget**
* GitHub Login: @karann-msft
* Microsoft Alias: **karann**

**Comment by JonDouglas** [comment]
@DeanFaizal 

There's a list of target frameworks here:

https://docs.microsoft.com/en-us/nuget/reference/target-frameworks

The number added to the framework is the target framework version. i.e. `monoandroid81` = (Xamarin.Android,Version=v8.1) or `xamarinios10` = (Xamarin.iOS,Version=v1.0).

Do know that Target Framework Versions will be changing significantly with .NET 5:

https://github.com/dotnet/designs/blob/master/accepted/2020/net5/net5.md#design

For example, `net5.0-android`, `net5.0-ios` which then will have the platform version they support additionally such as:

`net5.0-android11` or `net5.0-ios14`. This will represent `.NET 5 + OS + OS Version`

//cc @davidortinau to chime in on Xamarin TFMs.

The docs for creating symbol packages can be found here: https://docs.microsoft.com/en-us/nuget/create-packages/symbol-packages-snupkg

**Comment by loic-sharma** [comment]
Hello, we'll close this issue as it looks your question was answered. Feel free to leave a comment or create a new issue if you have more questions!
