### ISSUE TITLE
Update NuGet.Config Reference

### ISSUE THREAD

**Issue by mairaw** [NuGet/docs.microsoft.com-nuget#214]
Feedback we got for article https://docs.microsoft.com/en-us/nuget/schema/nuget-config-file

https://github.com/dotnet/docs/issues/1730#issuecomment-286601352

> globalPackagesFolder applies only to projects using project.json.

So that should probably be amended (now that project.json projects are a thing of the past).

**Comment by kraigb** [comment]
I merged the PR, so closing.
