### ISSUE TITLE
Why not brew install nuget?

### ISSUE THREAD

**Issue by krischik** [NuGet/docs.microsoft.com-nuget#2140]
Why not use 

```sh
brew install nuget
```

to install on MacOS? That's a lot easier and most developers have brew installed anyway.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3460a9b2-3b49-1cda-add2-14d26e217716
* Version Independent ID: 95b91106-faff-c7f6-3699-94d643b5cf73
* Content: [Installing NuGet client tools](https://docs.microsoft.com/en-us/nuget/install-nuget-client-tools)
* Content Source: [docs/install-nuget-client-tools.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/master/docs/install-nuget-client-tools.md)
* Product: **nuget**
* GitHub Login: @karann-msft
* Microsoft Alias: **karann**

**Comment by JonDouglas** [comment]
We provide the tooling for users to get started with NuGet. Many software package managers support NuGet, but they are maintained by the project maintainers or community. 

Although it is much easier to use `brew` / `port` on MacOS, or `winget` / `chocolately` on Windows, it's really up to the developer to make that choice.

I'll leave this issue open to collect upvotes from others to see if people would like to see popular software package managers mentioned in this doc.

Thanks for the issue!

**Comment by JonDouglas** [comment]
Given we haven't seen much demand to add this to our documentation over the last few months, I'm closing this issue. If you'd like to take on the work to add this to our docs, we'd gladly accept a PR where it makes sense.
