### ISSUE TITLE
Explain the role of the Dropdown and the Offline Packages package source

### ISSUE THREAD

**Issue by donnie-msft** [NuGet/docs.microsoft.com-nuget#2145]
I believe we can provide more detail on what the Package Source dropdown actually does. 

Additionally, we show an Offline Packages source here, but need to provide some explanation about what it is, when/if it should ever be changed, etc.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9cbbd8f5-8155-0057-b0cc-0b96ee35aad4
* Version Independent ID: 8b085f6d-05f3-e213-6b2a-3f7274581111
* Content: [Install and manage NuGet packages in Visual Studio](https://docs.microsoft.com/en-us/nuget/consume-packages/install-use-packages-visual-studio)
* Content Source: [docs/consume-packages/install-use-packages-visual-studio.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/master/docs/consume-packages/install-use-packages-visual-studio.md)
* Product: **nuget**
* GitHub Login: @anangaur 
* Microsoft Alias: **anangaur**

**Comment by zivkan** [comment]
We show the package sources configured for the solution, which include machine wide nuget.config files. This might include a package source configured by a Visual Studio component, but NuGet itself doesn't intrinsically add any offline packages source.
