### ISSUE TITLE
Create conceptual docs around everything NuGet restore performance.

### ISSUE THREAD

**Issue by JonDouglas** [NuGet/docs.microsoft.com-nuget#2155]
# What we want to cover:

- What is NuGet restore at it's core.
- What major factors impact a NuGet restore's performance.
- What is the difference between "full" restore vs. "no-op" restore.
    - How can you tell what mode you're running in.
    - What extra modes are available such as static graph w/ no-op.
- What methods can you use NuGet restore?
    - What are the best practices for each method? (MSBuild, dotnet CLI, nuget CLI, etc).
- Does NuGet configs affect performance? If they do?

Feel free to jot down thoughts below.

References:

https://github.com/NuGet/docs.microsoft.com-nuget/issues/1941
https://github.com/NuGet/docs.microsoft.com-nuget/issues/2149
https://github.com/NuGet/docs.microsoft.com-nuget/issues/1872

//cc @nkolev92 @anangaur

**Comment by anangaur** [comment]
Another nuance: VS always runs Solution restore

**Comment by nkolev92** [comment]
I left a lot of feedback in the teams thread. @JonDouglas do you want to start off some docs with all that info? Should I paste my thoughts here? Only problem with blind copy paste is that I was adding comments to a doc structure that's not here!
