### ISSUE TITLE
nuget.config changes aren't reflected in Visual Studio until solution is reloaded

### ISSUE THREAD

**Issue by donnie-msft** [NuGet/docs.microsoft.com-nuget#2156]
Similar to: https://github.com/NuGet/docs.microsoft.com-nuget/issues/2157

Explain that when making changes to a `nuget.config`, those changes won't apply to an open solution in Visual Studio immediately. Closing/reopening the Solution will allow the Package Manager UI to see the new config settings.

Example of a security scenario that won't be applied until PMUI is reloaded:

> - Created new netcore project (console app)
>   -  created NuGet.Config file using dotnet new nugetconfig command
>   -  added a trusted signer and set signature validation mode to require
>   -  opened PM UI and was able to install untrusted signed package
> 
> But when I restarted my solution and tried to install again on another project then I got an error saying package is untrusted. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0ea1390e-db36-6759-3095-ebab9d546fdb
* Version Independent ID: ca88d8c6-0515-a267-aac3-a508c54157ab
* Content: [nuget.config File Reference](https://docs.microsoft.com/en-us/nuget/reference/nuget-config-file)
* Content Source: [docs/reference/nuget-config-file.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/master/docs/reference/nuget-config-file.md)
* Product: **nuget**
* GitHub Login: @karann-msft
* Microsoft Alias: **karann**

**Comment by JonDouglas** [comment]
Can we close one of these out? They seem like dupes

https://github.com/NuGet/docs.microsoft.com-nuget/issues/2157

**Comment by donnie-msft** [comment]
@JonDouglas  they are similar, as I called out in the description. But they are two different docs with slightly different purposes, and both should be addressed.

**Comment by JonDouglas** [comment]
They have different title ordering but largely look duplicate even when re-reading.

> Visual Studio requires solution to be reloaded after making nuget.config changes

and

> nuget.config changes aren't reflected in Visual Studio until solution is reloaded

- Visual Studio requires solution to be reloaded after nuget.config changes
- nuget.config changes aren't reflected until solution is reloaded in Visual Studio

This is saying the same thing is it not? **VS is not aware of the file until it's reloaded.**

Can we clarify what the requirements are for this doc between the two in a single issue? It is not clear what these different purposes are. I'm asking if we can simplify the challenge which is "nuget.config requires VS to reload a solution to reflect changes"

These also have the exact same description text. I wouldn't know what to do with these two issues as is. Can you add more information to them or close one out appropriately?

**Comment by donnie-msft** [comment]
I replied here, again pointing out these are 2 distinct docs: https://github.com/NuGet/docs.microsoft.com-nuget/issues/2157#issuecomment-785411242

Beyond that, I don't think there's anything more to clarify. The same clarification is needed in 2 places.
