### ISSUE TITLE
Visual Studio requires solution to be reloaded after making nuget.config changes

### ISSUE THREAD

**Issue by donnie-msft** [NuGet/docs.microsoft.com-nuget#2157]
Similar to: https://github.com/NuGet/docs.microsoft.com-nuget/issues/2156

Copy of description:
Explain that when making changes to a `nuget.config`, those changes won't apply to an open solution in Visual Studio immediately. Closing/reopening the Solution will allow the Package Manager UI to see the new config settings.

Example of a security scenario that won't be applied until PMUI is reloaded:

> - Created new netcore project (console app)
>   -  created NuGet.Config file using dotnet new nugetconfig command
>   -  added a trusted signer and set signature validation mode to require
>   -  opened PM UI and was able to install untrusted signed package
> 
> But when I restarted my solution and tried to install again on another project then I got an error saying package is untrusted. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9cbbd8f5-8155-0057-b0cc-0b96ee35aad4
* Version Independent ID: 8b085f6d-05f3-e213-6b2a-3f7274581111
* Content: [Install and manage NuGet packages in Visual Studio](https://docs.microsoft.com/en-us/nuget/consume-packages/install-use-packages-visual-studio)
* Content Source: [docs/consume-packages/install-use-packages-visual-studio.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/master/docs/consume-packages/install-use-packages-visual-studio.md)
* Product: **nuget**
* GitHub Login: @karann-msft
* Microsoft Alias: **karann**

**Comment by JonDouglas** [comment]
@donnie-msft Can this be simplified to unloading/loading a project/solution?

**Comment by donnie-msft** [comment]
@JonDouglas I don't understand the question. The title and description already indicate `requires solution to be reloaded` and `closing/reopening the Solution will allow ...`.

**Comment by JonDouglas** [comment]
It's still not clear. The title is the only thing that differs here, the description is the same copy/paste?

**Comment by donnie-msft** [comment]
Gotcha, here's the diff:

> * Content: [Install and manage NuGet packages in Visual Studio](https://docs.microsoft.com/en-us/nuget/consume-packages/install-use-packages-visual-studio)

versus

> * Content: [nuget.config File Reference](https://docs.microsoft.com/en-us/nuget/reference/nuget-config-file)

**Comment by JonDouglas** [comment]
Can we close one issue & include these both in one?

**Comment by JonDouglas** [comment]
Sorry I was not looking at the context of the issues, (i.e. docs info). I was looking purely at the issues from a tool.
