### ISSUE TITLE
Who is the audience that this is written for?  

### ISSUE THREAD

**Issue by shayneb-uw** [NuGet/docs.microsoft.com-nuget#2159]
For the command line **solution** it is completely unclear what actual commands should be used, is there a reason why an actual example is not provided?  The statement "usually it's recommended to import the Microsoft.Common.targets" is a suggestion, certainly not a solution without further instructions as to what should be done to import the Microsoft.Common.targets".

In the section for Visual Studio the same problem exists, explanations of what might be a cause, but no concrete solution.  Additionally "In Visual Studio the error could mean that targets are not import similar to the command line scenario."  Without proper punctuation and grammar (e.g. "targets are not import") doesn't help understanding what the solution for the issue is.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e7a0653a-ec3b-3b60-ae77-a51fedf1966e
* Version Independent ID: 90a503d7-6d0f-7b9e-4c2c-45f9a9705ac7
* Content: [NuGet Error NU1105](https://docs.microsoft.com/en-us/nuget/reference/errors-and-warnings/nu1105?f1url=%3FappId%3DDev15IDEF1%26l%3Den-US%26k%3Dk(NU1105)%26rd%3Dtrue)
* Content Source: [docs/reference/errors-and-warnings/NU1105.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/master/docs/reference/errors-and-warnings/NU1105.md)
* Product: **nuget**
* GitHub Login: @zhili1208
* Microsoft Alias: **lzhi**

**Comment by JonDouglas** [comment]
I think the best error message comes from the IDE. Maybe we should match the docs?

```
Unable to find project information for '{0}'. Inside Visual Studio, this may be because the project is unloaded or not part of current solution. Otherwise the project file may be invalid or missing targets required for restore.
```

The command line parts would refer to the sentence: **Otherwise the project file may be invalid or missing targets required for restore.**

So perhaps we can improve this by saying your project file is not referencing the appropriate targets required for restore? 

For example sdk-style projects will have this type of node:

```
<Project Sdk="Microsoft.NET.Sdk">
```

and legacy style projects will have this type of node:

```
<Project ToolsVersion="15.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <Import Project="$(MSBuildExtensionsPath)\$(MSBuildToolsVersion)\Microsoft.Common.props" Condition="Exists('$(MSBuildExtensionsPath)\$(MSBuildToolsVersion)\Microsoft.Common.props')" />
```
