### ISSUE TITLE
untegrated

### ISSUE THREAD

**Issue by Tep8quahie** [NuGet/docs.microsoft.com-nuget#2164]
[Enter feedback here]
Spelling error or a word new to me with a false friend.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a3b20c46-c5f1-3a2a-738d-8aa8e69cf10c
* Version Independent ID: 7055e752-859b-6106-6802-70010d0305d9
* Content: [NuGet Package Restore](https://docs.microsoft.com/en-us/nuget/consume-packages/package-restore)
* Content Source: [docs/consume-packages/Package-Restore.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/master/docs/consume-packages/Package-Restore.md)
* Product: **nuget**
* GitHub Login: @karann-msft
* Microsoft Alias: **karann**

**Comment by JonDouglas** [comment]
Thanks for the feedback! I'll merge it in #2169
