### ISSUE TITLE
Update docs to emphasize modern packing/pushing conventions

### ISSUE THREAD

**Issue by zkat** [NuGet/docs.microsoft.com-nuget#2165]
We really emphasize .nuspec-based pack right now, but we should be emphasizing the much nicer SDK-style project packing, while still mentioning the .nuspec-based workflow for the benefit of legacy projects.

**Comment by nkolev92** [comment]
Newer dup of this in https://github.com/NuGet/Home/issues/10394

**Comment by nkolev92** [comment]
I actually didn't mean to close this. Leaving that decision to @zkat

**Comment by zkat** [comment]
I'm gonna close this one because stuff in Home is definitely more visible.
