### ISSUE TITLE
Can't send email to "account@nuget.org"

### ISSUE THREAD

**Issue by catalingavan** [NuGet/docs.microsoft.com-nuget#2172]
Hello,

Email address "account@nuget.org" only accepts emails from within the "@nuget.org" domain/organization.

Is there an alternate email address which we can use?

![image](https://user-images.githubusercontent.com/39127098/94146271-5e512f00-fe7c-11ea-852a-d0c618a6bccc.png)

Thank you

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 453f416f-1e0f-a73b-6690-c4c8bf34a4e2
* Version Independent ID: a8956be7-5b12-04a5-ee73-239973607dca
* Content: [ID Prefix Reservation](https://docs.microsoft.com/en-us/nuget/nuget-org/id-prefix-reservation)
* Content Source: [docs/nuget-org/id-prefix-reservation.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/master/docs/nuget-org/id-prefix-reservation.md)
* Product: **nuget**
* GitHub Login: @karann-msft
* Microsoft Alias: **karann**

**Comment by jcjiang** [comment]
Hi there! I see that the screenshot is indicating that 'nugetservereng@microsoft.com' cannot be emailed. Does the same error message pop up for 'account@nuget.org'?

**Comment by jcjiang** [comment]
Problem has been fixed by @aortiz-msft
