### ISSUE TITLE
Testing Microsoft Graph Quick Start- ASP.NET MVC development fails after clean Rebuild

### ISSUE THREAD

**Issue by amysy** [NuGet/docs.microsoft.com-nuget#2176]
After doing a clean rebuild app dumped the following error message.
Severity	Code	Description	Project	File	Line	Suppression State
Error		This project references NuGet package(s) that are missing on this computer. Use NuGet Package Restore to download them.  For more information, see http://go.microsoft.com/fwlink/?LinkID=322105. The missing file is ..\packages\Microsoft.CodeDom.Providers.DotNetCompilerPlatform.2.0.0\build\net46\Microsoft.CodeDom.Providers.DotNetCompilerPlatform.props.	C:\Install\AppGraph\graph-tutorial.sln	
C:\
![APPGraph](https://user-images.githubusercontent.com/13893456/95243226-f1238f00-07d5-11eb-8c8c-f09f5f7c5a60.PNG)
![APPGraph](https://user-images.githubusercontent.com/13893456/95243181-dc46fb80-07d5-11eb-9330-773a26649652.PNG)
Installs\AppGraph\graph-tutorial\graph-tutorial.csproj	399

**Comment by zivkan** [comment]
@amysy  Where are the instructions for the quick start?
