### ISSUE TITLE
Following the steps creates an invalid package

### ISSUE THREAD

**Issue by torgabor** [NuGet/docs.microsoft.com-nuget#2184]
Steps to reproduce.
1. Copy the example .nuspec into a file like `example.nuspec`, create `dat.txt`
2. Create package with command `nuget pack .\example.nuspec`, this is successful.
3. Try to examine the package with   `nuget list * -Source "$((gi . ).FullName)"`, this results in output  `No packages found.` No further output even with `-verbosity detailed`
4. Repeating the previous command after placing a .nupkg from `nuget.org`  like `Newtonsoft.Json` works correctly, `nuget list` finds the package.

**Edit:** I have found out, that the issue is that the specified version makes the package a prerelease package, thus hiding it  unless the `-prerelease` flag is specified. I think this is an easy to make mistake, for people following this guide. 
I think changing `<version>1.8.3-beta</version>` to ` <version>1.8.3</version>` avoids the issue.

**Comment by zivkan** [comment]
what docs page are the steps that you are referring to?
