### ISSUE TITLE
How to specify version wildcard in PMC 

### ISSUE THREAD

**Issue by Rick-Anderson** [NuGet/docs.microsoft.com-nuget#2186]
We’d like to use CLI style wildcards in Program Manager to install NuGet packages.

For the CLI, we use the following to get the latest version:

dotnet add package Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore -v 5.0.0-*

For VS, the PM is the preferred mechanism, but it doesn’t accept CLI style wild-cards

PM> Install-Package Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore -Version 5.0.0-*
Install-Package : Failed to parse the input of Version parameter: 5.0.0-* to a valid Semantic version. 
At line:1 char:1
+ Install-Package Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore  ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], InvalidOperationException
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand

I'd be happy to document this for you if you can show my the right syntax. Currently we need to update the PMC instructions for each new pre-release.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ef71b45e-0bb6-6e61-3b42-8e8f150db9fb
* Version Independent ID: 129fb470-7186-059a-fbe8-29b1caf96bf9
* Content: [Install and use a NuGet package in Visual Studio](https://docs.microsoft.com/en-us/nuget/quickstart/install-and-use-a-package-in-visual-studio)
* Content Source: [docs/quickstart/install-and-use-a-package-in-visual-studio.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/master/docs/quickstart/install-and-use-a-package-in-visual-studio.md)
* Product: **nuget**
* GitHub Login: @karann-msft
* Microsoft Alias: **karann**

**Comment by zivkan** [comment]
At this time it's not possible.

We have a tracking issue to add support into the package manager UI: https://github.com/NuGet/Home/issues/9829   An intern had started the implementation but was unable to finish before they left, and the rest of the team have other priorities, so this work unfortunately is stalled at this time.

I'm not aware of any issue requesting support for floating versions in Package Manager Console. If that's something you'd like, I encourage you to make a feature request at https://github.com/NuGet/Home/issues/new. This repo is for docs issues, not product issues.
