### ISSUE TITLE
VS2010 : This project references NuGet package(s) that are missing on this computer.

### ISSUE THREAD

**Issue by surlydev** [NuGet/docs.microsoft.com-nuget#2194]
Brand new laptop build (Win 10 64-bit).

Visual Studio 2010 Professional installed yesterday.

Git cloned the project 2 hours ago.

`Error	66	This project references NuGet package(s) that are missing on this computer. Enable NuGet Package Restore to download them.  For more information, see http://go.microsoft.com/fwlink/?LinkID=322105. The missing file is ..\..\..\..\..\packages\Microsoft.Bcl.Build.1.0.21\build\Microsoft.Bcl.Build.targets.	C:\dev\Source\OCS\Dev-Git\Dev\Code\UI\Web\Ocs.Web\OCS2.csproj	6836	5	OCS2
`

**Comment by JonDouglas** [comment]
There is a documentation page here:

https://docs.microsoft.com/en-us/nuget/Consume-Packages/Package-restore-troubleshooting

It is highly recommended that you update to Visual Studio 2019. There is a community version that is free as well! We don't typically support older versions such as 2010.

https://support.microsoft.com/en-us/lifecycle/search?alpha=Visual%20Studio%202010%20(all%20editions)
