### ISSUE TITLE
Creating localized packages with .NET SDK projects

### ISSUE THREAD

**Issue by mandalorianbob** [NuGet/docs.microsoft.com-nuget#2197]
.NET SDK projects don't use a nuspec, and thus can't really use this.

Also, this seems to assume that you are compiling resources into dlls. This isn't the recommended pattern from what I can see. In fact, this _one_ help document is the only place I've seen talking about localizing .NET that doesn't say you're going to be creating .resource binaries.

So this really needs an update, because I can't use this to create a localized Nuget package.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 054efc3a-8943-aa6b-88d9-e762c871059e
* Version Independent ID: 8b217e6a-8292-39af-a5be-85812f9fdecc
* Content: [How to Create a Localized NuGet Package](https://docs.microsoft.com/en-us/nuget/create-packages/creating-localized-packages)
* Content Source: [docs/create-packages/Creating-Localized-Packages.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/master/docs/create-packages/Creating-Localized-Packages.md)
* Product: **nuget**
* GitHub Login: @karann-msft
* Microsoft Alias: **karann**

**Comment by mandalorianbob** [comment]
Apparently in my particular case, it's very important that the resx files be named [filename].[locale].resx and not _just_ in a locale named folder. Probably good to mention here.

**Comment by JonDouglas** [comment]
@mandalorianbob Thanks for the contribution!

We'll have to expand on localization for SDK Style projects / dotnet pack scenarios. Thanks for the note about the resx requirement here as well!
