### ISSUE TITLE
What is the syntax to target .NET Framework in nuspec?

### ISSUE THREAD

**Issue by ghost** [NuGet/docs.microsoft.com-nuget#2199]
In the example 
```xml
<dependencies>
    <group>
        <dependency id="RouteMagic" version="1.1.0" />
    </group>

    <group targetFramework=".NETFramework4.7.2">
        <dependency id="jQuery" version="1.6.2" />
        <dependency id="WebActivator" version="1.4.4" />
    </group>

    <group targetFramework="netcoreapp3.1">
    </group>
</dependencies>
``` 
to target .NET Framework, this syntax is user.
But in other documentation page, the example show this syntax :

https://docs.microsoft.com/en-US/nuget/create-packages/supporting-multiple-target-frameworks#declaring-dependencies-
advanced
```xml
<dependencies>

    <group targetFramework="net472">
        <dependency id="jQuery" version="1.10.2" />
        <dependency id="WebActivatorEx" version="2.2.0" />
    </group>

    <group targetFramework="net20">
    </group>

</dependencies>
```

Is ".NETFramework4.7.2" or "net472"? Or both?
What is the syntax to target .NET Standard 2.0?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 06a19d7d-253d-f17f-6421-624c9867473d
* Version Independent ID: cc37eb17-f715-080c-7bfc-9eae868d50ba
* Content: [.nuspec File Reference for NuGet](https://docs.microsoft.com/en-us/nuget/reference/nuspec#dependency-groups)
* Content Source: [docs/reference/nuspec.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/master/docs/reference/nuspec.md)
* Product: **nuget**
* GitHub Login: @karann-msft
* Microsoft Alias: **karann**

**Comment by JonDouglas** [comment]
You can do both. Target Frameworks allow for both the target framework name & target framework moniker(TFM). 

https://docs.microsoft.com/en-us/dotnet/standard/frameworks#supported-target-frameworks

For .NET Standard 2.0 you can use

```
<group targetFramework=".NETStandard2.0" />

or

<group targetFramework="netstandard2.0" />
```

You can always download a NuGet package online & look at the .nuspec to see various examples as well!

**Comment by JonDouglas** [comment]
@nkolev92, @zivkan, or @zkat 

The preferred definition is the short folder name right? I think we should specify that in docs here if so rather than the .NET Framework name + version.

**Comment by nkolev92** [comment]
It's weird I think. 

Older frameworks use a variation of the long name, but net5.0 and later use the short name.

**Comment by zivkan** [comment]
I believe that when our official tools pack a custom nuspec file, if it can parse the group id as a short folder name into a NuGetFramework, then it will write that ".NETFramework4.7.2" syntax into the nupkg's nuspec, which is a non-standard syntax used only by nuspec and nothing else.

If the customer is using a non-official tool, say they're just zipping up a directory and renaming zip to nupkg, then I'm less confident if that will work, but I suspect it will, given that, as Nikolche wrote, net5.0 onwards will be using the short folder name. Also I don't believe that `NuGetFramework` has special `Parse` methods that only accept one format or another. The `Parse` method I know of will try all the different known syntaxes until it either finds one format parser that works, or all of them fail. Hence any syntax that gets parsed into the correct `NuGetFramework` instance should work.

For documentation purposes, I don't know what we should write. On one hand using the short folder name is better known, hence would be easier for customers. On the other hand, if they pack, then inspect the nuspec in the package, they'll see that it's been modified compared to what they wrote.

**Comment by A9G-Data-Droid** [comment]
I am getting this error:

> WARNING: NU5128: Some target frameworks declared in the dependencies group of the nuspec and the lib/ref folder do not have exact matches in the other location. Consult the list of actions below:
> - Add a dependency group for .NETFramework4.8 to the nuspec

So I added this section, as instructed by the [documentation](https://learn.microsoft.com/en-us/nuget/reference/errors-and-warnings/nu5128).

    <dependencies>
      <group targetFramework=".NETFramework4.8" />
    </dependencies>

I still get the same error. This setting appears to do nothing.

**Comment by zivkan** [comment]
@A9G-Data-Droid what version of nuget.exe are you using?

You could be hitting the bug fixed by https://github.com/NuGet/NuGet.Client/pull/4659 in NuGet.exe 6.3

**Comment by A9G-Data-Droid** [comment]
Thanks @zivkan ! I was running 6.2.1.2 (Currently recommended by Microsoft)

I switched to 6.3.0.131 and it packs without any issues.

**Comment by EmilAlipiev** [comment]
I am still getting this error in 6.6.1 version.

**Comment by zivkan** [comment]
@EmilAlipiev can you share a repro?

**Comment by EmilAlipiev** [comment]
@zivkan you can find my nuspec here https://github.com/EmilAlipiev/SamsungAccessorySDK.Net/blob/master/SamsungAccessorySDK-maui.nuspec

**Comment by zivkan** [comment]
@EmilAlipiev why are you using a nuspec?  If you cd into the project directory and run `dotnet pack` (actually, you can do it from the solution directory, it'll attempt to pack all projects in the solution that are "packable"), does it generate the package with the files in the expected locations? You'll need to move the package metadata into MSBuild properties, but NuGet will put files in the "correct" locations: https://learn.microsoft.com/en-us/nuget/reference/msbuild-targets#pack-target

**Comment by EmilAlipiev** [comment]
@zivkan just to update your question reason i use nuspec. Because of this open issue from 2019 https://github.com/NuGet/Home/issues/8016
