### ISSUE TITLE
Ways to install a NuGet Package

### ISSUE THREAD

**Issue by Nicztin** [NuGet/docs.microsoft.com-nuget#2203]
[Enter feedback here]

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6f32fcb5-8641-9062-83bd-2c8c09aab872
* Version Independent ID: 12404cbd-0105-957e-2875-bb91904fc359
* Content: [Overview and workflow of using NuGet packages](https://docs.microsoft.com/en-gb/nuget/consume-packages/overview-and-workflow)
* Content Source: [docs/consume-packages/Overview-and-Workflow.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/master/docs/consume-packages/Overview-and-Workflow.md)
* Product: **nuget**
* GitHub Login: @karann-msft
* Microsoft Alias: **karann**

**Comment by JonDouglas** [comment]
@Nicztin Feel free to add your feedback to this issue. Right now I'm not quite sure what the feedback is!

**Comment by JonDouglas** [comment]
We're closing this issue as it's been awhile since we've heard back!
