### ISSUE TITLE
Adding a readme and other files section does not work

### ISSUE THREAD

**Issue by MhAllan** [NuGet/docs.microsoft.com-nuget#2204]
This section "Adding a readme and other files" does not work. I tried it and looked around the internet, people are really lost and there are many online solution all of them just don't work in .Net standard package that is packed by dotnet pack.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 18071970-cf13-78af-ac1d-9adefefdb693
* Version Independent ID: 3bf15a5c-8b3e-0e69-0bf6-03b44654970c
* Content: [Create and publish a .NET Standard NuGet package - Visual Studio on Windows](https://docs.microsoft.com/en-us/nuget/quickstart/create-and-publish-a-package-using-visual-studio?tabs=netcore-cli)
* Content Source: [docs/quickstart/create-and-publish-a-package-using-visual-studio.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/master/docs/quickstart/create-and-publish-a-package-using-visual-studio.md)
* Product: **nuget**
* GitHub Login: @karann-msft
* Microsoft Alias: **karann**

**Comment by anangaur** [comment]
@chgill-MSFT , should we be talking about readme.txt option or add the readme.md documentation here?

**Comment by zivkan** [comment]
looking at https://learn.microsoft.com/en-us/nuget/quickstart/create-and-publish-a-package-using-visual-studio?tabs=netcore-cli#add-a-readme-or-another-file

I think it's not sufficitly simple for people new to .NET, who lack knowledge on MSBuild syntax.

Plus, the readme information is the old readme.txt instructions, but needs to be changed to the new embedded readme (markdown) information.
