### ISSUE TITLE
Required items are not really required.

### ISSUE THREAD

**Issue by agr** [NuGet/docs.microsoft.com-nuget#2217]
The "Set properties" section starts with a list of "required" properties, 4 out of 5 of which seems to be optional (the "if not specified" text is present on 4 items).

> Set properties
The following properties are required to create a package.

> * PackageId, the package identifier, which must be unique across the gallery that hosts the package. If not specified, the default value is AssemblyName.
> * Version, a specific version number in the form Major.Minor.Patch[-Suffix] where -Suffix identifies pre-release versions. If not specified, the default value is 1.0.0.
> * The package title as it should appear on the host (like nuget.org)
> * Authors, author and owner information. If not specified, the default value is AssemblyName.
> * Company, your company name. If not specified, the default value is AssemblyName.

How about

> The following project properties are used to generate a package manifest:

instead? Or

> The following properties are needed to create a package.

Also, package titles are not displayed on nuget.org anywhere anymore, should it be mentioned (or the title removed from the list)?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 92399c34-8136-b3bf-4754-5f0781a99bad
* Version Independent ID: 459b7ff8-6d5d-2dcb-fd78-9f52f56ae9b0
* Content: [Create a NuGet package using the dotnet CLI](https://docs.microsoft.com/en-us/nuget/create-packages/creating-a-package-dotnet-cli)
* Content Source: [docs/create-packages/creating-a-package-dotnet-cli.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/master/docs/create-packages/creating-a-package-dotnet-cli.md)
* Product: **nuget**
* GitHub Login: @karann-msft
* Microsoft Alias: **karann**

**Comment by donnie-msft** [comment]
"the minimum necessary to..." ?

**Comment by agr** [comment]
"the minimum necessary" still implies that they are required, while they can be omitted.

**Comment by JonDouglas** [comment]
https://docs.microsoft.com/en-us/style-guide/a-z-word-list-term-collections/s/should-vs-must

https://docs.microsoft.com/en-us/style-guide/a-z-word-list-term-collections/r/recommend

**Comment by JonDouglas** [comment]
Maybe we should do this:

The following properties are required to create a package.

- PackageId, the package identifier, which must be unique across the gallery that hosts the package. If not specified, the default value is AssemblyName.
- Version, a specific version number in the form Major.Minor.Patch[-Suffix] where -Suffix identifies pre-release versions. If not specified, the default value is 1.0.0.
- The package title as it should appear on the host (like nuget.org)

The following properties are recommended to be overridden when creating a package.

- Authors, author and owner information. If not specified, the default value is AssemblyName.
- Company, your company name. If not specified, the default value is AssemblyName.

**Comment by donnie-msft** [comment]
They are indeed the minimum necessary in order to pack. You just state that they will be defaulted if you don't specify your own value.

**Comment by zivkan** [comment]
The "required fields" make sense when talking about packing a nuspec. However, the docs page this feedback refers to is explicitly about an SDK style csproj, where `dotnet new classlib; dotnet pack` works just fine, without setting any of the mentioned properties at all. From a customer point of view using the dotnet cli and knowing nothing about the nuspec file, none of the properties are required.

It's more like "Here are a bunch of properties you can optionally set if you want to change your package's default values". There's no need to use the work "required" anywhere, as it's discussing an implementation detail that is not relevant to the customer in this scenario.
