### ISSUE TITLE
Solution with mixed projects styles (non-sdk, sdk and migrated)

### ISSUE THREAD

**Issue by roofiq** [NuGet/docs.microsoft.com-nuget#2220]
Hello,

I would like to ask for a best practice advise when it comes to implementing CI with NuGet creation (packing) for a solution, that consist of multiple project in different style:
- .net 4.8 with packages.config
- .net migrated to SDK packagesReference

For migrated .NET projects (packages.config -> packagesReference) we should use `msbuild -t:pack`.
For non-sdk .NET (so with packages.config) we should use `nuget.exe cli` (nuget pack task).
For any SDK-style project we should use `dotnet cli`.

Considering that we have each of above in one solution.
Should we build and pack separately (project by project)? Or maybe there is a way to still build a solution that will work?

Thanks,
Rafal

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 08eeba53-088c-5b66-99c7-dd7021463eb2
* Version Independent ID: 952d6f2b-ec06-69f3-621b-95c7f5eb49d2
* Content: [Identify the project format](https://docs.microsoft.com/en-us/nuget/resources/check-project-format)
* Content Source: [docs/resources/check-project-format.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/master/docs/resources/check-project-format.md)
* Product: **nuget**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by JonDouglas** [comment]
The best practices can be followed by using the right tool for your framework & package management style. Right now if you have a mixture of projects, you will need a mixture of tooling that understands those projects. There does not exist a single tool to accomplish this unless you migrated everything over to `<PackageReference>` and `SDK Style Projects`. Then you can use `dotnet CLI` or `MSBuild` interchangeably for CI purposes.
