### ISSUE TITLE
Link to list of trusted root authorities on windows

### ISSUE THREAD

**Issue by thesuavehog** [NuGet/docs.microsoft.com-nuget#2221]
This page notes that X.509 certificates need to "chain to a trusted root authority that is trusted by default on Windows" ... but there's no link to where to find out what the trusted root authorities on Windows are.

Given that the obvious question readers of this page will have after understanding _why_ they need an X.509 cert is: "How do I get one?" ... I realize Microsoft probably doesn't want to promote a specific vendor (though if Azure issues compatible certs, maybe pointing there would be ok...) but at least linking to a page which helps the reader understand how to get one (specifically to be sure they are getting one which will actually work given the chaining requirements) would be super helpful.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a43491eb-360f-b3ad-9718-12eef3b33862
* Version Independent ID: 486b96d8-3a28-2a44-072d-99fb64c415de
* Content: [Signed Packages](https://docs.microsoft.com/en-us/nuget/reference/signed-packages-reference)
* Content Source: [docs/reference/Signed-Packages-Reference.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/master/docs/reference/Signed-Packages-Reference.md)
* Product: **nuget**
* GitHub Login: @rido-min
* Microsoft Alias: **rmpablos**

**Comment by rido-min** [comment]
@thesuavehog thanks for your feedback. 

The article [Signing Packages](https://docs.microsoft.com/en-us/nuget/create-packages/sign-a-package#get-a-code-signing-certificate) includes a suggested list of CAs, with a link documenting the trusted root authorities on Windows.

Are you missing anything else?

**Comment by thesuavehog** [comment]
ah, missed that. I would reference that in the 'Certificate Requirements' section since it's easy to miss as a 'Related Article'
