### ISSUE TITLE
Consider adding advice for running NuGet on docker. 

### ISSUE THREAD

**Issue by nkolev92** [NuGet/docs.microsoft.com-nuget#2222]
Related: https://github.com/NuGet/Home/issues/10317

People can easily run into problems because of file permissions.

**Comment by JonDouglas** [comment]
Does https://docs.microsoft.com/en-us/dotnet/core/docker/build-container & https://docs.microsoft.com/en-us/dotnet/core/docker/introduction satisfy these items?

Should we add advice to lock files instead saying these may be hard to use in docker environments unless you commit them?

**Comment by nkolev92** [comment]
I'm not sure it's covered. 

The lock file idea is actually that could help people because NuGet will be forced to get the same graph, so actively avoiding the issue.
