### ISSUE TITLE
What is win10 TFM and what is the difference with win?

### ISSUE THREAD

**Issue by djee-ms** [NuGet/docs.microsoft.com-nuget#2237]
What does the following description means ("Supported frameworks" table)?

> win10 (not supported by Windows 10 Platform)

This makes no sense. And what is the difference between the `win` and `win10` TFMs?

The table under the "Supported frameworks" section also as an "Abbreviation" column that is undocumented; I assume that you cannot abbreviate 15+ different TFMs with a single abbreviation, so what those even mean?

This really must be better documented. The current documentation is not helpful at all; in fact it brings more confusion than it clarifies things.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0a0f5267-208d-8af2-ef18-dae7407eefad
* Version Independent ID: 19b00f91-5d31-0d4d-388b-30b1bd4e7c0f
* Content: [Target Frameworks Reference for NuGet](https://docs.microsoft.com/en-us/nuget/reference/target-frameworks?source=docs#supported-frameworks)
* Content Source: [docs/reference/target-frameworks.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/master/docs/reference/target-frameworks.md)
* Product: **nuget**
* GitHub Login: @karann-msft
* Microsoft Alias: **karann**

**Comment by djee-ms** [comment]
`uap` also has `uap10.0` listed as equivalent (between brackets). But then on the next line `uap10.0` also appears alone. Why? This just creates confusion.

**Comment by JonDouglas** [comment]
@djee-ms I believe this doc best answers the question: https://docs.microsoft.com/en-us/dotnet/standard/frameworks

There are two docs about frameworks, one from dotnet & one from NuGet. Perhaps we should refer to a single source of truth instead.

**Comment by djee-ms** [comment]
Now I am 10 times more confused. That new links says that:
- `win` is deprecated in favor of `netcore45` (what?!), which seems to be for "Windows Store" (re-what?! isn't Windows Store = UWP, and not Desktop?)
- `win10` is same as `uap10.0` (what?!)

How do we package our C# library which P/Invoke into our Desktop and UWP native C++ DLLs into our NuGet packages?

**Comment by JonDouglas** [comment]
@djee-ms This is a very confusing area because of the names that are used here.

One tool I believe that may help you is this tool our team put together a little bit ago that we keep updated:

https://nugettoolsdev.azurewebsites.net/5.8.0/framework-precedence

For example if you see something is deprecated in favor of another framework, you'll be able to see the precedence.

I believe the major confusion that is here is that `netcore45` represents a name that predates `netcoreapp`. So these `netcore` names represent the Universal Windows Platform[uap10.0/win10/etc]

**Comment by zivkan** [comment]
@JonDouglas this is about runtime identifiers (RIDs), not frameworks. NuGet gets passed these values, including the path to a json file which contains the compatibility graph, so we're not really experts in this area.

Maybe a link to this doc is all we need, or a simple first step until someone can read and understand that doc, then re-write this doc as required: https://docs.microsoft.com/en-us/dotnet/core/rid-catalog

**Comment by JonDouglas** [comment]
@zivkan The confusion is that the .NET doc says:

> A target framework is typically referenced by a TFM. The following table shows the target frameworks supported by the .NET SDK and the NuGet client. Equivalents are shown within brackets.

The framework precedence seems to also show the equivalents of these TFMs.

I believe RIDs use the bracket notation which doubly adds confusion.

**Comment by zivkan** [comment]
yeah, sorry, my previous comment was wrong. The linked docs is the TFM list, and it does list some TFMs starting with `win`. Even I have absolutely no idea what these are or what they're for.

**Comment by djee-ms** [comment]
Yeah well in any case it would be good to find someone with clear knowledge of that who can rewrite those 2 documentation pages (or at least the NuGet one) and answer the question in particular of where native DLLs go. It's already difficult to work with native DLLs and NuGet, but we don't even understand how to package them. And this is a widespread issue because I've asked other teams who also are confused.

**Comment by JonDouglas** [comment]
@diverdan92, @rconard, @terrajobst may be able to help or direct someone who can help us.

**Comment by zivkan** [comment]
@djee-ms if you're creating a package for native (c++) projects, then I'm pretty sure you should use the `native` fake TFM (`/build/native/packageid.[props|targets]`). My guess about the `win` and `win8` TFMs is that they're related to the Windows 8 UWP, which is not the same thing as native.

If you're creating a .NET package which P/Invokes a native dll that you need to include, I created [this epic issue](https://github.com/NuGet/docs.microsoft.com-nuget/issues/2070) to track customer requests for exactly this in a single place to make it more clear to managers and PMs that this is a pain point. Let me know, so I can link this issue, but please also 👍  that issue to help it bubble up higher. I feel like I have about 70% confidence I know how these packages should be packaged, but the time to test to gain more confidence, and then the time required to write easy to understand docs is very much non-trivial, so I'll only be able to do it myself if I have no other higher priority work.

**Comment by djee-ms** [comment]
@zivkan yes this is the same as #2070, we have a C# wrapper over a set of native C++ DLLs, which all must be packaged together inside a NuGet for use by our customers in their C# app. I can very confidently tell you, for having been through this on multiple projects and still not understanding it, and having discussed it with many colleagues, that this is a monumental pain and the documentation is severely lacking.

**Comment by djee-ms** [comment]
Thanks for re-opening @nkolev92; is there any update on clarifying those TFMs?
