### ISSUE TITLE
Cannot override/change global packages default directory

### ISSUE THREAD

**Issue by KyleC69** [NuGet/docs.microsoft.com-nuget#2261]
Using Fresh install of Windows 7 Pro and VS Community 2019 .Net Desktop Workload. 
I have been all through the documentation currently available for Nuget and I cannot seem to change the global directory used. I have tried environment variables, setting config via command line and VS default nuget.config file.  I can run <nuget locals all -list> 

> E:\code>nuget locals all -list
http-cache: e:\code\VS\httpNugetCache
global-packages: e:\code\VS\Packages
temp: C:\Users\Phil\AppData\Local\Temp\NuGetScratch
plugins-cache: e:\code\VS\NugetCache

> No matter what I seem to try Nuget restores the packages to the %User%\.Nuget folder

**Comment by erdembayar** [comment]
Can I ask why you're trying to override global packages path?

I tried to repro what you're doing. Here are steps which worked on my local.
1. You make above only effective for project/solution which you're working or all projects.
2. For effective all projects : Open C:\Users\yourusername\AppData\Roaming\NuGet\NuGet.Config
Add `<add key="globalPackagesFolder" value="C:\YourCustomNugetPackagesPath" />` into it.
For mine it looks like this:
```
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <packageSources>
    <add key="nuget.org" value="https://api.nuget.org/v3/index.json" protocolVersion="3" />
  </packageSources>
  <config>
     <add key="globalPackagesFolder" value="C:\NuGetProj\Packages" />
  </config>    
</configuration>
```
3. For make it only 1 solution/project then goto root of solution/project.
a. Create nuget.config file if it doesn't exist. (`dotnet new nugetconfig` creates it for you)
b. Open nuget.config file.
c. Add `<add key="globalPackagesFolder" value="C:\YourCustomNugetPackagesPath" />` into it.

For mine it looks like this:

```
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <packageSources>
    <!--To inherit the global NuGet package sources remove the <clear/> line below -->
    <clear />
    <add key="nuget" value="https://api.nuget.org/v3/index.json" />
  </packageSources>
  <config>
     <add key="globalPackagesFolder" value="C:\NuGetProj\Packages" />
  </config>  
</configuration>

```

Now restore your packages and check if it goes into new path.
Please let me know if it works for you.

**Comment by KyleC69** [comment]
I'm trying to move the cache to larger storage. Also trying to keep users
profile size to min.

**Comment by nkolev92** [comment]
I think @erdembayar response is self contained.

**Comment by KyleC69** [comment]
@erdembayar Thank you for your response. Your solution will limit the specified folder to only contain packages explicitly needed for project/solution {nuget.config at proj root}. which is my desired result.

Can the global cache at the global/user level config file be disabled?
When creating a new project I must create the nuget.config with packages folder key added before I create project or it will recreate the cache in the user folder. I have tried to enter a null/empty key value, but it seems to be ignored and a new global user cache is created.

I realize my situation may be a unique one. I am running on a 120GB USB flash drive with Ubuntu 20.04. Space is at a premium, portability a must. Creating bulk development drives for distribution with set parameters.

**Comment by erdembayar** [comment]
> @erdembayar Thank you for your response. Your solution will limit the specified folder to only contain packages explicitly needed for project/solution {nuget.config at proj root}. which is my desired result.
> 
> Can the global cache at the global/user level config file be disabled? When creating a new project I must create the nuget.config with packages folder key added before I create project or it will recreate the cache in the user folder. I have tried to enter a null/empty key value, but it seems to be ignored and a new global user cache is created.
> 
> I realize my situation may be a unique one. I am running on a 120GB USB flash drive with Ubuntu 20.04. Space is at a premium, portability a must. Creating bulk development drives for distribution with set parameters.

Not sure what you mean by disabling global/user level, you can override with some temp path which can be cleaned with cron job. With powershell you can create function that automate following for:
1. Ask for project name if empty set random value.
2. Creating new folder.
3. Create nuget.config with custom GPF in it.
4. Create project in it.
5. Restore
6. Open with VS.

I use similar setup with custom method to speed up development.

**Comment by KyleC69** [comment]
Thank you for your help
