### ISSUE TITLE
Inconsistent nuget.config boolean value casing

### ISSUE THREAD

**Issue by probablyadev** [NuGet/docs.microsoft.com-nuget#2264]
Of note:

1. Boolean values are a mix between `value="true"` and `value="True"` (compare [#bindingredirects-section](https://docs.microsoft.com/en-us/nuget/reference/nuget-config-file#bindingredirects-section) and [#packagerestore-section](https://docs.microsoft.com/en-us/nuget/reference/nuget-config-file#packagerestore-section)),
2. Documentation references code without markup (see [#bindingredirects-section](https://docs.microsoft.com/en-us/nuget/reference/nuget-config-file#bindingredirects-section)),
    - incorrect: "The default is false."
    - correct: "The default is `false`."
3. Casing differs between value description and its associated example (see [#packagerestore-section](https://docs.microsoft.com/en-us/nuget/reference/nuget-config-file#packagerestore-section)).

From memory, MSBuild handles Boolean comparisons in a case insensitive manner, though I could be wrong.
To reduce confusion for those new to the ecosystem and others referencing this page as the source of truth, it would be nice to see something along the lines of:

1. Consistent boolean values used across the page,
2. A note stating what boolean values are valid, or link to documentation that does this already.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0ea1390e-db36-6759-3095-ebab9d546fdb
* Version Independent ID: ca88d8c6-0515-a267-aac3-a508c54157ab
* Content: [nuget.config File Reference](https://docs.microsoft.com/en-us/nuget/reference/nuget-config-file)
* Content Source: [docs/reference/nuget-config-file.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/master/docs/reference/nuget-config-file.md)
* Product: **nuget**
* GitHub Login: @karann-msft
* Microsoft Alias: **karann**

**Comment by zivkan** [comment]
This seems useful and hopefully not too difficult to update.
