### ISSUE TITLE
Document NU1004 NuGet error code

### ISSUE THREAD

**Issue by dominoFire** [NuGet/docs.microsoft.com-nuget#2266]
There's no doc page for NU1004 NuGet log code.

The log code is related to locked file features.

https://github.com/NuGet/NuGet.Client/blob/af1a9a055f56131d753573bade4a2c2654440faa/src/NuGet.Core/NuGet.Common/Errors/NuGetLogCode.cs#L77

**Comment by nkolev92** [comment]
Dups in https://github.com/NuGet/docs.microsoft.com-nuget/issues/1257 and https://github.com/NuGet/docs.microsoft.com-nuget/issues/1441
