### ISSUE TITLE
How to install Nuget Packages by Framework?

### ISSUE THREAD

**Issue by mageshsankar** [NuGet/docs.microsoft.com-nuget#2267]
Im using below code to install nuget packages in CI process, but i need download particular framework one package

Example: I need to download net50 framework package alone and i dont want to install other frameworks such as net46, net451

`Cake.Common.Tools.NuGet.NuGetAliases.NuGetInstall(context, packageid, new NuGetInstallSettings
                        {
                            NoCache = true,
                            OutputDirectory = "../Packages",
                        });`

is there any setting download Nuget package by framework ?

Question: 2

How to download nuget package without its dependencies?

**Comment by JonDouglas** [comment]
@mageshsankar 

1. `nuget install <Package ID> -Framework <Framework>`
2. `nuget install <Package ID> -DependencyVersion Ignore`

I'm not exactly sure what you're trying to do, but installing a package usually will result in the full `.nupkg` which includes the frameworks & dependencies.

There's not really great support for either of these scenarios, and we'd have to understand what API Cake uses under the hood to invoke the NuGet install command too.
