### ISSUE TITLE
The "typical" nuspec is out of date and missing dependency groups

### ISSUE THREAD

**Issue by StingyJack** [NuGet/docs.microsoft.com-nuget#2269]
This is important to include because failure to use dependency groups will result in pack warnings (or errors).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f35f4267-e5e3-ddcf-d3e4-479fb233ce9f
* Version Independent ID: 6d49d66f-f777-7e44-3a45-723e3ad09a59
* Content: [Create a NuGet package using nuget.exe CLI](https://docs.microsoft.com/en-us/nuget/create-packages/creating-a-package)
* Content Source: [docs/create-packages/Creating-a-Package.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/master/docs/create-packages/Creating-a-Package.md)
* Product: **nuget**
* GitHub Login: @karann-msft
* Microsoft Alias: **feaguila**

**Comment by JonDouglas** [comment]
We can update this doc to use an example like EF Core or something just to show groups.

```
     <dependencies>
      <group targetFramework=".NETStandard2.1">
        <dependency id="Microsoft.EntityFrameworkCore.Abstractions" version="5.0.1" exclude="Build,Analyzers" />
        <dependency id="Microsoft.EntityFrameworkCore.Analyzers" version="5.0.1" exclude="Build" />
        <dependency id="Microsoft.Extensions.Caching.Memory" version="5.0.0" exclude="Build,Analyzers" />
        <dependency id="Microsoft.Extensions.DependencyInjection" version="5.0.1" exclude="Build,Analyzers" />
        <dependency id="Microsoft.Extensions.Logging" version="5.0.0" exclude="Build,Analyzers" />
        <dependency id="System.Collections.Immutable" version="5.0.0" exclude="Build,Analyzers" />
        <dependency id="System.ComponentModel.Annotations" version="5.0.0" exclude="Build,Analyzers" />
        <dependency id="System.Diagnostics.DiagnosticSource" version="5.0.0" exclude="Build,Analyzers" />
      </group>
    </dependencies>
```

**Comment by StingyJack** [comment]
Unstale

**Comment by StingyJack** [comment]
This comment is an automatic reaction for an issue that has had its closure threatened by a stalebot.

**Comment by Mikejo5000** [comment]
Ported to: https://github.com/NuGet/Home/issues/13595
