### ISSUE TITLE
NuGet.org accepted licenses underspecified

### ISSUE THREAD

**Issue by gewarren** [NuGet/docs.microsoft.com-nuget#2274]
---
**Issue moved from dotnet/docs#20963**
- Please respond to @boringcactus.

---

_From @boringcactus on Wednesday, October 7, 2020 4:43:22 PM_

The documentation on the PackageLicenseExpression property says
> NuGet.org accepts only OSI or FSF approved licenses when using license type expression.

However, I tried to use the OSI-approved [zero-clause BSD license](https://opensource.org/licenses/0BSD), which is listed at the very top of [the SPDX version permalinked in that section of the docs](https://spdx.org/spdx-specification-21-web-version#h.luq9dgcle9mo), and it was rejected as unsupported. Evidently only a subset of OSI or FSF approved licenses are allowed by NuGet.org, in which case the documentation should say which ones are allowed.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 06a19d7d-253d-f17f-6421-624c9867473d
* Version Independent ID: cc37eb17-f715-080c-7bfc-9eae868d50ba
* Content: [.nuspec File Reference for NuGet](https://docs.microsoft.com/en-us/nuget/reference/nuspec#license)
* Content Source: [docs/reference/nuspec.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/master/docs/reference/nuspec.md)
* Product: **nuget**
* GitHub Login: @karann-msft
* Microsoft Alias: **karann**

**Comment by gewarren** [comment]
---
**Issue moved from dotnet/docs#20963**
- Please respond to @tdykstra.

---

_From @tdykstra on Wednesday, October 7, 2020 6:12:59 PM_

cc @rrelyea @nkolev92

**Comment by agr** [comment]
@boringcactus, could you please clarify what exactly fails in your case? I just tried publishing a package with `0BSD` license expression and it was published fine: https://www.nuget.org/packages/Andrei.0bsd/0.2.10

I found the we have trouble displaying the license text here: https://licenses.nuget.org/0BSD, we'll look into it.

**Comment by boringcactus** [comment]
honestly, this was so long ago that I forget what the error was.

**Comment by agr** [comment]
Didn't realize the original issue was from October. I will close the issue for now, if stumble across the repro, feel free to reopen the issue with details.
