### ISSUE TITLE
Documentation for Nuget packages with multiple frameworks lacks any valuable examples

### ISSUE THREAD

**Issue by nandox** [NuGet/docs.microsoft.com-nuget#2275]
The article is not clear enough, it's really missing some examples of how to create these Nuget packages from scratch. Some real, working code, with example of dependencies, is mandatory.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f1482e18-5f1f-3a8a-3321-66af52879ec5
* Version Independent ID: d70bd2f5-c04b-9207-62a0-4ecb6e8e5ca6
* Content: [Multi-targeting for NuGet Packages](https://docs.microsoft.com/en-us/nuget/create-packages/supporting-multiple-target-frameworks)
* Content Source: [docs/create-packages/Supporting-Multiple-Target-Frameworks.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/master/docs/create-packages/Supporting-Multiple-Target-Frameworks.md)
* Product: **nuget**
* GitHub Login: @karann-msft
* Microsoft Alias: **karann**

**Comment by JonDouglas** [comment]
Thanks for the feedback.

**Are you more interested in a walkthrough type of documentation then?** There are enough examples in this doc, they just don't really help walkthrough authoring a package from the ground up.

https://docs.microsoft.com/en-us/nuget/create-packages/supporting-multiple-target-frameworks#declaring-dependencies-advanced

One of the better resources for authoring is GitHub & seeing popular open source packages & how they create their `nuspec`:

https://github.com/Humanizr/Humanizer/blob/master/NuSpecs/Humanizer.nuspec

or downloading the package from NuGet.org & viewing a .nuspec directly.

https://www.nuget.org/api/v2/package/Microsoft.EntityFrameworkCore/5.0.1
