### ISSUE TITLE
Please include warning that Azure Artifacts does not support snupkg

### ISSUE THREAD

**Issue by hansmbakker** [NuGet/docs.microsoft.com-nuget#2282]
Azure Artifacts does not support snupkg according to https://github.com/dotnet/sourcelink/blob/master/README.md and multiple other pages online.

Given that there was no mention of this at all on the documentation page I was quite disappointed. I would have expected a note on this page instead of finding out about it on another page after following all instructions.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 22767e96-d56f-aa81-f1ca-17e256ed617e
* Version Independent ID: d7cdc676-2705-3cb1-bcd6-d1637460d5c7
* Content: [How to publish NuGet symbol packages using the new symbol package format '.snupkg'](https://docs.microsoft.com/en-us/nuget/create-packages/symbol-packages-snupkg)
* Content Source: [docs/create-packages/Symbol-Packages-snupkg.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/master/docs/create-packages/Symbol-Packages-snupkg.md)
* Product: **nuget**
* Technology: ****
* GitHub Login: @cristinamanu
* Microsoft Alias: **cristinamanu**

**Comment by hansmbakker** [comment]
This is not completed @cristinamanum 

#please-reopen

**Comment by tlogik** [comment]
It is really disappointing that Azure Devops Artifacts still does not support snupkg.
It is not really a new standard so what is going on Microsoft?

**Comment by coding-bunny** [comment]
Any update on this?
It's really sad to see this platform being neglected so badly.

**Comment by gioce90** [comment]
Can we have any news?

**Comment by nkolev92** [comment]
Hey all, 

Please file Azure DevOps feedback to ask for that support. 

https://learn.microsoft.com/en-us/azure/devops/user-guide/provide-feedback?view=azure-devops and https://developercommunity.visualstudio.com/AzureDevOps?

**Comment by hansmbakker** [comment]
@nkolev92 I opened this issue to ask for documentation pointing out that this is not supported so that people don't lose time on it.

Can you please reopen this issue? Or did you really mean to say "we're not going to document this"?

**Comment by coding-bunny** [comment]
What's unusual is that Microsoft's own products don't support this, and that enough people are asking about this everywhere, yet Microsoft's answer is "Please post here"

**Comment by nkolev92** [comment]
This issue was filled on Jan 19, 2021, on Aug 17, 2021, the following note was added: https://github.com/NuGet/docs.microsoft.com-nuget/commit/94e47116a87a67e83ad213ce4bc6bcc73aad6d11, so the current do mention that. 

Regarding the feature ask, you can follow that on https://developercommunity.visualstudio.com/t/add-snupkg-support-to-azure-devops-artifacts/657354.
