### ISSUE TITLE
Gaps in `Push a package` documentation

### ISSUE THREAD

**Issue by p4paul** [NuGet/docs.microsoft.com-nuget#2291]
### (section) Push a package

1. Missing `/` on end of url `PUT https://www.nuget.org/api/v2/package`
(tested with `nuget push <package>` command, it's possible other tools behave differently, but this should be noted.)

2. **Multipart form data** explanation does not mention that the multi-part section is named `package`.

3. **Relist a package** section does not have a sub section for the **Request body**.  The POST could use Multipart form data (as in the earlier PUT), but there is no mention.  I can only assume that it does not.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6f5691c1-f008-bbbf-a086-d9e665b5c332
* Version Independent ID: f255cc99-1041-ca5c-d2e5-5981e450a236
* Content: [Push and Delete, NuGet API](https://docs.microsoft.com/en-us/nuget/api/package-publish-resource)
* Content Source: [docs/api/package-publish-resource.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/master/docs/api/package-publish-resource.md)
* Product: **nuget**
* GitHub Login: @joelverhagen
* Microsoft Alias: **jver**

**Comment by JonDouglas** [comment]
Thanks for the report! We'll look into improving this with your feedback.
