### ISSUE TITLE
SDK-style equivalent is not mentioned

### ISSUE THREAD

**Issue by gregsonian** [NuGet/docs.microsoft.com-nuget#2297]
I am trying to update a template's nuspec to a SDK-style csproj file. The documentation states to use the command-line option. It does not explicitly state whether there is an equivalent setting within the SDK-style csproj file for NuGet templates. Furthermore, IntelliSense also does not know about this option. After adding the following field to my SDK-style csproj file, it appears to satisfy the requirements:
```
<PropertyGroup>
  <NoDefaultExcludes>true</NoDefaultExcludes>
</PropertyGroup>
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ac8072e2-f469-88e5-5739-88323a09e28d
* Version Independent ID: 809d67c7-2ffe-ed10-2e1e-bf6c27bf5f21
* Content: [NuGet Warning NU5119](https://docs.microsoft.com/en-us/nuget/reference/errors-and-warnings/nu5119)
* Content Source: [docs/reference/errors-and-warnings/NU5119.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/master/docs/reference/errors-and-warnings/NU5119.md)
* Product: **nuget**
* GitHub Login: @mishra14
* Microsoft Alias: **jodou**

**Comment by JonDouglas** [comment]
This doesn't seemed documented well. Thanks for the report!

The properties available would be found here https://docs.microsoft.com/en-us/nuget/reference/msbuild-targets

From this issue https://github.com/NuGet/Home/issues/6450 it seems that you could use `NoPackageAnalysis` to turn this off.

But there's also https://stackoverflow.com/questions/51102177/how-to-use-nodefaultexcludes-when-creating-a-nuget-package which suggests you may be able to use it.

@nkolev92 or @zkat any idea if this property is supported for SDK-style / dotnet?

We can document this formally in the MSBuild location & this warning area if so.

**Comment by nkolev92** [comment]
If you really want to disable something, it's preferable that NoWarn and the code is used instead of blanket disabling package analysis. 

The property is supported. My guess as to why the SDK property is never mentioned is because this scenario is primarily hit when using a nuspec.
