### ISSUE TITLE
The list of supported frameworks does not include the net5.0 target framework moniker

### ISSUE THREAD

**Issue by 0xced** [NuGet/docs.microsoft.com-nuget#2307]
With .NET 5 officially released the list of supported frameworks should be updated to include the `net5.0` target framework moniker (TFM).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0a0f5267-208d-8af2-ef18-dae7407eefad
* Version Independent ID: 19b00f91-5d31-0d4d-388b-30b1bd4e7c0f
* Content: [Target Frameworks Reference for NuGet](https://docs.microsoft.com/en-us/nuget/reference/target-frameworks#feedback)
* Content Source: [docs/reference/target-frameworks.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/master/docs/reference/target-frameworks.md)
* Product: **nuget**
* GitHub Login: @JonDouglas
* Microsoft Alias: **jodou**

**Comment by JonDouglas** [comment]
Thanks for the report. We have an outdated TFM guide. It really should be consolidated into https://docs.microsoft.com/en-us/dotnet/standard/frameworks#latest-versions which is updated regularly compared to https://docs.microsoft.com/en-us/nuget/reference/target-frameworks

Perhaps we can add a note to this page to point to the latest doc or redirect ours entirely.
