### ISSUE TITLE
Document package build assets (MSbuild props and targets)

### ISSUE THREAD

**Issue by natemcmaster** [NuGet/docs.microsoft.com-nuget#231]
_Apologies if this is already documented, but I couldn't find it._

It would be good to document how the `build/` and `buildMultiTargeting/` folders work in a nuget package and how MSBuild imports them.

```
build/<tfm>?/<packageId>.props
build/<tfm>?/<packageId>.targets
buildMultiTargeting/<tfm>?/<packageId>.props
buildMultiTargeting/<tfm>?/<packageId>.targets

? = optional folder
```

cc @emgarten

**Comment by emgarten** [comment]
``Build`` is used when ``$(TargetFramework)`` is set, the behavior is the same as before.
``BuildMultiTargeting`` is used when ``$(TargetFramework)`` is not set, this is often called the outer build and what is hit before iterating on each TFM.

**Comment by CamSoper** [comment]
Rolling up to #777
