### ISSUE TITLE
Install Package needs a --target Folder option (for virus/Security Check)

### ISSUE THREAD

**Issue by weedkiller** [NuGet/docs.microsoft.com-nuget#2317]
Hello, the install folder needs an option, so that the once downloaded it can be scanned by a virus checker or other security steps in a workflow/company process.

Also, it needs to be able to accept a list that matches a pattern.

**Comment by JonDouglas** [comment]
Please open up an issue on https://github.com/NuGet/Home/issues for any feedback requests.

https://github.com/NuGet/Home/blob/dev/CONTRIBUTING.md#before-submitting-an-issue

https://github.com/NuGet/Home/blob/dev/CONTRIBUTING.md#suggestions-and-feature-requests
