### ISSUE TITLE
Manage Nuget Packages wants to update packages outside of floating range

### ISSUE THREAD

**Issue by crazycrank** [NuGet/docs.microsoft.com-nuget#2319]
A dependency we have in our project introduced a breaking change in the latest major update (6.x), and we decided to stay on the latest 5.x version, configuring the PackageReference as `<PackageReference Version="5.*" />`.

This works as expected, running `dotnet list package` on the project resolves the version to the latest available 5.x version, 5.2.4 to be exact. We want this behavior to ensure, that if for some reason another package version in the 5.x version is released, we get the latest version.

The problem is, that this behavior is ignored when using "Manage NuGet Packages..." in Visual Studio. The utility then proposes to update the version to the latest stable version, which would again introduce the bug mentioned above, introducing the possibility for accidental package upgrades. 

The Visual Studio Tooling should respect this setting and not give us the option to upgrade the package, when we explicitly set it to a version in the 5.* range.

Another thing we tried was to use version ranges, like `(,6.0]`. But version ranges seem to be more or less useless, as they always resolve to the lowest version that complies with the range, which would be 1.0.0 in this case. Visual Studio does respect the configuration in this case though, not proposing an update to the latest 6.x version in this case.

So, I guess I have 2 questions:
* Is the behavior in the nuget tool in visual studio when configuring a 5.* version a bug or intended behavior?
* Is it planned to allow defining version range which resolves to the highest matching version, instead of the lowest one? npm solves this with the `~` and `^` operators ([npm semver docs](https://docs.npmjs.com/cli/v6/using-npm/semver)). Is there something similar planned for nuget, and if not, what is the reason behind it?

**Comment by JonDouglas** [comment]
@crazycrank This sounds more like a product defect than a docs issue. Can you report this in https://github.com/NuGet/Home/issues ?

The two questions you have are great to bring up in separate issues.

1. A potential bug in Visual Studio Package Manager experiences
2. A feature request for SemVer compliant version ranges that changes the resolution behavior.

Given this is not a docs issue but product feedback, I'm closing this issue.

/cc @donnie-msft @chgill-MSFT @zkat
