### ISSUE TITLE
Add warning about flattening behavior to "architecture-specific folders"

### ISSUE THREAD

**Issue by zarenner** [NuGet/docs.microsoft.com-nuget#2322]
NuGet / dotnet publish supports copying platform-specific files via the `runtimes/{platform}-{architecture}/native` pattern. This is documented at https://docs.microsoft.com/en-us/nuget/create-packages/supporting-multiple-target-frameworks#architecture-specific-folders.

However, due to a supposedly [by-design behavior](https://github.com/dotnet/sdk/issues/9643#issuecomment-426767189), when publishing a platform-specific project the files under `{platform}-{architecture}\native` lose their hierarchy.

As a trivial example:
* Using `dotnet publish` to publish a cross-platform project might produce a structure:
  `net5.0/publish/runtimes/unix/native/subdir/unix.txt`
* Using `dotnet publish -r linux-x64` would produce the structure:
  `net5.0/linux-x64/publish/unix.txt`
  
While it's expected that the `runtimes/unix` hierarchy is lost, it's surprising that the `subdir` folder is also lost.

Whether or not this behavior is actually by design (a follow-up question in the linked issue was unanswered), it should be documented. It has caused other bugs, e.g. https://github.com/microsoft/playwright-sharp/issues/1145

**Comment by sjoerd222888** [comment]
Please decide whether behavior is desired. If not please close this issue and fix the issue. If yes please document it and then I know I am in trouble ;-).
