### ISSUE TITLE
Installing the nuget package from the package manager console in Visual Studio does nothing

### ISSUE THREAD

**Issue by tudorsibiu90** [NuGet/docs.microsoft.com-nuget#2334]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2942156d-9578-6b8a-6149-84724c6b1b56
* Version Independent ID: bface2dd-2e2d-ce98-8bda-21525bb0bf79
* Content: [Install and manage NuGet packages using the console in Visual Studio](https://docs.microsoft.com/en-us/nuget/consume-packages/install-use-packages-powershell)
* Content Source: [docs/consume-packages/install-use-packages-powershell.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/master/docs/consume-packages/install-use-packages-powershell.md)
* Product: **nuget**
* GitHub Login: @JonDouglas
* Microsoft Alias: **jodou**

**Comment by JonDouglas** [comment]
Hi @tudorsibiu90,

For us to help assist you, we're going to need some more information such as what happened, what you expected to happen, any type of logs you have, and information as to what package & the project you're trying to install the package into.
