### ISSUE TITLE
Create tutorial on how to make deterministic packages

### ISSUE THREAD

**Issue by loic-sharma** [NuGet/docs.microsoft.com-nuget#2335]
We should have a guide that covers the great content here: https://www.youtube.com/watch?v=PCGlSt1WAOo&ab_channel=CodeWithStu

Inspired by this Tweet: https://twitter.com/i_no_see_pound/status/1365354190013366276?s=20

**Comment by JonDouglas** [comment]
There's also this current proposal:

https://github.com/dotnet/designs/blob/main/accepted/2020/reproducible-builds.md

**Comment by loic-sharma** [comment]
The [`dotnet validate package.nupkg`](https://github.com/dotnet/designs/blob/main/accepted/2020/reproducible-builds.md#design) is interesting. I wonder if that should be added to the [`dotnet nuget verify` commmand](https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-nuget-verify)?
