### ISSUE TITLE
Broken Link in Related Artickes

### ISSUE THREAD

**Issue by rido-min** [NuGet/docs.microsoft.com-nuget#2336]
The link `Verify signed packages using the dotnet CLI` returns 404

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a43491eb-360f-b3ad-9718-12eef3b33862
* Version Independent ID: 486b96d8-3a28-2a44-072d-99fb64c415de
* Content: [Signed Packages](https://docs.microsoft.com/en-us/nuget/reference/signed-packages-reference)
* Content Source: [docs/reference/Signed-Packages-Reference.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/master/docs/reference/Signed-Packages-Reference.md)
* Product: **nuget**
* GitHub Login: @rido-min
* Microsoft Alias: **rmpablos**

**Comment by JonDouglas** [comment]
This link needs to drop the `.md`. We'll get to it or someone can pick this up as a first issue :)

**Comment by riri-yu** [comment]
Hi! I'm trying to contribute to open source, and I want a first issue. Would you mind assigning me this?

**Comment by JonDouglas** [comment]
@riri-yu wonderful! If you have any questions about contributing, let me know or see our README of the contributing workflow for a general idea! I'll help review your PR when you're ready.

**Comment by riri-yu** [comment]
Thanks for this great opportunity!
