### ISSUE TITLE
Wrong error message

### ISSUE THREAD

**Issue by ygoe** [NuGet/docs.microsoft.com-nuget#2337]
There's another possible issue with this error message: It's just wrong. See https://github.com/dotnet/sdk/issues/16148

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b2c2eb22-045b-1c00-512a-a9eb1be4d784
* Version Independent ID: 87d10a7f-725b-18ef-d5ae-12b2f1c568b3
* Content: [NuGet Error NU1202](https://docs.microsoft.com/en-us/nuget/reference/errors-and-warnings/nu1202)
* Content Source: [docs/reference/errors-and-warnings/NU1202.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/master/docs/reference/errors-and-warnings/NU1202.md)
* Product: **nuget**
* GitHub Login: @zhili1208
* Microsoft Alias: **lzhi**

**Comment by JonDouglas** [comment]
Please provide concrete suggestions as to what is wrong with this error message. This error message is one of the more popular error messages & will be thrown in cases where your target framework is not compatible with a package. The package in question here is a `DotNetTool` which may not behave in the same way a `Dependency` does.

**Comment by ygoe** [comment]
Sorry, I can't remember where I've seen that message. But if you say this error code stands for all sorts of issues, then *this* may just be the issue. It should probably be replaced by more specific useful error codes.

Meanwhile I've learned that there are two ways to write .NET tools. The old one that only supports .NET Core 2.x, and the new one that only supports .NET Core 3.x and newer. I've switched my two tools from the old to the new way today. So the issue is resolved for me. Documentation wasn't helpful, a whole lot of googling found me another GitHub issue that actually explained me what the trouble was.

**Comment by JonDouglas** [comment]
No worries, if there is a specific scenario that can make better use of its own code, let us know! It's a bit harder to decipher a number of issues as to what we should do. Can you help summarize what you think would make this a better experience for you from your perspective?
