### ISSUE TITLE
No information how to restore a project or solution

### ISSUE THREAD

**Issue by micha-d** [NuGet/docs.microsoft.com-nuget#2340]
Hi,
on the page there is no information how to restore a project or solution from the commandline. Would be great if you could link that info.
Michael
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e7a0653a-ec3b-3b60-ae77-a51fedf1966e
* Version Independent ID: 90a503d7-6d0f-7b9e-4c2c-45f9a9705ac7
* Content: [NuGet Error NU1105](https://docs.microsoft.com/en-us/nuget/reference/errors-and-warnings/nu1105?f1url=%3FappId%3DDev16IDEF1%26l%3DEN-US%26k%3Dk(NU1105)%26rd%3Dtrue)
* Content Source: [docs/reference/errors-and-warnings/NU1105.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/master/docs/reference/errors-and-warnings/NU1105.md)
* Product: **nuget**
* GitHub Login: @zhili1208
* Microsoft Alias: **lzhi**

**Comment by rpanday** [comment]
Raised PR with information how to restore a project or solution from the commandline
