### ISSUE TITLE
Document NuGet security vulnerabilities & ingestion pipeline as FAQ

### ISSUE THREAD

**Issue by JonDouglas** [NuGet/docs.microsoft.com-nuget#2344]
Document various things about NuGet's security vulnerability feature such as:

- How the process works today
- What's expected by NuGet packages w/ public GitHub repos
- What's expected to be included in a CVE / MSRC
- The speed or delay on ingestion depending on the method
- Contact information if a CVE was missed.

**Comment by Tratcher** [comment]
- How to correct a false positive. E.g. version numbers or package names in the input data are wrong.
