### ISSUE TITLE
Microsoft.CodeAnalysis.VersionCheckAnalyzer.props not found

### ISSUE THREAD

**Issue by amsdbarreto** [NuGet/docs.microsoft.com-nuget#2351]
Message on Compiler say, Microsoft.CodeAnalysis.VersionCheckAnalyzer.props not found. 

I'm compiling a Windows Forms C# application, and the compiler issues an error message that says the file is missing, but I checked, and the file exists in the specified location.

**Comment by erdembayar** [comment]
@amsdbarreto 
Can you give us "package manager console" output or error log, screenshot? 
Not sure what problem you're facing this moment.
