### ISSUE TITLE
Update dotnet nuget verify doc as per the spec.

### ISSUE THREAD

**Issue by kartheekp-ms** [NuGet/docs.microsoft.com-nuget#2359]

**Comment by donnie-msft** [comment]
MSBuild official docs give a table format you may want to use if you decide to include your table.
https://docs.microsoft.com/en-us/visualstudio/msbuild/obtaining-build-logs-with-msbuild?view=vs-2019#verbosity-settings

Also, you can see that the Docs page wasn't clear, so someone had to ask what the different levels mean for MSBuild.
Consider too that localization may be more critical for wording involving security-related tasks. 
https://social.msdn.microsoft.com/Forums/en-US/43b87c20-f81a-4858-8a0f-7f4d1878f32f/msbuild-verbosity-type?forum=msbuild

**Comment by kartheekp-ms** [comment]
@donnie-msft - I created a PR in dotnet/docs repo for this issue. https://github.com/dotnet/docs/pull/23767. I addressed your comment. Please let me know if you have any other feedback, I will be happy to address it in the PR.

**Comment by kartheekp-ms** [comment]
dotnet/docs PR linked above has been merged. Hence closing this issue.
