### ISSUE TITLE
Please could you update the docs now that iconUrl is deprecated?

### ISSUE THREAD

**Issue by BenjaminCharlton** [NuGet/docs.microsoft.com-nuget#2363]
I'm looking for a step-by-step guide to putting an icon on my Nuget package using Visual Studio 2019 Community Edition. I.e. an icon that is displayed in Nuget when searching for packages.

1. In the first instance, where can I/should I save the icon? In the project root? In a directory below the project root? Can I save the file somewhere totally separate on my hard drive and rely on Visual Studio to pull it in when it makes the package?
2. I read somewhere that iconUrl is a deprecated attribute, but it's still being used in the example in: https://docs.microsoft.com/en-us/nuget/quickstart/create-and-publish-a-package-using-visual-studio-net-framework
3. Can I use the same icon for a bunch of projects? Say, all the projects in a certain solution?
4. If I'm having trouble with attaching the icon in the Pack tab of the Properties dialog of the csproj file, can I see an example of the XML that should be in my csproj file to make it work?

Any direction would be much appreciated.

Thank you! :-)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e8beb111-7b49-2fbe-eeb5-e485b6515ef2
* Version Independent ID: 22535840-0a27-797e-ebc8-5dbe447156d2
* Content: [Create and publish a .NET Framework NuGet package using Visual Studio on Windows](https://docs.microsoft.com/en-us/nuget/quickstart/create-and-publish-a-package-using-visual-studio-net-framework)
* Content Source: [docs/quickstart/create-and-publish-a-package-using-visual-studio-net-framework.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/master/docs/quickstart/create-and-publish-a-package-using-visual-studio-net-framework.md)
* Product: **nuget**
* GitHub Login: @JonDouglas
* Microsoft Alias: **jodou**

**Comment by dominoFire** [comment]
Hi,

> In the first instance, where can I/should I save the icon? In the project root? In a directory below the project root? Can I save the file somewhere totally separate on my hard drive and rely on Visual Studio to pull it in when it makes the package?

Ideally, it's better to save the package icon under the project folder. You can also save the icon anywhere else in your hard drive, but, you will need to rely on modifying the project file. See the comment linked in the next question.

> I read somewhere that iconUrl is a deprecated attribute, but it's still being used in the example in: https://docs.microsoft.com/en-us/nuget/quickstart/create-and-publish-a-package-using-visual-studio-net-framework
Can I use the same icon for a bunch of projects? Say, all the projects in a certain solution?

See this comment: https://github.com/NuGet/Home/issues/9060#issuecomment-580446043

If I'm having trouble with attaching the icon in the Pack tab of the Properties dialog of the csproj file, can I see an example of the XML that should be in my csproj file to make it work?

See this example: https://github.com/NuGet/Samples/tree/main/PackageIconNuspecExample

Let me know if you have questions.

**Comment by aortiz-msft** [comment]
Closing based on the above comment. Let us know if something is missing in the docs.

**Comment by BenjaminCharlton** [comment]
Thank you! I'll give it a try today.
