### ISSUE TITLE
LiveFyre comment: Can source code transformation be avoided?

### ISSUE THREAD

**Issue by kraigb** [NuGet/docs.microsoft.com-nuget#237]
From https://docs.microsoft.com/en-us/nuget/create-packages/source-and-config-file-transformations#comments-container:

Source Code transformations (MyClass.cs.pp) seem to be applied during upgrade. I'm trying to include a sample class file, but I don't want it to be added back to the project every time the end-user updates the package. Is there a way around this?

**Comment by CamSoper** [comment]
Rolling up to #779
