### ISSUE TITLE
Target framework questions

### ISSUE THREAD

**Issue by kraigb** [NuGet/docs.microsoft.com-nuget#239]
From old docs issues list:
    https://github.com/NuGet/Home/issues/358 (Targeting)
    https://github.com/NuGet/Home/issues/720 (PCLs)
    https://github.com/NuGet/Home/issues/1160 (multi-targeting)
    https://github.com/NuGet/Home/issues/4331 (.NET compact)

From customer feedback:

1. What is the equivalent of the deprecated packages? when I create a .netcore library it import dnxcore50 which is deprecated? Should I replace it with netcoreapp1.0 or netcore50? 

2. Need some examples

**Comment by CamSoper** [comment]
Rolled up to #778
