### ISSUE TITLE
instructions for VS for Mac?

### ISSUE THREAD

**Issue by tele-bird** [NuGet/docs.microsoft.com-nuget#2394]
This seems to be Windows-specific.  Where is the VS for Mac instructions??

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a3b20c46-c5f1-3a2a-738d-8aa8e69cf10c
* Version Independent ID: 7055e752-859b-6106-6802-70010d0305d9
* Content: [NuGet Package Restore](https://docs.microsoft.com/en-us/nuget/consume-packages/package-restore)
* Content Source: [docs/consume-packages/Package-Restore.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/main/docs/consume-packages/Package-Restore.md)
* Product: **nuget**
* GitHub Login: @JonDouglas
* Microsoft Alias: **jodou**

**Comment by JonDouglas** [comment]
Visual Studio for Mac also has documentation around this subject!

https://docs.microsoft.com/en-us/visualstudio/mac/nuget-walkthrough?view=vsmac-2019

They should share similarities of automatic & manual restore.

**Comment by tele-bird** [comment]
@JonDouglas , thanks!  Probably these two pages should be linked together.

**Comment by JonDouglas** [comment]
@mrward or @jmatthiesen thoughts on above? 

@tele-bird we can probably add a Visual Studio for Mac section that links to the same doc provided above.
