### ISSUE TITLE
PackageId:jquery             # Match the package ID in an exact, case-insensitive manner  owner:microsoft              # Match the owner in an exact, case-insensitive manner  id:NuGet.Core                # Match any part of the ID property Id:"Nuget.Core" ID:jQuery id:jquery id:ui              # Search for multiple terms in the ID id:jquery tags:validation    # Search multiple properties  invalid:jquery ui            # Unsupported properties are ignored, so this                              # is the same as searching on ui

### ISSUE THREAD

**Issue by wilma-cyber** [NuGet/docs.microsoft.com-nuget#2407]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e3ad41c6-6549-e33b-407e-52357146f49a
* Version Independent ID: 741c3f86-a7c6-f48f-bc29-e49a439f7c61
* Content: [Finding and Choosing NuGet Packages](https://docs.microsoft.com/en-us/nuget/consume-packages/finding-and-choosing-packages#search-syntax)
* Content Source: [docs/consume-packages/Finding-and-Choosing-Packages.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/main/docs/consume-packages/Finding-and-Choosing-Packages.md)
* Product: **nuget**
* GitHub Login: @JonDouglas
* Microsoft Alias: **jodou**

**Comment by skofman1** [comment]
Spam
