### ISSUE TITLE
Clarify if NuGet Package readme content is included in search

### ISSUE THREAD

**Issue by mbranscomb** [NuGet/docs.microsoft.com-nuget#2413]
It would be useful to state on the [page for Package readmes](https://docs.microsoft.com/en-us/nuget/nuget-org/package-readme-on-nuget-org) if the content is included when searching/filtering packages (on NuGet.org itself or from within Package Manager). 

This will help package authors determine appropriate content to include when considering in relation to:
- https://docs.microsoft.com/en-us/nuget/reference/nuspec#description
- https://docs.microsoft.com/en-us/nuget/reference/nuspec#tags

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4e0f449e-7948-4b54-908f-f47d73ae9829
* Version Independent ID: c09940df-e65a-7bff-1e0d-58d95e6b78d0
* Content: [Package readme on NuGet.org](https://docs.microsoft.com/en-us/nuget/nuget-org/package-readme-on-nuget-org)
* Content Source: [docs/nuget-org/package-readme-on-nuget-org.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/main/docs/nuget-org/package-readme-on-nuget-org.md)
* Product: **nuget**
* GitHub Login: @chgill-MSFT
* Microsoft Alias: **chgill**

**Comment by chgill-MSFT** [comment]
@loic-sharma @joelverhagen any thoughts on if we should consider making README content searchable?

**Comment by joelverhagen** [comment]
It's a great idea and not implemented today. From the user's perspective README is kind of like a rich text description field. Description field is searchable so it just makes sense. 

There are some technical aspects we would need to consider but in general I love the idea.

**Comment by chgill-MSFT** [comment]
Made an issue for it 😊 https://github.com/NuGet/NuGetGallery/issues/8575
