### ISSUE TITLE
NuGet sign command doesn't need -configFile option

### ISSUE THREAD

**Issue by heng-liu** [NuGet/docs.microsoft.com-nuget#2416]
1. Follow up on comment https://github.com/NuGet/NuGet.Client/pull/3974#discussion_r618602039
So the following document need to be fixed: (remove -configfile option)
https://docs.microsoft.com/en-us/nuget/reference/cli-reference/cli-ref-sign
The dotnet command spec needs to remove -configfile option as well.

2. Follow up on comment https://github.com/NuGet/NuGet.Client/pull/3974#discussion_r632677617

**Comment by erdembayar** [comment]
@heng-liu @dtivel @kartheekp-ms 
I'm bit confused by this issue. `nuget verify` has `configFile` option, but `dotnet nuget verify` doesn't.
I'm working on to rectify as part of https://github.com/NuGet/Home/issues/10011
I believe we should have `configFile` option for [feature parity](https://github.com/NuGet/Home/issues/10774#issuecomment-1005318333).

**Comment by heng-liu** [comment]
Sorry, you're right. The verify command will need the trusted-signers info from config file.
So only the sign command doesn't need -configFile option.
I'll change the title and content in this issue.
