### ISSUE TITLE
Expand on NuGet package naming conventions & best practices

### ISSUE THREAD

**Issue by JonDouglas** [NuGet/docs.microsoft.com-nuget#2417]
Add the regex of words for nuget package names such as [`[a-zA-Z_0-9]`](https://docs.microsoft.com/en-us/dotnet/standard/base-types/character-classes-in-regular-expressions#word-character-w) to help users understand the allowed characters.

Additionally a link to https://docs.microsoft.com/en-us/dotnet/standard/design-guidelines/names-of-namespaces to help users understand what makes a good namespace name.

Add some clarification to the following pages:

https://docs.microsoft.com/en-us/nuget/reference/nuspec#id
https://docs.microsoft.com/en-us/nuget/create-packages/creating-a-package#choose-a-unique-package-identifier-and-setting-the-version-number

We should document what the most common package ID naming convention is even though Unicode is valid.

**Comment by erdembayar** [comment]
Please note unicode letters and `-, .` are supported in package name id.

**Comment by StingyJack** [comment]
If additional restrictions result from this, please be sure to differentiate between what is allowed on nuget.org/myget and what is allowed on private repository. They often have different needs and what is needed on a public repo will cripple a private repos or it's packages (PS1, config transform, etc)
