### ISSUE TITLE
Typo in description for NU5115

### ISSUE THREAD

**Issue by freeone3000** [NuGet/docs.microsoft.com-nuget#2418]
"Please scpecify" should be "Please specify"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 527ac382-888b-3e9a-747f-5f7461456aea
* Version Independent ID: e8049ab0-7edd-39b8-4dee-d8c2d9b3dcb1
* Content: [NuGet Warning NU5115](https://docs.microsoft.com/en-us/nuget/reference/errors-and-warnings/nu5115)
* Content Source: [docs/reference/errors-and-warnings/NU5115.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/main/docs/reference/errors-and-warnings/NU5115.md)
* Product: **nuget**
* GitHub Login: @mishra14
* Microsoft Alias: **jodou**

**Comment by eriawan** [comment]
@erdembayar 
I have submitted a PR that fix this: #2452 

Could you review it? thanks in advance! 🙂
