### ISSUE TITLE
cpprestsdk does not have a cpprestsdk.targets

### ISSUE THREAD

**Issue by cryolithic** [NuGet/docs.microsoft.com-nuget#2427]
[Enter feedback here]
As far as I can see in the git history, cpprestsdk has never had a cpprestsdk.targets file in /build. 

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c7064d86-7de7-1a58-393b-39a5281a9617
* Version Independent ID: 8efa557b-8b1e-6320-4640-5226b8983832
* Content: [Creating Native NuGet Packages](https://docs.microsoft.com/en-au/nuget/guides/native-packages)
* Content Source: [docs/guides/Native-Packages.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/main/docs/guides/Native-Packages.md)
* Product: **nuget**
* GitHub Login: @JonDouglas
* Microsoft Alias: **jodou**

**Comment by nkolev92** [comment]
@cryolithic 

I don't see `cpprestsdk` mentions in the doc, can you help us understand what you're referring to?
