### ISSUE TITLE
Nuget restore fails with "The specified path, file name, or both are too long. The fully qualified file name must be less than 260 characters, and the directory name must be less than 248 characters.. "

### ISSUE THREAD

**Issue by mattneerincx** [NuGet/docs.microsoft.com-nuget#2431]
NuGet Package restore failed for project ...: 
The specified path, file name, or both are too long. The fully qualified file name must be less than 260 characters, and the directory name must be less than 248 characters.. 
Please see Error List window for detailed warnings and errors.	

Using VS 2017 and getting this error building project, project builds fine from msbuild command line.

Why doesn't the error tell you anything useful like "which file" etc...

**Comment by StingyJack** [comment]
I got this recently and it was the projectName.nuget.assets.cache file that was eeking over the path limit when it tried to load the project. I didn't need that particular project at the time but found that there is a group policy setting to enable longer paths that I will try next time I have to work in that solution. Maybe that is something you can try if getting blocked by this?
