### ISSUE TITLE
Why does this give the advice of using dotnet.exe instead of nuget.exe? 

### ISSUE THREAD

**Issue by StingyJack** [NuGet/docs.microsoft.com-nuget#2438]
dotnet has less features per the feature section than nuget.exe. Why suggest an inferior tool?

Also nuget.exe may have its warts with regard to bad error messages but its been more reliable than dotnet for restoring packages. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3460a9b2-3b49-1cda-add2-14d26e217716
* Version Independent ID: 95b91106-faff-c7f6-3699-94d643b5cf73
* Content: [Installing NuGet client tools](https://docs.microsoft.com/en-us/nuget/install-nuget-client-tools)
* Content Source: [docs/install-nuget-client-tools.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/main/docs/install-nuget-client-tools.md)
* Product: **nuget**
* GitHub Login: @JonDouglas
* Microsoft Alias: **jodou**

**Comment by JonDouglas** [comment]
dotnet is the modern tooling and we suggest users to move to .NET Core+ if their scenario permits.
