### ISSUE TITLE
Translating keywords

### ISSUE THREAD

**Issue by zarzyckipawel** [NuGet/docs.microsoft.com-nuget#2440]
I was thinking that is obvious but maybe you are not aware of it. Your translations... (even though I always turn them off) whenever I enter a given site from google, the site is automatically translated. It could even be convenient, but please, mark keywords so that the automatic translation doesn't modify them. It sometimes results in all kinds of funny/problematic confusions.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6d00296b-ac62-3d6c-beea-b2042b63dc5b
* Version Independent ID: 587da972-dfde-88bc-9dc0-7c32dae3454b
* Content: [NuGet Command-Line Interface (CLI) Reference](https://docs.microsoft.com/en-us/nuget/reference/nuget-exe-cli-reference)
* Content Source: [docs/reference/nuget-exe-CLI-Reference.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/main/docs/reference/nuget-exe-CLI-Reference.md)
* Product: **nuget**
* GitHub Login: @JonDouglas
* Microsoft Alias: **jodou**

**Comment by JonDouglas** [comment]
@Mikejo5000 Can you assist here?

**Comment by Mikejo5000** [comment]
Nothing formatted as inline code or block code should get translated. It's important to capitalize corrrectly also, to assist the Loc team. If there's a particular word that is incorrectly getting localized, you can apply special markdown (but this shouldn't happen much). Details are here:
https://review.docs.microsoft.com/en-us/new-hope/specs/markdown/ignore-localization?branch=master
@zarzyckipawel Is there a particular keyword on the page that is getting translated?

**Comment by zarzyckipawel** [comment]
I am happy that you have a way of marking inline code. I actually commented on this page about a problem that I got an impression is all over miscrosoft docs. On this particular page the cli argument to nuget.exe - 'pack' is translated to 'pakuj'. The translation seems fine but I don't think nuget.exe would understand that in polish :)

**Comment by killergege** [comment]
I noticed the same issue, on [this page/section](https://learn.microsoft.com/en-us/nuget/consume-packages/package-references-in-project-files#controlling-dependency-assets), the `none` keyword in the Value column is translated in french (it shouldn't). This is the only value that is translated.
