### ISSUE TITLE
Docker build fails with "error : Unable to load the service index for source https://api.nuget.org/v3/index.json"

### ISSUE THREAD

**Issue by prasanthbangs2016** [NuGet/docs.microsoft.com-nuget#2447]
I have application code with dotnetcore5. i am trying to containerize with docker and dockerfile instruction as follows.However i have encoutered with NuGet.targets(131,5): error : Unable to load the service index for source https://api.nuget.org/v3/index.json.

Dockerfile
FROM mcr.microsoft.com/dotnet/aspnet:5.0 AS base
WORKDIR /app
EXPOSE 80

FROM mcr.microsoft.com/dotnet/sdk:5.0 AS build
COPY src src
RUN dir
RUN dotnet restore "src/Web/Web.csproj"

Please do the needful.

**Comment by joelverhagen** [comment]
Hello, apologies on the delay. If you're still having trouble, please open an issue here: https://github.com/NuGet/NuGetGallery/issues and we'll help you out.
