### ISSUE TITLE
"Issues fixed" link is not publicly available

### ISSUE THREAD

**Issue by niklaslundberg** [NuGet/docs.microsoft.com-nuget#2448]
Link to "List of all issues fixed in this release - 5.9.1" has URL https://app.zenhub.com/workspaces/nuget-client-team-55aec9a240305cf007585881/reports/release?release=6075f42efd068017639b4036 which is not publicly available.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f93564ce-3d70-69e6-8ccd-bc59af97ca0a
* Version Independent ID: 72d69b46-f981-3777-2d1f-29b16bda1019
* Content: [NuGet 5.9 Release Notes](https://docs.microsoft.com/en-us/nuget/release-notes/nuget-5.9)
* Content Source: [docs/release-notes/NuGet-5.9.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/main/docs/release-notes/NuGet-5.9.md)
* Product: **nuget**
* GitHub Login: @erdembayar
* Microsoft Alias: **eryondon**

**Comment by JonDouglas** [comment]
We should consider not using ZenHub to generate lists for release notes. That would solve this problem.

**Comment by nkolev92** [comment]
Starting with 6.2, the links are not zenhub based anymore.
