### ISSUE TITLE
SupportedFramework missing?

### ISSUE THREAD

**Issue by p4paul** [NuGet/docs.microsoft.com-nuget#2454]
SupportedFramework is not mentioned in the SearchQueryService Request parameters.

We see queries from VisualStudio 19 with a parameter supportedFramework.  For example:

`http://myserver:123/sampleNuGet/query-3.0.0-beta?q=&skip=0&take=26&prerelease=false&supportedFramework=net5.0&semVerLevel=2.0.0`

Kind regards,
Paul

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 289ebebf-7c50-531f-f560-952c5ad8a406
* Version Independent ID: 43ba59a2-e8b7-6ca6-6a2d-bf2cf83fc0a8
* Content: [Search, NuGet API](https://docs.microsoft.com/en-us/nuget/api/search-query-service-resource)
* Content Source: [docs/api/search-query-service-resource.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/main/docs/api/search-query-service-resource.md)
* Product: **nuget**
* GitHub Login: @joelverhagen
* Microsoft Alias: **jver**

**Comment by joelverhagen** [comment]
Hey @p4paul, this is a legacy parameter sent by the client that is unused on the server side (speaking for NuGet.org). We actually have a "search-by-TFM" feature in the works for NuGet.org web UI experience so it's possible this may have meaning in the future (or may be avoided and a new parameter is added -- we don't know yet), but currently it is totally ignored. In general, the API docs are meant to describe the agreed protocol being the NuGet client and server but there are cases where legacy behavior is on the server or client and is not documented. In this particular case the property has no use at all, so we left it undocumented. I hope this helps.
