### ISSUE TITLE
UWP package (C++) guide, the templated control is not visible

### ISSUE THREAD

**Issue by nelons** [NuGet/docs.microsoft.com-nuget#2458]
Hi,

This page provides a short guide for creating a Windows Runtime Component that includes a Templated Control, but after creating the nuget package (and installing into a new package), the templated control did not appear. There were no errors in following the guide, but I believe the guide is incomplete in what it is intended to accomplish.

For the sake of completeness, the default style in Generic.xaml for the control is:

    <Style TargetType="local:AwesomeImageControl" >
        <Setter Property="Template">
            <Setter.Value>
                <ControlTemplate TargetType="local:AwesomeImageControl">
                    <Border
                        Background="{TemplateBinding Background}"
                        BorderBrush="{TemplateBinding BorderBrush}"
                        BorderThickness="{TemplateBinding BorderThickness}">
                    </Border>
                </ControlTemplate>
            </Setter.Value>
        </Setter>
    </Style>

When I install the built nuget package into a test UWP App and add the control to the included MainPage with the following xaml (xmlns:ie="using:ImageEnhancer"), nothing is displayed on the page when the App is run.

        <ie:AwesomeImageControl
            Margin="10"
            Background="Red"
            BorderBrush="Black"
            BorderThickness="1" />

When looking at the AppX folder produced by a project that installs the nuget package vs a project that references the runtime component project within the same solution, I can see that the folder "(Id)\Themes" is missing in the project that installs the nuget package. This folder contains the Generic.xbf file produced by the compile.

I solved this by including the .xbf file in the files element for each build target in the .nuspec file. For example, this is for the x86 configuration:

    <file src="..\Debug\ImageEnhancer\ImageEnhancer\Themes\Generic.xbf" target="runtimes\win10-x86\native\ImageEnhancer\Themes" />

And then in the .targets file I included the following to copy the files to the AppX folder. I inserted this before the end of the 'Project' element:

  <Target Name="CopyContent" BeforeTargets="AssignTargetPaths">
    <ItemGroup>
      <AppxPackagePayload Include="$(MSBuildThisFileDirectory)..\..\runtimes\win10-$(ImageEnhancer-Platform)\native\ImageEnhancer\Themes\Generic.xbf">
        <TargetPath>ImageEnhancer\Themes\Generic.xbf</TargetPath>
      </AppxPackagePayload>
    </ItemGroup>    
  </Target>

After creating a new nuget package and updating the test project the control is successfully show with a black border and red background.

Additionally, when following the guide under the "Package the Component" heading, when running the command:

nuget pack ImageEnhancer.nuspec

I received the message:

WARNING: NU5128: Some target frameworks declared in the dependencies group of the nuspec and the lib/ref folder do not have exact matches in the other location. Consult the list of actions below:
- Add a dependency group for UAP10.0 to the nuspec

I got around this message by including the following within the "metadata" element within the .nuspec file.

    <dependencies>
      <group targetFramework="UAP10.0" />
    </dependencies>

I don't know if what I'm done is 'right' or the best way of dealing with the issues, but they appear to have worked for me ! Hope this is helpful for someone :)

Thanks,

Neale

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5842072b-8382-e7bb-7fd7-9e91cb4b4704
* Version Independent ID: c3e784d1-2aa7-9313-fcb6-bbbdb6ddb987
* Content: [Create NuGet Packages for the Universal Windows Platform](https://docs.microsoft.com/en-us/nuget/guides/create-uwp-packages)
* Content Source: [docs/guides/Create-UWP-Packages.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/main/docs/guides/Create-UWP-Packages.md)
* Product: **nuget**
* GitHub Login: @JonDouglas
* Microsoft Alias: **jodou**

**Comment by YourOrdinaryCat** [comment]
I hit this too with a packaged C++/WinRT control. In my case, the control worked on C# and C++/CX, but not C++/WinRT. I fixed it on my end with a slight tweak to your solution.

The `Generic.xbf` file can actually go under `lib\uap10.0`, and the XBF also shows up in the "Generated Files" directory, which makes things much simpler in the NuGet manifest:

`<file src="Generated Files\Themes\Generic.xbf" target="lib\uap10.0\ImageEnhancer\Themes" />`

And the targets get simpler too:

```XML
<Target Name="CopyContent" BeforeTargets="AssignTargetPaths">
	<ItemGroup>
		<AppxPackagePayload Include="$(MSBuildThisFileDirectory)..\..\lib\uap10.0\ImageEnhancer\Themes\Generic.xbf">
			<TargetPath>ImageEnhancer\Themes\Generic.xbf</TargetPath>
		</AppxPackagePayload>
	</ItemGroup>
</Target>
```

The docs should really be updated to reflect this, specially because I think it applies to WinUI 3 as well.

**Comment by YourOrdinaryCat** [comment]
Still worth documenting - not sure if my comment is the right way to go about it, would much rather have official confirmation.
