### ISSUE TITLE
Documentation of packageSourceCredentials mismatch between key-value-table and examples

### ISSUE THREAD

**Issue by daFritz84** [NuGet/docs.microsoft.com-nuget#2461]
There is a mismatch at the packageSourceCredentials section between the key-value-table and the examples.
i.e., the keys are all lowercase (username, password, ...) where as in the examples the keys are written in pascal case (Username, Password, ClearTextPassword, ...).

As to my knowledge, the Pascal Case is correct notation.

PS: I also noted, that the credentials in nuget are in Pascal Case, whereas everything else is written in Camel Case. Just a minor inconsistency, but annoying nontheless.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0ea1390e-db36-6759-3095-ebab9d546fdb
* Version Independent ID: ca88d8c6-0515-a267-aac3-a508c54157ab
* Content: [nuget.config File Reference](https://docs.microsoft.com/en-us/nuget/reference/nuget-config-file)
* Content Source: [docs/reference/nuget-config-file.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/main/docs/reference/nuget-config-file.md)
* Product: **nuget**
* GitHub Login: @JonDouglas
* Microsoft Alias: **jodou**

**Comment by daFritz84** [comment]
Just double-checked, the official documentation still contains this glitch. The keywords in the table are still Lower Case, while they should be written in Pascal Case.

**Comment by daFritz84** [comment]
Again, hust double-checked, the official documentation still contains this glitch. The keywords in the table are still Lower Case, while they should be written in Pascal Case.

Since this issue does not get much love: Shall I prepare a pull request?
I'm still determined to get this defect fixed somehow 😃. Although my attempts might be futile.

**Comment by Mikejo5000** [comment]
@daFritz84 A pull request would be great! We are moving away from GH issues for Doc feedback and will be closing down issues soon.

**Comment by Mikejo5000** [comment]
We apologize for the inconvenience. We are phasing out GitHub issues as the feedback mechanism on NuGet documentation content and replacing it with a new feedback system using the Feedback link within the articles. If you believe your feedback needs to be preserved and addressed, please submit a PR or open a new issue at https://github.com/NuGet/Home/issues
