### ISSUE TITLE
Is there a way to create NUPKG files without using Microsoft.NET.Sdk?

### ISSUE THREAD

**Issue by mike-christensen** [NuGet/docs.microsoft.com-nuget#2462]
I'd like to know if it's possible to create a CSPROJ file which outputs a .nupkg file, but doesn't use the Microsoft.NET.Sdk project type.  In my case, I'd like to create a nupkg but there's no code to compile.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 31da7408-981b-cc54-1791-ca39dbdbc091
* Version Independent ID: 2060c9e8-7f2e-5da1-ee19-d196f38339fe
* Content: [Create a NuGet package using MSBuild](https://docs.microsoft.com/en-us/nuget/create-packages/creating-a-package-msbuild)
* Content Source: [docs/create-packages/creating-a-package-msbuild.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/main/docs/create-packages/creating-a-package-msbuild.md)
* Product: **nuget**
* GitHub Login: @JonDouglas
* Microsoft Alias: **jodou**

**Comment by JonDouglas** [comment]
Related: https://github.com/NuGet/Home/issues/4254

At the moment, this scenario would be limited until the above is addressed. Thus I'm going to close this for now.
