### ISSUE TITLE
Need way to use ExcludeVersion in Nuget.config

### ISSUE THREAD

**Issue by varnk** [NuGet/docs.microsoft.com-nuget#2463]
I am using Nuget integrated with Visual Studio 2017.  I don't see a way to change the command line parameters for Nuget.  I need to have **-ExcludeVersion** option used when I download packages via Nuget in Visual Studio.  Is there a way to enable this command-line option via Nuget.config.  If not, I would like to submit this for a feature request.

**Comment by nkolev92** [comment]
Hey @varnk, 

There's no way to achieve that today, and we don't really think we want to support that at this point. 

Your question is about packages.config and at this point we're focusing on PackageReference experiences primarily. 
Furthermore, the packages folder is meant to be *shared* among projects, something that NuGet reads, but if we exclude the version we'd be breaking some of those Visual Studio project tied experiences.
