### ISSUE TITLE
Troubleshooting Guide for NuGet Client Frequently Asked Questions

### ISSUE THREAD

**Issue by donnie-msft** [NuGet/docs.microsoft.com-nuget#2465]
I've found users asking similar questions regularly, and believe a FAQ/Troubleshooting section on our docs page would be more discoverable, and reduce bug reports which may block the user on our reply. For example, TLS issues in Windows affect our product, so those users believe NuGet has a problem. An FAQ could provide some basic context, maybe a link, and some steps to check whether TLS is working as NuGet expects.

Example docs:
https://docs.microsoft.com/en-us/xamarin/android/troubleshooting/troubleshooting
https://docs.microsoft.com/en-us/nuget/resources/nuget-faq
There's also a self-serve docset with best practices here: https://docs.microsoft.com/en-us/style-guide/design-planning

My plan for now is to write-up what I have, then check with Justin Johnson (profexorgeek) or Mike Jones (Mikejo5000) to finalize formatting.

**Comment by joelverhagen** [comment]
@donnie-msft - should the Windows connection issue be a NuGet.org FAQ or a client FAQ? I don't have a strong feeling but perhaps @zhhyu can advise on any content you were planning for the client FAQ.

**Comment by anangaur** [comment]
https://github.com/NuGet/docs.microsoft.com-nuget/pull/2884

**Comment by anangaur** [comment]
It seems http response code for these errors are 101, so we might want to also document the response code to help with better indexing of the doc for related search queries on these issues.

**Comment by anangaur** [comment]
Some more context to help with prioritization: Users are hitting this Microsoft Q&A page frequently making it one of the most visited top FAQ pages as they do not find documentation for it on nuget docs (most likely reason): https://docs.microsoft.com/en-us/answers/questions/959588/visual-studio-2022-won39t-connect-to-nuget.html
