### ISSUE TITLE
Ask : http://go.microsoft.com/fwlink/?LinkID=322105

### ISSUE THREAD

**Issue by jlian168** [NuGet/docs.microsoft.com-nuget#2466]
Dear Sir : 

嚴重性	程式碼	說明	專案	檔案	行	隱藏項目狀態
錯誤		这台计算机上缺少此项目引用的 NuGet 程序包。使用“NuGet 程序包还原”可下载这些程序包。有关更多信息，请参见 http://go.microsoft.com/fwlink/?LinkID=322105。缺少的文件是 ..\SimpleMQTTBroker\packages\NETStandard.Library.2.0.0\build\netstandard2.0\NETStandard.Library.targets。	SimpleMQTT	D:\Test\C#\SimpleMQTT-master\SimpleMQTT.csproj	154	

I dont what happened! its from .csproj file
Can u help me...

Thank u.

**Comment by nkolev92** [comment]
Hi, 

We don't provide support for individual projects. 

Please refer to Q & A forums for help or developercommunity.visualstudio for bugs.
