### ISSUE TITLE
Sidebar link to nuspec schema page is broken

### ISSUE THREAD

**Issue by scottbommarito** [NuGet/docs.microsoft.com-nuget#247]
![nuspec broken sidebar link](https://cloud.githubusercontent.com/assets/18014088/24274839/5086cadc-0fe8-11e7-809f-a8056b4ae5cc.png)

The link cannot be followed.

The page itself (https://docs.microsoft.com/en-us/nuget/schema/nuspec) is fine.

**Comment by kraigb** [comment]
This is corrected now. Thanks for pointing it out.
