### ISSUE TITLE
Assets file... not found.  Already ran Restore several times.

### ISSUE THREAD

**Issue by jamesosb-msft** [NuGet/docs.microsoft.com-nuget#2474]
Would like more TSGs for when this "assets file" can't be found.  VS is telling me to run NuGet Restore, which I did several times.  The output looks like:
All packages are already installed and there is nothing to restore.
Time Elapsed: 00:00:00.1592831
========== Finished ==========

No idea what else to do; this was a brand new VM, new installation of VS, and I just cloned our repo.  For some reason, it tells me all NuGet packages are installed, yet when I build, it says to run NuGet restore.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 906d0438-0338-0167-3a38-d213ee187ddb
* Version Independent ID: b558fa0c-f549-1e6a-c2db-fd2e6a2351be
* Content: [Troubleshooting NuGet Package Restore in Visual Studio](https://docs.microsoft.com/en-us/nuget/Consume-Packages/Package-restore-troubleshooting)
* Content Source: [docs/consume-packages/Package-restore-troubleshooting.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/main/docs/consume-packages/Package-restore-troubleshooting.md)
* Product: **nuget**
* GitHub Login: @JonDouglas
* Microsoft Alias: **jodou**

**Comment by erdembayar** [comment]
Please note not all restore operation can be done with VS, some repositories include extra powershell(ps1) or bash script commands which brings extra packages. Also some cases npm/yarn used for front end package restore and nuget used for backend package restore. Please run them as instructed on repo readme guide.
I hope it helps, it you have more question then we need sample repo to investigate what is going on.
Thank you.
