### ISSUE TITLE
Confusion with package-name

### ISSUE THREAD

**Issue by mgwalm** [NuGet/docs.microsoft.com-nuget#2491]
Other pages in this doc series put great insistence on using a unique PackageId . They don't mention package-name, which this page seems to rely on.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6f32fcb5-8641-9062-83bd-2c8c09aab872
* Version Independent ID: 12404cbd-0105-957e-2875-bb91904fc359
* Content: [Overview and workflow of using NuGet packages](https://docs.microsoft.com/en-us/nuget/consume-packages/overview-and-workflow#ways-to-install-a-nuget-package)
* Content Source: [docs/consume-packages/Overview-and-Workflow.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/main/docs/consume-packages/Overview-and-Workflow.md)
* Product: **nuget**
* GitHub Login: @JonDouglas
* Microsoft Alias: **jodou**

**Comment by JonDouglas** [comment]
`<PACKAGE_NAME>` is commonly referred to given it is what the CLI expects in an argument:

`dotnet add [<PROJECT>] package <PACKAGE_NAME>`

https://learn.microsoft.com/en-us/dotnet/core/tools/dotnet-add-package#synopsis

This refers to a unique package ID or name for short.
