### ISSUE TITLE
Create a list of removed Public APIs for NuGet 6.0

### ISSUE THREAD

**Issue by dominoFire** [NuGet/docs.microsoft.com-nuget#2496]
In https://github.com/NuGet/NuGet.Client/pull/4020 , and https://github.com/NuGet/NuGet.Client/pull/4177 , we are planning to remove parameters from public APIs. This will be a breaking change.

This issue is for tracking all changed public APIs.

**Comment by nkolev92** [comment]
We have a way to do this automatically with a breaking change label.
