### ISSUE TITLE
MSBuild nuget package restore not working, no instructions

### ISSUE THREAD

**Issue by OMortensen** [NuGet/docs.microsoft.com-nuget#2500]
Trying to use msbuild to build our Web Application Project on our build machine (VS2019 not installed) and getting nuget package errors. Says to use nuget, but I don't have nuget(?) . How do I get the nuget packages to install?

I've already tried msbuild /t:pack

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 906d0438-0338-0167-3a38-d213ee187ddb
* Version Independent ID: b558fa0c-f549-1e6a-c2db-fd2e6a2351be
* Content: [Troubleshooting NuGet Package Restore in Visual Studio](https://docs.microsoft.com/en-us/nuget/Consume-Packages/Package-restore-troubleshooting)
* Content Source: [docs/consume-packages/Package-restore-troubleshooting.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/main/docs/consume-packages/Package-restore-troubleshooting.md)
* Product: **nuget**
* GitHub Login: @JonDouglas
* Microsoft Alias: **jodou**

**Comment by erdembayar** [comment]
Please check this [guide](https://docs.microsoft.com/en-us/nuget/consume-packages/package-restore#:~:text=Restore%20using%20MSBuild%201%20Open%20a%20Developer%20command,the%20following%20command%20to%20rebuild%20the%20project.%20). 
Please note: msbuild /t:pack is for packing not for restore, instead please try: msbuild /t:restore
Do you have packages.config or sdk style projects?
