### ISSUE TITLE
[Feature]: Improve deprecation docs

### ISSUE THREAD

**Issue by loic-sharma** [NuGet/docs.microsoft.com-nuget#2505]
### NuGet Product(s) Involved

NuGet.exe, Visual Studio Package Management UI, Visual Studio Package Manager Console, MSBuild.exe, dotnet.exe

### The Elevator Pitch

@chgill-MSFT asked I create an issue on NuGet/Home to track this:

>  ... Add more detail to the deprecation documentation to help the user take the right deprecation action based on their scenario, use the right reason, and understand when popularity transfer might be right for them.

**Comment by JonDouglas** [comment]
Here's some ideas for whoever picks this up:

https://learn.microsoft.com/en-us/nuget/nuget-org/deprecate-packages#deprecation-workflow

- Legacy should be the preferred option if a package is not maintained.
    - A suggested alternative should be included if there exists one. (also known as a redirect)
- Critical bugs should only be used if they aren't referring to a known security vulnerability. 
- Other should only be used as a last resort.

Also may be worth clarifying the language of "deprecated" here and also the workflows of unlisted vs. deprecated.

Deprecating a package means the package can still be useful, but it won't be supported nor potentially useful in the future. That users should no longer use it and/or move to a suggested alternative. This deprecated package will eventually become obsolete with time.

Unlisting is not an alternative to deprecation, it is more of a visibility characteristic.
