### ISSUE TITLE
Cannot follow instructions re. the project template

### ISSUE THREAD

**Issue by coxantohi** [NuGet/docs.microsoft.com-nuget#2506]
In the [Quickstart: Create and publish a NuGet package using Visual Studio (.NET Standard, Windows only)](https://docs.microsoft.com/en-us/nuget/quickstart/create-and-publish-a-package-using-visual-studio?tabs=netcore-cli) page, in the [Create a class library project](https://docs.microsoft.com/en-us/nuget/quickstart/create-and-publish-a-package-using-visual-studio?tabs=netcore-cli#create-a-class-library-project) section the following instruction can be found:

> 1. In Visual Studio, choose **File > New > Project**, expand the **Visual C# > .NET Standard** node, select the "Class Library (.NET Standard)" template, name the project AppLogger, and click **OK**.

But on my Visual Studio (16.10.4) with .net 5 sdk installed, I cannot find any "Visual C# > .NET Standard" node, and I don't have the "Class Library (.NET Standard)" template; The template that I've found is targetting ".NET Standard or .NET Core" and is titled "Class Library":
![image](https://user-images.githubusercontent.com/66870591/129342048-d3c4ff33-84d1-4ced-92e9-82790575a6fa.png)

Am I doing something wrong, or maybe are the instructions outdated?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 18071970-cf13-78af-ac1d-9adefefdb693
* Version Independent ID: 3bf15a5c-8b3e-0e69-0bf6-03b44654970c
* Content: [Create and publish a .NET Standard NuGet package - Visual Studio on Windows](https://docs.microsoft.com/en-us/nuget/quickstart/create-and-publish-a-package-using-visual-studio?tabs=netcore-cli)
* Content Source: [docs/quickstart/create-and-publish-a-package-using-visual-studio.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/main/docs/quickstart/create-and-publish-a-package-using-visual-studio.md)
* Product: **nuget**
* GitHub Login: @JonDouglas
* Microsoft Alias: **jodou**

**Comment by ianrathbone** [comment]
@JonDouglas / @coxantohi I have checked the documentation and can verify these have already been addressed in #2861 by @dksimpson
