### ISSUE TITLE
Poorly worded statement

### ISSUE THREAD

**Issue by dotMorten** [NuGet/docs.microsoft.com-nuget#2512]
The page stages the following:

> PackageReference is under active development: See PackageReference issues on GitHub. packages.config is no longer under active development.

This have had customers think this is a beta feature that shouldn't be used. Could the wording here be made clearer?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6a154e5f-436d-6297-ec05-4d134a2404f9
* Version Independent ID: 1c782e82-db9a-bf77-05ef-cd49374aee36
* Content: [Migrating from packages.config to PackageReference formats](https://docs.microsoft.com/en-us/nuget/consume-packages/migrate-packages-config-to-package-reference)
* Content Source: [docs/consume-packages/migrate-packages-config-to-package-reference.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/main/docs/consume-packages/migrate-packages-config-to-package-reference.md)
* Product: **nuget**
* GitHub Login: @JonDouglas
* Microsoft Alias: **jodou**

**Comment by anangaur** [comment]
Thanks for pointing it out. The whole line seems unnecessary IMO. Reminiscent of the past :)

**Comment by JonDouglas** [comment]
This issue was resolved via earlier PR
