### ISSUE TITLE
Author token explanation

### ISSUE THREAD

**Issue by Parkertg** [NuGet/docs.microsoft.com-nuget#2516]
The $author$ token is described etc but not the $authors$ token.. I'm fairly certain that the $author$ token is actually supposed to be authors

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 06a19d7d-253d-f17f-6421-624c9867473d
* Version Independent ID: cc37eb17-f715-080c-7bfc-9eae868d50ba
* Content: [.nuspec File Reference for NuGet](https://docs.microsoft.com/en-us/nuget/reference/nuspec)
* Content Source: [docs/reference/nuspec.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/main/docs/reference/nuspec.md)
* Product: **nuget**
* GitHub Login: @JonDouglas
* Microsoft Alias: **jodou**

**Comment by anangaur** [comment]
Can you elaborate?
