### ISSUE TITLE
Are property names PackageVersion, PackageVersionPrefix, and PackageVersionSuffix correct?

### ISSUE THREAD

**Issue by tdykstra** [NuGet/docs.microsoft.com-nuget#2522]
From https://github.com/dotnet/docs/pull/25751#issuecomment-909720591 (for more details, see the rest of the discussion in that issue):
 >I'm wondering if the "MSBuild property" names at https://docs.microsoft.com/en-us/nuget/reference/msbuild-targets#pack-target are even correct? I.e. `PackageVersion`, `PackageVersionPrefix`, and `PackageVersionSuffix`. [This article](https://andrewlock.net/version-vs-versionsuffix-vs-packageversion-what-do-they-all-mean/) says that, for example, the MSBuild properties `Version`, `VersionPrefix`, and `VersionSuffix` are used to set the value of `PackageVersion`, which is only visible in the build output.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 099102e8-c320-ef50-6821-57519684dc98
* Version Independent ID: 1523dac4-419d-613d-2497-4062f9efd358
* Content: [NuGet pack and restore as MSBuild targets](https://docs.microsoft.com/en-us/nuget/reference/msbuild-targets#pack-target)
* Content Source: [docs/reference/msbuild-targets.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/main/docs/reference/msbuild-targets.md)
* Product: **nuget**
* GitHub Login: @nkolev92
* Microsoft Alias: **nikolev**

**Comment by dsplaisted** [comment]
`PackageVersion` defaults to be the same as `Version`, and is probably what is actually used when you pack a project.

To me, it looks like there are no such properties as `PackageVersionPrefix` and `PackageVersionSuffix`.
