### ISSUE TITLE
Update Deprecation Screenshots

### ISSUE THREAD

**Issue by dominoFire** [NuGet/docs.microsoft.com-nuget#2525]
New Deprecation experiences were introduced in https://github.com/NuGet/NuGet.Client/pull/4144

We should update Deprecation screenshots and update instructions, if needed

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a01e821e-fdaa-ddeb-584c-e3d1af0ce964
* Version Independent ID: f919df6a-2e9e-d289-4628-f43d3330a9fe
* Content: [Deprecating packages on nuget.org](https://docs.microsoft.com/en-us/nuget/nuget-org/deprecate-packages#visual-studio)
* Content Source: [docs/nuget-org/Deprecate-packages.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/main/docs/nuget-org/Deprecate-packages.md)
* Product: **nuget**
* GitHub Login: @anangaur
* Microsoft Alias: **anangaur**

**Comment by JonDouglas** [comment]
Steps for whoever picks this up:

1. Download the most recent Visual Studio
2. Create a new project 
3. Install a couple of packages from the top list in Browse
4. Find a deprecated package such as `My.Sample.Lib` - https://www.nuget.org/packages/My.Sample.Lib/6.0.1
5. Take a screenshot of the installed tab.

**Comment by nkolev92** [comment]
Fixed in https://github.com/NuGet/docs.microsoft.com-nuget/pull/2906
