### ISSUE TITLE
An example of how to do this in Yaml probably wouldn't go amiss.

### ISSUE THREAD

**Issue by ScottKFraley** [NuGet/docs.microsoft.com-nuget#2527]
My title pretty much says it. : )

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a3b20c46-c5f1-3a2a-738d-8aa8e69cf10c
* Version Independent ID: 7055e752-859b-6106-6802-70010d0305d9
* Content: [NuGet Package Restore](https://docs.microsoft.com/en-us/nuget/consume-packages/package-restore)
* Content Source: [docs/consume-packages/Package-Restore.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/main/docs/consume-packages/Package-Restore.md)
* Product: **nuget**
* GitHub Login: @JonDouglas
* Microsoft Alias: **jodou**

**Comment by ScottKFraley** [comment]
I've lost all context on my comment at this point given that this was apparently 'posted' a year and ~3 months ago. If you guys can trace it back to the page against which I'd made this posting/comment/suggestion, then, well, my suggestion stands.

**Comment by nkolev92** [comment]
The primary feedback here is around having an example for yml, which is something specific to Azure DevOps than just NuGet.
