### ISSUE TITLE
Link to nuget in VS sample is broken

### ISSUE THREAD

**Issue by angelazhangmsft** [NuGet/docs.microsoft.com-nuget#2529]
![image](https://user-images.githubusercontent.com/69016571/133277074-096c6433-bf96-441f-b173-ea02a7ca96ea.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bbf9be6a-e7b0-b9b6-a3e8-8b5de3c6900d
* Version Independent ID: c12505c9-6f14-7111-2578-5c2664b4515d
* Content: [NuGet Packages in Visual Studio templates](https://docs.microsoft.com/en-us/nuget/visual-studio-extensibility/visual-studio-templates)
* Content Source: [docs/visual-studio-extensibility/Visual-Studio-Templates.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/main/docs/visual-studio-extensibility/Visual-Studio-Templates.md)
* Product: **nuget**
* GitHub Login: @JonDouglas
* Microsoft Alias: **jodou**

**Comment by nkolev92** [comment]
Should probably point to https://github.com/NuGet/Samples/tree/main/Preinstalled-Packages
