### ISSUE TITLE
Link to “NuGet Get Nearest Framework Tool” broken (403 Forbidden)

### ISSUE THREAD

**Issue by atifaziz** [NuGet/docs.microsoft.com-nuget#257]
The [link to **NuGet Get Nearest Framework Tool**](https://github.com/NuGet/docs.microsoft.com-nuget/blame/5839147ac2373a2e75a2cd08b74d3af9c48a9144/docs/Schema/Target-Frameworks.md#L131) is https://aka.ms/s2m3th but it's broken and yields a [403](https://httpstatuses.com/403).

**Comment by kraigb** [comment]
I just tried the aka.ms link and it seems to be working fine. Can you try again?

**Comment by atifaziz** [comment]
@kraigb Seems to be working again so closing the issue.
