### ISSUE TITLE
NU1100, NU11xy should point to PackageSourceMapping

### ISSUE THREAD

**Issue by advay26** [NuGet/docs.microsoft.com-nuget#2571]
When we try to restore a project/solution with PackageSourceMapping enabled, and restore cannot resolve a package, it gives the NU1100 Error. However, this error's docs page doesn't currently point to anything about PackageSourceMapping and editing the NuGet.config file. Should this also point to the SourceMapping docs so that users know that this could be a possible cause of this error?

**Comment by nkolev92** [comment]
This should apply to NU1101, NU1102, NU1103 as well.

**Comment by nkolev92** [comment]
PR out https://github.com/NuGet/docs.microsoft.com-nuget/pull/2628
