### ISSUE TITLE
Update note in nuget.exe sign command that says "Package signing is not yet supported in .NET Core"

### ISSUE THREAD

**Issue by kartheekp-ms** [NuGet/docs.microsoft.com-nuget#2573]
Given that [`dotnet nuget sign` command](https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-nuget-sign) has been added to the .NET SDK, we should update `Package signing is not yet supported in .NET Core, under Mono, or on non-Windows platforms.` note in the doc to reflect the change.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a85b6901-248a-5423-4b73-2e45cd1d750a
* Version Independent ID: bb29b2b7-46d0-e683-57e4-14317f29fd6f
* Content: [NuGet CLI sign command](https://docs.microsoft.com/en-us/nuget/reference/cli-reference/cli-ref-sign)
* Content Source: [docs/reference/cli-reference/cli-ref-sign.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/main/docs/reference/cli-reference/cli-ref-sign.md)
* Product: **nuget**
* GitHub Login: @dtivel
* Microsoft Alias: **dtivel**

**Comment by dtivel** [comment]
@kartheekp-ms, can you create this issue in the dotnet/docs repo?

If you go to https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-nuget-sign and click the "This page" button at the bottom, it'll open a new issue in the correct repo.

**Comment by kartheekp-ms** [comment]
@dtivel - The issue is in `nuget.exe sign` command [doc](https://docs.microsoft.com/en-us/nuget/reference/cli-reference/cli-ref-sign)  where the `Note` says `Package signing is not yet supported in .NET Core, under Mono, or on non-Windows platforms.`. IMHO, this text must be updated because `dotnet nuget sign` command has been implemented. Please consider re-opening this issue if you agree with my comment.
