### ISSUE TITLE
This error "Este host nao e conhecido. (packagesource:443) on Visual Studio Code

### ISSUE THREAD

**Issue by luizcojr** [NuGet/docs.microsoft.com-nuget#2575]
Hello!

This error happens when trying build a project on the Visual Studio Code

Please, help about it!

  Este host n�o � conhecido. (packagesource:443)
    Este host n�o � conhecido.
  Repetindo 'FindPackagesByIdAsyncCore' para a origem 'https://packagesource/FindPackagesById()?id='Microsoft.EntityFrameworkCore.Design'&semVerLevel=2.0.0'.
  Este host n�o � conhecido. (packagesource:443)
    Este host n�o � conhecido.
  Repetindo 'FindPackagesByIdAsyncCore' para a origem 'https://packagesource/FindPackagesById()?id='Microsoft.AspNetCore.Mvc.Razor.RuntimeCompilation'&semVerLevel=2.0.0'.
  Este host n�o � conhecido. (packagesource:443)
    Este host n�o � conhecido.
  Repetindo 'FindPackagesByIdAsyncCore' para a origem 'https://packagesource/FindPackagesById()?id='Microsoft.EntityFrameworkCore.Sqlite'&semVerLevel=2.0.0'.
  Este host n�o � conhecido. (packagesource:443)
    Este host n�o � conhecido.
  Repetindo 'FindPackagesByIdAsyncCore' para a origem 'https://packagesource/FindPackagesById()?id='Microsoft.EntityFrameworkCore.Tools'&semVerLevel=2.0.0'.
  Este host n�o � conhecido. (packagesource:443)
    Este host n�o � conhecido.
  Repetindo 'FindPackagesByIdAsyncCore' para a origem 'https://packagesource/FindPackagesById()?id='Microsoft.VisualStudio.Web.CodeGeneration.Design'&semVerLevel=2.0.0'.
  Este host n�o � conhecido. (packagesource:443)
    Este host n�o � conhecido.
  Repetindo 'FindPackagesByIdAsyncCore' para a origem 'https://packagesource/FindPackagesById()?id='Microsoft.EntityFrameworkCore'&semVerLevel=2.0.0'.
  Este host n�o � conhecido. (packagesource:443)
    Este host n�o � conhecido.
  Repetindo 'FindPackagesByIdAsyncCore' para a origem 'https://packagesource/FindPackagesById()?id='Npgsql.EntityFrameworkCore.PostgreSQL'&semVerLevel=2.0.0'.
  Este host n�o � conhecido. (packagesource:443)
    Este host n�o � conhecido.
  Repetindo 'FindPackagesByIdAsyncCore' para a origem 'https://packagesource/FindPackagesById()?id='Npgsql.EntityFrameworkCore.PostgreSQL.Design'&semVerLevel=2.0.0'.
  Este host n�o � conhecido. (packagesource:443)
    Este host n�o � conhecido.
C:\Program Files\dotnet\sdk\5.0.40

**Comment by joelverhagen** [comment]
This appears to be an invalid package source in your configuration.

Could you try running `dotnet nuget list source` and seeing if a feed like "https://packagesource" appears in the list? This sounds like an error in one of your configuration files (perhaps `%appdata%\NuGet\NuGet.Config`).
