### ISSUE TITLE
Redirect Loop when resolving URL from https://api.nuget.org/v3-flatcontainer

### ISSUE THREAD

**Issue by NN-BT** [NuGet/docs.microsoft.com-nuget#2576]
The issue started Friday (11-05-2021 PM PST) when running `dotnet restore` on a project failed with the following errors

```
/usr/share/dotnet/sdk/5.0.401/NuGet.targets(131,5): error : Failed to retrieve information about 'Microsoft.Extensions.DependencyInjection.Abstractions' from remote source 'https://api.nuget.org/v3-flatcontainer/microsoft.extensions.dependencyinjection.abstractions/index.json'. [**.csproj]
/usr/share/dotnet/sdk/5.0.401/NuGet.targets(131,5): error :   Response status code does not indicate success: 301 (Moved Permanently). [**.csproj]
  Failed to download package 'System.Xml.XDocument.4.0.11' from 'https://api.nuget.org/v3-flatcontainer/system.xml.xdocument/4.0.11/system.xml.xdocument.4.0.11.nupkg'.
  Response status code does not indicate success: 301 (Moved Permanently).
  Failed to download package 'System.Text.Encoding.Extensions.4.3.0' from 'https://api.nuget.org/v3-flatcontainer/system.text.encoding.extensions/4.3.0/system.text.encoding.extensions.4.3.0.nupkg'.
  Response status code does not indicate success: 301 (Moved Permanently).
```

Entering the URL, e.g. `https://api.nuget.org/v3-flatcontainer/microsoft.extensions.dependencyinjection.abstractions/index.json`  into a browser tab with Network inspection on showed that there is a redirect loop going on

![image](https://user-images.githubusercontent.com/26933358/140829177-4f68ccdc-eae5-4b1a-996f-d3763f28d46c.png)

This can be repro-ed by setting the IP address `13.107.246.18 api.nuget.org` to the **hosts** file and trying to get the above URL.

This issue happens at random, probably at the mercy of DNS resolution when it forwards the request to api.nuget.org to a functional nuget server vs the problematic one.

**Comment by joelverhagen** [comment]
Hello @NN-BT, I tried to reproduce with the suggest hosts file change. I wasn't able to reproduce it. It appears the problem has been resolved. If you are still running into this intermittent issue, please feel free to open an issue on https://github.com/NuGet/NuGetGallery (the issue tracker for NuGet.org specifically).
