### ISSUE TITLE
Add video tutorial to Package Source Mapping docs

### ISSUE THREAD

**Issue by chgill-MSFT** [NuGet/docs.microsoft.com-nuget#2587]
Consider adding https://www.youtube.com/watch?v=G6P38Dn69Ro from .NET conf to the [Package Source Mapping docs](https://docs.microsoft.com/en-us/nuget/consume-packages/package-source-mapping)

@JonDouglas what do you think?

**Comment by JonDouglas** [comment]
Absolutely, send a pr

**Comment by okayb7701** [comment]
#01732162794

**Comment by joelverhagen** [comment]
This is in PROD.
