### ISSUE TITLE
The Create Analyzers docs should provide an SDK centric version of authoring an analyzer package, and provide links to examples.

### ISSUE THREAD

**Issue by nkolev92** [NuGet/docs.microsoft.com-nuget#2595]
The Create Analyzers docs should provide an SDK centric version of authoring an analyzer package, and provide links to examples.

cc @clairernovotny 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 70362894-2286-0482-3285-5c9454698726
* Version Independent ID: 4fc64cf3-bc79-3577-0c1f-f5e214b087e2
* Content: [.NET Compiler Platform Analyzer Formats for NuGet](https://docs.microsoft.com/en-us/nuget/guides/analyzers-conventions)
* Content Source: [docs/guides/analyzers-conventions.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/main/docs/guides/analyzers-conventions.md)
* Product: **nuget**
* GitHub Login: @JonDouglas
* Microsoft Alias: **jodou**

**Comment by clairernovotny** [comment]
For this, I'm specifically thinking of source generators or analyzers that need to target different roslyn versions to use API's. @sharwell helped figure it out for Refit https://github.com/reactiveui/refit/blob/main/Refit. I'd suggest a simple sln that has a "hello world" source generator that targets Roslyn 3.x and 4.x, includes the csproj and necessary targets file to make it all work. The docs would point out the key pieces.

**Comment by nkolev92** [comment]
This is still needed.
