### ISSUE TITLE
Link to "Cross-Platform .NET Standard Plugin Templates extension" is broken, rendering tutorial useless

### ISSUE THREAD

**Issue by IanKemp** [NuGet/docs.microsoft.com-nuget#2615]
Extension appears to have been removed from the marketplace.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d228e1b2-34af-a8cb-0a54-e2fcb6cd34df
* Version Independent ID: 31e9b41e-b74f-3614-7c3d-cd17a04e1211
* Content: [Create NuGet Packages for Xamarin (for iOS, Android, and Windows) with Visual Studio 2017 or 2019](https://docs.microsoft.com/en-us/nuget/guides/create-packages-for-xamarin)
* Content Source: [docs/guides/create-packages-for-xamarin.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/main/docs/guides/create-packages-for-xamarin.md)
* Product: **nuget**
* GitHub Login: @JonDouglas
* Microsoft Alias: **jodou**

**Comment by randzdias** [comment]
Yes I have the same issue. Unable to create a nuget package due to this.

**Comment by joelverhagen** [comment]
I see the link in the document appears to be working right now. Perhaps it was an intermittent issue? The link I tried is here:
https://marketplace.visualstudio.com/items?itemName=vs-publisher-473885.PluginForXamarinTemplates

**Comment by JonDouglas** [comment]
This issue is resolved by the link provider.
