### ISSUE TITLE
Documentation is not helpful as it does not describe all possible problems.

### ISSUE THREAD

**Issue by krischik** [NuGet/docs.microsoft.com-nuget#2617]
[Enter feedback here]

The project was build. And unit tested. For some reason the pack command is looking at the wrong place for the DLL. The difference being that strange `netcoreapp3.1` intermediate directory.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7fb15c8f-7da1-a19c-0642-85dbf61ba8bf
* Version Independent ID: e9f608fc-a014-0061-0def-b2b04dca26fa
* Content: [NuGet Error NU5026](https://docs.microsoft.com/en-us/nuget/reference/errors-and-warnings/nu5026)
* Content Source: [docs/reference/errors-and-warnings/NU5026.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/main/docs/reference/errors-and-warnings/NU5026.md)
* Product: **nuget**
* GitHub Login: @mishra14
* Microsoft Alias: **jodou**

**Comment by zivkan** [comment]
@krischik can you please elaborate on what "that strange netcoreapp3.1 intermediate directory" means?  `dotnet pack` (or `msbuild -t:pack`) will by default ask MSBuild what the project outputs are, and then create a package with just those files. In other words, by default it doesn't include any files from the intermediate (obj) folder. I'm not sure how or why you would be experiencing something different.

Do you have a sample project you can zip up and attach, so I can investigate?

As for "does not describe all possible problems", MSBuild is a programming language, and as a result, there's an infinite number of ways customers can customize their project. We can and should document the commonly experienced issues, but we need feedback and details about what those problems are. For uncommon issues, there's a good chance that we never considered a customer getting themselves into certain scenarios, plus there's a balance about having short documentation that does not overwhelm customers trying to read it.

**Comment by JonDouglas** [comment]
Since this issue hasn't had a response for some time, we're going to close it. If there's more information provided to this issue, we can reopen it.
