### ISSUE TITLE
angular-slickgrid 

### ISSUE THREAD

**Issue by Robinl2018** [NuGet/docs.microsoft.com-nuget#2622]
I have an app, i´m using angular-slickgrid, in sometimes the app doesn't show the grid, instead of it, it shows a gray line, just like the image below

![image](https://user-images.githubusercontent.com/39069169/147156239-2129af93-cab5-4d08-b069-bb40f7e4edb7.png)

The page should be like this:

![image](https://user-images.githubusercontent.com/39069169/147156320-ba0d60a3-932f-4047-bda8-ec4f45f00716.png)

This is the html of control definition

![image](https://user-images.githubusercontent.com/39069169/147156862-fcf99892-c588-40e2-a647-3d75f7b7279b.png)

  <div id="divgridDeli" class="grid">
    <angular-slickgrid gridId="gridProd"
              [columnDefinitions]="columnDefinitions"
              [gridOptions]="gridOptions"
              [dataset]="dataset"
              (onAngularGridCreated)="aGridReady($event.detail)"
              (onDblClick)="gridDblClick($event.detail.eventData, $event.detail.args)"
              (onKeyDown)="gridonKeyDown($event.detail.eventData, $event.detail.args)">
    </angular-slickgrid>
  </div>

This is gridoptions definitions:

    this.gridOptions = {
      autoResize: { container: '#divgridDeli', rightPadding: 5 },
      //enableAutoResize: true,
      enableCellNavigation: true,
      autoHeight: false,
      enableRowSelection: true,
      enableFiltering: true,
      enableExcelExport: false,
      gridHeight: 200,
      gridMenu: { hideForceFitButton: true }
    };

Does Anyone can help me please?

**Comment by JonDouglas** [comment]
Please reach out to the project's maintainers for assistance.
