### ISSUE TITLE
Owners in trustedSigners is case sensitive

### ISSUE THREAD

**Issue by erdembayar** [NuGet/docs.microsoft.com-nuget#2637]
We need to document `owners` attribute in trustedSigners section is case sensitive.
Below one has non-capital letter `nuget` as owner then restoring `nuget.versioning` package  from nuget.org will succeed.
```
    <trustedSigners>
        <repository name="NuGetTrust" serviceIndex="https://api.nuget.org/v3/index.json">
            <certificate fingerprint="0e5f38f57dc1bcc806d8494f4f90fbcedd988b46760709cbeec6f4219aa6157d" hashAlgorithm="SHA256" allowUntrustedRoot="false" />
            <certificate fingerprint="5a2901d6ada3d18260b9c6dfe2133c95d74b9eef6ae0e5dc334c8454d1477df4" hashAlgorithm="SHA256" allowUntrustedRoot="false" />
            <owners>nuget;test</owners>
        </repository>
    </trustedSigners>
```
But below one has `Nuget` as owner so restoring `nuget.versioning` will fail.
```
    <trustedSigners>
        <repository name="NuGetTrust" serviceIndex="https://api.nuget.org/v3/index.json">
            <certificate fingerprint="0e5f38f57dc1bcc806d8494f4f90fbcedd988b46760709cbeec6f4219aa6157d" hashAlgorithm="SHA256" allowUntrustedRoot="false" />
            <certificate fingerprint="5a2901d6ada3d18260b9c6dfe2133c95d74b9eef6ae0e5dc334c8454d1477df4" hashAlgorithm="SHA256" allowUntrustedRoot="false" />
            <owners>Nuget;test</owners>
        </repository>
    </trustedSigners>
```

Involved refs:
https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-nuget-verify
https://docs.microsoft.com/en-us/nuget/reference/cli-reference/cli-ref-verify
https://docs.microsoft.com/en-us/nuget/reference/cli-reference/cli-ref-trusted-signers
https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-nuget-trust

**Comment by clairernovotny** [comment]
Is this a doc bug or a feature bug?

**Comment by erdembayar** [comment]
> Is this a doc bug or a feature bug?

It's doc issue.

**Comment by clairernovotny** [comment]
Do we allow account names to differ only in case?

**Comment by clairernovotny** [comment]
I'm not sure we should be treating this as a doc issue.
