### ISSUE TITLE
Improve documentation for NU1605 

### ISSUE THREAD

**Issue by zivkan** [NuGet/docs.microsoft.com-nuget#2638]
.NET SDK opts everyone into TreatWarningAsError for NU1605, so customers don't realize it's something they can opt-out of

we should have docs on how to opt out at a project level, and improve NU1605's page on how to NoWarn at project and package level

**Comment by nkolev92** [comment]
I have https://github.com/NuGet/docs.microsoft.com-nuget/pull/2870 out. This is similar, so I'll add better documentation on top of what I did in the other PR.
