### ISSUE TITLE
Msbuild Restore Does Not Restore All Projects In A Solution

### ISSUE THREAD

**Issue by jimblend** [NuGet/docs.microsoft.com-nuget#2647]
I cannot find anything on this one.  I have a solution with a primary .NET Framework class library and a second project that runs unit tests against the class library.  When running `msbuild /t:restore`, only the test unit project's NuGet packages are restored, the .NET Framework class library project's NuGet packages are not restored, the project is never mentioned in the output.  The command works fine with all other solutions I have.  There is something with the solution keeping the class library from being included.  The class library project has several NuGet packages and should not be excluded from the restore.  No error messages are shown for the class library when restore is run, the class library is not even mentioned once.  Command is being ran in the Developer PowerShell in Visual Studio.  The same results are experienced in GitHub when running build automation using msbuild.

I need restore to work right for GitHub CI/CD integration work.  I have to restore the packages every time I run an automated build.  The project I am attempting to get this done is a dependency of two other projects.  Until this is fixed, I am at a standstill.  Work is not happy because of the time being wasted trying to figure this out.  I don't blame them.  

I have tried:
- Creating a brand new solution, thinking there may be a problem with the existing one.  The class library csproj was a complete brand new one.  I didn't copy anything over from the project that is being excluded.  No change.
- Right-clicking the solution and then "Restore NuGet Packages" within Visual Studio, no change.
- I noticed all other solutions have project.assets.json in the obj folder of each project, yet the class library project doesn't.  Manually adding and modifying project.assets.json doesn't work.  The class library project is still being ignored.
- Looked for a setting in the class library project properties that would exclude the project from restore, found nothing.
- Looked at the csproj file to see if there is an exclude setting in there, nothing found.  
- Searching for "restore" in the csproj file turns up nothing.
- Compared working csproj files with the class library csproj file, nothing different.
- Googled "msbuild /t:restore project being excluded", nothing useful returned.
- Googled "msbuild restore exclude project", nothing helpful is returned.
- Following https://docs.microsoft.com/en-us/nuget/consume-packages/package-restore-troubleshooting doesn't help, nothing lead to the class library project being included.

Would be helpful if restore would at least mention why the project is being excluded so I can have a better chance at fixing the problem.

**Comment by nkolev92** [comment]
@jimblend 
Are you looking for something like this: https://docs.microsoft.com/en-us/nuget/reference/msbuild-targets#restoring-packagereference-and-packagesconfig-projects-with-msbuild? 

Are the projects that aren't restored in your case packages.config based?

**Comment by jimblend** [comment]
The project being skipped has a packages.config file.  I guess that makes the project packages.config based?  New to all this.

I did look at the link provided and ran msbuild -t:restore -p:RestorePackagesConfig=true, no change.  Project still being ignored.

**Comment by nkolev92** [comment]
What version of the tooling are you using?
