### ISSUE TITLE
Should we mark project.json format as deprecated?

### ISSUE THREAD

**Issue by dominoFire** [NuGet/docs.microsoft.com-nuget#2648]
[Enter feedback here]

There are other package management formats, such as PackageReference and packages.config that are used in newer projects.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a735fb3b-5d8e-0241-30af-38aa5e57ebb1
* Version Independent ID: a9ced5bd-9a95-e9a9-b8c9-1678b7823fab
* Content: [project.json File Reference for NuGet](https://docs.microsoft.com/en-us/nuget/archive/project-json)
* Content Source: [docs/archive/project-json.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/main/docs/archive/project-json.md)
* Product: **nuget**
* GitHub Login: @JonDouglas
* Microsoft Alias: **jodou**

**Comment by JonDouglas** [comment]
Yes, let's add a banner for this doc like the others!

![image](https://user-images.githubusercontent.com/1288848/151823618-62c52b0a-df0a-451b-859f-22e5b46dd6fd.png)
