### ISSUE TITLE
nuget trouble

### ISSUE THREAD

**Issue by mahirsaid** [NuGet/docs.microsoft.com-nuget#2666]

**Comment by mahirsaid** [comment]
I tried attaching a source to search for the packages (nuget.org) and that seems to not work. Ive spent the whole day trying to figure out a solution. Every video or article seems to show the same thing over and over again and i ma upset that this should be an easy fix. nuget manager keeps saying there is an error so took off any other resource. but will only show what the project packages has which doesnt help sense i need more. thank you if you could help.

**Comment by zivkan** [comment]
> nuget manager keeps saying there is an error

What is the error it reports?

Please consider using Visual Studio's report a problem: https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio?view=vs-2022

In particular, step 8, record your actions while reproducing the error, this gives us a lot of information 

Finally, given the little information you're provided to help me understand what problem you're experiencing, my best guess is that the Package Manager UI is set to use a package source that doesn't contain any packages. We have documentation on how to install packages in Visual Studio: https://docs.microsoft.com/en-us/nuget/consume-packages/install-use-packages-visual-studio

Notice in step 2, the screenshot shows our package management UI, and in the top right hand corner it says "Package Source:" and there's a dropdown box that says "nuget.org". Do you have a nuget.org option in the drop down?

**Comment by mahirsaid** [comment]
yes thank you i figured another method. im not sure why it was not showing nuget packages. than you.

**Comment by nkolev92** [comment]
Closing as product issues should be filled through nuget/home or developer community.
