### ISSUE TITLE
Document about authentication prompts and retries while accessing private feeds

### ISSUE THREAD

**Issue by kartheekp-ms** [NuGet/docs.microsoft.com-nuget#2669]
Accessing private feed requires credentials which can be acquired by a credential provider. Visual Studio Credential Provider prompts the user for credentials when a unique account cannot be found. If the credential entered by the user didn't work and the server responded with access forbidden response, then NuGet retries the request. During this process, users may be prompted again for credentials. This behavior is not documented right now and can sometimes be confusing.

#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 63ef2bec-be0a-b6ca-3a97-e4faefac198e
* Version Independent ID: 3995da84-d0c1-7c9e-5882-481588e255d6
* Content: [Consuming packages from authenticated feeds](https://docs.microsoft.com/en-us/nuget/consume-packages/consuming-packages-authenticated-feeds?source=docs)
* Content Source: [docs/consume-packages/consuming-packages-authenticated-feeds.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/main/docs/consume-packages/consuming-packages-authenticated-feeds.md)
* Product: **nuget**
* GitHub Login: @nkolev92
* Microsoft Alias: **nikolev**

**Comment by kartheekp-ms** [comment]
Until this issue is resolved, Customers who are experiencing this problem should `find the nuget.config file in their repo and grab the URL for each of the feeds and try entering that address into your web browser. You may get a permission error. In that case you need to request permissions to that feed from the feed owner`

Based on how [NuGet applies settings](https://docs.microsoft.com/en-us/nuget/consume-packages/configuring-nuget-behavior#how-settings-are-applied) the source url may not present in your repo's `NuGet.Config` file and it may be present in any of the parent folders. Identifying the source url that you don't have access to may sometimes require traversing through the NuGet.Config files from repository folder to the root folder or in the [default NuGet Config file](https://docs.microsoft.com/en-us/nuget/consume-packages/configuring-nuget-behavior#config-file-locations-and-uses).

**Comment by zivkan** [comment]
Usually customers can use `dotnet nuget list source` on the command line to find the full list of package sources and URLs, regardless of which nuget.config file the source is defined in.
