### ISSUE TITLE
Provide Example using files located outside of Project

### ISSUE THREAD

**Issue by hfloyd** [NuGet/docs.microsoft.com-nuget#2672]
When using the Project Properties > Package UI, there is a "Browse..." button next to the License file field, which (when used to select a file outside of the Project Root) will result in:

```
<PropertyGroup>
	...
	<PackageLicenseFile>..\..\LICENSE.md</PackageLicenseFile>
  </PropertyGroup>

```

This configuration throws an error on build:

**Severity	- Code -	Description**	
_Error	NU5030	The license file '..\..\LICENSE.md' does not exist in the package._	

In order to successfully build, not only does the `<ItemGroup>` need to be manually added, as per current docs, but the `<PackageLicenseFile>` value needs to be manually edited to remove the additional folders (so that it matches the "PackagePath" location):

Corrected Example:

```
<PropertyGroup>
	...
	<PackageLicenseFile>LICENSE.md</PackageLicenseFile>
  </PropertyGroup>


<ItemGroup>
	<None Include="..\..\LICENSE.md" Pack="true" PackagePath=""/>
</ItemGroup>
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6c43c07f-a3e6-6da8-1c85-d0dc06fade2f
* Version Independent ID: 5cc5f0b0-8ab5-f05c-89ad-92172362fcf3
* Content: [NuGet Error NU5030](https://docs.microsoft.com/en-us/nuget/reference/errors-and-warnings/nu5030?f1url=%3FappId%3DDev16IDEF1%26l%3DEN-US%26k%3Dk(NU5030)%26rd%3Dtrue)
* Content Source: [docs/reference/errors-and-warnings/NU5030.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/main/docs/reference/errors-and-warnings/NU5030.md)
* Product: **nuget**
* GitHub Login: @nkolev92
* Microsoft Alias: **jodou**

**Comment by nkolev92** [comment]
Hey @hfloyd 
This actually looks like a product bug, instead of a docs issue. 

The Project properties UI is not adding the correct item. 

Can you please file this issue at https://developercommunity.visualstudio.com/? 

I can do it myself, but it'll be more fairly represented as a customer discovered issue. You'll also be getting updates for that specific issue.
