### ISSUE TITLE
Docs  for legacy symbol publishing references symbolserver.org which no longer exists

### ISSUE THREAD

**Issue by pranavkm** [NuGet/docs.microsoft.com-nuget#2684]
The URLs http://symbolsource.org and https://nuget.smbsrc.net/ no longer exist.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 98435fc3-0e6f-91e8-b2ba-5329fffd193b
* Version Independent ID: ea0fe9fc-d171-8ddf-426d-a7ec3a232445
* Content: [Creating legacy symbol packages (.symbols.nupkg)](https://docs.microsoft.com/en-us/nuget/create-packages/symbol-packages)
* Content Source: [docs/create-packages/Symbol-Packages.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/main/docs/create-packages/Symbol-Packages.md)
* Product: **nuget**
* GitHub Login: @JonDouglas
* Microsoft Alias: **jodou**

**Comment by zivkan** [comment]
Appears to have been fixed already
