### ISSUE TITLE
Please clarify syntax of the packageSourceMapping section

### ISSUE THREAD

**Issue by gpwen** [NuGet/docs.microsoft.com-nuget#2691]
Please clarify syntax of the packageSourceMapping section. It's not obvious how I should associate multiple package patterns with the same package source. Should I specify multiple "packageSource" items with the same key? Or should I specify a complex pattern as combination of multiple simple patterns? Is that even allowed? Or should I specify multiple "package" items?

In the end, it appears that:
* A "packageSource" key can only be specified **once**; and
* Each "packageSource" item allow **multiple** "package" items; and
* Each package pattern can only be a simple ID or wildcards, **combination won't  work**.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 15617693-33df-025b-26c3-2d80e4df68d3
* Version Independent ID: 15617693-33df-025b-26c3-2d80e4df68d3
* Content: [Package Source Mapping](https://docs.microsoft.com/en-us/nuget/consume-packages/package-source-mapping)
* Content Source: [docs/consume-packages/Package-Source-Mapping.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/main/docs/consume-packages/Package-Source-Mapping.md)
* Product: **nuget**
* GitHub Login: @nkolev92
* Microsoft Alias: **nikolev**

**Comment by nkolev92** [comment]
Thanks for trying out the feature @gpwen 

I'll see if I can tweak the docs to improve readability for the first 2 points. 
Key usually implies one occurence.

The 3rd part is already covered in https://docs.microsoft.com/en-us/nuget/consume-packages/package-source-mapping#package-pattern-syntax

**Comment by gpwen** [comment]
Thanks for the prompt update @nkolev92 

It might be a little bit picky, but "Example Syntax" in "Package Pattern Syntax" section listed something like "NuGet.Common, Contoso.Contracts". That does leave an impression that package pattern might accept comma-delimited patterns, especially for those searching for ways to specify multiple patterns for one source. How about something like: "a", "b" or "c". If someone does try that as XML attribute value, it will be a syntax error, so it leaves no room for second guess.

I also think it would be very helpful if the sample code in "Enabling Package Source Mapping" includes a case where one source is associated with multiple patterns.

**Comment by nkolev92** [comment]
@gpwen I'm not sure I agree about the feedback on the package prefix table. The fact that those patterns are separate is indicated by the quotes. 

I think we can definitely add an example with multiple patterns though.
