### ISSUE TITLE
Question about file licenses and url

### ISSUE THREAD

**Issue by aescg1220** [NuGet/docs.microsoft.com-nuget#2695]
Specifically, I'm looking at this package, and want to know how the "License Info" link is populated:
[Microsoft.Data.SqlClient.SNI 4.0.0](https://www.nuget.org/packages/Microsoft.Data.SqlClient.SNI/4.0.0) has a file license type with the  path: `\LICENSE.txt`.
On the nuget package page, and within Visual Studio, they reference [License Info](https://www.nuget.org/packages/Microsoft.Data.SqlClient.SNI/4.0.0/License).
I couldn't find anywhere within the nuspec that references that link, nor does the documentation mention it.
Do all file licenses receive the same url? (e.g. `https://www.nuget.org/packages/{package id}/{package version}/License`)
Does the "License Info" link change based on the relative path of the file?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e3ad41c6-6549-e33b-407e-52357146f49a
* Version Independent ID: 741c3f86-a7c6-f48f-bc29-e49a439f7c61
* Content: [Finding and Choosing NuGet Packages](https://docs.microsoft.com/en-us/nuget/consume-packages/finding-and-choosing-packages#license-url-deprecation)
* Content Source: [docs/consume-packages/Finding-and-Choosing-Packages.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/main/docs/consume-packages/Finding-and-Choosing-Packages.md)
* Product: **nuget**
* GitHub Login: @JonDouglas
* Microsoft Alias: **jodou**

**Comment by JonDouglas** [comment]
@aescg1220 

I looked at this package with the FuGet link which shows nuspec metadata and you should see:

```
<license type="file">LICENSE.txt</license>
```

https://www.fuget.org/packages/Microsoft.Data.SqlClient.SNI/4.0.0

I believe that specific license url path gets generated when you embed a license. If you have a license expression (SPDX), it will go to another landing page i.e. https://licenses.nuget.org/MIT

Lastly, the deprecated experience will just link to wherever the license is expressed i.e. https://raw.githubusercontent.com/moq/moq4/main/License.txt

The license link changes based on what method you use. The relative path of the file I don't believe matters, it should generate the license page on nuget.org for you.

**Comment by aescg1220** [comment]
thank you!  the generated portion is what was confusing, hopefully it'll always be the same format.
