### ISSUE TITLE
Need to mention the license `spec` command defaults to

### ISSUE THREAD

**Issue by agr** [NuGet/docs.microsoft.com-nuget#2704]
Running `nuget.exe spec` with version 6.0.0 of the client yields a .nuspec that defaults to MIT license and no documentation seems to mention it anywhere. This behavior does not seem to be covered by any documentation and I think it is important enough to be explicitly mentioned.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 77471d86-36e2-298b-15b5-cc5311419e37
* Version Independent ID: e6595a89-de30-3f7f-f580-95823a86d588
* Content: [NuGet CLI spec command](https://docs.microsoft.com/en-us/nuget/reference/cli-reference/cli-ref-spec)
* Content Source: [docs/reference/cli-reference/cli-ref-spec.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/main/docs/reference/cli-reference/cli-ref-spec.md)
* Product: **nuget**
* GitHub Login: @JonDouglas
* Microsoft Alias: **jodou**

**Comment by kinkeadian25** [comment]
Hey @erdembayar or @agr , is it alright if I submit a PR for this?

**Comment by JonDouglas** [comment]
@kinkeadian25 absolutely. We'd really appreciate that.

**Comment by kinkeadian25** [comment]
@JonDouglas, sounds great. Thanks so much! I am going to be in class a bit today, but I will get it done today! Trying to do some documentation PRs for a few different projects that I want to eventually contribute code.

**Comment by JonDouglas** [comment]
@kinkeadian25 No rush at all. Throw up some PRs and we'll review them and guide you towards getting them merged. Also if you have any questions, feel free to include them in any issues or PRs so we can help.
