### ISSUE TITLE
Clarify that when GeneratePackageOnBuild is set to true, pack will not run implicit build

### ISSUE THREAD

**Issue by heng-liu** [NuGet/docs.microsoft.com-nuget#2706]
Originally from https://github.com/NuGet/Home/issues/11691
It might be confusing that after setting `GeneratePackageOnBuild ` to true, running pack without explicitly build will fail.
It might be good to clarify this in doc https://docs.microsoft.com/en-us/nuget/quickstart/create-and-publish-a-package-using-the-dotnet-cli#automatically-generate-package-on-build

**Comment by zivkan** [comment]
Although I haven't seen a customer complain about this for a while, I still think it's worthwhile documenting.
