### ISSUE TITLE
[Bug]: dotnet pack: IncludeAssets and ExcludeAssets on PackageReference differ in generated .nuspec file

### ISSUE THREAD

**Issue by 0liver** [NuGet/docs.microsoft.com-nuget#2716]
### NuGet Product Used

dotnet.exe

### Product Version

dotnet 6.0.201

### Worked before?

N/A

### Impact

I'm unable to use this version

### Repro Steps & Context

Create a project file [like this](https://github.com/Lombiq/NodeJs-Extensions/blob/a6b3353235bc56613ff792bfc7b743a99fb48617/Lombiq.NodeJs.Extensions/Lombiq.NodeJs.Extensions.csproj); in short:

```xml
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
  </PropertyGroup>
  <!-- more details here -->
  <ItemGroup Condition="'$(NuGetBuild)' == 'true'">
    <PackageReference Include="Lombiq.Npm.Targets" Version="1.0.1-alpha.6">
      <IncludeAssets>build</IncludeAssets>
    </PackageReference>
  </ItemGroup>
</Project>
```

After running [`build`](https://github.com/Lombiq/GitHub-Actions/blob/issue/OSOE-83/.github/workflows/publish.yml#L125) and [`pack`](https://github.com/Lombiq/GitHub-Actions/blob/issue/OSOE-83/.github/workflows/publish.yml#L134) using:

```PowerShell
dotnet build --configuration Release --no-restore -p:NuGetBuild=true -p:LangVersion=Latest -p:GenerateDocumentationFile=True -p:NoWarn=CS1573%3BCS1591%3BVSTHRD002%3BVSTHRD200 -p:EnableNETAnalyzers=false -p:ContinuousIntegrationBuild=true -p:DebugSymbols=true -p:DebugType=portable
```
and

```PowerShell
dotnet pack --output artifacts --configuration Release --no-restore --no-build -p:NuGetBuild=true -p:Version=${{ steps.get_version.outputs.VERSION }} -p:GenerateDocumentationFile=True -p:NoWarn=NU5104 -p:TreatWarningsAsErrors=true -warnaserror -p:WarnOnPackingNonPackableProject=True -p:IncludeSymbols=true -p:SymbolPackageFormat=snupkg -p:NoDefaultExcludes=true
```

... the resulting package contains the following _lombiq.nodejs.extensions.nuspec_ file:

```xml
<?xml version="1.0" encoding="utf-8"?>
<package xmlns="http://schemas.microsoft.com/packaging/2013/05/nuspec.xsd">
  <metadata>
    <!-- more details here -->
    <repository type="git" url="https://github.com/Lombiq/NodeJs-Extensions/" commit="a6b3353235bc56613ff792bfc7b743a99fb48617" />
    <dependencies>
      <group targetFramework=".NETStandard2.0">
        <dependency id="Lombiq.Npm.Targets" version="1.0.1-alpha.6" exclude="Runtime,Compile,Build,Native,Analyzers,BuildTransitive" />
      </group>
    </dependencies>
  </metadata>
</package>
```

As you can see - the dependency assets changed from `<IncludeAssets>build</IncludeAssets>` to `exclude="Runtime,Compile,Build,Native,Analyzers,BuildTransitive"`. This leads to the `.props` and `.targets` files of the dependency not being included in any consumer of this package. But that's exactly what I want to achieve.

I have verified that the `.props` and `.targets` files are correctly imported after changing the `<dependency>` element to contain `include="Build"` instead of the `exclude` attribute and installing that modified package.

The problem is with the `IncludeAssets` and `ExcludeAssets` elements.

**Comment by 0liver** [comment]
There still seem to exist more pieces in the puzzle, because **I'm not able to generate an `input` attribute with just `build` in it**. 

I've tried this:
```xml
    <PackageReference Include="Lombiq.Npm.Targets" Version="1.0.1-alpha.6">
      <!-- We want to make NPM-Targets' .props and .targets files available to consumer projects. -->
      <IncludeAssets>build</IncludeAssets>
      <!-- Exclude everything else (almost). -->
      <ExcludeAssets>buildTransitive;contentFiles;native;runtime</ExcludeAssets>
      <!-- Override the default value. -->
      <PrivateAssets>analyzers</PrivateAssets>
    </PackageReference>
```
But that will lead to the lack of a dependency.

```xml
    <dependencies>
      <group targetFramework=".NETStandard2.0" />
    </dependencies>
```

Why?

Now, I've found [this `if` statement](https://github.com/NuGet/NuGet.Client/blob/5b0ee2562df6cf2c66cc9905a8a65f2b09ea5473/src/NuGet.Core/NuGet.Commands/CommandRunners/PackCommandRunner.cs#L614) which reads to me like:

> If you want an `include` attribute on your dependency, `contentFiles` has to be one of `IncludeAssets` values.

So I moved `contentFiles` from `ExcludeAssets` to `IncludeAssets`, but now I get the `include` attribute with **only** `contentFiles` as its value:

```xml
    <dependencies>
      <group targetFramework=".NETStandard2.0">
        <dependency id="Lombiq.Npm.Targets" version="1.0.1-alpha.6" include="ContentFiles" />
      </group>
    </dependencies>
```

Please advise on how to generate an `input` attribute with just `build` in it.

**Comment by 0liver** [comment]
OK, I've got to work with:
```xml
    <PackageReference Include="Lombiq.Npm.Targets" Version="1.0.1-alpha.6">
      <!-- See https://docs.microsoft.com/en-us/nuget/consume-packages/package-references-in-project-files#controlling-dependency-assets. -->
      <!-- We want to make NPM-Targets' .props and .targets files available to consumer projects, so we need to specify
           "build" here. We also need "contentFiles", because without it no "include" attribute is generated on the
           dependency in the .nuspec file. -->
      <IncludeAssets>build;contentFiles</IncludeAssets>
      <!-- Nothing else works here to get "build" into the "include" attribute. -->
      <ExcludeAssets>none</ExcludeAssets>
      <!-- We specify "none" here to override the default value, which includes "build". -->
      <PrivateAssets>none</PrivateAssets>
    </PackageReference>
```
... which produces:

```xml
    <dependencies>
      <group targetFramework=".NETStandard2.0">
        <dependency id="Lombiq.Npm.Targets" version="1.0.1-alpha.6" include="Build,ContentFiles" />
      </group>
    </dependencies>
```

I still feel that some combinations of the attribute values produce unexpected results - I've updated [the table here](#issuecomment-1092223162) to reflect this.

**Comment by 0liver** [comment]
Something is dawning on me: When only the `exclude` attribute is specified on the `<dependency>`, the value for (the missing) `include` attribute will be `LibraryIncludeFlags.All`! I'll have to verify that.

**Comment by nkolev92** [comment]
hmm...I think there's something weird going on with buildTransitive. 
buildTransitive technically supersedes build. 

Try 

```xml
  <ItemGroup>
    <PackageReference Include="Lombiq.Npm.Targets" Version="1.0.0">
      <IncludeAssets>build;buildTransitive</IncludeAssets>
      <ExcludeAssets>none</ExcludeAssets>
      <PrivateAssets>none</PrivateAssets>
    </PackageReference> 
  </ItemGroup>
```

This should do what you'd want it to.

**Comment by 0liver** [comment]
That did the trick. Using `build;buildTransitive` the following `dependency` node is generated in the `.nuspec` file:

```xml
<dependency id="Lombiq.Npm.Targets" version="1.0.1-alpha.8" exclude="Runtime,Compile,Native,Analyzers" />
```

And installing that into a consumer project _**does**_ include the `.props` and `.targets` files from `Lombiq.Npm.Targets` in the `.nugetg.props`/`.nuget.g.targets` 🎉
