### ISSUE TITLE
The sample project does not seem to work

### ISSUE THREAD

**Issue by Matteo-T** [NuGet/docs.microsoft.com-nuget#2725]
It would be nice if the sample project would actually build once a real package is selected.

There were at least 3 errors when I tried to use it:
1. msbuild complained about `MSBuildProjectExtensionsPath` being set again. I moved it to a Directory.Build.props file, as suggested by the error message.
2.  Then, msbuild was erroring out with `error NETSDK1073: The FrameworkReference 'Microsoft.NETCore.App' was not recognized` which I managed to workaround by adding `<GenerateErrorForMissingTargetingPacks>false</GenerateErrorForMissingTargetingPacks>`
3. Then, msbuild failed with `The "CopyRefAssembly" task was not given a value for the required parameter "SourcePath"`, which I managed to workaround by adding `<ProduceReferenceAssembly>false</ProduceReferenceAssembly>`

I do not know whether all that was due to some new version of msbuild/VS/SDKs I have on my system. Also, it is true that 2 is probably due to the way the package I picked is; unsure about 3.

Regardless, this the sample project file already has "defensive logic" to keep the user away from common pitfalls (nicely commented, I would add), I would suggest considering addressing the 3 things I mentioned.

Thanks,
-Matteo

**New .proj file**
```xml
<Project Sdk="Microsoft.Build.NoTargets/1.0.80"> <!-- This is not a project we want to build. -->

    <PropertyGroup>
        <RestorePackagesPath>packages/</RestorePackagesPath> <!-- Changes the global packages folder-->
        <TargetFramework>net5.0</TargetFramework> <!-- This is not super relevant, as long as your SDK version supports it. -->
        <DisableImplicitNuGetFallbackFolder>true</DisableImplicitNuGetFallbackFolder> <!-- If a package is resolved to a fallback folder, it may not be downloaded.-->
        <AutomaticallyUseReferenceAssemblyPackages>false</AutomaticallyUseReferenceAssemblyPackages> <!-- We don't want to build this project, so we do not need the reference assemblies for the framework we chose.-->

        <!-- Making the project more resilient to common problems -->        
        <GenerateErrorForMissingTargetingPacks>false</GenerateErrorForMissingTargetingPacks>
        <ProduceReferenceAssembly>false</ProduceReferenceAssembly>
    </PropertyGroup>

    <ItemGroup>
        <PackageDownload Include="Microsoft.SqlServer.SqlManagementObjects" Version="[161.47008.0]" />
    </ItemGroup>

</Project>
```
**Added Directory.Build.props**

```xml
<?xml version="1.0" encoding="utf-8"?>
<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <PropertyGroup>
     <MSBuildProjectExtensionsPath>$(RestorePackagesPath)obj/</MSBuildProjectExtensionsPath> <!-- It's still PackageReference, so project intermediates are still created. -->
  </PropertyGroup>  
</Project>
```
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e7f319f5-ef4e-c1b6-0686-e5ff2e81e4e1
* Version Independent ID: e7f319f5-ef4e-c1b6-0686-e5ff2e81e4e1
* Content: [Download packages with PackageDownload](https://docs.microsoft.com/en-us/nuget/consume-packages/packagedownload-functionality)
* Content Source: [docs/consume-packages/PackageDownload-Functionality.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/main/docs/consume-packages/PackageDownload-Functionality.md)
* Product: **nuget**
* GitHub Login: @nkolev92
* Microsoft Alias: **nikolev**

**Comment by nkolev92** [comment]
Hey @Matteo-T 

What's the version of the SDK you're using. 

I attempted with `6.0.300-preview.22154.4` and did not have any of the issues mentioned.

**Comment by nkolev92** [comment]
Thank you reporting this issue. At this point we do not have enough information to continue investigating the issue. 
Please feel free to comment or open a new issue if needed.
