### ISSUE TITLE
Lots of dead links

### ISSUE THREAD

**Issue by tbayart** [NuGet/docs.microsoft.com-nuget#2726]
There are 8 links at the bottom of this page :  
https://github.com/NuGet/docs.microsoft.com-nuget/blob/main/docs/quickstart/create-and-publish-a-package-using-visual-studio.md

5 of them redirect to the github 404 not found.

**Comment by JonDouglas** [comment]
@tbayart This is likely because you are browsing through GitHub. The generated docs based on these files that 404 go to other documentation sets.

**Comment by tbayart** [comment]
I didn't expected that from a MD file.
Thank you for the external link.
