### ISSUE TITLE
Horrible!!!!

### ISSUE THREAD

**Issue by sdifiore** [NuGet/docs.microsoft.com-nuget#2748]
The problem is in Visual Studio 2022 not in CLI

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 099102e8-c320-ef50-6821-57519684dc98
* Version Independent ID: 1523dac4-419d-613d-2497-4062f9efd358
* Content: [NuGet pack and restore as MSBuild targets](https://docs.microsoft.com/en-us/nuget/reference/msbuild-targets#restore-target)
* Content Source: [docs/reference/msbuild-targets.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/main/docs/reference/msbuild-targets.md)
* Product: **nuget**
* GitHub Login: @nkolev92
* Microsoft Alias: **nikolev**

**Comment by nkolev92** [comment]
Hey @sdifiore, 

Can you describe the problem you're facing?

Product or docs issues?

**Comment by nkolev92** [comment]
Closing as we haven't gotten a response.
