### ISSUE TITLE
Missing instruction to set ManagePackageVersionsCentrally=true?

### ISSUE THREAD

**Issue by mfwilson** [NuGet/docs.microsoft.com-nuget#2750]
I followed the instructions under "Enabling Central Package Management" but that did not seem to enable this feature (running VS2022 Preview 6). It wasn't until I added the following in my Directory.Packages.props file that central package management seemed to activate:

<PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
</PropertyGroup>

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2d000f01-60a3-59c2-e06d-c02c8721fa76
* Version Independent ID: 2d000f01-60a3-59c2-e06d-c02c8721fa76
* Content: [Central Package Management](https://docs.microsoft.com/en-us/nuget/consume-packages/Central-Package-Management)
* Content Source: [docs/consume-packages/Central-Package-Management.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/main/docs/consume-packages/Central-Package-Management.md)
* Product: **nuget**
* GitHub Login: @JonDouglas
* Microsoft Alias: **jodou**

**Comment by nkolev92** [comment]
Latest one shows this as fixed. 

> To get started with central package management, you must create a Directory.Packages.props file at the root of your repository and set the MSBuild property ManagePackageVersionsCentrally to true.
