### ISSUE TITLE
Document embedded readme

### ISSUE THREAD

**Issue by zivkan** [NuGet/docs.microsoft.com-nuget#2752]
Other server implementors need to know how to provide PM UI with the metadata to enable the link to readme files.

Additionally, I believe we should be explicit in giving server implementors advice that for embedded licenses, icons and readme, that they need to host the files on their server, and modify the nuspec returned via http to include links for PM UI to use.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 300c5942-2d98-cac7-66be-95380798f3a8
* Version Independent ID: 69d5fdbe-1b3f-12b8-1089-c95ebcf5e7a2
* Content: [Package Metadata, NuGet API](https://docs.microsoft.com/en-us/nuget/api/registration-base-url-resource)
* Content Source: [docs/api/registration-base-url-resource.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/main/docs/api/registration-base-url-resource.md)
* Product: **nuget**
* GitHub Login: @joelverhagen
* Microsoft Alias: **jver**

**Comment by joelverhagen** [comment]
This is shipped.
