### ISSUE TITLE
What Version of .NET is this targeted at?

### ISSUE THREAD

**Issue by mattmckinstry** [NuGet/docs.microsoft.com-nuget#2753]
We have a large Full Framework .NET 4.8 solution with 60+ projects which would benefit greatly from this feature.  The projects have been updated to use the new project format (Sdk="Microsoft.NET.Sdk") to cross compile for .NET 6 or .NET 4.8.

However when I attempt introduce Central Package Management using VS 17.2 and/or Nuget 6.2 it does not pick up the Directory.Packages.props file. All of the Nuget packages get defaulted to their earliest version.

Sample project file can be provided if needed

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2d000f01-60a3-59c2-e06d-c02c8721fa76
* Version Independent ID: 2d000f01-60a3-59c2-e06d-c02c8721fa76
* Content: [Central Package Management](https://docs.microsoft.com/en-gb/nuget/consume-packages/Central-Package-Management)
* Content Source: [docs/consume-packages/Central-Package-Management.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/main/docs/consume-packages/Central-Package-Management.md)
* Product: **nuget**
* GitHub Login: @JonDouglas
* Microsoft Alias: **jodou**

**Comment by nkolev92** [comment]
@mattmckinstry 

The feature itself is not related to a specific .NET runtime version, but rather a specific tooling. 
As long as you have the correct version of the tooling, it should work. 

Please refer to for onboarding. 
https://github.com/NuGet/docs.microsoft.com-nuget/blob/main/docs/consume-packages/Central-Package-Management.md#enabling-central-package-management

If you are still having issues, please feel free to file a discussions/issue in the home repo.
