### ISSUE TITLE
Add preview version and how to specify preview versions

### ISSUE THREAD

**Issue by Rick-Anderson** [NuGet/docs.microsoft.com-nuget#2755]
1. [Pre-release versions](https://docs.microsoft.com/en-us/nuget/concepts/package-versioning#pre-release-versions) should add `-preview` give ASP.NET Core uses `-preview` . For example `<PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="7.0.0-preview.4.22251.1" />`
2. Show how to reference `-preview`  versions when no non-preview exits. For example, how to reference https://www.nuget.org/packages/Microsoft.AspNetCore.OpenApi/  
Reading this doc, you'd expect `Version="7.0.*-*` to work, but it doesn't. You need the following
`    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="7.0.*-*-*" />`

I'm happy to PR these if you agree.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7c462602-7e8f-2634-4006-3fadaa68ef45
* Version Independent ID: 7a6ec89f-55c5-2d49-6677-fcc87b0e40ac
* Content: [NuGet Package Version Reference](https://docs.microsoft.com/en-us/nuget/concepts/package-versioning#version-ranges)
* Content Source: [docs/concepts/Package-Versioning.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/main/docs/concepts/Package-Versioning.md)
* Product: **nuget**
* GitHub Login: @JonDouglas
* Microsoft Alias: **jodou**

**Comment by JonDouglas** [comment]
Would happily review and take on any contributions that can help this doc! Thanks in advance!

**Comment by zivkan** [comment]
Needing `7.0.*-*-*` rather than `7.0.*-*` sounds like a product bug, not a documentation issue.

**Comment by Phiph** [comment]
This might be fixed now, just tried the `7.0..*-*` notation and that worked for me
