### ISSUE TITLE
Documentation missing for NU1702

### ISSUE THREAD

**Issue by IanKemp** [NuGet/docs.microsoft.com-nuget#2756]
There is no entry for [this warning](https://github.com/NuGet/NuGet.Client/blob/dev/src/NuGet.Core/NuGet.Common/Errors/NuGetLogCode.cs#L317) on this page, nor is there a specific sub-page for it.

It is essentially identical to NU1701 except for project, instead of package, reference.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 55b95d44-f1f3-d27a-3881-345bc0ae215b
* Version Independent ID: a6689170-de5f-2b5d-98d0-80f8b37859d0
* Content: [NuGet Errors and Warnings Reference](https://docs.microsoft.com/en-us/nuget/reference/errors-and-warnings)
* Content Source: [docs/reference/Errors-and-Warnings.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/main/docs/reference/Errors-and-Warnings.md)
* Product: **nuget**
* GitHub Login: @JonDouglas
* Microsoft Alias: **jodou**

**Comment by nkolev92** [comment]
Dup of https://github.com/NuGet/docs.microsoft.com-nuget/issues/2544.
