### ISSUE TITLE
The "vulnerabilities" element is not present in metadata

### ISSUE THREAD

**Issue by dm2029** [NuGet/docs.microsoft.com-nuget#2759]
The "vulnerabilities" element is not present in response for vulnerable packages.
For example:
https://api.nuget.org/v3/catalog0/data/2018.12.13.23.40.13/microsoft.data.odata.5.2.0-rc1.json
https://api.nuget.org/v3/catalog0/data/2018.12.13.22.07.24/microsoft.data.odata.5.7.0.json
https://api.nuget.org/v3/registration3/microsoft.data.odata/index.json

Was it removed? Or am I misunderstanding something?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 300c5942-2d98-cac7-66be-95380798f3a8
* Version Independent ID: 69d5fdbe-1b3f-12b8-1089-c95ebcf5e7a2
* Content: [Package Metadata, NuGet API](https://docs.microsoft.com/en-us/nuget/api/registration-base-url-resource)
* Content Source: [docs/api/registration-base-url-resource.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/main/docs/api/registration-base-url-resource.md)
* Product: **nuget**
* GitHub Login: @joelverhagen
* Microsoft Alias: **jver**

**Comment by joelverhagen** [comment]
Hello @dm2029. The `https://api.nuget.org/v3/registration3/` base URL has been deprecated for a couple of years. It is no longer updated with new package events (such as vulnerability details). It is not only missing vulnerability data but also new package versions.

As with all API resource endpoints in the NuGet V3 protocol, the base URL must be discovered from the service index.

> It is possible to fetch metadata about the packages available on a package source using the NuGet V3 API. This metadata can be fetched using the `RegistrationsBaseUrl` resource found in the [service index](https://docs.microsoft.com/en-us/nuget/api/service-index).

If you look at the `@type` value `RegistrationsBaseUrl/3.6.0` on https://api.nuget.org/v3/index.json (the service index), you'll find  `https://api.nuget.org/v3/registration5-gz-semver2/`. 

This URL shows vulnerability information: https://api.nuget.org/v3/registration5-gz-semver2/microsoft.data.odata/index.json

Consider using the NuGet client SDK to fetch this data. It has built-in functionality to always fetch the latest base URL.
https://docs.microsoft.com/en-us/nuget/reference/nuget-client-sdk#get-package-metadata
