### ISSUE TITLE
Short link to "nearest target framework" broken

### ISSUE THREAD

**Issue by RustyF** [NuGet/docs.microsoft.com-nuget#2761]
Currently takes you to Bing!

It's on here after the TFM tables:

https://github.com/NuGet/docs.microsoft.com-nuget/blob/main/docs/reference/target-frameworks.md

Resolution would be to update the aka ms shortlink (not the page).

This appears to be a usable link: https://nugettools.azurewebsites.net/4.3.0/get-nearest-framework

**Comment by zivkan** [comment]
The short URL seems to be fixed now
