### ISSUE TITLE
Mention VS versions along with nuget versions for nugetdefaults.config

### ISSUE THREAD

**Issue by anangaur** [NuGet/docs.microsoft.com-nuget#277]
Looks like its not evident just from nuget version for the customer to find out that the nugetdefaults.config file has changed for VS 2017. We should make the doc more clear.

https://docs.microsoft.com/en-us/nuget/consume-packages/configuring-nuget-behavior#nuget-defaults-file

**Comment by CamSoper** [comment]
@anangaur Since I'm new to this docset, can you please fill me on the details on what needs to be clarified?  I'm not 100% clear.

**Comment by anangaur** [comment]
VS versions have corresponding NuGet versions that they get released with. i.e. When VS 15.6 released, the NuGet functionality corresponds to what we ship with nuget.exe 4.6.0. Obviously users can independently rev the nuget.exe versions on their machines. But the functionality of NuGet with a particular version of VS remains tied to corresponding NuGet versions. 

In this doc, the behavior is documented for NuGet versions which is not useful for VS users that do not use nuget.exe and rather use the NuGet functionality in VS. Does this make sense? 

Created [PR](https://github.com/NuGet/docs.microsoft.com-nuget/pull/745) to fix this issue. Do review and merge :)

**Comment by CamSoper** [comment]
That's very helpful. Thank you, sir!

**Comment by CamSoper** [comment]
Resolved in https://github.com/NuGet/docs.microsoft.com-nuget/pull/745
