### ISSUE TITLE
Central Package Management is not supported in Visual Studio 17.2 or .NET SDK 6.0.300

### ISSUE THREAD

**Issue by reduckted** [NuGet/docs.microsoft.com-nuget#2770]
This documentation states that:

> Starting with [NuGet 6.2](https://docs.microsoft.com/en-us/nuget/release-notes/nuget-6.2), you can centrally manage your dependencies in your projects with the addition of a `Directory.Packages.props` file and an MSBuild property.
> 
> The feature is available across all NuGet integrated tooling.
> 
> - [Visual Studio 2022 17.2 and later](https://visualstudio.microsoft.com/downloads/)
> - [.NET SDK 6.0.300 and later](https://dotnet.microsoft.com/download/dotnet/6.0)

This is very misleading.

You can _restore_ packages using Central Package Management in Visual Studio 17.2 and .NET SDK 6.0.300, but **you cannot install new packages**, which means that you cannot _manage_ your dependencies.

See here for confirmation: https://github.com/NuGet/Home/issues/11826#issuecomment-1147688099

Installing a package in Visual Studio results in this error:
```
NU1008: Projects that use central package version management should not define the version on the PackageReference items but on the PackageVersion items: MyPackage.
Package restore failed. Rolling back package changes for 'MyProject'.
```

Installing a package using the .NET CLI results in this error:
```
error: NU1008: Projects that use central package version management should not define the version on the PackageReference items but on the PackageVersion items: MyPackage.
error: Value cannot be null. (Parameter 'version')
```

Please change the documentation so that it is clear that Visual Studio 17.2 and the .NET SDK 6.0.300 _do not_ support Central Package Management.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2d000f01-60a3-59c2-e06d-c02c8721fa76
* Version Independent ID: 2d000f01-60a3-59c2-e06d-c02c8721fa76
* Content: [Central Package Management](https://docs.microsoft.com/en-us/nuget/consume-packages/central-package-management)
* Content Source: [docs/consume-packages/Central-Package-Management.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/main/docs/consume-packages/Central-Package-Management.md)
* Product: **nuget**
* GitHub Login: @JonDouglas
* Microsoft Alias: **jodou**

**Comment by JonDouglas** [comment]
Hi @reduckted,

Apologies if this is misleading.

While we are working on support to complete the tooling stories for both of these experiences today (the project system in VS & .NET CLI), we still want to make it clear to users as to what version they can expect the CPM feature with restore support to work under. 

There's a note at the bottom today letting people know that this feature currently doesn't have full Visual Studio or .NET CLI support such as the management of packages. We can probably put that note up higher in the docs and be more explicit.

Given these features are actively in development, we will update the documentation with these scenarios as they release. So we'll keep this issue open for now to collect more feedback.

https://github.com/NuGet/Home/pull/11849 (dotnet CLI)
https://github.com/NuGet/Home/issues/11826 (project system support)

**Comment by reduckted** [comment]
> @JonDouglas We can probably put that note up higher in the docs and be more explicit.

Yes, it really should be directly underneath "The feature is available across all NuGet integrated tooling" instead of "hidden" under the "Warning when using multiple package sources" section.

> @JonDouglas we still want to make it clear to users as to what version they can expect the CPM feature with restore support to work under.

That's fair enough, but the problem is there's no mention that those listed tools _only_ support restoring. The way I interpret the documentation is that CPM is fully supported on those tools.

> Starting with [NuGet 6.2](https://docs.microsoft.com/en-us/nuget/release-notes/nuget-6.2), **you can centrally manage your dependencies in your projects** with the addition of a Directory.Packages.props file and an MSBuild property.
> 
> **The feature is available across all NuGet integrated tooling.**

I think that section really needs to be clear that only restoring is currently supported by those tools.
