### ISSUE TITLE
setapikey does not apply to package consumption

### ISSUE THREAD

**Issue by VulumeCode** [NuGet/docs.microsoft.com-nuget#2784]
In the header of "setapikey command (NuGet CLI)" it says "Applies to: package consumption", this does not appear to be true. 

See these issues for people getting confused about it 

https://github.com/NuGet/Home/issues/3664

https://github.com/NuGet/Home/issues/6415

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 811c6900-960a-e766-79e0-f0e9015bb1a9
* Version Independent ID: 57be8dc3-035b-cf6e-4406-afc439312ab9
* Content: [NuGet CLI setapikey command](https://docs.microsoft.com/en-us/nuget/reference/cli-reference/cli-ref-setapikey)
* Content Source: [docs/reference/cli-reference/cli-ref-setapikey.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/main/docs/reference/cli-reference/cli-ref-setapikey.md)
* Product: **nuget**
* GitHub Login: @JonDouglas
* Microsoft Alias: **jodou**

**Comment by erdembayar** [comment]
I believe you're trying to use setapi command with Azure feeds.
Last week I worked with Azure folks to improve their docs and ours, use following guide. Please use https://github.com/microsoft/artifacts-credprovider or NuGetAuthenticate task. If not available, then use `dotnet nuget add source`.
https://docs.microsoft.com/en-us/azure/devops/artifacts/nuget/dotnet-exe?view=azure-devops

Even added section for [don't use API key for command line](https://docs.microsoft.com/en-us/azure/devops/organizations/accounts/use-personal-access-tokens-to-authenticate?view=azure-devops&tabs=Windows#q-can-i-use-a-personal-access-token-as-an-apikey-to-publish-nuget-packages-to-an-azure-artifacts-feed-using-the-dotnetnugetexe-command-line).
