### ISSUE TITLE
NU1301 Unable to load the service index for source

### ISSUE THREAD

**Issue by madawakarunarathna** [NuGet/docs.microsoft.com-nuget#2790]
This issue is getting only for only two projects of solution. rest of Projects load its dependencies correctly. 
When I check on the local nuget packages path (C:\Users\<username>\.nuget\packages\...) I can find all the dependency dlls. But It seems like VS unable to refere those file correctly for the project.

dependencies shows like this
![image](https://user-images.githubusercontent.com/11084157/174832741-ac4513fb-c33c-4df0-a6fe-8a8782c3c6ed.png)

Could you please help out to resolve this

**Comment by erdembayar** [comment]
@madawakarunarathna
Did you check this https://docs.microsoft.com/en-us/nuget/reference/errors-and-warnings/nu1301?
Do your sources require authentication then make sure you authenticated to them?
