### ISSUE TITLE
Additional guidance for NuGet Error NU1100

### ISSUE THREAD

**Issue by rukasakurai** [NuGet/docs.microsoft.com-nuget#2791]
Additional guidance for "Unable to resolve 'Dependency (>= 1.0.0)' for 'TargetFramework'" would be nice to have.

For example, when setting up a new development environment, the error could be caused by a lack of an appropriate NuGet source and a solution could simply be to `dotnet nuget add source`
https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-nuget-add-source

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a5b306fb-72a2-e479-b745-a89b0095764d
* Version Independent ID: c0b1a587-20c1-c885-a9f8-1cb7340f1d51
* Content: [NuGet Error NU1100](https://docs.microsoft.com/en-us/nuget/reference/errors-and-warnings/nu1100)
* Content Source: [docs/reference/errors-and-warnings/NU1100.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/main/docs/reference/errors-and-warnings/NU1100.md)
* Product: **nuget**
* GitHub Login: @zhili1208
* Microsoft Alias: **lzhi**

**Comment by JonDouglas** [comment]
@rukasakurai Does https://docs.microsoft.com/en-us/nuget/reference/errors-and-warnings/nu1100#solution not cover these items for you?
