### ISSUE TITLE
Need clarification on indenting and multiline support in description and releasenotes

### ISSUE THREAD

**Issue by Pxtl** [NuGet/docs.microsoft.com-nuget#2792]
It is not obvious how the description and releasenotes should be written.  Plain text?  Markdown?  HTML?  Is it okay to indent so that my .nuspec XML file is still readably indented?  What responsibilities do nuspec clients have for properly displaying releasenotes and description?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 06a19d7d-253d-f17f-6421-624c9867473d
* Version Independent ID: cc37eb17-f715-080c-7bfc-9eae868d50ba
* Content: [.nuspec File Reference for NuGet](https://docs.microsoft.com/en-us/nuget/reference/nuspec)
* Content Source: [docs/reference/nuspec.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/main/docs/reference/nuspec.md)
* Product: **nuget**
* GitHub Login: @JonDouglas
* Microsoft Alias: **jodou**

**Comment by erdembayar** [comment]
Please check https://docs.microsoft.com/en-us/nuget/create-packages/package-authoring-best-practices
Also, you can check existing nuget packages from nuget.org as example. Check newtonsoft.json, [nuget.common](https://www.nuget.org/packages/NuGet.Common) packages. Just change nupkg extension to zip then unzip. You can see nuspec file content with text editor.

**Comment by Pxtl** [comment]
This is still an issue for me.  Iv'e seen some clients display the release notes while removing repeating whitespace, others do not.

**Comment by Pxtl** [comment]
This is still an issue for me.  While I can find the information in other exemplars, neither the file reference document nor the best practices mention how description and release history shall be presented.  If I use spaces to indent a bullet to be a sub-bullet, will my whitespace be thrown out or respected?  Is it markdown, plain text, or text with repeated spaces stripped?  This is not defined and it is handled differently by different presentation views.  There should be a canonical answer to this question in the file reference.

**Comment by Mikejo5000** [comment]
Very sorry for the delayed response. We are phasing out GitHub issues as the feedback mechanism on documentation content and replacing it with a new feedback system. If you believe your feedback needs to be addressed, please submit a PR, or use the Feedback link on the article, or copy the content here to a new issue at https://github.com/NuGet/Home/issues

**Comment by Mikejo5000** [comment]
Very sorry for the delayed response. We are phasing out GitHub issues as the feedback mechanism on documentation content and replacing it with a new feedback system. If you believe your feedback needs to be addressed, please submit a PR, or use the Feedback link on the article, or copy the content here to a new issue at https://github.com/NuGet/Home/issues

**Comment by Mikejo5000** [comment]
We apologize for the inconvenience. We are phasing out GitHub issues as the feedback mechanism on NuGet documentation content and replacing it with a new feedback system using the Feedback link within the articles. If you believe your feedback needs to be preserved and addressed, please submit a PR or open a new issue at https://github.com/NuGet/Home/issues
