### ISSUE TITLE
help me

### ISSUE THREAD

**Issue by najmoo** [NuGet/docs.microsoft.com-nuget#2795]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b2c2eb22-045b-1c00-512a-a9eb1be4d784
* Version Independent ID: 87d10a7f-725b-18ef-d5ae-12b2f1c568b3
* Content: [NuGet Error NU1202](https://docs.microsoft.com/en-us/nuget/reference/errors-and-warnings/nu1202?f1url=%3FappId%3DDev16IDEF1%26l%3DEN-US%26k%3Dk(NU1202)%26rd%3Dtrue)
* Content Source: [docs/reference/errors-and-warnings/NU1202.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/main/docs/reference/errors-and-warnings/NU1202.md)
* Product: **nuget**
* GitHub Login: @zhili1208
* Microsoft Alias: **lzhi**

**Comment by JonDouglas** [comment]
We're unable to help you as there is no description in the feedback you provided.

**Comment by nkolev92** [comment]
Closing per the above comment.
