### ISSUE TITLE
Per-project package management with package.config is completely omitted

### ISSUE THREAD

**Issue by gh-andre** [NuGet/docs.microsoft.com-nuget#2801]
Visual Studio allows per-project package management, which is a very powerful feature for those who use native libraries, but surprisingly it is not even mentioned on this page.

It is typical to have multiple projects in a single solution, each with their own dependencies and Visual Studio allows to install packages individually for each project. It can be done manually or via _Package Management Console_, like this:
```powershell
Install-Package Elmah -ProjectName MyProject
```
This creates `packages.MyProject.config`, which has the same contents as `packages.config`. Each project can have its own package list this way. 

This page should mention per-project Nuget package list files. I vaguely recall that at some point one of these pages even listed something like `packages.<project name>.config`, but I can't find it anywhere. It must have been removed.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 63f06d78-4229-5af1-fd2f-a3c4f1601e82
* Version Independent ID: bfaddd49-ed46-768e-8c92-1af18d523ad9
* Content: [NuGet packages.config File Reference](https://docs.microsoft.com/en-us/nuget/reference/packages-config)
* Content Source: [docs/reference/packages-config.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/main/docs/reference/packages-config.md)
* Product: **nuget**
* GitHub Login: @JonDouglas
* Microsoft Alias: **jodou**

**Comment by erdembayar** [comment]
@gh-andre
I was not able to repro this, I tested with both PC and PR type projects. Could you able to provide us repro sample project?
