### ISSUE TITLE
NuGet packages that are missing

### ISSUE THREAD

**Issue by jiarredondo** [NuGet/docs.microsoft.com-nuget#2802]
This project references the NuGet packages that are missing from this machine. Use the NuGet package restore to download them. For more information, see http://go.microsoft.com/fwlink/?LinkID=322105. The missing file is ..\packages\System.Text.Json.6.0.0\build\System.Text.Json.targets

Visual Studio Integration Services 2019, Script Task

**Comment by erdembayar** [comment]
> This project references the NuGet packages that are missing from this machine. Use the NuGet package restore to download them. For more information, see http://go.microsoft.com/fwlink/?LinkID=322105. The missing file is ..\packages\System.Text.Json.6.0.0\build\System.Text.Json.targets
> 
> Visual Studio Integration Services 2019, Script Task

@jiarredondo 
Do you have VS output log or screenshot? Above is not project reference, it's package reference. It's package reference project then check for that file in your NuGet Global packages folder. if it's packages.config then rename/delete the solution local packages folder then try restoring again.
