### ISSUE TITLE
NuGet Error NU1101 Generated by Telerik UI for Blazor

### ISSUE THREAD

**Issue by prager** [NuGet/docs.microsoft.com-nuget#2810]
I cannot get rid of the error mainly because I work on Government computer and cannot install the Progress Control Panel with FIPS enabled. It is not possible to disable FIPS on Government computer. In addition, the Automated Wizzard Installer didn't solve the problem and neither the local NuGet feed setup. Now my manager decided not to use Telerik UI, but I cannot get rid of the error even when I uninstalled the extension from Windows 10 and reinstalled VS 2022. Perhaps I could delete the only Windows registry entry that refers to Telerik, but to mess with Windows registry on Government computer is a very last resort.

Now the error is hanging in the system and I am not able even run a Blazor sample project provided by Visual Studio 2022.

I am curious what would be the solution for this?

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c334f18d-66ca-28a9-3350-c20e762bbec1
* Version Independent ID: 2ea96dfa-e016-ae3b-864c-2a1ce513d90e
* Content: [NuGet Error NU1101](https://docs.microsoft.com/en-sg/nuget/reference/errors-and-warnings/nu1101)
* Content Source: [docs/reference/errors-and-warnings/NU1101.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/main/docs/reference/errors-and-warnings/NU1101.md)
* Product: **nuget**
* GitHub Login: @zhili1208
* Microsoft Alias: **lzhi**

**Comment by zivkan** [comment]
@prager I don't understand the relevance of FIPS.  Are your logs showing HTTPS connection failures?  NU1101, which the docs page says means that the package can't be fond on any configured source, indicates that it didn't fail to contact a package source. In any case, I'd be shocked if any cipher needed for HTTPS TLS is not supposed with FIPS mode on.

NuGet only tries to install packages (and their dependencies) that are defined in MSBuild. I'm not aware of any MSBuild feature that can cause PackageReference items to be added via the registry.

The .NET SDK does however automatically includes the first `Directory.Build.props` file found in any parent directory. So if you have one of thise in your root directory, for example, that adds a PackageReference to the Telerik package, that would be why your new project is trying to install it.

**Comment by prager** [comment]
Thank you for your very much for your advice.

The bottom line is that Progress Control Panel will not install on Government computer with FIPS enabled. The installer throws a specific error message in the sense "...to continue with installation you must disable FIPS...". It is not possible to disable FIPS on a Government computer. It is interesting that the the previous version of Telerik UI works on other Government computers in Blazor project. 

Unfortunately, I can't provide you with specifics what our troubleshooting included and because it took too much time, we decided to clean my machine of any reference to Telerik UI and with reinstall of Visual Studio the NU1101 error is finally gone.

And that means that at this time I will stay away from Telerik UI package for Blazor in near future and if such a time comes, I will revisit your advice. 

Thanks again!

**Comment by zivkan** [comment]
I don't know what "Progress Control Panel" is. Assuming it's related to Telerik's products, you can report it to them, but as you experienced when Telerik's tools are removed from your computer, NuGet works with FIPS enabled.

My summary is that a package was being added to your project, and you didn't understand why or where it came from. We'll consider what possible product changes we might be able to make to make this easier, but since PackageReference is built on MSBuild, it may be more of an MSBuild topic, rather than NuGet.

Since this issue is reported in the docs issue, I'm going to close it, because I don't believe that there's any actionable docs improvements.
