### ISSUE TITLE
This project references NuGet package(s) that are missing on this computer. 

### ISSUE THREAD

**Issue by joedorenbos** [NuGet/docs.microsoft.com-nuget#2811]
I have C# code in a script task in SSIS, VS 2019
I'm getting this error
 The missing file is ..\packages\Microsoft.Data.SqlClient.SNI.4.0.0\build\net46\Microsoft.Data.SqlClient.SNI.targets.

Microsoft.Data.SqlClient.SNI.4.0 has been installed, uninstalled, and reinstalled. Same error. It wont build.

**Comment by JonDouglas** [comment]
This repo is best for feedback regarding our documentation. Given this seems like a support request, we recommend you check out this wiki to best suit your needs:

https://github.com/NuGet/Home/wiki/Submitting-Bugs-and-Suggestions#before-submitting-an-issue
