### ISSUE TITLE
Doesn't actually say how to change the framework.

### ISSUE THREAD

**Issue by krischik** [NuGet/docs.microsoft.com-nuget#2823]
Also the error message says „NU1201: Project  is not compatible with net40“ but I don't us net40. Both frameworks are `<TargetFramework>net461</TargetFramework>` and I nave no idea where the net40 comes from.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 64341f8e-3f83-a6f2-f100-5bab3c6e6c77
* Version Independent ID: bf00b11d-1dcc-45c4-fbf8-929305fe49c6
* Content: [NuGet Error NU1201](https://docs.microsoft.com/en-us/nuget/reference/errors-and-warnings/nu1201)
* Content Source: [docs/reference/errors-and-warnings/NU1201.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/main/docs/reference/errors-and-warnings/NU1201.md)
* Product: **nuget**
* GitHub Login: @zhili1208
* Microsoft Alias: **lzhi**

**Comment by JonDouglas** [comment]
See https://docs.microsoft.com/en-us/visualstudio/ide/visual-studio-multi-targeting-overview for more information on targeting different frameworks.

The error is mentioning that there is a mismatch between the package and the project. We would need more information to help out further, but this channel is for product feedback and not for support. Please see https://github.com/NuGet/Home/wiki/Submitting-Bugs-and-Suggestions#before-submitting-an-issue with instructions on where to get support using NuGet.
