### ISSUE TITLE
Documented path for NuGetDefaults.Config on Windows seems incorrect

### ISSUE THREAD

**Issue by ManuelRin** [NuGet/docs.microsoft.com-nuget#2824]
This page states that on Windows the location for a NuGetDefaults.Config is `%ProgramFiles(x86)%\NuGet\Config`.
It seems that newer NuGet versions resp. at least `dotnet restore` expect the NuGetDefaults.Config to be located under `%ProgramFiles(x86)%\NuGet`.
The [relevant source code in PackageSourceProvider.cs](https://github.com/NuGet/NuGet.Client/blob/e30830adae5bb1f0e0f36776d970c067c37bad1e/src/NuGet.Configuration/PackageSource/PackageSourceProvider.cs#L60-L61) also indicates that the documentation is incorrect.

I haven't challenged other places mentioning the `Config` subdirectory, such as the User and Computer location for the NuGet config. It may be worth to challenge these as well.

Can you please have a look and if confirmed fix the docs?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 370d9d91-9f35-79aa-3ace-7b77436e988f
* Version Independent ID: 3da4591a-3d3d-c07a-6672-97964de13b14
* Content: [Common NuGet configurations](https://docs.microsoft.com/en-us/nuget/consume-packages/configuring-nuget-behavior?source=docs)
* Content Source: [docs/consume-packages/configuring-nuget-behavior.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/main/docs/consume-packages/configuring-nuget-behavior.md)
* Product: **nuget**
* GitHub Login: @JonDouglas
* Microsoft Alias: **jodou**

**Comment by JonDouglas** [comment]
@heng-liu Can you confirm?

**Comment by heng-liu** [comment]
Hi @JonDouglas , yes, NuGet tries to get settings from `NuGetDefaults.config` at https://github.com/NuGet/NuGet.Client/blob/dev/src/NuGet.Core/NuGet.Configuration/Settings/ConfigurationDefaults.cs#L33-L44
The directory and configFile are specified at
https://github.com/NuGet/NuGet.Client/blob/dev/src/NuGet.Core/NuGet.Configuration/Settings/ConfigurationDefaults.cs#L21-L22 
On Windows, the [MachineWideSettingsBaseDirectory ](https://github.com/NuGet/NuGet.Client/blob/dev/src/NuGet.Core/NuGet.Common/PathUtil/NuGetEnvironment.cs#L26-L42) is `%ProgramFiles(x86)%\NuGet`, not `%ProgramFiles(x86)%\NuGet\Config`.

**Comment by nkolev92** [comment]
> On Windows, the [MachineWideSettingsBaseDirectory ](https://github.com/NuGet/NuGet.Client/blob/dev/src/NuGet.Core/NuGet.Common/PathUtil/NuGetEnvironment.cs#L26-L42) is `%ProgramFiles(x86)%\NuGet`, not `%ProgramFiles(x86)%\NuGet\Config`.

That is correct, but that's not how machine wide settings are calculated. 

I am not really sure about the history of it all, but 
https://github.com/NuGet/NuGet.Client/blob/a5baa60cfd7560904a264cae1c21eff3498be177/src/NuGet.Core/NuGet.Common/PathUtil/NuGetEnvironment.cs#L44-L47 NuGet\Config is what the machine wide settings are loaded as (we have features that rely on that), but the other one just checks NuGetDefaults.config which is not something heavily used anymore.

**Comment by camigthompson** [comment]
@heng-liu @nkolev92 Is this issue good to be closed? I see a PR was merged with a fix.

**Comment by nkolev92** [comment]
looks like it, yes.
