### ISSUE TITLE
NU1702

### ISSUE THREAD

**Issue by ArvoX** [NuGet/docs.microsoft.com-nuget#2830]
Why is NU1702 not listed or documenten on this site?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 55b95d44-f1f3-d27a-3881-345bc0ae215b
* Version Independent ID: a6689170-de5f-2b5d-98d0-80f8b37859d0
* Content: [NuGet Errors and Warnings Reference](https://docs.microsoft.com/en-us/nuget/reference/errors-and-warnings)
* Content Source: [docs/reference/Errors-and-Warnings.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/main/docs/reference/Errors-and-Warnings.md)
* Product: **nuget**
* GitHub Login: @JonDouglas
* Microsoft Alias: **jodou**

**Comment by nkolev92** [comment]
Dup of https://github.com/NuGet/docs.microsoft.com-nuget/issues/2544.
