### ISSUE TITLE
This project references NuGet package(s) that are missing on this computer.

### ISSUE THREAD

**Issue by choudhary-harshita** [NuGet/docs.microsoft.com-nuget#2833]
This project references NuGet package(s) that are missing on this computer. Use NuGet Package Restore to download them.

**Comment by innov8ivecoder** [comment]
I have followed the steps outlined here:
https://learn.microsoft.com/en-us/nuget/Consume-Packages/Package-restore-troubleshooting

I see that I am still having the same error message... Please advise.
