### ISSUE TITLE
Add doc explaining policy for verification checkmark

### ISSUE THREAD

**Issue by kraigb** [NuGet/docs.microsoft.com-nuget#284]
nuget.org will be adding checkmarks to verified/certified packages to help prevent spoofing. Will need a document on what it means to be verified, explaining the policy for the checkmark, package signing, and how to get verified.

**Comment by kraigb** [comment]
@karann-msft has anything happened with this?

**Comment by karann-msft** [comment]
this is documented here - https://docs.microsoft.com/en-us/nuget/nuget-org/id-prefix-reservation#id-prefix-reservation-criteria
