### ISSUE TITLE
dotnet pack with nuspec does not automatically include lib directory

### ISSUE THREAD

**Issue by zkat** [NuGet/docs.microsoft.com-nuget#2841]
## Details about Problem

NuGet product used (NuGet.exe | VS UI | Package Manager Console | dotnet.exe):

NuGet version (x.x.x.xxx):

dotnet.exe --version (if appropriate):

VS version (if appropriate):

OS version (i.e. win10 v1607 (14393.321)):

Worked before? If so, with which NuGet version:

## Detailed repro steps so we can see the same problem

1. Create a new classlib (`dotnet new classlib`)
1. Generate a `.nuspec` for it.
1. Add an empty [`<files>`](https://docs.microsoft.com/en-us/nuget/reference/nuspec#files) element to the `nuspec`
1. `msbuild /restore`
1. copy the `bin/Debug` directory into the project root and rename it `lib`
1. `msbuild /t:pack /p:NuspecFile=.nuspec /p:NuspecBasePath=.` 

### Expected Results

A nupkg is generated that includes everything in `lib\` automatically.

### Actual Results

Pack will fail because the package is empty. 

### Notes

This _should_ work, [according to our docs](https://docs.microsoft.com/en-us/nuget/create-packages/creating-a-package#add-a-readme-and-other-files):

![image](https://user-images.githubusercontent.com/17535/93406366-583bcc80-f844-11ea-90c9-65d9af80dd5a.png)

**Comment by nkolev92** [comment]
As Andy mentioned, this is a docs bug, rather than a product one.
