### ISSUE TITLE
The correct markup for Tags in Project Properties

### ISSUE THREAD

**Issue by alireza-rezaee** [NuGet/docs.microsoft.com-nuget#2845]
When using [Visual Studio 2022](https://[aka.ms](https://aka.ms/VSReleaseNotes-17-Current#17.2.6)/VSReleaseNotes-17-Current#17.2.6) to fill in the Project Properties, there is a section titled **Tags**. It is explained there as follows:

![A semicolon-delimited list of tags and keywords that describe the package and aid discoverability of packages through search and filtering.](https://user-images.githubusercontent.com/55509086/183575570-1c83d3b1-44e0-42e6-b5ba-c6be88a0ea32.png)

Looking for more information, following the embedded question mark icon, I came across [this document](https://docs.microsoft.com/en-us/nuget/reference/nuspec#tags) which explained:

> A space-delimited list of tags and keywords that describe the package and aid discoverability of packages through search and filtering.

There is a difference between these two expressions: "space-delimited" and "semicolon-delimited". I see both implementations in Microsoft projects.

Using semicolon-delimited in [efcore](https://github.com/dotnet/efcore/tree/e68de74a4097d6de6dfc8b512535de9b2e21aa54)/[src](https://github.com/dotnet/efcore/tree/e68de74a4097d6de6dfc8b512535de9b2e21aa54/src)/[EFCore.SqlServer](https://github.com/dotnet/efcore/tree/e68de74a4097d6de6dfc8b512535de9b2e21aa54/src/EFCore.SqlServer)/[EFCore.SqlServer.csproj](https://github.com/dotnet/efcore/blob/e68de74a4097d6de6dfc8b512535de9b2e21aa54/src/EFCore.SqlServer/EFCore.SqlServer.csproj#L10):
```xml
<PackageTags>$(PackageTags);SQL Server</PackageTags>
```

Using space-delimited in [machinelearning](https://github.com/dotnet/machinelearning/tree/7f013a2c065f64cea7bcb8683345ee038b5048af)/[src](https://github.com/dotnet/machinelearning/tree/7f013a2c065f64cea7bcb8683345ee038b5048af/src)/[Microsoft.Data.Analysis](https://github.com/dotnet/machinelearning/tree/7f013a2c065f64cea7bcb8683345ee038b5048af/src/Microsoft.Data.Analysis)/[Microsoft.Data.Analysis.csproj](https://github.com/dotnet/machinelearning/blob/7f013a2c065f64cea7bcb8683345ee038b5048af/src/Microsoft.Data.Analysis/Microsoft.Data.Analysis.csproj#L9):
```xml
<PackageTags>ML.NET ML Machine Learning Data Science DataFrame Preparation DataView Analytics Exploration</PackageTags>
```

So which method is correct? (_space-delimited_ or _semicolon-delimited_ or maybe both)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 06a19d7d-253d-f17f-6421-624c9867473d
* Version Independent ID: cc37eb17-f715-080c-7bfc-9eae868d50ba
* Content: [.nuspec File Reference for NuGet](https://docs.microsoft.com/en-us/nuget/reference/nuspec#tags)
* Content Source: [docs/reference/nuspec.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/main/docs/reference/nuspec.md)
* Product: **nuget**
* GitHub Login: @JonDouglas
* Microsoft Alias: **jodou**

**Comment by JonDouglas** [comment]
Ah yes this seems rather confusing. I believe the answer is "both" for the `PackageTags` property although the best practice is semicolon-delimited due to [MSBuild-isms](https://docs.microsoft.com/en-us/visualstudio/msbuild/msbuild-special-characters?view=vs-2019#special-characters). The .nuspec however will keep the space-delimited syntax.

Here's a better doc:

https://learn.microsoft.com/en-us/nuget/reference/msbuild-targets#pack-target

`tags` / `PackageTags` - A semicolon-delimited list of tags that designates the package.

The `PackageTags` element will combine the semicolon-delimited list to a proper space-delimited nuspec at pack time. So both would be "valid" per-say. But semicolon would be best practice.

**Comment by zivkan** [comment]
The problem with semicolon separators is that it might give customers the false impression that `SQL Server;Something` are two tags, whereas in fact it's going to get transformed into `SQL Server Something` in the nuspec and therefore be 3 tags. So technically yes, it works, but I think it's probably going to confuse some customers.

**Comment by JonDouglas** [comment]
There's also this doc: https://learn.microsoft.com/en-us/dotnet/standard/library-guidance/nuget#important-nuget-package-metadata

Is it worth clarifying the MSBuild best practice and the nuspec one?

**Comment by Sironas** [comment]
I stumble on this problem too

Using the command `dotnet pack <sln> -p:PackageTags='Tags1;Tags2'` doesn't work, it will take only the first tag

But using space-delimited list will work fine

Maybe from the dotnet tool only the spaces work fine

Dotnet version : 6.0.401
