### ISSUE TITLE
NuGet install docs page only mentions VS 2019

### ISSUE THREAD

**Issue by dominoFire** [NuGet/docs.microsoft.com-nuget#2848]
The docs page should mention that Install packages feature is available in VS 2019 and newer versions. 

Or, update the page to refer to the current VS version.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ef71b45e-0bb6-6e61-3b42-8e8f150db9fb
* Version Independent ID: 129fb470-7186-059a-fbe8-29b1caf96bf9
* Content: [Install and use a NuGet package in Visual Studio](https://docs.microsoft.com/en-us/nuget/quickstart/install-and-use-a-package-in-visual-studio)
* Content Source: [docs/quickstart/install-and-use-a-package-in-visual-studio.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/main/docs/quickstart/install-and-use-a-package-in-visual-studio.md)
* Product: **nuget**
* GitHub Login: @JonDouglas
* Microsoft Alias: **jodou**

**Comment by JonDouglas** [comment]
This was resolved via a recent content refresh last month. Closing as it's now VS 2022.
