### ISSUE TITLE
Suppress NU1803

### ISSUE THREAD

**Issue by subhaballe** [NuGet/docs.microsoft.com-nuget#2849]
We are using http internal nuget source url and Is there a way to suppress this error in editor.config file ? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d2904abf-733e-9ad7-2920-e2ea449a1cba
* Version Independent ID: d2904abf-733e-9ad7-2920-e2ea449a1cba
* Content: [NuGet Warning NU1803](https://docs.microsoft.com/en-us/nuget/reference/errors-and-warnings/nu1803)
* Content Source: [docs/reference/errors-and-warnings/NU1803.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/main/docs/reference/errors-and-warnings/NU1803.md)
* Product: **nuget**
* GitHub Login: @nkolev92
* Microsoft Alias: **nikolev**

**Comment by khodaie** [comment]
This is true. Our company uses a local intranet IP address as nuget source, and we have no access to the internet.

**Comment by nkolev92** [comment]
Hey all, 

This is a warning, and our docs have instructions on how to suppress them: 

https://docs.microsoft.com/en-us/nuget/reference/errors-and-warnings
