### ISSUE TITLE
Clarify -Source parameter on `nuget add`

### ISSUE THREAD

**Issue by Marv51** [NuGet/docs.microsoft.com-nuget#2858]
Different from most nuget commands, when executing `nuget add`  the `-source` parameter is actually a folder name/path and not the source name as configured in nuget.config. 

This is somewhat confusing and the documentation is not very clear on this.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c7ea4c0c-f8af-aa40-cdaa-d7615e8c48c6
* Version Independent ID: 8426a098-1ccb-471c-ebe9-36597f60e882
* Content: [NuGet CLI add command](https://docs.microsoft.com/en-us/nuget/reference/cli-reference/cli-ref-add)
* Content Source: [docs/reference/cli-reference/cli-ref-add.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/main/docs/reference/cli-reference/cli-ref-add.md)
* Product: **nuget**
* GitHub Login: @JonDouglas
* Microsoft Alias: **jodou**

**Comment by JonDouglas** [comment]
@Marv51 How might we clarify this further? Here's the current explanation:

`Specifies the package source, which is a folder or UNC share, to which the nupkg will be added. Http sources are not supported.`

**Comment by Marv51** [comment]
The `nuget list -source` command is very similar to the `nuget add`command but `list` expects a source **name** to be passed. 
So it is very easy to mistakenly pass a source name to `add`, too. The command does not provide a helpful error message in that case.

So I would suggest:
`Specifies the package source to which the nupkg will be added. This must be the path to a folder or UNC share and not the source name. Http sources are not supported.`
