### ISSUE TITLE
Document two-factor authentication

### ISSUE THREAD

**Issue by kraigb** [NuGet/docs.microsoft.com-nuget#286]
When this is added, build out documentation for setting this up and what it means for workflows.

**Comment by karann-msft** [comment]
@Mikejo5000  can we update https://docs.microsoft.com/en-us/nuget/nuget-org/individual-accounts to talk about 2FA?

**Comment by Mikejo5000** [comment]
Sure, I will plan to add that.

**Comment by karann-msft** [comment]
Thanks @Mikejo5000 !

**Comment by Mikejo5000** [comment]
@karann-msft Sure, let me know if you see anything that needs to be changed. Thx!
