### ISSUE TITLE
Outdated Attribute name: EnablePackageVersionOverride

### ISSUE THREAD

**Issue by sebastianslutzky** [NuGet/docs.microsoft.com-nuget#2878]
Using dotnet sdk 6.0.4, I couldn't get this setting to work.
I've checked the source code and finally got it working setting CentralPackageVersionOVerrideEnabled to false instead.
Should this be updated?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2d000f01-60a3-59c2-e06d-c02c8721fa76
* Version Independent ID: 2d000f01-60a3-59c2-e06d-c02c8721fa76
* Content: [Central Package Management](https://docs.microsoft.com/en-us/nuget/consume-packages/central-package-management)
* Content Source: [docs/consume-packages/Central-Package-Management.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/main/docs/consume-packages/Central-Package-Management.md)
* Product: **nuget**
* GitHub Login: @JonDouglas
* Microsoft Alias: **jodou**

**Comment by nkolev92** [comment]
cc @jeffkl
