### ISSUE TITLE
Incorrect documentation on defaults

### ISSUE THREAD

**Issue by tonyhallett** [NuGet/docs.microsoft.com-nuget#2879]
Apparently 
Title defaults to $(PackageId) - there is no default

Authors defaults to the username of the current user - is $(AssemblyName) https://github.com/dotnet/sdk/blob/c4e5f0dd9c9bba6114f5d1fc4ca2aa2b5d22f37f/src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.DefaultAssemblyInfo.targets#L21
`<Authors Condition=" '$(Authors)'=='' ">$(AssemblyName)</Authors>`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 099102e8-c320-ef50-6821-57519684dc98
* Version Independent ID: 1523dac4-419d-613d-2497-4062f9efd358
* Content: [NuGet pack and restore as MSBuild targets](https://docs.microsoft.com/en-us/nuget/reference/msbuild-targets?source=docs)
* Content Source: [docs/reference/msbuild-targets.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/main/docs/reference/msbuild-targets.md)
* Product: **nuget**
* GitHub Login: @nkolev92
* Microsoft Alias: **nikolev**

**Comment by JonDouglas** [comment]
Thanks for filing this issue @tonyhallett.

As far as I'm following, you're saying that `<authors>` defaults to the assembly name. I can confirm that. 

@nkolev92 @zivkan This seems odd/incorrect?

**Comment by nkolev92** [comment]
> As far as I'm following, you're saying that <authors> defaults to the assembly name. I can confirm that.

Yep, all good as long as you can confirm it.
