### ISSUE TITLE
Use case missing for `language` metadata element

### ISSUE THREAD

**Issue by SetTrend** [NuGet/docs.microsoft.com-nuget#2882]
The documentation is missing an explanation for the [`language`](https://docs.microsoft.com/en-us/nuget/reference/nuspec#language) element.

The main question unanswered by the documentation is: Where is the `language` value used? What difference does it make? Does it accept multiple language identifiers?

With NuGet packages, localization is done either by using localized resource assemblies or by using satellite assemblies. So (given the documentation at present state) the `language` element doesn't seem to make any sense.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 06a19d7d-253d-f17f-6421-624c9867473d
* Version Independent ID: cc37eb17-f715-080c-7bfc-9eae868d50ba
* Content: [.nuspec File Reference for NuGet](https://docs.microsoft.com/en-us/nuget/reference/nuspec#language)
* Content Source: [docs/reference/nuspec.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/main/docs/reference/nuspec.md)
* Product: **nuget**
* GitHub Login: @JonDouglas
* Microsoft Alias: **jodou**

**Comment by SetTrend** [comment]
\*ping\*

**Comment by SetTrend** [comment]
*ping*

**Comment by Mikejo5000** [comment]
Very sorry for the delayed response. We are phasing out GitHub issues as the feedback mechanism on documentation content and replacing it with a new feedback system. If you believe your feedback needs to be addressed, please submit a PR, or use the Feedback link on the article, or copy the content here to a new issue at https://github.com/NuGet/Home/issues

**Comment by Mikejo5000** [comment]
We apologize for the inconvenience. We are phasing out GitHub issues as the feedback mechanism on NuGet documentation content and replacing it with a new feedback system using the Feedback link within the articles. If you believe your feedback needs to be preserved and addressed, please submit a PR or open a new issue at https://github.com/NuGet/Home/issues
