### ISSUE TITLE
Date or version when it will be removed

### ISSUE THREAD

**Issue by Regenhardt** [NuGet/docs.microsoft.com-nuget#2883]
This should include the information about when or with which version non-HTTPS support will be removed.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d2904abf-733e-9ad7-2920-e2ea449a1cba
* Version Independent ID: d2904abf-733e-9ad7-2920-e2ea449a1cba
* Content: [NuGet Warning NU1803](https://docs.microsoft.com/en-us/nuget/reference/errors-and-warnings/nu1803)
* Content Source: [docs/reference/errors-and-warnings/NU1803.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/main/docs/reference/errors-and-warnings/NU1803.md)
* Product: **nuget**
* GitHub Login: @nkolev92
* Microsoft Alias: **nikolev**

**Comment by nkolev92** [comment]
The exact version of each tool (Nuget.exe, VS & .NET SDK) isn't known yet, but we do have a timeline announced in https://devblogs.microsoft.com/nuget/https-everywhere/.

**Comment by nkolev92** [comment]
cc @JonDouglas Should we just link the blog or do you think we should add this content in the docs explicitly?

**Comment by JonDouglas** [comment]
Let's link to blog for now when we get to this for the warning code. That way if we change anything, we do it in one spot and not multiple.

**Comment by Regenhardt** [comment]
Perfect, thanks!
