### ISSUE TITLE
Document changes to VS IVsPackageInstallerServices APIs

### ISSUE THREAD

**Issue by zivkan** [NuGet/docs.microsoft.com-nuget#2895]
PR https://github.com/NuGet/NuGet.Client/pull/4814 changed the XMLDoc.

Maybe it's worthwhile adding some explanation about the async nature of CPS PackageReference projects to https://learn.microsoft.com/en-us/nuget/visual-studio-extensibility/nuget-api-in-visual-studio

**Comment by nkolev92** [comment]
Fixed in https://github.com/NuGet/docs.microsoft.com-nuget/pull/2929
