### ISSUE TITLE
When will VS Code stop supporting HTTP Nuget sources?

### ISSUE THREAD

**Issue by janussen** [NuGet/docs.microsoft.com-nuget#2909]
The page describes a warning about VS Code stopping its support for HTTP Nuget sources. But for the developers it's very important to get an idea of WHEN this support is likely to disappear from VS Code.

In my organisation there are technical issues with changing the internal sources from HTTP to HTTPS so we need to have an estimate of when it needs to be solved.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: d2904abf-733e-9ad7-2920-e2ea449a1cba
* Version Independent ID: d2904abf-733e-9ad7-2920-e2ea449a1cba
* Content: [NuGet Warning NU1803](https://learn.microsoft.com/en-us/nuget/reference/errors-and-warnings/nu1803)
* Content Source: [docs/reference/errors-and-warnings/NU1803.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/main/docs/reference/errors-and-warnings/NU1803.md)
* Product: **nuget**
* GitHub Login: @nkolev92
* Microsoft Alias: **nikolev**

**Comment by nkolev92** [comment]
Hey @janussen 

Does https://devblogs.microsoft.com/nuget/https-everywhere/ which is linked at the bottom of the NU1803 page answer your question?

**Comment by janussen** [comment]
Yes, thank you. 

I still think, though, that this date should be included on the doc page in question. 

Med venlig hilsen 

Kåre Janussen

**Comment by heng-liu** [comment]
I'll close it as fixed.
