### ISSUE TITLE
Reverted to previous commit version destroyed all nuget packages

### ISSUE THREAD

**Issue by 99067718** [NuGet/docs.microsoft.com-nuget#2915]
I reverted my application to a previous github version, and now my entire program is permanently corrupted.
I can't install any nuget package, and there is not a single way to fix it (as far as I know)

**Comment by nkolev92** [comment]
Hey @99067718 

This doesn't sound like a documentation bug. 

Do you have a minimal repro? 
Is this something you can repro consistently? Maybe on other machines? 

Consider looking at SO or other Q&A sources.

**Comment by 99067718** [comment]
> Hey @99067718
> 
> This doesn't sound like a documentation bug.
> 
> Do you have a minimal repro? Is this something you can repro consistently? Maybe on other machines?
> 
> Consider looking at SO or other Q&A sources.

It happens in all my projects, it somehow fixed itself after I tried installing another code editor

**Comment by 99067718** [comment]
But I still think its important to fix this since I was trying to fix it for at least 6 hours.
and I was just lucky to accidentally fix it, since Reïnstalling Visual Studio did not fix it.

**Comment by nkolev92** [comment]
Hey @99067718 
It'd be great to have details about the exact error, and the steps you were taking. 

Without that information, we can't investigate any further.

**Comment by Mielesgames** [comment]
> Hey @99067718 It'd be great to have details about the exact error, and the steps you were taking.
> 
> Without that information, we can't investigate any further.

I found out it happens because of the .gitignore, for some reason it ignores WAY too much stuff, including the colors.

**Comment by nkolev92** [comment]
I see. 

Given that, I don't think there's an action that can be taken at this point. 

Closing this issue for that.
