### ISSUE TITLE
Feature request: Mapping for globalPackagesFolder

### ISSUE THREAD

**Issue by gpwen** [NuGet/docs.microsoft.com-nuget#2916]
**packageSourceMapping** is a nice feature, it's very useful when testing locally built packages (force NuGet to use local build for certain packages). However, that only solves half of the problem. Global NuGet cache will still be contaminated. How about introducing similar feature for "globalPackagesFolder"? Something like **packageFolderMapping**? It can be used to force certain packages to be cached outside of the global cache, somewhere that can be easily cleaned before the next build. This will be very helpful for NuGet package development.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 15617693-33df-025b-26c3-2d80e4df68d3
* Version Independent ID: 15617693-33df-025b-26c3-2d80e4df68d3
* Content: [Package Source Mapping](https://learn.microsoft.com/en-us/nuget/consume-packages/package-source-mapping)
* Content Source: [docs/consume-packages/Package-Source-Mapping.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/main/docs/consume-packages/Package-Source-Mapping.md)
* Product: **nuget**
* GitHub Login: @nkolev92
* Microsoft Alias: **nikolev**

**Comment by nkolev92** [comment]
Dup in https://github.com/NuGet/Home/issues/6579.
