### ISSUE TITLE
Error in example nuget locals all --list command

### ISSUE THREAD

**Issue by sowa705** [NuGet/docs.microsoft.com-nuget#2936]
`nuget locals all -list` is an incorrect command invocation (missing second `-` in `--list`)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 71b49477-cafa-d7d4-76fe-83aff43a3f47
* Version Independent ID: 68d7a416-1397-8cf3-bead-e3cd328aca48
* Content: [How to manage the global packages, cache, temp folders in NuGet](https://learn.microsoft.com/en-us/nuget/consume-packages/managing-the-global-packages-and-cache-folders)
* Content Source: [docs/consume-packages/managing-the-global-packages-and-cache-folders.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/main/docs/consume-packages/managing-the-global-packages-and-cache-folders.md)
* Service: **nuget**
* GitHub Login: @JonDouglas
* Microsoft Alias: **jodou**

**Comment by zivkan** [comment]
@sowa705 are you sure?  What error are you getting?

`nuget.exe` uses powershell conventions, which is a single `-`.  the `dotnet` CLI uses GNU conventions, whichis double `--`.  I believe the docs to be correct:

```text
D:\src\NuGet.Client>nuget.exe locals all -list
http-cache: C:\Users\zivkan\AppData\Local\NuGet\v3-cache
global-packages: C:\Users\zivkan\.nuget\packages\
temp: C:\Users\zivkan\AppData\Local\Temp\NuGetScratch
plugins-cache: C:\Users\zivkan\AppData\Local\NuGet\plugins-cache
```
