### ISSUE TITLE
Global Package References documentation is unclear

### ISSUE THREAD

**Issue by kabua** [NuGet/docs.microsoft.com-nuget#2947]
The section, Global Package References, makes no sense; please consider rewriting it.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 2d000f01-60a3-59c2-e06d-c02c8721fa76
* Version Independent ID: 2d000f01-60a3-59c2-e06d-c02c8721fa76
* Content: [Central Package Management](https://learn.microsoft.com/en-us/nuget/consume-packages/central-package-management)
* Content Source: [docs/consume-packages/Central-Package-Management.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/main/docs/consume-packages/Central-Package-Management.md)
* Service: **nuget**
* GitHub Login: @JonDouglas
* Microsoft Alias: **jodou**

**Comment by JonDouglas** [comment]
Hi @kabua,

Can you provide us some constructive feedback regarding what makes no sense and how might we improve it?

Thank you kindly.
