### ISSUE TITLE
Out of date image

### ISSUE THREAD

**Issue by MrYossu** [NuGet/docs.microsoft.com-nuget#2956]
In the third image under the "Package sources" sections, you show the Nuget Options window.  In VS2022 Community, the up and down arrow buttons in the top right corner are missing.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 9cbbd8f5-8155-0057-b0cc-0b96ee35aad4
* Version Independent ID: 8b085f6d-05f3-e213-6b2a-3f7274581111
* Content: [Install and manage packages in Visual Studio using the NuGet Package Manager](https://learn.microsoft.com/en-us/nuget/consume-packages/install-use-packages-visual-studio)
* Content Source: [docs/consume-packages/install-use-packages-visual-studio.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/main/docs/consume-packages/install-use-packages-visual-studio.md)
* Service: **nuget**
* GitHub Login: @JonDouglas
* Microsoft Alias: **jodou**

**Comment by donnie-msft** [comment]
Close as I found @agr fixed this in https://github.com/NuGet/docs.microsoft.com-nuget/pull/3006 but for some reason the issue didn't close.
