### ISSUE TITLE
Getting errors in my Build pipeline - The missing file is ..\packages\EntityFramework.6.4.4\build\EntityFramework.props.

### ISSUE THREAD

**Issue by surendraadithe** [NuGet/docs.microsoft.com-nuget#2967]
Hi, 

I need some help with resolving build errors in my build pipeline for my application. But I'm not getting any build errors in my VS solution neither in "Debug" or "Release" mode. Please find the attached screenshots. The errors I'm getting are:

1) ##[error]SPSDataFeedUI\SPSDataFeedUI.csproj(573,5): Error : This project references NuGet package(s) that are missing on this computer. Use NuGet Package Restore to download them.  For more information, see http://go.microsoft.com/fwlink/?LinkID=322105. The missing file is ..\packages\EntityFramework.6.4.4\build\EntityFramework.props.
2) ##[error]SPSDataFeedUI\SPSDataFeedUI.csproj(573,5): Error : This project references NuGet package(s) that are missing on this computer. Use NuGet Package Restore to download them.  For more information, see http://go.microsoft.com/fwlink/?LinkID=322105. The missing file is ..\packages\EntityFramework.6.4.4\build\EntityFramework.props.
3) ##[error]Process 'msbuild.exe' exited with code '1'.

Here is the link in azure devops - https://dev.azure.com/humana/Group%20and%20Dental%20Claims/_build/results?buildId=3206367&view=logs&j=275f1d19-1bd8-5591-b06b-07d489ea915a&t=4ece4734-eca2-579f-284e-f003ab72c447&l=89
![Build errors](https://user-images.githubusercontent.com/121028732/208417281-6d297c72-f7ec-49d0-b22c-10f2b6092dae.PNG)
![Error in Build Solution stage](https://user-images.githubusercontent.com/121028732/208417284-245d455f-3e65-4fb4-95a1-ac74f56a27a8.PNG)

Could you please help me in resolving this?
Thanks,
Surendra

**Comment by surendraadithe** [comment]
You can reach out to me at surendra.adithe@gmail.com (or) sadithe@humana.com. Thanks.

**Comment by agr** [comment]
This looks like it belongs to Azure DevOps support or to https://github.com/NuGet/Home.

**Comment by Rajdeep9008** [comment]
Hi Surendra,

Did you get any solution this error as i am facing the same issue if you could help me on this it would be really helpful for me.

Regards
Raj

**Comment by zivkan** [comment]
I didn't see this issue when it was new, but looking at it now, I can confidently say that the problem was that the build wasn't running nuget restore. While the `dotnet` CLI automatically runs restore as part of most commands (build, test, publish), msbuild does not. Therefore, if you're building your solution with msbuild, you need to run restore before build.  I strongly recommend running restore via MSBuild if you can ([`msbuild -t:restore -p:RestorePackagesConfig=true`](https://learn.microsoft.com/en-us/nuget/reference/msbuild-targets#restoring-packagereference-and-packagesconfig-projects-with-msbuild)), otherwise you'll want to run the `NuGetInstaller` task (assuming you're on Azure Pipelines, as the original author of this issue is), and then `nuget.exe restore path\to\my.sln`.

This is what the error text's "Use NuGet Package Restore to download them" means. NuGet restore has not been run on the machine that the error is happening on. Note, this error can happen in some other edge case scenarios, like someone re-organizing the repo and moving project directories around. But in the screenshot from the original issue, I can see the build tasks on the left hand side, and nothing sounds like it ran nuget restore (there's a "use nuget" task, but completing in just 1 second doesn't seem like it ran restore, it must have done something else, like maybe the `NuGetInstaller` task setting up a specific version of nuget.exe, which isn't needed if you do MSBuild restore instead)

**Comment by zivkan** [comment]
Well, the error message says "Use NuGet Package Restore to download them". Do you have nuget restore as part of your pipeline?  If you do and you're still having issues, we're going to need more information than "i am facing the same issue" to be able to figure out why.

**Comment by Rajdeep9008** [comment]
Hi Andy

Like download build will update the code in testslave01 by referring
artifacts from Tool-Multione-RC-test-TestSuite job. So once completion of
the job will check the code in C:\ workspace\
Tool-MultiOne-RC-test-specflowtest-test in testslave01 machine it should
automatically update the folder.

**Comment by zivkan** [comment]
I'm sorry, I didn't understand that at all.

A CI build script usually looks something like

1. Set up environemnt, such as clone repo, run any setup scripts, download/install tools needed for the build.
2. Run NuGet Restore
3. Build project
4. Run tests
5. pack/publish
6. after build steps, maybe like assembly/package signing, publish build artifacts, publish any additional logs.
7. Sometimes cleanup

something to keep in mind is that projects that use packages.config, the project files references package files in a "solution packages folder" (typically a directory named `packages` in the same directory as the solution file). Since it's in the same directory as the solution file, it's in the repo, but most source control settings exclude the packages directory from source control.  Hence, after cloning the repo, you still need to run restore. With msbuild, restore is not automatic, so your build scripts must explicitly do something to run restore.

If you're saying that your build have two phases, and the second phase uses a package created in the first phase, you still need something in the second phase to restore the package, so that it's 1. in the right location on disk and 2. it's extracted correctly, including some additional metadata that is generated on extraction, it's not part of the package contents.

**Comment by Rajdeep9008** [comment]
Hi Andy,

Do you got any solution as I am really struggling with this if you got any
please let me know..

Thanks

**Comment by Rajdeep9008** [comment]
Thank you for your reply like the error message is : the command
msbuild.exe exited with code 1 is there alternative of msbuild which we can
use.

**Comment by Rajdeep9008** [comment]
![MicrosoftTeams-image](https://user-images.githubusercontent.com/129156786/228770709-bfa6ffb2-6f7f-413d-ac4d-d90441417376.png)

**Comment by Rajdeep9008** [comment]
Hi Andy, 
I tried adding the restore stage in my groovy script for nuget restore but it is not recognized and throwing this error do you have any idea how to add the  stage for restore nuget package  or syntax if yes please provide it will be a great help.

Started by user [Administrator](http://localhost:56792/user/admin)
Replayed [#14](http://localhost:56792/job/Tool-MultiOne-RC-test-SpecFlowTest-Expert-Test/14/)
Running as [Administrator](http://localhost:56792/user/admin)
Running in Durability level: MAX_SURVIVABILITY
[Pipeline] Start of Pipeline
[Pipeline] timestamps
[Pipeline] {
[Pipeline] node
15:53:09  Running on [TestSlave01](http://localhost:56792/computer/TestSlave01/) in C:\workspace\Tool-MultiOne-RC-test-SpecFlowTest-Expert-Test
[Pipeline] {
[Pipeline] pwd
[Pipeline] }
[Pipeline] // node
[Pipeline] }
[Pipeline] // timestamps
[Pipeline] End of Pipeline
java.lang.NoSuchMethodError: No such DSL method 'Restore Package Stage' found among steps [VersionNumber, archive, bat, build, catchError, checkout, deleteDir, dir, dockerFingerprintFrom, dockerFingerprintRun, echo, emailext, emailextrecipients, envVarsForTool, error, fileExists, findBuildScans, getContext, git, input, isUnix, jiraComment, jiraIssueSelector, jiraSearch, junit, library, libraryResource, load, lock, mail, milestone, node, parallel, powershell, properties, publishChecks, publishHTML, publishIssues, pwd, pwsh, readFile, readTrusted, recordIssues, resolveScm, retry, scanForIssues, script, sh, sleep, stage, stash, step, svn, throttle, timeout, timestamps, tm, tool, triggerRemoteJob, unarchive, unstable, unstash, validateDeclarativePipeline, waitForQualityGate, waitUntil, warnError, withContext, withCredentials, withDockerContainer, withDockerRegistry, withDockerServer, withEnv, withGradle, wrap, writeFile, ws] or symbols [BearerTokenAuth, CredentialsAuth, NoneAuth, NullAuth, PVSStudio, TokenAuth, acuCobol, ajc, all, allBranchesSame, allOf, allowBrokenBuildClaiming, always, androidLintParser, ansibleLint, ant, antFromApache, antOutcome, antPath, antTarget, any, anyOf, apiToken, architecture, archiveArtifacts, armCc, artifactManager, authorizationMatrix, axivion, axivionSuite, batchFile, bitbucket, bitbucketBranchDiscovery, bitbucketForkDiscovery, bitbucketPublicRepoPullRequestFilter, bitbucketPullRequestDiscovery, bitbucketSshCheckout, bitbucketTagDiscovery, bitbucketTrustEveryone, bitbucketTrustNobody, bitbucketTrustProject, bitbucketTrustTeam, bitbucketWebhookConfiguration, bitbucketWebhookRegistration, booleanParam, branch, brokenBuildSuspects, brokenTestsSuspects, buckminster, buildButton, buildDiscarder, buildDiscarders, buildFailureAnalyzer, buildParameter, buildRetention, buildSelector, buildUser, buildingTag, cadence, cargo, caseInsensitive, caseSensitive, ccm, certificate, changeRequest, changelog, changeset, checkStyle, checkoutToSubdirectory, choice, choiceParam, clang, clangTidy, cleanWs, clock, cmake, codeAnalysis, codeNarc, command, compactAllStatuses, compactJobName, compactJobNameColor, compactLastStableAndUnstable, compactLastSuccessAndFailed, configFile, configFileProvider, coolflux, copyArtifactPermission, copyArtifacts, copyartifact, cpd, cppCheck, cppLint, credentials, cron, crumb, cssLint, culprits, defaultFolderConfiguration, defaultView, demand, detekt, developers, diabC, disableConcurrentBuilds, disableResume, docFx, docker, dockerCert, dockerfile, downstream, doxygen, drMemory, dscanner, dumb, dupFinder, durabilityHint, eclipse, email-ext, envInject, envVars, envVarsFilter, environment, equals, erlc, errorProne, esLint, excludeCategory, excludeFile, excludeMessage, excludeModule, excludeNamespace, excludePackage, excludeType, expression, file, fileParam, filePath, findBugs, fingerprint, fingerprints, flake8, flexSdk, frameOptions, freeStyle, freeStyleJob, fromScm, fromSource, fxcop, gcc, gcc3, gcc4, gendarme, ghsMulti, git, gitBranchDiscovery, gitHubBranchDiscovery, gitHubBranchHeadAuthority, gitHubExcludeArchivedRepositories, gitHubForkDiscovery, gitHubPullRequestDiscovery, gitHubSshCheckout, gitHubTagDiscovery, gitHubTrustContributors, gitHubTrustEveryone, gitHubTrustNobody, gitHubTrustPermissions, gitTagDiscovery, github, githubPush, globalConfigFiles, gnat, gnuFortran, goLint, goVet, gradle, groovy, groovyScript, headRegexFilter, headWildcardFilter, http, hyperlink, hyperlinkToModels, iar, iarCstat, ibLinter, ideaInspection, includeCategory, includeFile, includeMessage, includeModule, includeNamespace, includePackage, includeType, infer, inheriting, inheritingGlobal, installSource, intel, invalids, isRestartedRun, issues, istanbulCobertura, istanbulCoberturaAdapter, jacoco, jacocoAdapter, java, javaDoc, jcReport, jdk, jdkInstaller, jgit, jgitapache, jnlp, jobBuildDiscarder, jobDsl, jobName, jsHint, jsLint, junitTestResultStorage, klocWork, kotlin, ktLint, label, lastCompleted, lastDuration, lastFailure, lastGrantedAuthorities, lastStable, lastSuccess, lastSuccessful, lastWithArtifacts, latestSavedBuild, legacy, legacySCM, list, local, location, logRotator, loggedInUsersCanDoAnything, mailer, masterBuild, maven, maven3Mojos, mavenConsole, mavenErrors, mavenGlobalConfig, mavenMojos, mavenWarnings, metrowerksCodeWarrior, modelsim, modernSCM, msBuild, msbuild, msbuildError, msbuildWarning, mstest, myPy, myView, nagFortran, namedBranchesDifferent, newContainerPerStage, node, nodeProperties, nonInheriting, none, not, nunit, opencoverAdapter, overrideIndexTriggers, paneStatus, parallelsAlwaysFailFast, parameters, password, pattern, pcLint, pep8, perforce, perlCritic, permalink, permanent, php, phpCodeSniffer, phpStan, pipeline-model, pipeline-model-docker, pipelineTriggers, pit, plainText, plugin, pmdParser, pollSCM, prefast, preserveStashes, projectNamingStrategy, protoLint, proxy, pruneTags, publishCoverage, puppetLint, pyDocStyle, pyLint, qacSourceCodeAnalyser, queueItemAuthenticator, quietPeriod, rateLimit, rateLimitBuilds, recipients, recordIssues, requestor, resharperInspectCode, resourceRoot, retainOnlyVariables, rfLint, robocopy, ruboCop, run, runParam, sSHLauncher, scala, schedule, scmRetryCount, script, scriptApproval, scriptApprovalLink, search, security, shell, simian, simpleBuildDiscarder, skipDefaultCheckout, skipStagesAfterUnstable, slave, sonarQube, sourceFiles, sourceRegexFilter, sourceWildcardFilter, specific, sphinxBuild, spotBugs, ssh, sshPublicKey, sshUserPrivateKey, standard, status, string, stringParam, styleCop, sunC, suppressAutomaticTriggering, swapSpace, swiftLint, tag, tagList, taskScanner, taskingVx, teamSlugFilter, text, textParam, throttleJobProperty, tiCss, timestamper, timestamperConfig, timezone, tmpSpace, tnsdl, toolLocation, triggeredBy, tsLint, unsecured, untrusted, upstream, upstreamDevelopers, url, userSeed, usernameColonPassword, usernamePassword, viewsTabBar, vsTest, warnings, warningsParsers, warningsPlugin, weather, withAnt, withSonarQubeEnv, workspace, xlc, xmlLint, yamlLint, yuiCompressor, zip, zptLint] or globals [currentBuild, docker, env, params, pipeline, scm, simpleBuild]
	at org.jenkinsci.plugins.workflow.cps.DSL.invokeMethod(DSL.java:216)
	at org.jenkinsci.plugins.workflow.cps.CpsScript.invokeMethod(CpsScript.java:122)
	at sun.reflect.GeneratedMethodAccessor1491.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1213)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1022)
	at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.call(PogoMetaClassSite.java:42)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)
	at org.kohsuke.groovy.sandbox.impl.Checker$1.call(Checker.java:163)
	at org.kohsuke.groovy.sandbox.GroovyInterceptor.onMethodCall(GroovyInterceptor.java:23)
	at org.jenkinsci.plugins.scriptsecurity.sandbox.groovy.SandboxInterceptor.onMethodCall(SandboxInterceptor.java:157)
	at org.kohsuke.groovy.sandbox.impl.Checker$1.call(Checker.java:161)
	at org.kohsuke.groovy.sandbox.impl.Checker.checkedCall(Checker.java:165)
	at org.kohsuke.groovy.sandbox.impl.Checker.checkedCall(Checker.java:135)
	at org.kohsuke.groovy.sandbox.impl.Checker.checkedCall(Checker.java:135)
	at com.cloudbees.groovy.cps.sandbox.SandboxInvoker.methodCall(SandboxInvoker.java:17)
	at WorkflowScript.run(WorkflowScript:7)
	at ___cps.transform___(Native Method)
	at com.cloudbees.groovy.cps.impl.ContinuationGroup.methodCall(ContinuationGroup.java:86)
	at com.cloudbees.groovy.cps.impl.FunctionCallBlock$ContinuationImpl.dispatchOrArg(FunctionCallBlock.java:113)
	at com.cloudbees.groovy.cps.impl.FunctionCallBlock$ContinuationImpl.fixArg(FunctionCallBlock.java:83)
	at sun.reflect.GeneratedMethodAccessor238.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.cloudbees.groovy.cps.impl.ContinuationPtr$ContinuationImpl.receive(ContinuationPtr.java:72)
	at com.cloudbees.groovy.cps.impl.ClosureBlock.eval(ClosureBlock.java:46)
	at com.cloudbees.groovy.cps.Next.step(Next.java:83)
	at com.cloudbees.groovy.cps.Continuable$1.call(Continuable.java:174)
	at com.cloudbees.groovy.cps.Continuable$1.call(Continuable.java:163)
	at org.codehaus.groovy.runtime.GroovyCategorySupport$ThreadCategoryInfo.use(GroovyCategorySupport.java:129)
	at org.codehaus.groovy.runtime.GroovyCategorySupport.use(GroovyCategorySupport.java:268)
	at com.cloudbees.groovy.cps.Continuable.run0(Continuable.java:163)
	at org.jenkinsci.plugins.workflow.cps.SandboxContinuable.access$001(SandboxContinuable.java:18)
	at org.jenkinsci.plugins.workflow.cps.SandboxContinuable.run0(SandboxContinuable.java:51)
	at org.jenkinsci.plugins.workflow.cps.CpsThread.runNextChunk(CpsThread.java:185)
	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup.run(CpsThreadGroup.java:400)
	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup.access$400(CpsThreadGroup.java:96)
	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup$2.call(CpsThreadGroup.java:312)
	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup$2.call(CpsThreadGroup.java:276)
	at org.jenkinsci.plugins.workflow.cps.CpsVmExecutorService$2.call(CpsVmExecutorService.java:67)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at hudson.remoting.SingleLaneExecutorService$1.run(SingleLaneExecutorService.java:139)
	at jenkins.util.ContextResettingExecutorService$1.run(ContextResettingExecutorService.java:28)
	at jenkins.security.ImpersonatingExecutorService$1.run(ImpersonatingExecutorService.java:68)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Finished: FAILURE
