### ISSUE TITLE
Add dependency version best practices to "Package authoring best practices"

### ISSUE THREAD

**Issue by georg-jung** [NuGet/docs.microsoft.com-nuget#2974]
Please add best practices for how to target dependencies. As a library author, I may be confused which version of my dependency is the right one to depend on. Scenarios:

1. I need [`Newtownsoft.Json`](https://www.nuget.org/packages/Newtonsoft.Json/13.0.2#versions-body-tab) and `10.0.1` satisfies all my needs. `13.0.2` does too, my library is not affected by any breaking changes.
  Options I could consider:
    1. Target `10.0.1`. Most reach. Installs a vulnerable version for consumers by default (vulnerable if < `13.x`).
    2. Target `13.0.1`. Most reach with a non-vulnerable version. Least non-vulnerable version.
    3. Target `13.0.2`. Most recent. Least rech. Gets consumers the most recent version by default.
    4. Target `13.*`. Most recent, even in future. Combines the reach of `13.0.1` with the recentness of `13.0.2` while still ensuring no breaking changes (assuming Netwonsoft.Json versions correctly). Seems like the best compromise, seems to be quite uncommon on NuGet.org.
    5. Now consider there'd be a `14.0.1`. `13.0.1` is still the least non-vulnerable version. Should I target `14.0.1` or `14.*` to express the library is not affected by any breaking changes or should I target a lower version, e.g. `10.0.1`/`13.0.1`/`13.0.2`?

2. I offer a `net6.0` target. The library also uses `System.Text.Json`. Should I add it as dependency for that target or use the runtime-included version?
    * The `Microsoft.Extensions.*` packages add the dependency. Probably to enable consumers of the `6.0` versions to upgrade to STJ `7.0` independently of `Microsoft.Extensions.*`?

3. I'm fine with `netstandard2.0` for my library's needs. I use STJ. Should I add e.g. a `net5.0` target that does not include the dependency, to keep the dependency graph as small as possible?

I assume it is possible to give general advice for (some of) these scenarios. It'd be great to include something like (I'm making these up, not saying they are the correct advice)

✔️ DO target the lowest package version that fits your needs for your dependencies.
✔️ DO target the least stable version with the highest available major version for your dependencies.
✔️ CONSIDER targeting floating versions of your dependencies with a fixed major version, e.g. `13.*`, if XYZ is the case.
❌ DO NOT target vulnerable package versions if non-vulnerable compatible versions are available.
✔️ DO add explicit dependencies to runtime-included components like `System.Text.Json` to enable users to upgrade them out-of-band.

This is something I wondered about for quite some time as a library author and I guess it is possible to provide easy rules of thumb, thus it would be great to add them.

If there is pre-existing documentation that covers this topic that I overlooked, it might be worth linking to it in _Package authoring best practices_.

Related content:
* <https://learn.microsoft.com/en-us/dotnet/standard/library-guidance/dependencies>
* <https://learn.microsoft.com/en-us/nuget/concepts/package-versioning>
* <https://learn.microsoft.com/en-us/nuget/concepts/dependency-resolution>
* <https://learn.microsoft.com/en-us/dotnet/standard/net-standard?tabs=net-standard-1-0#when-to-target-net50-or-net60-vs-netstandard>

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: f519bf56-3618-bfba-3921-cacea56e810a
* Version Independent ID: 9786b989-bce5-13ae-1e24-e88d7cadb7d3
* Content: [Package authoring best practices](https://learn.microsoft.com/en-us/nuget/create-packages/package-authoring-best-practices)
* Content Source: [docs/create-packages/Package-authoring-best-practices.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/main/docs/create-packages/Package-authoring-best-practices.md)
* Service: **nuget**
* GitHub Login: @nkolev92
* Microsoft Alias: **nikolev**

**Comment by georg-jung** [comment]
I still think this is relevant.

**Comment by AndrewTriesToCode** [comment]
As a library author I agree. Specifically when a new .NET release comes out, like today, should my library update dependency versions for `Microsoft.Extensions.*`? The release notes and CVE information can be confusing specifically when trying to determine exactly which nuget packages might be impacted.

Also would like clarity on if a .NET 6 project can target v7+ versions of `Microsoft.Extension.*` and similar runtime related packages. If the answer is technically it might work, but you probably shouldn't do it, I would like to know.

Thanks!

**Comment by georg-jung** [comment]
I still think this is relevant.

**Comment by Mikejo5000** [comment]
Very sorry for the delayed response. We are phasing out GitHub issues as the feedback mechanism on documentation content and replacing it with a new feedback system. If you believe your feedback needs to be addressed, please submit a PR, or use the Feedback link on the article, or copy the content here to a new issue at https://github.com/NuGet/Home/issues

**Comment by Mikejo5000** [comment]
We apologize for the inconvenience. We are phasing out GitHub issues as the feedback mechanism on NuGet documentation content and replacing it with a new feedback system using the Feedback link within the articles. If you believe your feedback needs to be preserved and addressed, please submit a PR or open a new issue at https://github.com/NuGet/Home/issues
