### ISSUE TITLE
No information about how to update a package only if it already exists

### ISSUE THREAD

**Issue by regaleagle** [NuGet/docs.microsoft.com-nuget#2983]
The nuget CLI had the update method but dotnet appears only to have add. I cannot see any documentation on how to update only if the package in question is already present as a projectreference in the csproj file. Of course there must be a switch somewhere or default behaviour (it would be insane for there not to be any way to programmatically update packages) but I cannot find documentation for it.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 6fb181a6-c01f-627a-6d4d-8b752add1ba7
* Version Independent ID: a1c46d27-37e3-0e5f-5e36-8a571a0e2978
* Content: [Install and manage NuGet packages with the dotnet CLI](https://learn.microsoft.com/en-us/nuget/consume-packages/install-use-packages-dotnet-cli)
* Content Source: [docs/consume-packages/install-use-packages-dotnet-cli.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/main/docs/consume-packages/install-use-packages-dotnet-cli.md)
* Service: **nuget**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by skofman1** [comment]
@regaleagle , I would like to make sure I understand your question.

Say you have a project, and it references Newtonsoft.Json version 10.0.2. Calling `dotnet add package Newtonsoft.Json` will update the version of the package in your project to the latest version.

Is this the command you are looking for?

**Comment by regaleagle** [comment]
Sorry I missed this response, I was looking for an update only switch . If I do add and the project does not have the package it will add it. If I'm going through a large list of projects programatically I would want to attempt to update *if it exists*

**Comment by skofman1** [comment]
@regaleagle , thank you for the details! We track a list of commands that are available in nuget.exe but are missing in dotnet.exe here: https://github.com/NuGet/Home/issues/4855

I will close this issue, and we will track your ask as part of https://github.com/NuGet/Home/issues/4855.

**Comment by skofman1** [comment]
Also, here's another related issue: https://github.com/NuGet/Home/issues/4103 (feel free to upvote!)
