### ISSUE TITLE
Better Examples in MEF calls.

### ISSUE THREAD

**Issue by JaedenRuiner** [NuGet/docs.microsoft.com-nuget#2984]
Currently you have an example in the MEF call for using the IComponentModel.  
However, the GetService method does NOT intrinsically exist in an IWizard interface.  It needs to be called from some object that you did not provide, so your example is useless.  

Please update with a full example that can compile, and run, out of the box.
Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 24e1c35e-18f4-1357-65a0-e5f228c72476
* Version Independent ID: 72a6e51a-3cb1-60bd-0ce5-9827a724a028
* Content: [NuGet API in Visual Studio](https://learn.microsoft.com/en-us/nuget/visual-studio-extensibility/nuget-api-in-visual-studio)
* Content Source: [docs/visual-studio-extensibility/nuget-api-in-visual-studio.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/main/docs/visual-studio-extensibility/nuget-api-in-visual-studio.md)
* Service: **nuget**
* GitHub Login: @nkolev92
* Microsoft Alias: **nikolev**

**Comment by nkolev92** [comment]
GetService is part of the VS package type, https://learn.microsoft.com/en-us/dotnet/api/microsoft.visualstudio.shell.asyncpackage.getservice?view=visualstudiosdk-2022#microsoft-visualstudio-shell-asyncpackage-getservice(system-type).
