### ISSUE TITLE
Document PackageReference.Publish

### ISSUE THREAD

**Issue by amcasey** [NuGet/docs.microsoft.com-nuget#2989]
We should document `PackageReference.Publish`.  E.g. to include a package in the output (i.e. bin) folder but not publish it, you can use:

```xml
<PackageReference Include="Microsoft.AspNetCore.SpaProxy" Version="6.0.13">
    <Publish>false</Publish>
</PackageReference>
```

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: ff707668-94d6-25a5-9139-b18cc1b6b446
* Version Independent ID: 494847b9-4894-0beb-7ffa-39a2359999fa
* Content: [NuGet PackageReference in project files](https://learn.microsoft.com/en-us/nuget/consume-packages/package-references-in-project-files)
* Content Source: [docs/consume-packages/Package-References-in-Project-Files.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/main/docs/consume-packages/Package-References-in-Project-Files.md)
* Service: **nuget**
* GitHub Login: @nkolev92
* Microsoft Alias: **nikolev**

**Comment by JonDouglas** [comment]
Gonna /cc @nkolev92 and @jeffkl for some summarization of this undocumented thing:

Here's a shot:

The Publish property in a PackageReference item in a .NET project file specifies whether to include the package in the NuGet package created when the project is built. When Publish is set to True, the package is included in the generated NuGet package. When Publish is set to False, the package is not included. This property allows you to control which packages are published with the project, and can be useful for excluding packages that are development-only or used only in specific environments.

**Comment by nkolev92** [comment]
This isn't a feature implemented by NuGet. 

Can we get more details on the implementation and where it's supported? 

PackageReference works with both Legacy and SDK projects, so it's possible that this is an SDK feature.

**Comment by amcasey** [comment]
The functionality is still present, so arguably the issue is "actionable", but it's not like people are clamoring for documentation of a feature they don't know exists.
