### ISSUE TITLE
NuGet doc required: Demystifying NuGet content files for 3.3+ (new csproj world)

### ISSUE THREAD

**Issue by anangaur** [NuGet/docs.microsoft.com-nuget#300]
We seem to have the content but its confusing. May need a cleaner way to explain the content concept as this is a recurring question from users.

Refer to this: 
http://blog.nuget.org/20160126/nuget-contentFiles-demystified.html

Also need to add more content.

**Comment by anangaur** [comment]
@kraigb can you take a stab at separating the content files concept to its own topic and then I can review the content and more content to it?

**Comment by kraigb** [comment]
#507 notes that there are several things wrong with the blog post, which is from 2016 and applies only to project.json.

**Comment by CamSoper** [comment]
Rolled up to #775
