### ISSUE TITLE
Guidance for non local sources would be appreciated.

### ISSUE THREAD

**Issue by RichardJFoster** [NuGet/docs.microsoft.com-nuget#3043]
The only example shown on this page is for a local package source. It would be helpful if there were also examples for https based package sources.

For example, I came to this page because I'm getting the following message: `error NU1301: Unable to load the service index for source https://[ApparentlyValidUrl]`

I use the term ApparentlyValidUrl because it really isn't. The machine in question uses a self-signed certificate which is not fully trusted (as proven by attempting to retrieve it using `curl` which returned the response `curl: (60) schannel: SEC_E_UNTRUSTED_ROOT (0x80090325) - The certificate chain was issued by an authority that is not trusted.` even after adding what I thought was the correct root certificate to those trusted on the machine).

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: ddfddc4f-d20c-a078-4e72-a997633a48d9
* Version Independent ID: ddfddc4f-d20c-a078-4e72-a997633a48d9
* Content: [NuGet Error NU1301](https://learn.microsoft.com/en-us/nuget/reference/errors-and-warnings/nu1301)
* Content Source: [docs/reference/errors-and-warnings/NU1301.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/main/docs/reference/errors-and-warnings/NU1301.md)
* Service: **nuget**
* GitHub Login: @nkolev92
* Microsoft Alias: **jodou**

**Comment by nkolev92** [comment]
Hey @RichardJFoster 

We can certainly add some http examples, but the action is always going to be impacted by the actual error. 
In your case, are you able to access the url using a simple console app with http client?
NuGet uses simple http client, so it's unlikely that NuGet can provide anything more than generic guidance.

**Comment by RichardJFoster** [comment]
That's understandable that you wouldn't be able to provide the exact cause in many cases @nkolev92. That said, from my perspective the message was just a little _too_ generic. On reading "Unable to load the service index..." my brain didn't immediately go "there's something wrong with our certificate" and the help content didn't point me that way either.

I didn't immediately jump to trying a console app using HttpClient directly as I assumed `curl` would be sufficient to confirm that the NuGet server's response was valid (which it was, with the exception of the TLS certificate not being issued by a trusted CA).

We did solve the problem a few hours after I opened the case. We were using a self-signed certificate on that server (because IT are a pain and have so-far been unwilling to support our use of LetsEncrypt or an equivalent ACME service) and my manager had accidentally installed the wrong certificate to the identify the issuing (internal) CA as trusted.

As our problem is resolved, feel free to close this case out although I still feel that some suggestions of what might go wrong in the HTTPS scenario would be useful - even if it's limited to the suggestion of using the simple HttpClient console app you mention (which I think I may even have seen in a StackOverflow answer yesterday too) to provide additional information, and/or a bullet list of things to check.

**Comment by nkolev92** [comment]
> As our problem is resolved, feel free to close this case out although I still feel that some suggestions of what might go wrong in the HTTPS scenario would be useful - even if it's limited to the suggestion of using the simple HttpClient console app you mention (which I think I may even have seen in a StackOverflow answer yesterday too) to provide additional information, and/or a bullet list of things to check.

I think we can still some more details. 

Did you get any other error message beyond the one telling you the service index can't be loaded? I'm hoping that we show you more than just that.

**Comment by RichardJFoster** [comment]
Regrettably, no. As least as far as what makes it back to the console from the call to MSBuild, it seems to be just that single service index message. I did check all the available build artifacts in the hope of finding more, but was unsuccessful. :-(

For context, our build script is just triggering MSBuild on the solution while passing in various options needed by the build (version information, copyright message, and a few flags related to Windows Installer XML).

**Comment by RichardJFoster** [comment]
Correction. A single service index message for each project in the solution. They all have the same message though.

**Comment by nkolev92** [comment]
> Regrettably, no. As least as far as what makes it back to the console from the call to MSBuild, it seems to be just that single service index message. I did check all the available build artifacts in the hope of finding more, but was unsuccessful. :-(

There's probably an internal exception that might be swallowed. I was hoping that'd be available.

**Comment by RichardJFoster** [comment]
> There's probably an internal exception that might be swallowed. I was hoping that'd be available.

Indeed, and I suspect you're right about it being swallowed. That internal exception (or at least the message from it) could have been very helpful.

**Comment by nkolev92** [comment]
I created https://github.com/NuGet/Home/issues/12530.
