### ISSUE TITLE
Add Linux/OSX experience to Configuring NuGet Behavior

### ISSUE THREAD

**Issue by kraigb** [NuGet/docs.microsoft.com-nuget#305]
Original comment below; larger work item is that the whole topic needs to reflect the experience on Linux/Mac alongside the Windows experience, which will take some hours of investment to pull together the necessary examples.

Post Time: 2017-05-01 13:02 (UTC)
Area: NuGet
Article: Configuring the behavior of NuGet | Microsoft Docs
https://docs.microsoft.com/en-us/nuget/consume-packages/configuring-nuget-behavior

CommentsCategory: Content-Incomplete   Sentiment: 19%
Comments:
I'm missing the linux/macOS paths for the config files. This documentation only documents the behaviour for Windows.

**Comment by kraigb** [comment]
Note that there are comments providing paths; I've also asked the NuGet team for details.

**Comment by alpaix** [comment]
Please update the documentation with a MacOS config location. It's not trivial to browse through comments to find the right value. Also people suggested two different locations  `~/.nuget/Nuget/Nuget.Config` and `~/.config/NuGet/NuGet.Config` which is very confusing.

**Comment by kraigb** [comment]
@anangaur @karann-msft Can one of you verify the correct paths on Mac and Linux for the config files?

**Comment by karann-msft** [comment]
this applies to everything that isn’t Windows today, so both Linux and macOS
~/.local/share 
OR
$XDG_DATA_HOME (if the variable is set, the default value for this variable is ~/.local/share according to https://standards.freedesktop.org/basedir-spec/basedir-spec-latest.html)

**Comment by kraigb** [comment]
Changed title and expanded the scope of this work item.

**Comment by CamSoper** [comment]
FYI @kraigb - Working on this, but I'm off week of 3/19.  Will resume when I return.

**Comment by CamSoper** [comment]
I never closed this. Work is complete.
