### ISSUE TITLE
Including native assemblies is very confusion and underdocumented

### ISSUE THREAD

**Issue by tilkinsc** [NuGet/docs.microsoft.com-nuget#3091]
Hello,
I recently went on a hour or two rabbit hole journey in the C# discord server, in where I was trying to get my native libraries I built available on other machines that import my library via nuget package reference as opposed to a direct project reference. I think it would be net beneficial to expand further on the information in this article.

This is crucial to understand, as `[DllImport("name")]` can automatically find your natives as opposed to you hardcoding the path to the resulting native.

In reference to,
https://github.com/NuGet/docs.microsoft.com-nuget/blob/main/docs/create-packages/Supporting-Multiple-Target-Frameworks.md

It appears the correct path you can include native assemblies are,
```
runtimes/[RID]/native/[.NETVersion]/*.{dll,so}
runtimes/[RID]/native/*.{dll,so}
```

So for example,
```
runtimes/win-x64/native/example.dll
runtimes/win-x64/native/net7.0/example.dll
runtimes/linux-x64/native/example.so
runtimes/linux-x64/native/net7.0/example.so
```

See also,
https://learn.microsoft.com/en-us/dotnet/core/rid-catalog

**Comment by zivkan** [comment]
@tilkinsc it sounds like you were able to successfully create a package that works.  I spent the last few hours trying to write a doc. Here's how far I got before I ran out of time: https://github.com/NuGet/docs.microsoft.com-nuget/pull/3092

I'd appreciate if you could take a look and provide any constructive feedback

**Comment by tilkinsc** [comment]
Documentation was worked on and I do believe its much better than it was. Closing. Request to re-open if progress isn't complete.
