### ISSUE TITLE
Stupid help suggestion

### ISSUE THREAD

**Issue by arpit2408** [NuGet/docs.microsoft.com-nuget#3107]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: ddfddc4f-d20c-a078-4e72-a997633a48d9
* Version Independent ID: ddfddc4f-d20c-a078-4e72-a997633a48d9
* Content: [NuGet Error NU1301](https://learn.microsoft.com/en-us/nuget/reference/errors-and-warnings/nu1301?f1url=%3FappId%3DDev16IDEF1%26l%3DEN-US%26k%3Dk(NU1301)%26rd%3Dtrue)
* Content Source: [docs/reference/errors-and-warnings/NU1301.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/main/docs/reference/errors-and-warnings/NU1301.md)
* Service: **nuget**
* GitHub Login: @nkolev92
* Microsoft Alias: **jodou**

**Comment by nkolev92** [comment]
Closing as this issue has no content.
