### ISSUE TITLE
GlobalPackageReference usage together with sub Directory.Package.Props

### ISSUE THREAD

**Issue by BenjaminAbt** [NuGet/docs.microsoft.com-nuget#3108]
We want to use the new GlobalPackageReference possibilities to simplify our dependencies.
To do this, we want to define our packages at the root level via `PackageVersion` according to the documentation, which works in principle.

For all test projects we now want to create another `Directory.Packages.props` where basic test dependencies are configured - this would streamline our projects immensely. Unfortunately this does not work.
It does not matter whether the additional props file exists or not.
We can't seem to make certain dependencies known via GlobalPackageReference - although the [blogpost](https://devblogs.microsoft.com/nuget/announcing-nuget-6-4-signed-central-delivered/) says that this should work with all dependencies.

The structure is as follows:

```shell
- src/
- tests/
	-  Directory.Packages.props
- Directory.Build.props
- Directory.Packages.props
```

For this purpose we have defined our test dependencies as GlobalPackageReference.
The result is
 >CS0246 The type or namespace name 'TheoryAttribute' could not be found (are you missing a using directive or an assembly reference?).	

So the dependency is not found, although I would expect this from `GlobalPackageReference`.

It is now not clear to us from the documentation whether our intention can work at all and if so how.

Main File
```xml
<Project>

    <PropertyGroup>
        <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
    </PropertyGroup>

   <!-- Global References-->
   <ItemGroup>
     <GlobalPackageReference Include="Enums.NET" Version="4.0.1" />
     <GlobalPackageReference Include="Roslynator.Analyzers" Version="4.3.0"/>
     <GlobalPackageReference Include="Microsoft.CodeAnalysis.Common" Version="4.6.0" />
     <GlobalPackageReference Include="Microsoft.CodeAnalysis.CSharp" Version="4.6.0" />
     <GlobalPackageReference Include="Microsoft.CodeAnalysis.Razor" Version="6.0.20" />
     <GlobalPackageReference Include="Nerdbank.GitVersioning" Version="3.6.133" />
    </ItemGroup>

    <ItemGroup>
        <PackageVersion Include="MediatR" Version="12.1.1" />
        <PackageVersion Include="SmartFormat.NET" Version="3.2.1" />
        <PackageVersion Include="OneOf" Version="3.0.255" />
        <PackageVersion Include="Refit" Version="7.0.0" />
 
.. more packages
```

Test File:

```xml
<Project>
    <Import Project="$([MSBuild]::GetPathOfFileAbove(Directory.Packages.props, $(MSBuildThisFileDirectory)..))" />

    <PropertyGroup>
        <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
    </PropertyGroup>

    <ItemGroup>
        <GlobalPackageReference Include="FluentAssertions" Version="6.11.0" />
        <GlobalPackageReference Include="Microsoft.NET.Test.Sdk" Version="17.6.3" />
        <GlobalPackageReference Include="Moq" Version="4.18.4" />
        <GlobalPackageReference Include="AutoFixture" Version="4.18.0" />
        <GlobalPackageReference Include="AutoFixture.AutoMoq" Version="4.18.0" />
        <GlobalPackageReference Include="AutoFixture.Xunit2" Version="4.18.0" />
        <GlobalPackageReference Include="AutoFixture.SeedExtensions" Version="4.18.0" />
        <GlobalPackageReference Include="xunit" Version="2.5.0" />
        <GlobalPackageReference Include="xunit.runner.console" Version="2.5.0">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </GlobalPackageReference>
        <GlobalPackageReference Include="xunit.runner.visualstudio" Version="2.5.0">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </GlobalPackageReference>
        <GlobalPackageReference Include="coverlet.msbuild" Version="6.0.0">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers</IncludeAssets>
        </GlobalPackageReference>
    </ItemGroup>
</Project>
```

We also deleted the second file (in tests/) and added the Global stuff to the main file - same result.

It would be great if the documentation would be extended and not only the first steps are documented.
Overall, the documentation is missing some scenarios that can only be known by browsing closed GitHub issues.

Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 2d000f01-60a3-59c2-e06d-c02c8721fa76
* Version Independent ID: 2d000f01-60a3-59c2-e06d-c02c8721fa76
* Content: [Central Package Management](https://learn.microsoft.com/en-us/nuget/consume-packages/central-package-management)
* Content Source: [docs/consume-packages/Central-Package-Management.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/main/docs/consume-packages/Central-Package-Management.md)
* Service: **nuget**
* GitHub Login: @JonDouglas
* Microsoft Alias: **jodou**

**Comment by darjanbogdan** [comment]
Hi!

Have you been able to find a workaround for this (that still works with `Directory.Packages.props`)? I've stumbled upon the same limitation.

The latest [docs](https://learn.microsoft.com/en-us/nuget/consume-packages/Central-Package-Management#global-package-references) says that all `GlobalPackageReferences` are included with following properties:
- `IncludeAssets="Runtime;Build;Native;contentFiles;Analyzers"`
- `PrivateAssets="All"`

This effectively means that assemblies won't be included, hence you won't be able to use them correctly.

However, I've found a similar [thread](https://github.com/microsoft/MSBuildSdks/issues/387) in MSBuild repo, and it was suggested to override properties _inline_:
- `<GlobalPackageReference Include="Moq" Version="4.18.4" IncludeAssets="All" PrivateAssets="None" />`

Unfortunately, that also doesn't work for me, so I'm wondering why it wasn't ported from [Microsoft.Build.CentralPackageVersions](https://github.com/microsoft/MSBuildSdks/tree/main/src/CentralPackageVersions#microsoftbuildcentralpackageversions)

The only way I found to reference packages across all test projects is to add another `tests/Directory.Build.props` with `PackageReference` elements that explicitly set the `Version` property.

```xml
 <Project>
   <Import Project="../Directory.Build.props" />
   <ItemGroup>
        <PackageReference Include="FluentAssertions" Version="6.11.0" />
        <PackageReference Include="Moq" Version="4.18.4" />
        <PackageReference Include="NUnit" Version="3.13.3" />
    </ItemGroup>
</Project>
```
However, this doesn't work with `Directory.Packages.props` which is suboptimal as it deviates from the rest of solution.

**Comment by darjanbogdan** [comment]
Hi, it would be helpful to get an answer on the question I had above. Thanks!

**Comment by Mikejo5000** [comment]
Very sorry for the delayed response. We are phasing out GitHub issues as the feedback mechanism on documentation content and replacing it with a new feedback system. If you believe your feedback needs to be addressed, please submit a PR, or use the Feedback link on the article, or copy the content here to a new issue at https://github.com/NuGet/Home/issues

**Comment by Mikejo5000** [comment]
We apologize for the inconvenience. We are phasing out GitHub issues as the feedback mechanism on NuGet documentation content and replacing it with a new feedback system using the Feedback link within the articles. If you believe your feedback needs to be preserved and addressed, please submit a PR or open a new issue at https://github.com/NuGet/Home/issues

**Comment by Mikejo5000** [comment]
We apologize for the inconvenience. We are phasing out GitHub issues as the feedback mechanism on NuGet documentation content and replacing it with a new feedback system using the Feedback link within the articles. If you believe your feedback needs to be preserved and addressed, please submit a PR or open a new issue at https://github.com/NuGet/Home/issues
