### ISSUE TITLE
"NuGet Get Nearest Framework Tool" link is broken

### ISSUE THREAD

**Issue by erdembayar** [NuGet/docs.microsoft.com-nuget#3113]
Check https://learn.microsoft.com/en-us/nuget/reference/target-frameworks#net-standard
Here this aka.ms link is broken, it redirect to Bing instead of actual tool.
![image](https://github.com/NuGet/docs.microsoft.com-nuget/assets/8766776/b384498e-0e95-4f66-9960-0945f35f3937)

**Comment by nkolev92** [comment]
cc @joelverhagen

**Comment by joelverhagen** [comment]
Thanks for the heads up. Looks like that "aka.ms" link died somehow! It's now fixed.
