### ISSUE TITLE
Invalid Xml Adding Package Source Mapping

### ISSUE THREAD

**Issue by alexhiggins732** [NuGet/docs.microsoft.com-nuget#3118]
When using the example code to add package mappings in nuget.config [here](https://learn.microsoft.com/en-us/nuget/consume-packages/package-source-mapping#enable-by-manually-editing-nugetconfig) Visual Studio complains the xml is not valid because the xml document has multiple root elements.

nuget.config:

``` xml

<!-- Define the package sources, nuget.org and contoso.com. -->
<!-- `clear` ensures no additional sources are inherited from another config file. -->
<packageSources>
  <clear />
  <!-- `key` can be any identifier for your source. -->
  <add key="nuget.org" value="https://api.nuget.org/v3/index.json" />
  <add key="contoso.com" value="https://contoso.com/packages/" />
</packageSources>

<!-- Define mappings by adding package patterns beneath the target source. -->
<!-- Contoso.* packages and NuGet.Common will be restored from contoso.com, everything else from nuget.org. -->
<packageSourceMapping>
  <!-- key value for <packageSource> should match key values from <packageSources> element -->
  <packageSource key="nuget.org">
    <package pattern="*" />
  </packageSource>
  <packageSource key="contoso.com">
    <package pattern="Contoso.*" />
    <package pattern="NuGet.Common" />
  </packageSource>
</packageSourceMapping>

```

Visual Studio Error:

![image](https://github.com/NuGet/docs.microsoft.com-nuget/assets/2246388/6930e9ee-e505-4a40-bd35-e68ef2869689)

Environment:
Visual Studio Enterprise 17.5.4,
![image](https://github.com/NuGet/docs.microsoft.com-nuget/assets/2246388/8ed0b27b-720d-46e6-916b-31fac20babbf)

 Windows 11 21H2
![image](https://github.com/NuGet/docs.microsoft.com-nuget/assets/2246388/c818579f-63ec-4806-b370-a559b289bd5c)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 15617693-33df-025b-26c3-2d80e4df68d3
* Version Independent ID: 15617693-33df-025b-26c3-2d80e4df68d3
* Content: [Package Source Mapping](https://learn.microsoft.com/en-us/nuget/consume-packages/package-source-mapping)
* Content Source: [docs/consume-packages/Package-Source-Mapping.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/main/docs/consume-packages/Package-Source-Mapping.md)
* Service: **nuget**
* GitHub Login: @nkolev92
* Microsoft Alias: **nikolev**

**Comment by nkolev92** [comment]
Hey @alexhiggins732 

The example wasn't intended to be something you just copy into your config. 

You can just wrap the content to start with 
`<?xml version="1.0" encoding="utf-8"?>
<configuration>`

and end with 
`</configuration>`

**Comment by alexhiggins732** [comment]
The point is I as developer had no idea that it needed to be inside a configuration tag and had to spend time searching for other document to find out why the example was causing errors. It should be clear in the example this is needed, and in the documentation for the example.

**Comment by donnie-msft** [comment]
There's an existing issue that I believe is the same request. Thanks for providing more context!
https://github.com/NuGet/docs.microsoft.com-nuget/issues/3081
