### ISSUE TITLE
LiveFyre Comments on How to Create a NuGet Package

### ISSUE THREAD

**Issue by kraigb** [NuGet/docs.microsoft.com-nuget#312]
Two comments here.

The first is inline (sidenote)--last line under "Including MSBuild props and targets":

It's unclear wether this is still the case after netcli tooling released with the new csproj format and ditching project.json. Is project.lock.json still used, or nuget has reverted to the old 2.x behavior?

Second one is posted in the comments:

Post Time: 2017-04-18 08:22 (UTC)
Area: (unknown)
Article: How to create a NuGet package | Microsoft Docs
https://docs.microsoft.com/en-us/nuget/create-packages/creating-a-package
CommentsCategory: Kudos   Sentiment: 50%
Comments:
It is said that the 'tools' folder will be added to the PATH.But after installing a package with a 'tools' folder, the PATH on my computer was not changed at all.Is there something we should know about that?Thanks!

**Comment by kraigb** [comment]
Additional sidenote comments, under Setting a Package Type below. @anangaur @karann-msft -- PM needs to review this topic thoroughly for references/usage of packages.config, project.json, and PackageReference as the comments indicate that the content is a little outdated.

darrell.tunnell 
project.json - assuming these docs need updating! :-)
2 · Reply 


Shrike 
"When a DotnetCliTool package is installed, Visual Studio places the package in the project.json tools node instead of the dependencies node." - please update, how DotnetCliTools is processed in new VS SDK-projects (VS15.3)?

**Comment by kraigb** [comment]
Also for MSBuild targets: Add examples on how to use the content while packaging from VS2017 IDE

**Comment by CamSoper** [comment]
Rolling up to #777
