### ISSUE TITLE
Example on specifying single package source needed

### ISSUE THREAD

**Issue by vborovikov** [NuGet/docs.microsoft.com-nuget#3122]
> To resolve this warning, map your package sources with [package source mapping](https://aka.ms/nuget-package-source-mapping) or specify a single package source.

It's unclear how to specify the single package source for a package reference. Is it a special attribute for `<PackageVersion/>` tag?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 2d000f01-60a3-59c2-e06d-c02c8721fa76
* Version Independent ID: 2d000f01-60a3-59c2-e06d-c02c8721fa76
* Content: [Central Package Management](https://learn.microsoft.com/en-us/nuget/consume-packages/Central-Package-Management)
* Content Source: [docs/consume-packages/Central-Package-Management.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/main/docs/consume-packages/Central-Package-Management.md)
* Service: **nuget**
* GitHub Login: @JonDouglas
* Microsoft Alias: **jodou**

**Comment by donnie-msft** [comment]
Hi @vborovikov , just so I understand you better, are you using CPM but do not have Package Source Mapping enabled? The package source mapping link you quoted takes you to another docs page which shows a few ways to enable source mapping.

**Comment by vborovikov** [comment]
I was looking for a way to specify the package sources directly in `Directory.Packages.props`.

**Comment by donnie-msft** [comment]
You can specify package sources in your `nuget.config`. That cannot be done in the `Directory.Packages.props`. The Package Source Mapping link in your first post sounds like what you need to enable in your `nuget.config`.
