### ISSUE TITLE
Update version number (or remove) for NuGet.Build.Tasks.Pack

### ISSUE THREAD

**Issue by michael-hawker** [NuGet/docs.microsoft.com-nuget#3124]
The example points to `NuGet.Build.Tasks.Pack` version **5.2.0** [here in this section](https://learn.microsoft.com/en-us/nuget/create-packages/creating-a-package-msbuild#add-the-nugetbuildtaskspack-package):

```xml
<PackageReference Include="NuGet.Build.Tasks.Pack" Version="5.2.0"/>
```

However, this version is years old (and even unlisted on NuGet now), and as I was bashing my head against an issue for the last few weeks as it doesn't properly support the `PackageIcon` property recommended for use for current NuGet guidelines...

The doc here should be updated to not reference a specific version or be included with updates to the base package, which is now at **6.7.0**.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 31da7408-981b-cc54-1791-ca39dbdbc091
* Version Independent ID: 2060c9e8-7f2e-5da1-ee19-d196f38339fe
* Content: [Create a NuGet package using MSBuild](https://learn.microsoft.com/en-us/nuget/create-packages/creating-a-package-msbuild)
* Content Source: [docs/create-packages/creating-a-package-msbuild.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/main/docs/create-packages/creating-a-package-msbuild.md)
* Service: **nuget**
* GitHub Login: @JonDouglas
* Microsoft Alias: **jodou**

**Comment by zivkan** [comment]
that example REALLY needs `PrivateAssets="true"` as well 😞

**Comment by michael-hawker** [comment]
> that example REALLY needs `PrivateAssets="true"` as well 😞

Good call, I didn't even think of that. This is what we're using now:

```xml
<PackageReference Include="NuGet.Build.Tasks.Pack" Version="6.7.0" PrivateAssets="all" Pack="false" />
```
