### ISSUE TITLE
Severity	Code	Description	Project	File	Line	Suppression State Error	NU1100	Unable to resolve 'Swashbuckle.AspNetCore (>= 6.5.0)' for 'net7.0'. PackageSourceMapping is enabled, the following source(s) were not considered: Microsoft Visual Studio Offline Packages, nuget.o

### ISSUE THREAD

**Issue by almjdalnafii1** [NuGet/docs.microsoft.com-nuget#3128]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: a5b306fb-72a2-e479-b745-a89b0095764d
* Version Independent ID: c0b1a587-20c1-c885-a9f8-1cb7340f1d51
* Content: [NuGet Error NU1100](https://learn.microsoft.com/en-us/nuget/reference/errors-and-warnings/nu1100)
* Content Source: [docs/reference/errors-and-warnings/NU1100.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/main/docs/reference/errors-and-warnings/NU1100.md)
* Service: **nuget**
* GitHub Login: @zhili1208
* Microsoft Alias: **lzhi**

**Comment by donnie-msft** [comment]
Hello, could you please fill out a description with your suggestion? The title appears to be pointing to Scenario 2 on that page: https://learn.microsoft.com/en-us/nuget/reference/errors-and-warnings/nu1100#scenario-2
