### ISSUE TITLE
Include detail on how often NuGet credential providers are called

### ISSUE THREAD

**Issue by mungojam** [NuGet/docs.microsoft.com-nuget#3142]
Before I set off on making my own credential provider, it would be useful to know how often it will be called, i.e. is it once per HTTP request, once per high level nuget operation, once per lower level operation. Or is it cached for a while across multiple nuget calls?

Ideally we would be able to return and expiry date and then nuget could decide to keep using the credentials until they were close to expiry when they would call the provider again.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 0c65baea-410a-437a-6d06-428075d06e4e
* Version Independent ID: 864a8667-e0d4-38df-9e5b-8eba5f177218
* Content: [nuget.exe Credential Providers](https://learn.microsoft.com/en-us/nuget/reference/extensibility/nuget-exe-credential-providers)
* Content Source: [docs/reference/extensibility/nuget-exe-Credential-Providers.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/main/docs/reference/extensibility/nuget-exe-Credential-Providers.md)
* Service: **nuget**
* GitHub Login: @JonDouglas
* Microsoft Alias: **jodou**

**Comment by mungojam** [comment]
It's still valid, the docs around credential provider plugins are very vague in this area

**Comment by Mikejo5000** [comment]
Very sorry for the delayed response. We are phasing out GitHub issues as the feedback mechanism on documentation content and replacing it with a new feedback system. If you believe your feedback needs to be addressed, please submit a PR, or use the Feedback link on the article, or copy the content here to a new issue at https://github.com/NuGet/Home/issues

**Comment by Mikejo5000** [comment]
We apologize for the inconvenience. We are phasing out GitHub issues as the feedback mechanism on NuGet documentation content and replacing it with a new feedback system using the Feedback link within the articles. If you believe your feedback needs to be preserved and addressed, please submit a PR or open a new issue at https://github.com/NuGet/Home/issues
