### ISSUE TITLE
Grammar issues

### ISSUE THREAD

**Issue by edmfgh** [NuGet/docs.microsoft.com-nuget#3147]
Major grammar issues:
"Avoid recommendations mention things that are generally not a good idea, but breaking the rule sometimes makes sense:

❌ AVOID NuGet package references that demand an exact version.

And finally, Do not recommendations indicate something you should almost never do:"

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: f519bf56-3618-bfba-3921-cacea56e810a
* Version Independent ID: 9786b989-bce5-13ae-1e24-e88d7cadb7d3
* Content: [Package authoring best practices](https://learn.microsoft.com/en-us/nuget/create-packages/package-authoring-best-practices)
* Content Source: [docs/create-packages/Package-authoring-best-practices.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/main/docs/create-packages/Package-authoring-best-practices.md)
* Service: **nuget**
* GitHub Login: @nkolev92
* Microsoft Alias: **nikolev**

**Comment by nkolev92** [comment]
Looking at it, I don't think there's a grammatical error necessarily, but there's definitely some ambiguity. 

> **Avoid recommendations** mention things that are generally not a good idea, but breaking the rule sometimes makes sense

In this case, `Avoid recommendations` is the object. 
Similar thing applies to the other sentence as well.

Maybe there's a way to rewrite it to reduce the ambiguity though.
