### ISSUE TITLE
Nuget.config - Missing settings for Package Source Mapping

### ISSUE THREAD

**Issue by danm-de** [NuGet/docs.microsoft.com-nuget#3148]
Missing settings for the new feature https://learn.microsoft.com/en-us/nuget/consume-packages/package-source-mapping

E.g.:

```xml
<!-- Define mappings by adding package patterns beneath the target source. -->
<!-- Contoso.* packages and NuGet.Common will be restored from contoso.com, everything else from nuget.org. -->
<packageSourceMapping>
  <!-- key value for <packageSource> should match key values from <packageSources> element -->
  <packageSource key="nuget.org">
    <package pattern="*" />
  </packageSource>
  <packageSource key="contoso.com">
    <package pattern="Contoso.*" />
    <package pattern="NuGet.Common" />
  </packageSource>
</packageSourceMapping>
``` 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 0ea1390e-db36-6759-3095-ebab9d546fdb
* Version Independent ID: ca88d8c6-0515-a267-aac3-a508c54157ab
* Content: [nuget.config File Reference](https://learn.microsoft.com/en-us/nuget/reference/nuget-config-file)
* Content Source: [docs/reference/nuget-config-file.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/main/docs/reference/nuget-config-file.md)
* Service: **nuget**
* GitHub Login: @JonDouglas
* Microsoft Alias: **jodou**

**Comment by donnie-msft** [comment]
Hello! I do see a source mapping section on the nuget.config page here: https://github.com/NuGet/docs.microsoft.com-nuget/blob/main/docs/reference/nuget-config-file.md#package-source-mapping-section

Did you notice that or are you saying it should have something more?

**Comment by danm-de** [comment]
Oh, I could swear I didn't find it there in September. But the Git history says otherwise. Thanks and sorry!
