### ISSUE TITLE
error : CopyWin32Resources failed with exit code 500

### ISSUE THREAD

**Issue by WDJ-01** [NuGet/docs.microsoft.com-nuget#3155]
Hi I'm busy building on a UWP App in Xamarin and when I run my code I get the below error. I have had some success repairing visual studio then the app will run once and as soon as any changes are made I get the same error.  I've replicated this on a new UWP app and get the same error.

1>C:\Users\WiandeJager\.nuget\packages\microsoft.net.uwpcoreruntimesdk\2.2.14\tools\CoreRuntime\Microsoft.Net.CoreRuntime.targets(238,5): error : CopyWin32Resources failed with exit code 500

**Comment by zivkan** [comment]
Hello,  we don't support individual packages (unless they happen to be created by the NuGet team ourselves). You can go to the package details page: https://www.nuget.org/packages/Microsoft.Net.UWPCoreRuntimeSdk/

There you can check the package's website, or if you log into nuget.org, you can use the "contact owners" button.

**Comment by WDJ-01** [comment]
Thank you for your response. I'll continue my issue with nuget.org
