### ISSUE TITLE
Nuget.org doesn't work

### ISSUE THREAD

**Issue by TimoRiikonenIF** [NuGet/docs.microsoft.com-nuget#3160]
I installed Visual Studio 2022
Nuget.org is not on list as a default.
I tried to add it, but I get error 404 Not Found when I search anything.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: ef71b45e-0bb6-6e61-3b42-8e8f150db9fb
* Version Independent ID: 129fb470-7186-059a-fbe8-29b1caf96bf9
* Content: [Quickstart: Install and use a NuGet package in Visual Studio (Windows only)](https://learn.microsoft.com/en-us/nuget/quickstart/install-and-use-a-package-in-visual-studio)
* Content Source: [docs/quickstart/install-and-use-a-package-in-visual-studio.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/main/docs/quickstart/install-and-use-a-package-in-visual-studio.md)
* Service: **nuget**
* GitHub Login: @JonDouglas
* Microsoft Alias: **jodou**

**Comment by nkolev92** [comment]
If this does happen, this is a product issue.
