### ISSUE TITLE
Examples?

### ISSUE THREAD

**Issue by mfm-gwt** [NuGet/docs.microsoft.com-nuget#3161]
Could we get some examples and links to packages that provide or consume targets and props in this way?

When I follow the suggested steps it appears to be creating the package as expected. I see the targets and props appear in the consuming project. But those files aren't actually created on the filesystem and neither the apparent name or the suggested names {PackageName}.nuget.g.props / {PackageName}.nuget.g.targets seem to work.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 51da5b55-188e-a46f-4b60-9785521ab513
* Version Independent ID: 51da5b55-188e-a46f-4b60-9785521ab513
* Content: [MSBuild props and targets in a package](https://learn.microsoft.com/en-us/nuget/concepts/msbuild-props-and-targets)
* Content Source: [docs/concepts/MSBuild-props-and-targets.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/main/docs/concepts/MSBuild-props-and-targets.md)
* Service: **nuget**
* GitHub Login: @nkolev92
* Microsoft Alias: **nikolev**

**Comment by nkolev92** [comment]
@mfm-gwt It's {ProjectName}.nuget.g.targets, not PackageName. 

Those would normally be in the project folder. Does that address your question?
