### ISSUE TITLE
Add a mention of using floating versions with prerelease packages

### ISSUE THREAD

**Issue by EronWright** [NuGet/docs.microsoft.com-nuget#3173]
This document talks about how to specify the version of a `PackageReference`. What it doesn't mention is:
- how you may use pre-release versions with an exact match.
- how a floating version may or may not match a prerelease version, as described here: https://github.com/NuGet/Home/wiki/Support-pre-release-packages-with-floating-versions

For example:
```xml
  <ItemGroup>
    <PackageReference Include="Contoso.Utility.UsefulStuff" Version="3.*-*"/>
  </ItemGroup>
```

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 19c82e43-a3ec-102d-38c4-9ca1a09e98b7
* Version Independent ID: 9b037f92-00d4-de61-4295-ddfe3027dbe1
* Content: [NuGet PackageReference in project files](https://learn.microsoft.com/en-us/nuget/consume-packages/package-references-in-project-files)
* Content Source: [docs/consume-packages/Package-References-in-Project-Files.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/main/docs/consume-packages/Package-References-in-Project-Files.md)
* Service: **nuget**
* GitHub Login: @nkolev92
* Microsoft Alias: **nikolev**

**Comment by nkolev92** [comment]
This could be as simple as adding an example:

>     <PackageReference Include="Contoso.Utility.UsefulStuff" Version="3.6.0-*.*" />

We'd be happy to take a PR @EronWright
