### ISSUE TITLE
document that package source credentials can be specified via environment variables

### ISSUE THREAD

**Issue by zivkan** [NuGet/docs.microsoft.com-nuget#3185]
https://github.com/NuGet/NuGet.Client/blob/229ddddf43a8b4d9a4a796d6b36736f87b8f0e16/src/NuGet.Core/NuGet.Configuration/PackageSource/PackageSourceProvider.cs#L279-L285

**Comment by kartheekp-ms** [comment]
The regular expression linked in the above comment will match strings that start with `Username=`, followed by any characters for the username, then `; Password=`, followed by any characters for the password, and optionally `; ValidAuthenticationTypes=` followed by any characters for the authentication types. The match ends at the end of the string.

For example, it would match and capture from a string like "Username=admin; Password=12345; ValidAuthenticationTypes=type1,type2". Here, 'admin' would be captured as the user, '12345' as the pass, and 'type1,type2' as authTypes.
