### ISSUE TITLE
What is "the code"?

### ISSUE THREAD

**Issue by rhires** [NuGet/docs.microsoft.com-nuget#3187]
In the Aliases example, it says "and in the code use it as following:" but what is "the code"? The example puts it in the Program.cs file, but is that the only place it can go? Are there other places it could go instead? 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: ff707668-94d6-25a5-9139-b18cc1b6b446
* Version Independent ID: 494847b9-4894-0beb-7ffa-39a2359999fa
* Content: [NuGet PackageReference in project files](https://learn.microsoft.com/en-us/nuget/consume-packages/package-references-in-project-files#packagereference-aliases)
* Content Source: [docs/consume-packages/Package-References-in-Project-Files.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/main/docs/consume-packages/Package-References-in-Project-Files.md)
* Service: **nuget**
* GitHub Login: @nkolev92
* Microsoft Alias: **nikolev**

**Comment by nkolev92** [comment]
> The example puts it in the Program.cs file, but is that the only place it can go? Are there other places it could go instead?

It can go in any file you want it to go in. 
That is just 1 example as you said.
