### ISSUE TITLE
Broken doc link for 3 ways to mitigate risk when using private packag

### ISSUE THREAD

**Issue by erdembayar** [NuGet/docs.microsoft.com-nuget#3198]
Below link is not working here: https://learn.microsoft.com/en-us/nuget/concepts/security-best-practices#nuget-feeds
I believe it should point here: https://azure.microsoft.com/mediahandler/files/resourcefiles/3-ways-to-mitigate-risk-using-private-package-feeds/3%20Ways%20to%20Mitigate%20Risk%20When%20Using%20Private%20Package%20Feeds%20-%20v1.0.pdf
![image](https://github.com/NuGet/NuGetGallery/assets/8766776/49423b3c-acdd-44f0-9892-c031196aa7e6)

**Comment by nkolev92** [comment]
Dup of https://github.com/NuGet/docs.microsoft.com-nuget/issues/3186.
