### ISSUE TITLE
A link to the reference docs would be helpful

### ISSUE THREAD

**Issue by wwilliams69** [NuGet/docs.microsoft.com-nuget#3204]
On this page with the release notes, there is no link back to the documentation for package manager.  I'm trying to use V6.4.0.111 in Visual Studio Enterprise 2022, but commands such as Find-Package are not recognizing arguments listed on https://learn.microsoft.com/en-us/powershell/module/packagemanagement/find-package?view=powershellget-2.x, the only one listed in a Bing/Google search.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: e23d0cfc-04fc-61d9-0a43-7e6e20f9ee28
* Version Independent ID: e23d0cfc-04fc-61d9-0a43-7e6e20f9ee28
* Content: [NuGet 6.4 Release Notes](https://learn.microsoft.com/en-us/nuget/release-notes/nuget-6.4)
* Content Source: [docs/release-notes/NuGet-6.4.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/main/docs/release-notes/NuGet-6.4.md)
* Service: **nuget**
* GitHub Login: @jebriede
* Microsoft Alias: **jebriede**

**Comment by nkolev92** [comment]
https://learn.microsoft.com/en-us/powershell/module/packagemanagement/find-package?view=powershellget-2.x is not what's in VIsual Studio. 

It's different from: 
https://learn.microsoft.com/en-us/nuget/reference/ps-reference/ps-ref-find-package
