### ISSUE TITLE
Nuget package signing page no longer accurate with new hardware-enforced certificate storage

### ISSUE THREAD

**Issue by daveaglick** [NuGet/docs.microsoft.com-nuget#3208]
With [the new code signing certificate storage requirements now in effect](https://knowledge.digicert.com/alerts/code-signing-changes-in-2023), the use of `nuget sign` or `dotnet nuget sign` no longer works since it can't read certificates from hardware tokens, etc.: https://github.com/NuGet/Home/issues/11948 and https://github.com/NuGet/Home/issues/11930. That means all the content on this page is now out of date and won't work for new code signing certificates.

There are alternate instructions for code signing artifacts using [the new `dotnet sign` tool](https://github.com/dotnet/sign) (though not NuGet packages) and that points towards the [NuGetKeyVaultSignTool](https://github.com/novotnyllc/NuGetKeyVaultSignTool) tool for package signing going forward, so maybe that's a place to start a rewrite of this content.

It's entirely possible I've misunderstood the situation, but as far as I can tell, `nuget sign` will stop working for any newly issued code signing certificate (and therefore all code signing certificates by the time currently legacy ones are all expired around the middle of this year).

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 5e2a0cf1-bbb7-18f7-bfed-f717da4c1812
* Version Independent ID: 0e4df241-34c7-d943-5811-9ed0d40291f1
* Content: [Signing NuGet Packages](https://learn.microsoft.com/en-us/nuget/create-packages/sign-a-package)
* Content Source: [docs/create-packages/Sign-a-Package.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/main/docs/create-packages/Sign-a-Package.md)
* Service: **nuget**
* GitHub Login: @rido-min
* Microsoft Alias: **rmpablos**

**Comment by kartheekp-ms** [comment]
FYI.. @dtivel @clairernovotny

**Comment by daveaglick** [comment]
As far as I can tell this page is still in need of a revision in light of the stronger certificate controls described in my original description.

**Comment by Mikejo5000** [comment]
Very sorry for the delayed response. We are phasing out GitHub issues as the feedback mechanism on documentation content and replacing it with a new feedback system. If you believe your feedback needs to be addressed, please submit a PR, or use the Feedback link on the article, or copy the content here to a new issue at https://github.com/NuGet/Home/issues

**Comment by Mikejo5000** [comment]
We apologize for the inconvenience. We are phasing out GitHub issues as the feedback mechanism on NuGet documentation content and replacing it with a new feedback system using the Feedback link within the articles. If you believe your feedback needs to be preserved and addressed, please submit a PR or open a new issue at https://github.com/NuGet/Home/issues
