### ISSUE TITLE
Nuget package issue

### ISSUE THREAD

**Issue by azuretutor** [NuGet/docs.microsoft.com-nuget#3213]
Hi,

I need assistance on setting my visual studio NuGet package to be fetching package from the internet.

**Comment by adeniyidev** [comment]
Got the solution from here: https://devblogs.microsoft.com/nuget/introducing-nugetsolver-a-powerful-tool-for-resolving-nuget-dependency-conflicts-in-visual-studio/.

**Comment by nkolev92** [comment]
Closing as not a doc bug.
