### ISSUE TITLE
Need `packageSourceMapping` in Example config file

### ISSUE THREAD

**Issue by donnie-msft** [NuGet/docs.microsoft.com-nuget#3215]
> Below is an example nuget.config file that illustrates a number of settings including optional ones:

This needs to include a Package Source Mapping example.

Additionally, this quote is no longer accurate, as VS now has some features to manage the source mappings.

> [This section can only be managed manually right now.](https://learn.microsoft.com/en-us/nuget/reference/nuget-config-file#package-source-mapping-section)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 0ea1390e-db36-6759-3095-ebab9d546fdb
* Version Independent ID: ca88d8c6-0515-a267-aac3-a508c54157ab
* Content: [nuget.config File Reference](https://learn.microsoft.com/en-us/nuget/reference/nuget-config-file)
* Content Source: [docs/reference/nuget-config-file.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/main/docs/reference/nuget-config-file.md)
* Service: **nuget**
* GitHub Login: @JonDouglas
* Microsoft Alias: **jodou**

**Comment by Mikejo5000** [comment]
We apologize for the inconvenience. We are phasing out GitHub issues as the feedback mechanism on NuGet documentation content and replacing it with a new feedback system using the Feedback link within the articles. If you believe your feedback needs to be preserved and addressed, please submit a PR or open a new issue at https://github.com/NuGet/Home/issues
