### ISSUE TITLE
Document auditSources

### ISSUE THREAD

**Issue by zivkan** [NuGet/docs.microsoft.com-nuget#3226]
New feature:
* https://github.com/NuGet/Home/blob/dev/accepted/2023/NuGetAudit-without-nuget.org-as-packageSource.md
* https://github.com/NuGet/Home/issues/12698
* https://github.com/NuGet/Home/issues/13211

**Comment by nkolev92** [comment]
Dup in https://github.com/NuGet/docs.microsoft.com-nuget/issues/3269.
