### ISSUE TITLE
BaGet is discontinued, BaGetter is the new kid in town

### ISSUE THREAD

**Issue by daghb** [NuGet/docs.microsoft.com-nuget#3231]
BaGet is stale and has been superseded by https://github.com/bagetter/BaGetter as the most popular fork, and is also acknowledged by the original author.

Best regards,
Dag H. Baardsen

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: aa4772b2-2159-d314-3e09-6913ef572e04
* Version Independent ID: 71936cfb-defb-07c2-7c13-f11943ce9696
* Content: [Overview of Hosting Your Own NuGet Feeds](https://learn.microsoft.com/en-us/nuget/hosting-packages/overview)
* Content Source: [docs/hosting-packages/Overview.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/main/docs/hosting-packages/Overview.md)
* Service: **nuget**
* GitHub Login: @JonDouglas
* Microsoft Alias: **jodou**

**Comment by JonDouglas** [comment]
Send a PR

**Comment by daghsentinel** [comment]
https://github.com/NuGet/docs.microsoft.com-nuget/pull/3259
