### ISSUE TITLE
Can't send email to "account@nuget.org" for Id Prefix Reservation

### ISSUE THREAD

**Issue by JonnyIV** [NuGet/docs.microsoft.com-nuget#3232]
Hello,

as in #2172 i am as well unable to send a mail to account.nuget.org with exactly the same error.

Is there an updated way to send the mail?

![image](https://github.com/NuGet/docs.microsoft.com-nuget/assets/144663662/90cc4ef7-72aa-43ca-adaa-5405d0c578b9)

Best Regards,

Marcel Rehkemper

**Comment by JonnyIV** [comment]
Statusupdate: It looks like the email has been delivered, but that makes this response even more confusing

**Comment by nkolev92** [comment]
Closing as there's no longer anything to address here. 

Future simiarl issues should go to https://github.com/NuGet/NuGetGallery/issues.
