### ISSUE TITLE
error NU1101: Unable to find package Microsoft.NET.ILLink.Tasks

### ISSUE THREAD

**Issue by kalexanderman** [NuGet/docs.microsoft.com-nuget#3239]
This has come up again with the latest VS2022 Preview. How can I fix it? Online sources have no functional answer.
Even starting a new MAUI project completely produces the error.

Error	NU1101	Unable to find package Microsoft.NET.ILLink.Tasks. No packages exist with this id in source(s): Microsoft Visual Studio Offline Packages, Package source, Package source--Maui. PackageSourceMapping is enabled, the following source(s) were not considered: C:\Program Files\dotnet\library-packs, dotnet8, nuget.org, Syncfusion WinUI Nugets 24.1.41.	xxx xxx.csproj	1

**Comment by zivkan** [comment]
@kalexanderman have you seen [the docs page for NU1101](https://learn.microsoft.com/nuget/reference/errors-and-warnings/nu1101)?

The error message you copied in this issue includes the words "PackageSourceMapping is enabled", and explicitly tells you a number of feeds were not considered. Scenario 2 in the NU1101 docs also mentions PackageSourceMapping, and says "The package in question may be available on a source that is not configured.". It also includes a link to [the package source mapping docs](https://learn.microsoft.com/en-us/nuget/consume-packages/package-source-mapping) where there is information on how to configure package source mapping.

Is this sufficient information for you to solve the problem?
