### ISSUE TITLE
Project to project references with MSBuild /t:pack not using PackageID

### ISSUE THREAD

**Issue by kraigb** [NuGet/docs.microsoft.com-nuget#326]
See comment thread on https://docs.microsoft.com/en-us/nuget/schema/msbuild-targets#comments-container, Ewout_Kramer Feb 14, 2017. Customer reports that <PackageID> in a dependent project isn't appearing in the created package, but test project below does show that behavior.

The following test scenario works with MSBuild 15.1.1012.6693.

First project: 

class1.cs:
```
using System;

namespace classlib1
{
    public class Class1
    {
    }
}
```
classlib1.csproj:

```
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard1.4</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\classlib2\classlib2.csproj"/>
  </ItemGroup>
</Project>
```

Second project:

class2.cs:
```
using System;

namespace classlib2
{
    public class Class1
    {
    }
}
```

classlib2.csproj:
```
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard1.4</TargetFramework>
    <PackageId>MyId</PackageId>
  </PropertyGroup>
</Project>
```

Run:
msbuild /t:restore classlib1.csproj
msbuild /t:pack classlib1.csproj

Open bin\debug\classlib1.1.0.0.nupkg in Package Explorer. Classlib2 is references as MyId:

![image](https://cloud.githubusercontent.com/assets/1339874/25665777/74ab4e3c-2fd3-11e7-82ab-7e6eb20da1e3.png)

**Comment by ewoutkramer** [comment]
Ok, let me try this with my own project that triggered this issue back in feb!

**Comment by ewoutkramer** [comment]
I can confirm that this bug has been fixed since.

**Comment by kraigb** [comment]
Excellent! Thanks for confirming.

**Comment by mrahhal** [comment]
Just a quick note. This can still happen if you don't restore your project first. Can happen if you're changing a PackageId of some project and directly running the pack command then inspecting the result.

**Comment by ewoutkramer** [comment]
Thanks for this interesting note @mrahhal! Fortunately, I do a full clean/restore/build/pack cycle before I publish ;-)
