### ISSUE TITLE
A potentially valid reason to continue to allow insecure HTTP sources for NuGet (with flag)

### ISSUE THREAD

**Issue by hitchhiker** [NuGet/docs.microsoft.com-nuget#3295]
HTTP sources with NuGet are going to be disallowed soon but I wanted to throw some light on a reasonable use case for HTTP:

**What we're doing**
To speed up Docker builds (unable to use buildx via Docker API) we are creating a BaGetter mirror on the local Docker network.

**Reason**
Each time a dockerfile is built, it starts in an empty container that must re-pull all NuGet packages. Out BaGetter server is local to the Docker network, and the NuGet.Config points to that during the build. Thus we eliminate the need to continually re-pull NuGet packages from your servers during each build.

**Problem**
If you completely remove HTTP then we will be forced to mess around with self-signed certs using TLS on a network that is not exposed, does not need that overhead, and use the new flag (disableTLSCertificateValidation) in 8.0.400 that allows us to ignore cert validation. None of that is needed, a direct HTTP connection is appropriate in this context.

Instead of removing HTTP, perhaps just include a flag similar to this?

```
 <?xml version="1.0" encoding="utf-8"?>
 <configuration>
   <packageSources>
     <clear />
     <add key="source" value="http://host-gateway:5555/v3/index.json" allowInsecure="true"/>
   </packageSources>
 </configuration>
```

Edit: Obviously the main MS servers would no longer support http, nor would any other instances that do not want to serve insecure content. This would only be used by people hosting their own instances that do not require that security layer.

**Ideally this would also suppress warning NU1803:** 

_You are running the 'restore' operation with an 'HTTP' source, 'http://host-gateway:5555/v3/index.json'. Non-HTTPS access will be removed in a future version. Consider migrating to an 'HTTPS' source._

**Comment by seriouz** [comment]
I see it like @hitchhiker. What is the solution for self-hosting NuGets on an intranet - possible even without internet access?

**Comment by hitchhiker** [comment]
@zivkan @Nigusu-Allehu does the flag give us the ability to use HTTP (without warnings or future removal), or does it only bypass certificate validation?
_Apologies if I've missed that somewhere, I've only been able to find the code where bypassing is done._

**Comment by hitchhiker** [comment]
@Nigusu-Allehu thank you, appreciated.
