### ISSUE TITLE
Wrong documentation in Create UWP package (C#)

### ISSUE THREAD

**Issue by HO-COOH** [NuGet/docs.microsoft.com-nuget#3310]
[Link here](https://learn.microsoft.com/en-us/nuget/guides/create-uwp-packages-cs)

Obviously, you are not packaging any `dll` files in the `nuspec` file
![image](https://github.com/NuGet/docs.microsoft.com-nuget/assets/42881734/c404a1cc-de30-4542-a4b6-a3f7d97a44bd)

But in the result screenshot, there are `dll` files out of nowhere
![image](https://github.com/NuGet/docs.microsoft.com-nuget/assets/42881734/dbef26a7-ef5b-4a27-95f2-accdd7834a82)

**Comment by Mikejo5000** [comment]
Very sorry for the delayed response. We are phasing out GitHub issues as the feedback mechanism on documentation content and replacing it with a new feedback system. If you believe your feedback needs to be addressed, please submit a PR, or use the Feedback link on the article, or copy the content here to a new issue at https://github.com/NuGet/Home/issues

**Comment by Mikejo5000** [comment]
We apologize for the inconvenience. We are phasing out GitHub issues as the feedback mechanism on NuGet documentation content and replacing it with a new feedback system using the Feedback link within the articles. If you believe your feedback needs to be preserved and addressed, please submit a PR or open a new issue at https://github.com/NuGet/Home/issues
