### ISSUE TITLE
Incorrect copyright mentioned in the LICENSE

### ISSUE THREAD

**Issue by jeffwilcox** [NuGet/docs.microsoft.com-nuget#336]
This file says copyright NuGet:
https://github.com/NuGet/docs.microsoft.com-nuget/blob/master/LICENSE

But it should be (c) .NET Foundation

**Comment by jeffwilcox** [comment]
Ping? The legal entity in the LICENSE file is not real/accurate.

**Comment by anangaur** [comment]
Thanks. I will get this fixed.

**Comment by kraigb** [comment]
This is done. @jeffwilcox please verify and close this issue when done.
