### ISSUE TITLE
LiveFyre Comment on NuGet Package Manager UI

### ISSUE THREAD

**Issue by kraigb** [NuGet/docs.microsoft.com-nuget#339]
Post Time: 2017-05-12 17:57 (UTC)
Area: NuGet
Article: NuGet Package Manager UI Reference | Microsoft Docs
https://docs.microsoft.com/en-us/nuget/tools/package-manager-ui
CommentsCategory: Content-Incomplete   Sentiment: 99%
Comments:
What's the best practice for dependencies when creating solutions that are ultimately packaged for nuget but are also locally consumed? Example: Solution0: 5 projects, 2 get packaged for nuget. Solution1: 7 projects, 4 with dependencies on Solution0 binaries.When I'm developing on Solution1 but also in heavy iteration of Solution0, it's far more convenient to set direct References to [c:\projects\Solution0\projectA\bin\debug\projectA.dll] than to a nuget source (even a local one). However, I don't want to commit my .csproj files to source with a local dependency path.  Also,   I don't want to include Solution0 projects within Solution1.sln - they're logically different, and have different source repos.

I feel like I'm missing something on "how to use nuget successfully" :).

**Comment by karann-msft** [comment]
Responded to the customer.
