### ISSUE TITLE
Left nav becomes shorter with a vertical scroll bar on docs page

### ISSUE THREAD

**Issue by anangaur** [NuGet/docs.microsoft.com-nuget#341]
Sometimes the left nav becomes shorter with a vertical scroll bar, making it difficult to use the TOC. It happens only sometimes and I do not have a consistent repro:

![image](https://cloud.githubusercontent.com/assets/14800916/26079319/34bfadc4-3977-11e7-82d6-d63d82970083.png)

**Comment by kraigb** [comment]
Please log this at https://sitehelp.microsoft.com/; this has to do with implementation of the docs.microsoft.com backend, and not the content it hosts.
