### ISSUE TITLE
There aren't any examples I can find of how to exclude specific files.

### ISSUE THREAD

**Issue by StingyJack** [NuGet/docs.microsoft.com-nuget#362]
nuget pack is always packaging the wrong things, or not packaging the right things.  Currently its including files that it shouldnt (dependency specified), so I've tried adding items to the files node as a whitelist. This only makes it complain about files have already been added and i should gtfo the files element.

I cant find documentation on how to make this only use the whitelist (which has worked before, but I will forego consistency), and all the existing usages are for "include a folder, but exclude this file or type" when I  just want to "exclude this file or type without having to specify an inclusion list." 

Can someone please point me to the spot where this is covered?

**Comment by CamSoper** [comment]
Rolling up to #775

**Comment by StingyJack** [comment]
@CamSoper - IIRC the problem here was there was the still non-obvious and (at the time) non-documented differences between issuing a `nuget  pack some.csproj` and a `nuget pack some.nuspec`. 

Trying to pack using the csproj will complain about files you may have specified in the nuspec, and has other quirks about what it will and wont and cant do that werent/arent very well explained., I just pack to the nuspec all the time because its specific and there is little guessing what will happen with the file inclusions, and it avoids the guessing game problems.

This actually had nothing to do with content files (or contentfiles - whichever is not the packageref one), but a walkthrough is/was sorely needed for some of the basic permutations...

-  single assembly  
-  assembly and content files   
-  the "same" assembly in different target frameworks  
- the same assembly for multiple target platforms  
- usage of the powershell scripts as part of a nuget package,
- using config transforms (or T4) in a package  
- tools packages/ dev only dependencies
- etc.

... some of these may exist now, I haven't looked recently.

**Comment by CamSoper** [comment]
@StingyJack Mea culpa - I was triaging and cleaning up the issues list last night and misunderstood the nuance. Reopening and assigning priority.

Thanks for explaining it to me, and I'm sorry for the mistake!

**Comment by StingyJack** [comment]
I didn't get it at first either. No need for apology. You can keep this open if it helps track any of the ideas or elements mentioned, I don't need it anymore.
