### ISSUE TITLE
SemVer 2.0 documentation

### ISSUE THREAD

**Issue by anangaur** [NuGet/docs.microsoft.com-nuget#376]
[Pending] on blog for the same.
This doc should be referenced from the NuGet gallery page for the Semver 2.0 packages.
Include list of supported clients versions for nuget.exe, dotnet.exe, VS 2017, VS 2015, Project Rider, etc.

**Comment by AndreyAkinshin** [comment]
@anangaur, what the current state of the issue?

**Comment by anangaur** [comment]
The documentation is done and can be found here: https://docs.microsoft.com/en-us/nuget/reference/package-versioning#semantic-versioning-200

However, we need to make the messaging consistent that links to this doc. This issue: https://github.com/NuGet/NuGetGallery/issues/4552 tracks it.

**Comment by xavierdecoster** [comment]
@anangaur Package details page warning for SemVer should now be consistent. If no work left on this issue, you may close it (as I don't seem to be able to do that on this repo).

**Comment by anangaur** [comment]
Closing as this the required changes are done and deployed.
