### ISSUE TITLE
Add more details about the "global packages folder", how it works/ what it is. 

### ISSUE THREAD

**Issue by nkolev92** [NuGet/docs.microsoft.com-nuget#406]
There's been some confusion among the community members on what the global packages folder actually is. 
At some points it had been called a cache from our side but it's actually an install directory for the transitive  project systems. 

//cc
@anangaur @kraigb 
Including @emgarten to clarify in case I've missed something.

**Comment by kraigb** [comment]
Addressed in PR #770
