### ISSUE TITLE
The topic: "Normalized version numbers" needs to mention SemVer v2.0.0 normalization too

### ISSUE THREAD

**Issue by anangaur** [NuGet/docs.microsoft.com-nuget#427]
https://docs.microsoft.com/en-us/nuget/reference/package-versioning#normalized-version-numbers

needs to mention:
build-metadata is removed, for example, 1.0.0+githash becomes 1.0.0

**Comment by kraigb** [comment]
I don't have enough information to make any changes here. It would be easier if you just make changes directly to the topic and submit a PR.
