### ISSUE TITLE
Need to document various ways to install packages

### ISSUE THREAD

**Issue by anangaur** [NuGet/docs.microsoft.com-nuget#432]
https://docs.microsoft.com/en-us/nuget/consume-packages/overview-and-workflow covers the workflow. We need the exact commands and UI ways of installing the packages documented at one place.

**Comment by kraigb** [comment]
(Merging #554).

Also, this should be an install topic under Consume. Without it, the TOC looks like it's missing something. Should be a fuller scenario than the quickstart, perhaps adding multiple packages, one or two of which contains more than just a DLL.

**Comment by kraigb** [comment]
https://docs.microsoft.com/en-us/nuget/consume-packages/ways-to-install-a-package
