### ISSUE TITLE
Escaped asterisks are not rendered correctly from Markdown

### ISSUE THREAD

**Issue by mairaw** [NuGet/docs.microsoft.com-nuget#436]
From @ddrinka, originally at https://github.com/dotnet/docs/issues/2993

Consider this documentation section which uses a number of asterisks: https://docs.microsoft.com/en-us/nuget/consume-packages/dependency-resolution#floating-versions

The author has attempted to escape some of them with backslashes (while some where left mistakenly unescaped). Github renders these correctly, but the docs renderer does not.

/cc @kraigb

**Comment by kraigb** [comment]
The behavior on docs is too inconsistent, so I just removed the italics from the version numbers that were at issue.
