### ISSUE TITLE
<PackageReference> project types out of date?

### ISSUE THREAD

**Issue by svick** [NuGet/docs.microsoft.com-nuget#443]
[The *Package references (PackageReference) in project files* article](https://docs.microsoft.com/en-us/nuget/consume-packages/package-references-in-project-files) says:

> At present, package references are supported in Visual Studio 2017 only, for .NET Core projects, .NET Standard projects, and UWP projects targeting Windows 10 Build 15063 (Creators Update).

But in VS 15.3, I am able to use `<PackageReference>` even in .Net Framework projects (if I set it as default in NuGet options). Should the note be updated?

Possibly related: https://github.com/NuGet/docs.microsoft.com-nuget/issues/290.

**Comment by kraigb** [comment]
Updated this article recently with current project types.
