### ISSUE TITLE
Add a file to folder from nuget package not work on UWP

### ISSUE THREAD

**Issue by wilsonvargas** [NuGet/docs.microsoft.com-nuget#445]
I've create a Nuspec file to build my nuget package for a control to Xamarin.Forms.

I want add a .ttf file into **Assets/Fonts** to UWP platform using:

```xml
<file src="ButtonCircle\ButtonCircle.FormsPlugin.UWP\Assets\Fonts\MaterialIcons-Regular.ttf" target="content\UAP10\Assets\Fonts" />
```

I've try added this to another platform but only added to PCL, Android and iOS projects, it's not possible to add to the UWP project.

![hq1uh](https://user-images.githubusercontent.com/22247447/30032066-7a81b4bc-9159-11e7-9971-a65004956208.jpg)

How can I add this file to UWP project?

**Comment by CamSoper** [comment]
Rolled up to #775
