### ISSUE TITLE
Improve documentation on Managing dependencies

### ISSUE THREAD

**Issue by m8ram** [NuGet/docs.microsoft.com-nuget#446]
On the page [An introduction to NuGet](https://docs.microsoft.com/en-us/nuget/what-is-nuget) an image is shown to explain dependencies.

The project shown includes 5 dependencies. Dependency "D" depends on "B" which is shown as an external dependency even though it is one of the 5 Top-level dependencies.

Furthermore NuGet "B" in this image has a circular dependency on itself (through dependency on "I").

Is such a setup possible and desirable?  If not I suggest to rework the example to something more realistic.

**Comment by kraigb** [comment]
I modified that graphic a while back to remove the circular dependency. As for D depending on B, it's simply trying to show that both the top-level project and package D might both use package B (as does package E which is used by F which is used by A). In this case there aren't "internal" or "external" dependencies, simply those that are _directly_ referenced by the project in question, and those that are implicitly referenced through the direct dependencies.

Note that I didn't show the redundant dependency of E on B for simplicity, although that could probably be improved.

In any case, I'm closing this particular issue. Feel free to reopen if you want other changes.
