### ISSUE TITLE
Update NU log code docs

### ISSUE THREAD

**Issue by anangaur** [NuGet/docs.microsoft.com-nuget#447]
From @emgarten: https://github.com/NuGet/Home/issues/5857
The NU log code doc should be updated for 4.4

* NU1607 has moved to NU1107
* NU1606 has moved to NU1108
* NU1608 has been added

https://github.com/NuGet/Home/wiki/Restore-errors-and-warnings/_compare/a2fe6b4f2f97ef5929b17a3c7dbddc44449114b3...ecc7b4cd554f633c5f9c288e9ff594b7eb78ea37

**Comment by kraigb** [comment]
What is the timeframe for which we should update https://docs.microsoft.com/en-us/nuget/reference/errors-and-warnings? That is, what's the timeframe for 4.4?

**Comment by kraigb** [comment]
@anangaur Please note earlier comment about the timeframe involved here? I'd like to stage the changes in a suitable branch.

**Comment by anangaur** [comment]
@kraigb Looks like i missed it. Can you make the changes asap and publish them?

**Comment by kraigb** [comment]
Done in https://github.com/NuGet/docs.microsoft.com-nuget/pull/614.
