### ISSUE TITLE
Docs for Install command DependencyVersion and Framework flags

### ISSUE THREAD

**Issue by anangaur** [NuGet/docs.microsoft.com-nuget#448]
From @emgarten: https://github.com/NuGet/Home/issues/5858

`nuget.exe install` added the following options which should be documented.

* DependencyVersion https://github.com/NuGet/NuGet.Client/blob/53ad3962093b16795402fb8b364795c2b3d31d0c/src/NuGet.Clients/NuGet.CommandLine/Commands/InstallCommand.cs#L40
* Framework https://github.com/NuGet/NuGet.Client/blob/53ad3962093b16795402fb8b364795c2b3d31d0c/src/NuGet.Clients/NuGet.CommandLine/Commands/InstallCommand.cs#L43

See the help when running these commands for more details.

**Comment by kraigb** [comment]
This is 4.4, correct? What's the release timeline for that? I have to do this work in a separate branch and not publish it until 4.4 is released.

**Comment by hickford** [comment]
* [x] Framework https://github.com/NuGet/docs.microsoft.com-nuget/pull/552
* [ ] DependencyVersion

**Comment by CamSoper** [comment]
Appears to be addressed.
