### ISSUE TITLE
Customer question in nuget.exe CLI reference (nuget locals)

### ISSUE THREAD

**Issue by kraigb** [NuGet/docs.microsoft.com-nuget#457]
See https://docs.microsoft.com/en-us/nuget/tools/nuget-exe-cli-reference#comments-container

Alex_Maslov Aug 31, 2017

The packages-cache support was dropped in 3.6.0-rc1, thus this will fail:

nuget locals packages-cache -clear

I wish they kept it as a matter of backward compatibility.

**Comment by karann-msft** [comment]
responded to the customer.
