### ISSUE TITLE
Customer question in nuget.exe CLI reference (install/uninstall)

### ISSUE THREAD

**Issue by kraigb** [NuGet/docs.microsoft.com-nuget#458]
https://docs.microsoft.com/en-us/nuget/tools/nuget-exe-cli-reference#comments-container

Dheeps Aug 21, 2017

1. I have uninstall Nuget package which unavailable in NuGet cache using below code I get error like package uninstall failed.

var installer = componentModel.GetService<IVsPackageInstaller>(); 
installer.UninstallPackage(project, NuGetPackageName, false);

2. I have removed unavailable package entry from ASP.NET Core project and install same package with available version, it's show exception like Package restore failed. Rolling back package changes in projectName while try to install that package. 

installer.installPackage(project, NuGetPackageName, false);

Can you please update if there's any solution to resolve this issue? 

I need to uninstall NuGet packages which unavailable in NuGet cache location and install same NuGet package another version which available in NuGet cache location.

Its possible to uninstall Nuget package which unavailable in NuGet cache location programmatic?

Thanks,
Dheeps

**Comment by karann-msft** [comment]
responded to the customer.
