### ISSUE TITLE
Customer question in nuget.exe CLI reference (dependencies)

### ISSUE THREAD

**Issue by kraigb** [NuGet/docs.microsoft.com-nuget#460]
https://docs.microsoft.com/en-us/nuget/tools/nuget-exe-cli-reference#comments-container

simon.vuong Aug 10, 2017

coming from a node background and working on .net core.

would "nuget add <package" be the .net core equivalent of "npm install <package>?" does it automatically satisfy version requirements between other dependencies? where does "nuget add" place the dependencies when source isn't specified? is there a "node_modules" equivalent?

**Comment by karann-msft** [comment]
responded to the customer.
