### ISSUE TITLE
Customer question in nuget.exe CLI reference (password caching)

### ISSUE THREAD

**Issue by kraigb** [NuGet/docs.microsoft.com-nuget#461]
https://docs.microsoft.com/en-us/nuget/tools/nuget-exe-cli-reference#comments-container

Thomas_Trotzki Jul 18, 2017

We are running nuget.exe under the same domain user/account on two different machines.
nuget.exe sources update -Name <source-name> -Username doesnotmatter -Password <PAT for source> -ConfigFile <path to config>
This produces different encrypted passwords in the config file
How to Setup an NuGet.Config with encrypted Passwords usable on all Build Servers?

**Comment by karann-msft** [comment]
responded to the customer
