### ISSUE TITLE
Customer question in nuget.exe CLI reference (wildcards)

### ISSUE THREAD

**Issue by kraigb** [NuGet/docs.microsoft.com-nuget#462]
https://docs.microsoft.com/en-us/nuget/tools/nuget-exe-cli-reference#comments-container

Jazzeagape Feb 3, 2017

How can you update specific packages based on a wildcard/regex pattern? I notice CLI reference ignores expressions such as (nuget.exe update a.sln | where Id -like “*DefinitelyTyped*” | foreach { update-package $_.Id  -reinstall })

**Comment by karann-msft** [comment]
responded to customer.
