### ISSUE TITLE
Customer question in package manager UI reference (C++/CLI)

### ISSUE THREAD

**Issue by kraigb** [NuGet/docs.microsoft.com-nuget#464]
https://docs.microsoft.com/en-us/nuget/tools/package-manager-ui#comments-container

jack_bauer Feb 10, 2017

I have a c++\cli project which I want to use this for, but when I try to use the NuGet package manager to install this, it fails. It seems to be unable to detect what .net framework version I'm using.

**Comment by karann-msft** [comment]
responded to the customer.

**Comment by kraigb** [comment]
I don't see a response to this question...

**Comment by karann-msft** [comment]
![image](https://user-images.githubusercontent.com/16904420/31917636-55b3fe3a-b80d-11e7-8612-cd95a4680ba4.png)
