### ISSUE TITLE
Customer question on Reinstalling and Updating packages

### ISSUE THREAD

**Issue by kraigb** [NuGet/docs.microsoft.com-nuget#465]
https://docs.microsoft.com/en-us/nuget/consume-packages/reinstalling-and-updating-packages#comments-container

zbalkan Aug 27, 2017

After a .Net Framework Upgrade (from 4.6.1 to 4.7 in my case), some packages need to be reinstalled, which notified in an untitle and unnumbered warning. I'm pretty sure this issue could be added to VS code analysis warnings as it's possible to reinstall those packages through command line or GUI in an easy way.

**Comment by karann-msft** [comment]
@kraigb  responded to the comment.
