### ISSUE TITLE
Update .nuspec file reference for content files

### ISSUE THREAD

**Issue by kraigb** [NuGet/docs.microsoft.com-nuget#466]
https://docs.microsoft.com/en-us/nuget/schema/nuspec#comments-container

Clay_Lenhart 11 days ago

"For maximum compatibility with consuming projects, a package ideally specifies the content files in both elements."
None of the examples here do this (and I'm struggling to get this to work).  Can you add an example, or point to a nuget package (with github source code) that does this? 

I'm modifying a pack that does "nuget pack MyProj.csproj"
(with the *.nuspec file next to the csproj file).

**Comment by karann-msft** [comment]
here is the blogpost for contentFiles - https://blog.nuget.org/20160126/nuget-contentFiles-demystified.html

**Comment by karann-msft** [comment]
Also, as I am looking at the doc, I am not sure what the issues is? We have examples of both content and contentFiles.

The /content folder is used in packages.config based projects, whereas /contentFiles is used is PackageReference based projects. Can we clarify that in the docs and give an example where an image has been included as both content as well as contentFiles and call out what would be consumed when.

**Comment by karann-msft** [comment]
responded to the customer.

**Comment by CamSoper** [comment]
Rolled up to #775
