### ISSUE TITLE
"Restore vs. install" and "Dependency installs" seem to be missing after Nuget.org's facelift.

### ISSUE THREAD

**Issue by alfredmyers** [NuGet/docs.microsoft.com-nuget#469]
*Restore vs. install* and *Dependency installs* seem to be missing after Nuget.org's [facelift](https://blog.nuget.org/20170718/NuGet-Gallery-Gets-A-Facelift.html).

> - *Restore vs. new install*: on the same package statistics page, clear the **Version** checkbox and select **Operation** to see a chart of package restores vs. new installs (below).
> 
>     ![Chart of operations for a NuGet package on nuget.org package statistics](media/Finding-05-OperationChart.png)
> 
> - *Dependency installs*: the same **Operation** chart above has an "Install-Dependency" bar that indicates how many other NuGet packages have taken a dependency on this one. This is an even stronger indication that other developers find the package reliable.

If these features were removed from the site we should probably remove the references to them as well. If the features weren't removed, where can they be found?

**Comment by kraigb** [comment]
Merged PR 470, so closing.
