### ISSUE TITLE
NU1202 has an incorrect example message. 

### ISSUE THREAD

**Issue by nkolev92** [NuGet/docs.microsoft.com-nuget#481]
In https://github.com/NuGet/docs.microsoft.com-nuget/blob/master/docs/Reference/Errors-and-Warnings.md#nu1202
the current example message of NU1202 
```
Package System.ComponentModel.EventBasedAsync 4.0.11 is not compatible with netstandard1.3 (.NETStandard,Version=v1.3). Package System.ComponentModel.EventBasedAsync 4.0.11 supports:
- monoandroid10 (MonoAndroid,Version=v1.0)
- monotouch10 (MonoTouch,Version=v1.0)
- net45 (.NETFramework,Version=v4.5)
- netcore50 (.NETCore,Version=v5.0)
- netstandard1.0 (.NETStandard,Version=v1.0)
- netstandard1.3 (.NETStandard,Version=v1.3)
- portable-net45+win8+wp8+wpa81 (.NETPortable,Version=v0.0,Profile=Profile259)
- win8 (Windows,Version=v8.0)
- wp8 (WindowsPhone,Version=v8.0)
- wpa81 (WindowsPhoneApp,Version=v8.1)
- xamarinios10 (Xamarin.iOS,Version=v1.0)
- xamarinmac20 (Xamarin.Mac,Version=v2.0)
- xamarintvos10 (Xamarin.TVOS,Version=v1.0)
- xamarinwatchos10 (Xamarin.WatchOS,Version=v1.0)
```

The key there is we say **System.ComponentModel.EventBasedAsync 4.0.11 is not compatible with netstandard1.3** yet few lines under we list in the compatible frameworks:
**- netstandard1.3 (.NETStandard,Version=v1.3)**

Related to https://github.com/NuGet/Home/issues/4259

I will chat with @emgarten to clear it up and will create a PR. 

/cc
@anangaur

**Comment by emgarten** [comment]
@nkolev92 fix it here: https://github.com/NuGet/Home/wiki/Restore-errors-and-warnings
And then create a PR or issue to fix the official docs
