### ISSUE TITLE
How to add a new language version for some exist topics

### ISSUE THREAD

**Issue by miao17game** [NuGet/docs.microsoft.com-nuget#483]
I find that there is no other languages supported instead of en-US.
What should I do if I want to contribute some new language versions?

**Comment by kraigb** [comment]
We're supposed to have localized versions, but those haven't happened yet. I'm investigating.

**Comment by kraigb** [comment]
From what I can see, we have localized pages for the various supported languages, e.g. https://docs.microsoft.com/ja-jp/nuget/consume-packages/ways-to-install-a-package.
