### ISSUE TITLE
NuGet.Config File Reference (proxy configuration)

### ISSUE THREAD

**Issue by mnieto** [NuGet/docs.microsoft.com-nuget#492]
Please, increase the proxy configuration documentation in https://github.com/NuGet/docs.microsoft.com-nuget/blob/00df19348edfef840ff92abf260cf0af9ef246d7/docs/Schema/nuget-config-file.md.

In particular, the no_proxy format is undocumented. After a try / error cycle I saw that exceptions are stored with regular expressions and wildcards must be escaped
in my configuration I wrote `<add key="no_proxy" value="*.mydomain.com" />`
but when updating (`nuget update -self`) an exception was trown parsing the proxy configuration. 
The correct syntax is `<add key="no_proxy" value="\*.mydomain.com" />`

**Comment by kraigb** [comment]
@karann-msft Another one to confirm with engineering.

**Comment by karann-msft** [comment]
@mnieto what version of nuget.exe are you running?
I tried that exact scenario with the latest version - 4.4, and I could not reproduce the error.

**Comment by CamSoper** [comment]
Rolled up to #776
