### ISSUE TITLE
Customer question in NuGet Command-Line Interface (CLI) (project files)

### ISSUE THREAD

**Issue by kraigb** [NuGet/docs.microsoft.com-nuget#494]
https://docs.microsoft.com/en-us/nuget/tools/nuget-exe-cli-reference#comments-container

Rahul_Kulkarni2 Sep 19, 2017

Is there a way I can get list of nuget packages installed on a solution.
Something like nuget list a.sln?
I wanted to get the package Id, version, license url, authors, owners etc.

I was trying to run in Package Manager Console the following command
Get-Package | Select -Unique Id, Version, LicenseUrl, Description, Author, Owner, RequireLicenseAcceptance | Format-Table -Autosize
However it does not return the Description, Author, Owners etc. Only generates the Id, Version and LicenseUrl in Visual Studio 2015

**Comment by kraigb** [comment]
See also this comment:

matthew_de_beer Jun 26, 2017
Is there any way of listing what packages are currently installed in a given project?

**Comment by karann-msft** [comment]
responded to both customers.

**Comment by kraigb** [comment]
Note that I corrected a link with the second response, and clarified that while the get-package cmdlet works for this, the nuget.exe CLI doesn't have the equivalent, which was the original question in that case.
