### ISSUE TITLE
Document Consolidate Feature

### ISSUE THREAD

**Issue by spottedmahn** [NuGet/docs.microsoft.com-nuget#498]
I noticed this tab today in VS go I Googled it.  I found this [SO post](https://stackoverflow.com/questions/34022454/nuget-consolidate-vs-update).  And eventually I found[ this blog post](https://blog.nuget.org/20151118/nuget-3.3.html#consolidate) but I couldn't find anything in [https://docs.microsoft.com/en-us/nuget](https://docs.microsoft.com/en-us/nuget).

I would like to propose this feature be documented here.  Thoughts?

**Comment by kraigb** [comment]
Sorry it took so long to get to this, but I've added a section to the Package Manager UI docs for this. https://github.com/NuGet/docs.microsoft.com-nuget/pull/616

**Comment by spottedmahn** [comment]
@kraigb sweet!

For reference, it was documented here: [NuGet Package Manager UI -> Consolidate tab](https://docs.microsoft.com/en-us/nuget/tools/package-manager-ui#consolidate-tab)

**Comment by kraigb** [comment]
Actually you're seeing the material I just added this afternoon. :)

**Comment by spottedmahn** [comment]
Hi @kraigb - right, that's what I figured.

I wanted to "complete the circuit" if you will.  The PR link was great but there wasn't a link to where users can view the final output!  Hope that makes sense.

**Comment by kraigb** [comment]
Oh yes...I neglected to give the page link, which I typically do. Anyway, all done!

**Comment by spottedmahn** [comment]
cool, glad we're on the same page 😄
