### ISSUE TITLE
Package Reference vs packages.config install directory/ RepositoryPath

### ISSUE THREAD

**Issue by nkolev92** [NuGet/docs.microsoft.com-nuget#509]
This issue is motivated by an internal thread/question. 

I was not able to find any docs detailing where packages are extracted in the package reference case, reasons why, and the differences from packages.config. 

//cc @anangaur @karann-msft

**Comment by anangaur** [comment]
https://docs.microsoft.com/en-us/nuget/consume-packages/package-restore has the details but today there are so many ifs and buts for the docs that users will have tough time to find what they are looking for. I and @karann-msft will be working to clean the docs in general and while doing so, we should keep this issue in mind.

**Comment by kraigb** [comment]
Addressed in PR #770
