### ISSUE TITLE
PackageReference supports PP transforms

### ISSUE THREAD

**Issue by emgarten** [NuGet/docs.microsoft.com-nuget#516]
PackageReference supports pp transforms under `contentFiles/`

The doc https://docs.microsoft.com/en-us/nuget/create-packages/source-and-config-file-transformations says that they are *not* supported, which is incorrect.

There are some issues that could be blocking this currently, but it is expected to work.

Related: https://github.com/NuGet/Home/issues/2050#issuecomment-337485476

//cc @jainaashish

**Comment by kraigb** [comment]
The page itself has been updated. Providing a sample is a separate issue.

**Comment by mudassarsaleem** [comment]
Hi,
**.cs.pp** file does not seem to be working with .NET Standard project. I have created a package with **.cs.pp** file in **contentFiles** folder. As the .NET Standard project supports the PackageReference by default, it should add the source code transformation file in the target location after transformation as **.cs** file. But it did not happen. Please guide me here or point me to the correct docs. Thanks!

@emgarten @kraigb
