### ISSUE TITLE
Customer questions in NuGet PackageReference in Visual Studio Project files

### ISSUE THREAD

**Issue by kraigb** [NuGet/docs.microsoft.com-nuget#518]
https://docs.microsoft.com/en-us/nuget/consume-packages/package-references-in-project-files#comments-container

Five total, dating back to July 22nd.

**Comment by kraigb** [comment]
Bumping to P0 as there are ten open questions (also one in a sidenote).

**Comment by CamSoper** [comment]
Gone with the Lyvefire comments
