### ISSUE TITLE
The help link on NuGet settings window is incorrect

### ISSUE THREAD

**Issue by karann-msft** [NuGet/docs.microsoft.com-nuget#523]
@anangaur commented on [Mon Apr 03 2017](https://github.com/NuGet/Home/issues/4960)

1. The help link seems to be incorrect
2. The drop-down overlaps the label in high DPI (regression?)

![image](https://cloud.githubusercontent.com/assets/14800916/24619675/a898dd36-184f-11e7-94ab-d467afeaa8d3.png)

---

@karann-msft commented on [Mon Apr 03 2017](https://github.com/NuGet/Home/issues/4960#issuecomment-291202064)

to Rob for triage.

---

@kraigb commented on [Mon Apr 03 2017](https://github.com/NuGet/Home/issues/4960#issuecomment-291280051)

The ? is likely a docs issue, because VS generates a query using certain F1 keywords that we don't currently have in the metadata of the NuGet docs pages. @karann-msft please the Docs label to this issue.

---

@karann-msft commented on [Mon Apr 03 2017](https://github.com/NuGet/Home/issues/4960#issuecomment-291280481)

I reactivated the high dpi bug we had before....feels like a regression....https://github.com/NuGet/Home/issues/4439

Let's use this issue just for the help link

**Comment by kraigb** [comment]
The help issue was corrected a long time ago, but I hadn't seen the #4960 bug to resolve it. In any case, pressing ? when the NuGet Package Manager, General, and Package Sources tab all go to  https://docs.microsoft.com/en-us/nuget/tools/package-manager-ui as expected. This is controlled by the f1_keywords: in the topic metadata:

f1_keywords: 
  - "vs.toolsoptionspages.nuget_package_manager"
  - "vs.toolsoptionspages.nuget_package_manager.general"
  - "vs.toolsoptionspages.nuget_package_manager.package_sources"
