### ISSUE TITLE
package versioning not satisfying customer expectation

### ISSUE THREAD

**Issue by karann-msft** [NuGet/docs.microsoft.com-nuget#532]
I am looking at this doc https://docs.microsoft.com/en-us/nuget/reference/package-versioning#version-ranges-and-wildcards

Where a customer has said

> This is also where other pages in this reference directed me to when trying to find out how to handle project references where each project emits a nuget package, and that info is not here.

Can we take a look at how customers arrive to this page. Nearly half the referrals are from Microsoft.

**Comment by CamSoper** [comment]
I took a look at SkyEye for you, but I'm not able to figure out how to find the Microsoft.com referrals. The data analytics team could certainly help you with this.

**Comment by Mikejo5000** [comment]
Most of these links are coming from other NuGet pages. Most of the poorly prhased links are from the What is NuGet? article and also from the set of creating packages articles. Updating docs.
