### ISSUE TITLE
update package publish steps to reflect the changes in NuGet.org UI

### ISSUE THREAD

**Issue by karann-msft** [NuGet/docs.microsoft.com-nuget#535]
I am looking at this doc -> https://docs.microsoft.com/en-us/nuget/create-packages/publish-a-package

The screenshots need replacing, and we need to talk about scoped API keys somewhere - https://blog.nuget.org/20170202/introducing-scoped-api-keys.html

**Comment by kraigb** [comment]
@karann-msft https://review.docs.microsoft.com/en-us/nuget/create-packages/publish-a-package?branch=kraigb-feedback has the updates, FYI.
