### ISSUE TITLE
NuGet.exe update should mention PackageReference

### ISSUE THREAD

**Issue by emgarten** [NuGet/docs.microsoft.com-nuget#542]
The docs for `NuGet.exe update` mention that `project.json` is not supported. It should also mention that `PackageReference` is not supported by update.

https://docs.microsoft.com/en-us/nuget/tools/cli-ref-update

**Comment by kraigb** [comment]
Fixed this a while ago.

**Comment by fishingry** [comment]
@kraigb 
"nuget update xxx.sln" could update all packages in all projects, but how to do it with "dotnet add package"?  If no, I don't think it's a fix.
https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-add-package
"dotnot add xxx.sln package" to update all packages?
Thanks a lot.

**Comment by kraigb** [comment]
@fishingry For product changes and requests like this, please file an issue on https://github.com/NuGet/Home/issues. This repo is for documentation issues only.
