### ISSUE TITLE
Explain the restore -NoCache option

### ISSUE THREAD

**Issue by anangaur** [NuGet/docs.microsoft.com-nuget#561]
Doc page: https://docs.microsoft.com/en-us/nuget/tools/cli-ref-restore

An average user would probably assume that “local machine caches” includes the **global-packages** cache (which is listed [here](https://docs.microsoft.com/en-us/nuget/consume-packages/managing-the-nuget-cache) as a cache). So it seems that the documentation needs an update.

**Comment by kraigb** [comment]
Closed in #770
