### ISSUE TITLE
Document pack extension points

### ISSUE THREAD

**Issue by rohit21agrawal** [NuGet/docs.microsoft.com-nuget#577]
An extension point has been provided for executing custom target in the inner build for files that go in the lib (or folder specified via BuildOutputTargetFolder) . A user can write their own custom target and specify it as the value of the property $(TargetsForTfmSpecificBuildOutput). The target should write out any files that need to go into the lib folder into the ItemGroup BuildOutputInPackage and set the following two metadata values :
a) FinalOutputPath : This is the absolute path of the file on disk (if not provided, the Identity is used to evaluate source path)
b) TargetPath : This is optional and defaults to the name of the file. Users need to set it when the file needs to go into a subfolder within lib\<TFM> like satellite assemblies which go under their respective culture folders.

An extension point has been provided for files that need to go in the nupkg outside of lib folder but are still TFM specific. A user can write their own custom target and specify it as the value of the property $(TargetsForTfmSpecificContentInPackage). The target should write out any files that need to be included in the nupkg into the ItemGroup TfmSpecificPackageFile and set the following metadata:
a) PackagePath : Path where the file should be output in the package. NuGet will throw a warning if more than one file is added to the same package path.
b) BuildAction: Default value has been set to None. This is only required if the package path is in contentFiles folder.

An example:

``` 
<PropertyGroup>
  <TargetsForTfmSpecificBuildOutput>$(TargetsForTfmSpecificBuildOutput);GetMyPackageFiles</TargetsForTfmSpecificBuildOutput>
</PropertyGroup>

<Target Name="GetMyPackageFiles">
  <ItemGroup>
    <BuildOutputInPackage Include="$(OutDir)*.generated.on.build.txt" />
  </ItemGroup>
</Target>

```

**Comment by kraigb** [comment]
Merged in #794
