### ISSUE TITLE
Please provide a usable nuspec schema file

### ISSUE THREAD

**Issue by StingyJack** [NuGet/docs.microsoft.com-nuget#580]
The one linked on the nuspec schema description page has a bunch of string replacements, and doesn't import into VS properly. Please link to a version of this that can be imported right into VS (surprised its not present already). 

[Here is the doc page](https://docs.microsoft.com/en-us/nuget/schema/nuspec#general-form-and-schema)

[Here is the file it links to](https://github.com/NuGet/NuGet.Client/blob/dev/src/NuGet.Core/NuGet.Packaging/compiler/resources/nuspec.xsd)

**Comment by mikkelbu** [comment]
@StingyJack Perhaps you can use https://gist.github.com/sharwell/6131243

**Comment by kraigb** [comment]
@StingyJack Please transfer this issue to https://github.com/NuGet/Home/issues as the .xsd file in question isn't in the docs repo. I'd open an issue there except I'd rather you were the originator so you get all the follow up.

**Comment by kraigb** [comment]
Oh, and close the issue here when it's transferred.

**Comment by StingyJack** [comment]
[transferred](https://github.com/NuGet/Home/issues/6295)
