### ISSUE TITLE
Document header requirements for clients

### ISSUE THREAD

**Issue by rohit21agrawal** [NuGet/docs.microsoft.com-nuget#590]
As described in : https://github.com/NuGet/Home/issues/5988
as per discussion with the team, we are going to document the fact that "X-NuGet-Client-Version" is a reserved header for official NuGet clients by Microsoft. All other clients should use the "X-NuGet-Protocol-Version" header with a min value of 4.1.0 to be able to push to NuGet.org . In addition, we should also ask them to start setting the user-agent string for telemetry purposes.
We should also fix the user-agent strings for all client entry points (except nuget.exe which already does this correctly).

**Comment by joelverhagen** [comment]
Done.
https://docs.microsoft.com/en-us/nuget/api/nuget-protocols#client-requirement
