### ISSUE TITLE
Document that RIDs are case sensitive

### ISSUE THREAD

**Issue by emgarten** [NuGet/docs.microsoft.com-nuget#592]
_From @emgarten on May 18, 2017 22:14_

The package authoring docs should include details on how RIDs are found in other packages using runtime.json, and specifically that they are case sensitive.

_Copied from original issue: NuGet/Home#5249_

**Comment by kraigb** [comment]
Please be more specific as to what the "details" here are, i.e. the process of how runtime.json is applied and what runtime.json is and what one does with it, if anything. In other words, there's not enough information in this issue to proceed further.

**Comment by emgarten** [comment]
Didn't realize runtime.json wasn't documented at all yet, that will take some time :smile:

Related: https://github.com/NuGet/Home/issues/6083

**Comment by CamSoper** [comment]
Rolled up to #600
