### ISSUE TITLE
Error in Reference/Package-Versioning.md? "packages.config" should be ".nuspec".

### ISSUE THREAD

**Issue by tomvonclef** [NuGet/docs.microsoft.com-nuget#597]
I think the line "References in packages.config" should be "References in .nuspec" based  on the code underneath it:

```
 <!-- Accepts any version 6.1 and above -->
<dependency id="ExamplePackage" version="6.1" />

<!-- Accepts any version 6.x.y version -->
<dependency id="ExamplePackage" version="6.*" />
```

The code below "References in packages.config" seems to contain .nuspec elements (`<dependency/>`) rather than packages.config elements (`<package/>`). Also, in "packages.config", the `version` attribute of `package` is documented to be "the exact version of the package to install", while the for ".nuspec" the `version` attribute of `dependency` is documented to be "The range of versions acceptable as a dependency". The code examples are for ranges.

**Comment by kraigb** [comment]
Yes, you're correct. The .nuspec examples were given for packages.config, and real packages.config examples were missing. There are now sections for both, see https://docs.microsoft.com/en-us/nuget/reference/package-versioning#version-ranges-and-wildcards.

**Comment by tomvonclef** [comment]
Thanks! But I'm still confused about the `version` attribute of the `package` element. In the [packages.config reference](https://docs.microsoft.com/en-us/nuget/schema/packages-config) it says the `version` attribute is:

> The exact version of the package to install, such as 3.1.1 or 4.2.5.11-beta. A version string must have at least three numbers; a fourth is optional, as is a pre-release suffix. Ranges are not allowed.

But in the [package versioning](https://docs.microsoft.com/en-us/nuget/reference/package-versioning#version-ranges-and-wildcards) page, it the example shows:

```xml
<!-- Install/restore version 6.1, accept any version 6.1 and above on update. -->
<package id="ExamplePackage" version="6.1" allowedVersions="6.1" />
```

Here, the `version` string only has two numbers.

**Comment by kraigb** [comment]
Urk, my bad, there should be x.y.z versions in there. I'll get that fixed.
