### ISSUE TITLE
nuspec file reference incorrectly lists minClientVersion as an element rather than attribute

### ISSUE THREAD

**Issue by ChrisMaddock** [NuGet/docs.microsoft.com-nuget#607]
https://docs.microsoft.com/en-us/nuget/schema/nuspec

On this page, `minClientVersion` is listed as an optional element to appear under the `<metadata>` element. This is incorrect - `minClientVersion` should actually be an attribute on `<metadata>`.

This caused us problems in https://github.com/nunit/nunit/pull/2595 

/cc @phillipsj

**Comment by kraigb** [comment]
Done, https://github.com/NuGet/docs.microsoft.com-nuget/pull/617.

**Comment by ChrisMaddock** [comment]
Great - thanks! 😄
