### ISSUE TITLE
Is .NET Compact Framework supported?

### ISSUE THREAD

**Issue by karann-msft** [NuGet/docs.microsoft.com-nuget#622]
@NenoLoje commented on [Thu Jan 19 2017](https://github.com/NuGet/Home/issues/4331)

**Question**: Does NuGet support creating packages for **.NET Compact Framework**?

The [Target Frameworks page](https://docs.microsoft.com/en-us/nuget/schema/target-frameworks) does not list any .NET Compact Framework versions (but others like .NET Micro Framework and very old .NET versions). 

Maybe .NET CF needs to be added to that list?

--Neno

---

@emgarten commented on [Thu Jan 19 2017](https://github.com/NuGet/Home/issues/4331#issuecomment-273925520)

I believe CF is treated as a framework profile instead of a new framework.

Example: ``net45-cf``

The docs should probably be updated to include these along with the silverlight profiles.

---

@kraigb commented on [Mon May 15 2017](https://github.com/NuGet/Home/issues/4331#issuecomment-301629309)

@emgarten Where in the source is the best place to get the definitive list of TFMs? Perhaps https://github.com/NuGet/NuGet.Client/blob/f0f9186a0d236611a104d527a8466fb789299e0c/test/NuGet.Core.Tests/NuGet.Frameworks.Test/CompatibilityTests.cs?

---

@emgarten commented on [Mon May 15 2017](https://github.com/NuGet/Home/issues/4331#issuecomment-301657986)

The profile names are here: 
https://github.com/NuGet/NuGet.Client/blob/dev/src/NuGet.Core/NuGet.Frameworks/DefaultFrameworkMappings.cs#L113-L117

The above code contains the mappings from the abbreviations to the full name.

---

@karann-msft commented on [Wed Nov 08 2017](https://github.com/NuGet/Home/issues/4331#issuecomment-342993236)

@kraigb did we close on this?

---

@kraigb commented on [Wed Nov 08 2017](https://github.com/NuGet/Home/issues/4331#issuecomment-342994891)

@karann-msft Not that I know of.

**Comment by CamSoper** [comment]
Rolled up to #778
