### ISSUE TITLE
NuGet.exe documentation should clarify that "nuget restore <packages.config> requires the -PackagesDirectory or -SolutionDirectory parameter

### ISSUE THREAD

**Issue by karann-msft** [NuGet/docs.microsoft.com-nuget#623]
@pspill commented on [Mon Jul 24 2017](https://github.com/NuGet/Home/issues/5635)

In all versions of nuget.exe, "nuget.exe restore <packages.config>" requires the use of the -PackagesDirectory or -SolutionDirectory parameter or an error will occur.  This should be clarified in the documentation for the restore command.

Note that install does not have the same restriction -- it will assume a local "packages" folder no output folder is supplied.

**Comment by kraigb** [comment]
Addressed in PR #770
