### ISSUE TITLE
Improved target documentation

### ISSUE THREAD

**Issue by jainaashish** [NuGet/docs.microsoft.com-nuget#625]
From https://github.com/NuGet/Home/issues/358

NuGet is getting a lot of new framework targets. I think the documentation needs to do a better job explaining what they are each for (and for people who don't know, explain a DNX app vs regular .NET app), explain what is loaded in different situations, and explain fallback precedence.

For example if you have a DNX project that references a package with no dnx452 assembly in it, when running on the desktop CLR will it fall back to loading dnxcore50 (because they are both DNX) or fall back to loading net45 (because they are both desktop).

Bonus points if you can also included PCLs in the fallback precedence documentation.

I realize there are a lot of scenarios once you start including Win8, Silverlight and WP - and they could probably wait for now - but this documentation would be helpful to package authors and remove a lot of guess work.

**Comment by CamSoper** [comment]
Rolled up to #778
