### ISSUE TITLE
Content Files documentation is confusing.

### ISSUE THREAD

**Issue by nkolev92** [NuGet/docs.microsoft.com-nuget#644]
The content/contentFiles documentation currently is a bit confusing. 

Please correct me if I'm wrong, the only place where we mention how to correctly include content files in here: https://github.com/NuGet/docs.microsoft.com-nuget/blob/1dbdd27a4e92e9eae05b00e4c3632cde0c8233cb/docs/Schema/msbuild-targets.md#including-content-in-a-package

ContentFiles as a concept are not mentioned in any other place (release notes not including, but those docs are not great as well).

So I think we need to do the following:

Define contentFiles as a concept and how they differ from content. 
State clearly that contentFiles are valid for package reference/project.json, and that content is used in packages.config. 
Point out differences such contentFiles are static, while content is not.

Relevant blog post here: https://blog.nuget.org/20160126/nuget-contentFiles-demystified.html

We should point out the pattern for contentfiles.
<language>/<tfm>/{AnyFile}

We should also state that when using a nuspec to pack, how to set the build action on the files. 

Verbatim from my comment on https://github.com/NuGet/Home/issues/6404

The files element that you use to include files in the nuspec, does not really set any attributes. 
You can only set attributes such as buildAction in the metadata section. 

So 
```
    <contentFiles>
      <files include="**\templates\**\*.*" buildAction="None" copyToOuput="true"  />
    </contentFiles>
``` 
is correct, 

but the buildAction and copyToOutput here, is not needed.
```
  <files>
    <file src="templates\**\*.*" target="contentFiles\any\any\templates" buildAction="None" copyToOutput="true" />
  </files>
```

This brain dump is all over the place, so feel free to ping me/come chat with me if needed.

/cc 
@karann-msft @kraigb

**Comment by CamSoper** [comment]
Rolled up to #775
