### ISSUE TITLE
Improve <repository> documentation

### ISSUE THREAD

**Issue by joelverhagen** [NuGet/docs.microsoft.com-nuget#693]
Major questions need to be answered and documented:

1. How is `<repository>` used my official tooling? _not at all today..._
1. What are valid `type` values? Is it freeform?
1. What should the `url` link to? A link that can be opened in the browser? A URL you can pass to `git clone`?

Related:

- show the data in UI: https://github.com/NuGet/NuGetGallery/issues/4941
- add commit hash to metadata: https://github.com/NuGet/Home/issues/6547

/cc @emgarten @diverdan92

**Comment by joelverhagen** [comment]
We've updated MSBuild target docs to mention the new `RepositoryBranch` and `RepositoryCommit`. We should also include these in some more high level docs.

**Comment by fschmied** [comment]
See also #1046.

**Comment by karann-msft** [comment]
Documented here - https://docs.microsoft.com/en-us/nuget/reference/nuspec#repository
