### ISSUE TITLE
Document the use of protocolVersion - what does it do?

### ISSUE THREAD

**Issue by joelverhagen** [NuGet/docs.microsoft.com-nuget#704]
What does it do?
Is it required?
How does it effect the protocol layer ?

/cc @clairernovotny

**Comment by joelverhagen** [comment]
@karann-msft, I presume this means "protocolVersion" in the nuget.config sources section. I could document it but I think it's best if this was owned by someone on the client team.

**Comment by karann-msft** [comment]
@joelverhagen - if time permits, it would be awesome if you can start a PR which we can have client folks review.
