### ISSUE TITLE
Document precedence rules for package frameworks

### ISSUE THREAD

**Issue by nkolev92** [NuGet/docs.microsoft.com-nuget#718]
@karann-msft commented on [Tue Aug 23 2016](https://github.com/NuGet/Home/issues/3361)

_From @harikmenon on July 18, 2016 17:4_

We need to explicitly call out our resolution rules and possibly link to joels site.

_Copied from original issue: NuGet/NuGetDocs#495_

---

@kraigb commented on [Thu Apr 13 2017](https://github.com/NuGet/Home/issues/3361#issuecomment-293991222)

What information do you have on this that I can work from?

---

@kraigb commented on [Thu Apr 20 2017](https://github.com/NuGet/Home/issues/3361#issuecomment-295846230)

@joelverhagen Do you have suitable information?

**Comment by nkolev92** [comment]
Any work here is incomplete and confusing without https://github.com/NuGet/NuGetGallery/issues/7828 first.

**Comment by JonDouglas** [comment]
@joelverhagen @dannyjdev @nkolev92 Any preferences on where this should go?

I was thinking under client's "concepts":

![image](https://user-images.githubusercontent.com/1288848/193060011-bb3ab58c-8cc7-40f2-a1bb-a196e81ff6c2.png)

or as a new server "reference" page to explain the new "frameworks" tab further.

![image](https://user-images.githubusercontent.com/1288848/193060180-bfc59e77-40e1-4efa-8aea-c570b26b2ff5.png)

This should be fairly easy to write a small section on with everything we have today.

**Comment by joelverhagen** [comment]
I think Concepts fits better. It's a lot like the Dependency resolution doc. We can certainly have a section on the concepts page to talk about how the general idea overlaps with NuGet.org's impl.

**Comment by nkolev92** [comment]
We need this.
