### ISSUE TITLE
Customer Request: UWP package using C#

### ISSUE THREAD

**Issue by kraigb** [NuGet/docs.microsoft.com-nuget#756]
Rather than just WinRT component.

Verbatim: You need a C# example! I tried generating a C# runtime component and only after I published and downloaded it did I realize I can't access any classes!

**Comment by anangaur** [comment]
Who is UWP expert? For now assigning to @karann-msft. May be we can use UWP team's expertise?

**Comment by karann-msft** [comment]
@dajaco is the expert for UWP :)

**Comment by rrelyea** [comment]
I think the ask here is to make a C# version of this:
https://docs.microsoft.com/en-us/nuget/guides/create-uwp-packages
