### ISSUE TITLE
Symbol Server tooling - the part applicable for 15.7 tooling

### ISSUE THREAD

**Issue by anangaur** [NuGet/docs.microsoft.com-nuget#765]
@CamSoper @kraigb @karann-msft , Can one of you add me as admin so that I can add members here? 

This work is pending on @diverdan92

**Comment by CamSoper** [comment]
I do not have the permissions.  I believe @karann-msft will have to do it.

**Comment by karann-msft** [comment]
@anangaur you are an admin on the repo.
