### ISSUE TITLE
Create walkthrough/sample for package with readme and content files

### ISSUE THREAD

**Issue by kraigb** [NuGet/docs.microsoft.com-nuget#775]
Copied from https://github.com/MicrosoftDocs/mvp-hackadoc-2018/issues/38

https://docs.microsoft.com/en-us/nuget/create-packages/creating-a-package#adding-a-readme-and-other-files only sparsely mentions readmes and hardly mentions content files and how those should be used.

Request is to create a separate article focusing on readme.txt and content files. This would be placed under the create-packages node. Recommend approaching from a basic CLI standpoint using a folder structure to create the .nuspec.

http://blog.nuget.org/20160126/nuget-contentFiles-demystified.html provides something of a basis (it speaks to project.json, which is a dead format; PackageReference supports contentFiles, as shown on https://docs.microsoft.com/en-us/nuget/consume-packages/package-references-in-project-files.

Include dotnet and nuget CLI commands in all examples.

Relevant issues:
#644
#300

Also:
#362
#445
#466

**Comment by kraigb** [comment]
Should also address #805

**Comment by robertmclaws** [comment]
This situation is still super-confusing and nowhere near fixes... ESPECIALLY in reference to how to configure these things if you're building from the new project format.

@terrajobst/@rreleya Any chance we could get some clarification on this? And I know you folks have said in the past that you don't want content files to be added to the project, but there are some legitimate situations (like delivering config files and T4/CSX templates) where this is necessary. It's almost 2019 and making this happen should not be so hard...
