### ISSUE TITLE
Create walkthrough/sample for a package using MSBuild props and targets

### ISSUE THREAD

**Issue by kraigb** [NuGet/docs.microsoft.com-nuget#777]
Copied from https://github.com/MicrosoftDocs/mvp-hackadoc-2018/issues/41

https://docs.microsoft.com/en-us/nuget/create-packages/creating-a-package#including-msbuild-props-and-targets-in-a-package describes this capability and outlines the process, but isn't comprehensive enough.

Request is to create a separate article focusing on this capability with a working example. This would be placed under the create-packages node. Recommend approaching from a basic CLI standpoint using a folder structure to create the .nuspec.

Include dotnet and nuget CLI commands in all examples.

Relevant issues:
#231
#312
#417

**Comment by casz** [comment]
Very frustrating to spend hours figuring out you need "buildMultiTargeting" to support loading targets/props for `TargetFrameworks` 😅

**Comment by Mikejo5000** [comment]
Partially mitigated by the new article on multi-targeting:
https://docs.microsoft.com/en-us/nuget/create-packages/multiple-target-frameworks-project-file

**Comment by Mikejo5000** [comment]
Also, new doc on creating a package with MSBuild (simple working example):
https://docs.microsoft.com/en-us/nuget/create-packages/creating-a-package-msbuild

**Comment by casz** [comment]
@Mikejo5000 I see no reference to `buildMultiTargeting` in the `creating a package msbuild` or `multiple-target-frameworks-project-file`

**Comment by Mikejo5000** [comment]
@casz Right, I included that links as related to this issue. If I can get some good information on buildMultiTargeting, I can plan to update one or more of these docs with that information.

**Comment by Mikejo5000** [comment]
#1508 is also relevant

**Comment by karann-msft** [comment]
Fixed in https://github.com/NuGet/docs.microsoft.com-nuget/pull/1616
