### ISSUE TITLE
Create walkthrough/sample for multi-targeting

### ISSUE THREAD

**Issue by kraigb** [NuGet/docs.microsoft.com-nuget#778]
Copied from https://github.com/MicrosoftDocs/mvp-hackadoc-2018/issues/42

https://docs.microsoft.com/en-us/nuget/create-packages/supporting-multiple-target-frameworks describes the capability, but we lack a good example with a walkthrough. Recommend approaching from a basic CLI standpoint using a folder structure to create the .nuspec.

The article itself can use a thorough review and update (see issues below). Needs to address cases where .NET Standard isn't suitable. Include doing this in VS. Include dotnet and nuget CLI commands in all examples.

Relevant issues:
#239
#622
#625

**Comment by Mikejo5000** [comment]
Mitigated somewhat by the new article on multi-targeting:
https://docs.microsoft.com/en-us/nuget/create-packages/multiple-target-frameworks-project-file

**Comment by Mikejo5000** [comment]
Low priority to document manually creating a .nuspec with the newer tooling. We have new articles on creagting a package with dotnet CLI and for multitargeting.
