### ISSUE TITLE
Create walkthrough/sample for source and config file transformations

### ISSUE THREAD

**Issue by kraigb** [NuGet/docs.microsoft.com-nuget#779]
Copied from https://github.com/MicrosoftDocs/mvp-hackadoc-2018/issues/44

https://docs.microsoft.com/en-us/nuget/create-packages/source-and-config-file-transformations describes the capability, but we lack a good example that also shows the impact on the consuming project. The impact also needs to show what happens in both packages.config and PackageReference cases (according to NuGet/docs.microsoft.com-nuget#516, the statement at the top about PackageReference is wrong, but needs verification).

Request is to update the article with a walkthrough. Recommend approaching from a basic CLI standpoint using a folder structure to create the .nuspec.

Include dotnet and nuget CLI commands in all examples.

Relevant issues:
#237
#516

**Comment by karann-msft** [comment]
Not eligible for docs day.
Note to self - find the dupe and close it.
