### ISSUE TITLE
Create walkthrough/sample for localized packages

### ISSUE THREAD

**Issue by kraigb** [NuGet/docs.microsoft.com-nuget#780]
Copied from https://github.com/MicrosoftDocs/mvp-hackadoc-2018/issues/45

https://docs.microsoft.com/en-us/nuget/create-packages/creating-localized-packages describes the capability, but we lack a good example.

Request is to update the article with a walkthrough. Recommend approaching from a basic CLI standpoint using a folder structure to create the .nuspec. One additional language other than en-us is sufficient.

Include dotnet and nuget CLI commands in all examples.

**Comment by karann-msft** [comment]
Not eligible for docs day.

**Comment by nkolev92** [comment]
Related issues are NuGet/Home#2245, NuGet/Home#9561 and NuGet/Home#5885

**Comment by erdembayar** [comment]
@chgill-MSFT 
Can I assign this one to myself? I never done any localization related stuff on github before, maybe this is can be my first.

**Comment by JonDouglas** [comment]
Go for it @erdembayar!

**Comment by dominoFire** [comment]
Unassign to load balance.
