### ISSUE TITLE
Document the NuGet SDK

### ISSUE THREAD

**Issue by kraigb** [NuGet/docs.microsoft.com-nuget#787]
Transfer from https://github.com/NuGet/Home/issues/4062. 

* [x] Basic operations (list versions, download package, get package metadata, search for package, create package, read package): https://docs.microsoft.com/en-us/nuget/reference/nuget-client-sdk
* [x] Authenticated operations on NuGet.org (push, unlist)
* [x] Authenticated operations on feed with HTTP authentication (push, unlist, ~~restore~~)
* [x] Catalog using NuGet.Protocol.Catalog: https://docs.microsoft.com/en-us/nuget/guides/api/query-for-all-published-packages

**Comment by karann-msft** [comment]
@nkolev92 - are the new ones already documented here - https://docs.microsoft.com/en-us/nuget/reference/nuget-client-sdk ?

**Comment by nkolev92** [comment]
Sort of, it's not really complete.

**Comment by loic-sharma** [comment]
Should we split up this issue into specific areas we'd like to add? Examples:

1. Authenticated operations on NuGet.org (push, unlist)
1. Authenticated operations on feed with HTTP authentication (push, unlist, restore)
1. Catalog using NuGet.Protocol.Catalog

Is there anything else you'd add @nkolev92?

**Comment by nkolev92** [comment]
guess so...we can split into a few issues.
Personally don't really want to document restore specifics, but I see a use-case for push/unlist and authenticated feeds

**Comment by nkolev92** [comment]
I think I'm covering the `authenticated operations on feed with http auth` in https://github.com/NuGet/docs.microsoft.com-nuget/pull/2254. 

It's not *all* the options, but it's the *easiest* one.

**Comment by loic-sharma** [comment]
@nkolev92 Nice! I sent a pull request for nuget.org push/unlist here: https://github.com/NuGet/docs.microsoft.com-nuget/pull/2256

Do you think it'd be worth a sample for client certificate authentication?

**Comment by nkolev92** [comment]
There are no examples for workign with plugins and client certs. 

I think they'd be nice to add, but are less valuable than the basic approach.

I'm not planning on adding them now, because they are significantly more work.
I'm ok with leaving this open or creating a issue tracking those 2 special examples.

**Comment by loic-sharma** [comment]
OK we addressed all of the customer's asks from the original issue. Let's just close this until someone asks for more examples :)
