### ISSUE TITLE
Overhaul MSBuild Pack and Restore targets article

### ISSUE THREAD

**Issue by kraigb** [NuGet/docs.microsoft.com-nuget#789]
https://docs.microsoft.com/en-us/nuget/reference/msbuild-targets

Address comments on the page as well as saved comment (contact @kraigb for these if needed).

Also address https://github.com/NuGet/docs.microsoft.com-nuget/issues/626

**Comment by Mikejo5000** [comment]
Partially mitigated by the new article on multi-targeting:
https://docs.microsoft.com/en-us/nuget/create-packages/multiple-target-frameworks-project-file

**Comment by Mikejo5000** [comment]
Also published a new article on creating a package with MSBuild.
https://docs.microsoft.com/en-us/nuget/create-packages/creating-a-package-msbuild
We can

**Comment by Mikejo5000** [comment]
@karann-msft @nkolev92 Seems to be a missing feature vs. nuget.exe CLI, i.e., "IncludeReferencedProjects". Is that still the case? Is there an equivalent for dotnet CLI?

**Comment by nkolev92** [comment]
There is none. 

It's a really a PackageReference deficiency right now.
