### ISSUE TITLE
Reorient package creation approach to folder structure

### ISSUE THREAD

**Issue by kraigb** [NuGet/docs.microsoft.com-nuget#792]
https://docs.microsoft.com/en-us/nuget/create-packages/creating-a-package needs to be refactored into separate articles alongside the various samples/walkthroughs in other issues.

After the quickstarts, which document how to use features in dotnet and VS to easily create a package, the recommended approach is:

- Create an assembly however you want.
- Create a folder structure for the package
- Create a .nuspec from the folder structure (but maybe use project properties; that is, lead with the folder structure and mention using a project file, rather than relying on project files first).
- Create and publish the package.

Include dotnet and nuget CLI commands in all examples.

Some customer verbatims to address:

- Too vague. Just give a simple Hello World example of the minimum needed to create a nuget package! (This is mostly handled by quickstarts now, but still need the simplest version using a folder structure.)
- Completely out of date. An entirely different folder structure is present in https://docs.microsoft.com/en-us/nuget/consume-packages/package-references-in-project-files

**Comment by kraigb** [comment]
Note to whomever picks this up: I started work on this issue in the branch kraigb-create, but did not finish it. That work gives an idea of the direction I was going. Feel free to reach out with questions.

**Comment by Mikejo5000** [comment]
It would be good if we could use tabbed conceptual to keep this all in one topic, but the feature is deprecated, and no new tabs are allowed (e.g., nuget.exe CLI). However, we have two new articles on this subject that can be expanded if need be.
https://docs.microsoft.com/en-us/nuget/create-packages/creating-a-package-dotnet-cli
https://docs.microsoft.com/en-us/nuget/create-packages/creating-a-package-msbuild
