### ISSUE TITLE
Add examples to .nuSpec reference

### ISSUE THREAD

**Issue by kraigb** [NuGet/docs.microsoft.com-nuget#793]
Customer comment:

- Nuspec ref: As ALWAYS, there are too many fragmented examples outside the context in which they are required, and the current questions on contentFiles illustrate this. I intended to find a 'hard' definition of nuspec schema, not a millennial's collegiate writeup. A little proofreading wouldn't hurt, either. Using the correct UI elements for examples is advisable ("Content files with directory structure" absolutely does NOT require a source code type UI element, WHY do this?)

Content file material is covered under #775

**Comment by CamSoper** [comment]
Rolled up to #775
