### ISSUE TITLE
nuspec documentation not clear enough

### ISSUE THREAD

**Issue by paulomorgado** [NuGet/docs.microsoft.com-nuget#805]
It is not clear (to me, at least) from [the nuspec documentation](https://github.com/NuGet/docs.microsoft.com-nuget/blob/master/docs/reference/nuspec.md)

- the place of `<contentFiles>` - I had to read the XSD to know where
- what is the content of the package for each example

**Comment by CamSoper** [comment]
Rolled up to #775
