### ISSUE TITLE
Is there a way to get download count information by nuget client name and version?

### ISSUE THREAD

**Issue by rianjs** [NuGet/docs.microsoft.com-nuget#809]
All packages have a detailed statistics page. ([Example](https://www.nuget.org/stats/packages/Ical.Net?groupby=Version&groupby=ClientName&groupby=ClientVersion))

There you can see a breakdown of package version download counts by nuget client name and version.

The data from that page comes from somewhere. Is it publicly accessible by the nuget API? If so, it's not documented.

**Comment by kraigb** [comment]
@joelverhagen I'm guessing that the Package Metadata API, https://docs.microsoft.com/en-us/nuget/api/registration-base-url-resource, is the way to go here. Can you confirm? If not, can you answer @rianjs's question?

**Comment by joelverhagen** [comment]
Hey @rianjs, this information is not currently part of our official API. The only download count information available in our API is per ID and per version, as seen in the [response from our search service](https://docs.microsoft.com/en-us/nuget/api/search-query-service-resource#search-result).

This ask is tracked here: https://github.com/NuGet/NuGetGallery/issues/2810.

Please feel free to add your voice to that discussion and tell us about what your scenario is. If there is significant support from the community, it will help our team prioritize this task.
