### ISSUE TITLE
What am I missing still: Stuck at missing NuGet package from Visual Studio 2017

### ISSUE THREAD

**Issue by alecela** [NuGet/docs.microsoft.com-nuget#818]
Trying to build a piece of sample code within VS 2017 and I got the error message of:  
Error
This project references NuGet package(s) that are missing on this computer. Use NuGet Package Restore to download them.  For more information, see http://go.microsoft.com/fwlink/?LinkID=322105. The missing file is ..\packages\Microsoft.Bcl.Build.1.0.21\build\Microsoft.Bcl.Build.targets.

BUT when I look into the folder of:

..\packages\Microsoft.Bcl.Build.1.0.21\build

I do see the file: Microsoft.Bcl.Build.targets.

Both package restore options within package manager settings are ticked/enabled.

Thanks in advance for any pointer/suggestion.

**Comment by SergioMouraFe** [comment]
I got the same problem, but with the package ..\packages\Microsoft.Net.Compilers.2.1.0\build\Microsoft.Net.Compilers.props.

???

**Comment by Advanium** [comment]
I could reproduce this by manually moving the project folder around. As the .csproj file contains the relative location to the referenced packages, those locations have to be updated manually.

In my project structure, I move projects into a src or tests folder. By introducing the additional hierarchy level, I needed to update the .csproj files accordingly. So every `..\packages` reference would become `..\..\packages`. Easy to do with find & replace.

I believe restoring / reinstalling packages doesn't properly account the folder hierarchy.

**Comment by zivkan** [comment]
@alecela I know this issue is months old, but is this still an issue for you?  Advanium's comment sounds very plausible. Installing packages in a project that uses packages.config modifies the csproj to reference the dlls in the packages folder. If you move projects around so that the relative path is different, you will need to re-install the packages so that the csproj is fixed up. It's one of the reasons we prefer PackageReference over packages.config.

**Comment by Mikejo5000** [comment]
The issue of how to handle project files when moved around is discussed here, which mentions the same error:
https://docs.microsoft.com/en-us/nuget/consume-packages/package-restore-troubleshooting#this-project-references-nuget-packages-that-are-missing-on-this-computer

**Comment by BitcoinCode** [comment]
> \packages

Yes, this is the correct solution in my case I have moved the project to another folder so the ..\packages should be just packages 
 <Import Project="..\packages\ will become  <Import Project="packages\
