### ISSUE TITLE
Have documentation + samples for PackageReference workarounds

### ISSUE THREAD

**Issue by anangaur** [NuGet/docs.microsoft.com-nuget#819]
We have been talking to customers about the workarounds for the following limitations with PackageReference. We should have it documented along with samples.

* Web.config transforms
* Copying contents files to project
* ...

**Comment by karann-msft** [comment]
Not eligible for docs day.

**Comment by anangaur** [comment]
@nkolev92 , arent there already some samples? Can you link them here?

**Comment by nkolev92** [comment]
There's docs for https://github.com/NuGet/docs.microsoft.com-nuget/blob/master/docs/create-packages/Source-and-Config-File-Transformations.md#xdt-transforms

The content files part is a harder to get right and we have no sample that I could find at this point.

**Comment by JonDouglas** [comment]
Much of this issue seems to be addressed with previous migration docs. Let's close this for now and open new issues if there's not sufficient docs here.
