### ISSUE TITLE
nice job , still there i s room for improvement.

### ISSUE THREAD

**Issue by Farzad-Jalali** [NuGet/docs.microsoft.com-nuget#839]
Could you please provide more example for the "Restore packages for the solution in the current folder, specifying package sources".
specifically when I need to restore a specific version of a specific NuGet package from a private feed.
* obviously  I got enough example for first 3 options, so I just ask for the fourth.
thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d63170c3-1894-8ead-b557-9937dae88172
* Version Independent ID: 67968c11-0aa0-f835-357d-8690911eb011
* Content: [NuGet CLI restore command](https://docs.microsoft.com/en-us/nuget/tools/cli-ref-restore)
* Content Source: [docs/tools/cli-ref-restore.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/master/docs/tools/cli-ref-restore.md)
* Service: **unspecified**
* GitHub Login: @kraigb
* Microsoft Alias: **kraigb**

**Comment by anangaur** [comment]
The current set of examples seem sufficient. You can use the `-PackagesDirectory` option, as specified in one of the examples, for restoring packages for a solution too. Let us know if that doesn't work for you. Closing this issue for now.
