### ISSUE TITLE
FAQ Re: V2 API Support

### ISSUE THREAD

**Issue by airzym** [NuGet/docs.microsoft.com-nuget#844]
The [FAQ document](https://github.com/NuGet/docs.microsoft.com-nuget/blob/master/docs/policies/NuGet-FAQ.md) notes at the end `that the V2 API is deprecated and does not work with NuGet 4+.`

Yet I have read in a number of places that V2 support is not going anywhere, and the fact I am running NuGet 4+ and my V2 feeds work fine.

Does this note need to be removed?

**Comment by kraigb** [comment]
@anangaur can you answer this one?

**Comment by Mikejo5000** [comment]
Looks like note was previously removed.
There is this information now:
https://docs.microsoft.com/en-us/nuget/nuget-org/overview-nuget-org#api-endpoint-for-nugetorg
