### ISSUE TITLE
The note in dependency ranges and their resolution is not fully correct

### ISSUE THREAD

**Issue by nkolev92** [NuGet/docs.microsoft.com-nuget#845]
The note in https://docs.microsoft.com/en-us/nuget/reference/package-versioning#version-ranges-and-wildcards is not fully correct, because ranges in PR do contain prerelease versions. 
See https://github.com/NuGet/Home/issues/6434#issuecomment-358782297

This required a clarification from the engineering side to clarify the experience, but we definitely need to correct this to align it to the current behavior. 

/cc @rrelyea 
This is a docs issue, but we need a client investment to make sure no scenarios are missed.

**Comment by Mikejo5000** [comment]
@nkolev92 Sounds like a simple fix to the note to say that the note applies to packages.config, not PackageReference. Is that right?

**Comment by nkolev92** [comment]
It's kind of convoluted. 
I think the doc is talking about resolution based on a PackageReference declared version range rather thna dependency version ranges in the nuspec.

The correct thing is: 
Version ranges in PackageREfeqrence will include prerelease versions. 
Floating versions will by design not resolve prerelease versions unless opted into.

I think that's what the note is trying to communicate, and link to the feature ask at hand.
