### ISSUE TITLE
Using the cmdlet outside of Visual Studio

### ISSUE THREAD

**Issue by fleed** [NuGet/docs.microsoft.com-nuget#847]
Is there a way to use this command outside of Visual Studio?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9477f383-5e28-7739-6562-fb3234b6b0ec
* Version Independent ID: f9af74cb-e3a8-d5e0-75d1-7c7199e76d36
* Content: [NuGet Get-Package PowerShell Reference](https://docs.microsoft.com/en-us/nuget/tools/ps-ref-get-package)
* Content Source: [docs/tools/ps-ref-get-package.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/master/docs/tools/ps-ref-get-package.md)
* Service: **unspecified**
* GitHub Login: @kraigb
* Microsoft Alias: **kraigb**

**Comment by kraigb** [comment]
No, it applies to only the NuGet Package Manager Console. There is, however, a generic PowerShell Get-Package, https://docs.microsoft.com/en-us/powershell/module/packagemanagement/get-package?view=powershell-6, but I don't know whether it can work with a source like nuget.org.

If there's a scenario you need, file an issue with the NuGet client team on https://github.com/NuGet/Home/issues.
