### ISSUE TITLE
Not enough info on architecture specific native assemblies

### ISSUE THREAD

**Issue by HarelM** [NuGet/docs.microsoft.com-nuget#850]
I'm trying to create a cross platform NuGet package - I have create the needed assemblies for windows and linux, placed them in the described folder structure and published it to NuGet.
When I use this package the native assemblies do not get copied to output debug folder but they do appear when I publish the package - this is very strange and I don't know how to properly solve this...
Clearer documentation on how to build such packages and how to use them would have saved me a lot of time.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f1482e18-5f1f-3a8a-3321-66af52879ec5
* Version Independent ID: d70bd2f5-c04b-9207-62a0-4ecb6e8e5ca6
* Content: [Multi-targeting for NuGet Packages](https://docs.microsoft.com/en-us/nuget/create-packages/supporting-multiple-target-frameworks)
* Content Source: [docs/create-packages/Supporting-Multiple-Target-Frameworks.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/master/docs/create-packages/Supporting-Multiple-Target-Frameworks.md)
* Service: **unspecified**
* GitHub Login: @kraigb
* Microsoft Alias: **kraigb**

**Comment by jormundgand** [comment]
I've spent two days reading the documentation and asked a question on stack to figure out how to do this too.

**Comment by HarelM** [comment]
@jormundgand do you have any insights you can share? I'm baffled by how this works.
I want to create a NuGet package to pack assemblies from linux and windows for a dotnet core project and have the assemblies copied to the right location, both in that project and another project that uses this one.
Here's the project I'm working on, the NuGet package spec is defined in the csproj:
https://github.com/IsraelHikingMap/GPSBabelWebAPI/tree/master/IsraelHiking.GPSBabel

**Comment by jormundgand** [comment]
Sadly no. I'm still looking for a solution. I'll let you know if I find a solution.

**Comment by ransagy** [comment]
I just tore my hair out for a few hours as well. This is truly aggravating.

**Comment by biohazard999** [comment]
I have the same problem, currently the only solution i can see, is adding a custom targets file to copy them in debug mode to the output directory myself. But there must be a hidden thing, why this is only done on publish

**Comment by zivkan** [comment]
might be related #1013

**Comment by HarelM** [comment]
@zivkan, yes, seems like the same issue. Only this issue was opened in May and the other in August.
Could've saved a lot of time for a lot of developers if you have solved this issue when I opened it...

**Comment by zivkan** [comment]
Unfortunately resources for maintaining docs have shifted, but I'm starting to work on it in my spare time. The link to the other issue is largely for my own benefit, so when I (or anyone else who would like to contribute) want to write docs to resolve this issue, I have a starting point. I know nothing about RIDs and selecting different dlls based on architecture or operating system, and that issue will help me ramp up more quickly. For now I'm just assining/triaging doc issues to work on later.

**Comment by Mizux** [comment]
does https://github.com/Mizux/dotnet-native may help you ?

**Comment by HarelM** [comment]
@Mizux Thanks! So the content of the readme of this repository is basically the way to create a cross platform nuget package, right? Looks very promising.
Since I wrote this (more than a year ago) I moved forward in order to create a cross-platform docker containers instead of a nuget package - this way I can compile the relevant code in every platform and use a docker build step, entry point etc. Docker's documentation on cross platform containers is much better...

**Comment by KinsonDigital** [comment]
I myself am running into these issues.  I think that the issue should be reopened and worked on as well.  There is not much documentation on this.  I can add the native assemblies easily but when it comes to the C# library assembly being added to the nuget package itself in different architectures and being consumed properly by the consumer, this is where I am failing. Here is an issue that I opened about all of this.  https://github.com/NuGet/Home/issues/9272
