### ISSUE TITLE
Location of project.assets.json

### ISSUE THREAD

**Issue by rustamm** [NuGet/docs.microsoft.com-nuget#852]
The documentation states that project.assets.json file is stored in obj folder of the project. How can I change the path in case I want to separate my code folders from artifacts created by build process?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 68d87097-68a1-cdd2-edfc-93fd2366fd0a
* Version Independent ID: b7d27caf-5476-2315-f4dc-e413b1be0726
* Content: [NuGet Package Dependency Resolution](https://docs.microsoft.com/en-us/nuget/consume-packages/dependency-resolution#feedback)
* Content Source: [docs/consume-packages/Dependency-Resolution.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/master/docs/consume-packages/Dependency-Resolution.md)
* Service: **unspecified**
* GitHub Login: @kraigb
* Microsoft Alias: **kraigb**

**Comment by chris1248** [comment]
Agree. These files are polluting my source repo, and I don't want to add another entry to my .gitignore file.

**Comment by rrelyea** [comment]
@nkolev92 - can you reply with answer? And then we should add to docs.

**Comment by nkolev92** [comment]
The way to overwrite this is to use the `MSBuildProjectExtensionsPath` as described in https://docs.microsoft.com/en-us/visualstudio/msbuild/common-msbuild-project-properties?view=vs-2017#list-of-common-properties-and-parameters
