### ISSUE TITLE
Token replacement not working

### ISSUE THREAD

**Issue by Jotune** [NuGet/docs.microsoft.com-nuget#858]
The example will not use token replacement, to do so, make sure your are trying to nuget pack the csproj file, not the nuspec file. Here is the complete nuget cmd :

nuget pack myproject.csproj -IncludeReferencedProjects -Prop Configuration=Release

---
#### Détails du document

⚠ *Ne pas modifier cette section. C’est obligatoire pour docs.microsoft.com ➟ Liaison des problèmes GitHub.*

* ID: e8beb111-7b49-2fbe-eeb5-e485b6515ef2
* Version Independent ID: 22535840-0a27-797e-ebc8-5dbe447156d2
* Content: [Introductory Guide to Creating and Publishing a .NET Framework NuGet Package using Visual Studio](https://docs.microsoft.com/fr-fr/nuget/quickstart/create-and-publish-a-package-using-visual-studio-net-framework)
* Content Source: [docs/quickstart/create-and-publish-a-package-using-visual-studio-net-framework.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/master/docs/quickstart/create-and-publish-a-package-using-visual-studio-net-framework.md)
* Service: **unspecified**
* GitHub Login: @kraigb
* Microsoft Alias: **kraigb**

**Comment by lucasgl** [comment]
this works even without the nuspec file, looks like the newest version is not looking into the nuspec at all, because is not taking the additional metadata from the nuspec file, like the urls and tags.

**Comment by lucasgl** [comment]
related issue: [https://github.com/NuGet/docs.microsoft.com-nuget/issues/899](url)

**Comment by Mikejo5000** [comment]
As mentioned, this guide should work with the example shown. For more advanced package creation using nuget.exe pack, see this article:
https://docs.microsoft.com/en-us/nuget/create-packages/creating-a-package
