### ISSUE TITLE
An example of a netstandard2.0 proj file (with working pack targets) would be very useful. 

### ISSUE THREAD

**Issue by StingyJack** [NuGet/docs.microsoft.com-nuget#859]
Trying to port a 3 class netfx library to a (netstandard20;netfx452) shouldn't be a two day affair at guessing why msbuild cant find the assets.json file (need to call dotnet restore - but no netcore here), or why cant nuget.exe figure out that the output folder is not " 'bin\release\My.Project\bin\release\'. "  Trying to add a /t:Pack to the msbuild task just gets a "The target "Pack" does not exist in the project". 

It should not be this painful to get what should be a simple thing working, but a minimal working example would probably go a long way toward reducing it.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 18071970-cf13-78af-ac1d-9adefefdb693
* Version Independent ID: 3bf15a5c-8b3e-0e69-0bf6-03b44654970c
* Content: [Introductory Guide to Creating and Publishing a .NET Standard NuGet Package using Visual Studio](https://docs.microsoft.com/en-us/nuget/quickstart/create-and-publish-a-package-using-visual-studio#lf-content=228595307:781068938)
* Content Source: [docs/quickstart/create-and-publish-a-package-using-visual-studio.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/master/docs/quickstart/create-and-publish-a-package-using-visual-studio.md)
* Service: **nuget**
* GitHub Login: @kraigb
* Microsoft Alias: **kraigb**

**Comment by rumen-yankov** [comment]
Bump..
I also  lost few hours reading and trying with no success so far.

**Comment by zivkan** [comment]
We certainly need to improve the docs, but for anyone following this issue, here's my quick tutorial:

1. Create new .NET Standard class library either in Visual Studio or use `dotnet new classlib`
2. Edit the csproj, changing `<TargetFramework>netstandard2.0</TargetFramework>` to `<TargetFrameworks>netstandard2.0;net45</TargetFrameworks>`. Note that the XML element changed from singular to plural. Make sure you add the "s" to both the open and close tags.
3. If you have any code that only works in one TFM, you can use `#if NET45` or `#if NETSTANDARD20` to separate TFM dependent code. For example:
```
public string Platform {
  get {
#if NET45
  return ".NET Framework"
#elif NETSTANDARD2_0
  return ".NET Standard"
#else
#error This code block does not match csproj TargetFrameworks list
#endif
  }
}
```
4. Add any NuGet metadata you want to the csproj as MSBuild properties. [Here are the docs listing the available metadata and the MSBuild property names](https://docs.microsoft.com/nuget/reference/msbuild-targets#pack-target).
5. Now you can `dotnet pack` and the resulting nupkg will be multitargetting .NET Standard 2.0 and .NET Framework 4.5

For reference, here's the full csproj that is generated when I did the above steps using .NET Core SDK 2.2

```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>netstandard2.0;net45</TargetFrameworks>
    <Description>Sample project that targets multiple TFMs</Description>
  </PropertyGroup>

</Project>
````

I don't believe that nuget.exe supports packing SDK projects, so you should only use `dotnet pack` or `msbuild /t:pack`. I beleive there are also issues if you try to use a .nuspec file for NuGet metadata, so only use MSBuild properties. If you want to separate build related properties from NuGet metadata, you can use whitespace or a different PropertyGroup, or put the NuGet properties in another file and use [MSBuild's Import directive](https://docs.microsoft.com/visualstudio/msbuild/import-element-msbuild?view=vs-2017) to include it.

**Comment by StingyJack** [comment]
> I beleive there are also issues if you try to use a .nuspec file for NuGet metadata.

@zivkan - Any specific issues or search terms you can remember or share?

**Comment by StingyJack** [comment]
@zivkan - I understand your advice about using dotnet.exe is practical, but it does conflict with the first sentence of [How to create a package](https://docs.microsoft.com/en-us/nuget/create-packages/creating-a-package).  Its already a pain to have to add a step in every build def to call `dotnet restore` before `msbuild`ing the solution because nuget.exe cant restore SDK style projects correctly.  

Being able to use a nuspec file for either csproj style is going to be really important. There is not enough control and flexibility when using the MSBuild properties. https://github.com/NuGet/Home/issues/7371, including specific additional files needed for an included dependency's licensing, and a few others.

**Comment by zivkan** [comment]
Most of NuGet's docs were written before SDK projects or MSBuild-integrated NuGet targets existed, so the docs make more sense knowing that, not that it's a good reason. Also, Microsoft has a dedicated docs team, and they used to work on NuGet's docs, but they no longer do, so now the Engineering team has to prioritise docs work with all the other deliverables. Maybe this just sounds like excuses, but it's my understanding of the truth. I think all of the new features that were implemented since I joined the team had new docs written, so that's something, but maintaining/updating the existing docs is a real issue.

**Comment by karann-msft** [comment]
@stingyjack, basically you want a sample of Andy's first response, right?

```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>netstandard2.0;net45</TargetFrameworks>
    <Description>Sample project that targets multiple TFMs</Description>
  </PropertyGroup>

</Project>
```

**Comment by Mikejo5000** [comment]
Example published:
https://docs.microsoft.com/en-us/nuget/create-packages/multiple-target-frameworks-project-file
