### ISSUE TITLE
ASP.NET PackageReference Migration

### ISSUE THREAD

**Issue by AdamCaviness** [NuGet/docs.microsoft.com-nuget#860]
I have the newly minted VS 15.7 and you did a fine job on the built-in migration tool. It worked great for class libraries and desktop projects. I'm looking forward to migrating ASP.NET projects ASAP. Thanks! 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 75e25f56-15c8-79d7-5e55-d145b7c1159c
* Version Independent ID: 06388a58-df68-9438-92d7-17359196f5c8
* Content: [Migrating from package.config to PackageReference formats](https://docs.microsoft.com/en-us/nuget/reference/migrate-packages-config-to-package-reference)
* Content Source: [docs/reference/migrate-packages-config-to-package-reference.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/master/docs/reference/migrate-packages-config-to-package-reference.md)
* Service: **nuget**
* GitHub Login: @karann-msft
* Microsoft Alias: **karann**

**Comment by sgwatgit** [comment]
@AdamCaviness `PackageReference` should work fine in traditional full framework ASP.NET projects. I've converted many Web Forms apps from `packages.config` to `PackageReference`.

What currently is not supported is converting full framework ASP.NET apps to the new VS2017 project system (an SDK project). See more here https://github.com/dotnet/project-system/issues/2670.

I have a lot of class library projects running on .NET 4.6.1 using the SDK .csproj format working nicely with my .NET 4.7.1 ASP.NET Web Forms projects using `PackageReference`.

I did these migrations before the tooling was available in VS using this VS extension https://marketplace.visualstudio.com/items?itemName=CloudNimble.NuGetPackageReferenceUpgrader.

**Comment by AdamCaviness** [comment]
@sgwatgit Thanks, you explain that pretty nicely. I wrote the feedback having already converted with the VS extension you mention. It did a pretty good job (the attribute syntax is different than the element syntax that the VS migration tool uses but no-big-deal). I backed out of the extension-based conversion because the VS 15.7 PackageReference integration gives such a nice experience with both the auto-removal of nuget packages and UI hints via References in SolutionExplorer. Because I'm new to ProjectReference, I backed out of that PackageReference conversion not knowing how soon the VS ASP.NET PackageReference migration may get baked in. I think after your suggestion I'll revisit it and commit to using the extension and just ignore the VS sugar. Thanks again.

**Comment by jemiller0** [comment]
When will migration to PackageReference in Visual Studio 2017 officially be supported? It is a major oversight and a major hassle having to deal with packages.config's DLL hell. Or at least provide instructions on how to do so manually. One should not have to rely on a third party extension to do this. The last time I created new .NET Framework library and console application projects which was just a few days ago, it was still not using PackageReference by default. I would like to see more attention paid to the full .NET Framework. Not everyone is using .NET Core. packages.config is a total pain. Especially when you are using packages like EF Core which pull in a ton of dependencies.

**Comment by cremor** [comment]
@jemiller0 Visual Studio 2017 15.7 does offer official support for migration to PackageReference. You don't need an extension for that. See the documentation linked in the initial comment of this issue.

You can also configure Visual Studio to use PackageReference by default for new projects. Just change the setting in Tools - Options - NuGet Package Manager.

**Comment by jemiller0** [comment]
I somehow left out that what I was talking about is support for PackageReference in ASP.NET/.NET Framework projects. I already have it working for my other projects. Thanks for the info about being able to set the default.

**Comment by NicolasDorier** [comment]
The way I migrated my ASP.NET project to PackageReference is by making VS think it is a project library.

* Open the csproj
* Replace the ProjectGuid by `<ProjectGuid>{7C796B6B-86B5-4C57-ADAA-12CF1FECDA71}</ProjectGuid>` and remove `ProjectTypeGuids`
* Now right click on reference, you should be able to migrate
* Put back the previous `ProjectType` and `ProjectTypeGuids`

Enjoy!

**Comment by Thieum** [comment]
@NicolasDorier - the problem with this, is that some packages won't play well on reinstall, aren't they ?


Microsoft.CodeAnalysis.Analyzers v1.1.0
install.ps1 script will be ignored when the package is installed after the migration.

Microsoft.CodeDom.Providers.DotNetCompilerPlatform v1.0.8
install.ps1 script will be ignored when the package is installed after the migration.
'content' assets will not be available when the package is installed after the migration.
XDT transform file 'content\net45\web.config.install.xdt' will not be applied when the package is installed after the migration.
XDT transform file 'content\net45\web.config.uninstall.xdt' will not be applied when the package is installed after the migration.
XDT transform file 'content\net46\web.config.install.xdt' will not be applied when the package is installed after the migration.
XDT transform file 'content\net46\web.config.uninstall.xdt' will not be applied when the package is installed after the migration.

Newtonsoft.Json v9.0.1
install.ps1 script will be ignored when the package is installed after the migration.

**Comment by Thieum** [comment]
Latest version seems to pop warnings still:
Microsoft.CodeAnalysis.Analyzers v2.6.1
install.ps1 script will be ignored when the package is installed after the migration.

Microsoft.CodeDom.Providers.DotNetCompilerPlatform v2.0.0
install.ps1 script will be ignored when the package is installed after the migration.
'content' assets will not be available when the package is installed after the migration.
XDT transform file 'content\net45\app.config.install.xdt' will not be applied when the package is installed after the migration.
XDT transform file 'content\net45\app.config.uninstall.xdt' will not be applied when the package is installed after the migration.
XDT transform file 'content\net45\web.config.install.xdt' will not be applied when the package is installed after the migration.
XDT transform file 'content\net45\web.config.uninstall.xdt' will not be applied when the package is installed after the migration.
XDT transform file 'content\net46\app.config.install.xdt' will not be applied when the package is installed after the migration.
XDT transform file 'content\net46\app.config.uninstall.xdt' will not be applied when the package is installed after the migration.
XDT transform file 'content\net46\web.config.install.xdt' will not be applied when the package is installed after the migration.
XDT transform file 'content\net46\web.config.uninstall.xdt' will not be applied when the package is installed after the migration.

**Comment by NicolasDorier** [comment]
@Thieum yes, but these are the limitation of the PackageReference system. You can see more info [here](https://github.com/NuGet/docs.microsoft.com-nuget/blob/master/docs/reference/migrate-packages-config-to-package-reference.md#package-compatibility-issues).

**Comment by jemiller0** [comment]
I really wish Microsoft would get this fixed. Not all of us are using .NET Core, or are going to be anytime soon. I'm tired of .NET Framework users being treated as second-class citizens. packages.config is total pain. IMHO, Microsoft should put more resources to solving this. Meanwhile, they are off working on any number of less important features. That's fine, but, fundamental issues like this should be focused on first.

**Comment by NicolasDorier** [comment]
Problem is that .NET Framework feel the weight of years of backward compatibility.
.NET Framework has the reputable, of being rock solid on time. I am quite sure a project I developed on .NET 2.0 would have no problem to get migrated (maybe even compile fine!) on Visual Studio 2017.

This is an important achievement for businesses whose software will run for decades when the former developers left the company. This is impressive achievement if you ask me.

.NET Core has none of these issue.
That said, I wish I will never have to touch .NET Framework again, long life to .NET Core!

**Comment by jemiller0** [comment]
Any word on when this will be officially supported? I see that VS 15.8 is out and I see no mention of it. It seems like Microsoft is adding all kinds of other whizbang features and ignoring fundamentals like this. packages.config is a total pain. Please fix this.

**Comment by karann-msft** [comment]
All of this is good feedback. Please use this issue https://github.com/NuGet/Home/issues/5877 for product feedback.

**Comment by spottedmahn** [comment]
>I did these migrations before the tooling was available in VS using this [VS extension](https://marketplace.visualstudio.com/items?itemName=CloudNimble.NuGetPackageReferenceUpgrader)

This tool worked for me w/ an ASP.NET Webforms project, had to go back to VS 2017 to do it but it worked!  Thanks @seangwright 🤝

**Comment by rrelyea** [comment]
Linking to the official devcommunity feedback item requesting support from the ASP.NET Team for PackageReference:
https://developercommunity.visualstudio.com/content/problem/246759/migrate-packagesconfig-to-packagereference-not-ava.html

**Comment by jeeshenlee** [comment]
I've tried to migrate my ASP.NET project (API, swagger, .net framework 4.8) based on NicolasDorier's guides, it does not work for me.

Looking forward to seeing the option to migrate to PackageReference for ASP.NET projects.

**Comment by spottedmahn** [comment]
>Looking forward to seeing the option to migrate to PackageReference for ASP.NET projects

I don't think that is going to happen as the [official request is closed - low priority](https://developercommunity.visualstudio.com/t/migrate-packagesconfig-to-packagereference-not-ava/246759) but hey, squeaky wheel gets the grease 😉

**Comment by softwarekamal** [comment]
I have a way to Hacking ASP.NET to force PackageReference instead of Packages.config
As we know ASP.NET [doesn't support migrating](https://docs.microsoft.com/en-us/nuget/consume-packages/migrate-packages-config-to-package-reference#limitations) packages.config to PackageReference by default.

**I found strange thing. I try following with ASP.NET.**
1. Go to Visual Studio Tools -> Options -> Default Package Management Format to PackageReference. [See Image](https://i.stack.imgur.com/QZC5Z.png)

2. I create empty ASP.NET (.NET Framework) project.

3. I use following [command](https://stackoverflow.com/questions/28596666/how-do-i-uninstall-all-nuget-packages-from-a-solution-in-visual-studio) on package manager console

`Get-Package | Uninstall-Package -RemoveDependencies -Force`

4. Packages.config are gone automatically!

5. Now installing any Nuget Package with GUI. Its installed automatically as PackageReference inside *.csproj.

6. Try yourself...

**Back to question?**

1. Is this a bug?
2. Or is this a hack way to force migrating to PackageReference for ASP.NET?
3. If it worked? what drawback/issues I maybe got If I do that?

_I use Visual Studio 2022, .NET 4.8, Old non-sdk/classic csproj_

**Comment by quetzalcoatl** [comment]
@softwarekamal
It doesn't seem like a bug, nor feature. To me, it seems to be just the way the PM UI works. If there is package.json, it uses it. If there's not, it falls back to PackageReference as you ordered it to do. And then, if last nuget reference is removed from package.config, the file is deleted, as it's empty and has no value. All are just side effects of normal operation.

This will NOT however mean that '<PackageReference> works properly for ASP.NET projects'. See what [Thieum said in two comments on 6 Aug 2018](https://github.com/NuGet/docs.microsoft.com-nuget/issues/860#issuecomment-410741982) in this thread. (*) Scripts, transforms, etc, will not be executed when installing nugets having them. The thing you did was to uninstall all default nugets from that brand-new ASP.NET project, so package.config disappeared. Also, after that, the project is broken, missing core libraries. If you try installing them back with PackageReference enforced, some of those re-installed libraries may simply not fully/properly install, and you may even not notice that, as the PM UI will download them, add PkgRefs to csproj file, and so on, but the extra post-install side-effects won't run, and the best info you get is some lousy warning in package manager log output panel.

(*) you may also want to [read this](https://developercommunity.visualstudio.com/t/migrate-packagesconfig-to-packagereference-not-ava/246759#T-N824729)

I really HOPE that I'm wrong, and that after all these years, the problem of old ASP.NET projects and nugets has some solution other than sticking-to-packages.config-and-not-using-PackageReferences !
