### ISSUE TITLE
Using environment variables on Linux

### ISSUE THREAD

**Issue by VasiliyNovikov** [NuGet/docs.microsoft.com-nuget#862]
There is a mistake in the following paragraph:
  

> Similarly, if HOME on Mac/Linux is set to /home/myStuff, then $HOME/NuGetRepository in the configuration file resolves to /home/myStuff/NuGetRepository.

Syntax on Linux should be the same as on Windows: `%HOME%/NuGetRepository`.
I tested it on my Linux box and found the corresponding code in the sources:
https://github.com/NuGet/NuGet.Client/blob/dev/src/NuGet.Core/NuGet.Configuration/Settings/Settings.cs#L494
https://github.com/dotnet/corefx/blob/5cbac95f5530695a31a43e7748a4561e3a2dd32d/src/System.Runtime.Extensions/src/System/Environment.Unix.cs#L36

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0ea1390e-db36-6759-3095-ebab9d546fdb
* Version Independent ID: ca88d8c6-0515-a267-aac3-a508c54157ab
* Content: [nuget.config File Reference](https://docs.microsoft.com/en-us/nuget/reference/nuget-config-file#feedback)
* Content Source: [docs/reference/nuget-config-file.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/master/docs/reference/nuget-config-file.md)
* Service: **nuget**
* GitHub Login: @kraigb
* Microsoft Alias: **kraigb**

**Comment by kraigb** [comment]
Ah, that looks like a simple typo. Thanks for pointing it out.

**Comment by travispaul** [comment]
The example file on that page also suggest that `$` is used on Mac/Linux and `%` on Windows:
```
        <!--
            Used to specify the default location to expand packages.
            See: nuget.exe help install
            See: nuget.exe help update

            In this example, %PACKAGEHOME% is an environment variable. On Mac/Linux,
            use $PACKAGE_HOME/External as the value.
        -->
```
Also, can an environment variable be replaced anywhere in the file or only in the `<config>` section?
