### ISSUE TITLE
Guidance for packages with compatibility issues

### ISSUE THREAD

**Issue by dmarlow** [NuGet/docs.microsoft.com-nuget#863]
The section mentions that there could be problems with certain package and what those issues could be, but doesn't talk about what to do about it. Should we manually inspect packages and apply those change manually or should we not migrate since it'll break things in unexpected ways?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 75e25f56-15c8-79d7-5e55-d145b7c1159c
* Version Independent ID: 06388a58-df68-9438-92d7-17359196f5c8
* Content: [Migrating from package.config to PackageReference formats](https://docs.microsoft.com/en-us/nuget/reference/migrate-packages-config-to-package-reference#package-compatibility-issues)
* Content Source: [docs/reference/migrate-packages-config-to-package-reference.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/master/docs/reference/migrate-packages-config-to-package-reference.md)
* Service: **nuget**
* GitHub Login: @karann-msft
* Microsoft Alias: **karann**

**Comment by rohit21agrawal** [comment]
hi dmarlow,

right now, what I can suggest is to manually inspect these packages, especially for cases like install.ps1. You can even run these scripts manually. Similarly, for packages with a "content" folder, you can copy the files from these folder manually into project directory and add it as content in your project file.

However, I would also suggest you to reach out to package author and request him/her to fix their package to make it compatible for PackageReference.
