### ISSUE TITLE
Migrate packages.config to PackageReference option not available 15.7.1 or 15.8 Preview 1

### ISSUE THREAD

**Issue by JohnGalt1717** [NuGet/docs.microsoft.com-nuget#867]
Right clicking on References or packages.config does not present the option to migrate on any project. What am I doing wrong?

**Comment by eduardocp** [comment]
I'm also having the same problem in version 15.7.3

**Comment by jainaashish** [comment]
There is one known issue where sometimes you need to first initialized NuGet before this option can be seen. So please either open NuGet manager UI or PMC console then right click on packages.config file, it will show the migrator option.

Meantime, we'll update the docs to mention this known issue.
