### ISSUE TITLE
Computer Level NuGet Config Path

### ISSUE THREAD

**Issue by mitgiraffe** [NuGet/docs.microsoft.com-nuget#868]
When referencing the Computer config file path, please note that the full path looks like %ProgramFiles(x86)%\NuGet\Config\nuget.config

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 370d9d91-9f35-79aa-3ace-7b77436e988f
* Version Independent ID: 3da4591a-3d3d-c07a-6672-97964de13b14
* Content: [Configuring the behavior of NuGet](https://docs.microsoft.com/en-us/nuget/consume-packages/configuring-nuget-behavior)
* Content Source: [docs/consume-packages/Configuring-NuGet-Behavior.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/master/docs/consume-packages/Configuring-NuGet-Behavior.md)
* Service: **nuget**
* GitHub Login: @kraigb
* Microsoft Alias: **kraigb**

**Comment by kraigb** [comment]
Yes, you're correct. Thanks for pointing that out. I've made a change.

**Comment by bairog** [comment]
Current docs (https://docs.microsoft.com/en-us/nuget/consume-packages/configuring-nuget-behavior) have **%appdata%\NuGet\NuGet.Config** for User scope, but **%ProgramFiles(x86)%\NuGet\Config** for Computer scope. 
Shouldn't it be **%ProgramFiles(x86)%\NuGet\ConfigNuGet.Config**?
