### ISSUE TITLE
How to specify NuGet Version ranges

### ISSUE THREAD

**Issue by mwpowellhtx** [NuGet/docs.microsoft.com-nuget#869]
There is the PackageReference element, which I can use to pull in a specific version of package. However, how do I specify that I'd like to allow a range of versions for the dependency at the time of packaging my assembly.

In other words, I have a dependency that does not belong in any 'lib' folders, per se, but I want to permit the range of versions. However, all I get is this:

```
1>C:\Program Files\dotnet\sdk\2.1.200\Sdks\NuGet.Build.Tasks.Pack\build\NuGet.Build.Tasks.Pack.targets(198,5): warning NU5100: The assembly 'content\NUnit3.TestAdapter.dll' is not inside the 'lib' folder and hence it won't be added as a reference when the package is installed into a project. Move it into the 'lib' folder if it needs to be referenced.
```

Desired reference is this:

```Xml
<PackageReference Include="NUnit" Version="[3.10.1,4)" />
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ff707668-94d6-25a5-9139-b18cc1b6b446
* Version Independent ID: 494847b9-4894-0beb-7ffa-39a2359999fa
* Content: [NuGet PackageReference format (package references in project files)](https://docs.microsoft.com/en-us/nuget/consume-packages/package-references-in-project-files)
* Content Source: [docs/consume-packages/Package-References-in-Project-Files.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/master/docs/consume-packages/Package-References-in-Project-Files.md)
* Service: **nuget**
* GitHub Login: @kraigb
* Microsoft Alias: **kraigb**

**Comment by Mikejo5000** [comment]
I believe the version ranges are specified here:
https://docs.microsoft.com/en-us/nuget/reference/package-versioning#version-ranges-and-wildcards
There's a link to this page in the section Controlling Dependency Versions. Please re-open if that does not answer the issue.

**Comment by mwpowellhtx** [comment]
@Mikejo5000 Thanks for the clue, although the section is *Controlling dependency version*, not *Controlling Dependency Versions*, for those following after. Yes, that basically addressed the question, and I've been successful at doing that.

**Comment by Mikejo5000** [comment]
Great, thanks!
