### ISSUE TITLE
Possible typo with manifest-name

### ISSUE THREAD

**Issue by frankmeten** [NuGet/docs.microsoft.com-nuget#871]
Should the only one manifest-name be a mistake of project-name in this document?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f35f4267-e5e3-ddcf-d3e4-479fb233ce9f
* Version Independent ID: 6d49d66f-f777-7e44-3a45-723e3ad09a59
* Content: [How to create a NuGet package](https://docs.microsoft.com/en-us/nuget/create-packages/creating-a-package#from-a-visual-studio-project)
* Content Source: [docs/create-packages/Creating-a-Package.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/master/docs/create-packages/Creating-a-Package.md)
* Service: **nuget**
* GitHub Login: @kraigb
* Microsoft Alias: **kraigb**

**Comment by kraigb** [comment]
Yes, you're correct. I've made the edit (and updated the title of this issue to be more descriptive.)
