### ISSUE TITLE
Support required for net standard package

### ISSUE THREAD

**Issue by AshwinKamathB** [NuGet/docs.microsoft.com-nuget#872]
We have created nuget package for netstandard2.0 DLL.As part of this we want to copy some files to the out put directory.Which is not happening.Do you guys have document which tells how to do

**Comment by Mikejo5000** [comment]
I believe this question is about MSBuild rather than NuGet. Perhaps the MSBuild Copy task
https://docs.microsoft.com/en-us/visualstudio/msbuild/copy-task?view=vs-2019
