### ISSUE TITLE
what file system?

### ISSUE THREAD

**Issue by frankmeten** [NuGet/docs.microsoft.com-nuget#873]
[its often easiest to create the folder structure you want on the file system, but what file system?]
is c:\ right?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f35f4267-e5e3-ddcf-d3e4-479fb233ce9f
* Version Independent ID: 6d49d66f-f777-7e44-3a45-723e3ad09a59
* Content: [How to create a NuGet package](https://docs.microsoft.com/en-us/nuget/create-packages/creating-a-package#from-a-convention-based-working-directory)
* Content Source: [docs/create-packages/Creating-a-Package.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/master/docs/create-packages/Creating-a-Package.md)
* Service: **nuget**
* GitHub Login: @kraigb
* Microsoft Alias: **kraigb**

**Comment by kraigb** [comment]
Yes. "the file system" refers to your local hard drive, SSD, etc. It's standard terminology. Would it help to say "on your file system" instead of "on the file system"?

**Comment by kraigb** [comment]
In any case, I made some small edits that'll hopefully clarify this for you.
