### ISSUE TITLE
How to migrate packages dependent on install.ps1?

### ISSUE THREAD

**Issue by RussKie** [NuGet/docs.microsoft.com-nuget#885]
We are migrating a large SDK-style solution which is heavily dependent on install.ps1.
Some guidance would be greatly appreciated

https://github.com/NuGet/Home/issues/5963 is opened in Sep'17 and still is pending.
https://developercommunity.visualstudio.com/comments/125352/view.html suggests to utilise MSBuild props and targets however provides no information on how to do so.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 75e25f56-15c8-79d7-5e55-d145b7c1159c
* Version Independent ID: 06388a58-df68-9438-92d7-17359196f5c8
* Content: [Migrating from package.config to PackageReference formats](https://docs.microsoft.com/en-us/nuget/reference/migrate-packages-config-to-package-reference#package-compatibility-issues)
* Content Source: [docs/reference/migrate-packages-config-to-package-reference.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/master/docs/reference/migrate-packages-config-to-package-reference.md)
* Service: **unspecified**
* Product: **nuget**
* GitHub Login: @karann-msft
* Microsoft Alias: **karann**

**Comment by rohit21agrawal** [comment]
let's engage in the discussion here: https://github.com/NuGet/Home/issues/5963#issuecomment-391889708
