### ISSUE TITLE
Not Available for Xamarin.Android projects

### ISSUE THREAD

**Issue by topgenorth** [NuGet/docs.microsoft.com-nuget#892]
Just tried this on VS2017 15.7.2 with a solution containing a Xamarin.Android project and a Xamarin.Android binding project. There is no "Tools > NuGet Package Manager > Package Manager Console..." menu item available.  Is this by design?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 75e25f56-15c8-79d7-5e55-d145b7c1159c
* Version Independent ID: 06388a58-df68-9438-92d7-17359196f5c8
* Content: [Migrating from package.config to PackageReference formats](https://docs.microsoft.com/en-us/nuget/reference/migrate-packages-config-to-package-reference#migration-steps)
* Content Source: [docs/reference/migrate-packages-config-to-package-reference.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/master/docs/reference/migrate-packages-config-to-package-reference.md)
* Service: **unspecified**
* Product: **nuget**
* GitHub Login: @karann-msft
* Microsoft Alias: **karann**

**Comment by rohit21agrawal** [comment]
no, Package Manager Console should always be available. Can you try repairing your installation of Visual Studio?

Can you also check if this directory exists: C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\CommonExtensions\Microsoft\NuGet
