### ISSUE TITLE
Missing refs due to project file move

### ISSUE THREAD

**Issue by bb1769** [NuGet/docs.microsoft.com-nuget#898]
I got the "" error and tried all solutions in this article, but nothing worked. The problem had nothing to do with missing packages. Instead, the problem was that I'd moved the project, but the .csproj file retained the now-invalid paths to package restore locations. I edited those paths and the build worked. See https://stackoverflow.com/questions/32254439/nuget-packages-are-missing

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 906d0438-0338-0167-3a38-d213ee187ddb
* Version Independent ID: b558fa0c-f549-1e6a-c2db-fd2e6a2351be
* Content: [Troubleshooting NuGet Package Restore in Visual Studio](https://docs.microsoft.com/en-us/nuget/Consume-Packages/Package-restore-troubleshooting)
* Content Source: [docs/consume-packages/Package-restore-troubleshooting.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/master/docs/consume-packages/Package-restore-troubleshooting.md)
* Service: **unspecified**
* Product: **nuget**
* GitHub Login: @kraigb
* Microsoft Alias: **kraigb**

**Comment by kraigb** [comment]
@bb1769 What was the specific error message? I want to make sure I put a note about this under the correct heading on the page.

**Comment by kraigb** [comment]
@bb1769 Never mind, I see the error message on the stackoverflow thread.

**Comment by kraigb** [comment]
@bb1769 Take a look at https://github.com/NuGet/docs.microsoft.com-nuget/commit/18e8e51b05939d66eeb8d8f3ff5270a84daa9270 and let me know if more needs to be said.

**Comment by bb1769** [comment]
That does address the issue, thanks.

Bryan
