### ISSUE TITLE
From nuget pack .csproj: "which automatically loads the project's .nuspec file and replaces any tokens within it using values in the project file"

### ISSUE THREAD

**Issue by lucasgl** [NuGet/docs.microsoft.com-nuget#899]
Does that means it will use the .nuspec file from where? I am trying to add Tags and projectUrl into my pack but I can put the nuspec file anywhere or not have it at all it does not seems to change anything.
How should I proceed? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f35f4267-e5e3-ddcf-d3e4-479fb233ce9f
* Version Independent ID: 6d49d66f-f777-7e44-3a45-723e3ad09a59
* Content: [How to create a NuGet package](https://docs.microsoft.com/en-us/nuget/create-packages/creating-a-package#from-a-visual-studio-project)
* Content Source: [docs/create-packages/Creating-a-Package.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/master/docs/create-packages/Creating-a-Package.md)
* Service: **unspecified**
* Product: **nuget**
* GitHub Login: @kraigb
* Microsoft Alias: **kraigb**

**Comment by kraigb** [comment]
It assumes the .nuspec file is in the same folder as the project file, and has the same name as the project file. That is, if you have myproject.csproj, it looks for myproject.nuspec.

**Comment by lucasgl** [comment]
So it is the way I have now but I can change or add anything in the nuspec file and the pack does not seem to get it.
To reproduce the issue, just create a project and a nuspec file, then change any field in the nuspec file then pack using the csproj, the resulting nuspec file into the nupkg does not contain any of those inside.

**Comment by ahmadidev** [comment]
It would be great if you note this in the article itself. I spent couple of hours to figuring out why nuget pack doesn't use my .nuspec file.

**Comment by ErikxNilsson** [comment]
Is there any way to specify nuspec file manually when packing a .csproj file? Right now I have two nuspec files in my project, and if I run "nuget pack myproject.csproj", nuget just ignores the name and picks the nuspec file that appear first in the .csproj file (which is even located in a subdirectory).

This is using nuget 4.3.0.3

**Comment by Mikejo5000** [comment]
The doc referenced in this issue is mainly for nuget.exe CLI. The main scenario for SDK-style projects and non-SDK-style migrated to PackageReference is not to build a .nuspec at all (it gets generated). See this topic:
https://docs.microsoft.com/en-us/nuget/create-packages/creating-a-package-dotnet-cli

However, if you do choose to use a .nuspec in the these scenarios, it is documented here:
https://docs.microsoft.com/en-us/nuget/reference/msbuild-targets#packing-using-a-nuspec
