### ISSUE TITLE
Incorrect assertion about search behaviour

### ISSUE THREAD

**Issue by rwil02** [NuGet/docs.microsoft.com-nuget#904]
"that contain ALL the provided keywords"

Nope.  ANY.

Search for "bbcode"10 results
search for "editor" 525 results
search for "bbcode editor" 535 results
search for "editor bbcode" 535 results

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e3ad41c6-6549-e33b-407e-52357146f49a
* Version Independent ID: 741c3f86-a7c6-f48f-bc29-e49a439f7c61
* Content: [Finding and Choosing NuGet Packages](https://docs.microsoft.com/en-nz/nuget/consume-packages/finding-and-choosing-packages#search-syntax)
* Content Source: [docs/consume-packages/Finding-and-Choosing-Packages.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/master/docs/consume-packages/Finding-and-Choosing-Packages.md)
* Service: **unspecified**
* Product: **nuget**
* GitHub Login: @kraigb
* Microsoft Alias: **kraigb**

**Comment by kraigb** [comment]
Thanks for the clarification. You can do a search for all the terms with "+" between them. I'll make the change in the docs.
