### ISSUE TITLE
TargetsForTfmSpecificBuildOutput example should use $(OutDir) and not $(OutputPath)

### ISSUE THREAD

**Issue by assafi** [NuGet/docs.microsoft.com-nuget#906]
$(OutputPath) is relative and so Pack will complain that the file is not found if run from anywhere else besides the project root folder.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 099102e8-c320-ef50-6821-57519684dc98
* Version Independent ID: 1523dac4-419d-613d-2497-4062f9efd358
* Content: [NuGet pack and restore as MSBuild targets](https://docs.microsoft.com/en-us/nuget/reference/msbuild-targets)
* Content Source: [docs/reference/msbuild-targets.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/master/docs/reference/msbuild-targets.md)
* Service: **unspecified**
* Product: **nuget**
* GitHub Login: @kraigb
* Microsoft Alias: **kraigb**

**Comment by Mikejo5000** [comment]
In general, we give instructions to run MSBuild from the project root, but I can mention that $(OutputPath) expects you to be in the project root.
