### ISSUE TITLE
Proxy settings

### ISSUE THREAD

**Issue by sigiesec** [NuGet/docs.microsoft.com-nuget#907]
The information on proxy settings is somewhat confusing.

First, it says:
> http_proxy should be in the format `http://<username>:<password>@<domain>`. Passwords are encrypted and cannot be added manually. 

This is already confusing as there are also keys http_proxy.user and http_proxy.password, which are not mentioned in the description at all.

"domain" is also confusing here, probably "host" is meant. The format should also mention how the port is specified.

Then there is an example:
```
 <add key="http_proxy" value="http://company-squid:3128@contoso.com" />
```

This example is very confusing, and probably not as intended. It was probably extended from the information on http://skolima.blogspot.com/2012/07/nuget-proxy-settings.html, where `http://company-squid:3128` is given as an example, where `company-squid` is the host and 3128 is the port, which on this page turns into a user `company-squid` with password `3128` (which is in conflict with the statement that passwords must be encrypted), on host `contoso.com`.

Please also provide some information on how I can verify what nuget actually uses. I am struggling to get nuget to work in my network, and suspect it is somehow related to the proxy settings.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0ea1390e-db36-6759-3095-ebab9d546fdb
* Version Independent ID: ca88d8c6-0515-a267-aac3-a508c54157ab
* Content: [nuget.config File Reference](https://docs.microsoft.com/en-us/nuget/reference/nuget-config-file)
* Content Source: [docs/reference/nuget-config-file.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/master/docs/reference/nuget-config-file.md)
* Service: **unspecified**
* Product: **nuget**
* GitHub Login: @kraigb
* Microsoft Alias: **kraigb**

**Comment by sigiesec** [comment]
A follow-up question: Is there only a http_proxy setting or are there corresponding https_proxy (and maybe ftp_proxy) settings?

**Comment by philip-reed** [comment]
Why does password even need to be set? Cant the proxy credentials be picked up from the current logged in user? Company password policies often have a password expiry, having to come in and manually update config files each time I change my password is really annoying.  Especially if you forget, and then Nuget locks the domain account because it has an old password!

**Comment by kachalkov** [comment]
https://multibrowser.helpscoutdocs.com/article/20-visual-studio-configure-nuget-behind-a-proxy
