### ISSUE TITLE
documentation to convert advanced nuspec option to csproj format

### ISSUE THREAD

**Issue by SidShetye** [NuGet/docs.microsoft.com-nuget#910]
copied from https://github.com/dotnet/cli/issues/2170#issuecomment-393724157 and simplified

------
### File inclusion
~~How does one add files to the nuget package using the new csproj format? For example with older nuspec files, the tools\install.ps1 is auto-run to setup a few things. As is to copy a license, readme etc.~~

There is some rough documentation for the file inclusion [here](https://github.com/NuGet/Home/wiki/Adding-nuget-pack-as-a-msbuild-target#including-content-in-package). Should be cleaned for better presentation and clarity though.

### Dependency version

Also how does one specify the dependency versions in the csproj? For example, if we want a `mylibrary.nupkg`. The dependency is `mylibrary.dll` -> `mycore.dll` (version 8.0.0.0 and above). Both exist as separate projects in a single solution. How can this dependency, to a specific version, be expressed inside the `csproj` so `dotnet pack` picks it up?

@kraigb This appears to be a gap in the documentation ...

**Comment by sidshetye** [comment]
After reading a bit more, I've significantly re-worded the original post and deleted the corresponding post from dotnet/cli. If you got an email alert, please see this on github.com instead for the latest.

**Comment by Mikejo5000** [comment]
The referenced content has been published here:
https://docs.microsoft.com/en-us/nuget/reference/msbuild-targets#pack-scenarios
