### ISSUE TITLE
How to add a dependency package with an environment variable

### ISSUE THREAD

**Issue by iamamresh** [NuGet/docs.microsoft.com-nuget#911]
Hi All,

I'm trying to add a dependency package, with a condition. In .csproj file, we could add an assembly reference with a condition if there exists an environmental variable or not. The same I'm trying to add in my .nuspec file. Kindly let me know your ideas.

Regards,
Amresh S

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 06a19d7d-253d-f17f-6421-624c9867473d
* Version Independent ID: cc37eb17-f715-080c-7bfc-9eae868d50ba
* Content: [.nuspec File Reference for NuGet](https://docs.microsoft.com/en-us/nuget/reference/nuspec#example-nuspec-files)
* Content Source: [docs/reference/nuspec.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/master/docs/reference/nuspec.md)
* Service: **unspecified**
* Product: **nuget**
* GitHub Login: @kraigb
* Microsoft Alias: **kraigb**

**Comment by loic-sharma** [comment]
You should be able to use an MSBuild condition that tests an environment variable.

Here's an example that demonstrates this: https://docs.microsoft.com/en-us/visualstudio/msbuild/how-to-use-environment-variables-in-a-build#to-provide-a-default-value-for-a-property
Here's the documentation on MSBuild conditions: https://docs.microsoft.com/en-us/visualstudio/msbuild/msbuild-conditions
