### ISSUE TITLE
How do I create a Test Certificate on Mac

### ISSUE THREAD

**Issue by migueldeicaza** [NuGet/docs.microsoft.com-nuget#912]
Would love to get instructions on how to get a test certificate on a Mac, before I go and buy a certificate, I want to make sure that the tooling will work on Mac, and the test certificate sounds like the first step to towards it.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a43491eb-360f-b3ad-9718-12eef3b33862
* Version Independent ID: 486b96d8-3a28-2a44-072d-99fb64c415de
* Content: [Signed Packages](https://docs.microsoft.com/en-us/nuget/reference/signed-packages-reference#get-a-code-signing-certificate)
* Content Source: [docs/reference/Signed-Packages-Reference.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/master/docs/reference/Signed-Packages-Reference.md)
* Service: **unspecified**
* Product: **nuget**
* GitHub Login: @rido-min
* Microsoft Alias: **rmpablos**

**Comment by ridomin** [comment]
you can use openssl to create certs:

```
openssl genrsa 4096 > private.pem
openssl req -x509 -new -key private.pem -out public.pem
openssl pkcs12 -export -in public.pem -inkey private.pem -out mycert.pfx
```

Also from KeyChain UI, there is a Certificate Assistant. Make sure you select CodeSigning.
