### ISSUE TITLE
Please also add that you have to select PackageReference as default format in Tools / Options.

### ISSUE THREAD

**Issue by MichaelRumpler** [NuGet/docs.microsoft.com-nuget#916]
I didn't have the context menu entry and already wanted to add an issue until I found the comment by @kuenzign on a closed issue. https://github.com/NuGet/docs.microsoft.com-nuget/issues/905#issuecomment-392957629
Now I add an issue to add that to the main article. :-)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 75e25f56-15c8-79d7-5e55-d145b7c1159c
* Version Independent ID: 06388a58-df68-9438-92d7-17359196f5c8
* Content: [Migrating from package.config to PackageReference formats](https://docs.microsoft.com/en-us/nuget/reference/migrate-packages-config-to-package-reference#package-compatibility-issues)
* Content Source: [docs/reference/migrate-packages-config-to-package-reference.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/master/docs/reference/migrate-packages-config-to-package-reference.md)
* Product: **nuget**
* GitHub Login: @karann-msft
* Microsoft Alias: **karann**

**Comment by rohit21agrawal** [comment]
closing as stated in https://github.com/NuGet/docs.microsoft.com-nuget/issues/905#issuecomment-395171468
