### ISSUE TITLE
repository metadata field is missing

### ISSUE THREAD

**Issue by scramsby** [NuGet/docs.microsoft.com-nuget#921]
Newer NuGet versions now support a &lt;repository&gt; item as a child of the &lt;metadata&gt; item for specifying the URL to the source repository associated with the NuGet package. That field's documentation appears to be missing here.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 06a19d7d-253d-f17f-6421-624c9867473d
* Version Independent ID: cc37eb17-f715-080c-7bfc-9eae868d50ba
* Content: [.nuspec File Reference for NuGet](https://docs.microsoft.com/en-us/nuget/reference/nuspec#feedback)
* Content Source: [docs/reference/nuspec.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/master/docs/reference/nuspec.md)
* Product: **nuget**
* GitHub Login: @karann-msft
* Microsoft Alias: **karann**

**Comment by scramsby** [comment]
Submitted a PR to update the docs: https://github.com/NuGet/docs.microsoft.com-nuget/pull/922

**Comment by karann-msft** [comment]
we have this covered as part of [Optional metadata elements
](https://docs.microsoft.com/en-us/nuget/reference/nuspec#optional-metadata-elements)
