### ISSUE TITLE
'Project-scope' nuget.config should be 'Solution-scope'?

### ISSUE THREAD

**Issue by pogosama** [NuGet/docs.microsoft.com-nuget#923]
Hi,

I'm confused by [this section](https://docs.microsoft.com/en-us/nuget/consume-packages/configuring-nuget-behavior#config-file-locations-and-uses) of the documentation.

Shouldn't 'project level/scope' of nuget.config file supposed to be 'solution level/scope'? According to one answer on [this issue](https://developercommunity.visualstudio.com/content/problem/24733/visual-studio-nuget-package-manager-ignores-nugetc.html#), Visual Studio does not support project folder nuget.config.

Which one is correct?

I tried it with Visual Studio 2017 (15.6) with a C# .NET library project, I can only made solution scope nuget.config work, not the project scope.

Related to issue [#776](https://github.com/NuGet/docs.microsoft.com-nuget/issues/776).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 370d9d91-9f35-79aa-3ace-7b77436e988f
* Version Independent ID: 3da4591a-3d3d-c07a-6672-97964de13b14
* Content: [Configuring the behavior of NuGet](https://docs.microsoft.com/en-us/nuget/consume-packages/configuring-nuget-behavior)
* Content Source: [docs/consume-packages/Configuring-NuGet-Behavior.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/master/docs/consume-packages/Configuring-NuGet-Behavior.md)
* Product: **nuget**
* GitHub Login: @karann-msft
* Microsoft Alias: **karann**

**Comment by CamSoper** [comment]
Rolled up to #776
