### ISSUE TITLE
Not sure if I can create a NuGet package to distribute my non-NET DLL (natine C++ code) 

### ISSUE THREAD

**Issue by starmessage** [NuGet/docs.microsoft.com-nuget#925]
I have created a DLL ( https://github.com/starmessage/libSoftMeter ) in native C++ code and distributed in 32 + 64 bit formats.
I do not use .net frameworks.
I would like to explore the possibility to distribute it as a NuGet package.
- From the "What is NuGet" it is not clear if I can create a NuGet package for my DLL.
- From inside the Visual Studio, when I try to create a new NuGet project, I am asked for the version of the .Net framework.

It would be helpful for the new users to mention in this documentation, what code can be turned to a NuGet package and what code cannot.
Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bd0c2ac7-8837-d4fd-955b-6a5b261592f3
* Version Independent ID: 4c62f271-70ea-8537-f670-b59bb702c4c0
* Content: [What is NuGet and what does it do?](https://docs.microsoft.com/en-us/nuget/what-is-nuget)
* Content Source: [docs/what-is-nuget.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/master/docs/what-is-nuget.md)
* Product: **nuget**
* GitHub Login: @karann-msft
* Microsoft Alias: **karann**

**Comment by DavidPrio** [comment]
Hi @karann-msft can you please check this? Thanks!

**Comment by DavidPrio** [comment]
Hi @karann-msft is this under you radar?
@nokura FYI

**Comment by gosali** [comment]
Hi @karann-msft is this under your radar?
@nokura FYI

**Comment by gosali** [comment]
Hi @karann-msft is this under your radar?
@nokura FYI

**Comment by karann-msft** [comment]
@DavidPrio do not assign owners to any issues.

**Comment by loic-sharma** [comment]
Please refer to this documentation: https://docs.microsoft.com/en-us/nuget/create-packages/native-packages

That documentation states:

> A native package contains native C++ code instead of managed code, allowing it to be used within C++ projects. (See Native C++ Packages in the Consume section.)
>
> To be consumable in a C++ project, a package must target the `native` framework. At present there are not any version numbers associated with this framework as NuGet treats all C++ projects the same.

Does that help?

**Comment by starmessage** [comment]
Hi,
the documentation you mentioned 
 https://docs.microsoft.com/en-us/nuget/create-packages/native-packages
answers my question that non .NET code can be added. 
But it created another question:
It states "contains native C++ code". Does this mean that it cannot contain simply a DLL? 
(A native DLL can be created with other languages as well, not only by C++)

My initial question was about the "What is NuGet" at 
https://docs.microsoft.com/en-us/nuget/what-is-nuget 
It states "A 'compatible' package means that it contains assemblies built for at least one target .NET framework"  and this statement, being on the first page, cuts down any hope for nuget to cover support for a native dll. This is why I did not dig further to find the "native packages".

Younger developers will probably think these are obvious and no further explanation is needed, but older developers like me, will have difficulties understanding this packaging.

thanks

**Comment by loic-sharma** [comment]
> It states "contains native C++ code". Does this mean that it cannot contain simply a DLL?
(A native DLL can be created with other languages as well, not only by C++)

A NuGet package can contain a DLL, even if it was built from a language other than C++.

Have you considered any alternatives? You may have a better experience with vcpkg: https://github.com/Microsoft/vcpkg

**Comment by karann-msft** [comment]
we updated docs to make this more clear.
