### ISSUE TITLE
Nuget

### ISSUE THREAD

**Issue by ChadMcCaffery** [NuGet/docs.microsoft.com-nuget#927]
In the section [Normalized version numbers](https://docs.microsoft.com/en-us/nuget/reference/package-versioning#normalized-version-numbers), this statement is false:
_This normalization does not affect the version numbers in the packages themselves; it affects only how NuGet matches versions when resolving dependencies._

nuget.exe changes the version number to "1.0.1" given this .nuspec file:
```
<?xml version="1.0"?>
<package>
  <metadata>
    <id>MyPackage</id>
    <version>1.00.01.0</version>
    <authors>johndoe@company.com</authors>
    <description>Simple description</description>
  </metadata>
</package>
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 55c7db33-f188-0247-4c5e-035b25b11392
* Version Independent ID: 33cd8166-51d5-3ce3-8d6f-8f0df0310724
* Content: [NuGet Package Version Reference](https://docs.microsoft.com/en-us/nuget/reference/package-versioning)
* Content Source: [docs/reference/Package-Versioning.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/master/docs/reference/Package-Versioning.md)
* Product: **nuget**
* GitHub Login: @karann-msft
* Microsoft Alias: **karann**

**Comment by Mikejo5000** [comment]
@nkolev92 Is there a doc change required for this?

**Comment by nkolev92** [comment]
> This normalization does not affect the version numbers in the packages themselves 

This is technically true. 
NuGet does not change the packages already built, which is what the sentence might be implying. 

Pack & restore operations, both normalize versions whenever posssible.

**Comment by Mikejo5000** [comment]
I'll make that more explicit then.
