### ISSUE TITLE
Update 'Create Packages for Xamarin' Doc with .NET Standard Content

### ISSUE THREAD

**Issue by dfoulk** [NuGet/docs.microsoft.com-nuget#928]
This documentation describes how to create Xamarin plugins using PCLs. Now that Xamarin.Forms is using .NET Standard 2.0, is there any chance that we can get this documentation updated with information on how to create plugins using .NET Standard?

Extra Credit: There is currently no documentation on how to add/update files in a target project from a NuGet package targeting Xamarin.Android, Xamarin.iOS or Xamarin.UWP. For example: How do we add and/or modify an XML file present in the target project via a Xamarin.Forms plugin? It would be great if you could share how to do this in the docs so that we can create themes (plugins) that can style Android (in addition to the Xamarin.Forms ResourceDictionary styles).

Thank you,
-Derek

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d228e1b2-34af-a8cb-0a54-e2fcb6cd34df
* Version Independent ID: 31e9b41e-b74f-3614-7c3d-cd17a04e1211
* Content: [Create NuGet Packages for Xamarin (for iOS, Android, and Windows) with Visual Studio 2015](https://docs.microsoft.com/en-us/nuget/guides/create-packages-for-xamarin)
* Content Source: [docs/guides/create-packages-for-xamarin.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/master/docs/guides/create-packages-for-xamarin.md)
* Product: **nuget**
* GitHub Login: @karann-msft
* Microsoft Alias: **karann**

**Comment by irongut** [comment]
Updating the docs for VS2017 would be nice too, especially with VS2019 just around the corner.

**Comment by chrisevans9629** [comment]
Still waiting for this

**Comment by dfoulk** [comment]
Wow, I am surprised that this hasn't been addressed yet... This doc is 2.5+ years old. Oh, the joys of being a Xamarin developer!

**Comment by dfoulk** [comment]
@chrisevans9629 In the meantime, please checkout this extension for a jump-start: https://marketplace.visualstudio.com/items?itemName=vs-publisher-473885.PluginForXamarinTemplates

It may be over-kill if you're just creating a plugin for the .NET Standard project in Xamarin.Forms. The long and short of it is that you can create a .NET Standard library for the project you want to create the plugin for, then use the project's properties to package the project as a NuGet package.

In this .NET Standard project(s), you can install the necessary NuGet packages (Xamarin.Forms, Acr.UserDialogs, etc.) to develop your plugin for that project- just like any other .NET Standard library.

Regarding the "Extra Credit" portion of my original post; I've yet to figure that out. If you wish to study the discussion I watched for a long time, you can find it here: https://github.com/NuGet/Home/issues/4803#issuecomment-290206781

I hope this helps!

**Comment by MagicAndre1981** [comment]
what a crappy bot, closes an issue that is not fixed at all

**Comment by johnshardman** [comment]
This article is ridiculously out of date. Attempting to create a NuGet using either VS2017 or VS2019, and things simply don't match this article.

**Comment by karann-msft** [comment]
@johnshardman - can you point me to the issue you are referring to?

**Comment by johnshardman** [comment]
@karann-msft - https://docs.microsoft.com/en-us/nuget/guides/create-packages-for-xamarin

Try following those instructions on either VS2017 or VS2019

**Comment by dfoulk** [comment]
@johnshardman call me crazy, but that is the URL that I was referencing in this issue... The "updated" date shows 2017 still, but now the doc references .NET Standard 1.4... Still not current, but better than the PCL information that was there.

**Comment by johnshardman** [comment]
@dfoulk - Not crazy at all. It seems that I need more sleep and/or coffee, as I misinterpreted the question from @karann-msft . The issue that I logged is at https://github.com/xamarin/Xamarin.Forms/issues/8070

There is now a PR to update the documentation at https://github.com/NuGet/docs.microsoft.com-nuget/pull/1758

The proposed documentation update is at https://github.com/michizhou/docs.microsoft.com-nuget/blob/michizhou-update-docs/docs/guides/create-packages-for-xamarin.md

I haven't had time to review the proposed update yet. If you have time, please do.

**Comment by dfoulk** [comment]
🤘

**Comment by karann-msft** [comment]
The updates have now been published! Thank you for the feedback everyone!

**Comment by dfoulk** [comment]
@karann-msft Thats's an improvement, thank you.
