### ISSUE TITLE
Add/Update Command

### ISSUE THREAD

**Issue by kduenke** [NuGet/docs.microsoft.com-nuget#929]
It be nice to have one command (or flag) that would add a new source, or update a source if it already exists.  Currently, I'm doing Remove then Add.  Remove and Update both fail if the source doesn't already exist.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fd704fe8-fd6e-ba7f-6021-15f280657f4d
* Version Independent ID: dc047102-284f-ad70-99ee-dac5be511392
* Content: [NuGet CLI sources command](https://docs.microsoft.com/en-us/nuget/tools/cli-ref-sources)
* Content Source: [docs/tools/cli-ref-sources.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/master/docs/tools/cli-ref-sources.md)
* Product: **nuget**
* GitHub Login: @karann-msft
* Microsoft Alias: **karann**

**Comment by SQLEmil** [comment]
This doesn't fix the commands, but it's a PowerShell workaround so you don't have to mess around with remove:
```powershell
if (-not $(nuget sources List | Select-String -Pattern 'PackageSourceAlias' -Quiet)) {
    nuget sources Add -Name PackageSourceAlias -Source https://nuget.address.com
}
else {
    nuget sources Update -Name PackageSourceAlias -Source https://nuget.address.com
}
```

**Comment by CamSoper** [comment]
Hi there, @kduenke!  This is the NuGet docs repo. I think you'll want to open this issue over in https://github.com/NuGet/Home
