### ISSUE TITLE
Update-Package without argument isn't possible in VS2017

### ISSUE THREAD

**Issue by erikbra** [NuGet/docs.microsoft.com-nuget#933]
There is always a "default project", so if you write "Update-Package" without any arguments, it operates on the default project, not on all projects, as stated in the example:

&gt;# Updates all packages in all projects in the solution
&gt;Update-Package

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3e755306-fb38-33c5-6f0f-1947832c21f2
* Version Independent ID: 0335cc14-e041-ffb3-f3c4-26dd39d18ef2
* Content: [Reinstalling and Updating NuGet Packages](https://docs.microsoft.com/en-us/nuget/consume-packages/reinstalling-and-updating-packages)
* Content Source: [docs/consume-packages/Reinstalling-and-Updating-Packages.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/master/docs/consume-packages/Reinstalling-and-Updating-Packages.md)
* Product: **nuget**
* GitHub Login: @karann-msft
* Microsoft Alias: **karann**

**Comment by Mikejo5000** [comment]
@nkolev92 Nikolche, I'm inclined to update these docs based on the suggestion here. Let me know if that is incorrect.

**Comment by nkolev92** [comment]
I just tested it locally with 16.x and 15.x of Visual Studio, Update-Package works on all the projects in the solution. 
You need to specify -ProjectName to update for a specific project.

I get why this can be misleading and/or maybe soemthing else is going, so @erikbra if you see inconsistencies please open an issue in nuget/home

**Comment by Mikejo5000** [comment]
Thanks, @nkolev92 Closing this issue here.
