### ISSUE TITLE
Rate limiter error is incorrect

### ISSUE THREAD

**Issue by hadichami** [NuGet/docs.microsoft.com-nuget#934]
I was hitting the rate limit of 250/hour via Put and Delete calls but instead of a 429 : "Rate limit is exceeded. Try again in 56 seconds." error, I was getting a 403 : "Quota Exceeded" error. This lead to a lot of confusion as that error is undocumented. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ea5f95be-04dd-82bb-7cbb-6d89bf4bbc83
* Version Independent ID: 3cf47c47-1070-91b8-fd70-469517f1a076
* Content: [Rate Limits, NuGet API](https://docs.microsoft.com/en-us/nuget/api/rate-limits)
* Content Source: [docs/api/rate-limits.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/master/docs/api/rate-limits.md)
* Product: **nuget**
* GitHub Login: @cmanu
* Microsoft Alias: **cmanu**

**Comment by CamSoper** [comment]
Fixed
