### ISSUE TITLE
-Source not documented very well

### ISSUE THREAD

**Issue by Mattacks** [NuGet/docs.microsoft.com-nuget#936]
Is it possible to specify more than one source? Should it be comma separated? An array?...

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fd704fe8-fd6e-ba7f-6021-15f280657f4d
* Version Independent ID: dc047102-284f-ad70-99ee-dac5be511392
* Content: [NuGet CLI sources command](https://docs.microsoft.com/en-us/nuget/tools/cli-ref-sources)
* Content Source: [docs/tools/cli-ref-sources.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/master/docs/tools/cli-ref-sources.md)
* Product: **nuget**
* GitHub Login: @karann-msft
* Microsoft Alias: **karann**

**Comment by Lexcess** [comment]
Was just looking for this very thing. Documentation states a list is valid but doesn't show what to use.

**Comment by solomon-xpo** [comment]
Same! This feature can come in handy when restoring nuget in Teamcity.

**Comment by max-lancaster** [comment]
Also there is no documentation about how to remove a source, how is this done?

**Comment by max-lancaster** [comment]
I was able to manually remove a source by editing Nuget.config directly but would be nice to have a command to do so.

**Comment by chaami** [comment]
Hi,
I am just a bystander, but after briefly reading the documentation and [the code ](https://github.com/NuGet/NuGet.Client/blob/dev/src/NuGet.Clients/NuGet.CommandLine/Commands/SourcesCommand.cs) I think that:
you can list the configured sources (list is a valid _command_, but the documentation never indicates that you can add a list.
you can only have one add invocation when using nuget sources (From the MaxArgs = 1 annotation of the sources command) to therefore add only one source (with valid credentials) for each add attempt.
Kind regards,
Amine

**Comment by karann-msft** [comment]
currently, you can specify only one source when working with the `nuget source` command.
@Lexcess - can you point me to the statement that led you to believe that a list is valid?

**Comment by Lexcess** [comment]
@karann-msft This was nearly a year ago, but as I recall you can specify multiple Source parameters to get the desired effect. Re-reading now I suspect I was mis-reading the 'manages the list of...'.

That said if you can still supply multiple source parameters to get the effect then the documentation is incomplete.

**Comment by karann-msft** [comment]
@Lexcess - if you pass more than one source, only the last one is used. So you cannot get a result where you can act on more than one source with a single command.

**Comment by Lexcess** [comment]
@karann-msft I don't have access to the source code any more so I'll take your word for it!

**Comment by karann-msft** [comment]
@Lexcess - nuget is open source including the nuget client :) - https://github.com/NuGet/NuGet.Client
