### ISSUE TITLE
Add Sleet as option for custom feeds

### ISSUE THREAD

**Issue by loic-sharma** [NuGet/docs.microsoft.com-nuget#937]
The ["Hosting your own NuGet feeds" page](https://docs.microsoft.com/en-us/nuget/hosting-packages/overview) documents how customers can host their own feeds. The documented options fall into two categories:

1. Local feed that uses network share
2. Web servers that implement NuGet protocols

Sleet (https://github.com/emgarten/Sleet) is an alternative that allows customers to create static feeds. This is more powerful than a local feed and less cumbersome than hosting a web server.

See this issue: https://github.com/NuGet/Home/issues/7031

/cc @emgarten

**Comment by CamSoper** [comment]
It's a great project, but I'm afraid it's out of scope for the conceptual/reference docs.
