### ISSUE TITLE
Unclear under which conditions the search syntax applies

### ISSUE THREAD

**Issue by Apollo3zehn** [NuGet/docs.microsoft.com-nuget#939]
According to comment https://github.com/NuGet/NuGetGallery/issues/5999#issuecomment-396732278 the instructions on this page apply only to nuget.org and V2 API. I would appreciate if you could make this page more clear in where it applies. The sentence "These packages can come from the public collection on nuget.org, or a private source that's provided by your organization or another third party." leads to the assumption that e.g the property filtering (&lt;property&gt;:&lt;term&gt;) applies generally. Also I was assuming that the "+" sign is also valid on V3 searches.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e3ad41c6-6549-e33b-407e-52357146f49a
* Version Independent ID: 741c3f86-a7c6-f48f-bc29-e49a439f7c61
* Content: [Finding and Choosing NuGet Packages](https://docs.microsoft.com/en-us/nuget/consume-packages/finding-and-choosing-packages#feedback)
* Content Source: [docs/consume-packages/Finding-and-Choosing-Packages.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/master/docs/consume-packages/Finding-and-Choosing-Packages.md)
* Product: **nuget**
* GitHub Login: @karann-msft
* Microsoft Alias: **karann**

**Comment by loic-sharma** [comment]
Hi, thanks for opening this issue!

> "These packages can come from the public collection on nuget.org, or a private source that's provided by your organization or another third party."

This sentence means that packages may be downloaded from nuget.org, or any other custom package sources you may have added (like Azure Artifacts, MyGet, etc...).

> The sentence "These packages can come from the public collection on nuget.org, or a private source that's provided by your organization or another third party." leads to the assumption that e.g the property filtering (<property>:<term>) applies generally.

Each package source has its own search syntax. NuGet.org's search service does have property filtering like `packageId:newtonsoft.json`, but this may not be supported by other NuGet package sources like Azure Artifacts. This property filtering should work on Visual Studio's "Browse" packages tab if NuGet.org is your only source.

> Also I was assuming that the "+" sign is also valid on V3 searches.

The `+` sign works on the NuGet.org website. However, this is broken on Visual Studio as it does not escape search queries properly (see https://github.com/NuGet/Home/issues/9043).

Please let us know if you have any additional questions, or any feedback on how to word this documentation better!

**Comment by karann-msft** [comment]
@Apollo3zehn - if you have additional feedback please file a new issue. Thanks!
