### ISSUE TITLE
Nuget dependency on .Net framework 4.7

### ISSUE THREAD

**Issue by Brett57Heinz** [NuGet/docs.microsoft.com-nuget#940]
Hello,
The target frameworks page of the nuget documentation does not mention reference to the TFM to use for a package that references .net 4.7 or 4.7.1 framework. Is that supported? Can I just use "net47"?

Thanks,
Brett

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0a0f5267-208d-8af2-ef18-dae7407eefad
* Version Independent ID: 19b00f91-5d31-0d4d-388b-30b1bd4e7c0f
* Content: [Target Frameworks Reference for NuGet](https://docs.microsoft.com/en-us/nuget/reference/target-frameworks)
* Content Source: [docs/reference/target-frameworks.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/master/docs/reference/target-frameworks.md)
* Product: **nuget**
* GitHub Login: @karann-msft
* Microsoft Alias: **karann**

**Comment by tg2k** [comment]
https://docs.microsoft.com/en-us/dotnet/standard/frameworks lists that, but this page doesn't.

**Comment by karann-msft** [comment]
@Brett57Heinz @tg2k thanks for the feedback. This has been fixed.
