### ISSUE TITLE
Invalid Link in "Omitting NuGet packages in source control systems"

### ISSUE THREAD

**Issue by HolidayLighting** [NuGet/docs.microsoft.com-nuget#943]
https://docs.microsoft.com/en-us/nuget/consume-packages/packages-and-source-control

Under Omitting packages with Team Foundation Version Control
5. On TFS 2012 or later, or with Visual Studio Team Services, create a .tfignore file as described on AddFiles to the Server. 

"AddFiles to the Server" link is not valid and shows a 404 (https://docs.microsoft.com/en-us/vsts/tfvc/add-files-server.md?view=vsts#tfignore)

It looks like it should be (https://docs.microsoft.com/en-us/vsts/tfvc/add-files-server?view=vsts#tfignore)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d965aea9-a6cc-06da-a347-6e8c89458c98
* Version Independent ID: 6775f211-f4b6-6d0c-6f2e-6664b3e9721e
* Content: [NuGet Packages and Source Control](https://docs.microsoft.com/en-us/nuget/consume-packages/packages-and-source-control)
* Content Source: [docs/consume-packages/Packages-and-Source-Control.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/master/docs/consume-packages/Packages-and-Source-Control.md)
* Product: **nuget**
* GitHub Login: @karann-msft
* Microsoft Alias: **karann**

**Comment by Rod-in-NM** [comment]
I found the same problem that HolidayLighting did. The "AddFiles to the Server" link is broken.

**Comment by karann-msft** [comment]
Fixed!
