### ISSUE TITLE
Nuget package that are missing on this computer

### ISSUE THREAD

**Issue by coyuX** [NuGet/docs.microsoft.com-nuget#944]
I got this error: The missing file is ..\packages\opencv3.1.redist.1.0\build\native\opencv3.1.redist.targets.
But I went to the native folder and the file is right there. I turned on the the package restore setting itoo,  but it still doesn't work.

**Comment by rrelyea** [comment]
You are reporting this problem in our Docs repo. Can you please search for similar issues at https://GitHub.com/nuget/home/issues  - 

If you are not able to find another similar issue, with helpful discussion, please open a new issue (with more details/steps on how anybody else can repro this same problem).
