### ISSUE TITLE
This is just for a runtime component

### ISSUE THREAD

**Issue by moneylow** [NuGet/docs.microsoft.com-nuget#946]
I would love to see the packaging process for just plain library project.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f35f4267-e5e3-ddcf-d3e4-479fb233ce9f
* Version Independent ID: 6d49d66f-f777-7e44-3a45-723e3ad09a59
* Content: [How to create a NuGet package](https://docs.microsoft.com/en-us/nuget/create-packages/creating-a-package)
* Content Source: [docs/create-packages/Creating-a-Package.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/master/docs/create-packages/Creating-a-Package.md)
* Product: **nuget**
* GitHub Login: @karann-msft
* Microsoft Alias: **karann**

**Comment by mbedded** [comment]
Hello moneylow is just read your comment as i had an issue with the readme file.
What do you mean exactly?

On VS2017 and Net Core-Library you can just tick "create a package" and your are done.
![2018-08-21 21_44_05-colib common - microsoft visual studio](https://user-images.githubusercontent.com/22235508/44425216-8712e600-a58b-11e8-95e9-7f51891669b1.png)

For classic Net Framework projects you have to add this nuspec file. So you can create your library as usual and thats it.
