### ISSUE TITLE
Confusing info about NuGet credential providers

### ISSUE THREAD

**Issue by sryabkov** [NuGet/docs.microsoft.com-nuget#947]
The [nuget.exe credential providers page](https://docs.microsoft.com/en-us/nuget/reference/extensibility/nuget-exe-credential-providers) reads "Note that the credential providers described here work only in nuget.exe **and not in 'dotnet restore'** or Visual Studio. For credential providers with Visual Studio, see nuget.exe Credential Providers for Visual Studio"

The [NuGet credential providers for Visual Studio page](https://docs.microsoft.com/en-us/nuget/reference/extensibility/nuget-credential-providers-for-visual-studio) reads "NuGet credential providers for Visual Studio work only in Visual Studio (**not in dotnet restore** or nuget.exe). For credential providers with nuget.exe, see nuget.exe Credential Providers."

Notice how both pages talk about "it does not work for dotnet restore" and point to each other, but there is no page that talks about how nuget credentials work with `dotnet restore`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0c65baea-410a-437a-6d06-428075d06e4e
* Version Independent ID: 864a8667-e0d4-38df-9e5b-8eba5f177218
* Content: [nuget.exe Credential Providers](https://docs.microsoft.com/en-us/nuget/reference/extensibility/nuget-exe-credential-providers)
* Content Source: [docs/reference/extensibility/nuget-exe-Credential-Providers.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/master/docs/reference/extensibility/nuget-exe-Credential-Providers.md)
* Product: **nuget**
* GitHub Login: @karann-msft
* Microsoft Alias: **karann**

**Comment by rrelyea** [comment]
yes. Today it doesn't work with dotnet restore.

we are doing the work to make it work in the VS 2017 15.8 timeframe, with .NET SDK 2.1.400 (and potentially an additional installation step)

FYI: @nkolev92

**Comment by sryabkov** [comment]
@rrelyea Got it, thank you for the quick response.

**Comment by jhenyffer** [comment]
Hello, how can I generate this credentialProvider.exe file through CMD ?
On the site just explais the content of the file and where it must be placed.

Thanks!

**Comment by jhenyffer** [comment]
Or is there a way to do nuget.exe install command with credentials already set in the command line?

**Comment by nkolev92** [comment]
@jhenyffer 
> Hello, how can I generate this credentialProvider.exe file through CMD ?

I'm not sure I follow this. Can you please elaborate? 

> Or is there a way to do nuget.exe install command with credentials already set in the command line?

You can set the credentials in the config file.

**Comment by jhenyffer** [comment]
Hello, I would like to know how I create The credential provide, because on
the site is not clear and if there is a way to create it trhough cmd.
In reality my real problem is that I can't run The install Package command
with out having to informa the credentials for proxy in cmd. I already did
the necessário configurations for on Nuget. Config, but it does not work.
If there is a way to run the install command already informing the
credentials it would also help.

Thank you!

Em qui, 16 de ago de 2018 15:37, Nikolche Kolev <notifications@github.com>
escreveu:

**Comment by nkolev92** [comment]
@jhenyffer 
Please refer to https://docs.microsoft.com/en-us/nuget/reference/nuget-config-file#packagesourcecredentials for how to setup NuGet.Config credentials. 

If you are talking about credential providers, your provider should have instructions on how to get it.

**Comment by jhenyffer** [comment]
Yes I have already read this documentário, but it is not clear. I need a
step by step because I am New to it and I don't even know if this will
solve The proxy password stuff. Isn't there a way to passa credential for
froxy toghether with The install Package com and?

Em sex, 17 de ago de 2018 14:58, Nikolche Kolev <notifications@github.com>
escreveu:

**Comment by nkolev92** [comment]
@jhenyffer 

You need to provide the credentials in the nuget.config as in the example docs. 

The same docs should have info about the proxy. 


Feel free to create a dummy project and show me what you're attempted to do (obfuscate the password and username ofc) so far, and I can take a look.

**Comment by jhenyffer** [comment]
I really apreaciate your help, I am sending you an examlple of what I have
done so far:

** I have created a powershell script that will run everytime someone logs
in the computer, this powershell will contain the commands below that
update the NuGet.config (Note that on this step I already tryied pointing
to the %AppData%\**NuGet\**NuGet.config and also triyed pointing to my
local NuGet.config, but non of them seems to work):*
Tryied this (This will update my %AppData% Nuget.config):
.\nuget config -set http_proxy=http://000.000.00.000:8080
.\nuget config -Set http_proxy.user=vcn\a00000
.\nuget config -Set http_proxy.password=password

.\nuget install Automation.AdapterUpdates -Version $version
-OutputDirectory ..\Folder

And also this (This will update my local Nuget.config):
.\nuget config -set http_proxy=http://000.000.00.000:8080 -configFile
C:\Test\AT\NuGet\NuGet.config
.\nuget config -Set http_proxy.user=vcn\a00000 -configFile
C:\Test\AT\NuGet\NuGet.config
.\nuget config -Set http_proxy.password=password -configFile
C:\Test\AT\NuGet\NuGet.config

.\nuget install Automation.AdapterUpdates -Version $version
-OutputDirectory ..\Binaries

** Afther running the powershell my NuGet.config updated to this:*

<?xml version="1.0" encoding="utf-8"?>
<configuration>
<packageSources>
<add key="nuget.org" value="https://api.nuget.org/v3/index.json"
protocolVersion="3" />
</packageSources>
<config>
<add key="http_proxy" value="http://000.000.00.000:8080" />
<add key="http_proxy.user" value="vcn\a000000" />
<add key="http_proxy.password" value=
"AQAAANCMnd8BlmioAwE/Cl+sBAAAAx2buhbuobygtvfdxxxxxAAAAACAAAAAAAQZgAAAAEAACAAAAArhnzGhRk/6t5x7lfsxs1isR7jjR0XiqkrVAosrh1zbQAAAAAOgAAAAAIAACAAAADXybENxHSrO7zq9pUo0n6yhU4XS8CROEueFB41JmQqDRAAAAC+F42GfCJDSAWer3DEQP9aQAAAAMZYYcOUqUgSP2Yk2AEdgh1xGlGT3yGTHfmbFK4fiT7ST5V2SfwYlF88tlks1poGtXqjkEo0fpLy6WqHweCSUAE="
/>
</config>
</configuration>

* * But then when i run the code it always asks me the proxy password as
this:*

[image: image.png]

If you have any doubt about what i have done please ask me and I am going
to clarify.
Hope this can help to understand better.

Thanks !!

Em sex, 17 de ago de 2018 às 15:40, Nikolche Kolev <notifications@github.com>
escreveu:

**Comment by nkolev92** [comment]
@jhenyffer I don't see anything wrong ther.e 

Can you please try to upload the image again? I don't see in your comment.
