### ISSUE TITLE
Package Restore unable to download and install proper NUnit 3

### ISSUE THREAD

**Issue by putztzu** [NuGet/docs.microsoft.com-nuget#950]
Following steps described 
https://docs.microsoft.com/en-us/nuget/Consume-Packages/Package-restore-troubleshooting

Attempting to build
https://github.com/Microsoft/GVFS
Have installed the Framework 3.5, C++/cli , C++ toolset and Windows SDK pre-requisites.
Opened solution and attempted to build, output 8 errors similar to the following, all complaining about the version of NUnit 3.10 not installed on system (see following error). 

`Severity	Code	Description	Project	File	Line	Suppression State
Error		This project references NuGet package(s) that are missing on this computer. Use NuGet Package Restore to download them.  For more information, see http://go.microsoft.com/fwlink/?LinkID=322105. The missing file is ..\..\..\packages\NUnit.3.10.0-dev-05190\build\NUnit.props.	GVFS.Tests	C:\Repos\GVFS\src\GVFS\GVFS\GVFS.Tests\GVFS.Tests.csproj	73`

Have verified that the following setting described in the link at the top of this post is set correctly
> In Visual Studio, enable package restore by selecting the Tools > NuGet Package Manager > Package Manager Settings menu command, setting both options under Package Restore, and selecting OK. Then build the solution again.

Have also installed the NUnit 3.0 Adapter and Templates using Nuget Manager.

No Joy.

**Comment by putztzu** [comment]
Additional.
Attempted to install from NUnitLite package using Nuget Package Manager > 
Error says not available
`Severity	Code	Description	Project	File	Line	Suppression State
Error		NuGet Package restore failed for project GVFS Tests\GVFS.FunctionalTests: Unable to find version '3.10.0-dev-05190' of package 'NUnit'.
  https://api.nuget.org/v3/index.json: Package 'NUnit.3.10.0-dev-05190' is not found on source 'https://api.nuget.org/v3/index.json'.
  https://www.myget.org/F/nunit/api/v3/index.json: Package 'NUnit.3.10.0-dev-05190' is not found on source 'https://www.myget.org/F/nunit/api/v3/index.json'.
. Please see Error List window for detailed warnings and errors.`

**Comment by rrelyea** [comment]
Have you worked with folks in the GFVS project to determine the issue?
That might be a good first step?


If you do need to engage the nuget team, https://github.com/nuget/home/issues/
 is the right place.

**Comment by rrelyea** [comment]
If a project specifies a package that isn't published to one of their sources, they need to fix it...

**Comment by putztzu** [comment]
No, are you saying that they should update their source to support a later
Nunit rather instead of you providing the required Nunit version?
Right now, am looking at possibly obtaining the proper Nunit version
without using the Nuget feed.

**Comment by putztzu** [comment]
OK, I'll have them fix their source
