### ISSUE TITLE
Add PowerShell install command

### ISSUE THREAD

**Issue by hack2root** [NuGet/docs.microsoft.com-nuget#952]
Under PowerShell Command Line, under administrator account run:

Invoke-WebRequest -Uri 'https://dist.nuget.org/win-x86-commandline/v4.7.0/nuget.exe' -OutFile 'nuget.exe'

Alternatively, run cmd.exe under local sysetm adminstrator account, execute:

powershell -NoProfile -ExecutionPolicy unrestricted -Command "Invoke-WebRequest -Uri 'https://dist.nuget.org/win-x86-commandline/v4.7.0/nuget.exe' -OutFile 'nuget.exe'"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 30f597bb-080f-188b-b1ba-a02efbe1e9ca
* Version Independent ID: 88e19d47-f4e1-0496-305c-af14f0d54afb
* Content: [NuGet Command-Line Interface (CLI) Reference](https://docs.microsoft.com/en-us/nuget/tools/nuget-exe-cli-reference#installing-nugetexe)
* Content Source: [docs/tools/nuget-exe-CLI-Reference.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/master/docs/tools/nuget-exe-CLI-Reference.md)
* Product: **nuget**
* GitHub Login: @karann-msft
* Microsoft Alias: **karann**

**Comment by CamSoper** [comment]
Thanks for the feedback! You're right, they both work just as well.
