### ISSUE TITLE
More detail about "pack" options needed, specifically BasePath

### ISSUE THREAD

**Issue by chiefengineer** [NuGet/docs.microsoft.com-nuget#957]
BasePath | Sets the base path of the files defined in the .nuspec file.

OK, just what the heck does "the base path of the files defined in the .nuspec file" actually mean? 

I may not have even created a .nuspec file and if so, might not have opened it up to tinker with it. 

What files are "defined" in the .nuspec file? Why do I care? What happens when I set this value and what should I set it to?

So, in short, this option definition tells me absolutely NOTHING about what is going on and what the value should be.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2e18eb26-7a73-5e48-abd0-3d53476c6f91
* Version Independent ID: 5469de95-4b00-2fbd-f3c0-1cde036f3c7f
* Content: [NuGet CLI pack command](https://docs.microsoft.com/en-us/nuget/tools/cli-ref-pack)
* Content Source: [docs/tools/cli-ref-pack.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/master/docs/tools/cli-ref-pack.md)
* Product: **nuget**
* GitHub Login: @karann-msft
* Microsoft Alias: **karann**

**Comment by Mikejo5000** [comment]
We don't want to say much about the .nuspec here, but there should be a link to the correct doc.
