### ISSUE TITLE
-Source and -Fallback source switches are vague

### ISSUE THREAD

**Issue by matthewjones555** [NuGet/docs.microsoft.com-nuget#958]
The source switch description states "Specifies the list of package sources (as URLs) to use. If omitted, the command uses the sources provided in configuration files, see Configuring NuGet behavior".  It does not however state how you provide the URLs as a list.  It is very important to know how the URLs should be separated, whether by commas, spaces, semicolons, etc.  

As of the time of writing, I cannot get this switch to work with multiple sources, as I do not know how to present this "list" of URLs.  Further guidance would be appreciated, along with a matching update to the documentation.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1a3a03ff-44be-a544-a9ae-baf7f7cc6989
* Version Independent ID: 3e18cf47-ee8f-135e-2b15-6b1a65a95a28
* Content: [NuGet CLI install command](https://docs.microsoft.com/en-us/nuget/tools/cli-ref-install#feedback)
* Content Source: [docs/tools/cli-ref-install.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/master/docs/tools/cli-ref-install.md)
* Product: **nuget**
* GitHub Login: @karann-msft
* Microsoft Alias: **karann**

**Comment by odendoak** [comment]
I have the same problem finding out what and how to provide a "list" as a CLI argument.

It looks like it is separated by semicolon:
https://github.com/NuGet/docs.microsoft.com-nuget/blob/master/docs/tools/cli-ref-restore.md#examples

**Comment by Mikejo5000** [comment]
Looks like doc needs to be updated with fix from @odendoak
