### ISSUE TITLE
Search Query response params does not list `@type` but sample response does

### ISSUE THREAD

**Issue by Phrohdoh** [NuGet/docs.microsoft.com-nuget#960]
The [search result](https://docs.microsoft.com/en-us/nuget/api/search-query-service-resource#search-result) table does not mention a `@type` property but the [sample response](https://docs.microsoft.com/en-us/nuget/api/search-query-service-resource#sample-response) has it (always with the value `"Package"`).

Either the table should be updated to include this property and valid values or this property should be removed from the sample response.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 289ebebf-7c50-531f-f560-952c5ad8a406
* Version Independent ID: 43ba59a2-e8b7-6ca6-6a2d-bf2cf83fc0a8
* Content: [Search, NuGet API](https://docs.microsoft.com/en-us/nuget/api/search-query-service-resource)
* Content Source: [docs/api/search-query-service-resource.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/master/docs/api/search-query-service-resource.md)
* Product: **nuget**
* GitHub Login: @joelverhagen
* Microsoft Alias: **jver**

**Comment by Mikejo5000** [comment]
Looks like you will always get "Package" for @type, since the API only searches for packages. If you have additional information on this, please re-open.

**Comment by Phrohdoh** [comment]
Can we add that to the docs I linked to?
That's the main issue here.

**Comment by joelverhagen** [comment]
The observe client does observe this field. It should be removed from the sample instead of added to the docs.

**Comment by Phrohdoh** [comment]
`@id` should probably be removed from the sample, too.

**Comment by joelverhagen** [comment]
Yes, totally agreed. The underlying "design" when I wrote the API docs was to match the current implementation but only mention what the client uses. This had a couple of exceptions (.nuspec in flat container -- not used by client, relist endpoint -- not used by client) but for cases like this where metadata is not really adding any customer value we should remove it from the samples and not mention it in the docs.

**Comment by Mikejo5000** [comment]
Updating doc
