### ISSUE TITLE
Reason to use @ sign for ID and Type

### ISSUE THREAD

**Issue by satish860** [NuGet/docs.microsoft.com-nuget#961]
Little bit surprised the to @Id in character as the field. Is that any best practices. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d0b2ec4d-76e7-1c04-098c-99ea98676866
* Version Independent ID: 3cb2eaa8-3101-dc2e-b298-5c0d12a830be
* Content: [Service Index, NuGet API](https://docs.microsoft.com/en-us/nuget/api/service-index)
* Content Source: [docs/api/service-index.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/master/docs/api/service-index.md)
* Product: **nuget**
* GitHub Login: @joelverhagen
* Microsoft Alias: **jver**

**Comment by loic-sharma** [comment]
Yes, this is intentional as NuGet v3 APIs follow the JSON-LD format: https://en.wikipedia.org/wiki/JSON-LD

**Comment by satish860** [comment]
Thanks and that's great approach
