### ISSUE TITLE
Document 'ref' folder

### ISSUE THREAD

**Issue by KristianWedberg** [NuGet/docs.microsoft.com-nuget#962]
Please document how and when a 'ref' folder is used for providing reference assemblies, especially when AnyCPU 'ref' assemblies must be provided with both x86 and x64 assemblies in the 'runtimes' folder.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f35f4267-e5e3-ddcf-d3e4-479fb233ce9f
* Version Independent ID: 6d49d66f-f777-7e44-3a45-723e3ad09a59
* Content: [How to create a NuGet package](https://docs.microsoft.com/en-us/nuget/create-packages/creating-a-package)
* Content Source: [docs/create-packages/Creating-a-Package.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/master/docs/create-packages/Creating-a-Package.md)
* Product: **nuget**
* GitHub Login: @karann-msft
* Microsoft Alias: **karann**

**Comment by Mikejo5000** [comment]
Appears to be fixed in #7316
