### ISSUE TITLE
nice explanation

### ISSUE THREAD

**Issue by rsaugier** [NuGet/docs.microsoft.com-nuget#963]
This ia helpful for people struggling with NUGET with "old" TFS versions and Build Process Templates.
However, having to commit Nuget.exe is clearly an ugly workaround to modifying the template (modifying the WF template is so inconvenient compared to simply editing a msbuild file).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: da5022dd-bd05-1a9b-82cb-ea4578c2a2d7
* Version Independent ID: 6c908776-730d-97bd-2e09-4c2e7a3f0531
* Content: [Walkthrough of NuGet Package Restore with Team Foundation Build](https://docs.microsoft.com/en-us/nuget/consume-packages/team-foundation-build)
* Content Source: [docs/consume-packages/Team-Foundation-Build.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/master/docs/consume-packages/Team-Foundation-Build.md)
* Product: **nuget**
* GitHub Login: @karann-msft
* Microsoft Alias: **karann**

**Comment by CamSoper** [comment]
Thanks for the feedback! Passing it along to the product team.
