### ISSUE TITLE
Package references now stored in the csproj?

### ISSUE THREAD

**Issue by jcaillon** [NuGet/docs.microsoft.com-nuget#975]
Hello,

Regarding https://docs.microsoft.com/en-us/nuget/what-is-nuget#tracking-references-and-restoring-packages, i think the documentation fails to mention that the list of packages for a project are now stored in the new csproj format.

Best regards

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bd0c2ac7-8837-d4fd-955b-6a5b261592f3
* Version Independent ID: 4c62f271-70ea-8537-f670-b59bb702c4c0
* Content: [What is NuGet and what does it do?](https://docs.microsoft.com/en-us/nuget/what-is-nuget#tracking-references-and-restoring-packages)
* Content Source: [docs/what-is-nuget.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/master/docs/what-is-nuget.md)
* Product: **nuget**
* GitHub Login: @karann-msft
* Microsoft Alias: **karann**

**Comment by gosali** [comment]
Hello @karann-msft

Can you check on this issue?

Thanks!

**Comment by karann-msft** [comment]
@jcaillon if you read further, you'll see we talk about packages.config and package reference where talk about where these references are recorded.
