### ISSUE TITLE
You might still have a problem with VS

### ISSUE THREAD

**Issue by Rod-in-NM** [NuGet/docs.microsoft.com-nuget#983]
I have been struggling with this issue. I wasn't able to check in the project into TFVC. I talked with our TFS admin. He said that even though I had manually deleted the packages folder, VS 2017 still thought that the packages folder existed, at least as a part of the solution. I had to Undo packages and all of the files under it, before VS would let me check it in.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d965aea9-a6cc-06da-a347-6e8c89458c98
* Version Independent ID: 6775f211-f4b6-6d0c-6f2e-6664b3e9721e
* Content: [NuGet Packages and Source Control](https://docs.microsoft.com/en-us/nuget/consume-packages/packages-and-source-control#omitting-packages-with-team-foundation-version-control)
* Content Source: [docs/consume-packages/Packages-and-Source-Control.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/master/docs/consume-packages/Packages-and-Source-Control.md)
* Product: **nuget**
* GitHub Login: @karann-msft
* Microsoft Alias: **karann**

**Comment by karann-msft** [comment]
Issue moved to [NuGet/Home #7127](https://github.com/NuGet/Home/issues/7127) via [**ZenHub**](https://www.zenhub.com/)
