### ISSUE TITLE
It will require admin rights

### ISSUE THREAD

**Issue by vivekwaghmare** [NuGet/docs.microsoft.com-nuget#984]
On some installations specially in enterprise setup of Domain(active directory) nuget.exe may not work correctly if not ran with admin rights. I was expecting it to be documented. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fd704fe8-fd6e-ba7f-6021-15f280657f4d
* Version Independent ID: dc047102-284f-ad70-99ee-dac5be511392
* Content: [NuGet CLI sources command](https://docs.microsoft.com/en-us/nuget/tools/cli-ref-sources)
* Content Source: [docs/tools/cli-ref-sources.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/master/docs/tools/cli-ref-sources.md)
* Product: **nuget**
* GitHub Login: @karann-msft
* Microsoft Alias: **karann**

**Comment by karann-msft** [comment]
@vivekwaghmare what is the scenario? Can you provide steps to repro the issue?

**Comment by karann-msft** [comment]
Issue moved to [NuGet/Home #7128](https://github.com/NuGet/Home/issues/7128) via [**ZenHub**](https://www.zenhub.com/)
