### ISSUE TITLE
Where is NuGet.Build.Tasks.Pack.targets

### ISSUE THREAD

**Issue by ericlemes** [NuGet/docs.microsoft.com-nuget#986]
If I'm building a MSBuild script from scratch, will be good to have the documentation about how to find the .dll and where is the official location for the targets file.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 099102e8-c320-ef50-6821-57519684dc98
* Version Independent ID: 1523dac4-419d-613d-2497-4062f9efd358
* Content: [NuGet pack and restore as MSBuild targets](https://docs.microsoft.com/en-us/nuget/reference/msbuild-targets)
* Content Source: [docs/reference/msbuild-targets.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/master/docs/reference/msbuild-targets.md)
* Product: **nuget**
* GitHub Login: @karann-msft
* Microsoft Alias: **karann**

**Comment by mhutch** [comment]
They're in the NuGet.Client repo: [NuGet.Build.Tasks.Pack.targets](https://github.com/NuGet/NuGet.Client/blob/dev/src/NuGet.Core/NuGet.Build.Tasks.Pack/NuGet.Build.Tasks.Pack.targets)

**Comment by Nirmal4G** [comment]
If you're looking for the installed location within the system drive, here it is:

Visual Studio 15 ships a local .NET Sdk and Pack targets with the .NET Core 1.x Tools workload.

`%ProgramFiles(x86)%\Microsoft Visual Studio\2017\Enterprise\MSBuild\Sdks\`

Visual Studio 16 uses the one that comes with the .NET Core SDK.

`%ProgramFiles%\dotnet\sdk\<version>\Sdks\`

But if you want to use it in your MSBuild props and targets, you can use the property `$(MSBuildSdksPath)` to get the location of the SDKs. This property is basically `$(MSBuildExtensionsPath)\Sdks`.

This property can also be overriden by an Environment variable of the same name. See dotnet/cli#4884

**Comment by karann-msft** [comment]
@ericlemes - take a look at this - https://docs.microsoft.com/en-us/nuget/create-packages/creating-a-package-msbuild#add-the-nugetbuildtaskspack-package

Does this help?

**Comment by karann-msft** [comment]
I assume it helped. If not please reopen the issue.
