### ISSUE TITLE
Pack command does nothing

### ISSUE THREAD

**Issue by irongut** [NuGet/docs.microsoft.com-nuget#987]
The Pack command does nothing except tell me my build is up to date. Only if I Clean the solution first will the Pack command actually create a Nuget package. Since any library will have been built at least once during testing this is very annoying behaviour and the workaround is not obvious for anyone who hasn't experienced the issue before.

**Comment by karann-msft** [comment]
Issue moved to [NuGet/Home #7227](https://github.com/NuGet/Home/issues/7227) via [**ZenHub**](https://www.zenhub.com/)
