### ISSUE TITLE
My S-8

### ISSUE THREAD

**Issue by Deano123** [NuGet/docs.microsoft.com-nuget#988]
Why is my S-8 always shutting off for no reason at all? Not always, but more than I like the screen just goes off!!!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 87bb0093-2809-50d2-f673-075530220d3d
* Version Independent ID: 2c0bb2fa-4df9-f8db-a5cf-f7d974b637d4
* Content: [Introductory Guide to Using NuGet Packages Through the dotnet CLI](https://docs.microsoft.com/en-us/nuget/quickstart/install-and-use-a-package-using-the-dotnet-cli)
* Content Source: [docs/quickstart/install-and-use-a-package-using-the-dotnet-cli.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/master/docs/quickstart/install-and-use-a-package-using-the-dotnet-cli.md)
* Product: **nuget**
* GitHub Login: @karann-msft
* Microsoft Alias: **karann**

**Comment by rrelyea** [comment]
Not a NuGet issue. Closing.
