### ISSUE TITLE
Please bring back "Migrating to Automatic Package Restore"

### ISSUE THREAD

**Issue by StephenCleary** [NuGet/docs.microsoft.com-nuget#993]
Removed here: https://github.com/NuGet/docs.microsoft.com-nuget/pull/536/files#diff-a0afd8293acb47ac599478b3653aeb5eL228

Please at least bring back the steps:

1. Close Visual Studio.
2. Delete `.nuget/nuget.exe` and `.nuget/NuGet.targets`.
3. For each project file, remove the `&lt;RestorePackages&gt;` element and any reference to `NuGet.targets`.

as well as the steps on testing the migration:

1. Remove the `packages` folder from the solution.
2. Open the solution in Visual Studio and start a build.
3. Automatic restore should download and install each dependency package, without adding them to source control.

These migration steps are old, but still necessary. I literally used them today, and it took forever to find them.

The pull request comments state "There is no more migration scenario", which is incorrect. At least, Visual Studio is certainly not migrating these automatically, so a manual migration scenario still exists. Also, "Several blog posts talk about how we (msft) have been giving the wrong guidance dating as far back as the 2014. http://blog.davidebbo.com/2014/01/the-right-way-to-restore-nuget-packages.html https://www.xavierdecoster.com/post/2014/03/06/migrate-away-from-msbuild-based-nuget-package-restore.html" - but neither of those blog posts say the guidance is wrong; in fact, they do *not* document how to do the migration - they only emphasize that the migration should be done and point to this exact migration documentation (https://docs.nuget.org/docs/workflows/migrating-to-automatic-package-restore -&gt; https://docs.microsoft.com/nuget/consume-packages/package-restore#migrating-to-automatic-restore), which has now been deleted. Please bring it back.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a3b20c46-c5f1-3a2a-738d-8aa8e69cf10c
* Version Independent ID: 7055e752-859b-6106-6802-70010d0305d9
* Content: [NuGet Package Restore](https://docs.microsoft.com/en-us/nuget/consume-packages/package-restore)
* Content Source: [docs/consume-packages/Package-Restore.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/master/docs/consume-packages/Package-Restore.md)
* Product: **nuget**
* GitHub Login: @karann-msft
* Microsoft Alias: **karann**

**Comment by RobHudson72** [comment]
Agreed.  The migration steps are essential documentation.  

I ran into this issue today, on a project created only 2 years ago.

Please restore this documentation.

**Comment by Indigo744** [comment]
Same boat here. We had an old solution and couldn't find the migration information. After a while, I noticed this issue at the bottom and found how to... Btw thanks @SpaceShot for the Archive.org link.

So much time wasted.

**Comment by karann-msft** [comment]
@Mikejo5000 - can you please take a look at this one.

**Comment by Mikejo5000** [comment]
@karann-msft Yes, thanks, I'll take a look at that.

**Comment by Mikejo5000** [comment]
Update is in #1525. Please take a look; I needed to add some context for this content.
