### ISSUE TITLE
Clarify that props and targets assets will not be imported through transitive dependencies

### ISSUE THREAD

**Issue by geeeyetee** [NuGet/docs.microsoft.com-nuget#997]
The phrase "_as can projects that consume AppLogger_" in the following sentence is incomplete and may mislead some developers.

> AppLogger can consume the targets and props from Contoso.Utility.UsefulStuff, as can projects that consume AppLogger.

The sentence is in the section "_Controlling dependency assets_" on the "_Package references (PackageReference) in project files_" page. The following references detail the fact that targets and props can be made to `Import` to projects that directly consume a package, but not to projects that indirectly (transitively) consume a package.

- https://github.com/NuGet/Home/issues/6934 "_Transitive PackageReference packages do not contribute build logic_"
- https://github.com/NuGet/Home/issues/6091 "_Change the default behavior of build dependency asset to transitive_"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ff707668-94d6-25a5-9139-b18cc1b6b446
* Version Independent ID: 494847b9-4894-0beb-7ffa-39a2359999fa
* Content: [NuGet PackageReference format (package references in project files)](https://docs.microsoft.com/en-us/nuget/consume-packages/package-references-in-project-files#controlling-dependency-assets)
* Content Source: [docs/consume-packages/Package-References-in-Project-Files.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/master/docs/consume-packages/Package-References-in-Project-Files.md)
* Product: **nuget**
* GitHub Login: @karann-msft
* Microsoft Alias: **karann**

**Comment by nkolev92** [comment]
This is only by default. 
Package authors can build packages correctly to make their packages bring in the transitive dependencies.

**Comment by geeeyetee** [comment]
@nkolev92 - How can a project **`Import`** a `.props` or `.targets` file that is contained in a transitively-referenced `PackageReference`?

**Comment by nkolev92** [comment]
Say you have the following:

Project 1 -> Package A -> Package B, where Package B has targets. 

When building Package A, the author of Package A can choose to allow the Package targets to flow transitively. 

Package A could be built with Package B as a reference like this:
> <PackageReference Include="B" PrivateAssets="content;analyzers"/>

The default PrivateAssets value is `build;content;analyzers` per https://docs.microsoft.com/en-us/nuget/consume-packages/package-references-in-project-files#controlling-dependency-assets

**Comment by geeeyetee** [comment]
@nkolev92 - Thanks for your reply-- it crossed path with my "EDIT" above. Please let me know if that clarification makes sense to you and let me know if it is correct. Based on my own experience/testing and research over the last couple of days, I believe it is.

**Comment by geeeyetee** [comment]
So in your example, if `PrivateAssets` is set to `none` Project 1 will theoretically have access to the targets files, it will not import them.

**Comment by geeeyetee** [comment]
... whereas the project for  Package A will import the targets.

**Comment by nkolev92** [comment]
>  Project 1 will theoretically have access to the targets files, but it will not import them.
I wouldn't say it has access, but you are correct, it won't import them.

**Comment by bording** [comment]
>I wouldn't say it has access, but you are correct, it won't import them.

@nkolev92 Are you sure about that? I've definitely authored a package that has package reference with `PrivateAssets=none`, and when projects consume that package, they definitely get the props/targets of the transitively referenced packages in their nuget.g.props/nuget.g.targets file.

**Comment by karann-msft** [comment]
Issue moved to [NuGet/Home #7226](https://github.com/NuGet/Home/issues/7226) via [**ZenHub**](https://www.zenhub.com/)

**Comment by nkolev92** [comment]
@bording 
It will have access if it's referencing a package.
It won't if it's referencing a project. 
The example got weird.

Namely:
Project1 -> (PackageReference) PackageA built with PrivateAssets=none -> PackageB with props/targets - works

Project1 -> ProjectReference to PackageA's project that has a PR with PrivateAssets=none -> PackageB with props/targets - works

**Comment by bording** [comment]
Sorry if I'm just being dense, but I'm quite understanding the scenario yet.

You say that both your examples work (though it's not clear what "PR" means in the second example).

What is an example where it wouldn't work?

**Comment by nkolev92** [comment]
That's by bad @bording thanks for calling it out. 

I wrote the first scenario and the copied it and amended it, but didn't change the most important part of it.

**Comment by bording** [comment]
Ok, that makes more sense!

So it's a ProjectReference that won't allow the the props/targets to transitively apply? Why is that? Can you add a property to the ProjectRefernece to alter that behavior?
